### ISSUE TITLE
Testing fresh 1.2 RC1

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1002]
Fresh 1.2 RC1

On dashboard I see: (safety warnings)
Failed to retrieve http://forums.modx.com/board.xml?board=295 

![1](https://cloud.githubusercontent.com/assets/523389/20687711/dff78d30-b5bd-11e6-91dc-af4b3624321c.jpg)

**Comment by fourroses666** [comment]
@dmi3yy  

This is reverted?
https://github.com/modxcms/evolution/pull/940

The font-sizes are not correct :(

**Comment by dmi3yy** [comment]
Why not correct?  

13 very good for codemirror   

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 29 ноября 2016 г. в 00:07, Marc написал:

**Comment by fourroses666** [comment]
Well at least tinymce skin needs different font-size;

https://github.com/modxcms/evolution/commit/98bc1d5c606a1d04d6fa3913b4dae4c5884c49ed#diff-05ee0a4051d60a877311b5883db654e1

![x](https://cloud.githubusercontent.com/assets/523389/20688238/4a71c0ac-b5c0-11e6-9059-578a298c86b4.jpg)

**Comment by pmfx** [comment]
I disagree. TineMCE font-size is very good. Easily readable and reflects most of modern websites typography.

**Comment by fourroses666** [comment]
But shouldn't all fonts be the same size?
![font](https://cloud.githubusercontent.com/assets/523389/20688631/f481eba2-b5c1-11e6-8135-542669f808ad.jpg)

**Comment by fourroses666** [comment]
Hmm, weird. Fresh install, just wanted to give admin an image and when saving:
E-mail address doesn't seem to be valid!

It seems the emailaddress is blank.

**Comment by fourroses666** [comment]
I don't see any diffenrence between textarea and textarea (mini)
Is it different?
![mini](https://cloud.githubusercontent.com/assets/523389/20689253/a494f8fc-b5c4-11e6-9495-5a7128af910b.jpg)

**Comment by Deesen** [comment]
Seems not.. maybe some old relict.

**Comment by Deesen** [comment]
Still "Failed to retrieve" as per your initial post?

**Comment by fourroses666** [comment]
On the fresh install one it does. 
Also did an upgrade 1.1 version with yams. It does work there. The upgrade went ok beside tinymce. Had to select none and then tinymce as text editor on config tabs

**Comment by fourroses666** [comment]
Ah and needed to remove htaccess in cache folder! No images visible on the upgraded one

**Comment by fourroses666** [comment]
Oops on mobile clicked close. Need coffee

**Comment by fourroses666** [comment]
if you would like to see whats going on with the RSS (feed) I have send an login @Deesen

**Comment by Deesen** [comment]
Ok but have not received anything yet.

**Comment by fourroses666** [comment]
Oh I have used info@ now. Else you found a bug :)

**Comment by Deesen** [comment]
Or maybe someone else enjoys now access ;-). I receive emails on info@, no problems here.

Issue should be fixed. I guess there is problem with forums.modx.com redirecting to https or so.

**Comment by fourroses666** [comment]
Oke cool :)
There also is an issue when a site has https. The module Store don't list their items when using https://www.site.com/manager.

I don't know if I'm the only one who noticed it.

**Comment by dmi3yy** [comment]
Update to 1.2RC2 )

**Comment by fourroses666** [comment]
@dmi3yy that works!

Did an update RC1 to RC2.
We might need to add vertical-align top? This font-size of the content field needs to be bigger and Arial:

`font-family: Arial,Helvetica,sans-serif; font-size: 13px;`

**Comment by fourroses666** [comment]
Ah never mind the content styling, I somehow have a custom css for that I wasn't aware of.

**Comment by yama** [comment]
@fourroses666 
https://github.com/modxcms/evolution/blob/v1.2RC2/manager/media/style/MODxRE2/style.css#L40-L42
How is this solution? This is a specialized solution for Japanese fonts.

**Comment by fourroses666** [comment]
That will use Arial too like line 31.

Its oke, I probably will use my own style because I'm very picky on this kind of stuff. 
It needs to be the same style everywhere in my eyes. 
_Arial 10pt (yes for printing, so not px) looks the best / best readable on iMac._
