### ISSUE TITLE
help needed for upgrade

### ISSUE THREAD

**Issue by wishbone-design** [modxcms/evolution#1003]
from evo 1.04. Snippets have been written from third party, but I think no core changes (not sure).
Site has been being hacked permanently the last days so I don't know if clean. (at the moment it's quiet).

**Comment by bossloper** [comment]
No disrespect, but should this sort of request really be on the/a forum rather than this issues list?

To all - There seems to be a general lack of 'forum' chat for Evo at the moment which ends up posted here and is diluting the GitHub issues list. How to solve?...

**Comment by fourroses666** [comment]
Maybe Slack for the time being?

**Comment by wishbone-design** [comment]
sry if this is not the right place for my request.
I had really great help here.

**Comment by bossloper** [comment]
Didn't mean to sound negative.. sorry:)
I suppose I'm really just sounding out as to how the community forum could be kicked into life again. Back in the day it was THE place to go for help.

**Comment by modxuser** [comment]
@bossloper I sent @wishbone-design here, because of exactly the problem you have already mentioned - the lack of support via the MODX forum

This is an on-going issue, that people posting in the FOrum are either not get answers to their problems or they are waiting so long that they simply give up.

The posts should be deleted from Github as soon as they are answered, that way the board won't get overloaded

**Comment by wishbone-design** [comment]
> The posts should be deleted from Github as soon as they are answered, 
no, pls not... precious information, could be of use for others, and I myself couldn't use all of it yet.

**Comment by bossloper** [comment]
I think deleted was the wrong word. They need to be closed as soon as resolved. Then still part of a searchable archive.

**Comment by fourroses666** [comment]
Had some .php files in the /manager folder too, for example " /media/style/MODxRE2/ ".
Would advise to make a copy and update. (whole manager folder can be replaced and only upload you config.inc.php file.)

**Comment by wishbone-design** [comment]
I sort of need commercial help so if something goes wrong ... it's a live site

**Comment by dmi3yy** [comment]
1. Do backup   upgrade and se if all good 
2. use http://www.syntevo.com/smartsynchronize/   your site and new 1.0.4  can see changes of core files. 
3. for not die live site  need clone on test server, upgrade and replace by new 

if need write dmi3yy@gmail.com i help

**Comment by wishbone-design** [comment]
great thx
but with a testserver, I run into other problems... for me, it doesn't work well

**Comment by fourroses666** [comment]
You could add a subdomain? 
Then after its ok you only have to move the files.

**Comment by Deesen** [comment]
@wishbone-design Could you please outline how big your project is? I mean total filesize of all files in MODX-directory, and size of your latest DB-dump?

**Comment by bossloper** [comment]
As @fourroses666  said you could create your test setup as a sub-domain.
Or if you have trouble with a sub-domain (maybe too many absolute paths) then just get another domain setup on your live server and clone to there. You could use that setup ongoing to test upgrades for any sites and not risk messing up a live site. You would know then it would be the same server environment as the live site (php version etc). Even with a sub-domain you can accidentally overwrite the wrong files if you are not concentrating... I know from experience! :)

**Comment by wishbone-design** [comment]
thank you so much everybody! now I have hope again to continue this site. It's even difficult to get commercial for that because they rather like to do new projects than search for stupid changes and such.
**When I have enough quiet time**, I will try to upgrade myself to learn it. With all of you in the back I'll dare ;-)
@Deesen The project is small, the web files 200MB and the database 2 MB. If I don't manage, I'll ask you, thx.
@bossloper I will try the extra domain setup on the server (once I found out how)

**Comment by wishbone-design** [comment]
merry christmas to everybody!
I'd like to do the upgrade niw, as the time is calm...
@bossloper I wanted to do it via your suggested second domain set-up, not sure what you meant by it?

**Comment by bossloper** [comment]
Merry Christmas!

I was just suggesting that for complete separation from any existing live site you could create a clone of the site on a separate domain name, but it would essentially work the same as creating a sub-domain.

Clear the cache on the existing site then export the database and files from your live site. Import them into the new 'temporary' domain. You would at minimum need to edit the manager/includes/config.inc.php for the new database login and change the site_sessionname to another unique string. Then you might need to alter your .htaccess if it has domain specific settings. Then log in to manager and clear cache again for good measure. In system config you would need to reset the 'File Manager path' and 'File base path' fields. If the site works ok then you can maybe back that up before attempting an upgrade on it, then you could roll back if there were issues and you wanted to retry it again.

**Comment by wishbone-design** [comment]
thx! on christmas ...
only I don't know what you meanby "temporary" domain or how to set it up

**Comment by bossloper** [comment]
By temporary domain I just mean a new site/domain. But if you do not have tools as part of your existing site 'control panel' to export the database then this may be a none starter!

**Comment by Deesen** [comment]
To export/import SQL-tables this tool is simple & great http://www.phpmybackuppro.net/ . You need to

- upload it to original domain
- setup DB-credentials
- make DB-backup
- copy its directory to new/temporary domain
- edit the SQL-backup file and change "USE `db_name`" at beginning to your new DB-Name
- eventually change the config-file if you have to use different user/password for DB at new/temporary server
- import backup to new DB

**Comment by wishbone-design** [comment]
sry yes, I can export the database and the web space. Only no second domain environment, which would have been great to just try out, if it just goes smoothly... but I dare it doen't go back smoothly if I just try on the live site.

**Comment by bossloper** [comment]
Then it is really your call on cost of each option vs risk of site being down for a time and how forgiving your client will be!:

If you cannot set up a local test server with same basic environment:
- Attempt to setup a sub-domain for testing.
- Buy a second domain environment to experiment with 
Or:
- Pay someone for 'commercial help'.
- Risk it by upgrading the live site and fixing on the fly.
If your live site has an easy backup/restore facility (which is sounds like it does) you could try an upgrade 'overnight' and roll back if it fails badly. But you need to be confident about the restore working if you have never used it before.

**Comment by Deesen** [comment]
Another tip might be experimenting with a portable full-featured webserver / localhost like http://www.uniformserver.com/ ... it provides Apache, PHP and MySQL / phpMyAdmin out of the box without installation and can be put on USB-Stick. There you can experiment with 100 MODX-installations without hurting anybody.

**Comment by wishbone-design** [comment]
Thank you for all your tipps which I tried!
I've used my old xampp installation and managed to get the current version of my website running.
Then installed new modX - ok.
Inserting my data in database and web - no effect. The default index.php is still shown.
Could it be a database version problem?
The new install config says: $database_type = 'mysqli';
also pointed me to use "SET NAMES" instead of "CHARACTER SET"
THe site doesn't appear at all with the mentionend UniserverZ running (endless loading, showing nothing) - database version 5.6.35
But it is running with my xampp mysql version 5.1.41
The live mysql version is 5.6.19

**Comment by Deesen** [comment]
Hmmm.. "Default index.php is shown"? You mean the default one when starting server? Did you set "Apache Root-Folder" to your MODX root-directory?

You can also try to set `127.0.0.1` instead of `localhost` as your DB-host.

**Comment by wishbone-design** [comment]
now I understand. localhost is correct directory, other sites show normal.
I dropped the prefix modx_ during installation, because it tolf me, there already was a prefix _modx... 
I must empty the old database data before installing?

**Comment by dmi3yy** [comment]
if new install you can use other prefix if use same db


От 27 декабря 2016 г. в 16:48:01, wishbone-design (notifications@github.com)
написал:

now I understand. localhost is correct directory, other sites show normal.
I dropped the prefix modx_ during installation, because it tolf me, there
already was a prefix _modx...
I must empty the old database data before installing?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1003#issuecomment-269335210>,
or mute the thread

**Comment by wishbone-design** [comment]
@dmi3yy but I want to import my data, and it is with prefix. Shouldn't it override the install data?

**Comment by wishbone-design** [comment]
what is the approach for updating:
Clear database, empty all contents - or delete all tables?
Install new version modX
Import old database, overriding new snippets and everything
?

**Comment by bossloper** [comment]
No db clearing needed. Have a working site. upload/overwrite the new version files. Run the install.

**Comment by wishbone-design** [comment]
the new install doesn't let me use the same prefixes

**Comment by bossloper** [comment]
If you upload the new files over the current install then it should say 'existing install found do you want to update?'

**Comment by wishbone-design** [comment]
didn't get that option. Deleted all files in the webspace because of hack (not identifyable which files could have been hacked)

**Comment by bossloper** [comment]
You need to leave at least the /manager/includes/config.inc.php in place so the install picks it up as an existing install.

**Comment by wishbone-design** [comment]
ok got the option
Now wants me to set an admin password - but no option for doing that
![image](https://cloud.githubusercontent.com/assets/3841564/21510578/70a65c56-cc95-11e6-87cb-d29a81df8335.png)
Cleared erverything, rebootet the machine, installed for new several times, also in new directory - no option for setting the admin password.
If choosing normal upgrade install, I can't choose the prefix, and the tables are doubled. Also, no admin password.
If I call the root index, I get the mesage:
"ERROR: Too many forward attempts!
The request could not be completed due to too many unsuccessful forward attempts."
That was once when I went back with the browser and reloaded.
But where does the system store that? how to make it forget?

**Comment by Deesen** [comment]
Just guessing: Root-Index gives "Too many forward attempts"? Maybe you are using .htaccess from your live-server which has rules that are not compatible with your localhost, resulting in infinite redirect-attempts? Maybe rename that file to test if it helps.

**Comment by wishbone-design** [comment]
Set up everything clean and new, and it now works! Manager, resources, snippets - all there!
Issues:
- still showing v 1.04, though new UI ;-)
- where have the settings gone for adjusting base paths in the configuration
- ditto is not being executed, as aren't other snippets (maybe because of the wrong paths?)
- then I suddenly got a mysql error: "#2003 - Can't connect to MySQL server on 'localhost' (10055) " but I can access directly to my database (via URL). Only the phpmyadmin home is not accessible
big thx as always!

**Comment by wishbone-design** [comment]
phpmyadmin working again. 
besides the above mentioned, I can't save anything in the backend.

**Comment by dmi3yy** [comment]
check modSecure on the server




От 29 декабря 2016 г. в 22:43:43, wishbone-design (notifications@github.com)
написал:

phpmyadmin working again.
besides the above mentioned, I can't save anything in the backend.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1003#issuecomment-269690562>,
or mute the thread

**Comment by wishbone-design** [comment]
"check modSecure on the server"
where? how?
It's been running with the old version of evo

**Comment by wishbone-design** [comment]
installed again, chose collation "utf8:swedish_ci" as proposed, now the database_type stays mysql (not mysqli)
with the same alert as above screenshot "you must add a password to the admin user account".
The manager doesn't open, but throws the error:
"Warning: file_get_contents(D:/xampp/htdocs/pelznertest/manager/media/style/common/login.tpl) [function.file-get-contents]: failed to open stream: No such file or directory in D:\xampp\htdocs\pelznertest\manager\includes\accesscontrol.inc.php on line 156"

**Comment by Deesen** [comment]
It seems /manager/media/style/common/login.tpl is not existing or not readable?

**Comment by wishbone-design** [comment]
sry that was may bad. I forgot to copy some files into the manager dir.
Now I'm again / still at the point, that I can't complete the install because of this message 
![image](https://cloud.githubusercontent.com/assets/3841564/21617138/0c3532ec-d1e5-11e6-991a-1da6b174479c.png)
so that the database is not being updated

**Comment by wishbone-design** [comment]
Since I don't get any further with my local install, I had this great idea of running a second modX in a subdirectory, with a second database.
> subdir/install runs the top (live) installation ^^
