### ISSUE TITLE
Execution of a query to the database failed — Table 'new_modx.modx_active_user_sessions' doesn't exist

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1006]
http://modx.im/blog/addons/4853.html#comment39098

« MODX Parse Error »
Execution of a query to the database failed — Table 'new_modx.modx_active_user_sessions' doesn't exist
SQL > REPLACE INTO `new_modx`.`modx_active_user_sessions` (internalKey, lasthit, ip) VALUES (1, 1480394460, '127.0.0.1')

**Comment by Deesen** [comment]
For me when I delete all 3 active_user-tables like

![before-upgrade](https://cloud.githubusercontent.com/assets/8569221/20705520/89970fae-b623-11e6-9cb4-33d4d6d88a17.png)

and I run upgrade, they are all back up again:

![after-upgrade](https://cloud.githubusercontent.com/assets/8569221/20705543/98751d90-b623-11e6-921f-1119a83693f5.png)

If I upgrade without deleting, they are truncated so the "DROP TABLES" before "CREATE TABLE" also works for me https://github.com/modxcms/evolution/blob/develop/install/setup.sql#L7-L37 

I can only guess some MySQL-errors are ignored, like missing "DROP TABLES"-permission maybe.

**Comment by dmi3yy** [comment]
to can reproduse

**Comment by dmi3yy** [comment]
I know  why this bug

if update all files but not run install :)
