### ISSUE TITLE
DocLister 2.3.0 not work orderBy=`tvname ASC`

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1008]
https://monosnap.com/file/5WUdocsnMq5QKYYli7s8KkLoqr3kfC

if use  content name all ok  it tv sql error

**Comment by AgelxNash** [comment]
lol https://github.com/AgelxNash/DocLister/issues/230
Maybe you should send bugreports to DocLister repository, and then use cumulative updates?
