### ISSUE TITLE
MODXupdateNotifer

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1014]
Add to core https://github.com/extras-evolution/MODXupdateNotifer

but need check for php setting for all run ok. and do multilang. 

i think it be great and we can do more but smallest realizes

**Comment by modxuser** [comment]
Would it not be better to add this to the core ?

I think something like this woul be great, especially as the release channel from MODX is pretty much dead now.

I didn't know that 1.2RC1 had been released until 5 minutes ago, so yes, great work

**Comment by dmi3yy** [comment]
Yes its need to core but first need stable work.  
- need check for work  curl, zip, normal permission for files and folders
- add settings for develop or stable version, show only admin or for all
- add multilang  


when all ready then move to core)   

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 29 ноября 2016 г. в 23:38, modxuser написал:

**Comment by Nicola1971** [comment]
@dmi3yy +1 for me, but if we add to the core need some "permission" settings (or add with Evodashboard) , i don't want to show to my users this kind of critical widget

**Comment by Deesen** [comment]
Maybe show version-notice for all (theirfore also the customer) but Upgrade-Button only to Admin.

**Comment by Nicola1971** [comment]
![updateconf](https://cloud.githubusercontent.com/assets/7342798/20765075/33fb7f6c-b731-11e6-9980-0d98418c6f48.jpg)

https://github.com/extras-evolution/MODXupdateNotifer/pull/7

**Comment by dmi3yy** [comment]
add in 1.3 as Updater plugin
