### ISSUE TITLE
if move site with phx then have bug and we are can't set default path

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1017]
http://take.ms/RX1Vi

or if none phx file.

**Comment by modxuser** [comment]
I didn't realise that that was a bug

I had that each time I moved from localhost to live server, as the path to PHX was different. I always logged into the manager and reset the paths and all was then OK.

But, I no-longer use PHX so don't have that problem anymore LOL

**Comment by dmi3yy** [comment]
its bug with new  filter(phx in core)  
i too no more use PHx  ))  

but someone use  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 30 ноября 2016 г. в 16:28, modxuser написал:

**Comment by MrSwed** [comment]
1. disable phx
2. correct paths
3. enable phx

**Comment by dmi3yy** [comment]
1 need before move )
if гаеук you can do 2 step


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 30 ноября 2016 г. в 16:36, Sergey Davydov написал:

**Comment by MrSwed** [comment]
here 
https://github.com/modxcms/evolution/blob/develop/manager/actions/mutate_settings/tab1_site_settings.inc.php#L137

need catch error..

**Comment by MrSwed** [comment]
https://github.com/modxcms/evolution/issues/623#ref-commit-4e50715

**Comment by yama** [comment]
```
if(is_file(MODX_BASE_PATH . 'assets/plugins/phx/phx.class.inc.php')
```
maybe add this

**Comment by dmi3yy** [comment]
yes

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 5 декабря 2016 г. в 12:19, yamamoto написал:

**Comment by yama** [comment]
It should be same error on the front page, how is it?

**Comment by dmi3yy** [comment]
if frontend no problem )  
go setting and  check MODX_BASE_PATH

but when error in setting in first tab you cant fix MODX_BASE_PATH )  

you see only first tab and error %)  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 5 декабря 2016 г. в 12:28, yamamoto написал:

**Comment by yama** [comment]
![a](https://cloud.githubusercontent.com/assets/73999/20882010/52f853fa-bb22-11e6-8b40-132d18e0dcff.jpg)
hmm...? I do not know well, but it is certainly strange

**Comment by MrSwed** [comment]
I think I need a more accurate verification decision path in general, not specifically relating phx. If the check does not pass, first allow the user to adjust them, implying that the site has been moved

**Comment by dmi3yy** [comment]
no strange  i move site to another host  
but can’t set by default  base_path in settings.  

I  think this help  
http://take.ms/26Vxl


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 5 декабря 2016 г. в 12:39, Sergey Davydov написал:

**Comment by MrSwed** [comment]
@yama 

> if(is_file(MODX_BASE_PATH . 'assets/plugins/phx/phx.class.inc.php'))

no  https://github.com/modxcms/evolution/issues/623#ref-commit-4e50715 was after two tryes, because phx can be renamed, including rename plugin files...

**Comment by MrSwed** [comment]
@dmi3yy 
there are is error occurs
`$modx->invokeEvent('OnParseDocument')` 
before you test path to phx :)

**Comment by MrSwed** [comment]
something like ([proposed logic](https://github.com/modxcms/evolution/issues/1017#issuecomment-264820864))
```
if(!is_file(MODX_BASE_PATH . 'manager/include/config.inc.php')) {
 // promt to correct MODX_BASE_PATH
} else {
// existing output configuration.
}

?

**Comment by yama** [comment]
> but can’t set by default base_path in settings.

hmm...?

**Comment by MrSwed** [comment]
@yama https://github.com/modxcms/evolution/issues/1017#issuecomment-264823054

**Comment by Deesen** [comment]
Or maybe replacing invokeEvent('OnParseDocument') with check for phx-plugincode and disabled != 1

    // Check if PHX is enabled
    $count = $modx->db->getRecordCount(
      $modx->db->select('id', $modx->getFullTableName('site_plugins'), 
      "plugincode LIKE '%phx.parser.class.inc.php%OnParseDocument();%' AND disabled != 1")
    );

    if($count) {
        $disabledFilters = 1;
        echo '<b>'.$_lang['enable_filter_phx_warning'].'</b><br/>';
    }

**Comment by yama** [comment]
its better

**Comment by yama** [comment]
The old version of PHx referred to "rb_base_url". Is that problem?

**Comment by Deesen** [comment]
In my testing-case yes.

**Comment by yama** [comment]
ok, understood. I will fix this issue later

**Comment by yama** [comment]
```
// Check if PHX is enabled
$count = $modx->db->getRecordCount(
  $modx->db->select('id', $modx->getFullTableName('site_plugins'), 
  "plugincode LIKE '%phx.parser.class.inc.php%OnParseDocument();%' AND disabled != 1")
);

if($count) {
    $disabledFilters = 1;
    echo '<b>'.$_lang['enable_filter_phx_warning'].'</b><br/>';
}
```
I thought carefully, I think this fix is smarter.
I think that rb_base_dir needs to be solved as another problem.

**Comment by MrSwed** [comment]
may be better 
```
"plugincode LIKE '%PHxParser%OnParseDocument();%' 
```
?

**Comment by dmi3yy** [comment]
But this check not  work with incorect base_parh. Need check file;) or still have bug

Отправлено с iPhone

**Comment by Deesen** [comment]
@dmitryy But what is you exact error-message? For me the error is

- invokeEvent onParseDocument
- this will eval() plugin-code of PHX
- plugincode starts with include_once ($modx->config['rb_base_dir']), not found
- calling $PHx->OnParseDocument() will cause fatal-error

So avoid invokeEvent should avoid any incorrect base-path at least for PHx? Or do other plugins cause problems OnParseDocument too?

**Comment by yama** [comment]
> But this check not work with incorect base_parh

Is it "base_path", not "rb_base_dir"?

**Comment by MrSwed** [comment]
updated [phx](https://github.com/extras-evolution/PHx) has correct path

**Comment by Deesen** [comment]
Maybe this is a more global solution to check all kinds of plugins? https://github.com/modxcms/evolution/issues/1060#issuecomment-265096880

**Comment by dmitryy** [comment]
@Deesen please write correct @dmi3yy not @dmitryy ;)

**Comment by Deesen** [comment]
Sry :-D

**Comment by MrSwed** [comment]
@Deesen 
first - check [correct path](https://github.com/modxcms/evolution/issues/1017#issuecomment-264820864)
second - check path fo each plugin befor run/invokeevent
