### ISSUE TITLE
login to manager from 2 different browser types gives 'forgot to logout' message

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1024]
e.g.
1) log in to manager from Chrome
2) log in also from Firefox

The second login always presents the message 'Reminder: It seems on <date> you forgot to logout. Please pay attention in future to do so after your work is finished.' 
Presumably to do with them being independent sessions for each browser? Guess not a big deal, though I quite often have multiple browsers running to check website compatibility.

**Comment by Deesen** [comment]
This routine is preparing the reminder: https://github.com/modxcms/evolution/blob/develop/manager/processors/login.processor.php#L257-L258

How to extend it to perfectly catch your situation? If active_user_sessions with same ID exists then show no warning?

**Comment by bossloper** [comment]
"If active_user_sessions with same ID exists then show no warning?"
Yes, or even display a different message indicating something like "you are logged in on multiple devices"?

**Comment by bossloper** [comment]
... which has me thinking (not for 1.2 as it needs to get out there!). But could a login present something like many banks do for a little added security. e.g. 
"you last logged in on <date> from ip address <ip> and browser: <browser>"

**Comment by Deesen** [comment]
Yes or a list of last X logins :+1: . Also your above proposal makes much sense. As well as showed me when a bug...:

When logging out user in Browser A, all locks will be removed, even when Browser B still has elements open for editing. So user will loose all locks even when having elements open for editing in Browser B. Do we really need to add browser session-id to database to avoid this situation?

**Comment by bossloper** [comment]
"Do we really need to add browser session-id to database to avoid this situation?"
- maybe so as it would it also work the other way. Currently if browser A has element open then browser B with same login can also edit the same resource.

**Comment by Deesen** [comment]
But I think this is an advantage, so to be able to open a resource twice. Makes no sense to me to block yourself just because of different browsers.

**Comment by bossloper** [comment]
Maybe from the same browser yes, but from two different browsers is that a step too far? 

Also, however much I suggest to my clients I know some of them share a manager login account so in that case it could be a help.

**Comment by Deesen** [comment]
I think you are right as always ;-). Already working on it :+1:

**Comment by bossloper** [comment]
Still getting the 'forgot to log out' message if I log in from 2 different browser types with the same manager account (i.e. Edge and Chrome). Plus can edit the same resource from both at the same time. Is this still work in progress or a change of thought?

**Comment by Deesen** [comment]
Its like with "lock elements", more complicated than it seemed from beginning, but no change of thought from my side. Too many things to do.

**Comment by bossloper** [comment]
Now the locks and lock cleaning is working smoothly (great work!), is the message: 'Reminder: It seems on you forgot to logout. Please pay attention in future to do so after your work is finished.' needed at all? There is really no problem with staying logged in that I can see?

**Comment by Deesen** [comment]
Well it will at least release locks sooner if users remember using logout-button. Not sure if this is too much "perfectionism" but I think its always good to "softly educate" users get used to press logout (alone for security reasons, to delete session, or whatever might be important OnManagerLogout-event).

Reg. "multiple browser sessions ids", I continued working on the new mechanism yesterday so its not forgotten. But I need some more testings.

**Comment by Deesen** [comment]
If you like to test https://github.com/Deesen/evolution/tree/multi_browser_sid

**Comment by bossloper** [comment]
Season greetings! Great work - Been testing with multiple browsers 1 or more logs etc. 
I just found one issue so far.
If I edit a resource in a browser then have a second tab in the same browser (same manager login) then edit a resource in the second tab the first tab edit becomes unlocked.

**Comment by Deesen** [comment]
Sry, greetings back :-)! Thanks, I found the fix.. did not expect this small change to have this effect. To fix you need to re-run installation/setup.

**Comment by bossloper** [comment]
That seems to have fixed it.

The only other thing I can do to break it is if I edit a resource, then second tab, again same manager account, and edit the same resource so I have 2 tabs editing same resource. Then in one tab go and edit a different resource then the other tab still has an edit open but no lock. Not sure that is an easy one to fix and might not be worth the effort!

Also I like the icon for multi-user on the 'online user' list. It probably needs a 'single user' icon on the other entries to balance the look and alignment of usernames?

**Comment by Deesen** [comment]
I think there is no reliable automatic solution for your first point. We could fill a localStorage-item storing the number of windows open per resource, and control sending unlock-requests.. but this will probably lead to new issues ;-).

And reg. the icon(s), I have no opinion, you guys/madames can decide.

**Comment by bossloper** [comment]
Agreed. It is working well and a great improvement. With the 'auto clean' of stale locks I think it is more than ready for prime-time.
RE: Online user list icons - Yes, don't really mind it just looked a little strange. @Nicola1971 any thoughts? :-)

**Comment by Nicola1971** [comment]
@Deesen @bossloper 

icon does not look good and, most important, this is the "**webuser**" icon.

1) with default **manager user** icon
![1](https://cloud.githubusercontent.com/assets/7342798/21497153/75807634-cc23-11e6-9e27-6c6360b64b8b.png)

2) alternative 2 (lighter version, looks good to me)
![2](https://cloud.githubusercontent.com/assets/7342798/21497165/7eb456bc-cc23-11e6-9ba6-48456cc20804.png)

3) alternative 3 (for a more unique icon, nice for me)
![3](https://cloud.githubusercontent.com/assets/7342798/21497177/8c72c82e-cc23-11e6-97e1-020b7a09a83c.png)

4) alternative 4
![4](https://cloud.githubusercontent.com/assets/7342798/21497181/94a5bf06-cc23-11e6-8779-c3e82714a6c6.png)

**Comment by fourroses666** [comment]
3

**Comment by bossloper** [comment]
I think the idea is there are two different icons as the manager is either a unique logon or if there are multiple browsers with the same manager (different sessions) then these have an icon to represent the 'multiple session' nature of those online sessions.

So it would need something like 2. for a 'normal' logon and 3. for a multi-session logon.... for example.
Think I have that right @Deesen ?

**Comment by Deesen** [comment]
Yes right. And I took that icon because it shows "several people" which is perfect to represent "multiple users". It is just a [CSS-class](https://github.com/Deesen/evolution/commit/8cbb924969f97af009fe5a3a909d8e26f10de004#diff-a9d85231d7481799a7126afc6bf101f8R3498) that will be added to a row so we could also use different color, italic font-style or whatever. I leave that to you if you want to keep icon or remove it. At least the feature is prepared.

**Comment by Nicola1971** [comment]
suggestion: instead a different icon for multiple sessions, just add a different color class - as an alert

![5](https://cloud.githubusercontent.com/assets/7342798/21498261/44f5af54-cc2b-11e6-8e1a-9f0467e8bad1.png)


```
strong.userMultipleSessions:before {
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    color: #d44d4d;
    padding: 0 5px 0 0;
    content:'\f007';
}
``

**Comment by bossloper** [comment]
That would probably do. I guess normally you would try not to rely on colour alone - so as to help site usability regarding colour-blind.

**Comment by Nicola1971** [comment]
@bossloper using **user-circle-o** for normal user and red **user-circle**  for multiple users?

![4aaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/21500986/6a61bd3c-cc44-11e6-9fa3-340a0f1242e5.png)
