### ISSUE TITLE
Feature Request: URL Re-writing

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1030]
I am not sure if this is possible at all, not being a PHPer

I answered a question in the forum ref. dead links and came to the conclusion that when friendly url's are set in the configuration, pages can still be reached in multiple ways, instead of just one.

Also if you set folders to have "/" at the end of the url, they can still be reached in multiple ways.

**Examples:**

"domain.com/alias/" is still reachable via "domain.com/alias" and can also be reached via "domain.com/index.php?id=xx"

If a suffix is set "domain.com/alias/" can also be reached via "domain.com/alias.suffix"

Is it possible that when friendly urls are set, that the pages can only be reached as you expect.

**Example:**

without pre-defined suffix: **domain.com/contact**
with pre-defined suffix: **domain.com/contact.html**

**Comment by Deesen** [comment]
I had to correct it for some SEO-issues where SEO-company insisted on removing every trace of duplicate-content. The 2 links in your example would already be duplicate-content as per their definition.

Maybe we should add a "strict"-parameter to URL-resolving.

**Comment by janniconl** [comment]
On this topic: https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

**Comment by bossloper** [comment]
Doesn't the 'SEO Strict URLs' plugin solve this? 
https://modx.com/extras/package/seostricturls
It does a 301 redirect of urls without a trailing slash as will as the none FURL.

**Comment by yama** [comment]
It is OK with SEO Strict URLs, but this plugin is complicated and expensive to process. Since it works lightly if it is mounted with the core, I will think about it.

**Comment by dmi3yy** [comment]
plugin dont need  

we arre move its to core.  

Setting tab with urls  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 1 декабря 2016 г. в 10:29, yamamoto написал:

**Comment by modxuser** [comment]
To my shame, I must admit, I didn't realise that that is there - sorry, don't like wasting peoples time.

**Comment by modxuser** [comment]
I have just download RC2 to look at the ht.access file ref. strict urls.

I see the following:
```
# Rewrite domain.com -> www.domain.com -- used with SEO Strict URLs plugin
#RewriteCond %{HTTP_HOST} !^$
#RewriteCond %{HTTP_HOST} !^www\. [NC]
#RewriteCond %{HTTP_HOST} (.+)$
#RewriteRule ^(.*)$ http://www.%1/$1 [R=permanent,L] . 
```
I presume this has to be uncommented ?

Also, what happens if you use SSL, as there is only "http" in the last line.

Sorry for my lack of re-write knowledge

**Comment by janniconl** [comment]
@modxuser The code you show us is for rewriting domain.com to www.domain.com. Just for this. Does not have anything to do with the trailing slash (/). There also should be some code for the vice versa (www. to non-www).

And if you use/force SSL you need to fix the http:// part yes, but then you also need more htaccess changes if you want to set it up correctly (https://www.siteground.com/kb/how-to-force-ssl-with-htaccess/ for example).

**Comment by Deesen** [comment]
I used this one

    # Redirect http to https
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

**Comment by modxuser** [comment]
@janniconl I posted that code as it states "used with SEO Strict URLs plugin"

And as @dmi3yy mentioned, the plugin is now in the core, so is the .htaccess info needed ?

I use different code for "www / non www" already, so if you say that that's all it does - I can delete it ?

@Deesen I to have different code for HTTPS:

```
RewriteEngine On
RewriteBase /

RewriteCond %{HTTP_USER_AGENT} ^.*internal\ dummy\ connection.*$ [NC]
RewriteRule .* - [F,L]

RewriteCond %{HTTP_HOST} !^$
RewriteCond %{HTTP_HOST} !^www\. [NC]
RewriteCond %{HTTP_HOST} (.+)$
RewriteRule ^(.*)$ https://www.%1/$1 [R=permanent,L] .

RewriteRule ^(manager|assets)/.*$ - [L]
RewriteRule \.(jpg|jpeg|png|gif|ico)$ - [L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]

RewriteCond %{HTTPS} !^on$
RewriteRule (.*) https://www.DOMAIN.com/$1 [R,L]

RewriteCond %{SERVER_PORT} !=443
RewriteRule (.*) https://www.DOMAIN.com/$1 [R=301,L]
```

**Comment by janniconl** [comment]
`RewriteCond %{HTTPS} !^on$` and `RewriteCond %{HTTPS} off`
and
`RewriteCond %{SERVER_PORT} !=443` and `RewriteCond %{SERVER_PORT} 80`

Both do basically the same afaik. 

See this answer on stackoverflow about how to remove the trailing / via .htaccess: http://stackoverflow.com/questions/21417263/htaccess-add-remove-trailing-slash-from-url/21417551#21417551
````
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)/$ /$1 [L,R=301]
````

**Comment by Deesen** [comment]
I think it would be great to add an optional https-redirect to .htaccess but sure which code is the perfect one to commit.

**Comment by modxuser** [comment]
@Deesen it took me a long time to find the code from above, I tried multiple other solutions, but none worked properly for me.

What I posted above works for me, but may not work for others - I can only presume that different code is required for the different set-ups providers have

So sadly it's probably the case that one solution can't fit all.

@fourroses666 created a similar post, which can be found [here](https://github.com/modxcms/evolution/issues/1033)

**Comment by nick0** [comment]
Hello,

Sorry to dredge up an old thread. I thought it best to ask here given its relevance rather than starting a new issue.

My query is related to htaccess https redirects - specifically relating to redirecting the Evo Manager folder. 

I would like to redirect:
http://www.domain.com/manager/
https://www.domain.com/manager/
http://domain.com/manager/
to:
https://domain.com/manager/

I have got https redirects working for Evo pages - but not the manager address itself - with the following code...

#redirect www to non www
```
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ http://%1/$1 [R=301,L]
RewriteCond %{HTTPS} !on
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
This redirects:
http://domain.com/test
http://www.domain.com/test
https://www.domain.com/test
to:
https://domain.com/test
```

and the opposite...

```
#redirect non www to www
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]
RewriteCond %{HTTPS} !on
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
This redirects:
http://www.domain.com/test
http://domain.com/test
https://domain.com/test
to:
https://www.domain.com/test
```

Friendly URLs are on
End Container URL with Slash = Yes
Use SEO Strict URLs = Yes

Any htaccess ideas or suggestions on how to redirect the manager folder?

Thanks in advance.
