### ISSUE TITLE
Duplicating Elements will allow duplicate elements with the same name

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1034]
Example:
1) Duplicate a snippet and save it.
2) Edit the original snippet and duplicate again.
3) Saving that second snippet duplicate gives a warning that it should have a unique name - but it still saves it.

So looking at snippets there are now two with the exact same name. There seems to be similar issue for all other elements.

EDIT: also when duplicating a TV it is the caption that gets the 'Duplicate of' prefix instead of the TV name.

![untitled](https://cloud.githubusercontent.com/assets/1744687/20797511/e9d19e4c-b7d2-11e6-9cc9-6df2d6602f74.png)

**Comment by Deesen** [comment]
Good find, even when it seems I never had that situation.

**Comment by bossloper** [comment]
I came across it because occasionally duplicated a snippet as a backup before I modifying the original. I just happened to duplicate one I had already duplicated from previous coding.

**Comment by Deesen** [comment]
Like every 2-3 time your find leads to improvement. I think it is a great advantage to label Duplicates like

When duplicating the first one:
- Snippet
- Snippet Duplicate
- Snippet Duplicate 2

Or:
- Snippet Duplicate
- Snippet Duplicate Duplicate
- Snippet Duplicate Duplicate 2

Same with all other elements and resources.

**Comment by bossloper** [comment]
A couple of further thoughts on element duplicates.
1) should duplicate plugin and modules be set as disabled by default - a bit like when duplicating a resource 
2) duplicating elements creates the duplicate instantly vs for resources you must select save before the duplicate is actually created. Should the element duplicate logic work in the same way?

**Comment by Deesen** [comment]
1. Yes I´m sure it makes definetly sense, added it.
2. Are you sure? For me resource-duplicates are in resource-tree without pressing save-button.

**Comment by bossloper** [comment]
1. Thanks.
2. You are right - That's what happens when your overnight thoughts go straight to GitHub!

**Comment by Deesen** [comment]
LOL ;-)
