### ISSUE TITLE
error if no page and url like(site.com/7890)

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1035]
http://modx.im/uploads/images/00/17/31/2016/12/01/c498c0.jpg

**Comment by Deesen** [comment]
But why needle `$sanitize_seed` is empty? https://github.com/modxcms/evolution/blob/develop/manager/includes/protect.inc.php#L24

**Comment by Deesen** [comment]
Tested resources with alias 7890, forwarding to site.com/7890.html and no error. Also containers with site.com/7890/ working like expected.

**Comment by dmi3yy** [comment]
Test plz with seostrict on/off 


Отправлено с iPhone

**Comment by Deesen** [comment]
Tested with seo-strict **on** before. Also no problems now with with seo-strict **off**:

Resource 7890
- http://localhost/7890
- http://localhost/7890/
- http://localhost/7890.html

Container 7891
- http://localhost/7891
- http://localhost/7891/
- http://localhost/7891.html

**Comment by dmi3yy** [comment]
Maybe with aliaslistingfolder this is last place  were maybe bug

Отправлено с iPhone

**Comment by Deesen** [comment]
I tested also aliaslisting, no issues. But the error in your screenshot is exactly the same as triggered by issue #1051 !! Seems the template assigned to the resource in your screenshot was completely empty (string-length 0).
