### ISSUE TITLE
OnManagerMainFrameHeaderHTMLBlock does not work on modules

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#1037]
Event **OnManagerMainFrameHeaderHTMLBlock** does not work on modules.

Using a plugin to ouput something with OnManagerMainFrameHeaderHTMLBlock, works everywhere but not on modules page.

Is it a limit of OnManagerMainFrameHeaderHTMLBlock or Modules code need something to work with this event?

**Comment by Deesen** [comment]
If you just search the MODX-core for string "OnManagerMainFrameHeaderHTMLBlock" you will already notice it is only invoked inside header.inc.php, which is only included in manager-actions. But a module is a unique application with 100% control about the HTML-code that will be output into mainframe. This way you can create every kind of custom application within the mainframe so to speak, also AJAX-responses etc..

**Comment by Deesen** [comment]
You would need to add that to a module and output `$onManagerMainFrameHeaderHTMLBlock` at right place:

    $evtOut = $modx->invokeEvent('OnManagerMainFrameHeaderHTMLBlock');
    $onManagerMainFrameHeaderHTMLBlock = is_array($evtOut) ? implode("\n", $evtOut) : '';
    echo $onManagerMainFrameHeaderHTMLBlock;

**Comment by Nicola1971** [comment]
ok, now i undestand, Thanks @Deesen 

I think, at least default Core Modules, like Doc Manager should includes this peace of code to support this Event.

**Comment by Deesen** [comment]
Makes sense to me!

**Comment by Nicola1971** [comment]
i will add code for this event for 1.2.1 on default modules.

we need to improve documentation and write some guidelines for modules and plugin development. 
- better events documentation
- guidelines for delopment and styling extras - extras should fit manager themes and support themes customizations (included plugins for settings and colors)

**Comment by Nicola1971** [comment]
fixed in https://github.com/modxcms/evolution/pull/1090
