### ISSUE TITLE
Evo 1.2 Release - Forum Post

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1039]
@yama , @dmi3yy  , @Deesen

Just a heads up:

I have [posted on the MODX forum](https://forums.modx.com/thread/101359/important-evo-1-2-released) ref. the latest 1.2 release - if you want anything added, please let me know and I will add the infos you provide me.

**Comment by Breezer** [comment]
They need to change the wording on the downloading page from Revolution to Evolution...

**Comment by modxuser** [comment]
@Breezer 

Yes, I noticed that as well as soon as they went live with the new site, but I can't remember if I notified them of the problem. It's very hard to get any of the LLC nowadays

**Comment by Breezer** [comment]
Well you do a great job keeping the forum up to date, we appreciate it.
