### ISSUE TITLE
Evo 1.2 - Tree not automatically reloading on save or move

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1040]
@pmfx , @Nicola1971 , @Deesen 

I decided I would give the new 1.2 a try and see how the new back-end looks and works.

At the moment I am getting realy frustrated that the tree menu isn't reloading by itself after I save a document or move one. I have to either refresh manualy or click on a different document.

Does the "elementsintree" plugin have to be installed for this ?

Forgot to mention, this is on my local PC - Windows 7 Pro, Intel Core i7, 500 GB SSD, 16GB memory, using WAMP 64bit

I have a few other queries as well, but I will post them later - at the moment, my workflow is as slow as in Revo - I find in general that the back-end is now slower

To note is, this doesn't happen when using 1.0.15

**Comment by Deesen** [comment]
Perfect time to test new feature when the release is already out :-)... I need server-access to see myself what is going wrong with such strange problems. I upgraded myself several 1.0.14 installation with 1.2-RC and had no issues. Dmitryy also received a lot of mails that "lock elements" causes issues of all colors. But they did not run the `/install`-routine so DB-tables were not up-to-date :+1: ..

So to answer your questions:

1) Tree should reload also without active "elementsInTree". The reload-mechanismn is the same as when just saving+leaving a resource in 1.0.15 (= an added &r=1 to an action-URL will cause the tree to reload).
2) With a slow connection the workflow is indeed slower if you click like hell one resource after the other, as there are now 2 frames requesting server and updating their content often.

Maybe we can improve the "display_locks"-permission. It controls the display of locks in site-tree and elements-management. So in case user has no permission, we maybe should also avoid reloading to have the option to disable those additional server-requests. But then of course you will not be noticed in advance an element/resource is locked, or who is working where.

Or we just revert all this and can lock only a single element or resource like before.

**Comment by modxuser** [comment]
@Deesen 

At the moment the site is only on my PC - the live site still uses 0.9.6.3

So as such, I can't give access yet - I may have time today to get it online, then I can give you temp access, if thats OK

**Comment by modxuser** [comment]
So, the site is online - the problem is intermittent on the live server

**Comment by yama** [comment]
$_REQUEST['r'] ?

**Comment by Deesen** [comment]
@modxuser Yes please give me temp-access so I can see myself (need file-manager access). Also which browser are you using?

**Comment by Deesen** [comment]
Ah ok "intermittent" means the problem is partly solved? Maybe you want to check your localhost´s DB-config. If you use "localhost" as your database-server, you can try replacing it by 127.0.0.1. Otherwise I have a damn slow localhost-connection.

**Comment by modxuser** [comment]
Its only intermittent on the live server

Using 1.0.15 or 1.1 my local server is lightning fast

How can I send you details for the site ? I don't want to publsh them here, its a live site

**Comment by modxuser** [comment]
@Deesen just sent the email, thanks

**Comment by modxuser** [comment]
@Deesen 

Just finished updating a 1.0.12 version and the exact same problem is apparent

This one is a bigger site and will take longer before I can get it on a live server

**Comment by Deesen** [comment]
As written by mail indeed the duplicate-button inside actionbuttons-bar does not unlock resource. Seems I forgot to test and nobody here uses this button?

While reg. speed I cannot find any issue with the installation I had access to. When clicking through resources, as you can see in user-log, each resource opened within 1-2 sec as well as the resource-tree updates also in 1-2sec for me. For me lightning fast compared to my own Revo-site... and your installation is also faster than my own localhost! But this is due to several MultiTVs etc. I guess.

So does anybody else faces such speed-dropping issues on his installations?

**Comment by Nicola1971** [comment]
updated about 30 sites today, can't replicate this isssue

**Comment by modxuser** [comment]
The problem has probaby been resolved, it's an issue when using "NoScript" for FireFox

Thanks @Deesen for his help with this, I wouldn't have gotten it sorted if he hadn't helped me out.

Now I just turn it of when I work with the manager.
