### ISSUE TITLE
On install decide what the manager login folder will be

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1042]
I was thinking about a way to get a more secure manager.
Would it be possible to decide on a new install or update to use a custom manager login folder?
Then if you like to update you have to enter the renamed foldername?!

Don't know if there would be any issues and the difficulty to do it.

**Comment by Deesen** [comment]
Yes but it would be quite a big change, and any addons that rely on a hardcoded "/manager" (means in code is written `include("/manager/includes/xxx.php")` instead of `include($managerPath."includes/...")`. So it would need all of them to be updated.

Good thing is, a custom manager-dir is already supported in core as far as I understand but I did not try it yet.

**Comment by Deesen** [comment]
I just renamed /manager on my localhost and at first sight everything works immediately ;-). Everything nessecary seems is already prepared. Maybe before/after "delete install-directory" we can add "rename manager-path".

What I love about Revo is the "Hardening MODX"-part. You can make big changes to default-directories, in short like

- /srv/www/domain.xy/core/
- /srv/www/domain.xy/public/

where core is not connected to the domain, only public is. And in directory public you have only index.php and some required PHP-files acting as connectors to form-components, CSS and JS-stuff etc. So you provide much less files and directories for hackers.

But adding that to Evo would be a real big change I guess.

**Comment by modxuser** [comment]
Have you tried updating a site which has a different manager name ? I don't think it works, at least thats the report I have seen to date.

The update always looks for "manager". I delete everything in the core, upload, update, then rename, each time I update any sites that have re-named manager folders - somewhat tedious, but gets the job done

The same goes with some of the core file which have "MODX Content Manager" in the HTML title tag - thats removed straight away - a typical point of search for hackers

**Comment by bossloper** [comment]
RE: removing title tag - Should we therefore remove the MODX reference from the manager login template? And modx GPL licence at the bottom... and the MODX logo? How far to go?! ... I do from my sites.

**Comment by modxuser** [comment]
@bossloper 

I remove as much as I can - I don't use the default login form either as is I have a refurbished form

My opinion: for security reasons I think all mentions of MODX should be removed

**Example:**

You should use the "MODX Content Manager" is in tons of files - why ? Maybe change it to, you should be using the admin system or something on those lines

I can only presume that the word "MODX" is the top search criteria when it comes to hacking an Evo or Revo site, along with "manager"

**Comment by bossloper** [comment]
@modxuser - completely agree, every little helps.
Best way to advertise MODX Evo will be a new website. If a setup really does want to advertise their CMF system they can put it on the website frontend footer... though I never would!

**Comment by modxuser** [comment]
@bossloper 

Agree fully - just noticed that Github remove tags - so my form isn't rendered properly

**Comment by bossloper** [comment]
Just thinking... For the "Please use the MODX Content Manager ..." messages in the top of manager php code instead of a different message would it be better and give less away just to return a 404 page not found?

**Comment by nick0** [comment]
I am bit late in the convo here...

I agree with @fourroses666, it would be nice to do it through the update process so it is more obvious.

The name of the manager folder can currently be changed (from 1.0.12 from memory) manually via ftp, and by adding the relevant folder name in the siteManager.php file in assets/cache.

It works perfectly like that. Maybe not for old scripts with manager hard coded though.

Updating is not a problem, it works everytime. But if you do the assets-new/manager-new ftp update method, you do need to update the manager folder name to match the custom name. As long as you get that right, there are no dramas in updating.
