### ISSUE TITLE
ElementsInTree todo: add plugin on/off

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#1044]

**Comment by Nicola1971** [comment]
what do you mean with add plugin on/off? don't understand

**Comment by pmfx** [comment]
I think it is about to add "Disable/Enable Plugin" in context menu. Could be useful. @MrSwed please post ElementsInTree related things to https://github.com/pmfx/ElementsInTree/issues

**Comment by Deesen** [comment]
Why not use disable/enable plugin in plugins-configuration? To allow non-admins also enable/disable it?

**Comment by MrSwed** [comment]
https://github.com/pmfx/ElementsInTree/issues/33
