### ISSUE TITLE
Cannot set doc parent folder to 0 (main), clicking site name opens edit (fresh 1.2 install)

### ISSUE THREAD

**Issue by Breezer** [modxcms/evolution#1045]
A couple issues with the tree, if you move a document and then try to edit and set its parent to the main site its a no go.

Clicking the main site doc (0) opens an edit page and then gives multiple errors.

This is a fresh 1.2 install with default site installed.

**Comment by modxuser** [comment]
I just tried moving a document back into the root.

I don't get any mistakes, but I don't get the "New parent" notice after clicking on the root

This is an updated site to 1.2

**Comment by bossloper** [comment]
Same here - Site root (0) title is not selectable from the site tree when trying to select a target for Move Resource

**Comment by Nicola1971** [comment]
confirm, can't set site root as parent

**Comment by Deesen** [comment]
This is really unnessecary embarassement, if you look at the fix. Both issues should be solved with it. Please confirm.

**Comment by bossloper** [comment]
Certainly no need to be embarrassed about your coding skills!

**Comment by Deesen** [comment]
Thanks, but definetly a little about my testing skills :-D

**Comment by bossloper** [comment]
:-)
Confirming now fixed for both issues.

**Comment by modxuser** [comment]
Same here - tested and works, thanks @Deesen

**Comment by bossloper** [comment]
Not sure what is different, but with the latest commits to dev I cannot move any resource. When I click the parent on the site tree I always get 'Unable to set the new parent!!'
