### ISSUE TITLE
Installation Problem: asking for password, but no form to fill

### ISSUE THREAD

**Issue by kulmjens** [modxcms/evolution#1046]
Hi there,

I ran an installation of Evo 1.2 and chose the "advanced upgrade" option. As I was finished setting the correct database collation and clicked to go to the the next step, a javascript alter poped up and told me that I had to enter the admin password to proceed. But there was no field to fill in anything.
The chrome devtools  displayed a javascript error that "Slider2" is undefined.

In the file "install/actions/tpl_connection.html" I commented out line 230 and 235.
```
...
//if(installMode==0 && document.getElementById('AUH')) {
  Slider2 = new Fx.Slide('AUH', {duration:477});//transition:Fx.Sine.easeOut,
  Slider2.hide();
  $('AUH').style.display = 'block';
  $('AUH').style.backgroundColor = '#ffff00';
//}
...
```
After that I ran through the whole install process again, and this time the admin form showed up. I filled in the existing admin user and was able to finish the installation.
I don't think it's the right solution for the problem, because in my case it didn't overwrite the existing admin user's password...

**Comment by Deesen** [comment]
Definetly an issue, thanks for reporting!
