### ISSUE TITLE
IMPORTANT: New commit-description policy starting now

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#1048]
As it is important to be able to create statistics about future releases we want to implement a new commit-description "policy". The last draft can be found here https://github.com/modxcms/evolution/wiki/Contributing-to-MODX-Evolution-Core . Every idea, thought, critic is welcome. 

Practically this will help to prepare statistics to add to press-releases like

Fixes: **30**
Refactoring: **20**
Improvements: **10**
Security: **5**

Please everyone, to be able to see how many fixes, improvements etc the next release has, we need such kind of simple tagging. Version 1.2 had 1251 commits and nobody was willing to check all of them manually to create above statistic ;-).

**Comment by Deesen** [comment]
Not sure where to spread this info else to reach everybody.

**Comment by Nicola1971** [comment]
nice idea

**Comment by mcparana** [comment]
cool!

what about "concept" issue type - large, global improvement, like Elements in tree or #961?

**Comment by Deesen** [comment]
Not sure, maybe "I / Improvement" is still enough description for something like singleton. But @dmitryy and @yama maybe think different.

**Comment by Deesen** [comment]
I added small description of commit-types and also type C for "Code clean up".

**Comment by bossloper** [comment]
Note the link in the first post does not work now. Details are here: https://github.com/modxcms/evolution/wiki/Contributing-to-MODX-Evolution-Core

**Comment by Deesen** [comment]
Thanks!

**Comment by MrSwed** [comment]
Why are not standard notation?
for a long time used in many pages change
[+] Added ..
[-] Removed ...
[*] corrected...

**Comment by MrSwed** [comment]
I propose to add best practice tips of git
for example: 
- To make changes for PR, make a separate branch from the last commit of the original develop branch. This will avoid unnecessary merges into your branch of the develop in your PR
- 

also, I think need to add info about code formating
https://github.com/modxcms/evolution/issues/666

**Comment by Deesen** [comment]
Why not standard notation? I do not know it to be honest. I only know dmi3yy asked me to prepare release-notes for 1.2-release. It had 1251 commits. At every MODX-release statistics are mentioned, and it is not possible to manually check 1251 commits to create statistic (like mentioned in my first post). How to find out how many improvements, fixes, security-related fixes etc, when notation is only [+] [-] [*]? Nobody will check 1251 commits manually.

Thanks I will add the PR-tip.

Reg. devil #666 I think it would be great to solve, you´re right. But we need us to decide for a space/tabs-scheme first, reformat all files and then keep up to that new scheme. Personally I prefer "smart-tabs".

**Comment by Deesen** [comment]
Should I add like below?

"If you want to contribute code, it is recommended to create a separate branch of last commit of the original develop branch for it. This will avoid unnessecary merges into your PR."

**Comment by MrSwed** [comment]
for example: history of The Bat!
[readme.txt](https://github.com/modxcms/evolution/files/636061/readme.txt)

**Comment by MrSwed** [comment]
I think "excessive" more informative
"If you want to contribute code, it is recommended to create a separate branch of last commit of the original develop branch for it. This will avoid **excessive** merges into your PR."

Though it is better to address to the man-native English :)

**Comment by Deesen** [comment]
Ok ;-), maybe "This can excessively reduce the amount of additional merge-commits into your PR." ?

Reg "The Bat!"-history, I see the legend has 4 types:

    [ ! Major Improvement        ]
    [ + Added feature            ]
    [ * Improved/changed feature ]
    [ - Bug fixed (we hope)      ]

My proposal allow a little more detailed statistic, but not sure which makes more sense. Would be great to have more opinions on this maybe?

**Comment by bossloper** [comment]
"This can **extensively** reduce the **number** of additional merge-commits into your PR." ?

**Comment by Deesen** [comment]
Sounds better indeed, thanks!

**Comment by MrSwed** [comment]
this file - only example available at hand, I often met similar designations in other programs - an asterisk, plyuchik, minus, etc. in square brackets ..

Though of course, I'm wrong - in most cases, each programmer indicates how he wants :)

I rummaged through on the disk for different history.txt:

Some examples:

Icons in square brackets:
[! + - * /] - Ritlabs (thebat), mkey, far plugins, Hard Link Magic, TotalConsole (totalcmd plugins)

The icons and a parenthesis
! + - *) - EasySoft (EasyBoot UltraIso).

Just badges:
! + - * - Graphics Converter, AmpView - Lister-plugin for Total Commander

Short Text tags:
"Fixed", "added", "removed" etc - ghisler (totalcmd), HWiNFO, Graphics Converter

CHG :, FIX: LNG: - Codestuff Starter

**Comment by MrSwed** [comment]
As for me - icons - shorter, however, they may not be enough in the case of large legend :)

As a result, seems I will agree with the selected legend already.  

And suggest some symbols for the texts and translations.

**Comment by Deesen** [comment]
But maybe we can combine both, using brackets and letters and move them to beginning like

    [F] #123 description of fix

instead of

    #123 F: description of fix

Looks much cleaner to me.

**Comment by Deesen** [comment]
Nobody cares?

**Comment by bossloper** [comment]
Maybe nobody minds, as long as it is consistent.
+1 for 
[F] #123 description of fix

**Comment by Nicola1971** [comment]
@Deesen trying to use it : https://github.com/modxcms/evolution/pull/1094

**Comment by Deesen** [comment]
:+1:
