### ISSUE TITLE
Translation missing on dashboard

### ISSUE THREAD

**Issue by kulmjens** [modxcms/evolution#1049]
Hi there, 

on the welcome dashboard there is a missing translation when the inbox has no messages.
In line 11 of `/manager/media/style/MODxRE2/welcome.php` the string is hardcoded. So I changed this
```
$code = 'global $_lang;return $_SESSION["nrtotalmessages"] ? sprintf($_lang["welcome_messages"], $_SESSION["nrtotalmessages"], \'<span style="color:red;">\' . $_SESSION["nrnewmessages"] . "</span>") : "No messages";';
```
into this
```
$code = 'global $_lang;return $_SESSION["nrtotalmessages"] ? sprintf($_lang["welcome_messages"], $_SESSION["nrtotalmessages"], \'<span style="color:red;">\' . $_SESSION["nrnewmessages"] . "</span>") : $_lang["messages_no_messages"];';
```
This language index (messages_no_messages) is already available in the language files, so there is no need to update them. :-)

**Comment by Fr3ddy7** [comment]
+1

no russian translate

**Comment by Nicola1971** [comment]
fixed in https://github.com/modxcms/evolution/pull/1090
