### ISSUE TITLE
Missing title in tree tooltip

### ISSUE THREAD

**Issue by kulmjens** [modxcms/evolution#1052]
Hi there,

the tooltip that pops up when hovering over the nodes in the site tree has an empty title or rather displays only the menutitle. By changing line 106 of `/manager/frames/nodes.functions.inc.php` from
```
$alt.= $_lang['resource_opt_menu_title']          .': '.$menutitle;
```
to
```
$alt.= $_lang['resource_opt_menu_title']          .': '.$nodetitle_esc;
```
solved the thing. By looking at line 73 the `$nodetitle` is retrieved through the function `getNodeTitle` which returns the right title depending on the settings.

**Comment by Deesen** [comment]
Hmm but does it make sense? These $alt-titles are meant to have a quick overview of all given fields and there values. So "Menu title: value of alias/pagetitle/longtitle etc" makes no sense to me. Rather adding 

Page title:
Long title:

Do you know option "Display Name in Resource Tree" under the sort tree options?

**Comment by kulmjens** [comment]
Ah, okay. So it's only for the menutitle. Looked strange to me because I seldom make use of the field menutitle, so there was nothing behind "Menutitle:" in my tooltips. So it's not an issue.

But if I switch the option "Display Name in Resource Tree" to menutitle, all nodes remain showing the pagetitle instead of something like "---", when their menutitle is empty. Hmmm...

**Comment by kulmjens** [comment]
So you can close this issue.

**Comment by Deesen** [comment]
You are right, empty menutitle should stay empty to have a quick overview which menutitles are missing.
