### ISSUE TITLE
Question: Evo 1.2 + TinyMCE4 Entity Encoding

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1053]
I have tried to figure this out, to no avail

The Entity Encoding by default is set to named, but it isn't changing inverted commas to `&quot;`

This is causing problems with other elements, as the inverted commas are used for code formatting they are messing my HTML up

Any ideas, other than trying "numeric", as that doesn't work either

Thanks for any ideas or help

**Comment by Deesen** [comment]
Not sure what is happening. The entity-encoding is set in base-theme (base = always loaded) https://github.com/modxcms/evolution/blob/develop/assets/plugins/tinymce4/theme/theme.tinymce4.base.inc.php#L43

The official documentation says https://www.tinymce.com/docs/configure/content-filtering/#encodingtypes

In the frames sourcecode I see `entity_encoding:'named',` so config is setting this parameter up correct. I don´t understand why it doesn´t seem to work..

**Comment by Deesen** [comment]
Maybe I found the reason? https://www.tinymce.com/docs/configure/content-filtering/#entities

- **Encoding Type - named**: Characters will be converted into named entities based on the entities option
- **Entities**: The base entities < > & ' and " will always be entity encoded into their named equivalents. Though ' and " will only be encoded within attribute values and < > will only be encoded within text nodes. This is correct according to the HTML and XML specifications.

**Comment by modxuser** [comment]
@Deesen 

Yeh, I read that as well as I was searching through the Tinymce website, but I must admit, I didn't fully understand it.

To my knowledge and user experience, all editors I have used to date, always change inverted commas to `&quot;` when used in content / rich text areas

I find it strange that TinyMce doesn't work like many others do

**Comment by Deesen** [comment]
Hmm TinyMCE states that this is HTML/XML-specification? Are you talking about normal single and double-quotes? Or which ones exactly? https://dbaron.org/www/quotes

Maybe you just need to add all signs you want to convert to the "entities"-param (in plugin-config) like

    entities : '8218,sbquo,8222,bdquo,147,ldquo,148,rdquo,145,lsquo,146,rsquo'

or 

    entities : '8218,sbquo,8222,bdquo,8220,ldquo,8221,rdquo,8216,lsquo,8217,rsquo'

**Comment by modxuser** [comment]
@Deesen 

Number 1 in the list of quotation marks you posted

`"This sentence is surrounded by &quot; and &quot;, which are a type of quotation marks." `

**Comment by Deesen** [comment]
Ok then I have no more ideas for now. I guess it is the specification stating `&quot;` is only nessecary inside attributes to not break them. Like `<a href="#" data=title="This is a &quot;">link</a>`

**Comment by modxuser** [comment]
@Deesen 

No stress, thank you for your time. The solution I have works so for the time being thats OK.
