### ISSUE TITLE
Closing date field popup calendar

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1054]
For resource date fields the popup calendar used to be able to be closed by pressing enter key. Now the only way to close the calendar is to click outside it. This is also linked to issue #1027.
Either need to reinstate 'enter' key or add a close button.

EDIT - Also in Chrome if an invalid time is entered I get multiple dialog boxes indicating invalid minutes entered if the enter key is used with an invalid time.

**Comment by Deesen** [comment]
Maybe you want to test this one too?

**Comment by bossloper** [comment]
Yup, I'll grab the latest and greatest dev release later today

**Comment by bossloper** [comment]
This is not quite right yet. Yes it closes with enter but the time cannot be altered. If the time is changed in the popup it is not honoured on the date field.

**Comment by Deesen** [comment]
What a torture this little script is, if you want to manage every possible situation. Maybe you want to check "latest and greatest" again? Its enough to just replace https://github.com/Deesen/evolution/blob/cc3cf71ffe0e0b22ac7aadb2bc23afd95e61c768/manager/media/style/common/moo-datepicker/datepicker.js

**Comment by bossloper** [comment]
It seems to work in Chrome, but for Firefox and Edge they are still not updating the time if I alter just the time and press enter.

**Comment by bossloper** [comment]
Looks good. After I had double checked each browser type had cleared js caching!

**Comment by Deesen** [comment]
Nice, thanks!
