### ISSUE TITLE
manager 'Forgot your password?' not working

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1057]
I might be wrong, but I cannot get the manager password reset to work from the manager login screen.
It sends the email but clicking the link in the email always fails.

**Comment by Deesen** [comment]
Yes my fault. "active_users" must have an existing entry of a user to create hash, but I added DROP TABLE "active_users" to 1.2-upgrade which breaks the hash-mechanismn now. Will replace it with user_attributes.lastlogin (if > 0), so functionality should be same like before means user must have logged in once to reset password.

**Comment by Deesen** [comment]
It should be also improved now with forwarding to change-password page after login.

**Comment by bossloper** [comment]
Nice. I'll give it a test...

**Comment by bossloper** [comment]
Yes, working.
