### ISSUE TITLE
Modx Parse Error after updating to Evo 1.2

### ISSUE THREAD

**Issue by nickff** [modxcms/evolution#1073]
Hi All,

I'm getting [this error](http://mercyconnections.org/) after updating from 1.0.15 -> 1.2.

It seems to be related to the maxigallery plugin, and if I go to a page that doesn't use it everything works fine - http://mercyconnections.org/vermont-non-profit.html

Any thoughts on why it would start erroring out?

**Comment by modxuser** [comment]
As noted in the [MODX Forum](https://forums.modx.com/thread/101397/modx-parse-error-after-updating-to-evo-1-2#dis-post-547038)

**Comment by MrSwed** [comment]
Ypu need update [maxigallery](https://github.com/yama/MaxiGallery)

**Comment by dmi3yy** [comment]
or  set in config.inc.php  type=mysql

**Comment by nickff** [comment]
Updating Maxigallery per the latest version on Github did the trick and I was able to continue with the default 'mysqli' setting in config.inc.php. I'd recommend adding this latest version of MG to the Evo extras repository.
