### ISSUE TITLE
Enhancement: @INCLUDE For Chunks

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1074]
@yama , @Deesen 

I am currently trying out the new features and have looked at the template file binding found [here](https://github.com/modxcms/evolution/issues/627)

Is it possible to do the same for chunks ?

Something like any of the following:

```
@INCLUDE:assets/chunks/mychunk.txt
@INCLUDE:assets/chunks/mychunk.tpl
@INCLUDE:assets/chunks/mychunk.html
```

I want to get as much of the code out of the siteCache.idx.php as possible and also remove as many 3rd party snippets as I can from my code

**Comment by yama** [comment]
Is that to call in the chunk code?

**Comment by modxuser** [comment]
Hi @yama 

Yes, just like in the templates

**Comment by modxuser** [comment]
Example:

My template call - minimal-template

`@INCLUDE:assets/templates/minimal-template.tpl`

Contains:
```
{{header}}
[*content*]
{{footer}}
```

The header chunk is called (same goes for the footer) via:

`@INCLUDE:assets/chunks/header.txt`

Or .html / .tpl - whatever is best

And the header.txt contains something like the following

    <!DOCTYPE html>
    <html lang="en">
    <head>
    <base href="[(site_url)]">
    <meta charset="[(modx_charset)]">
    <title>[(site_name)] | [*longtitle*]</title>
    <meta name="description" content="[*summary*]">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="57x57" href="apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon-180x180.png">
    </head>

**Comment by yama** [comment]
```
<?php include_once('assets/chunks/header.txt'); ?>
[*content*]
<?php include_once('assets/chunks/footer.txt'); ?>
```
Is this?

**Comment by yama** [comment]
> Yes, just like in the templates

If it,

```
{{@INCLUDE:assets/chunks/header.txt}}
```
```
{{@FILE:assets/chunks/header.txt}}
```
How about such syntax?

**Comment by Deesen** [comment]
New syntax looks very practical! :-)

**Comment by Deesen** [comment]
@modxuser Right now I think its only possible to use @INCLUDE with templates. There is also a great plugin called "Static Elements" which will turn all chunks, templates etc into editable files automatically: https://github.com/dzhuryn/StaticElements-for-MODX-Evo

**Comment by pmfx** [comment]
That's cool! 
BTW Russian community created a lot of gems like that. Sad that not many knows about it (I didn't know that one) and most are missing English description/manual/readme.

**Comment by modxuser** [comment]
@yama That would be great if it's possible

@Deesen I thought I could use Filesource, but I ended up seaching the forum until 05.00 this morning looking for documentation on how to use it and [found that in the Forum](https://forums.modx.com/thread/89453/virtual-chunks-and-snippets-for-modx-evolution-development-with-ide). But I am looking to get away from as much 3rd party code as possible. Built in is better :)

**Comment by modxuser** [comment]
@Deesen 

Talking of Filesource, try adding the path for the managermanager static file and you will get errors, something like the 100 limit has been reached

**Comment by Deesen** [comment]
FileSource: Did you set managermanager/mm.inc.php as your filesource? Then you have overwritten the original mm.inc.php with the plugincode. You have to use different name like managermanager/test.php

LoadElement: I also tried it but I like staticElements more as it is fully automated. When you change elements via manager, it will alter the static files. If you change static files, it will alter the elements-code in database. Also you can create your default setup of templates, TVs, chunks etc you generally want to use for new installations. So for new installation you just need to copy your default static files, install the plugin and it will create all templates, TVs etc acc to your uploaded files.

**Comment by modxuser** [comment]
@Deesen 

Yes, I realised that after it took me ages to find the line in the DB, as I couldn't remove it from the manager, due to the errors field crashing everything

Thats something that should possibly be mentioned in the documentation

staticElements sounds good, but for my needs it'e probabl a little OTT (Over The Top / To Much)

**Comment by Deesen** [comment]
But I can assure you staticElements is pure comfort if you want to work with static files, or maybe use it to add your elements and changes to Github.

**Comment by modxuser** [comment]
Stupid question maybe - any tutorials around for it ?

And, does it cache the files in the siteCache.idx.php as they are still in the system ?

**Comment by Deesen** [comment]
Tutorial? No need for that. Its just nessecary to install plugin, reload manager & frontpage once (this will check database/files and create its own cache). And then take a look into directory assets/elements ;-).

**Comment by Deesen** [comment]
Maybe try on your localhost.

**Comment by modxuser** [comment]
@Deesen are you talking about "staticElements" or "LoadElement" ?

**Comment by Deesen** [comment]
This one https://github.com/dzhuryn/StaticElements-for-MODX-Evo

**Comment by modxuser** [comment]
OK, will give it a try - thanks

**Comment by modxuser** [comment]
@Deesen just installed, does a great job, but the chunk code is still in the siteCache.idx.php

**Comment by Deesen** [comment]
Of course chunks are cached in sitecache, so you don´t need to reload them always from DB.

**Comment by modxuser** [comment]
Can't get LoadElement working @AgelxNash I don't know why not as I have followed the video 1 for 1

The chunks aren't being called in

**Comment by modxuser** [comment]
I have sacked the LoadElement plugin, I can't get it to work no matter what I do., so for me at the moment I will stay with what I have and hope that possibly in the future that @yama will incorporate [his suggestion from above](https://github.com/modxcms/evolution/issues/1074#issuecomment-265659391) into the core.

I think that would be the optimal solution anyway, as everything else can now use @BINDINGS, TV's and Templates and snippets, plugins can be included now as well - so the additional @BINDING for chunks is in my opinion the next step in the evolution, sorry for the pun LOL

**Comment by modxuser** [comment]
@dmi3yy , @yama 

Can this be relabeled as "Enhancement" please

**Comment by yama** [comment]
```
{{@INCLUDE:assets/chunks/header.txt}}
```
```
{{@FILE:assets/chunks/header.txt}}
```
1.2.2

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/55
