### ISSUE TITLE
SEO Strict URLs + Google Sitemap Incompatibility

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1075]
When having the SEO Strict URLs set to "Yes" in the configuration, a second "/" replaces the alias

Which means you get something like this:

Not active: domain.com/home

Active: domain.com//

I have tested this on 3 sites and they all act the same

**Comment by Deesen** [comment]
So alias "/" should redirect to "/start-page" or "", right?

**Comment by bossloper** [comment]
@modxuser To reproduce it I have to have a Friendly URL Prefix of / . Is that what you have? Also do you have the default .htaccess file or a custom version? For me if home is the designated 'site_start' page in the config then it seems ok to me.... but there are quite a few variables here.

Another related issue is if you manually alter an address and add extra /s e.g.: domain.com////contact-us then this still works when really it should not or maybe redirect to domain.com/contact-us

**Comment by modxuser** [comment]
no prefix - no suffix

simply add a name to the alias, for example: home

standard URL is then for ID 1 is then "domain.com/home"

switch on Seo Strict URLs

Seo Strict URLs then removes "home" and replaces it with "/"

**Comment by modxuser** [comment]
Just a heads up:

This may not actually be Seo Strict Urls itself, I have a Googlesitemap snippet which generates the sitemap.xml and thats where I see the double slash

So, in theory and possibly pracrice, it could be the combination of the sitemap snippet and Seo Strict URLs

[snippet.googlesitemapxml.php.txt](https://github.com/modxcms/evolution/files/643738/snippet.googlesitemapxml.php.txt)

**Comment by bossloper** [comment]
ah that makes more sense. from the default site install it looks fine, except the ability to add manually multiple /s and not get a redirect or error.

**Comment by bossloper** [comment]
Yes it should. Maybe the sitemap code is also doing some basic SEO tweaks so doing the same as the SEO Strict URLs option. That snippet probably needs adjusting to remove any SEO stuff?

**Comment by modxuser** [comment]
Although not a PHP Dev, looking at [the script](https://github.com/modxcms/evolution/issues/1075#issuecomment-266203718), there is nothing "SEO" in it :)

**Comment by bossloper** [comment]
but presumably the actual website does not display the page with a double // which suggests it is only in the sitemap snippet?
Is there anything in the script checking for site_start config value.
e.g. along the lines of:
if ($doc['id'] == $modx->config['site_start']) ...

**Comment by modxuser** [comment]
@bossloper 

The snippet is attached to my [post](https://github.com/modxcms/evolution/issues/1075#issuecomment-266203718) above

The URL which you are sent to when clicked in the sitemap.xml is "domain.com//" and it stays as such, SEO Strict URLs doesn't modify it

**Comment by modxuser** [comment]
If you would like to test the sitemap script:

Create a snippet, call it "SitemapXML" and add the contents of the snippet or include it (standard stuff LOL)

Create a nex template call it "Sitemap" and add the follwing:
`[[SitemapXML? &allowedtemplates=`NAME1, NAME2, NAME3`]]`

Changing NAME1 etc for the names of your templates that you want added to the sitemap.xml

Note, GitHub removes the single backtick, so don't forget to add it before the first name and after the last name

Create a new document with the following alias: sitemap.xml

Document setting as in the image:
![sitemap-document-settings](https://cloud.githubusercontent.com/assets/1859868/21073530/65c5ddd2-bee1-11e6-8819-051cc25bebbb.png)

You may have to go into the configuration and add a Custom content type for XML, found under the tab "Site", if so, add the following: text/xml

**Comment by bossloper** [comment]
I think it is a shortfall in your sitemap code.

If you replace the line 78 globals with:
`global $site_url, $modx;`

and replace line 84 ($url = $site_url."[\~".$id."~]";) with 2 new lines:
```
if ($id == $modx->config['site_start']) $url = $site_url;
else $url = $site_url."[~".$id."~]";
```
then it should be ok?

**Comment by modxuser** [comment]
@bossloper 

That's done the job, thank you for your time

It has removed the alias completely, so the URL shown is always the domain name - which is good
