### ISSUE TITLE
TinyMCE Themes missing buttons

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1081]
**File:** assets/plugins/tinymce4/theme/theme.tinymce4.full.inc.php

1. `insertdate inserttime` should be changed to `insertdatetime`
2. `search replace`  should be changed to `searchreplace`
3. `hr` is repeted
4. `blockquote` is repeted
5. `codesample` missing
6. `insertlayer moveforward movebackward absolute styleprops cite abbr acronym del ins attribs insertfile insertimage` are either not working or are outdated
6. `spellchecker` not sure if working? ( I receive "The spelling service was not found: (undefined)" when clicked)

**Here is an updated and better organized example for a full toolbar:**

`$this->set('plugins', 'anchor autolink lists spellchecker pagebreak layer table save hr modxlink image imagetools emoticons insertdatetime preview media searchreplace print code contextmenu paste directionality fullscreen noneditable visualchars textcolor nonbreaking template youtube autosave advlist visualblocks charmap', 'string');`

`$this->set('toolbar1', 'save newdocument | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | styleselect formatselect fontselect fontsizeselect', 'string');`

`$this->set('toolbar2', 'cut copy paste pastetext | search replace | bullist numlist | outdent indent blockquote | undo redo | link unlink anchor image help code | insertdate inserttime preview | forecolor backcolor', 'string');`

`$this->set('toolbar3', 'table | hr removeformat visualblocks | subscript superscript | charmap emoticons youtube media hr | print | ltr rtl | fullscreen', 'string');`

`$this->set('toolbar4', 'insertlayer moveforward movebackward absolute | styleprops spellchecker | cite abbr acronym del ins attribs | visualchars nonbreaking template blockquote pagebreak | insertfile insertimage', 'string');`

**Comment by Deesen** [comment]
Thanks for your work!

Reg. spellcheck maybe this helps? Then we should add it too https://github.com/extras-evolution/tinymce4-for-modx-evo/issues/26#issuecomment-220929577

**Comment by Deesen** [comment]
Ehm, the code you posted seems to be the original full-theme, there is no change in code?

**Comment by risingisland** [comment]
Sorry, my bad. It was late and I grabbed the wrong file. :/
Here are the updates:

`$this->set('plugins', 'anchor autolink lists spellchecker pagebreak layer table save hr modxlink image imagetools emoticons insertdatetime preview media searchreplace print code contextmenu paste directionality fullscreen noneditable visualchars textcolor nonbreaking template youtube autosave advlist visualblocks charmap template wordcount codesample', 'string');`

`$this->set('toolbar1', 'save print newdocument | undo redo | searchreplace | cut copy paste pastetext | visualchars spellchecker | visualblocks code | preview fullscreen', 'string');`

`$this->set('toolbar2', 'styleselect formatselect fontselect fontsizeselect | forecolor backcolor', 'string');`

`$this->set('toolbar3', 'bold italic underline strikethrough subscript superscript removeformat | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent blockquote | ltr rtl', 'string');`

`$this->set('toolbar4', 'image youtube media | link unlink anchor | table | pagebreak hr | template codesample nonbreaking insertdatetime | charmap emoticons', 'string');`

Adding `browser_spellcheck` broke TinyMCE, and would not load.

**Comment by Deesen** [comment]
Adding `$this->set('browser_spellcheck', true, 'bool' );` to your theme will break TinyMCE? Can you check browser-console for error?

**Comment by risingisland** [comment]
@Deesen 
Confirmed, working fine now. I had added it as a plugin.

Should `spellchecker `be removed from plugins and toolbar?

**Comment by Deesen** [comment]
No I think not. I added it to plugin-configuration for easy turn on/off. I cannot imagine it will cause problems. But if so please let me know so we can remove it again.
