### ISSUE TITLE
ManagerManager ddmultiplefields widget

### ISSUE THREAD

**Issue by sashabeep** [modxcms/evolution#1082]
ManagerManager ddmultiplefields widget is unuseable in 1.2

call in mm_rules:
```
mm_ddMultipleFields('sliderTV', '', '', 'field,text,text', 'Картинка,Подпись,Ссылка');
```
result:
![screenshot-roks1 ru 2016-12-08 22-53-29](https://cloud.githubusercontent.com/assets/5689796/21025580/5d6b9662-bda2-11e6-806f-4deb5bc93d4a.png)

???

**Comment by MrSwed** [comment]
you need use **image** instead **field**
`mm_ddMultipleFields('sliderTV', '', '', 'image,text,text', 'Картинка,Подпись,Ссылка');`

**Comment by sashabeep** [comment]
No effect. Changed TV type to textarea, only button disappear, row file input still missing
call
```
mm_ddMultipleFields('sliderTV', '', '', 'image,text,text', 'Картинка,Подпись,Ссылка');
```
![2016-12-09 9 54 36](https://cloud.githubusercontent.com/assets/5689796/21040365/e652f762-bdfd-11e6-8827-ddfb08a717ec.png)

ManagerManager from current develop branch... Maybe some patch needed?...

**Comment by sashabeep** [comment]
Looks like button and image not inserted at all. console says no errors
1.1
![2016-12-09 11 38 29](https://cloud.githubusercontent.com/assets/5689796/21042720/bd76c742-be0c-11e6-9578-47771abd8136.png)

1.2 same settings
![2016-12-09 11 38 04](https://cloud.githubusercontent.com/assets/5689796/21042730/c7f2f88a-be0c-11e6-90c6-134e42b6c903.png)

**Comment by sashabeep** [comment]
Sorry, guys, after several tries i got changed input height in CSS because it's too small and was writen with content-box instead of border-box... And then firefox loaded new CSS and everything is works now. You can call me idiot :)
