### ISSUE TITLE
js error in frame tree

### ISSUE THREAD

**Issue by Zevseg** [modxcms/evolution#1086]
if modx_charset = windows-1251 (or !=utf8), then

```javascript
var lockedElementsTranslation = ;
```
which causes the error 
/manager/frames/tree.php line 309 
```javascript
var lockedElementsTranslation = <?php echo json_encode($unlockTranslations); ?>;
``` 

for json_encode all string data must be UTF-8 encoded.

![image](https://cloud.githubusercontent.com/assets/2156427/21041517/f5e7d8f8-be04-11e6-98d1-50bb15787e96.png)

**Comment by Deesen** [comment]
Will this simple line added after line 305 convert all foreign charsets or UTF8? https://github.com/modxcms/evolution/blob/develop/manager/frames/tree.php#L305

    foreach ($unlockTranslations as $key=>$value) $unlockTranslations[$key] = utf8_encode($value);

Or do we need to use something like 

    $unlockTranslations[$key] = iconv('Windows-1250', 'UTF-8', $value);

**Comment by Zevseg** [comment]
I did it already. And it is not necessary for the other?

P.S. 
```php
foreach ($unlockTranslations as $key=>$value) $unlockTranslations[$key] = iconv($modx->config["modx_charset"], "utf-8", $value);
```

**Comment by Deesen** [comment]
Thanks, just wanted you to test first before committing a fix.

**Comment by Zevseg** [comment]
https://github.com/modxcms/evolution/blob/develop/manager/actions/resources.static.php#L142

fix this to

**Comment by Deesen** [comment]
Thanks..
