### ISSUE TITLE
TV @FILE binding not working

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1092]
@Deesen , @yama 

I am not sure that this is just my set-up or if I am doing something wrong, so it could possibly be a bug, but not being a DEV, I can't say why it's happening.

I have tried adding a txt file for my tags to the "file" binding in my tags TV (as seen in the [Evo Docs](https://docs.modx.com/evolution/1.0/developers-guide/template-variables/(at)-binding), it always says it doesn't find the file, although it is 100% there.

Images say more than a thousand words, so here goes:

**TV Setup:**

![tv-setup](https://cloud.githubusercontent.com/assets/1859868/21074051/f49bc082-beee-11e6-9934-2507dbfb6233.png)

**Assets folder:**

![assets-folder](https://cloud.githubusercontent.com/assets/1859868/21074046/e19dfee6-beee-11e6-85d1-328d156a1f45.png)

**Contents of the chunks folder:**

![assets-folder-tags](https://cloud.githubusercontent.com/assets/1859868/21074049/eca1a7ac-beee-11e6-9c13-5af3e0985f34.png)

**Error** (shown when editing a document with the TV):

![error](https://cloud.githubusercontent.com/assets/1859868/21074056/03b96a06-beef-11e6-9231-a42a05f89737.png)

Here the TagOptions.txt file for review:
[TagOptions.txt](https://github.com/modxcms/evolution/files/643819/TagOptions.txt)

**Comment by modxuser** [comment]
@yama 

Hi Yama, can you let me know which files (a list) are dependant for the modifications that you have made.

I don't want to have to re-install completely, just spent the whole weekend modifying my set-up

I can then test it

Much appreciated

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/37fe7bb1d1b44d7dfd016e7c10b32c1950b5d5ed/manager/includes/tmplvars.inc.php
maybe only this

**Comment by modxuser** [comment]
@yama 

Just that one file doesn't seem to be enough, I have copied it but there is no change, I still get the same error

**Comment by modxuser** [comment]
If I add the modification found in: manager/includes/tmplvars.commands.inc.php

The error isn't shown, but, there is only one checkbox shown, without any text

**Comment by modxuser** [comment]
@yama 

I have updated the document parser as well, with the code that can be [found here](https://github.com/modxcms/evolution/commit/f23f24ace3821d42e638c8273db1aae380821ed7)

That seems to have done the trick, so all three files must be updated

Are there any more modified files ?

**Comment by dmi3yy** [comment]
Now All ok  ? 
with this fix ?
#1092 TV @FILE binding not working

**Comment by modxuser** [comment]
@dmi3yy 

I can only say for "this" specific element - YES, all is now OK
