### ISSUE TITLE
MODxRE2 Document Manager Layout

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1093]
@Nicola1971 , @pmfx 

The attached image has everything on it :)

![docmanager](https://cloud.githubusercontent.com/assets/1859868/21074137/2db62fb8-bef1-11e6-966f-424a52c5fcc9.jpg)

Cheers

**Comment by Nicola1971** [comment]
wich browser?  don't have issue 1 & 2 with Chrome and FF on Win10

![jznjineebaejfk3p8qzw4n69e3r48gf6xgctrgabbbbaimkccxys0jilswgnkuxm8qgggaacuwv8fxhyeklh6opaaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/21074640/5d31e540-befe-11e6-98d4-7dd3b7a91fa6.png)

**Comment by modxuser** [comment]
Latest FireFox

**Comment by Nicola1971** [comment]
Firefox 50.0.2 on my pc:
![docman-ff-50 0 2](https://cloud.githubusercontent.com/assets/7342798/21075311/b1950224-bf0e-11e6-848b-71bf16ada497.png)

**Comment by bossloper** [comment]
I'm on Firefox 50.0.2 and it looks fine:
![firefox](https://cloud.githubusercontent.com/assets/1744687/21075301/15a135c0-bf06-11e6-9da1-46eb25e33791.jpg)
Your dropdown lists look different ('old'). Maybe it is related to the OS. What MS Windows version are you on?

**Comment by Nicola1971** [comment]
seems Xp to me..

**Comment by modxuser** [comment]
@Nicola1971 XP - PMSL

Windows 7 Pro + Windows 10

**Comment by modxuser** [comment]
@Nicola1971 , @bossloper 

I have found the reason why my layout looks different, minimise the styles.css in "manager/media/style/MODxRE2/" and you should get the same result

I used [CSS Compressor](http://www.cssdrive.com/index.php/main/csscompressor)

Using "Super Compact" and "Strip ALL Comments".

This tells me that something isn't right in the file, because minimising basicaly stacks, removes space, reduces hex names and thats about it. So putting it all on one line is causing it to break

I use the compressor on a regular basis, almost every day, my job is front-end

**Comment by modxuser** [comment]
Just did exactly the same as the other day, now it works, realy strange as nothing has changed - unless changes have been made to the styling

Works now.

But whats with Point 3 ? Can the elements not be left aligned / not indented ? Whats the point of indenting ?

**Comment by Nicola1971** [comment]
@modxuser , probably Re2 CSS needs some cleanup, because most of styles just overwrite original modx re styles, but if you have modified something in the core, you need to think about your mod for the first issue cause :)
Anyway, is not the first time that I see issue compressing CSS. We can do some validate tests to find errors, but I don't think evo manager themes needs compressing (is still very fast in all my sites)

**Comment by modxuser** [comment]
@Nicola1971 

As already mentioned, I do this on a daily basis :) Core changes haven't been made

Compressing is a personal preference, you guys have included Font Awesome, which brings along a huge CSS file and plenty of font files, so anyone with a slow connection may feel the benefit of compressing the files.

I like the new layout, so don't get me wrong, I also like using Font Awesome - it's simply personal preference

Point 3 ?

**Comment by Nicola1971** [comment]
..sorry , for core, I mean deafault files. If you have an issue with the manager theme, you need to think about your modification to the manager theme or plugins, just because I always playing with these things and a lot of times I have done the same error :)

I think that we can remove a lot of duplicated styles from modxre2 CSS to get a file smaller than a compressed version ;) and this is only the first version of this theme and there are some new features to add for 1.2.2

**Comment by Nicola1971** [comment]
@modxuser 
> Point 3 ?

![h1h4pynoutzbaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/21079407/80c403b0-bf91-11e6-9541-e6c037670637.png)

**Comment by modxuser** [comment]
@Nicola1971 

Much better ;)

**Comment by modxuser** [comment]
@Nicola1971 

Can I close this now ? I don't know if anyone else needs to be asked ref. this small modification ?

**Comment by Nicola1971** [comment]
@modxuser added a commit for this issue, you can close if you want

**Comment by modxuser** [comment]
@Nicola1971 

OK, thanks

**Comment by modxuser** [comment]
@Nicola1971 

I see you have added "fa-calendar", wouldn't it be better with "fa-calendar-minus-o", as the calender icon is the to delete the date, not to open the clander

**Comment by Nicola1971** [comment]
@modxuser fa-calendar is just in the title. for the "clear date" function i used fa-calendar-o (empty calendar)

not sure wich is better, for me, fa-calendar-minus-o does not look very intuitive with very small icons

**Comment by modxuser** [comment]
The thing is, not everyone has miniature browser settings LOL

**Comment by Nicola1971** [comment]
anyway, we should use the same icon in Resource settings (now is the full calendar and is not the right icon)
![download](https://cloud.githubusercontent.com/assets/7342798/21097554/4c1a38ee-c065-11e6-810c-0acbfc173144.png)

@pmfx what do you think?

**Comment by modxuser** [comment]
True, just seen that as well
