### ISSUE TITLE
Evo 1.2 Ticker Widget missing

### ISSUE THREAD

**Issue by MarkTWIC** [modxcms/evolution#1095]
When upgrading to Evo 1.2 I didn't find the Ticker Widget I've used for some time. Is there a reason for this?

**Comment by Nicola1971** [comment]
Ticker, Marquee and Floater

don't know who removed, but these kind of widget are not very used today and i suspect are obsolete and no more valid W3C

**Comment by MarkTWIC** [comment]
I still think they're nice to use if maintained simply. I used it as a simple indication of updates, the info was also elsewhere.

If I understand correctly there might be accessibility issues with moving text and one thing was that the user should be able to stop them. 

It seems unlikely they're going to be added back into the CMS. Thanks for the quick reply.

**Comment by yama** [comment]
1. These widgets require a too old version of MooTools
2. That version of MooTools has not been maintained for more than 10 years
3. There is a security concern as using MooTools placed in the administration screen area
4. MODX is trying to solve dependency on MooTools

It deleted for these reasons. Equivalent functions can be implemented as modifiers.
I will look it up later.

**Comment by MarkTWIC** [comment]
Thanks for the answer. An alternate solution would be appreciated but I'll live without the ticker if I have to, I'm sure I can indeed find some other way if I really want it. By the way the new version of Evo is excellent. Thanks for the hard work.

**Comment by Nicola1971** [comment]
@MarkTWIC you can replace with a multitv
