### ISSUE TITLE
Question: siteCache.idx.php

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1096]
@yama , @dmi3yy , @Deesen 

As I am re-building one of my very large sites, I am always open to make it faster, moving away from 3rd party code to use new in-built / core code.

Since I updated one of the sites I noticed that the "siteCache.idx.php" has increased its size by "70kb" without me even adding anything to the system, I just updated, that's all. I found out one of the reasons was that default code was put back into the database, for example the captcha words and the default email messages for sign-up / reminder etc. (to note: these are deleted in the manager configuration, so they shouldn't in my opinion still be put into the DB as defaults)

Getting to my question: why does all of the manager settings as well as plugins etc. have to be in this file ?

Would it not be better to create separate URL and system / manager configuration files ?

**Example:**
urlCache.idx.php - specifically for URLs
siteCache.idx.php - for the rest

A large site using nested FURLs can bloat the "siteCache.idx.php" quite easily, as I found out, removing excess bloat like the manager stuff would be in my eyes a benefit, or not ?

@dmi3yy has proven that Evo can now cater for tens of thousands of documents, but that won't happen if you are using FURLs and caching all the pages - why, because the size of the "siteCache.idx.php" will be way to big for the server to manage, or you will have to pay extortionate amounts for a dedicated server with tons of power and even then, I am not sure it would work, due to server time limits (not a DEV so can't say)

**Side Note:**

Being able to place everything on one line in this file is great, but plugins like managermanager have code that refuses to stay on one line - try putting the content of the "properties tab on one line - it won't happen"

**Comment by yama** [comment]
In my opinion, this is a remnant of Etomite.
In the past, handling databases was troublesome as compared with the present. Therefore, the number of CMSs that perform complicated design increases.
By about the same time Etomite was able to create a developer friendly system by the cache idea. Thinking back then, I think it was a good idea.

However, it is now faster to read directly from the database.

The Japanese version of Evolution under development has a size of 30,000 pages, but the size of siteCache.idx.php is only 9 KB. The benchmark value is also very good. Perhaps the lightness is the same for sites with over 1 million pages. I want to transplant this.

**Comment by dmi3yy** [comment]
Use settings aliasListingFolder 

And no metter 5000 docs or 500000

Отправлено с iPhone

**Comment by modxuser** [comment]
@yama that sounds great

@dmi3yy does that have an impact on performance / speed ?

**Comment by dmi3yy** [comment]
speed x2  and memory x2-3 smaller )


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 13 декабря 2016 г. в 11:22, modxuser написал:

**Comment by modxuser** [comment]
Ah, so it is slower, OK, I will give it a try and see how the performance on the live dedicated server is, your time is much appreciated, thanks

**Comment by Deesen** [comment]
I´m sure he meant faster, not slower ;-)

**Comment by modxuser** [comment]
on my localhost its slower

**Comment by dmi3yy** [comment]
faster when docs 5000+  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 13 декабря 2016 г. в 11:27, modxuser написал:

**Comment by modxuser** [comment]
ah, haven't reached 5000 yet, but getting there LOL :)

**Comment by dmi3yy** [comment]
better results if docs 10 000+ )

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 13 декабря 2016 г. в 11:29, modxuser написал:

**Comment by modxuser** [comment]
I can hit 5000 by the end of March / April, but 10,000 is somewhat in the distance :)

Just checked the sitecache and see that the default email & captcha stuff is back in there again, even though I deleted it per hand from the DB - I noticed that when the configuration is modified and saved, that the content is placed back into the database every time - that is, if it is missing

Why is this ? If I delete it from the configuration, surely there shouldn't be default stuff left in the DB or put back into the DB.

**Comment by modxuser** [comment]
A side note: with so many documents I am finding the tree is starting to take a long time to load.

I know child pages can be edited by simply clicking on the parents page and clicking view children, but how do others manager such large sites.

I've seen "Collections" in Revo, and found that to be good, makes management somewhat easier

Thoughts ?

**Comment by dmi3yy** [comment]
30 000 docs with 100 tv )  
no problems: http://take.ms/obvoa
http://velosiped.com

in manager to all ok   
http://take.ms/4S3Nz  

tree  with  3000+ docs open 2-3 sec   

all another open quick 0,1- 0,5 sec   

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 13 декабря 2016 г. в 11:38, modxuser написал:

**Comment by modxuser** [comment]
@dmi3yy Impressed :)

**Comment by modxuser** [comment]
heads up @dmi3yy 

I just updated the live website and updated the server to use PHP 7

I see no speed decrease, so thanks for the info.

**Comment by modxuser** [comment]
Just a heads up:

I have found the reason why when defualt email and captcha is removed from the manager it is always in the database and if you remove it from the DB manually and save the configuration, it will be back again.

You need to remove the content of these elements from the file for your specific language:

- captcha_words_default
- system_email_signup
- system_email_webreminder
- system_email_websignup

File path: manager/includes/lang/XXXXXXXXXX.inc.php

Changing "XXXXXXXXXX" to your language

Once you have removed the contents, go to the manager, and resave the configuration. The DB is updated and no-longer has the default wording

**Comment by yama** [comment]
- system_email_signup_default
- system_email_websignup_default
- system_email_webreminder_default
- captcha_words_default
- siteunavailable_message_default

I think these are the five. how is it? I can fix it right away.

**Comment by modxuser** [comment]
@yama 

My personal thoughts:

If you delete the information from within the manager, I see no reason it should be kept in the datase under the default tables

Why, because once it is deleted from within the manager the defaulst are not reset / re-applied when the configuration is saved

So the defaults take up valuable space in the sitecache for no reason

I would be happy to see them removed from the DB, that way I don't have to modify core files and have to remember to modify them again when I update
