### ISSUE TITLE
The login state is synchronized at multiple sites with the same site_sessionname

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#1097]
Strange situation. The login state is synchronized at multiple sites with the same site_sessionname.
This situation occurs when the site is duplicated.
It is necessary to set unique site_sessionname for each site.

**Comment by modxuser** [comment]
That's been like that for years :) I didn't realise that it's a possible bug

When I duplicate a site for testing or updating I always manually change the number in the config.inc.php

**Comment by bossloper** [comment]
Yes I create all my sites by cloning and have to remember to change the session name each time I clone. This is a nice help.

I assume there are no security risks, and that the session name cannot easily be reengineered?

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/45
