### ISSUE TITLE
[Security] Session Adoption issue

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#1098]
https://www.google.com/search?q=Session+Adoption+session_regenerate_id
I do not think it's serious vulnerability, but I would like to fix it.

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/v1.2/manager/processors/login.processor.php#L198
Should insert "session_regenerate_id(true);" into this line, but it will not work. Does anyone know why?
I will not be able to log in. It seems that returning to the login screen after redirecting.
Correctly rewritten the session ID by looking at the cookie.

**Comment by Deesen** [comment]
Hmm for me it works, can login as usual on my localhost with

    session_regenerate_id(true);
    $currentsessionid = session_id();
