### ISSUE TITLE
PHP-controlled CronJobs like Wordpress

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#1099]
https://github.com/WordPress/WordPress/blob/master/wp-cron.php

Related to issues
- check system files regularly via cronjob https://github.com/modxcms/evolution/issues/944
- scheduled automatic DB-snapshots https://github.com/modxcms/evolution/issues/1028
- Evocheck Cronjobs like https://github.com/extras-evolution/evocheck/issues/2

**Comment by nick0** [comment]
+10

**Comment by Nicola1971** [comment]
@Deesen check this:
http://www.phpjobscheduler.co.uk/

**Comment by Deesen** [comment]
Thanks. And there are a lot of other scripts https://www.google.de/search?q=php+job+scheduler . Question is how to exactly implement a cronjobs-feature into Evo. 

- How will the user-interface look like, which options will it have?
- Will you have a list of predefined options delivered by custom modules like "EvoBackup" or "EvoCheck"? 
- Or will users have to define the URL / parameters manually, that should be called by a cronjob?
- etc.

**Comment by Nicola1971** [comment]
I'm not a cron expert, but i think we need to add two features

* Cronjob support for backup (so you can set your crons from server panel)

* A Fake Cronjob Module: for users without cronjob access (like wordpress), ie phpjobscheduler

**Comment by Nicola1971** [comment]
this a snippet based on AutoEvoBackup, we could use with cron (not tested).
https://github.com/Nicola1971/CronEvoBackup

1) install
2) create a page cron.html with this call ```[!CronEvoBackup? &mode=`dbonly` &zipdb=`0` &rootfiles=`0` &deletesql=`0` &customfiles=`0` !]```
3) run the page 

you can call the page with parameters in url:
```www.domain.com/cron.html&mode=light&zipdb=1&deletesql=1&customfiles=1&customfold1=shop```

**Comment by bossloper** [comment]
www.domain.com/cron.html would need to be secured in some way.

**Comment by Nicola1971** [comment]
another way is a fakecron module, that runs the snippet ($modx->runSnippet) inside the manager

**Comment by Nicola1971** [comment]
i started to _trying_ to convert **phpjobscheduler** to a evo module, but a lot of things still not working :) :

![l5swtouhbaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/21804201/027d1a0a-d72e-11e6-84c3-0941a94edccc.png)

![cfgyvl rekaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/21804204/05fb4210-d72e-11e6-8574-b4bcf5a84c19.png)

![2fcfrbfrqwwaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/21804206/09725226-d72e-11e6-845b-75ffe32bd142.png)

**Comment by nick0** [comment]
I really like the idea of the "fake cron" module, so it can all be done within Evo, preferably in the current backup section so its all together. This would be more seamless and slicker and consistent with WordPress' ease of backup scheduling.
I personally don't know how to do Cron jobs, and won't always have access to do them either. I am sure many other Evo users are in the same boat.
Something that works within Evo for non technical users would be amazing.
Thanks so much for your great work.

**Comment by Nicola1971** [comment]
OK, i got a very alpha, but working phpjobscheduler "fake cron" module. :-)

The package includes:

1) A basic **phpjobscheduler  module**
2) A **CronEvoBackup** snippet (to create backups like EvoBackups)
3) A small plugin **firepjs**  to render the invisible image on frontend
4) An example php file to run the CronEvoBackup snippet (thank @pmfx for the tip ) https://github.com/Nicola1971/JobScheduler/blob/master/assets/modules/jobscheduler/cron-backup-sqlonly.php

In this way we can run any snippet with Fake Crons

I think is a nice starting point.

Anyone want to try?
https://github.com/Nicola1971/JobScheduler

Just install with Package Manager and try

**Comment by Nicola1971** [comment]
updates:
![by2xsj2yrevbaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/21909524/adb67d80-d918-11e6-84ba-2d8a0ef71a79.png)

![f3gykd4jxzpoaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/21909542/b260374a-d918-11e6-9454-0c13bcb2c757.png)

![bz9hcoq3h2udaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/21909538/b002e2ea-d918-11e6-89f5-33deedd1257a.png)

![jsqbm15on0qaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/21909546/b6661044-d918-11e6-9656-584ebc0490a4.png)

**Comment by nick0** [comment]
Awesome @Nicola1971, I cant wait to test it.

Can I please ask a basic question? Up above to mentioned "Just install with Package Manager and try".
Where can I download the package manager?
Is this it?: http://extras.evolution-cms.com/packages/utilityi/packagemanager.html
Thanks

**Comment by bossloper** [comment]
'Is it this?' - Yes, just install from 'Extras' module. 
As an aside - To me as 'Package Manager' is now [depreciated] https://github.com/Jako/PackageManager I'd like to see it merged into Extras functionality as one module for all package management needs.

**Comment by nick0** [comment]
Beauty, thanks for confirming that @bossloper, I will give the depreciated Package manager a crack. Cheers

**Comment by Nicola1971** [comment]
Agree with @bossloper - for my way to work with Evo, Package Manager is the most important extra. I always work with custom packages: templates, sets of chunks, snippets and plugins.

I've tried @dmi3yy [Install Manager](https://github.com/dmi3yy/modx-install-manager), but cant get it work

**Comment by bossloper** [comment]
@Nicola1971 - getting an error as my MODX install is in a sub-directory.
https://github.com/Nicola1971/JobScheduler/blob/master/assets/modules/jobscheduler/pjsfiles/config.inc.php#L6
Think this needs to be using MODX_BASE_PATH ?

**Comment by Nicola1971** [comment]
yes, need more integration with modx api, for base path and manager path (actually does not support alternative manager folder names too) and requires hardcoded path to work in my windows wamp  localhost, 
```include_once ($_SERVER['DOCUMENT_ROOT'].'evo-test/manager/includes/config.inc.php');```
so, i suppose need the something similiar in subdomains enviroments

before more api integrations and any other improvements from this beta1 - i need to be sure that phpjobscheduler satisfy our needs for Evo
