### ISSUE TITLE
parse Snippet not work with [[ [[ 

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1100]
http://take.ms/oPgO7

This all ok 
http://take.ms/pi8zW

But if change to [[Ditto not work ((( 

need normal work:  
[[ [[ 
[! [! 
[[ [!
[! [[

**Comment by bossloper** [comment]
Is this already logged as issue #1089 ?

**Comment by dmi3yy** [comment]
yes not see close this )

**Comment by dmi3yy** [comment]
The same problems with multilang (( 

[!if? &is=`[%mode%]:eq:ru` &then=`bla bla bla`!]  - not work 

but 

[%mode%]  return  ru

**Comment by yama** [comment]
```
[%mode%]
```
What is this value?

**Comment by dmi3yy** [comment]
Yams or blang    Or something else for multilang 

Отправлено с iPhone

**Comment by yama** [comment]
https://github.com/extras-evolution/YAMS
https://github.com/bumkaka/bLang
Is this?

**Comment by yama** [comment]
```
// hook to OnParseDocument
$modx->documentOutput = str_replace('[%mode%]','ru',$modx->documentOutput);
```
I made a simple plugin like above and tried it, but it was no problem.
Would you open docid_1.pageCache.php in a text editor and check how snippet calls are handled?
If there is something wrong, calling OnParseDocument may be able to solve it.

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/9feea669970c2852a8522cfbf2aa5b8e3b0464e8/manager/includes/document.parser.class.inc.php#L1523

Insert on the next line.
```
$this->invokeEvent('OnParseDocument');
```
Does this solve it?

**Comment by dmi3yy** [comment]
no 
http://modx.im/blog/questions/4876.html#comment39846

**Comment by yama** [comment]
I want to know where the value of [%mode%] comes from. This process is simple, so I can fix it if I can reproduce it. Is there a test environment etc?

**Comment by Deesen** [comment]
[%mode%] looks like evoBabel-plugin -> https://github.com/extras-evolution/evoBabel/blob/master/install/assets/plugins/plugin.evoBabelPlaceholders.tpl#L33
