### ISSUE TITLE
After Upgrade to Evo 1.2 all @inherit bindings not work

### ISSUE THREAD

**Issue by rwam** [modxcms/evolution#1101]
This is just a hint or a please to improve the docs!

**My problem:**
After an upgrade from MODX 1.0.4 to 1.2 all @bindings no longer work and I don't know why. I cannot find any info in the changelog or in the issues.

**Solution:**
After hours of research and trail and error I found out, that all (at)bindings must be capitalized. So I change all @inherit or @select bindings to @INHERIT resp. @SELECT and it works well.

**Comment by modxuser** [comment]
Hi @rwam 

The following is taken from the Evo docs.

> The format for using the five types of data source bindings available to all template variables follows:

    @FILE file_path
    @DOCUMENT document_id
    @CHUNK chunk_name
    @SELECT sql_query
    @EVAL php_code
    @DIRECTORY _path_to_folder

Note that they are all written in uppercase, I think the problem may have been beforehand, as I find no information about using lowercase - I personaly have never used lowercase, always uppercase

**Comment by rwam** [comment]
Hi @modxuser,

the following is the current Evo doc for @INHERIT: https://docs.modx.com/evolution/1.0/developers-guide/template-variables/(at)-binding/(at)inherit. Not really helpful, isn't it? But ok, yes I found the docs, but a hint to use uppercase would be nice and it would have saved me a few headaches. And maybe an entry in the changelog would also helpful because for me it's a breaking change. I don't know when the change happens, but several Evolution installations I build in the past few years are using lowercase (at)bindings. This is taken from old docs or tutorials and it worked.

Ciao
Ralf

**Comment by modxuser** [comment]
Nobody is saying that the documentation is perfect - it never was, not only for bindings.

The same goes for Revo, take a look there and you won't find anything that says use uppercase.

I would think that the use of uppercase in the actual documentation would be enough to state that you have to use uppercase - the Evo + Revo docs are displayed the same, both use uppercase

Old docs ? Where are they, would love to see them, maybe the the RTFM could be updated with them. Where are the tutorials that you used, maybe they could also be used, obviously after being corrected if they are using lowercase

**Comment by rwam** [comment]
First: the documentation of MODX is fine, very helpful and much more better than other systems ;)

Puh, it's nearly impossible to find one of these tutorials after years. One of them must be situated [here](http://de.modx.com/forum/thread/2450/diskussion-multidomain-loesung-fuer-modx), because I had a setup like described there. But unfortunaly the referenced tutorial is not available online ;( Other tutorials or sites like wiki.modxcms.com were updated in the meantime so I cannot provide any doc. Sorry for that.

I've created this issue to pointed out that there can be a problem. I did not just use lowercase, but I had to orient myself to something.

Ciao
Ralf

**Comment by rwam** [comment]
I see, in past versions there was used the following check on the file `manager/includes/tmplvars.commands.inc.php`:

    $regexp = '/@(' . implode('|', $BINDINGS) . ')\s*(.*)/im';

and

    if ((string) $tv['value'] !== '' && !preg_match('%^@INHERIT[\s\n\r]*$%im', $tv['value'])) {
      …
    }

And this regex matches lowercase too, because it used caseinsensitive flag.

It seems one spot was fixed 2013 with https://github.com/modxcms/evolution/commit/6e8e9a57b33024a69737a417bc7b7b0b4098534f#diff-53a01587f64d37ca1d819d6d55936df0 But on the current version I can still find one other spot on [Line 84](https://github.com/modxcms/evolution/blob/develop/manager/includes/tmplvars.commands.inc.php#L84)

Is it still necessary?

**Comment by yama** [comment]
Indeed, the regular expression modifier is im
I think that this is not officially unified. Even now, for example, the "If" snippet has lower-case parameters to call as "@eval".
I think that it is better to accept both upper case letters and lower case letters unless there is a particular reason. how is it?

**Comment by modxuser** [comment]
If it accepts both, the documentation has to change

I have a copy from the original documentation here, written as uppercase and no mention of lowercase

It's a compiled HTML Help file, I don't know if it can be read on a MAC, but PC it works - see attached zip

[modx 0.9.1 v1.1 06.07.2006 - online docs .zip](https://github.com/modxcms/evolution/files/651489/modx.0.9.1.v1.1.06.07.2006.-.online.docs.zip)

**Comment by Deesen** [comment]
Maybe this issue can also be related to https://github.com/modxcms/evolution/issues/503 in terms on "case sensitivity"

**Comment by dmi3yy** [comment]
i Docs for binding all time use @UPPERCASE i think its correct and need case sensitivity.

**Comment by rwam** [comment]
Then should [Line 84](https://github.com/modxcms/evolution/blob/develop/manager/includes/tmplvars.commands.inc.php#L84) change too, shouldn't it?

**Comment by yama** [comment]
I think that it is better to write the document firmly beforehand and to revise the php code after a while. Because there are other users who think "we can use lowercase letters". To avoid confusing them suddenly. I want to make v1.2.1 a quiet release.

**Comment by rwam** [comment]
But lowercase letters don't work?! Because of the [ParseCommand](https://github.com/modxcms/evolution/blob/develop/manager/includes/tmplvars.commands.inc.php#L129) and so the caseinsensitive flag on line 84 is needless.

**Comment by dmi3yy** [comment]
move on new repo 
https://github.com/evolution-cms/evolution/issues/43
