### ISSUE TITLE
403 forbidden cache image

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#1102]
Hi,
After update 1.2,
my cache image are 403 forbidden.
I delete all cache images and recache , 
Remove htacces, 
Change file and folder permission to 777
owner www-data
but it still happen.
assets/cache/images/148x120-myimage.jpg

note : Phpthumb work well and it generate cache image, make folder.

**Comment by dmi3yy** [comment]
in assets/cache/images/  
have file:  .htaccess?


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 14 декабря 2016 г. в 11:31, mgzawlinoo написал:

**Comment by mgzawlinoo** [comment]
Yes bro . 
Like this 
<IfModule !mod_authz_core.c>
Order allow,deny
Allow from all
</IfModule>

<IfModule mod_authz_core.c>
## configuration for Apache 2.4
Require all granted
</IfModule>

**Comment by mgzawlinoo** [comment]
I also remove that htaccess but it still forbid the cache images.

**Comment by mgzawlinoo** [comment]
Remove main htaccess from 
access/cache/.htaccess 
(it ok)

**Comment by dmi3yy** [comment]
if delete then can’t work correct )  

put only 2 strings  
Order allow,deny
Allow from all  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 14 декабря 2016 г. в 11:38, mgzawlinoo написал:

**Comment by dmi3yy** [comment]
delete from assets/cache/.htaccess   incorrect for security reason  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 14 декабря 2016 г. в 11:40, mgzawlinoo написал:

**Comment by mgzawlinoo** [comment]
Hi dmi3yy
Only put 2 strings ...
Now it's work.
Thank you .
