### ISSUE TITLE
Translation of a string, (minor issue)

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1104]
Can we add this string in translation?
I think its using an other existing string or its hardcoded.

![needs-translation](https://cloud.githubusercontent.com/assets/523389/21184025/e1b35c86-c20a-11e6-91fe-6a2f1767e1be.jpg)

**Comment by Deesen** [comment]
I think this is $_lang['defaulttemplate_title']

**Comment by fourroses666** [comment]
Yea sorry, found it yesterday.

**Comment by fourroses666** [comment]
Hmm, looking a it further, that string is being used for the Config page too.`System Default Template` 208. Would like to remove the `:`

![st](https://cloud.githubusercontent.com/assets/523389/21217036/6e0d0c32-c2aa-11e6-9d16-d057d2646c76.jpg)

I know its a minor thingy :-o 
On the other hand I can remove the `:` 

The Config page actually isn't consistent with or without anyway.

**Comment by Deesen** [comment]
Yes then it will be an issue for other languages too I guess. We should just add a new key for this purpose.
