### ISSUE TITLE
Suggestion: Update / Release Intervals

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1105]
I am not sure if I am in any position to suggest this, but I see nobody else doing so.

I would like to suggest that future releases are shorter, meaning:

1.1 was released on the 29th of Februaury 2016, 1.2 was released 01st December 2016, 10 months apart. But what has happend within the 10 months has been amazing

Tons of work went into the 1.2 release, but we are seeing more and more bug reports coming back. Some minor but some major site breakers

The latest hack can be seen as two things, a major hinderance and a blessing. Why a blessing, because loads of Evo users have been forced to update their sites to use 1.2 and they are now reporting back with their problems.

Major releases are all well and good, but if these releases are not fully tested, they can be a major problem.

Any thoughts ?

**Side note(s):**
I see no point in writing this in the LLC forum as the majority don't use it
Time for the Community Evo Site + Forum ?

**Comment by dmi3yy** [comment]
No one want tested Beta and RC :( 
Then we have only one way. 
1.2 no stable,  1.2.1 stable 
1.2.2 no stable, 1.2.3 stable ) 

then all be fine)

**Comment by fourroses666** [comment]
@modxuser I'm pretty sure this will be the case, shorter releases. Which also mean less bugs/issues.

Like most of the time the first release after a big release will be the most stable one if you know what I mean.

_I don't have allot of advanced sites and don't find much bugs when testing.
Just did an update on a site -> 1.2.1 beta, which is being released very soon (1.2.1), and didn't find any bugs._

**Comment by modxuser** [comment]
Yes I understand

The problem (in my opinion) is the lack of involvement from users who solely use the LLC forum - those who use GitHub on the other hand are more involved.

This probably has to do with the lack of a relevant Evo forum and information portal

Something like adding RC releases to the information section of the manager / create a section for RC releases

And on the other hand, testing lets say 10 updates is a lot easier than testing 100 :)

Time to move the security link for the information section in the manager away from the LLC section and add it to a bespoke Evo website - that way no-one has to beg the LLC to add stuff to their website and it would be quicker

**Comment by dmi3yy** [comment]
I wand do  reliases  1 per month   its been easy to test )  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


среда, 14 декабря 2016 г. в 16:59, modxuser написал:

**Comment by modxuser** [comment]
Although I am personally moving away from web-development and making my hobby my job, I will still be using Evo in the future and as such would love to see it grow again. Shorter update intervals make for a better move and as @dmi3yy has mentioned, releasing updates on a monthly basis would be great.

Who knows, small updates could be patches, so that there is no need to completely re-install - which could be a problem for large sites

Another matter, although not 100% to do with the releases is the documentation. It has been brought to attention that it has lots of missing content and outdated content

**Comment by modxuser** [comment]
May I propose the following:

1. Changing the Security Notices feed from the LLC to a community driven feed
2. Changing the MODX News feed from the LLC to a community driven feed

I think this would improve the attention to Evo, by removing irrelevant Revo / LLC information
