### ISSUE TITLE
GitHub Question - Pull Request

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1108]
Sorry for being to stupid to do this myself, but I am not getting to grips with GitHub properly

I decided if the future brings regular updates that I would like to not have to add  a default "index.html" file to all the folders that are missing them

So I have created a repository with the Develop version of Evolution and added the files, a total of 254

Can someone help me get them into the main Evolution Develop repository please, maybe @Deesen or @fourroses666 etc.

[The commit is here](https://github.com/modxuser/Evo/commit/20e817e683058580aef8b395b573687a7fba6d0f)

**Comment by yama** [comment]
I think that it is better to stop index.html addition to all folders. Although it is another CMS, maintenance has become difficult, I have been puzzled. I think that the original purpose of "index.html" is not to blindfold.

**Comment by modxuser** [comment]
Thats correct, its not the correct purpose, but sadly there are still hosts out there that list directories

Adding the files at least stops direct visibility in those situations

**Comment by yama** [comment]
Can not be prevented with .htaccess? In that case, it would be better to add index.html.

**Comment by modxuser** [comment]
Correct - dedicated servers are easy to manipulate, but shared hosting isn't optimal in many situations

I have clients on both, and as I still support them, I add the index.html, some can override via htaccess or config, others can't

**Comment by yama** [comment]
Shall I create a simple plugin that automatically adds index.html to all folders? Maybe, I think it is beneficial for other extras not included in Evo's package.

**Comment by modxuser** [comment]
Sounds good @yama

**Comment by modxuser** [comment]
thats probably better than adding what I have done, especially for the future when more folders are added or swapped out

**Comment by yama** [comment]
Ok, please wait for a while. It is better to have an operation screen, so module is good.

**Comment by modxuser** [comment]
OK, thanks for your help and time

**Comment by Deesen** [comment]
Maybe we could add that feature to Evocheck? Sounds to me like it makes sense.

**Comment by yama** [comment]
Oh, it's more better!

**Comment by modxuser** [comment]
@Deesen , @yama 

Can I close this now ?

**Comment by Deesen** [comment]
I think so as it is noted in Evocheck.

**Comment by modxuser** [comment]
OK, Thanks
