### ISSUE TITLE
English-british.inc.php not detected

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#1110]
In manager

**Comment by bossloper** [comment]
Just wondering where this was not working? It seemed to be working without this fix for me.
As English is the fallback here so already included?:
https://github.com/modxcms/evolution/blob/develop/manager/index.php#L161

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/develop/manager/actions/mutate_settings/functions.inc.php#L7-L30
There is a problem with the processing of this part. I will fix it with v1.2.2
