### ISSUE TITLE
Evo 1.2 tested, found following issues

### ISSUE THREAD

**Issue by michael-big** [modxcms/evolution#1111]
During testing Evo 1.2 and checking the source code, i found the following issues:

**Snippet Ajaxsearch:**
	File asPhxParser.class.inc.php, line 225:
		`$modx->config['etomite_charset'] `
		should be change to
		`$modx->config['modx_charset'] ` 

**Snippet Ditto:**
	File phx.parser.class.inc.php, line 243:
		`$modx->config['etomite_charset'] `
		should be change to
		`$modx->config['modx_charset']`  

**Snippet Wayfinder:**
	File examples/cssplay/dropline.css, line 17:
		Typo: `##b3ab79`  

**Install:**
	File actions/action_summary, PHP Version check in line 9 to 13:
		add display of current PHP Version, e.g.:
		``} else {
echo "<span class=\"ok\">" . $_lang['ok'] .'</span><strong>'. $_lang['you_running_php'] . phpversion() . "</strong></p>";``

File sqlParser.class.php, line13:
		`function SqlParser`
		change to 
		`function __construct`

**Manager:**
File actions/resources.static.php:
Unordered Lists: Missing `</li>`
Input placeholders: Text ist hardcoded, move to `$_lang`
Combined View: No help button like in all other tabs 

File includes/actionlist.inc.php:
Double entry 81
	
File includes/controls/datagrid.class.php, line 118-119:
``if(!$type_format) $type_format = "%A %d, %B %Y";
$value = strftime($type_format,$value);``
change to 
`$value = $modx->toDateFormat($value);`
and add `global $modx;` in function

File document.parser.class.inc.php
Line 126:
`$this->decoded_request_uri;` this function does not exists
Line 217: 
move upwards after line 191 for better reading
Lines 2741 to 2754:
function rotate_log should be moved to log.class.inc.php
Line 3181:
`$this->config['virtual_dir']` was never set, can be removed?
Line 2107 ff:
Change to HTML5-syntax

File purge_plugin.processor.php, Lines 5-6:
``
$e->setError(3);
$e->dumpError();
``
change to 
`$modx->webAlertAndQuit($_lang['error_no_privileges']);`
And i think, the file includes/error.class.inc.php can be removed
	

**General:**
Tons of hardcoded messages should be moved to language files.

In several files there is a `class="transition"`, which is never set.

Is this still in use?: `$theme_refresher`

WebAlertAndQuit seems to be buggy: 
1. Error messages ist displayed twice
2. After clicking OK, i got sometimes an CSRF attempt message. (Firefox on OSX and Windows10 on local and live server; reproducable: try to unpublish startpage; Safari, IE11 and Microsoft Edge are OK) 

DocumentDirty seems not working correct in OSX Safari: Changed text in Resource content, then moved directly to another document: Message ist displayed once in a session, afterwards: no more error message are displayed

Create/Edit User and Create/edit Web User: Date of birth: DateTimepicker Year range is wrong: -+ 10 years, should be 0 to -80 or so

Change to HTML5-syntax in:
manager/actions/mutate_plugin_priority.dynamic.php
manager/actions/resource_selector.static.php
manager/frames/menu.php
manager/frames/tree.php
manager/media/browser/mcpuk/browser.html
manager/media/browser/mcpuk/browser.php
manager/media/style/common/login.tpl
manager/media/style/common/manager.lockout.tpl
manager/media/style/MODxRE2/login.tpl
manager/media/style/MODxRE2/manager.lockout.tpl

**Comment by modxuser** [comment]
@yama , @dmi3yy , @Deesen 

That's great, by the looks of things you are a Developer, are you going contribute to Evo and fix these issues yourself ?

I presume fixing them would be beneficial to your AvenirCMS, as it is a duplicate of Evo

I see that you have taken the time to also create a website and have translated [the documentation to German](http://avenircms.ch/dokumentation.html), maybe interesting for @Deesen

**Comment by yama** [comment]
Thank you, it is meaningful information. By thinking like this to clean every corner, I think that it is possible to prevent serious trouble from occurring.
However, some users are waiting for the release of 1.2.1, so I think that it is better to deal with these in 1.2.2.

**Comment by dmi3yy** [comment]
need recheck in 1.3.0 
if somethink not do write here plz 
https://github.com/evolution-cms/evolution/issues
