### ISSUE TITLE
Ditto "paginateAlwaysShowLinks" not always showing

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1115]
@dmi3yy , @yama , @Deesen 

I have found the reason for the problem, the commit is [here](https://github.com/modxcms/evolution/commit/7686c4374131ab21d234461d01a9e3fe7ddab4fb)

This code needs to be modified as it breaks compatibility

If you set: `&paginateAlwaysShowLinks=`1` the previous and next links are no-longer shown

This requires a workaround, something like:

if paginateAlwaysShowLinks is set to "1" then show, else don't show

**Comment by dmi3yy** [comment]
ok i fix it)

**Comment by dmi3yy** [comment]
done

**Comment by modxuser** [comment]
Thanks @dmi3yy great work as always
