### ISSUE TITLE
After update images disappear, fix with .htaccess

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1118]
When I update a site the images disappear.

I think we need to add a .htaccess file here;
https://github.com/modxcms/evolution/tree/develop/assets/cache

With content;
`order deny,allow`
`deny from all`

Need to recheck whats going on but something is wrong.

**Comment by fourroses666** [comment]
Hmm, when uploading development version I see in: /cache/images/.htaccess

```
<IfModule !mod_authz_core.c>
Order allow,deny
Allow from all
</IfModule>

<IfModule mod_authz_core.c>
## configuration for Apache 2.4
Require all granted
</IfModule>
```

This hides my images. When changing it into;
`Order allow,deny`
`Allow from all`

It works again.

**Comment by fourroses666** [comment]
Looks like this is the problem on my sites:
https://github.com/modxcms/evolution/blob/develop/assets/cache/images/.htaccess

**Comment by fourroses666** [comment]
Nobody got the same issues?

For me images start to show up again after changing /assets/cache/images/.htaccess like;

```
Order allow,deny
Allow from all

<IfModule mod_authz_core.c>
## configuration for Apache 2.4
Require all granted
</IfModule>
```

**Comment by bossloper** [comment]
No, fine for me.
If you try and view the assets/cache/images folder from a browser with the original htaccess file then do you get a 500 Internal server error? If so then it is probably a server configuration issue.

**Comment by fourroses666** [comment]
Never had any issues, as soon as uploading the new .htaccess file I can't reach images.

This just don't work; (/assets/cache/images/.htaccess
```<IfModule !mod_authz_core.c>
Order allow,deny
Allow from all
</IfModule>```

Can't see any images while they are there.
After removing `<IfModule !mod_authz_core.c>` and `</IfModule>` it works again.

**Comment by bossloper** [comment]
Probably your server setup is not setup to work with IfModule.
I'm not sure what the '## configuration for Apache 2.4' part of the file is for and if it is really needed, @esszett might be able to enlighten us, but it is probably not a good assumption that by default all servers will be able to handle IfModule?
Maybe it should be returned to the version given in: https://github.com/modxcms/evolution/blob/develop/assets/cache/images/ht.access

**Comment by fourroses666** [comment]
Don't know about the best solution but I seem to have issues with it for 90% of my sites.
They use Apache 2.0.

Rather have this reverted..

**Comment by esszett** [comment]
Hi there, I'm sorry for causing trouble – my source was related to a Host Europe server-update. I still have no issues with the mentioned htaccess-version, but that maybe is related to a special Host Europe setting?!
https://www.hosteurope.de/faq/webhosting/skripte/skriptanpassungen-fuer-jessie-update/
So I would suggest to revert the htaccess - and just be aware of your hosters announcements, in case things change (apache versions/configs).

**Comment by fourroses666** [comment]
The server I use is located in the Netherlands.
I might not be the only one with this issue.
So maybe its best to revert this pull @dmi3yy @yama  ?

**Comment by bossloper** [comment]
It is down to the particular server host. Some might restrict htaccess for performance and/or security reasons, particularly on shared servers.
+1 for revert.
