### ISSUE TITLE
Quick Manager+ not holding a lock

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1120]
If manager A edits a resource using Quick Manager+ and holds the edit open longer than the 'session timeout' length then the resource becomes unlocked and can be edited by manager B at the same time.

Presuming the 'mailer ping' is not running when using Quick Manager+

**Comment by Deesen** [comment]
Hmm but the mailer ping does work as long as you have the main manager window open. As long as this session is valid, locks should not get removed by manager B. I need to check in detail as per your explanation.

**Comment by bossloper** [comment]
Quick Manager+ does not run the top frame though. (I believe?!) So if you are just on the frontend editing a resource it will only be running the main manager window. It is the mainmenu frame that is doing the ping?

**Comment by Deesen** [comment]
I mean, me I always work with tabs, and I always have a tab with backend and most times one with frontend open. Means I always have a ping, also when using QM.

**Comment by bossloper** [comment]
Yes, for us 'heavy users'. But I have sites where some managers are only on the frontend, some even have 'Manager Login Startup' page set on the manager 'user' tab so after login they never see the backend.

**Comment by Deesen** [comment]
Interesting, thanks for the insight. Then QM needs its own ping-script.

**Comment by Deesen** [comment]
Should work now too.
