### ISSUE TITLE
MODxAPI Library

### ISSUE THREAD

**Issue by tweezy-au** [modxcms/evolution#1121]
For years I've been using modxapi.php to access $modx from a standalone PHP script, as described here: http://wiki.modxcms.com/index.php/MODx_site_menu_in_external_PHP_app

I've just upgraded my site from 1.0.14 to 1.2, and something seems to have broken the standalone script.

Can anyone suggest what the problem might be?

The latest (only?) version of MODxAPI Library 0.1.0, available from https://modx.com/extras/package/modxapilibrary

**Comment by dmi3yy** [comment]
You can you somethink like this without old lib)  


define('MODX_API_MODE', true);
include_once(dirname(__FILE__)."/index.php");
$modx->db->connect();
if (empty ($modx->config)) {
    $modx->getSettings();
}
$modx->invokeEvent("OnWebPageInit");


$out = $modx->runSnippet('test');
$return = array('message' => $out);
echo json_encode($return);  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


суббота, 17 декабря 2016 г. в 14:57, tweezy-au написал:

**Comment by tweezy-au** [comment]
Wow @dmi3yy that was quick! Just what I need - huge thanks :-)
