### ISSUE TITLE
Ditto + Cross references = not working

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1127]
I have tried adding information to my Ditto output by using the "[Cross references](https://github.com/modxcms/evolution/wiki/Cross-references)" that can be found here, but it doesn't work.

The following is my standard call:

    [[Ditto? 
    &parents=`3` 
    &depth=`2` 
    hideFolders=`1` 
    &orderBy=`id ASC` 
    &showInMenuOnly=`0` 
    &showPublishedOnly=`0` 
    &tpl=`@CODE:<tr><td>[+parent+]</td><td>[+longtitle@parent+]</td><td>[+id+]</td><td>[+longtitle+]</td></tr>`
    ]]

I have also tried using the following template code:

    &tpl=`@CODE:<tr><td>[+parent+]</td><td>[*longtitle@parent*]</td><td>[+id+]</td><td>[+longtitle+]</td></tr>`

But this doesn't work either

Any ideas @yama

**Comment by yama** [comment]
```
&tpl=`@CODE:<tr><td>[+parent+]</td><td>[+longtitle@parent+]</td><td>[+id+]</td><td>[+longtitle+]</td></tr>
```
[+longtitle@parent+] does not work. It works only with [*resource variables*] or [*template variables*].
I think that it is convenient if we can use it in the place holder, but since large-scale repair is necessary, I will consider it in the next version.

**Comment by modxuser** [comment]
@yama thanks for the feedback

I thought it would work "out of the box" as it's part of the core, I didn't realise that Ditto has to be modified as well

Hopefully it's something you will consider for a future release

Cheers

**Comment by yama** [comment]
It's easy. I'll fix it next month
