### ISSUE TITLE
Maxigallery stopped working

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1129]
I have an old site which uses maxigallery. Updated it from 1.0.14 too 1.2.1beta

```
Error : mysql_query(): Access denied for user ''@'localhost' (using password: NO)

File 	/home/xxx/domains/xxxnl/public_html/assets/snippets/maxigallery/maxigallery.php

Source 	$query=mysql_query("DESC $mg->pics_tbl");
Current Snippet 	MaxiGallery
Current Plugin 	YAMS(OnLoadWebDocument)
```

When changing it into mysqli then I get the next error:

`Error : mysqli_query() expects at least 2 parameters, 1 given`

**Comment by MrSwed** [comment]
is it updated ?
https://github.com/yama/MaxiGallery

**Comment by yama** [comment]
https://github.com/extras-evolution/MaxiGallery
It's here

**Comment by fourroses666** [comment]
Thanks, 

(that was the next thing I wanted to do, update maxigallery)

**Comment by fourroses666** [comment]
Hmm, its not in package manager. I will update manually

**Comment by fourroses666** [comment]
Thanks, I updated these two files and it works again.

```
maxigallery.class.inc.php
maxigallery.php
```
