### ISSUE TITLE
Restyle KCfinder/CKeditor/MCpuk -> RE2 styling

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1133]
Did a little test, we should restyle this editor so it looks like it belongs to the manager.
_(Icons and buttons needs to be restyles too)_

![kcfinder-ckeditor](https://cloud.githubusercontent.com/assets/523389/21390337/bb751574-c786-11e6-9eed-6003f8de75e4.jpg)

**Comment by dmi3yy** [comment]
Great



От 21 декабря 2016 г. в 3:32:52 ПП, Marc (notifications@github.com) написал:

Did a little test, we should restyle this editor so it looks like it
belongs to the manager.

[image: kcfinder-ckeditor]
<https://cloud.githubusercontent.com/assets/523389/21390337/bb751574-c786-11e6-9eed-6003f8de75e4.jpg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1133>, or mute the thread

**Comment by fourroses666** [comment]
Need a new theme here: https://github.com/modxcms/evolution/tree/develop/manager/media/browser/mcpuk/themes

And in Config Tab a selectbox to choose theme.

**Comment by Nicola1971** [comment]
very nice @fourroses666

**Comment by fourroses666** [comment]
I do like to have an other system for images and files. But have to deal with it at the moment I guess. There must be many other options to implement.

**Comment by Deesen** [comment]
Another system? What do you mean?

**Comment by fourroses666** [comment]
Don't know a good name for it, Web file manager?
KCFinder feels outdated to me. 
It would be possible to restyle it thow.

**Comment by Nicola1971** [comment]
this is nice http://responsivefilemanager.com/demo.php

**Comment by Nicola1971** [comment]
@fourroses666 on modx.im someone already started to replace kcfinder with responsivefilemanager :)

http://modx.im/blog/addons/4693.html

**Comment by fourroses666** [comment]
Oh thats nice!

**Comment by fourroses666** [comment]
TinyMCE4 has moxie manager, unfortunately its a premium but it looks very good!
http://www.moxiemanager.com/demos/

**Comment by dmi3yy** [comment]
need Write and ask about add in modx evo )


От 28 декабря 2016 г. в 15:49:47, Marc (notifications@github.com) написал:

TinyMCE4 has moxie manager, unfortunately its a premium but it looks very good!
http://www.moxiemanager.com/demos/

**Comment by fourroses666** [comment]
need Write? 

Are you going to ask them if it can be used in Evo? 
Or you need us to write the text to ask it because your English is not good enuf?

**Comment by fourroses666** [comment]
@dmi3yy any news about moxiemanager ?

**Comment by dmi3yy** [comment]
write letter now )

**Comment by dmi3yy** [comment]
its only available as a subscription...

**Comment by fourroses666** [comment]
👍

**Comment by dmi3yy** [comment]
then we can use by default (

**Comment by fourroses666** [comment]
Subscription?  So we have to pay if we would like to use moxiemanager?

**Comment by dmi3yy** [comment]
https://www.ephox.com/moxiemanager/

**Comment by fourroses666** [comment]
https://www.ephox.com/moxiemanager/#plans

**Comment by fourroses666** [comment]
I have asked if we can have a license to use it.
