### ISSUE TITLE
$modx->getChildIds() is very slow

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#1139]
[fast.zip](https://github.com/modxcms/evolution/files/672130/fast.zip)
Adjusting it will make it 3 times faster.
There is even more difference in large-scale sites.

**Comment by yama** [comment]
sorry, It did not get so fast as I supposed

**Comment by dmi3yy** [comment]
But its great if 20 000+ docs 
Old getchildsid work wery slow 

See that in Wayfinder and Ditto 

DocLister not used getchildids and work faster)

Отправлено с iPhone

**Comment by yama** [comment]
Thanks, However, there is a problem to be fixed. 
I have already fixed it in the Japanese version, so I will port it later.

**Comment by yama** [comment]
I think that 1.2.2 or later is better if adopted.
