### ISSUE TITLE
Security PHPMailer

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1143]
Need update
https://github.com/PHPMailer/PHPMailer/blob/master/SECURITY.md

**Comment by risingisland** [comment]
Was this updated in 1.2.1rc or not yet?

**Comment by dmi3yy** [comment]
Not update yet


От 27 декабря 2016 г. в 12:21:58, risingisland (notifications@github.com)
написал:

Was this updated in 1.2.1rc or not yet?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1143#issuecomment-269306836>,
or mute the thread

**Comment by dmi3yy** [comment]
Update

**Comment by tobice** [comment]
It looks like there has been another vulnerability. 

https://github.com/PHPMailer/PHPMailer/blob/master/SECURITY.md

The current version in Modx is 5.2.18 and should be updated to 5.2.20.

**Comment by yama** [comment]
https://github.com/PHPMailer/PHPMailer/blob/1d51856b76c06fc687fcd9180efa7a0bed0d761e/class.phpmailer.php#L1068-L1157
This part is dangerous. I do not think that the problem of PHPMailer has been solved completely, but we can take measures on MODxMailer side.

**Comment by yama** [comment]
```
function validateAddress($address, $patternselect = null) {
	if    (strpos($address, ' ')!==false)  return false;
	elseif(strpos($address, '"')!==false)  return false;
	elseif(strpos($address, "'")!==false)  return false;
	elseif(strpos($address, '\\')!==false) return false;
	else
		return parent::validateAddress($address, $patternselect);
}
```
into modxmailer
It may be good to add it to eform as well

**Comment by modxuser** [comment]
@yama @dmi3yy 

Should Evo users be updating phpmailer in versions 1.2 and below with the changes that have been made to the develop branch ?

Is replacing the whole phpmailer folder with the updated code sufficient ?

Thanks guys

**Comment by yama** [comment]
@modxuser 
There is no need to update PHPMailer. Like the WordPress and Drupal, also Evo does not reproduce the vulnerability of PHPMailer.
But, it is not good to cause misunderstanding, so we will update it for the moment.

**Comment by hexcollective** [comment]
Hi, will you be releasing a patch / guide for updating: modxmailer + eForm?
