### ISSUE TITLE
Installed 1.2.1RC but TinyMCE4 is not working correct

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1144]
See here;

![red](https://cloud.githubusercontent.com/assets/523389/21487637/87adc000-cbce-11e6-9171-0b4b302d16dc.jpg)

**Comment by bossloper** [comment]
I get the same.

**Comment by Deesen** [comment]
Seems related to https://github.com/modxcms/evolution/issues/989

**Comment by yama** [comment]
I understood the cause. Maybe $modx->parseText() problem.
I will fix it later.
