### ISSUE TITLE
tinymce4- table properties hide

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#1153]
Hi,
one of my client said new text editor's table property always show when he edited first row.
I search tinymce4 config and there is not option to hide that features.

![mega myanmar modx cms manager](https://cloud.githubusercontent.com/assets/9032715/21521821/b1be2e0a-cd2e-11e6-847c-81b40cfcc331.png)

**Comment by bossloper** [comment]
In the plugin configuration for TinyMCE4 add

`table_toolbar: ""`

to the Custom Parameters field.

**Comment by mgzawlinoo** [comment]
thank you .
![modx cms manager](https://cloud.githubusercontent.com/assets/9032715/21547354/e5eefca0-ce13-11e6-8161-93f3480088cb.png)
