### ISSUE TITLE
EvoBackup - Backup Evo files and compress into .zip

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#1156]
**EvoBackup**
Backup Evo files and compress into .zip for easy download
Based on **modbak** by stempy https://modx.com/extras/package/modbak (a 10 years old modx 0.9x module) with a lot of new options!

Need testers :)
https://github.com/Nicola1971/EvoBackup

for Evo 1.2.1

![evobackup-beta3](https://cloud.githubusercontent.com/assets/7342798/21550978/42e045ce-cdfe-11e6-8a86-11e3a84f47c7.png)

**Comment by modxuser** [comment]
Is this not heavily related to [this feature request](https://github.com/modxcms/evolution/issues/1028)

**Comment by Nicola1971** [comment]
Yes, but it's just for "manual" backup :( sorry, but helpful for update, moving or  selected backup for hacked sites.

**Comment by Deesen** [comment]
Thanks! It is perfect you remembered & prepared this module, we can extend it now with more features like adding it to future cronjobs etc.

**Comment by modxuser** [comment]
@Nicola1971 don't get me wrong, I think it's good, just wanted to mention that @Deesen had started his post ref. backups etc. and that combing efforts may be the way to go - as @Deesen has mentioned above

**Comment by pmfx** [comment]
This looks sweet. Thank you Nicola!

**Comment by fourroses666** [comment]
Very cool Nicola

**Comment by Nicola1971** [comment]
Thaks guys.
Merged some @pmfx nice modifications, now i need to add again my today improvements, then **beta4**

**Comment by Nicola1971** [comment]
Beta 4
Whats new:

* better styles, text and various fixes by @pmfx 
* improvement for better performance (less query) when you backup whole manager and/or assets folder
* support for renamed manager folders
* more manager backup checkbox options
* 3 backup type templates: Light, Medium, Full (for not expert users )
* Help toggle (like manage elements) to add instructions and tips

![b4](https://cloud.githubusercontent.com/assets/7342798/21567718/8e57550a-ceae-11e6-82bb-b61db0398651.png)


Example of small,medium,large backup size:
![3backup](https://cloud.githubusercontent.com/assets/7342798/21566136/29882662-cea0-11e6-9387-fa93fc0b1d45.png)

Help
![b4help](https://cloud.githubusercontent.com/assets/7342798/21567729/9ae4154c-ceae-11e6-8ded-adc746e18ee1.png)

**Comment by Nicola1971** [comment]
Testing on some live sites works well.

I think "backup template" (light, medium, full) are nice for fast backup and to simplify support to restore hacked sites, broken sites, updating sites, moving sites.. on forum.

Any suggestion to add/remove things from Light and Medium templates?

**Comment by Fr3ddy7** [comment]
If everything is stable) I can translate to Russian :)

**Comment by Nicola1971** [comment]
> If everything is stable

...i've done dozens of backups and tests, no issue with files. But need more test on restore db, to be sure all tables are exported correctly.
Ater more test, If everything work, for me, the module is completed, so any better coder can start to add other features.

Latest Updates:

**beta 4.1**: You can add up to **5 custom folder or files** to backup (ie: assets/galleries), from root, assets, or manager. 
You can set those custom folders and files in module config page
Custom Files and Folders section is displayed only if you have added a file to the config

**beta 4.2**: **Multilanguage Support** - the package includes italian and english lang (someone check the english translation :-D ),
https://github.com/Nicola1971/EvoBackup/blob/master/assets/modules/evobackup/lang/english.php

so @Fr3ddy7 , you can go to translate in russian :)

![backupb4 1](https://cloud.githubusercontent.com/assets/7342798/21578168/be5719b6-cf76-11e6-8d45-875f78c552f5.png)

**Comment by risingisland** [comment]
English looks fine, one change in Full Backkup Help:
`(included custom sub folders)`
to
` (including custom sub folders)`

Testing it now. So far so good. Awesome work!

**Comment by Nicola1971** [comment]
Stopped working on the module, working on extending  the package with two new extras (I will probably release as a distincted package)

- a **run backup snippet** - main feature run a backup from any other module or plugin, using **run snippet**. Not tested, but could works running standalone on a dedicated page with cronjob.
Run backup Snippet has a mode parameter: sqlonly,light,medium,full (like the module); a rootfiles parameter (1/0) , a zipsql parameter (1/0) and i will add custom folders parameter.

.You can run from a dashboard widget plugin or any module,  plugin or snippet

Mode values: 
- sqlonly: backup just db and save in default evo backup/restore folder (assets/backup)
- light, medium backup: files backup like module templates. Db saved in assets/backup
- full: files backup assets and manager . Db saved in assets/backup

Rootfiles: add index, index-ajax, robots and htaccess to any backup modes.

Zipsql: move the db backup in zip/assets/backup/ and delete the copy from asssets/backup, in any backup modes.

  

- an **event backup plugin** :  an example of using backup snippet - you can run a backup at one or more plugin events: on manager login, on manager logout, saving resource.... snippet parameters are set in plugin config. Events can be selected in events tab.

**Comment by Nicola1971** [comment]
and here is the new plugin
**AutoEvoBackup**
Automatic EvoBackup on system events

https://github.com/Nicola1971/AutoEvoBackup

https://www.youtube.com/watch?v=VQMrsLxolHE
![plugin](https://cloud.githubusercontent.com/assets/7342798/21612614/3fbc4898-d1d2-11e6-9640-eb316181f6d5.png)

**Comment by Nicola1971** [comment]
**EvoBackup RC1**

https://github.com/Nicola1971/EvoBackup
![bkptab1](https://cloud.githubusercontent.com/assets/7342798/21662554/85169f84-d2da-11e6-9599-a538f7865125.png)

* lot of fixes and code rewrite
* tab design
* now can manage (download and delete) AutoEvoBackup db backups and default evo snapshot backups

**Comment by modxuser** [comment]
Just a quick one: does this allow to backup the whole server ?

Not everyone saves their images / files etc. in "assets/"

For example:
root/images
root/assets/
root/manager/

Cheers :)

**Comment by Nicola1971** [comment]
@modxuser yes, you can add root/images with "custom Files and Folders" option

**Comment by Nicola1971** [comment]
> If everything is stable) I can translate to Russian :)

@Fr3ddy7 

I'm ready for the public release (probably today)  with english, italian, nederlands and spanish languages. everything is done and all knowed issues are fixed - tested up php 7.1

**Comment by Fr3ddy7** [comment]
if need, i translate to russian language :)

**Comment by Nicola1971** [comment]
@Fr3ddy7 yes thanks, missing russian language
