### ISSUE TITLE
PHx issue with 1.2 Upgrade, Can't Save Chunks, and Template Variables Aren't Showing Up 

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#1157]
I'm getting the following error message:

Error : include_once(/plugins/phx/phx.parser.class.inc.php): failed to open stream: No such file or directory

as seen here in a screenshot

https://cl.ly/3J03343J030g

and I've upgraded PHx but can't seem to fix this.

**Comment by MrSwed** [comment]
Try:
1. Disable phx plugin
2. Correct system path
3. Enable phx

**Comment by Tourist4Life** [comment]
I'm not sure where to update the path.  I checked line 15 in /manager/includes/document.parser.class.inc.php(1301) 

and see this 
   ` var $config= null;`
....not sure if this is where I should manually enter the path?

Also, I can't save any resources, TVs, snippets, etc.

**Comment by MrSwed** [comment]
1. Go to elements and click to plugin phx, Set Disable it, save
2. go to configuration, an reset pathes in to place (it must be **[(base_path)]assets/** and **[(base_path)]**
3. Elements-plugin -phx - enable

**Comment by Tourist4Life** [comment]
I believe that these issues can be solved using the steps [here](https://github.com/modxcms/evolution/issues/1178).
