### ISSUE TITLE
Wayfinder + Evo 1.2 &where paramater issue

### ISSUE THREAD

**Issue by vega231** [modxcms/evolution#1159]
Hi,
Just updated my website to Evo 1.2 and realized that Wayfinder plugin doesn't work when using &where parameter and JSON notation. 

With PHx v 2.2.1 enabled (with build-in filters enabled is the same), the following value _&where=`[{"parent:NOT IN": [37,39]}]`_ gives me error like that:

_Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[{"parent:NOT IN": [37,39]}]) AND sc.id IN (1,77,100,79,78,80,81,2,280,186,190,2' at line 1_

The &where param is placed literally without being parsed by DBAPI (mysqli)

Wayfinder call:
_[[Wayfinder? &where=`[{"parent:NOT IN": [37,39]}]` &startId=`0` &level=`2` &outerTpl=`_psNav_outer_container` &rowTpl=`_psNav_row` &innerTpl=`_psNav_inner_container` &innerRowTpl=`_psNav_inner_row` &parentRowTpl=`_psNav_parent_row` &selfClass=`current` &hereClass=`active`  &firstClass=`nav_first_row` &lastClass=`nav_last_row` &levelClass=`nav_row_level_` &fullLink=`TRUE` ]]_

However if I call the snippet using raw SQL in &where param, it seems to work just fine (i.e.  &where=`parent NOT IN (37,39)` ).

**Comment by dmi3yy** [comment]
Now see problems.  Correct write: 
`&where=`parent NOT IN (37,39)` `

**Comment by dmi3yy** [comment]
its. cant work: &where=[{"parent:NOT IN": [37,39]}]
