### ISSUE TITLE
MultiTV and 1.2.1-beta no thumbnails

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1161]
On a site where I use MultiTV after an update the thumbnails where not visible. (back-end)
I have updated MultiTV to the newest version with Extras Module but it still doesn't work.

The multiTV config looks like this:

```
<?php
$settings['display'] = 'vertical';
$settings['fields'] = array(
	'image' => array(
		'caption' => 'Afbeelding',
		'type' => 'image'
	),
	'thumb' => array(
		'caption' => 'Thumbnail',
		'type' => 'thumb',
		'thumbof' => 'image'
	)
);
$settings['templates'] = array(
	'outerTpl' => '<div class="images">[+wrapper+]</div>',
	'rowTpl' => '<div class="image"><div class="copyrightwrapper"><img src="[+image+]" alt="[+legend+]" title="[+title+]" />[+author:ne=``:then=`<p class="copyright">[+author+]</p>`+]</div>[+legend:ne=``:then=`<p class="legend">[+legend:nl2br+]</p>`+]</div>'
);
$settings['configuration'] = array(
	'enablePaste' => FALSE,
	'enableClear' => FALSE,
	'csvseparator' => ','
);
?>
```

It should show the thumbnail.

**Comment by dmi3yy** [comment]
Show only if generate thumbnail from kcfinder
and only for images from /assets/images/


От 3 января 2017 г. в 15:14:07, Marc (notifications@github.com) написал:

On a site where I use MultiTV after an update the thumbnails where not
visible.
I have updated MultiTV to the newest version with Extras Module but it
still doesn't work.

The multiTV config looks like this:

<?php
$settings['display'] = 'vertical';
$settings['fields'] = array(
        'image' => array(
                'caption' => 'Afbeelding',
                'type' => 'image'
        ),
        'thumb' => array(
                'caption' => 'Thumbnail',
                'type' => 'thumb',
                'thumbof' => 'image'
        )
);
$settings['configuration'] = array(
        'enablePaste' => FALSE,
        'enableClear' => FALSE,
        'csvseparator' => ','
);
?>

It should show the thumbnail.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1161>, or mute the thread

**Comment by fourroses666** [comment]
The images are selected from: /assets/images/..
I think multitv generates thumbs in the cache folder.

**Comment by dmi3yy** [comment]
multi tv  no generate 
use from assets/.thumbs/


От 3 января 2017 г. в 15:28:25, Marc (notifications@github.com) написал:

The images are selected from: /assets/images/..
I think multitv generates thumbs in the cache folder.

**Comment by fourroses666** [comment]
How can I do that, we need to update that path in multiTV?

**Comment by dmi3yy** [comment]
I think  this path need add to config 
- use original
- use thumb from /assets/.thumbs/
- use custom path


От 3 января 2017 г. в 16:08:02, Marc (notifications@github.com) написал:

How can I do that, we need to update that path in multiTV?

**Comment by fourroses666** [comment]
The multiTV snippet Static path doesn't work.
After save its empty again

**Comment by fourroses666** [comment]
/ assets / tvs / multitv / multitv.snippet.php

```
// set customtv (base) path
define('MTV_PATH', str_replace(MODX_BASE_PATH, '', str_replace('\\', '/', realpath(dirname(__FILE__)))) . '/');
define('MTV_BASE_PATH', MODX_BASE_PATH . MTV_PATH);
```

**Comment by fourroses666** [comment]
To be clear:
Front-end is oke but **back-end** isn't!

![no-imgs](https://cloud.githubusercontent.com/assets/523389/21613798/0e3cda76-d1d7-11e6-9e05-5c26f039418f.jpg)

**Comment by fourroses666** [comment]
Its weird, I have an site which doesn't have the issue.
Maybe I need to re-generate them somehow.

**Comment by risingisland** [comment]
@fourroses666 
The multiTV you are using, That is to display the selected images randomly?
If so, is this package in a repository?

**Comment by fourroses666** [comment]
@risingisland  

Yes, you can show random images with multiTV:
https://github.com/Jako/multiTV
```
[!multiTV?
    &tvName=`schoenen`
    &docid=`1`
    &outerTpl=`schoenen-multiTV-outer`
    &rowTpl=`schoenen-multiTV-row`
    &display=`1`
    &rows=`all`
    &toPlaceholder=`0`
    &randomize=`1`
    &published=`1`
    &emptyOutput=`1`
!]	```

&randomize=`1`
&display=`1`

You can install multitv with the Extras module.

**Comment by fourroses666** [comment]
Closing for now. 
New sites with multiTV shows thumbs, I do have 2 or 3 sites which shows no thumbs in the manager which are updated (evo). Really no clue whats wrong.
