### ISSUE TITLE
How to disable Alt+S shortcut in Evolution 1.2.0

### ISSUE THREAD

**Issue by yanqpl** [modxcms/evolution#1164]
Hi guys, please help me out.

For several hours trying to find a solution how to disable the shortcut "Alt+S" in the new MODX Evolution 1.2.0

Unfortunately I can not turn it off because in the Polish language is necessary to enter the "ś". In the body it is possible but in the "Title", "Longtitle", "Description" not.

**Comment by pmfx** [comment]
Confirmed. I just tested it and have exactly same issue. Pressing (right) ALT+S should give Polish "ś" character but it saves resource instead. It is kind of critical issue for us in Poland :)

**Comment by fourroses666** [comment]
That might be a problem for Germans too. ß

**Comment by Deesen** [comment]
I think this is the responsible block which needs to be commented out https://github.com/modxcms/evolution/blob/develop/manager/includes/footer.inc.php#L10-L15

Or at least remove `|| e.metaKey`

**Comment by Deesen** [comment]
I hopefully found a solution (notice the `&& !e.altKey`). So [Line 11](https://github.com/modxcms/evolution/blob/develop/manager/includes/footer.inc.php#L11) should look like

    if ((e.which == '115' || e.which == '83' ) && (e.ctrlKey || e.metaKey) && !e.altKey) {

**Comment by yanqpl** [comment]
Thanks! Problem is fixed.
