### ISSUE TITLE
setLastClickedElement 

### ISSUE THREAD

**Issue by Cipa** [modxcms/evolution#1166]
TypeError: top.tree.setLastClickedElement is not a function
1.2.1RC

Nothing in the top frame si clickable
Site tree not appearing

**Comment by Deesen** [comment]
Are you sure every single file has been uploaded correct?

**Comment by Cipa** [comment]
I use github/source tree

After I pulled I ran install one more time

[image: Inline image 1]

**Comment by Cipa** [comment]
![screen shot 2017-01-05 at 1 49 51 pm](https://cloud.githubusercontent.com/assets/293377/21698843/dbef20c4-d34d-11e6-8b48-835ab338e0a1.png)

Here's the tree empty

If I check the frame 
http://localhost/evolution/manager/index.php?a=1&f=tree

it's empty

**Comment by Deesen** [comment]
If you look into source-code of http://localhost/evolution/manager/index.php?a=1&f=tree , is it also empty? 

setLastClickedElement() is inside https://github.com/modxcms/evolution/blob/develop/manager/frames/tree.php#L432 so you can check your file.

**Comment by Cipa** [comment]
This issue was cause because iconv vas missing

 PHP Fatal error:  Call to undefined function iconv() in /Applications/AMPPS/www/evolution/manager/frames/tree.php on line 307, referer: http://localhost/evolution/manager/index.php

After I enabled it on the server and restarted everything is normal

PLease reopen if you think this needs to be added to the install check list

**Comment by Deesen** [comment]
Thank you for finding the solution already, I think to avoid confusion it is important to add a check to /install.
