### ISSUE TITLE
Unknown column 'ip' in 'field list

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#1168]
After upgrading to MODx 1.2 I'm getting the following error after logging in to the manager

« MODX Parse Error »
MODX encountered the following error while attempting to parse the requested resource:
« Execution of a query to the database failed - Unknown column 'ip' in 'field list' »
SQL > REPLACE INTO `taiyoage_newwestcondos`.`modx_active_users` (internalKey, username, lasthit, action, id, ip) VALUES (2, 'dean', '1483652662', '3', 1, '75.139.99.105')
Basic info
REQUEST_URI :	http://www.new-westminster-condo.ca/manager/index.php?a=3&id=1
Manager action :	3 - Viewing data for resource
Referer :	http://www.new-westminster-condo.ca/manager/index.php?a=1&amp;f=tree
User Agent :	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
IP :	75.139.99.105
Benchmarks
MySQL :	0.0038 s (1 Requests)
PHP :	0.7577 s
Total :	0.7615 s
Memory :	1.7790298461914 mb

Backtrace

1	include_once()
manager/index.php on line 181
2	DBAPI->query()
manager/includes/accesscontrol.inc.php on line 192

**Comment by Tourist4Life** [comment]
After running install it breaks.  I will start another thread with the issues related to this.

**Comment by blazkrapez** [comment]
Yes same error here... After upgrade 1.2 ->1.2.1. 

I've manually added a blank field "ip" into table modx_active-users and then installation finished successfully..

**Comment by Deesen** [comment]
As mentioned before you need to run /install and the upgrade-process for the DB to be updated.

**Comment by blazkrapez** [comment]
I've run /install and upgrade-process but obviously field ip was new in this release 1.2.1 (and not present in 1.2) and I get this error in upgrade process:

Creating database tables: Database Alerts!

MODX setup couldn't install/alter some tables inside the selected database.

The following errors had occurred during installation

Unknown column 'ip' in 'modx_active_users' during the execution of SQL statement ALTER TABLE `modx_active_users` MODIFY COLUMN `ip` varchar(50) NOT NULL DEFAULT ''.

**Comment by Deesen** [comment]
It seems your version of setup.sql is not up to date. Your mentioned line has been removed on 02.10.2016 so MODX 1.2 and 1.2.1 both should not contain it:

https://github.com/modxcms/evolution/commit/47e780e5e87ca6dfb8d08ec64c1d6e9b297d0480#diff-5ff3f70e00decfe74911717663cc01b6L753

**Comment by modxuser** [comment]
@Tourist4Life If this issue is resolved can you close it please, if you are not sure how to, take a [look here](https://github.com/modxcms/evolution/issues/1213)
