### ISSUE TITLE
Path problem with Modifiers

### ISSUE THREAD

**Issue by kulmjens** [modxcms/evolution#1169]
Hi there,

my MODX Evo 1.2 ist using a different name for the manager directory. As I tried to use the summary-modifier on a placeholder in a chunk, I got an error message saying that the `mdf_summary.inc.php` failed to load. It turned out that the function responsible for loading the file is in `modifiers.class.inc.php` and uses a constant named `MODX_CORE_PATH`which is defined at the begining of this file. And there the manager-dir-name is hardcoded...
Changing line 2 from
```if(!defined('MODX_CORE_PATH')) define('MODX_CORE_PATH', MODX_BASE_PATH.'manager/includes/');```
to 
```if(!defined('MODX_CORE_PATH')) define('MODX_CORE_PATH', MODX_MANAGER_PATH.'includes/');```
did the trick. :-)

**Comment by Deesen** [comment]
:+1: ! Do you want to make a PR or should I do?

**Comment by kulmjens** [comment]
I would be glad if you do. :-D
