### ISSUE TITLE
Validate HTTP_REFERER headers

### ISSUE THREAD

**Issue by Cipa** [modxcms/evolution#1170]
If no,

I still can't get access to the manager pages directly

http://localhost/evolution/manager/index.php?a=114

gives me

![screen shot 2017-01-05 at 2 02 19 pm](https://cloud.githubusercontent.com/assets/293377/21699238/96a8344a-d34f-11e6-9f93-d9897179cbb2.png)

**Comment by Deesen** [comment]
You still can open most actions in a separate tab with right mouseclick, but you cannot copy / paste a manager-url with action-id like `?a=114` manually.

**Comment by Cipa** [comment]
Then what is the point of Validate HTTP_REFERER headers? In older version by setting this to NO I was able to copy paste the url of the frame and work on it.

Is this setting serving a diffrent purpose now?

**Comment by Deesen** [comment]
Ah ok, I tested and it works for me. If turned off, pasted URLs are working. And on welcome screen I get a notice "Warning: validate_referer is turned off". Do you get the same warning?

**Comment by Cipa** [comment]
Closing, my bad, because my install was not working properly I had to set up the flag directly in the database, but it's possible that the flag is read from a session/cached variable so it was not working for me.
