### ISSUE TITLE
Deactivated user is active after forgot password mail

### ISSUE THREAD

**Issue by kulmjens** [modxcms/evolution#1171]
Hi there,

I encountered this problem by chance in Evo 1.1 and it is still there in 1.2. When a user is deactivated via the checkbox, he can't login and gets an error message. But when he then clicks on "forgot password", fills in the correct email address and follows the link in the email, this user is again active and can login. Although there is a little error alert after the link in the email was clicked and a reload of the login page, he can login as normal.
Is that the intended behaviour? I thought a user checked as not-active, shouldn't be able to login...

**Comment by kulmjens** [comment]
The questionable code is in the "Forgot Manager Login" plugin.
First I changed line 56 to get the block-information from 
```"usr.id, usr.username, attr.email, MD5(CONCAT(auser.lasthit,usr.password)) AS hash",```
to
```"usr.id, usr.username, attr.email, MD5(CONCAT(auser.lasthit,usr.password)) AS hash, attr.blocked, attr.blockeduntil, attr.blockedafter",```

And after that around line 170 there is the code handling the link from the email. I changed the second `if`-statment from
```
if($event_name == 'OnBeforeManagerLogin' && $hash && $username) {
    $user = $forgot->getUser(false, $username, '', $hash);
    if($user && is_array($user) && !$forgot->errors) {
        $forgot->unblockUser($user['id']);
    }
}
```
to
```
if($event_name == 'OnBeforeManagerLogin' && $hash && $username) {
    $user = $forgot->getUser(false, $username, '', $hash);
    if($user && is_array($user) && $user['blocked'] == 0 && !$forgot->errors) {
        $forgot->unblockUser($user['id']);
    }
}
```
It's the `$user['blocked'] == 0 &&` which is new...
It's a quick workaround. It doesn't take the `blockeduntil` oder `blockedafter` fields in account. If the user is blocked, he cannot use the link from his "forgot password" email.

**Comment by Deesen** [comment]
Maybe also this issue should be taken into account #1059.

**Comment by kulmjens** [comment]
I'm with @bossloper. I think there are these three cases:
1. A user is blocked for good -> only field `blocked` should be checked.
2. A user is blocked temporarily -> only field `blockeduntil` should be filled.
3. A user should be blocked in the future -> field `blockedafter` should be filled and maybe after the selected date the field `blocked` should be set.

Another question would be whether a blocked user (for good or temporarily) should be able to send himself a password request email or if he should only be denied to access the link in the email.

**Comment by bossloper** [comment]
RE: Another question would be whether a blocked user (for good or temporarily) should be able to send himself a password request email or if he should only be denied to access the link in the email.

I'd suggest:
denied if 'for good' i.e. blocked 'checked'
email sent if 'blocked temporarily'

**Comment by dmi3yy** [comment]
move here https://github.com/evolution-cms/evolution/issues/42
