### ISSUE TITLE
some tabs are missing in manager panel

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#1175]
Hi,
I am newly install modx 1.2 and some tabs are missing in manager panel.
Like this , 
![my site modx cms manager](https://cloud.githubusercontent.com/assets/9032715/21751600/23dbae0a-d5f8-11e6-88b2-177fae9bafb4.png)

**Comment by Deesen** [comment]
https://github.com/modxcms/evolution/issues/1157#issuecomment-269741331

**Comment by mgzawlinoo** [comment]
Hi,
I don't have PHx plugins, and 
it was everythings ok at localhost.
![asiana myanmar modx cms manager](https://cloud.githubusercontent.com/assets/9032715/21751734/72e1f9ee-d5fa-11e6-9887-1837ddbd6225.png)
I have four websites and they all are upgrade from 1.1 to 1.2 , and everything fine.
But this one is newly install from 1.2 and manager tabs are missing. 
Server : Digital Ocean , Os : Ubuntu 14.04

**Comment by mgzawlinoo** [comment]
sorry for duplicate issue , i found it 
#1130

**Comment by Deesen** [comment]
:+1: ;-)
