### ISSUE TITLE
Parse error on all sites

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1176]
I just started receiving parse errors across all of my sites with the following error:

> Warning: session_start(): open(/tmp/sess_c7e1b78c9b3b796dcaddacc8c1125105, O_RDWR) failed: Permission denied (13) in /home/xxx/public_html/manager/includes/config.inc.php on line 87

> Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/xxx/public_html/manager/includes/config.inc.php:87) in /home/xxx/public_html/manager/includes/config.inc.php on line 87
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/xxx/public_html/manager/includes/config.inc.php:87) in /home/xxx/public_html/manager/includes/config.inc.php on line 102
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/xxx/public_html/manager/includes/config.inc.php:87) in /home/xxx/public_html/manager/index.php on line 175
> 
> Warning: Unknown: open(/tmp/sess_c7e1b78c9b3b796dcaddacc8c1125105, O_RDWR) failed: Permission denied (13) in Unknown on line 0
> 
> Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/tmp) in Unknown on line 0

None of these sites have been modified recently. Any ideas?

**Comment by Deesen** [comment]
It seems to be a server issue. If you have access to /tmp you can try change its permissions http://stackoverflow.com/a/6821576/2354531

**Comment by risingisland** [comment]
Thanks @Deesen 
I contacted my host, looks as though someone had fat fingers and changed permissions on the server.
Its been resolved.
