### ISSUE TITLE
tinymce4 and RTE TV problems

### ISSUE THREAD

**Issue by vmoreira** [modxcms/evolution#1177]
Hello
I am having a problem with new installations of version 1.2 and higher that tinymce4 does not work on content does not work on template variables with RTE.
I tested an upgrade from a previous version and the previous version of tinymce works and tinymc4 does not work.
Did someone have the same problem? How did you solve it?

Thank you,
Vitor M.

**Comment by Deesen** [comment]
Did you edit/saved the configuration after update? Any errors in browser-console?

**Comment by Deesen** [comment]
Or maybe https://github.com/modxcms/evolution/issues/1130

**Comment by vmoreira** [comment]
Error:
Failed to load: /assets/plugins/tinymce4/tinymce/langs/pt.js

**Comment by vmoreira** [comment]
Done: Change the file name pt_PT.js to pt.js.

**Comment by Deesen** [comment]
Thanks :+1: . I need to recheck `$_lang['lang_code']` inside `tinymce/lang/gsettings/*.inc.php` for all languages then.

**Comment by modxuser** [comment]
<table>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/ukrainian.inc.php</td>
    <td>$_lang['lang_code'] = 'uk';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/czech.inc.php</td>
    <td>$_lang['lang_code'] = 'cs';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/danish.inc.php</td>
    <td>$_lang['lang_code'] = 'da';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/english.inc.php</td>
    <td>$_lang['lang_code'] = 'en';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/finnish.inc.php</td>
    <td>$_lang['lang_code'] = 'fi';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/francais-utf8.inc.php</td>
    <td>$_lang['lang_code'] = 'fr';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/german.inc.php</td>
    <td>$_lang['lang_code'] = 'de';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/hebrew.inc.php</td>
    <td>$_lang['lang_code'] = 'he';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/italian.inc.php</td>
    <td>$_lang['lang_code'] = 'it';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/japanese-utf8.inc.php</td>
    <td>$_lang['lang_code'] = 'ja';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/nederlands.inc.php</td>
    <td>$_lang['lang_code'] = 'nl';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/nederlands-utf8.inc.php</td>
    <td>$_lang['lang_code'] = 'nl';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/norsk.inc.php</td>
    <td>$_lang['lang_code'] = 'nb';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/persian.inc.php</td>
    <td>$_lang['lang_code'] = 'fa';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/polish.inc.php</td>
    <td>$_lang['lang_code'] = 'pl';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/polish-utf8.inc.php</td>
    <td>$_lang['lang_code'] = 'pl';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/portuguese.inc.php</td>
    <td>$_lang['lang_code'] = 'pt';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/portuguese-br.inc.php</td>
    <td>$_lang['lang_code'] = 'pt-br';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/russian-UTF8.inc.php</td>
    <td>$_lang['lang_code'] = 'ru';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/spanish-utf8.inc.php</td>
    <td>$_lang['lang_code'] = 'es';</td>
  </tr>
  <tr>
    <td>assets/plugins/tinymce4/lang/gsettings/svenska-utf8.inc.php</td>
    <td>$_lang['lang_code'] = 'sv';</td>
  </tr>
</table>

**Comment by Deesen** [comment]
Yes definetly saves time of course, thank you!
