### ISSUE TITLE
Migration Issues from one server to another

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#1178]
I've taken the below steps to migrate to a new host (site5 to inmotionhosting.com):

1.  Backed up DB and downloaded SQL import file
2.  Downloaded all website files
3.  Created new DB on new host
4.  Imported SQL file into to DB
5.  Uploaded all website files to new server
6.  Modified config.inc to point to new database

...and I'm getting the following error when viewing the website home page:

https://cl.ly/1P2N1w223S3u/annotate

....also after logging into the manager I get the following error:

A possible CSRF attempt was detected from referer: http://173.205.126.168/~soriahkanji/manager/index.php.

so it is unusable.

**Comment by Deesen** [comment]
You can try https://github.com/modxcms/evolution/issues/1157#issuecomment-269741331

**Comment by Tourist4Life** [comment]
I can't get into the manager to disable phx.  Is there an alternative way to do this?

**Comment by Deesen** [comment]
With phpmyadmin, table "site_plugins" and then search for plugin "phx" and set disabled to 1.

**Comment by Deesen** [comment]
And maybe in table "system_settings" the setting "validate_referer" to 0.

**Comment by Tourist4Life** [comment]
I still get the same error when viewing the home page after disabling phx via the DB and setting validate_referer to 0.

Also, when logging into the manager it appears that something is redirecting to the old website path as the URL goes from http://173.205.126.168/~soriahkanji/manager/

http://fairview-condo.com/~soriahkanji/manager/

and once I refresh the manager login URL I get the CSRF error again.

**Comment by Deesen** [comment]
The manager redirects you to old domain? Strange! Is there a redirect-rule in /.htaccess or /manager/.htaccess ?

**Comment by modxuser** [comment]
@Deesen that re-direct also happens when the "siteHostnames.php" is different to the current domain

@Tourist4Life have you cahnaged the "siteHostnames.php" ?

**Comment by modxuser** [comment]
@Tourist4Life 

**Just a check / test:**

Delete everything in the assets/cache/ folder, other than:
- sitePublishing.idx.php
- images/
- rss/

Then try to login again - don't go to the front-end, it will give you an error, go directly to the manager and try to login.

**Comment by Nicola1971** [comment]
> I still get the same error when viewing the home page after disabling phx via the DB and setting validate_referer to 0.

When i had a plugin that causes errors in the manager, just disabling from phpmyadmin, never worked for me.
1) disable from phpmyadmin
2) run evo installer again

**Comment by Tourist4Life** [comment]
thanks @modxuser 👍  I was able to get into the manager and if i disable phx the site loads!  

However I need phx as it is integral to the website and in use in most of my templates.

When enable phx I see the [following](https://cl.ly/0p1j3O071z3P)

It appears that the file manager path cannot be set via Tools > Configuration in the manager and I see the following:

Enable filters	
Warning: include_once(/home/*****/public_html/soriahkanji.com/assets/plugins/phx/phx.parser.class.inc.php): failed to open stream: No such file or directory in /home/soriahkanji/public_html/manager/includes/document.parser.class.inc.php(1301) : eval()'d code on line 15

Warning: include_once(): Failed opening '/home/*****/public_html/soriahkanji.com/assets/plugins/phx/phx.parser.class.inc.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php:/home/soriahkanji/public_html/manager/includes/') in /home/soriahkanji/public_html/manager/includes/document.parser.class.inc.php(1301) : eval()'d code on line 15

Fatal error: Class 'PHxParser' not found in /home/soriahkanji/public_html/manager/includes/document.parser.class.inc.php(1301) : eval()'d code on line 19

screenshot can be found [here](https://cl.ly/3b3Z1s2s3y0O/annotate).  

As you can see it is still pointing to the old server path.

**Comment by modxuser** [comment]
@Tourist4Life 
Stupid question: is PHX on your server ?

If its not there, you will get the error all the time as its trying to include a file thats not there

**Comment by modxuser** [comment]
@Tourist4Life 

I suggest removing the first screenshot as your full server path can be seen in it - from [this post](https://github.com/modxcms/evolution/issues/1178#issuecomment-271581076)

Have you checked the paths in your DB ?

**Find the following:**

YOURPREFIX_system_settings

In system setting look for the following three tables.

Find: rb_base_dir
Find: rb_base_url
Find: filemanager_path

According to the image you posted I would say your settings should be something like the following:

**rb_base_dir:** /home/XXXXXXX/public_html/soriahkanji.com/assets/
**rb_base_url:** assets/
**filemanager_path:** /home/XXXXXXX/public_html/soriahkanji.com/

If they aren't, then you will have to change them

**Comment by Tourist4Life** [comment]
not a stupid question as you know with FTP files don't always make it!

Yes phx is there.  I have updated the paths in the DB per your suggestion and they needed it!

However phX is still throwing the same error to the old file path.  Also, I'm unable to save to the static file path in the configuration settings of phx.

**Comment by modxuser** [comment]
Are you still using the same DB as you did before ?

So to say - the old DB is still being used.

If you manually change the path in the manager, that should reflect in the DB

May I suggest the following (if this doesn't work - I give up)

1. Clean the assets/cache/ folder of all files as [mentioned here](https://github.com/modxcms/evolution/issues/1178#issuecomment-271516473)

2. Go to the DB and check the 3 paths again - modify where needed
3. Login - don't go to the front-end, go directly to the back-end / manager
4. Check the paths displayed in the system configuration - they should be the same as those shown in the DB (If they are not the same - something is drastically wrong)
5. Clear manager cache and check the front-end
6. If it still doesn't work, disable PHx
7. Re-check, if it works then I am stuck

The only option would be to ask one of the Dev's to take a quick look, but you will have to grant them access

**Comment by Tourist4Life** [comment]
I've done all of these including checking the .htaccess files but #4 above is not possible as the system configurations settings cannot be modified in the manager due to the error message described above in the Enable Filters section.

I have many many sites that use phX and these need to be migrated to a new host.  As you can imagine going thru countless templates and replacing phx with IF is going to be very time consuming.

I see that this was a [bug](https://github.com/modxcms/evolution/issues/1017) which was closed.  I'm just wondering if this is still unresolved with 1.2?

I'm happy to give a Dev access @Deesen already has access.  @modxuser I can set you up as well if you PM me your email.

thanks for your continued help and support on this.

**Comment by modxuser** [comment]
I just looked at my DB and have found the setting for the filters.

In system settings find "enable_filter" and if it is set to "1", change it to "0" (zero)

The rest is the usual, clear cache etc. and then log-in and test

**Comment by Tourist4Life** [comment]
i didn't see enable_filter in my DB as seen [here](https://cl.ly/0S342e3h0P2K).

But I have finally got the paths to stick.  

I disabled PHx, went to the MODx manager system configurations (Tools > Configuration) and updated File Manager and File Bast pages, SAVED, and then reenabled PHx and it works!

Thank you for sticking with me and responding so quickly.  You guys ROCK!!!!~~!

**Comment by Deesen** [comment]
Nice, I was just asking you to leave the "edit configuration"-page so I can edit it ;-)..

**Comment by fourroses666** [comment]
I think I had the same issue once, cleaning cache didn't help but was needed and then re-updated again and that seemed to work. So next time you might consider disable phx before making a copy 📦 😄

**Comment by Deesen** [comment]
Or wait for 1.2.1 where this issue is fixed.

**Comment by risingisland** [comment]
How long before 1.2.1?
@Deesen

**Comment by Deesen** [comment]
Good question. What is the situation with 1.2.1 @dmi3yy ?

**Comment by dmi3yy** [comment]
I think we can realise 
Do this today

Отправлено с iPhone
