### ISSUE TITLE
Release of 1.2.1?

### ISSUE THREAD

**Issue by hquadrat** [modxcms/evolution#1182]
Hi all,

in some comments was stated that Evo 1.2.1 could possibly be released on 02.01.2017, a few customers are pushing hard because they heard of the PHPMailer bug themselves.

Any idea when things will be prepared?

Thanks for a hint, Henning

**Comment by yama** [comment]
PHPMailer vulnerability is not problem in Evo.
The problem with PHPMailer occurs when validation is done only with PHPMailer.
However, since misunderstanding is not good, we will update PHPMailer.
I think that v1.2.1 will be released soon.

**Comment by hquadrat** [comment]
Thank you for the information.
