### ISSUE TITLE
PHPMailer 5.2.22 Update

### ISSUE THREAD

**Issue by EarlThorfinn** [modxcms/evolution#1186]
I notice a further new version of PHPMailer has been released (5.2.22 - January 5th 2017) with a security fix, which may need to be applied to the MODx Evolution files in:  /manager/includes/controls/phpmailer/

PHPMailer changelog is at: https://github.com/PHPMailer/PHPMailer/blob/master/changelog.md

Thanks

**Comment by dmi3yy** [comment]
fixed
