### ISSUE TITLE
question: "session handling temp" path for the "manager ht.access" file

### ISSUE THREAD

**Issue by nick0** [modxcms/evolution#1187]
Hello,

I just wanted to check the relevant "session handling temp" path for my install relating to the note referenced in the "manager ht.access" file:
For unexpected logouts in multi-server/cloud environments see:
https://docs.modx.com/evolution/1.0/administration/friendly-url-solutions

I have experienced these logouts on some installs before and didn't know there was a possible solution as simple as this.

On that docs.modx.com page in the session handling bit it talks about the path:
php_value session.save_path /path/to/your/web/content/sessions/

Is this path outside the public_html in the tmp file? 

And if my public_html path looks like so...:
/home/USERNAME/public_html
would I use the following path?:
/home/USERNAME/tmp

Attached are some screen caps to show server folders
![untitled-1](https://cloud.githubusercontent.com/assets/1768308/21922671/b6d5051a-d9bf-11e6-84d7-838fb39f4941.jpg)

And inside the tmp folder:
![untitled-2](https://cloud.githubusercontent.com/assets/1768308/21922670/b6d218aa-d9bf-11e6-80cb-2fd3a41ca77a.jpg)

Any help greatly appreciated.

**Comment by bossloper** [comment]
Yes that is what I do on all my installs, though I use a different folder name other than tmp (priv) and set it all via a custom php.ini - all gives the same result though. 

I also move the php error logs out of public_html,. For htaccess I think that will just be:
php_value error_log = /home/USERNAME/priv/logs/error_log

So you could have /home/USERNAME/priv/sessions for the session path and /home/USERNAME/priv/logs for the php log. Only reason I keep the sessions out of just tmp is it can get quite big (and slow) if browsing the tmp folder and hundreds of session files are all in the top level of tmp.

**Comment by nick0** [comment]
Thanks @bossloper. Fantastic tips and much appreciated for the clear explanation.

One more question has sprung to mind if that's ok...
do you add the tmp line into both your main (root) htaccess file and the one in the manager folder? Or just one or the other?

Thanks again.

**Comment by bossloper** [comment]
Personally I just added to the 'root' htaccess, did not alter the manager one. Not 100% sure about the rights or wrongs of doing that but it seems to work fine!

**Comment by nick0** [comment]
Beauty, thanks for that. I like it and will do just the root htaccess file also. One less thing to have to change on an update. Thanks again for your expertise and input @bossloper

**Comment by modxuser** [comment]
@nick0 If this issue is resolved can you close it please, if you are not sure how to, take a [look here](https://github.com/modxcms/evolution/issues/1213)
