### ISSUE TITLE
 [+rows.total+] not working any more in MultiTV

### ISSUE THREAD

**Issue by leonie12** [modxcms/evolution#1189]
I use MultiTV in one of my websites and have something in the form of `[+rows.total:eq=1:then=xxx:else=yyy+].` It worked until recently. Now there seems to be no output any more.
Even `[+rows.total+]` in some multitv.config.inc.php does not output anything.

Was there a change in the code that induced this behaviour and is this supposed to be this way?

See also [https://github.com/Jako/multiTV/issues/171](https://github.com/Jako/multiTV/issues/171)

**Comment by Deesen** [comment]
What happens if you use `row.total` like in docs, instead of `rows.total`?

**Comment by leonie12** [comment]
No change at all. Does not work.

Am 16.01.2017 um 19:47 schrieb Deesen:
> What happens if you use `row.total` like in docs, instead of `rows.total`?
>

**Comment by leonie12** [comment]
I tested some more and found that when I put `[+rows.total:eq=1:then=xxx:else=yyy+]` (rows not row) directly in the multitv config file it works. But having the phx call in a chunk, like I have, then it does not work. My problem is I have to have it in a chunk because I want to get a style tag outputted in the html head section when I have only one image in a slider to not have shown the prev/next buttons. Putting it in the multitv config file the style tag would be outputted inside body, which is not valid html.

**Comment by Jako** [comment]
Maybe just this:

```
&outerTpl=`slider-controls`
```

**Comment by Deesen** [comment]
@leonie12 Maybe you want to test quickly my version of document.parser, and see if it solves the issue? https://github.com/Deesen/evolution/blob/develop/manager/includes/document.parser.class.inc.php

**Comment by leonie12** [comment]
@Deesen: I tested your new document.parser. It did not solve the issue. Instead there was a html output with missing site elements. I was not able to investigate closer what exactly happened.

@Jako: Thank you. This was the solution to this issue.

At the moment I will not close this issue, because I think that this was only half of a solution as I think that such changes in the core should not break existing sites.

**Comment by Jako** [comment]
Your outerTpl parameter was filled wrong before. It was filled indirect by the chunk code. You should never use chunk code without @CODE. And if you use @CODE, you have to mask the placeholders tags `[+` and `+]` with `((` and `))`. 

You were quite lucky that this worked before. So the change was not a breaking one in 1.2.

**Comment by leonie12** [comment]
So I had luck that it worked before and now I am happy that it is working again.

Thank you for the explanation.

Now I am happy to close this issue.
