### ISSUE TITLE
Error when activating core modifiers/filters

### ISSUE THREAD

**Issue by leonie12** [modxcms/evolution#1190]
I use phx heavily on some websites. Since years. No problems so far.

When disabling plugin phx and activating new core modifiers/filters all websites are broken. Everywhere I get a blank page with the same error: `Parse error: syntax error, unexpected '0' (T_LNUMBER) in /path/to/document/root/manager/includes/extenders/modifiers.class.inc.php(340) : eval()'d code on line 1`

**Comment by modxuser** [comment]
I can't help with the actual problem, but are you using the latest version of [Evo - 1.2.1](https://github.com/modxcms/evolution/releases/tag/1.2.1) ?

There were issues with PHX and the core modifiers in previous versions

**Comment by Deesen** [comment]
Some questions
- Which MODX- and PHX-version do you use?
- Did you run /install without errors?
- Did you update&save your MODX-configuration without errors?

**Comment by leonie12** [comment]
MODX 1.2.1, Ditto 2.1.2, Phx 2.2.0 Everything worked for years until recently. Same error on production website (because of this is it is urgent to solve the problem) and on local xampp. Both installations using PHP 7.0.
Update on all (those and some more websites) installations without errors or problems. Configuration saved without modifications after update.

**Comment by Deesen** [comment]
I also updated a site with heavy PHX from old times recently and no problems so far. But I always keep PHX activated instead of using new modifiers.

**Comment by leonie12** [comment]
My sites all work as expected when phx is activated. But trying out the new core modifiers which are introduced to replace phx in the future (so my understanding) and therefore deactivating phx throws above error. On all installs, different websites, different servers.

**Comment by Deesen** [comment]
@yama Are the news filters/modifiers meant to be 100% compatible with existing PHX-modifiers? Or do they have to be rewritten to use the new filters?

**Comment by MrSwed** [comment]
@leonie12 
try to change phx call
for example, I remove from the expression :input, and this help  https://github.com/modxcms/evolution/issues/623#issuecomment-234555532 

and, by the way, what kind of a piece of code causes an error ?

**Comment by yama** [comment]
@Deesen 
Yes, It is compatible. But In this case, there may be a problem.
I want detailed information.

https://github.com/modxcms/evolution/blob/develop/manager/includes/extenders/modifiers.class.inc.php#L340
Line 340

**Comment by yama** [comment]
@leonie12 
[modifiers.class.inc.zip](https://github.com/modxcms/evolution/files/710319/modifiers.class.inc.zip)
Would you try this file?

**Comment by leonie12** [comment]
@yama: Itried your modifiers.class.inc. Error is now:

`Parse error: syntax error, unexpected '1' (T_LNUMBER) in /path/to/document/root/manager/includes/extenders/modifiers.class.inc.php(338) : eval()'d code on line 1`

**Comment by Deesen** [comment]
In the original-file you can add new line after [line 339](https://github.com/modxcms/evolution/blob/develop/manager/includes/extenders/modifiers.class.inc.php#L339) (or new file after line 337) with `echo $conditional;` like

    $conditional = implode(' ',$this->condition);
    echo $conditional;

to maybe give us more insight of what is happening.

**Comment by leonie12** [comment]
The additional output to the known error message is:

011 || 011111 1

Does this help?

**Comment by fourroses666** [comment]
I had the same message on an install 1.2.1.beta. 

Updated to 1.2.1 and the error/parse message is gone.
