### ISSUE TITLE
Some placeholders/TVs not working in Ditto any more, shown as TV name

### ISSUE THREAD

**Issue by leonie12** [modxcms/evolution#1192]
I use Ditto to show a preview of articles on a summary page. Therefore I use following Ditto template (bacticks replaced through apostrophs here):

 `<a title="[+pagetitle+]" href="[~[+id+]~]">
	[+summary-image:ifnotempty='<img src="[+summary-image+]" alt="[+summary-image-alt-text+]" title="[+summary-image-title+]" />'+]
</a>
<span><a title="[+pagetitle+]" href="[~[+id+]~]">[+pagetitle+]</a></span>
[+summary:ifnotempty='<p>[+summary:striphtml=`<br />`+] <a title="more" href="[~[+id+]~]">mehr →</a></p>'+]`

Since some time (maybe the update of evo to 1.2/1.2.1) some of the used placeholders/TVs are shown as plaintext. These are `[+summary-image+]` and `[+summary-image-alt-text+]` from the template above.

Those worked until recently as expected. Phx is installed and activated. New core modifiers/filters not active. Maybe related to [https://github.com/Jako/multiTV/issues/171](https://github.com/Jako/multiTV/issues/171) and [https://github.com/modxcms/evolution/issues/1190](https://github.com/modxcms/evolution/issues/1190).

MODX 1.2.1, Ditto 2.1.2, Phx 2.2.0

**Comment by leonie12** [comment]
Mea culpa.
This issue can be closed. I had a similar ditto template in another ditto call and confused them. In this call were somehow the brackets and + around the TV names lost. No idea how and when this happened, but being so it could not work any more as expected. No fault of MODX evo.

My other two issues persist.

**Comment by Deesen** [comment]
You can close it using close button.
