### ISSUE TITLE
Migration Issues from one host to another....again

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#1193]
I have another 1.2 install that I just moved and I'm getting the following errors:

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /*****/*****/public_html/manager/includes/config.inc.php:119) in /*****/*****/public_html/manager/includes/config.inc.php on line 101

Warning: Cannot modify header information - headers already sent by (output started at /*****/*****/public_html/manager/includes/config.inc.php:119) in /*****/*****/public_html/manager/includes/config.inc.php on line 116

Warning: Cannot modify header information - headers already sent by (output started at /*****/*****/public_html/manager/includes/config.inc.php:119) in /*****/*****/public_html/manager/index.php on line 181

I did not have PHx installed on this install but did change the paths in the DB per this issue

https://github.com/modxcms/evolution/issues/1178

**Comment by modxuser** [comment]
A remedy when having problems moving from one server to another is to re-install in upgrade / update mode, using the same version you already have - simply grab the install folder (and only the install folder), upload it to your server and go through the process of re-installing.

I generaly don't activate any chunks snippets etc. to be installed, all you want it to do is refresh the DB.

In the now 12 years of using Evo, I have only experienced session issues once, and I did exactly what I just wrote. If you take a look in the forum you will find that lots of people use this method, for both Evo + Revo

**Comment by Tourist4Life** [comment]
Thx @modxuser. I have done as you say above and I'm able to login to the manager but view all pages gives me this message:



Your IP is 7*.1**.99.105

**Comment by Cipa** [comment]
Hi,

what is the Detection level of PHP errors in configuration.

Also try removing/renaming the cache files inside assets/cache
- siteCache.idx.php
- siteHostnames.php
- siteManager.php

**Comment by Tourist4Life** [comment]
Thank you Cipa!  That worked.  I first disabled the PHP errors and then removed the files.

**Comment by modxuser** [comment]
@Tourist4Life If this issue is resolved can you close it please, if you are not sure how to, take a [look here](https://github.com/modxcms/evolution/issues/1213)
