### ISSUE TITLE
Init on TinyMCE. 

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1196]
I would like to add a new FontAwesome plugin for TinyMCE ([Tinyfonticon](http://jasonrichardsmith.github.io/tinyfonticon/)), but dont know where to add the Init refferences:

```
tinyfonticon: {
    fontello_style : {  // This array key the is the value set on the css link.
      prefix: ".icon-",  // This is the prefix for font designations.
      font: 'fontello',  // This is the font-family
    },
    fontawesome_style : {
      prefix: ".fa-",
      added_class : "fa",
      font: 'FontAwesome',
    }
  },
  extended_valid_elements : "span[style|fontclass]",  // fontclass will give the ability to rewrite POST after submission
  fontsize_formats: "8pt 9pt 10pt 11pt 12pt 26pt 36pt 48pt 54pt 72pt 86pt 98pt 112pt",
```
I tried adding into Custom Parameters in the TinyMCE plugin, but not sure if this is correct, as nothing happened.

**Comment by Deesen** [comment]
You can duplicate one of the theme-files you desire, give it a new filename and it will be listed in MODX-configuration Tiny4 theme-list. 

Your init is missing adding `tinyfonticon` to the plugins list like here:
https://github.com/modxcms/evolution/blob/develop/assets/plugins/tinymce4/theme/theme.tinymce4.creative.inc.php#L24

And adding `tinyfonticon` to the toolbar
https://github.com/modxcms/evolution/blob/develop/assets/plugins/tinymce4/theme/theme.tinymce4.creative.inc.php#L25

And you will need to add a link to this file (copy to your server) http://jasonrichardsmith.github.io/tinyfonticon/js/tinyfonticon/tinyfonticon.plugin.js after line 3 here > https://github.com/modxcms/evolution/blob/develop/assets/plugins/tinymce4/tpl/tpl.tinymce4.init_once.html#L3 like

    <script src="js/tinyfonticon.plugin.js"></script>

That should work.

**Comment by risingisland** [comment]
Thanks for the info Deesen, although I still cant get it to work.  :disappointed:
I viewed the source of the frame, and everything looks ok (to me), but it brakes Tinymce.

**Comment by Deesen** [comment]
It brakes Tinymce? Any error in browser-console?

**Comment by risingisland** [comment]
Yes, Tinymce and textarea are just a blank box, no content nor toolbars.
I dont see any problems via console.

**Comment by Cipa** [comment]
But if you remove the added code, will it get fixed?

**Comment by risingisland** [comment]
Yes, removing the code in the first post or removing the plugin/toolbar reference makes everything normal.
