### ISSUE TITLE
shell_exec

### ISSUE THREAD

**Issue by Cipa** [modxcms/evolution#1197]
On a new install I am getting some errors because shel_exec is not allowed

Here are some lines from teh error page

Error : shell_exec() has been disabled for security reasons
...
$menu = $modx->runSnippet("Wayfinder", array('startId' => $res['id'], 'rowTpl' => `MenuNoTitle`)); 
...
eval()
manager/includes/document.parser.class.inc.php on line 1360
include(string $var1)
manager/includes/document.parser.class.inc.php(1360) : eval()'d code on line 2
shell_exec('MenuNoTitle')
assets/snippets/site/support-menu.php on line 22

Seems like the whole site is fine except for running Wayfinder using the runSnippet api

Any ideas how to fix, maybe even improve Evo not to use shell_exec()

Thank you

PS: [[Wayfinder? &startId=`0` &level=`1` &rowTpl=`MenuNoTitle`]] works fine in a template

**Comment by Deesen** [comment]
If you search source-code for `shell_exec` it is only used via phpthumb. But you can try setting in MODX-configuration under tab "Security" -> "Eval php code in snippet call" to "Unlimited (Use only for debugging)".

**Comment by Deesen** [comment]
Otherwise I guess its a server issue.

**Comment by Cipa** [comment]
Unlimited doesn't seem to work, I get the same error.
Host seems unccoperative to enable that function. Used to work when the website was insitially set up 2 years ago.

I might go with a custom snippet for now.
