### ISSUE TITLE
Document Content does not remember 'Editor to use' setting

### ISSUE THREAD

**Issue by ricardo-lewis** [modxcms/evolution#1198]
After upgrading to MODX 1.2, the main document content RTE cannot remember if you set it to use TinyMCE. 

You can select TinyMCE4 and it will activate but after saving the page, the setting is back to 'None'.

There are no JS console errors, no 404 errors.

I've tried setting and un-setting the 'Enable Editor' configuration. I've tried setting and un-setting the 'Rich Text' document option. The database field 'richtext' is set to 1 for all documents.

Only the TinyMCE4 plugin is enabled.

Strangely, there are page templates on the site that have secondary RTE content areas and they have TinyMCE4 enabled and working.

MODX 1.2.1 
PHP 5.5.9-1ubuntu4.20
MySQL 5.5.53
Ubuntu 14.04.5 LTS

**Comment by Nicola1971** [comment]
Do you have any default editor in your user settings? Check please

**Comment by ricardo-lewis** [comment]
Yes, there are only two options in Config > Interface & Features: None and TinyMCE4, and the latter is selected.

It seems the Manager is ignoring that setting. When you edit a page, the Javascript required to launch TinyMCE is not on the page.

**Comment by ricardo-lewis** [comment]
I figured it out. I forgot that each user can have their own TinyMCE settings (this is because I hardly ever need to edit those settings). The selector was set to a blank value: after upgrading TinyMCE3 is replaced by 4 and that selector also needs to change. I will submit a feature request for this.
