### ISSUE TITLE
MODX 1.2.1 seems to be interrupting PHx in WayFinder

### ISSUE THREAD

**Issue by ricardo-lewis** [modxcms/evolution#1200]
I just updated a site from 1.2 to 1.2.1 and PHx calls inside a WayFinder template are returning nothing.

When PHX tries to modify a value directly, it returns nothing:

```[+phx:input=`[+wf.linktext+]`:entity_decode+]```

However you can "prime the pump" by making the placeholder appear somewhere else in the template:
```[+wf.linktext+] [+phx:input=`[+wf.linktext+]`:entity_decode+]```

**This will work** and output the placeholder twice. The bare placeholder seems to allow PHx to process a value.

There are no PHP errors in the system log.

See also #623

**Comment by Deesen** [comment]
Does it work when you disable PHX-plugin and set "Enable filters" in MODX-config to yes? For me this is exactly the case, I could recreate your issue. `[+wf.linktext:test+]` doesnt work but `[+phx:input ..+]` does.

**Comment by ricardo-lewis** [comment]
My problem is trying to get PHX to work the way it did in 1.2, disabling PHX entirely won't help me do that. 

My first code example doesn't work, the second does. Wayfinder or PHX seems to need to bare placeholder in order to give the value to PHX. 

I've seen this before in Ditto, it's the only reason I figured out the workaround.

**Comment by Deesen** [comment]
I tested also with Ditto using same modifier `[+title:test+]` which looks like:

    // assets/plugins/phx/modifiers/test.phx.php
    return $output.'+test';

It only works when phx-plugin is enabled. Ditto-Parameter `&phx=´0 / 1´` gets ignored. With disabled plugin and enabled filters the modifier doesn´t work. Ditto needs activated phx-plugin, then `[+title:test+]` works.

For Wayfinder it is the other way round for me. `[+wf.linktext:test+]` works only with disabled phx but enabled filters. Totally confusing.. requires serious investigation.

**Comment by ricardo-lewis** [comment]
@Deesen are you saying that the new "Core Filters" are an alternate front-end to PHX and not a full internal alternative? Are you able to continue using all your own custom PHX modifiers?

How is WayFinder/MODX Filters processing your "test" modifier?

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/1.2/assets/snippets/ditto/classes/ditto.class.inc.php#L340-L349
DItto

https://github.com/modxcms/evolution/blob/1.2/assets/snippets/wayfinder/wayfinder.inc.php#L266
Wayfinder

Ditto parses itself without core function.
Wayfinder parses using the core function (parseText).

https://github.com/modxcms/evolution/blob/1.2/manager/includes/document.parser.class.inc.php#L3382-L3408
$modx->parseText()

**Comment by Deesen** [comment]
@yama Ok I investigated again. My fault, `&phx=0` works. I changed Ditto and document.parser (Ditto uses `[+lang:next+]`) slightly to use $modx->parseText which should make Ditto compatible with new filters -> [ditto-fix.zip](https://github.com/modxcms/evolution/files/713247/ditto-fix.zip).

@ricardo-lewis No I was just noticing my test-case. The new filters should be fully compatible to old phx, if not we have work left to do IMO except bad modifiers-code is responsible. And I updated a site with heavy custom-phx (for a shop). At least with activated phx-plugin I have no issues after upgrading to Evo 1.2.1.

BTW, are you 100% sure, that the old sites you updated did not use any kind of phx-hack to incooperate phx into your Wayfinder? I searched through old Wayfinder versions and cannot find phx applied anywhere which implies to me that Wayfinder is a "non-phx snippet" -> http://wiki.modxcms.com/index.php/PHx#Using_PHx_in_non-phx_snippet_templates , that is why only [+phx .. +] works. 

Also since MODX 1.0.14 phx-placeholders are explicitly skipped (not replaced) to leave them intact -> https://github.com/modxcms/evolution/blob/1.2/assets/snippets/wayfinder/wayfinder.inc.php#L634 which implies to make use of [+phx .. +] . Before 1.0.14 the string "phx" does not occur in wayfinder-code.

**Comment by yama** [comment]
@Deesen 
https://github.com/modxcms-jp/evolution-jp/blob/develop/assets/snippets/ditto/classes/ditto.class.inc.php#L334-L342
thanks. I wrote like this in the Japanese package. I do not remember the reason well, recursive processing is necessary.

**Comment by nick0** [comment]
Just confirming I am also having an issue in a site with a PHX call in the row template of a Wayfinder sub menu in a recently updated 1.2.1 site.

The link that was working fine in 1.0.15 was
`[+phx:if=`[+go-pdf+]`:is=``:then=`[+wf.link+]`:else=`[+go-pdf+]`+]`

This doesn't work at all in 1.2.1 - it returns a link to the home page for all links with this WF row template

Any tricks to getting it work how it was?

It sounds a big job to change to the internal modifiers and I am happy to stay with phx if I can. Otherwise other things might get broken.

**Comment by ricardo-lewis** [comment]
@nick0 
My trick to getting it working is detailed above: you'll need to put the bare placeholders in your template to "feed" PHX.

**Comment by ricardo-lewis** [comment]
@Deesen 
I'm pretty sure my WayFinder is not hotwired, that's why I need to use the syntax
``` [+phx:input=`[+wf.linktext+]` ```
...in order to use PHX at all. The problem is that syntax no longer works, the value of ```[+wf.linktext+]``` is empty, unless you put that placeholder outside the PHX call.

**Comment by Deesen** [comment]
Please reconfirm for my 100% understanding of your issue then

1. `[+phx:input=´[+wf.linktext+]´:test+]` outputs nothing / no linktext
2. `[+wf.linktext+] [+phx:input=´[+wf.linktext+]´:test+]` outputs double linktext

**Comment by ricardo-lewis** [comment]
Correct. I work around the double up by putting the placeholder as the title attribute.

**Comment by pmfx** [comment]
I had similar issue some time ago but with Ditto. Had to call placeholder before phx to work. I was hidding it in html comment :)

**Comment by nick0** [comment]
Thanks @ricardo-lewis. Ah I see what you mean by priming the pump...
If I put the  [+wf.link+] outside the phx call into the title attribute, it works as expected (just that the title is a little clumsy - but at least the link works now). My row template becomes...
`<li[+wf.classes+]><a href="[+phx:if=`[+go-pdf+]`:is=``:then=`[+wf.link+]`:else=`[+go-pdf+]`+]" title="[+wf.title+] - [+wf.link+]" [+wf.attributes+]>[+wf.linktext+]</a>[+wf.wrapper+]</li>`
Without that extra use of [+wf.link+] outside the phx call in the title attribute, it does not work. 
Thanks for the workaround.

**Comment by Deesen** [comment]
Ok I found the reason, $modx->_getTagsFromContent (called by Wayfinder -> $modx->parseText() ) does not return tags that are nested.

@yama Do you think it makes sense to add nested tags around Line 920 -> https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L920 ? This solves this issue for me:

    if($lc===$rc) {
	    // Add nested placeholders to $tags like for $fetch = "phx:input=`[+wf.linktext+]`:test"
	    if(strpos($fetch,$left)!==false) {
	        $nested = $this->_getTagsFromContent($fetch,$left,$right);
	        foreach($nested as $tag) {
	            if(!in_array($tag, $tags))
	                $tags[] = $tag;
	        }
	    }

        // Now add parent tag
	    if(!in_array($fetch, $tags)) {  // Avoid double Matches
	        $tags[] = $fetch; // Fetch
	    };
	    $fetch = ''; // and reset
	    $lc=0;
	    $rc=0;
	}

**Comment by nick0** [comment]
I have now found a problem where I can't "prime the pump". 
In a recently 1.2.1 updated site I am using phx to include wf.wrapper if a certain document like so:
`[+phx:if=`[+wf.docid+]`:is=`128`:then=`[+wf.wrapper+]`:else=``+]`
Its not feasible to include the wrapper for a mega menu twice.
I am looking forward to the official fix for this issue.
Thanks so much

**Comment by ricardo-lewis** [comment]
@nick0

Are you sure your problem is not with [+wf.docid+] ?

Try including that outside the PHX call.

**Comment by nick0** [comment]
Whoops, thanks @ricardo-lewis.... good pickup. Yes its with [+wf.docid+] , but for some reason where I put it I cannot get it to work like the other instance.

`<li[+wf.classes+]><a href="[+wf.link+]" title="[+wf.title+]"[+wf.id+]><span>[+wf.linktext+]</span></a>[+phx:if=`[+wf.docid+]`:is=`128`:then=`[+wf.wrapper+]`:else=``+]</li>`

Tried a few variations like this to test but still not working
`<li[+wf.classes+]><a href="[+wf.link+]" title="[+wf.title+]"[+wf.id+]><span>[+wf.linktext+]</span></a>[+phx:if=`[+wf.docid+]`:is=`128`:then=`[+wf.wrapper+]`:else=``+][+wf.docid+]</li>`

**Comment by ricardo-lewis** [comment]
@nick0

Is GitHub eating the backticks in your PHX call? Get those backticks in there, soldier!

**Comment by fourroses666** [comment]
You need to do three backtricks. 
` ` `  code ` ` `

**Comment by nick0** [comment]
Whoops. Classic comment @ricardo-lewis. LOL. 
Thanks so much for the tips on posting, I didn't realise that. 
The back ticks are in in the call on the CMS, github just got hungry and ate them.

**Comment by ricardo-lewis** [comment]
Well if your call has the backticks in all the right places then there's no help for us. Does wf-docid actually output into data-link?

**Comment by nick0** [comment]
Yes - wf-docid does - the row template and the output is shown below...
```<li[+wf.classes+]><a href="[+wf.link+]" title="[+wf.title+]"[+wf.id+] data-link="[+wf.docid+]"><span>[+wf.linktext+]</span></a>[+phx:if=```[+wf.docid+]```:is=```128```:then=```[+wf.wrapper+]```:else=``````+]</li>```

outputs
`<li class="first"><a href="/products/" title="Products" id="nav128" data-link="128"><span>Products</span></a></li>`

So its in there but the wf.wrapper for the drop down menu doesn't appear anymore. Tricky one.

**Comment by Deesen** [comment]
Have you added this? https://github.com/modxcms/evolution/issues/1200#issuecomment-274792833

**Comment by ricardo-lewis** [comment]
Have you tried using the syntax

[+phx:input='value here' etc +]

**Comment by nick0** [comment]
> Have you added this? #1200 (comment)

I just tried then @Deesen and it threw an error. All I did was add your code in that gap and upload and check. So I reverted back to the original. With my zero php skills I am better off waiting for the official updated file or something to download so I don't break anything.

Interestingly in an another site I use an IF snippet call to insert a drop down menu in a WayFinder row template in a similar manner and it works fine:
```<li[+wf.classes+]><a href="[+wf.link+]" title="[+wf.title+]"[+wf.attributes+]><span>[+wf.linktext+]</span></a>[[if? &is=`[+wf.docid+]:is:14` &then=`{{menu-mega}}` &else=`[+wf.wrapper+]`]]</li>```

And on testing the pdf phx call
```[+phx:if=`[+go-pdf+]`:is=``:then=`[+wf.link+]`:else=`[+go-pdf+]`+]```
and replacing with
```[[if? &is=`[+go-pdf+]:empty` &then=`[+wf.link+]` &else=`[+go-pdf+]`]]```
it works as expected

> Have you tried using the syntax [+phx:input='value here' etc +]

I haven't - and not sure how to turn this into the input style you mention. What would that look like in the format you suggest?:
```[+phx:if=`[+wf.docid+]`:is=`128`:then=`[+wf.wrapper+]`:else=``+]```

**Comment by ricardo-lewis** [comment]
Sadly the only PHX resource on the web stopped working a few days ago:

http://wiki.modxcms.com/index.php/PHx

Golf claps all round for shutting down the best MODX API documentation site.

Thank god for the Wayback Machine:
http://web.archive.org/web/20160506161117/http://wiki.modxcms.com/index.php/PHx

The "input" syntax is for use with your own custom modifiers. You might need to go down that route and get your hands dirty.

```[+phx:input=`[+wf.docid+]`:MyAwesomeModifier+]```

MyAwesomeModifier.phx.php:

```<?php return $output == 128 ? 'YEAH BABY' : 'BUMMER' ?>```

**Comment by ricardo-lewis** [comment]
I keep forgetting the If snippet exists, if it works well with WayFinder then by all means use it instead of a custom PHX modifier.

**Comment by Deesen** [comment]
@nick0 I have tested your issue yesterday and with my fix it worked. I also added some fixes to my repository but not 100% sure yet if they should be merged, we need everybody testing it. So you can download https://github.com/Deesen/evolution/blob/develop/manager/includes/document.parser.class.inc.php and replace your version with it.

Reg. IF-snippet, yes it works but I think we must avoid that developers have to rework PHX-calls after updating MODX. Backward-compatibility should be given IMO.

**Comment by nick0** [comment]
> The "input" syntax is for use with your own custom modifiers. You might need to go down that route and get your hands dirty.

Ah I see. Thanks for tutorial. That is cool to see how simple a modifier can be.

> @nick0 I have tested your issue yesterday and with my fix it worked...

Thankyou for the full file :) @Deesen. I have tested in 3 sites that had issues and works great, just like before. I think this should be rolled into the official package. Thanks so much.

> Reg. IF-snippet, yes it works but I think we must avoid that developers have to rework PHX-calls after updating MODX. Backward-compatibility should be given IMO.

I 100% agree with this. (This protocol wasn't followed for TinyMCE4 though - things have moved so not so smooth an transition).
