### ISSUE TITLE
Resource Locks - If network lost or sleep PC

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1201]
Scenario:
- Manager A is editing resource x and while editing either sleeps PC or network connection is lost.
- a couple of minutes elapses (or at least the session timeout length)...
- Manager B can now edit resource x and save some changes
- Manager A comes back 'online' and the browser is still editing resource x. 
- Manager A saves some changes in resource x and has now overwritten Manager B changes.

**Comment by Deesen** [comment]
Cannot be solved without a "keep resource locked"-ping like in first try/version of lock-elements, which alerted "lock is lost" in such a case.

I guess we cannot cover every single scenario.

**Comment by Deesen** [comment]
Old mechanismn: https://github.com/modxcms/evolution/issues/945

**Comment by bossloper** [comment]
OK, not a deal breaker and what we have works well. - closing for now.
