### ISSUE TITLE
Needless files in assets/js/jeditable

### ISSUE THREAD

**Issue by akool** [modxcms/evolution#1203]
Why so many jquery files in https://github.com/modxcms/evolution/tree/master/assets/js/jeditable/js ?
And other libraries also duplicated in _js/jeditable/_ and _js/jeditable/js/_

**Comment by Nicola1971** [comment]
Never noticed before. really too much copy of jquery and other js

**Comment by modxuser** [comment]
So far as I understood, these files were added as they are required for various elements of Doclister, you will have to ask @dmi3yy

**Comment by dmi3yy** [comment]
files from here: 
https://github.com/AgelxNash/DocLister/tree/master/assets/js/jeditable
