### ISSUE TITLE
TinyMCE4 queries in 1.2.1

### ISSUE THREAD

**Issue by nick0** [modxcms/evolution#1205]
Hello,

I have just upgraded a site from 1.0.15 to 1.2.1 and have a couple of TinyMCE4 queries.

1. In TinyMCE4, I can't seem to get rid of the second row of buttons like I could in the previous version.
![untitled-2](https://cloud.githubusercontent.com/assets/1768308/22130746/2cfeeeac-defe-11e6-920a-ca77204a56db.jpg)

In Tools > Configuration - I have set the buttons I want into one row. Nothing is in the second row
![untitled-1](https://cloud.githubusercontent.com/assets/1768308/22130734/16a6190a-defe-11e6-91cc-7c999a8e6045.jpg)

In Manage Users > Create/Edit User > User - I have deleted the 2 example rows because I want to use the global setting from the Configuration. This does not seem to work. Whenever I save the User file, the 2 rows are automatically added back in.

a. Is it possible to have one row of custom buttons. If so, how?

b. Is it possible to save a global setting for the TinyMCE4 buttons so it is not done in 2 places (seems to be needed in configuration and then for each user which is not ideal)? If so, how?

2. In this new version of TinyMCE4 in 1.2.1, the Formats menu shows the css styles in both inline and block in a double level drop down like so:
Formats
_ Inline
  _ _ Custom Style 1
  _ _ Custom Style 2
_ Block
  _ _ Custom Style 1
  _ _ Custom Style 2
![untitled-3](https://cloud.githubusercontent.com/assets/1768308/22131050/6792c712-df00-11e6-862c-d76cfa2db12c.jpg)

(Not sure what this does but In Plugins > TinyMCE4 > Configuration - inline is disabled.)

The TinyMCE in 1.0.15 had a simpler single level drop down more like this:
Formats
Styles
  _ Custom Style 1
  _ Custom Style 2

The words Inline and Block will confuse my clients.

Is it possible in this new version to just have a single level shown? If so, how to change?

Thanks for any help.

**Comment by ricardo-lewis** [comment]
I believe there are hard-coded defaults in the plugin folder that are "restoring" the empty button row.

**Comment by bossloper** [comment]
1. yes looks like a bug with the 'Manage Users > Create/Edit User > User ' for TinyMCE4. It will allow you to alter them but not set the fields to blank. Really the custom plugins options should be blank by default anyway ... as it is for TinyMCE3

2. The separate 'inline' and 'block' are used because TinyMCE4 custom formats do not work quite the same as TinyMCE3. See https://github.com/modxcms/evolution/issues/1134#issuecomment-270020646 onwards for the discussion. You can create your own by clearing the 'Custom Style Formats' field in the plugin config and using the 'Custom Parameters' field, though you will still come up with the issue that you cannot generate a single custom style that can be applied to both a block (p,h1,h2 etc) and inline as a span.

**Comment by nick0** [comment]
Thanks for your input. 

So #1 is a bug (agreed @bossloper) and #2 is a new setting (bit of a bummer as it will confuse many non technical users and take time to explain).

**Comment by nick0** [comment]
I Just noticed a possible third issue....

I also cannot seem to delete the "Block Formats" content in Manage Users > Create/Edit User > User...

If I delete the default "Paragraph=p;Header 1=h1;Header 2=h2;Header 3=h3" and save, they still load in the RTE and are visible again on next open.
![untitled-1](https://cloud.githubusercontent.com/assets/1768308/22230072/8789c0d8-e22b-11e6-8580-35e6d72a2733.jpg)
Same as with 1 above, global defaults are not honoured and I have to save the desired "Block Formats" for each user

**Comment by Deesen** [comment]
Yes I already prepared a fix for all parameters in user-settings and added a "Use global config"-checkbox where it was missing. Will do the PR soon.

**Comment by nick0** [comment]
Thank you Deesen
