### ISSUE TITLE
question: what is the autoload.php.blank and what should I do with it?

### ISSUE THREAD

**Issue by nick0** [modxcms/evolution#1206]
Hello,

In 1.2.1 I can see a file in the root of the Evo package called autoload.php.blank.

Just wondering if someone could please tell me what this is and what I should do with it? Eg rename it to remove the .blank, delete it etc.

Thanks a lot

**Comment by modxuser** [comment]
LOL

If you don't know what it is, you are obviously not using it, so delete it :)

The [Wiki has a post](https://github.com/modxcms/evolution/wiki/About-autoload.php), but the links are dead

**Comment by modxuser** [comment]
@nick0 If this issue is resolved can you close it please, if you are not sure how to, take a [look here](https://github.com/modxcms/evolution/issues/1213)

**Comment by fourroses666** [comment]
Afaik its a developer file to make things easier, you don't need it and can delete it.

**Comment by Deesen** [comment]
For example in case of a hack-scenario, or for creating statistics etc, developers can add some logging/checking functions (or whatever) into /autoload.php as it will be loaded first when /index.php is called -> https://github.com/modxcms/evolution/blob/develop/index.php#L50

**Comment by nick0** [comment]
Haha, funny @modxuser, In reality I don't know what 99% of these files and if I deleted them all I would be back to static sites :)
Thanks for confirming all, deleted.

**Comment by Deesen** [comment]
I added more infos, maybe useful at some point in future https://github.com/modxcms/evolution/wiki/About-autoload.php

**Comment by nick0** [comment]
Excellent work, thanks Deesen. That definitely clarified things for me.
