### ISSUE TITLE
Are these folders still needed?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1207]
On every install we have a couple of empty folders in assets/.
Do we need all of these?

- docs
- flash
- media
- site

I never use them.

**Comment by pmfx** [comment]
I don't use those also.

**Comment by modxuser** [comment]
The docs folder isn't empty - It has the changelog + end-user licence

Just a side note:

The "index.html" should be removed from the import and export folders

**Comment by Nicola1971** [comment]
a long time ago **sites** contained some custom css, i think is not used from years

**flash** and **media** were used to upload with richtext editors buttons (not sure if is still used)

**Comment by fourroses666** [comment]
@dmi3yy 

Can we remove the folder **flash** and **media**?
