### ISSUE TITLE
1.2.1 no Options in File Manager

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1208]
Did I miss something? I don't have the options :o

![no-options](https://cloud.githubusercontent.com/assets/523389/22153745/dc6d00de-df28-11e6-98af-86573ce02b42.gif)

**Comment by Nicola1971** [comment]
have you tried to refresh the browser cache?

missing icons too, seems not loading styles and font awesome

**Comment by Nicola1971** [comment]
try to upload again manager/includes/header.inc.php

**Comment by fourroses666** [comment]
Didn't help for me. (tried from development version too)

**Comment by fourroses666** [comment]
Works when selecting default theme.
My bad
