### ISSUE TITLE
Style "select files" button

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1209]
Detail item: File Manager little button style upgrade;
(or blue color)

Is this +1 or -1 ?
http://geniuscarrier.com/how-to-style-a-html-file-upload-button-in-pure-css/

![upload](https://cloud.githubusercontent.com/assets/523389/22154860/7b6ce56a-df2d-11e6-96a6-a05374f91ffa.jpg)

**Comment by modxuser** [comment]
@Nicola1971 

I have found something similar - for consistency across the board, I think the Save button in all sections should be the same colour.

Default
![save-resource](https://cloud.githubusercontent.com/assets/1859868/22244456/f5a37712-e22b-11e6-8168-8774637a9890.jpg)

On Move Resource Page
![move-resource-save](https://cloud.githubusercontent.com/assets/1859868/22244464/00d109ce-e22c-11e6-92e7-6445fbbd3fd1.jpg)
