### ISSUE TITLE
MODX Parse Error

### ISSUE THREAD

**Issue by DthMachine** [modxcms/evolution#1211]
Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2

after save page
Example:
`SQL > SELECT DISTINCT sc.* FROM modx_table`modx_site_content` AS sc LEFT JOIN modx_table.`modx_document_groups` AS dg ON dg.document = sc.id WHERE sc.parent='1' AND (1='1' OR sc.privatemgr=0) ORDER BY createdon LIMIT 0,`

Backtrace
include_once(string $var1)
manager/index.php on line 304
DBAPI->select('DISTINCT sc.*', string $var2, string $var3, 'ORDER BY createdon ', ' LIMIT 0, ')
manager/actions/document_data.static.php on line 80
`$rs = $modx->db->select(
	'DISTINCT sc.*',
	"{$tbl_site_content} AS sc
		LEFT JOIN {$tbl_document_groups} AS dg ON dg.document = sc.id",
	"sc.parent='{$content['id']}' AND ({$access})",
	"{$sort} {$dir}",
	$modx->table->handlePaging() // add limit clause  <-80 str
	);`
maketable.class.php - handlePaging():

`function handlePaging() {
		$offset= (is_numeric($_GET['page']) && $_GET['page'] > 0) ? $_GET['page'] - 1 : 0;
		$limitClause= ' LIMIT '. ($offset * MAX_DISPLAY_RECORDS_NUM).', '.MAX_DISPLAY_RECORDS_NUM;
		return $limitClause;
}`

im use php 7.0
mysql 5.7.13

**Comment by Deesen** [comment]
Too less details. Which MODX-version do you use? What did you do change to get this error?

From your description it seems to me your configuration is not up to date and setting `number_of_results` is empty/missing: https://github.com/modxcms/evolution/blob/develop/manager/actions/document_data.static.php#L56-L57

Are you sure every file has been uploaded correctly? Have you edited and saved MODX-configuration after updating?

**Comment by fourroses666** [comment]
Maybe a weird question, but did you use /install ?
