### ISSUE TITLE
Upgrade 1.2 -> 1.2.1 and tree error: ElementsInTree(OnManagerTreeRender)

### ISSUE THREAD

**Issue by blazkrapez** [modxcms/evolution#1212]
Hi,

After upgrading Modx Evo from 1.2 to 1.2.1 and logging into manager I get in tree this error:

« MODX Parse Error »
MODX encountered the following error while attempting to parse the requested resource:
« Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY 5,1' at line 1 »
SQL > SELECT Array FROM ORDER BY 5,1
Basic info
REQUEST_URI : 	/***i/manager/index.php?a=1&f=tree
Manager action : 	1 - Loading a frame(set)
Current Plugin : 	 
Referer : 	http://***/manager/
User Agent : 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by Deesen** [comment]
Seems to be related to https://github.com/modxcms/evolution/issues/1168#issuecomment-274262777 . Please assure every file has been uploaded correctly and the upgrade-process used the right setup.sql-file.

**Comment by blazkrapez** [comment]
You were right! My mistake. Copied the wrong version. you can close this issue.

**Comment by modxuser** [comment]
@blazkrapez Can you close this issue please, if you are not sure how to, take a [look here](https://github.com/modxcms/evolution/issues/1213)
