### ISSUE TITLE
Close Issues When Solved

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1213]
The issues list keeps growing for no reason - when an issue is resolved, **please** close it yourself.

Placing this extra work on the admins costs time, their time is better spent resolving issues and not closing the resolved posts

The editor has a button "Close Issue", all you have to do is press the button and the issue will be closed.

For those still not sure how to close their own issues, take a look at the image below:

![close-issue](https://cloud.githubusercontent.com/assets/1859868/22181719/d5bcb990-e091-11e6-8482-19dc31e1dd6c.jpg)

**Comment by modxuser** [comment]
If you are not sure where you have posted in the past, simply search for your posts in the filter search bar above the list of issue. As seen in the following image.

![search](https://cloud.githubusercontent.com/assets/1859868/22181837/45094bd0-e095-11e6-96d4-3e72048b5f83.jpg)

**Comment by Deesen** [comment]
Thanks for your efforts. Also every github-user has an "Issues"-button at the top of every page.
