### ISSUE TITLE
Upgrade Process - Make 'more forceful' 

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1215]
More thoughts... Is there a way the upgrade process could be made more forceful?

I.e. I know the manager presents an 'install folder found' message, but could it be even more forceful and restrict manage actions until it is run? And/or send the admin a periodic email until it is done. Similar for the 'save system configuration' after an upgrade, or could that even automatically be applied as part of running the install.

Maybe also some sort of ability to know if all files are uploaded correctly, though that might be tricky. I think SMF Forum software for example takes a hash of files and compares before upgrading, though not exactly sure what the process logic is there.

**Comment by Deesen** [comment]
CRC-Check is related to https://github.com/extras-evolution/evocheck/issues/2
