### ISSUE TITLE
Web User Passwords - Should Use Hash algorithm setting?

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1220]
Web user logic using the weblogin snippet takes account of failed login/blocked settings and CAPTCHA option from the System Configuration settings.
Currently it does not used the 'Hash algorithm' setting.

**Comment by yama** [comment]
https://www.google.com/search?q=phpass
Since we decided to use phpass for hashing, abolished "Hash algorithm".
I think webuser are still md5 hash.

**Comment by bossloper** [comment]
Yes, so weblogin snippet needs updating to use phpass.
