### ISSUE TITLE
Tinymce4 in introtext : too small richtexteditor

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#1222]
If you enable > Tinymce4  config  **Introtext RTE - add richtext- features to "introtext"** the text area is very small (tight)

![tmrt](https://cloud.githubusercontent.com/assets/7342798/22342284/20ba085c-e3f4-11e6-9f24-8c1dc8d79c34.png)

**Comment by Deesen** [comment]
You can customize dimensions here -> https://github.com/modxcms/evolution/blob/develop/assets/plugins/tinymce4/theme/theme.tinymce4.introtext.inc.php#L32-L33

**Comment by Nicola1971** [comment]
thanks @Deesen 
should be the same width - il will fix soon
