### ISSUE TITLE
Manager lang. vs TinyMCE config. lang.

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1226]
When the admin default is set to a different lang. other than English, but admin user lang. is English, the TinyMCE config. is still in default language. The rest of the config. area is as expected.

![tinymce](https://cloud.githubusercontent.com/assets/6113504/22407096/a5ad0892-e657-11e6-90fc-f5d3738c2a6a.png)

**Comment by Deesen** [comment]
Should be fixed.

**Comment by risingisland** [comment]
That did it. Thanks.
