### ISSUE TITLE
Broken parser logic

### ISSUE THREAD

**Issue by Pathologic** [modxcms/evolution#1227]
I've received complain about strange work of my EvoTwig plugin in last Evo versions. The investigation shows 2 aspects of the problem:
1. OnLoadWebDocument event was invoked before the parseDocumentSource method call. So it was possible to skip parser by setting minParserPasses and maxParserPasses to -1 with plugin. Now this ability is lost because OnLoadWebDocument is invoked after parseDocumentSource.
2. On the other side, there is newly introduced cleanUpMODXTags method now, which acts as parseDocumentSource method in general, but it's not possible to avoid its call. What's the use of this method? Is 10 parser passes not enough to clean MODX tags up?

And I see that cleanUpMODXTags method (as well as mergeConditionalTagsContent and _getSGVar) ignores enable_filter setting.

**Comment by Deesen** [comment]
1. Indeed the logic of OnLoadWebDocument has been changed on 15.12. with https://github.com/modxcms/evolution/commit/7dbcc9cce822cf94d8408eba39d56d57079a72cb . The definition of this event is "This event fires before any tags are parsed" so you are right. Maybe #1107 could be fixed with `minParserPasses and maxParserPasses set to -1` instead.

2. @yama You probably know better.

**Comment by Pathologic** [comment]
@Deesen minParserPasses property is not used anymore: https://github.com/modxcms/evolution/commit/926c1a0eb8bb2983ea23f74827acb33fa70b135b#diff-b91fad0266a33c1d4d87dff876939692

**Comment by Deesen** [comment]
Today I received a support-request for plugin https://modx.com/extras/package/paginationplugin which does not work since Evo 1.2, probably due to the above changes.

**Comment by sonicpunk** [comment]
For the pagination plugin I changed the output for line 110 from:
$modx->documentObject['content'] = $pip_content;

to:

$modx->documentContent = $pip_content;
$modx->documentContent = $modx->parseDocumentSource($modx->documentContent);

Thanks to the input from @Deesen .  The result is that it now parses the content correctly, but the output to the browser does not include processing the template.  So in the browser you just get the content delivered.

Any idea how to do this?  

PS: the plugin is triggered on the OnLoadWebDocument event.

**Comment by adminko** [comment]
Поломали событие OnLoadWebDocument
Ранее $modx->documentContent хранил шаблон $modx->documentObject данные страницы в массиве, и можно бло делать инъекцию в массив тем самым добавлять на страницу свои плейсхолдеры. Сейчас так не работает, так как parseDocumentSource выполняется до вызова события.

**Comment by zabudkin** [comment]
Пиздец, нахуя поломали?! Введите новое событие, зачем трогать то, что уже прижилось мать вашу?

**Comment by dmi3yy** [comment]
1 простба не выражаться 
2 1.2.1 вышла пару месяцев назад а вы добрались только сейчас значит не так оно вам и надо. 
3 помогайте с тестированием я всегда RC выпускаю но тут оно вам пригорело а помогать в тестах вам не надо.... 

Так что будьте скромнее в своих выражениях.

**Comment by yama** [comment]
Sorry, please give me actually test case. I will correct it soon.

**Comment by Pathologic** [comment]
@yama Сreate OnLoadWebDocument plugin:
```
$modx->minParserPasses = -1;
```
The required behaviour of the parser is to output document template as is (except [! !] and [~ ~]).

My proposed fix is https://github.com/modxcms/evolution/pull/1318

**Comment by yama** [comment]
thanks!
