### ISSUE TITLE
Things about Naming

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#1229]
Before MODX, things about Etomite.
2003. At first it was named BCMS. After that, because of the trademark problem etc., changed the name two or three times. Eventually, the name "Etomite" was chosen.

The name "MODX Evolution" has no problem. It is because it has originality.
But what about "Evolution CMS" and "EVO-CMS"? As we already know, there is already a similarly named product.

I thought about it.

One of the hints, anagram.

Evolution
Unveil Too
Outlive On
Outlive No
Voile Unto
Olive Unto
Volute Ion
Ovule Into
Voile Nu To
Olive Nu To
Vile On Out
Vile No Out
Vile Nu Too
Live On Out
Live No Out
Live Nu Too
Evil On Out
Evil No Out
Evil Nu Too
Veil On Out
Veil No Out
Veil Nu Too
Nevi Lo Out
Vine Lo Out
Vein Lo Out
Vie Lo Unto
Vie Loot Nu
Vie Tool Nu
Vie Lout On
Vie Lout No
El Vino Out
Novel I Out
Volute I On
Volute I No
Ovule I Not
Ovule I Ton
Ovule In To
Ovule It On
Ovule It No
Ovule Ti On
Ovule Ti No
Love I Unto
Love In Out
Vole I Unto
Vole In Out
En Viol Out
Oven I Lout
Toe Viol Nu
Veto Oil Nu
Vote Oil Nu
Vie Lo Nu To
Oleo I Nu Tv
Love I Nu To
Vole I Nu To
Veto I Lo Nu
Vote I Lo Nu
http://wordsmith.org/anagram/index.html

I like the name "Evolution" and I think that is fine. But if we have even more nice name.

**Comment by Deesen** [comment]
I think like "never change a winning team" we should stay with "Evolution / Evo": 

- people are already used to it
- it will help to be found when users google for "modx evolution update"
- domains are already reserved like evolutions-cms.com and evolution-docs.com
- I think the name describes our CMS very well

**Comment by yama** [comment]
OK, it may be. Let's do so, Thank you.

**Comment by Fr3ddy7** [comment]
evolutions 8)))

**Comment by modxuser** [comment]
I'm for the current "Evolution" and short form "Evo"

**Comment by fourroses666** [comment]
These hints are very funny :))
`Evil Nu Too` 
`Love In Out`
`Olive Unto`
`Vote I Lo Nu`

**Comment by nick0** [comment]
Love In Out. What a name for a CMS/F!!!
