### ISSUE TITLE
/* Commented text */

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1233]
I have a 1.2.1 EVO site and use:
```[*id:is=`1`:then=`{{my chunk}}`:else=``*]```

When my chunk has: /* uncommented */ text in it outputs nothing.
Without its all oke.

Maybe this is already fixed or don't want to have fixed because of vulnerability.

**Comment by Deesen** [comment]
Cannot recreate this issue. For me the chunk will be outputted as expected, including `/* comment */`

**Comment by fourroses666** [comment]
Need to recheck on a clean 1.2.1 install instead of an updated site because I did have this issue.
