### ISSUE TITLE
Help: Canonical Modifier

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1234]
I am attempting to get the canonical tag in the head to work properly, I have the following

    <link rel="canonical" href="[(site_url)]<@IF:[*id:isnt(1,118,119)*]>[~[*id*]~]<@ENDIF>">

But this won't work. If I remove the ",118,119" it doesn't change a thing

Looking at the redered HTML, the canonical output for the homepage is correct as is for every other page, but 118 + 119 are shown as well, they should default to the homepage as they are the 403 + 404 pages

I have a similar call using ultimateparent, where I have used this format "(1,118,119)" and that works, so don't know why my modifier call won't work - any halp appreciated, cheers

**Just a side note:**

Looking at the demo content in a new Evo install, the "MODX startup - Bootstrap" template uses:

    <link href="[(site_url)]<@IF:[*id:isnt(1)*]>[~[*id*]~]<@ENDIF>" rel="canonical">

But, the 404 page (ID=7) isn't in the call - which it should be, in my opinion

**Comment by modxuser** [comment]
I have it working, but it seems clumsy:

    <link rel="canonical" href="<@IF:[*id:is(1):or:is(118):or:is(119)*]>[(site_url)]<@ELSE>[(site_url)][~[*id*]~]<@ENDIF>">

**Comment by Deesen** [comment]
Why "clumsy"? Maybe shorten `is(1):or:is(118):or:is(119)` by `in(1,118,119)`?

**Comment by modxuser** [comment]
@Deesen 

Clumsy, due to the amount of code being needed

I didn't think "**in**" would work, as I thought in that situation the id must be "in" that id, meaning, a child document

Possibly one of the reasons I gave up on PHP in 2000, a serious lack of understanding for the logic.

Thanks Dennis - your solution works perfectly
