### ISSUE TITLE
New built-in IF / ELSE don't work with placeholders

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#1236]
_(I've posted this on Slack, but it should be here too - just in case - as it is an issue.)_

Does new built-in IF / ELSE filters/modifiers works with placeholders? 
It work with Template Variables [**] but don't work with placeholders [++].

Example:

![pasted image at 2017_01_19 16_30](https://cloud.githubusercontent.com/assets/10888055/22565833/e77ce244-e989-11e6-9bc6-b28a64ebafc5.png)

Doesn't matter if [+ph_0+] has value or not. <@IF: .... > simply don't work.

@yama you mentioned that the problem may be here:
https://github.com/modxcms/evolution/blob/1.2.1/manager/includes/document.parser.class.inc.php#L1219-L1220

**Comment by modxuser** [comment]
Possibly related [to this](https://github.com/modxcms/evolution/issues/1127)

**Comment by dmi3yy** [comment]
For me better use snippet IF 



Отправлено с iPhone
