### ISSUE TITLE
Incorrect Version Number?

### ISSUE THREAD

**Issue by jpdevries** [modxcms/evolution#1237]
Installed Evo 1.2.1 but it displays as 1.0.2 in parts of the dashboard.

![](http://j4p.us/2c0c0w3C2u2d/Screen%20Shot%202017-02-02%20at%202.41.18%20PM.png)

**Comment by fourroses666** [comment]
Did you save the config page?

**Comment by dmi3yy** [comment]
Save config page. And reload page in browser

Отправлено с iPhone

**Comment by nick0** [comment]
I noticed this too. There seems to be a slight delay (maybe caching) with the new version number showing.

**Comment by jpdevries** [comment]
@fourroses666 I updated the database info in `manager/includes/config.inc.php` when I set up the site.

It seems like the issue might be that the installer (which I ran) isn't updating `/assets/cache/siteCache.idx.php`.

**Comment by fourroses666** [comment]
But did you navigate to: Tools > Configuration and saved that page?
When you did an update and used /install then you need to save that page after its complete with installing.

_I recently had an issue with Mod_security setting on the server. When I tried to save the configuration page I got a 404 and the old version wasn't updated._

**Comment by bossloper** [comment]
But did you navigate to: Tools > Configuration and saved that page?
 - which relates to this #1215
