### ISSUE TITLE
Remove PHx/modifiers/filters from core

### ISSUE THREAD

**Issue by Ronef** [modxcms/evolution#1238]
Because:
* a lot of bugs;
* a pile of crutches in the code;
* few people know about it, so we can remove painless.

I remember PHx even with the MODX 0.9.6.3 and it is always **only problems**. We removed this garbage from each project all the time. And now he's added to the core… I think it is the worst idea. Stable parser turned into misery.

**Comment by modxuser** [comment]
@Deesen @yama 

Please correct me if I am wrong, but "PHx" hasn't been added to the core.

[Modifiers](https://github.com/modxcms/evolution/wiki/@IF-@ELSEIF-@ELSE-@ENDIF) and [Cross References](https://github.com/modxcms/evolution/wiki/Cross-references) have been added

Can you also be more explicit with the problem(s) you have experienced ?

**Comment by Deesen** [comment]
Why not just disable "filters/modifiers" in MODX-config? Does the parser still cause issues then? Which ones?

**Comment by bossloper** [comment]
I think 'filters' are disabled by default anyway?
![untitled](https://cloud.githubusercontent.com/assets/1744687/22589650/3d62b840-ea03-11e6-9db8-d55ffec1399b.png)

**Comment by MrSwed** [comment]
@Ronef 
Please explain what you mean?
Disable alternative development phx logic at all?
#623 

In most cases, problems occur with phx if misused.

**Comment by Deesen** [comment]
@ronef I do not understand why I invested time now again. On Slack I kindly asked for testing my revised [document.parser](https://raw.githubusercontent.com/Deesen/evolution/develop/manager/includes/document.parser.class.inc.php), got no response at all. So now I have downloaded your ddIf-snippet, and have set up testing case as per your Slack-example:

	[[ddIf?
		&operand1=`1`
		&operand2=`1`
		&trueString=`[[ddIf?
			&operand1=`2`
			&operand2=`2`
			&trueString=`[[ddIf?
				&operand1=`3`
				&operand2=`3`
				&trueString=`True 3`
				&falseString=`False 3`
			]]`
			&falseString=`False 2`
		]]`
		&falseString=`False 1`
	]]

- Without my fix, nested call returns `False 1`
- With fix, nested call returns `True 3`

**Comment by Deesen** [comment]
This should be the part that fixes it https://github.com/modxcms/evolution/pull/1224/commits/a30163dbe16e6b2ba4f7033f1fdb2b3942715472#diff-b91fad0266a33c1d4d87dff876939692R948

**Comment by janniconl** [comment]
I never have problems with PHX (I did a lot with it) and use it in about 30+ installations in some form. Please stay backwards compatible.
(Although I don't really care if it is in core or not, I always build my own custom installations)

**Comment by modxuser** [comment]
**My Opinion:**

PHx is a third party add-on that is not distributed within Evo per default, so by rights, it should keep up with Evo development, not the other way around

**Comment by pmfx** [comment]
Itoo never had bigger issues with PHx but built-in filters/modifiers are a fine replacement and I really appreciate it. Needs some polishing still.

**Comment by nick0** [comment]
The IF snippet sure is a great alternative @modxuser. I use that a lot too as a phx alternative.

Correct me if I am wrong... I am pretty sure though that the IF snippet does not work with MultiTV. MultiTV requires phx for if/else, if empty, if not empty etc in the templates.

Do the new modifiers work with MultiTV?

I think there would be more buy in and less uncertainty on the new modifiers if there was documentation with example usage, and comparisons showing typical PHx calls and the equivalent Modifier call. Without that I wouldn't know where to start.

I cannot agree with @janniconl enough. Backwards compatability is a must. Its reasonable to expect that phx calls would still work when updating sites to the latest version of Evo.

**Comment by Deesen** [comment]
I also had now issues with the new modifiers, and I understand now better the statement "stable parser turned into misery".. A simple if/else call did not work for me like

    [+phx:if=`[+phx:session=`payment`+]`:is=`paypal`:then=`
       [!eForm? &formid=`form_paypal`!]
    `:else=`
      [!eForm? &formid=`form_invoice`!]
    `+]

so I had to disable Filters and enable latest PHX to get it working again.

**Comment by Ronef** [comment]
Sorry for the inaccuracy in terms. 🙏

Once we have updated one of the sites (official clean distributive, site without PHx) and on some pages became displayed something like `PHX_INTERNAL`.

I think, modifiers (or PHx, or call it what you want) is too hard logic for the parser. At least it follows that:
1. Difficult to understand, support and development ugly code of parser and in all Core in generally.
2. Large consumption of resources (low resource consumption is one of the most important features of MODXEvo).
3. Fragile code and inevitably appearance of some bugs (because it is too difficult logic).

And… Why? For what? For some subjective syntax sugar?

God! Just use a couple of very simple snippets instead: more clean, more power, less troubles, more love and happiness. ❤️

**Comment by modxuser** [comment]
I think the problem here is that these things haven't been tested enough - it's that simple, i've said this before - too many updates with not enough testing on different installs

**But, the problem is now:** since the modifiers have been integrated into the core, Evo has been downloaded and installed multiple thousands of times - so simply removing the core modifiers is in my opinion not a solution.

Why, simple, because people are using the new code

The solution is to clean up the bugs and refine the code, to have one solution in place that covers all the requirements that "PHx" + "If" cover

**Comment by dmi3yy** [comment]
Problems now: 
- hardest code
- phx + modifiers (1 need delete) they sublicate functions 

- snippet if and core @IF ( 1 need delete) 

Our way: simple code, fast work, simple study



Отправлено с iPhone

**Comment by Ronef** [comment]
@modxuser There is no docs about modifiers → very few people know about it. That's why we can remove it.

What about performance?

**Comment by nick0** [comment]
> The solution is to clean up the bugs and refine the code, to have "one solution" in place that "ticks" all the requirements that "PHx" + "If" do.

With some documentation so its easy to see the equivalent calls.

The IF snippet, whether hard coded or as a snippet is so nice. Please don't take away this IF functionality. It can do things that PHx, and presumably the new in built modifiers, can't. It also doesn't seem to cause any problems

**Comment by modxuser** [comment]
> There is no docs about modifiers → very few people know about it. That's why we can remove it.

That's not correct, docs can be found [here](https://github.com/modxcms/evolution/wiki/@IF-@ELSEIF-@ELSE-@ENDIF), [here](https://github.com/modxcms/evolution/wiki/Global-var), [here](https://github.com/modxcms/evolution/issues/623#issue-153920253),  [here](http://www.evolution-docs.com/documentation/designing/modifiers/at-modifiers), [here](http://www.evolution-docs.com/documentation/designing/modifiers/) & [here](http://mblo.info/matome/modifiers/)

The Japanese site can easily be translated by Goole, which I found to be the best solution (sadlyas I don't like Google)

Claiming that "very few people know about it" is a huge statement, how do you know who is or isn't using the new code ?

**Q&A** - I can only speak for myself from my experience(s)

**Q:** What about performance?
**Ans:** I haven't experienced any loss

**Q:** How would it work with 10 000 docs with 5 000 visitors per day?
**Ans:** I don't have 10,000 docs but I do have a lot more than 5000 uniques per day without a problem

**Q:** 50 000 docs / 1 000 000 docs?
**Ans:** Does anyone actually have a real life working site this large, if the answer is yes, please let us know your experiences

**Q:** How people can update this sites now?
**Ans:** I have updated a multitude of sites and not experienced any problems

**Q:** No one thinks of them?
**Ans:** I am not sure where your going here, but if you mean that the modifiers were simply added without asking the community, then that's possible. A lot has happend in the last year whereby only a small amount of people have actually said yes / no to things that have been added / removed

One of the problems now with Evo is that the DEV community seems to be getting smaller and smaller and as such the changes seem to be getting more on a personal needs basis.

**Comment by janniconl** [comment]
> The IF snippet, whether hard coded or as a snippet is so nice. Please don't take away this IF functionality. It can do things that PHx, and presumably the new in built modifiers, can't. It also doesn't seem to cause any problems

@nick0, out of curiosity, can you name an example of what can be done with IF but not with PHx?

**Comment by Nicola1971** [comment]
> Q: No one thinks of them?
Ans: I am not sure where your going here, but if you mean that the modifiers were simply added without asking the community, then that's possible. A lot has happend in the last year whereby only a small amount of people have actually said yes / no to things that have been added / removed

Not true in this case

@yama posted on modx forum about modifiers lot of time ago: 1 year, 5 months ago - 
was before **Evo 1.0.1**!!
https://forums.modx.com/thread/98065/sample-package---builtin-phx-function#dis-post-530626

as always, only a few people  are interested or have replied or commented.

**Comment by fourroses666** [comment]
Will removing PHx only clean up code or does it have development issues?

I don't think its a good idea to remove it when its only for cleaning up the code. 
I and probably many people will have to fix allot of sites. Will have a big impact.
It does can be tested by disableling PHx plugin before upgrading Evo without PHx in the core but will give me a day work to check 100+ sites.

So the question is, how big of issue is it to keep PHx?
I'm not a developer.

Also I don't have these large sites so don't experience any performance issues.

**Comment by modxuser** [comment]
@Nicola1971 

Thanks for that, I wasn't aware of the forum post, but I did say "that's possible.", I didn't say "It Was".

But again here, your statement is 100% correct
> as always, only a few people are interested or have replied or commented.

**Comment by Nicola1971** [comment]
...and here:
https://forums.modx.com/thread/100131/new-features-for-template-work

**Comment by Nicola1971** [comment]
I agree about the communication issue between devs and users.

github is not the right place to communicate with the world.

We need our own forum, with a dedicated "dev" board to announce, presents and publicly discuss new features with all evo users. 

but people must to test beta and devs releases, not just asking or criticize new features - this is the way to avoid issues and this kind of discussions, 1 year and half later.

in Italy we used to say: "_who keeps silent, consents_"

**Comment by bossloper** [comment]
Agreed. And backwards compatibility should be considered. Upgrading should not require admins to rewrite their code

**Comment by dmi3yy** [comment]
We remove or update in evo 2.0 

I think from next month we start discus about this and start  do EVO;) 

I have many question and before work we disqus ;)


Отправлено с iPhone

**Comment by modxuser** [comment]
> We remove or update in evo 2.0

I am for [one solution](https://github.com/modxcms/evolution/issues/1238#issuecomment-279696680) that works - not multiple solutions that cause problems between users in the community

**Comment by dmi3yy** [comment]
Yes one solution will be work fine 


Отправлено с iPhone

**Comment by janniconl** [comment]
Can anyone explain **why** features like the filters/modifiers and @IF needed to be in core modx?

What was/is wrong with just using PHx and IF as (optional) snippets? I am not a PHP developer but as I mentioned before I never had any problems with PHx and I can make almost every solution I want with it. (heck, I havent ever used IF-snippet either).

The power of MODx always was and is that its lightweight and that users can customize it according to their needs. The solution of some snippets worked fine for years. I sort of agree with @Ronef's comment (#1238#issuecomment-279694761) on this topic

Next to this I agree with @modxuser that one solution is the preferred option. Why not stick to those which are around for years now: PHx and IF snippets.

**Comment by dmi3yy** [comment]
Yes with external snippet plugin i see its better.  

Unfortunately the current implementation of highly complicated parser code which now does not work consistently. And also does not cover the full solutions that were previously in the end we got a more complex code + a few extra suschnost

Отправлено с iPhone

**Comment by bossloper** [comment]
What did evo gain with the changes to the parser? ... which does seem to have introduced compatibility issues.

**Comment by nick0** [comment]
> @nick0, out of curiosity, can you name an example of what can be done with IF but not with PHx?

@janniconl I can't remember specifics as the project was a couple of years ago. But I do remember running into problems on one big site where I had to use some IF and some PHx for things to work as expected (mainly for when tv not empty, include something) - all PHx or all IF seemed to have issues. The site used an external booking system embedded as iframe and not sure if that impacted things. It was a wierd one and I that had never experienced before and nor since.

**Comment by janniconl** [comment]
@nick0 Alright, thanks for the info mate!
