### ISSUE TITLE
Bug: Tinymce4 French Language File

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1239]
@Deesen @dmi3yy @yama 

**To replicate:**

1) Ensure that Tinymce4 is activated and used as the default editor
2) Change the manager language to either of the "French" choices: "Francais" or "Francais-utf8"
3) Now try and edit a page where the editor is in use

You will notice, all rich text areas, content, TVs and intro text no longer show the editor.

**To fix the problem:**

1) Navigate to: assets/plugins/tinymce4/tinymce/langs/
2) Duplicate the "fr_FR.js"
3) Rename the duplicated "fr_FR.js" to "fr.js"

Once duplicated, refresh your manager and attempt to edit a page again - the editor now works

**Important Note:**

Whether this is the correct solution to remove this issue is a matter that a DEV will have to look at

**Comment by Deesen** [comment]
Related to #1177 I guess.

**Comment by modxuser** [comment]
By the looks of things - Yes

Seems to be the same problem, just a different language file

**Comment by lottaar** [comment]
Same solution works for Swedish - duplicate sv_SE.js and name it sv.js.

**Comment by modxuser** [comment]
@lottaar This Repo. is no-longer monitored

May I suggest you post on the [new version here](https://github.com/evolution-cms/evolution/issues)
