### ISSUE TITLE
Working with Ditto Tags?

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1241]
I have a question regarding posts with tags:

In a Ditto listing, I can display the tag corresponding to the posts. 
How can I display the tag within the article itself that links to other articles with that tag? 

Any help would be greatly appreciated.

**Comment by pmfx** [comment]
I have used Ditto for it:

**Under article:**

`[[run_ditto_articleTags?
&id=list
&documents=[*id*]
&tagDocumentID=557
]]`

**Snippet:**

`<?php`
$params['id']=$id;
$params['documents']=$documents;
$params['tpl']='@CODE:[+tagLinks:isnot=None:then=Tags: [+tagLinks+]+]';
$params['tplTagLinks']='@CODE:`<a href="[+url+]">[+tag+]</a>`';
$params['tagData']='articleTags';
$params['tagDelimiter']=';';
$params['tagDisplayDelimiter']=', ';
$params['tagDocumentID']=$tagDocumentID;

$output = $modx->runSnippet('Ditto',$params);

return $output;
`?>`

**Comment by risingisland** [comment]
Thanks for the reply @pmfx 

I just pasted this in, but it is not showing any output.
Also, what is the 557 from tagDocument?

**Comment by Deesen** [comment]
Maybe `$params['extenders'] = 'tagging';` is missing in the params-list?

**Comment by Deesen** [comment]
And 557 is the target-page with a Ditto-call to receive the tags and show filtered documents.

**Comment by modxuser** [comment]
Dont know if this will help, but anyway:

**In your article page:**

    <ul class="tags">
    [[Ditto?
    &documents=`[*id*]`
    &tagDocumentID=`10`
    &tagData=`myTags`
    &tpl=`DittoTags`
    &tplTagLinks=`DittoTagLinks`
    &tagSort=`1`
    &tagDelimiter=`,`
    &tagDisplayDelimiter=` `
    ]]
    </ul>

**&tagDocumentID** = The landing page where all the results are shown, no matter what tag is selected e.g domain.com/tags?tag=tagname

**&tagData** = Template Variable with all the tags

**DittoTags** chunk: `[+tagLinks+]`

**DittoTagLinks** chunk: `<li><a href="[+url+]" rel="tag">[+tag+]</a></li>`

**In your landing page:**

    <ul class="nospace clear">
    [[Ditto?
    &parents=`1,2,3,4,5`
    &orderBy=`id DESC`
    &tagData=`myTags`
    &tagDelimiter=`,`
    &tagDisplayDelimiter=` `
    &tpl=`MyDisplayOutput`
    &summarize=`10`
    &paginate=`1`
    &paginateAlwaysShowLinks=`1`
    &showInMenuOnly=`0`
    &showPublishedOnly=`1`
    &tplPaginatePage=`DittoPaginatePage`
    &tplPaginateCurrentPage=`DittoPaginateCurrentPage`
    &tplPaginatePrevious=`DittoPaginatePrevious`
    &tplPaginatePreviousOff=`DittoPaginatePreviousOff`
    &tplPaginateNext=`DittoPaginateNext`
    &tplPaginateNextOff=`DittoPaginateNextOff`
    ]]
    </ul>

**MyDisplayOutput** = chunk which determines how the individual results are displayed

The pagination templates are down to you - I persoanlly prefer using my own for safety reasons, I don't like to use the default Ditto classes

**Comment by risingisland** [comment]
@modxuser Thank you.
This works fine, and is the most straight forward for me to understand. Awesome!

**Comment by modxuser** [comment]
@risingisland 

I have added the content of my small tutorial to the new docs, it can be found here: [Tagged blogging with Ditto](http://www.evolution-docs.com/tutorials/extras-how-to/ditto-tutorials/tagged-blogging-with-ditto-ex-2)

The page now has links to references throughout the docs section and a bit more of an explanation to how the call works

**Comment by risingisland** [comment]
@modxuser 
You wouldn't happen to have a simple way to style the pagination in ditto?
So it is not needed to use the default "ditto_currentpage" etc.
Or is this all hardcoded into the Ditto snippet?

**Comment by modxuser** [comment]
@risingisland 

The pagination uses its own templates, you can see in the bottom call that I have created chunks names for each element - I would suggest doing the same and use your own code / style

Otherwise, yes, its hard coded in the defaults, [as seen here](http://www.evolution-docs.com/extras/ditto/ditto-parameters#pagination-parameters)

**Comment by modxuser** [comment]
You could use the @CODE method

    &tplPaginateCurrentPage=`@CODE <li>[+page+]</li>`

**Comment by risingisland** [comment]
Thanks for the info and the docs link.
I was under the impression that `@CODE` was not recommend because of of the "=" sign?

**Comment by modxuser** [comment]
Never heard that before :)

**Comment by risingisland** [comment]
@modxuser 
Thanks, the `@CODE` calls work perfectly, very quick and easy to implement. 

I had read and old [post](https://forums.modx.com/thread/42454/ditto-paginate-next-and-previous-template#dis-post-245775) and didnt bother to try it.

**Comment by modxuser** [comment]
@risingisland 

I hadn't seen that post before

I have updated [the tutorial](http://www.evolution-docs.com/tutorials/extras-how-to/ditto-tutorials/tagged-blogging-with-ditto-ex-2) in the docs, cleaned it up a bit and added more "explanatory" information, including the `@CODE` elements
