### ISSUE TITLE
Language of Date

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1243]
Does anyone know if it is possible to have the date display in a given language other than English?
ex.: April 10, 2017 => 10 Abril, 2017 or 10 Apr. 2017 => 10 Abr. 2017

I have tried adding `setlocale (LC_ALL, 'es_ES');` in config.inc.php, but nothing happens.

**Comment by Deesen** [comment]
`date()` returns only english language, so you could try [strftime()](http://php.net/manual/de/function.strftime.php) together with `setlocale()`.

**Comment by modxuser** [comment]
@risingisland 

An [old post of mine](https://forums.modx.com/thread/87641/date-time-in-a-different-language-to-english) in the forum may help you

**Comment by risingisland** [comment]
Thanks for your input, but nothing seems to want to work for me.
I believe in the past I had added setlocale inside of the ditto snippet, but that doesnt want to do anything either anymore.

**Comment by modxuser** [comment]
May sound stupid BUT, if you have updated the snippets since you originally added the code - have you since changed them again ? Have you re-added the setlocale ?

**Comment by risingisland** [comment]
Im trying to add this to a new install, just not getting anywhere with it.
Will try again in the morning after some coffee, see if that help.

**Comment by modxuser** [comment]
Good luck :)

**Comment by modxuser** [comment]
Ah, before I forget - you are on a spanish IP aren't you

I think setting the locale also has to do with the server location, but not being a developer I am not sure

**Comment by Deesen** [comment]
To add setlocale() you can use also [autoload.php](https://github.com/modxcms/evolution/wiki/About-autoload.php#custom-php-settings-at-run-time). It also will not get removed by future updates.

The question is, what exactly are you trying to achieve? Which TV/placeholder and which modifier do you use?

Maybe it helps, in Ditto you can also use placeholder `[+date+]` with param

    &dateFormat=`<span class="day">%d</span><span class="mon">%b</span><span class="year">%Y</span>`

**Comment by Deesen** [comment]
Also setlocale() can only set given languages. Means maybe "es_ES" or "es_ES.utf8" is not installed by your explicit hoster.

**Comment by risingisland** [comment]
Maybe that is the problem, I have a different host now. I didnt know that it was server dependent.

**Comment by Deesen** [comment]
It seems you can easily check if it is installed using:

    setlocale(LC_ALL, 'es_ES') or die('Locale not installed');

**Comment by Deesen** [comment]
But just now I have an issue with getting just a blank screen when using "setlocale()" inside autoload.php. I have to remove it. Veeeery strange.
