### ISSUE TITLE
Chunk inside of Ditto template, [+longtitle+]

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1244]
I have a chunk which contains the following:
` <a href="mailto:?Subject=[+longtitle+]&amp;Body=Un articulo interesante de la página web de %22[(site_name)]%22: %0D%0A %0D%0A[+longtitle+]...%0D%0A [(site_url)][~[+id+]~]%0D%0A %0D%0A"><img src="assets/templates/social-icons/email.png" alt="Email" /></a>`

Which is then placed inside of a ditto template via `{{social-links}}`

Problem: `[+longtitle+]` does not display, but `[+title+]` does?

**Comment by modxuser** [comment]
Where are you getting `[+title+]` from ?

Available resource fields are:

    [+pagetitle+]
    [+longtitle+]
    [+introtext+]
    [+content+]

Just checked one or two of my chunks and see that they also use longtitle and work

**Comment by modxuser** [comment]
I know this is probably a stupid question, but I will ask anyway - does the longtitle have content in it ?

**Comment by Deesen** [comment]
The problem is that the chunk(s) will only get parsed after Ditto-parsing is finished, so placeholders inside chunk will not be replaced. But you can try to make use of #625 and replace your chunk by the following :

    {{social-links?longtitle='[+longtitle+]'}}

**Comment by risingisland** [comment]
The default "ditto_blog" chunk...
![title](https://cloud.githubusercontent.com/assets/6113504/22744240/b651b480-ee14-11e6-8060-604d8c57b098.png)

And yes, longtitle does have info in it.

**Comment by risingisland** [comment]
@Deesen Wow, I didnt know that was possible, and it works just fine. Thanks
