### ISSUE TITLE
Checkbox field incorrect rendering

### ISSUE THREAD

**Issue by sunhaim** [modxcms/evolution#1245]
It seems that the checkbox field with more than one checked value not renders properly ("123", when should be "1||2||3").

**Comment by Deesen** [comment]
Which version?

**Comment by sunhaim** [comment]
1.2.1 Jan 11, 2017

**Comment by dmi3yy** [comment]
You need set visual component like delimited list. Its work same in all version

Отправлено с iPhone

**Comment by sunhaim** [comment]
I did and it works, but default delimiters ("||") should not be cut out, its a bug.

**Comment by Deesen** [comment]
I just set up latest dev like

![delimiter](https://cloud.githubusercontent.com/assets/8569221/22769915/6cba2122-ee8c-11e6-9c71-32692323a281.png)

and my TV `[*issue_1245*]` will output `2|||3`.

**Comment by dmi3yy** [comment]
All time by defauld  be nothing. 


Отправлено с iPhone
