### ISSUE TITLE
ID of the resource on context menu of tree

### ISSUE THREAD

**Issue by AndreyMyagkov** [modxcms/evolution#1248]
If the resource has a very long title, it is not visible the ID of the resource. I want to duplicate ID in context menu. Screen https://yadi.sk/i/xOAODhUF3Dx8eY

Please modify line №104  into file \manager\frames\nodes.functions.inc.php
to
$alt = 'id:'.$id.'[+lf+]';

**Comment by modxuser** [comment]
Would it not be better to simply add it to the information block - as seen in the attached image

![details](https://cloud.githubusercontent.com/assets/1859868/22881874/c366c71e-f1e8-11e6-9f5d-e96b8c6f2de3.jpg)

Set the ID as the first element - before "Menu title:"

**Comment by AndreyMyagkov** [comment]
modxuser, see my screen 
![2017-02-12_23-24-25](https://cloud.githubusercontent.com/assets/12766797/22882067/33e3c6a0-f20b-11e6-8222-f57565d518bd.png)

**Comment by fourroses666** [comment]
My thoughts would be;

Just add ... for long titles. When hover show full title. 
I really don't need all that other information.
`My long menutitle goes he... (5)`

**Comment by modxuser** [comment]
Ah, sorry, didnt realise that was the information block - my BAD

**Comment by dmi3yy** [comment]
fixed
