### ISSUE TITLE
sitemap.xml displays nothing

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#1253]
I'm having an issue after upgrading to 1.2 where my [sitemap](http://www.fairview-condo.com/sitemap.xml) displays nothing.  I'm using the following snippet call
`[!sitemap? &format=`sp` &excludeTemplates=`blank` &priority=`priority` &changefreq=`changefreq`!]`

with a (blank) template and settings as follows:  https://cl.ly/2s0g2f280R2m

incidentally if I change the file to .html extension it works fine.

**Comment by Tourist4Life** [comment]
here is the sitemap snippet code:

`<?php
/*
==================================================
	sitemap
==================================================

Outputs a machine readable site map for search
engines and robots. Supports the following
formats:

- Sitemap Protocol used by Google Sitemaps
  (http://www.google.com/webmasters/sitemaps/)

- URL list in text format
  (e.g. Yahoo! submission)

Author: Grzegorz Adamiak [grad]
Version: 1.0.8 @ 22-AUG-2008
License: LGPL
MODx: 0.9.2.1, 0.9.6.1

History:
# 1.0.8
- excludeTemplates can now also be specified as a template ID instead of template name. 
  Useful if you change the names of your templates frequently. (ncrossland)
  e.g. &excludeTemplates=`myTemplateName,3,4`
# 1.0.7
- Unpublished and deleted documents were showing up in the sitemap. Even though they could not be viewed, 
  they were showing up as broken links to search engines. (ncrossland)
# 1.0.6
- Add optional parameter (excludeWeblinks) to exclude weblinks from the sitemap, since they often point to external
  sites (which don't belong on your sitemap), or redirecting to other internal pages (which are already
  in the sitemap). Google Webmaster Tools generates warnings for excessive redirects.	
  Default is false - e.g. default behaviour remains unchanged. (ncrossland)
# 1.0.5
- Modification about non searchable documents, as suggested by forum user JayBee
  (http://modxcms.com/forums/index.php/topic,5754.msg99895.html#msg99895)
# 1.0.4 (By Bert Catsburg, bert@catsburg.com)
- Added display option 'ulli'. 
  An <ul><li> list of all published documents.
# 1.0.3
- Added ability to specify the XSL URL - you don't always need one and it 
  seems to create a lot of support confusion!
  It is now a parameter (&xsl=``) which can take either an alias or a doc ID (ncrossland)
- Modifications suggested by forum users Grad and Picachu incorporated
  (http://modxcms.com/forums/index.php/topic,5754.60.html)
# 1.0.2
- Reworked fetching of template variable value to
  get INHERITED value.
# 1.0.1
- Reworked fetching of template variable value,
  now it gets computed value instead of nominal;
  however, still not the inherited value.
# 1.0
- First public release.

TODO:
- provide output for ROR
--------------------------------------------------
*/

/* Parameters
----------------------------------------------- */

# $startid [ int ]
# Id of the 'root' document from which the sitemap
# starts.
# Default: 0

$startid = (isset($startid)) ? $startid : 0;

# $format [ sp | txt | ror ]
# Which format of sitemap to use:
# - sp <- Sitemap Protocol used by Google
# - txt <- text file with list of URLs
# TODO - ror <- Resource Of Resources
# Default: sp

$format = (isset($format) && ($format != 'ror')) ? $format : 'sp';

# $priority [ str ]
# Name of TV which sets the relative priority of
# the document. If there is no such TV, this
# parameter will not be used.
# Default: sitemap_priority

$priority = (isset($priority)) ? $priority : 'sitemap_priority';

# $changefreq [ str ]
# Name of TV which sets the change frequency. If
# there is no such TV this parameter will not be
# used.
# Default: sitemap_changefreq

$changefreq = (isset($changefreq)) ? $changefreq : 'sitemap_changefreq';

# $excludeTemplates [ str ]
# Documents based on which templates should not be
# included in the sitemap. Comma separated list
# with names of templates.
# Default: empty

$excludeTemplates = (isset($excludeTemplates)) ? $excludeTemplates : array();

# $excludeTV [ str ]
# Name of TV (boolean type) which sets document
# exclusion form sitemap. If there is no such TV
# this parameter will not be used.
# Default: 'sitemap_exclude'

$excludeTV = (isset($excludeTV)) ? $excludeTV : 'sitemap_exclude';

# $xsl [ str ] 
# URL to the XSL style sheet
# or
# $xsl [ int ]
# doc ID of the XSL style sheet

$xsl = (isset($xsl)) ? $xsl : '';
if (is_numeric($xsl)) { $xsl = $modx->makeUrl($xsl); }


# $excludeWeblinks [ bool ]
# Should weblinks be excluded?
# You may not want to include links to external sites in your sitemap,
# and Google gives warnings about multiple redirects to pages 
# within your site.
# Default: false
$excludeWeblinks = (isset($excludeWeblinks)) ? $excludeWeblinks : true;


/* End parameters
----------------------------------------------- */

# get list of documents
# ---------------------------------------------
$docs = getDocs($modx,$startid,$priority,$changefreq,$excludeTV);


# filter out documents by template or TV
# ---------------------------------------------
// get all templates
$select = $modx->db->select("id, templatename", $modx->getFullTableName('site_templates'));
while ($query = $modx->db->getRow($select)) {
	$allTemplates[$query['id']] = $query['templatename'];
}

$remainingTemplates = $allTemplates;

// get templates to exclude, and remove them from the all templates list
if (!empty ($excludeTemplates)) {
	
	$excludeTemplates = explode(",", $excludeTemplates);	
	
	// Loop through each template we want to exclude
	foreach ($excludeTemplates as $template) {
		$template = trim($template);
		
		// If it's numeric, assume it's an ID, and remove directly from the $allTemplates array
		if (is_numeric($template) && isset($remainingTemplates[$template])) {
			unset($remainingTemplates[$template]);
		} else if (trim($template) && in_array($template, $remainingTemplates)) { // If it's text, and not empty, assume it's a template name
			unset($remainingTemplates[array_search($template, $remainingTemplates)]);			
		}
	} // end foreach
}

$output= array();
// filter out documents which shouldn't be included
foreach ($docs as $doc)
{
	if (isset($remainingTemplates[$doc['template']]) && !$doc[$excludeTV] && $doc['published'] && $doc['template']!=0 && $doc['searchable']) {
		if (!$excludeWeblinks || ($excludeWeblinks && $doc['type'] != 'reference')) {
			$output[] = $doc;		
		}
	}
}
$docs = $output;
unset ($output, $allTemplates, $excludeTemplates);


# build sitemap in specified format
# ---------------------------------------------

switch ($format)
{
	// Next case added in version 1.0.4
	case 'ulli': // UL List
		$output .= "<ul class=\"sitemap\">\n";
		// TODO: Sort the array on Menu Index
		// TODO: Make a nested ul-li based on the levels in the document tree.
		foreach ($docs as $doc)
		{
			$s  = "  <li class=\"sitemap\">";
			$s .= "<a href=\"[(site_url)][~" . $doc['id'] . "~]\" class=\"sitemap\">" . $doc['pagetitle'] . "</a>";
			$s .= "</li>\n";
			$output .= $s;
		} // end foreach
		$output .= "</ul>\n";
		break;
		
	case 'txt': // plain text list of URLs

		foreach ($docs as $doc)
		{
			$url = '[(site_url)][~'.$doc['id'].'~]';

			$output .= $url."\n";
		} // end foreach
		break;

	case 'ror': // TODO
	default: // Sitemap Protocol

	
	$output = '<?xml version="1.0" encoding="UTF-8"?>'."\n";
	if ($xsl != '') {
		$output .='<?xml-stylesheet type="text/xsl" href="'.$xsl.'"?>'."\n";
	}
	$output .='<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'."\n";
	
	
	foreach ($docs as $doc)	{
		$url = '[(site_url)][~'.$doc['id'].'~]';
		$date = $doc['editedon'];
		$date = date("Y-m-d", $date);
		$docPriority = ($doc[$priority]) ? $doc[$priority] : 0; // false if TV doesn't exist
		$docChangefreq = ($doc[$changefreq]) ? $doc[$changefreq] : 0; // false if TV doesn't exist

		$output .= "\t".'<url>'."\n";
		$output .= "\t\t".'<loc>'.$url.'</loc>'."\n";
		$output .= "\t\t".'<lastmod>'.$date.'</lastmod>'."\n";
		$output .= ($docPriority) ? ("\t\t".'<priority>'.$docPriority.'</priority>'."\n") : ''; // don't output anything if TV doesn't exist
		$output .= ($docChangefreq) ? ("\t\t".'<changefreq>'.$docChangefreq.'</changefreq>'."\n") : ''; // don't output anything if TV doesn't exist
		$output .= "\t".'</url>'."\n";
	} // end foreach
	$output .= '</urlset>';

} // end switch

return $output;

# functions
# ---------------------------------------------

# gets (inherited) value of template variable
function getTV($modx,$docid,$doctv)
{
/* apparently in 0.9.2.1 the getTemplateVarOutput function doesn't work as expected and doesn't return INHERITED value; this is probably to be fixed for next release; see http://modxcms.com/bugs/task/464
	$output = $modx->getTemplateVarOutput($tv,$docid);
	return $output[$tv];
*/
	
	while ($pid = $modx->getDocument($docid,'parent'))
	{
		$tv = $modx->getTemplateVar($doctv,'*',$docid);
		if (($tv['value'] && substr($tv['value'],0,8) != '@INHERIT') or !$tv['value']) // tv default value is overriden (including empty)
		{
			$output = $tv['value'];
			break;
		}
		else // there is no parent with default value overriden 
		{
			$output = trim(substr($tv['value'],8));
		}
		$docid = $pid['parent']; // move up one document in document tree
	} // end while
	
	return $output;
}

# gets list of published documents with properties
function getDocs($modx,$startid,$priority,$changefreq,$excludeTV)
{
	// get children documents
	$docs = $modx->getActiveChildren($startid,'menuindex','asc','id,editedon,template,published,searchable,pagetitle,type'); 
	// add sub-children to the list
	foreach ($docs as $key => $doc)
	{
		$id = $doc['id'];
		$docs[$key][$priority] = getTV($modx,$id,$priority); // add priority property
		$docs[$key][$changefreq] = getTV($modx,$id,$changefreq); // add changefreq property
		$docs[$key][$excludeTV] = getTV($modx,$id,$excludeTV); // add excludeTV property
		
		if ($modx->getActiveChildren($id))
			$docs = array_merge($docs, getDocs($modx,$id,$priority,$changefreq,$excludeTV));
	} // end foreach
	return $docs;
}
`

**Comment by fourroses666** [comment]
Can't help with the snippet but maybe you can try it with Ditto.
This is how I make sitemap.xml: (for YAMS have an other one)

Blank page sitemap.xml
In content (no richtext editor) place: {{sitemap-xml}}

Chunk sitemap_xml
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
[[Ditto? 
&id=`xmlsitemap` 
&startID=`0` 
&depth=`0` 
&showPublishedOnly=`1` 
&showInMenuOnly=`0` 
&tpl=`sitemap-xml-row` 
&tplFirst=`sitemap-xml-row-first`
&dateSource=`editedon` 
&dateFormat=`%Y-%m-%d` 
&orderBy=`id ASC, menuindex ASC, pagetitle ASC` 
&filter=`id,28,2`
]]
</urlset>
```
(filter removes id 28)

Chunk sitemap-xml-row
```
<url>
    <loc>[(site_url)][~[+id+]~]</loc>
    <lastmod>[+date+]</lastmod>
    <priority>0.5</priority>
    <changefreq>daily</changefreq>
</url>
```

Chunk (blank line on bottom): sitemap-xml-row-first
```
<url>
    <loc>[(site_url)]</loc>
    <lastmod>[+date+]</lastmod>
    <priority>1</priority>
    <changefreq>daily</changefreq>
</url>
```

**Comment by Tourist4Life** [comment]
Thanks @fourroses666.  I tried this and I'm still getting nothing.  I wonder if Ditto is not working properly?

**Comment by fourroses666** [comment]
Do you already have a sitemap.xml in the root on FTP?
If you rename the ditto version to .html you do see it?

**Comment by Tourist4Life** [comment]
If I rename it to sitemap.html it appears!

**Comment by Tourist4Life** [comment]
I don't see another sitemap.xml in the root.

**Comment by Tourist4Life** [comment]
I wonder if this is related to the website showing up as hacked in Google Searches - https://cl.ly/0Z3v0d1w3o1H

**Comment by Deesen** [comment]
Try setting Alias to "sitemap.xml" and Internet Media Type to "text/xml".

**Comment by fourroses666** [comment]
Hmm, it needs to show .xml when you are browsing to yoursite.com/sitemap.xml

maybe in your .htaccess there is a protection line ?
Did you selected on Page Setting: text/xml ?

**Comment by fourroses666** [comment]
Ah Deesen was faster. 
Have had a couple of sites with that hack too, allot of pages indexed unfortunately :(

**Comment by Tourist4Life** [comment]
@Deesen i did set the alias and media as above but i get nothing.  here is my .htaccess file:

# For full documentation and other suggested options, please see
# http://svn.modxcms.com/docs/display/MODx096/Friendly+URL+Solutions
# including for unexpected logouts in multi-server/cloud environments

# For security reasons, Option followsymlinks cannot be overridden.
#Options +FollowSymlinks
Options +SymLinksIfOwnerMatch
RewriteEngine On
RewriteBase /

# Fix Apache internal dummy connections from breaking [(site_url)] cache
RewriteCond %{HTTP_USER_AGENT} ^.*internal\ dummy\ connection.*$ [NC]
RewriteRule .* - [F,L]

# Rewrite domain.com -> www.domain.com -- used with SEO Strict URLs plugin
#RewriteCond %{HTTP_HOST} .
#RewriteCond %{HTTP_HOST} !^fairview-condo\.com [NC]
#RewriteRule (.*) http://fairview-condo.com/$1 [R=301,L]

RewriteCond %{HTTP_HOST} ^[0-9]+(\.[0-9]+){3} [OR]
RewriteCond %{HTTP_HOST} ^fairview-condo\.com
RewriteRule (.*) http://www.fairview-condo.com/$1 [R=301,L] 

# Exclude /assets and /manager directories from rewrite rules
RewriteRule ^(manager|assets|vieleRETS) - [L]

# For Friendly URLs
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?q=$1 [L,QSA,NC]

**Comment by fourroses666** [comment]
I'm seeing your sitemap.xml 
http://www.sitename.com/sitemap.xml

**Comment by Tourist4Life** [comment]
I manually created that from the sitemap.html.  It is not being generated by MODx.  I wanted to provide it to Google for rendering.

**Comment by fourroses666** [comment]
When renaming it to test.xml no output either? 
I have no other ideas left.

**Comment by Tourist4Life** [comment]
@fourroses666 that works!  i wonder if the hack is impacting the file sitemap.xml ?

**Comment by fourroses666** [comment]
Do you have an other page with sitemap.xml alias? I think there is a conflict.
Else you can add the different sitemap URL in Google webmastertool.

**Comment by Tourist4Life** [comment]
i don't get any errors when saving as sitemap.xml and I don't see a sitemap folder.

**Comment by Tourist4Life** [comment]
the other thing that is odd is that i can't get MODx to drop the .html extension (exp.  http://www.fairview-condo.com/site_map.xml.html)

**Comment by fourroses666** [comment]
It does work without http://www.fairview-condo.com/site_map.xml

You can remove .html at config page. You don't need it.
Add this in .htaccess:
```
Options +FollowSymLinks -MultiViews
DirectorySlash Off

RewriteCond %{SCRIPT_FILENAME}/ -d
RewriteCond %{SCRIPT_FILENAME}.html !-f
RewriteRule [^/]$ %{REQUEST_URI}/ [R=301,L]

RewriteCond %{ENV:REDIRECT_STATUS} ^$
RewriteRule ^(.+)\.html$ /$1 [R=301,L]

RewriteCond %{SCRIPT_FILENAME}.html -f
RewriteRule [^/]$ %{REQUEST_URI}.html [QSA,L]
```

Then it will redirect .html too non .html

**Comment by Tourist4Life** [comment]
Yes the url does work when you manually remove the .html..... but when I attempt to submit to Google for crawling it thinks it is an HTML page.  

When I preview the page from MODx is adds the .html extension to the file.  Why?

I've set the resource to be an xml file.

I tried removing all of the code from my .htaccess file and using the above as wall as just adding it on and it still seems that it cannot shake the .html.

**Comment by fourroses666** [comment]
Manager > tools > configuration > friendly urls > friendly url suffix 

There remove .html

**Comment by Tourist4Life** [comment]
If I remove .html in the config then it would impact SEO as all the URLS would change right?  Also, I have some pages outside of MODx on this site that point to URLs that have the .html in them (i know, i know the hardcoding is not good practice).

For the .htaccess are you saying that I should add in your code above?  If so where should it go?  Or are you saying I should replace my .htaccess file with this?

**Comment by Tourist4Life** [comment]
Is there an exception that I could add in the .htaccess just for the sitemap?  So it would not append the .html to it?

**Comment by fourroses666** [comment]
It doesn't adds the .html when removing the .html suffix does it?
Does it give an error when you test it on the webmaster tool?

I'm pritty sure you won't have SEO issues when it works when you type with .html and it redirects to without .html. The .html page still "exsists" (is reachable) but after a while the .html page will get replaced on the Google index by the non .html one.

It shouldn't loose its score/ranking.
You can test it after a while on google.
Search on Google site:mysitename.com and you see how many pages and what URLs are indexed.
After a while the .html will get removed from the indexed URL and won't loose its ranking.

I have done it for a couple of sites. 
I guess Google doesn't give you an answer on it but I trust this method.

Just make sure the .htaccess works, redirecting from with .html to without and still see the same page.

**Comment by modxuser** [comment]
In theory (and practice) you don't need a sitemap at all, so long your website is well structured and interlinked. You already have a normal on-site sitemap, so in reality, you don't need an XML sitemap.

If you are spamming by adding pages that aren't directly visible to the end-user but are in a sitemap.xml, then I would re-think that strategy - I am not saying you do, but that is a standard practice, or at least it used to be when I worked as an SEO.

**Possible solution**

If your sitemap page has an alias of ".xml" and you have the suffix set to ".html" you can re-direct the result, as you will have "name.xml.html"

I just tested and I can reach your file via: "yourdomain.com/sitemap.xml.html" and "yourdomain.com/sitemap.xml"

301 re-direct the ".xml.html" to ".xml", example:

    RewriteRule sitemap.xml.html http://www.yourdomain.com/sitemap.xml [R=301,L]

I've experienced something similar in the past, but now no-longer use a suffix.

**Important:**
Do not create a static file with the same name in the same place as the dynamic sitemap - that won't work

**Comment by dmi3yy** [comment]
For .xml no need delete sufix .html 

Need ad alias like sitemap.xml

Its work for 
Css js txt xml ;) 


Отправлено с iPhone

**Comment by nick0** [comment]
Not sure if this matters, but I always use the (blank) template for sitemap.xml (which I create with Ditto like Marc above) and manually paste 
sitemap.xml 
as the alias

**Comment by dmi3yy** [comment]
I use sitemap from extras.  Need only install 
Auto creat snippet tv and doc ;)

Отправлено с iPhone

**Comment by Tourist4Life** [comment]
Thanks All!!!  I

**Comment by fourroses666** [comment]
@dmi3yy That sitemap only adds a TV, russian text converted to ?????  and no snippet and no doc.

**Comment by dmi3yy** [comment]
???  Need db utf8-general_ci

Отправлено с iPhone

**Comment by modxuser** [comment]
@Tourist4Life

Out of interest, which solution have you used, as I can still see your sitemap using:

1. yourdomain.com/sitemap.xml
2. yourdomain.com/sitemap.xml.html

And your HTML sitemap (thesitemap.html) still has the ".xml.html" URL in it, which Google will follow / find and index

**Comment by Tourist4Life** [comment]
I ended up using @fourroses666 's suggestion above.  I think my hacked index.php file in the root may have been preventing the sitemap from working properly.

**Comment by modxuser** [comment]
Ah, ok

Tip: I would still suggest you re-direct ".xml.html" to ".xml"

**Comment by Tourist4Life** [comment]
310 redirect?

**Comment by modxuser** [comment]
As seen here https://github.com/modxcms/evolution/issues/1253#issuecomment-280493811
