### ISSUE TITLE
auto logout from admin panel

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#1256]
1.2.1 
i see the problem when you turn on the access rights - throws from the admin area. Randomly. Log in again, and: ![screenshot-rozmovlai kiev ua-2017-02-20-22-31-13](https://cloud.githubusercontent.com/assets/8958344/23140848/854536d0-f7bc-11e6-98c1-30674c90accd.jpg)

session limit - 15 min

**Comment by Fr3ddy7** [comment]
the problem came when added active users :)

**Comment by Deesen** [comment]
What do you mean by "turn on access rights"?

**Comment by Fr3ddy7** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/8958344/23164893/24d3b098-f842-11e6-9da3-8c947e873580.jpg)

managers and used to say that "flies out the admin panel", is now seen :)

**Comment by morionsoft** [comment]
Да, такая проблема действительно есть ... когда менеджер заходит в админку через некоторое время происходит autologoff

**Comment by Deesen** [comment]
I would like to solve but I cannot recreate that issue. I turned off/on access permissions 10x, left the config-page open for some time etc.. No auto-logoff here?

**Comment by morionsoft** [comment]
версия в которой возникла проблема Dmi3yy – MODX Evolution 1.2.1-d9.1.0, в данный момент пока немогу отловить момент на котором возникает autologoff

**Comment by Fr3ddy7** [comment]
@dmi3yy wrote that the problem with the test mailbox, with increasing test interval - part of the problem disappears :)
