### ISSUE TITLE
after fresh install - empty settings fields 

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1261]
http://take.ms/XcFc5

**Comment by M-xm** [comment]
Yes! "Site down, site down!". $base_url is empty, rm_site_url is empty!
Fix it now, please!

**Comment by Grinyaha** [comment]
Это когда такой баг возникает?

**Comment by M-xm** [comment]
после обновления на версию 1.2.2. В Конфигурация пропали поля с указанием путей (это то что сразу бросается в глаза). Ну и соответственно перестал работать сайт - ошибки выше. Лечится переопределением переменных смотрящих на $base_url или $rm_site_url на $_SERVER['DOCUMENT_ROOT']

**Comment by dmi3yy** [comment]
only affected on MODX.EVO.CUSTOM and now Fixed
