### ISSUE TITLE
multiple calls of PHx don't work in 1.2.1

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#1263]
Seems that one PHx call is fine but if I put more than one in a TPL the second doesn't work.  I'd love to use something besides phx to check to see if an TV is empty or not in Evo but I'm not sure anything else exists?

**Comment by Tourist4Life** [comment]
I found this code:

`[*Photo2:is=``:else=``*]`

which works....but still a bit concerned that multiple instances of PHx on one page fail.

**Comment by nick0** [comment]
This doesn't solve the multiple phx call issue you have found but as a workaround you could try using the IF snippet for the second call. 

Something like this, just fill in the blanks...
```[[if? &is=`[*Photo2*]:empty` &then=`` &else=`CHANGETHIS`]]```

Or if not empty...
```[[if? &is=`[*Photo2*]:!empty` &then=`CHANGETHIS`]]```

**Comment by MrSwed** [comment]
in different situations needs different call phx, for example it may be
```[*Photo2:is=``:else=``*]```
for ditto chunk:
```[+Photo2:is=``:else=``+]```
and most reliable:
```
[*phx:input=`[*Photo2*]`:is=``:else=``*]
[+phx:input=`[*Photo2*]`:is=``:else=``+]
```

please, give yours full code of using multi phx, 

PS. [example usage](https://github.com/MrSwed/modx-1.x-swed/blob/beta/assets/element/chunk/Template/CONTENT.tpl)

**Comment by Tourist4Life** [comment]
Here is the code that I'm using that works (without two instances of PHx):

`ul class="amenities">
								[+phx:if=`[*propertytype*]`:is=`Land`:then=`<li><i class="icon-land"></i> Land / Lot</li>`:else=`[+phx:if=`[*propertytype*]`:is=`Residential`:then=`<li><i class="icon-house"></i> Residential</li>`:else=`<li><i class="icon-apartment"></i> Apartment / Condo / Townhome</li>`+]
								`+]
								
								<li><i class="icon-area"></i> [*listing_floor_area*] Sq Ft</li>
								<li><i class="icon-bedrooms"></i> [*listing_bedrooms*]</li>
								<li><i class="icon-bathrooms"></i> [*listing_bathrooms*]</li>
							</ul>
							
							<div id="property-id">MLS: #[*listing_mls*]</div>
						</div>

						
						<div id="property-detail-wrapper" class="style1">
							
							<div class="price">
								<i class="fa fa-home"></i>For Sale
								<span>$[*listing_price*]</span>
							</div>
									
							
							<div id="property-detail-large" class="owl-carousel">
								
								[*Photo1:is=``:else=`
								<div class="item">
									<img src="[*Photo1*]" alt="Photo1:  [*pagetitle*] for sale in [*neighborhood*]" />
								</div>`*]
								`

If I replace the `[*Photo1:is=``:else=`` with phx it fails.

**Comment by MrSwed** [comment]
try
```
[+phx:if=`[*Photo1*]`:is=``:else=`
								<div class="item">
									<img src="[*Photo1*]" alt="Photo1:  [*pagetitle*] for sale in [*neighborhood*]" />
								</div>`+]
```
or  (ifnotempty  or isnotempty)
```
[+phx:if=`[*Photo1*]`:ifnotempty=`
								<div class="item">
									<img src="[*Photo1*]" alt="Photo1:  [*pagetitle*] for sale in [*neighborhood*]" />
								</div>`+]
```
