### ISSUE TITLE
new modifers - is there a word limit parameter?

### ISSUE THREAD

**Issue by nick0** [modxcms/evolution#1264]
Hello,
With the new modifiers, is there a "word limit" (eg 25 words) parameter to use in a ditto row template?
If so, how do I use it with the content variable?
```[+content:word_limit=`25`+]??```
Thanks

**Comment by modxuser** [comment]
I am not sure, but [give this a try](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fmblo.info%2Fmatome%2Fmodifiers%2Fstring_modifiers%2F&edit-text=)

`[*content: summary (300)*]`

Where 300 is the limit, if I am right, it strips the HTML itself

**Comment by nick0** [comment]
Thanks for the help.
That one didn't work. I got empty output with + or with*
Thanks for the link - I also tried this without success:
`[+content:Count_words(30)+]`
Maybe I have got the syntax wrong?

**Comment by modxuser** [comment]
Strange - that should work - do you have modifiersactivated in the config ?

If yes, then @yama will have to take a look, the code is there https://github.com/modxcms-jp/evolution-jp/blob/develop/manager/includes/extenders/ex_modifiers.php#L521

**Comment by nick0** [comment]
Yes. Modifiers are activated (Enable Filters is yes) in the config and the PHx plugin has been deleted.

I can see the code in the links you sent but I don't know what to do with it.

Some comprehensive documentation on the modifiers listing all parameters, example usage etc would be handy. There are probably lots of little tricks that could be done with the modifiers but without examples its hard to know.

This is the call that worked for me in PHx - I am also wanting to strip all html tags...
```[+content:word_limit=`25`:striptags+]```

This is the replacement call I am currently trying without success in the new modifiers...
```[+content:Count_words(30)+] ```

The full call in the ditto row template is like so...
```[+content:isnot=``:then=`<p>[+content:Count_words(30)+] <span class="more"><a href="[~[+id+]~]" title="read more">more</a></span></p>`+]```

Thanks for your help @modxuser.

I will wait for @yama.

**Comment by Deesen** [comment]
There is also a snippet, maybe it helps for the time being https://github.com/AgelxNash/DocLister/tree/master/assets/snippets/summary .

Or maybe just disable modifiers and use latest PHX ?

**Comment by nick0** [comment]
Thanks @Deesen. That is good to know re the summary snippet. I would use that as a last resort but keen to see if the new modifiers can do it natively.

It works fine me in PHx and has for many years. I am just wanting to know how to do it with the new modifiers. This makes me want to stick with PHx :) PHx is a proven performer but I am trying out the modifiers. Hopefully it can be done so its easy to update in existing ditto row templates. 

The problem with the doc parser issue and the new modifiers and PHx is that the combinations seem to work for me in some scenarios and not in others (like in that demo site you looked at for me where the Modifiers had to be used instead of PHX). 

Cheers again.

**Comment by modxuser** [comment]
@yama any chance of you looking at this problem please ?

I am also trying to convert tags from "IF", but if the built-in modifiers don't work properly I see no point in having them in the system, at least, not until they work properly

The discussion about PHx, IF and Built-In modifiers would also be resolved, at least until the built-in modifiers are 100% compatible
