### ISSUE TITLE
Bug in 1.2.1-9.1.1

### ISSUE THREAD

**Issue by F1fanatik** [modxcms/evolution#1265]
После обновления на 9.1.1
updateNotify - предлагает установить прошлую версию...
[http://images.vfl.ru/ii/1488437136/39d39022/16294808.jpg](http://images.vfl.ru/ii/1488437136/39d39022/16294808.jpg)
И еще... не удобно, что описание элемента стало ссылкой...
[http://images.vfl.ru/ii/1488437998/8e0b851f/16294942.jpg](http://images.vfl.ru/ii/1488437998/8e0b851f/16294942.jpg)

На одном обновленном сайте настройки элементов(с одной страницы) сразу ставятся во все вкладки, а на другом каждую вкладку пришлось настраивать..

**Comment by dmi3yy** [comment]
поправил это я метку не поставил :) на гитхабе
