### ISSUE TITLE
 Information: Multiple active user sessions (total 2) found for user

### ISSUE THREAD

**Issue by oclanis** [modxcms/evolution#1266]
Hi folks,

installed the latest evo release. Is there a solution for blocked resources while Editing? Whenever i try to edit a Resource it says it's blocked from the user with that i'am currently logged in.

When i try to unblock the Resource, it works until i change the Template.

**Comment by bossloper** [comment]
First, just checking... besides copying all files you ran the install without error and saved Tools-> Configuration?

**Comment by oclanis** [comment]
Hi Bossloper,

yes the installation ran without any error, and the config.inc.php has been written to manager/includes

**Comment by bossloper** [comment]
Are you logged with the same account in two different browsers? Or are you sharing the account with others? If so then this is correct expected behaviour.

**Comment by oclanis** [comment]
No not that i know, i have just one account on my Computer with the latest Firefox and a one and only running instance of modx at a time. I tried the same with another Browser (IE) with the same issue, if i change the Template i get the same message, that the resource is locked by myself :D

**Comment by oclanis** [comment]
May the PHP-Version be to old? Got 5.3.8 on my Server?

**Comment by bossloper** [comment]
I guess it is possible, but you would likely see some errors in your php error_log and presume there is nothing showing in the modx system events either?

Just trying to fully understand "When i try to unblock the Resource, it works until i change the Template".
Can you edit a resource and change anything else, or is it just changing a template for a resource that gives the problem?

**Comment by oclanis** [comment]
Yes, i can edit and save all other things within a resource, except the template. When i change the template, the page within the frame reloads and the "locked" message appears.

**Comment by oclanis** [comment]
Parser - header('Content-Type: ' . $ty - Systemereignisse
Fehler

Ereignis-ID: 	0 	Quelle: 	Parser - header('Content-Type: ' . $ty
 
Datum: 	02-03-2017 11:20:51 	Benutzer: 	
 

Trying to get property of non-object
« MODX Parse Error »
Error : Cannot modify header information - headers already sent by (output started at /home/htdocs/maineo/!_SUB/abnahme/index.php:2)
Error information 	
ErrorType[num] 	WARNING[2]
File 	/home/htdocs/maineo/!_SUB/abnahme/manager/includes/document.parser.class.inc.php
Line 	700
Source 	header('Content-Type: ' . $type . '; charset=' . $this->config['modx_charset']);

Basic info 	
REQUEST_URI 	xxx
Resource 	[1] Startseite
Referer 	
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
IP 	93.212.108.234
Current time 	2017-03-02 11:20:51

Benchmarks 	
MySQL 	0.0178 s (6 Requests)
PHP 	0.0591 s
Total 	0.0769 s
Memory 	1.5373764038086 mb

Backtrace
DocumentParser->executeParser()
index.php on line 129
DocumentParser->prepareResponse()
manager/includes/document.parser.class.inc.php on line 2141
DocumentParser->outputContent()
manager/includes/document.parser.class.inc.php on line 2234
header(string $var1)
manager/includes/document.parser.class.inc.php on line 700

**Comment by oclanis** [comment]
Now i found this in the modx system events?

**Comment by bossloper** [comment]
Maybe try clearing browser cache?

**Comment by oclanis** [comment]
No, no chance, same thing. I'am going to revert to an older version of MODx, seems 1.21 needs to get some things fixed first

**Comment by bossloper** [comment]
OK, though it works fine for me.

**Comment by oclanis** [comment]
Ok so, i'am going to reinstall it at first, maybe it went something wrong, who knows :D

**Comment by oclanis** [comment]
Ok this is new, the problem seems fixed. All i did is to delete all session flatfiles in /var/lib/php5 and i set full permissions to this folder, restartet the webserver and it works like a charm.

**Comment by bossloper** [comment]
glad you got it sorted, hard to know exactly what was going on though! ... and don't forget to close this issue ;-)

**Comment by oclanis** [comment]
Yea, still testing with 1.21 but until now it is working.
