### ISSUE TITLE
Evo 1.2 with TinyMCE4 - Insert Link with "Search in MODX" doesn't work

### ISSUE THREAD

**Issue by webkarli** [modxcms/evolution#1268]
When I try to insert a Link with "Search in MODX", it doesn't work. No list in "Search in MODX".

**Comment by bossloper** [comment]
Maybe upgrade to 1.2.1 first?

**Comment by webkarli** [comment]
I did, it is the same.

**Comment by bossloper** [comment]
It is working for me. Have you tried clearing the browser cache and maybe check for any JavaScript errors?

**Comment by webkarli** [comment]
browser cache is cleared, no JavaScript error in console. 
When I change to TinyMCE its work. For me is it not a problem, but for other editors, when I update to 1.2.1 on the liveserver.
My configuration:
I test allways on XAMPP
MODX-Version 	  	1.2.1
PHP Version 	  	5.5.9
Zugriffsberechtigung 	  	Aktiviert
Datenbank-Name 	  	
Datenbank-Server 	  	127.0.0.1
Datenbank-Version 	  	5.6.16
Datenbank-Zeichensatz 	  	latin1
Datenbank-Kollations-Zeichensatz 	  	latin1_swedish_ci

**Comment by Deesen** [comment]
Please check the console as follows, then you will get a notice for each server-request giving you a status 200 (OK) or 404 (error) like seen in the last line of my screenshot. If 404, you can check if the path exists. Maybe you are using MODX inside a subdirectory like http://localhost/modx/index.php?

![insert](https://cloud.githubusercontent.com/assets/8569221/23538410/37d8831a-ffd3-11e6-8e05-9872ae12882e.png)

**Comment by webkarli** [comment]
It works. I had expected the old way of working. In the older versions, a list was opened. Now I have to enter a few letters for the search. Sorry, I did not know.

**Comment by Deesen** [comment]
You should also be able to directly choose a resource from the resource-tree instead of needing to type letters first.

**Comment by webkarli** [comment]
Wow. It works also.

**Comment by modxuser** [comment]
@webkarli is your problem now resolved, if yes, please close the issue

If you aren't sure on how to close the issue, please take a look here => https://github.com/modxcms/evolution/issues/1213#issue-202373111
