### ISSUE TITLE
Evo 1.2.1 – Doc Finder and Quickmanager

### ISSUE THREAD

**Issue by katja7** [modxcms/evolution#1269]
Hi!

I updated Modx from 1.0.15 to 1.2.1 and have some troubles now:

- Doc Finder 1.7 doesn’t recognize AND, OR, NOT in the search query. Using those I’m getting no results. I got this problem both in the updated version and in a fresh Modx-1.2.1 install on another server.

- QuickManager: One part of the website is visible to logged in web users only. In this part administrators can create and edit resources via Quickmanager. Editing works fine. But when I create a new resource and click the save button I’m getting a 404 error.

Can anybody help?

**Comment by Fr3ddy7** [comment]
Doc Finder 1.7 - sorting does not work in the search results

![screenshot_1](https://cloud.githubusercontent.com/assets/8958344/23557041/505e4e1a-0037-11e7-8448-63ab74cf753c.jpg)
