### ISSUE TITLE
OnLoadDocumentObject event dont work

### ISSUE THREAD

**Issue by webber12** [modxcms/evolution#1271]
```
$out = $documentObject;
print_r($out); //that`s right array
$e->output($out); // and then that`s an empty array
```

**Comment by Pathologic** [comment]
Change the event call to:
```
$out = $this->invokeEvent('OnLoadDocumentObject', compact('method', 'identifier', 'documentObject'));
if(is_array($out) && is_array($out[0])){
    $documentObject = $out[0];
}
```

**Comment by webber12** [comment]
Так я пробовал с самого начала - error, it`s not an array - т.е. сам плагин возвращает непонятно в каком виде результат. Причем, при включении плагина на это событие падает любая страница (просто белая, без всяких ошибок), независимо от того, возвращал ли плагин на этом событии что-то или нет. Т.е. 

```
if ($modx->documentIdentifier == '10') {
    $e->output($out);
}
```

убивает не только страницу с id=10, но и вообще любую. Т.е. проблема связана с самим некорректным срабатыванием этого события.

**Comment by webber12** [comment]
```
$out = $this->invokeEvent('OnLoadDocumentObject', compact('method', 'identifier', 'documentObject'));
print_r($out);
```

Выдает в итоге Array([0] => Array) , вот в чем проблема у меня. Хотя $e->output($out); и непустой $out   в виде массива туда из плагина отдаются.

**Comment by Pathologic** [comment]
```
$modx->event->_output = $documentObject;
```

**Comment by webber12** [comment]
Непонятно, почему стандартный возврат $out[0] не работает в случае с этим событием

**Comment by webber12** [comment]
Все равно белая страница, причем любая.

Для теста делаю так - пытаюсь подменить для id=10 шаблон на шаблон главной (id=3). В итоге все три события пишутся нормально в лог, а на выходе белая страница (любая страница сайта). Вырубаю плагин - все работает, весь сайт (ну кроме этого функционала, конечно).

```
$e = & $modx->Event;
switch($e->name) {
	case 'OnLoadDocumentObject':
	if ($modx->documentIdentifier == '10') {
		$modx->logEvent('1', '1', $modx->documentIdentifier, 'ok1');
		$out = $documentObject;
		$modx->logEvent('1', '1', $out['template'], 'ok2');
		$out['template'] = '3';
		$modx->logEvent('1', '1', $out['template'], 'ok3');
		$modx->event->_output = $out;
	}
	break;
	
	default:
	break;
}
```

**Comment by Pathologic** [comment]
Стандартный возврат через output() только со строками возможен. C моей правкой работает твой плагин.

**Comment by webber12** [comment]
Странно, у меня на версии 1.2.1.9.1.0 не работает то, что я выше написал..

**Comment by Pathologic** [comment]
https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L1977-L1979  - вот это поменяй на:
```
$out = $this->invokeEvent('OnLoadDocumentObject', compact('method', 'identifier', 'documentObject'));
if(is_array($out) && is_array($out[0])){
    $documentObject = $out[0];
}
```

Тогда и будет работать.

**Comment by webber12** [comment]
Да, так то оно работает. 

Вопрос в том, зачем тогда эта свистопляска - если события не возвращают массивы, то надо напрямую с $modx->documentObject и оперировать, а не передавать его в $documentObject и обратно, который потом разваливается.

**Comment by dmi3yy** [comment]
Тут недавно Яма что то рефакторил еще 
https://github.com/modxcms/evolution/commit/0a244df3976c6b3beca5df08a4f05631f6e9cf99




От 8 марта 2017 г. в 20:56:32, webber12 (notifications@github.com) написал:

Да, так то оно работает.

Вопрос в том, зачем тогда эта свистопляска - если события не возвращают массивы, то надо напрямую с $modx->documentObject и оперировать, а не передавать его в $documentObject и обратно, который потом разваливается.

**Comment by Pathologic** [comment]
> Вопрос в том, зачем тогда эта свистопляска - если события не возвращают массивы, то надо напрямую с $modx->documentObject и оперировать, а не передавать его в $documentObject и обратно, который потом разваливается.

Наверное, сложилось исторически так :smile:

**Comment by dmi3yy** [comment]
Та да там много нюансов исторических

Но если по чуть чуть исправлять то рано или поздно будет все гуд ;) 
Главное что б при исправлении добавлялось меньше багов чем исправлялось ;)))) 

Отправлено с iPhone

**Comment by Grinyaha** [comment]
Нет ребята, не исторически так сложилось. В старых версиях все работало нормально. Потому зачем-то поменяли на вот то что имеем сейчас с белым экраном. Я тоже в себя на сайтах где использую это событие возвращаю так как было раньше, чтобы работало.

**Comment by dmi3yy** [comment]
Напишите что на что исправляете и где поправим в ядре 

просто когда каждый сам себе правит и не сообщает то и получаем что есть баг который не исправляется :( 

короче лучше 1 раз исправить в Ядре чем каждый раз у себя )

От 13 марта 2017 г. в 12:28:30, Alexander (notifications@github.com) написал:

Нет ребята, не исторически так сложилось. В старых версиях все работало нормально. Потому зачем-то поменяли на вот то что имеем сейчас с белым экраном. Я тоже в себя на сайтах где использую это событие возвращаю так как было раньше, чтобы работало.

**Comment by webber12** [comment]
Раньше это событие просто ничего не возвращало, да и внутрь ничего не передавалось.
```
$this->invokeEvent('OnLoadDocumentObject');
if ($documentObject['template']) {...}
```
Т.е. по идее можно было просто через global $documentObject; получить доступ, сделать что надо и все работало.

А теперь пытается вернуть массив, а из плагина вернуть можно только строку.

```
$out = $this->invokeEvent('OnLoadDocumentObject', compact('method', 'identifier', 'documentObject'));
if(is_array($out)){
    $documentObject = $out;
}
if ($documentObject['template']) {....}
```

**Comment by Grinyaha** [comment]
Я у себя вот так делаю, может не кошерно, но работает:

`if($isPrepareResponse==='prepareResponse') $this->documentObject = & $documentObject;
	$out = $this->invokeEvent('OnLoadDocumentObject', compact('method', 'identifier', 'documentObject'));
	/*if(is_array($out)){
		$documentObject = $out;
	}*/`
