### ISSUE TITLE
can't set (0) parent from sub page and user can create web page at root

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#1273]
Sub page can't set (0) parent again :
![download](https://cloud.githubusercontent.com/assets/9032715/23887088/eb10b262-08ad-11e7-84b2-94bb911f78b9.png)

Set Not Allow Users to create new Resources in the site root : 
![download 1](https://cloud.githubusercontent.com/assets/9032715/23887098/f029d120-08ad-11e7-9940-f985b0ce7baa.png)

But user can create :
![download 2](https://cloud.githubusercontent.com/assets/9032715/23887099/f43d5142-08ad-11e7-8c31-e76b8adc1e63.png)

**Comment by Deesen** [comment]
Regarding your first point, no problem for me using latest dev. Can you find any error in browser-console?

The other 2 issues were right, users with permission "edit_document" were automatically allowed to create or move documents in root -> https://github.com/modxcms/evolution/commit/796580e3955248b1606a4449cc426fcffeafde32#diff-ece6f0242c01db69806f83d31dab941dR26

Maybe you want to test it first? https://github.com/Deesen/evolution/blob/829808440166971228b952e70d56dede945ed99e/manager/processors/user_documents_permissions.class.php

**Comment by mgzawlinoo** [comment]
Hi,
My first problem is I can't re assign sub page to under root again :
Change Manager themes, Brower and still problem .
Second problem is now fix , thank you Deesen.
![download](https://cloud.githubusercontent.com/assets/9032715/23891585/86c5c91a-08c5-11e7-92c4-a1299dca61e4.png)

**Comment by Deesen** [comment]
Your screenshot reveals v1.2, I was using latest 1.2.2-beta.

**Comment by Deesen** [comment]
Is your first problem solved with 1.2.2 ?

**Comment by dmi3yy** [comment]
Fixed
