### ISSUE TITLE
tinyMCE by defauде lose h1-h1 p div 

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1275]
http://take.ms/2Gfmd

**Comment by Deesen** [comment]
I tried my best to add clean description for this parameter. I guess you need only "Custom Style Format Block". In latest dev the plugin-config should look like

![tinymce-plugindesc](https://cloud.githubusercontent.com/assets/8569221/23942858/e3518356-096d-11e7-9ec1-b3ab708b867d.png)

**Comment by dmi3yy** [comment]
yes but all this add class
and no have easy way ad tag h1 - h6  p


От 15 марта 2017 г. в 11:57:33, Deesen (notifications@github.com) написал:

I tried my best to add clean description for this parameter. I guess you
need only "Custom Style Format Block". In latest dev the plugin-config
should look like

[image: tinymce-plugindesc]
<https://cloud.githubusercontent.com/assets/8569221/23942858/e3518356-096d-11e7-9ec1-b3ab708b867d.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1275#issuecomment-286694285>,
or mute the thread

**Comment by bossloper** [comment]
h1-h6 tags are defined in a similar way to TinyMCE3
Go to Tools->Configuration->Interface & Features
At bottom of TinyMCE4 settings are 'Block Formats' - then make sure you have the blockselect as one of your toolbar buttons.

**Comment by Deesen** [comment]
Looks like

![tinymce-plugindesc2](https://cloud.githubusercontent.com/assets/8569221/23943671/85250390-0970-11e7-85f8-2684b9d57724.png)

and will turn into

![tinymce-plugindesc3](https://cloud.githubusercontent.com/assets/8569221/23943674/8930f43a-0970-11e7-8c90-297cb5a30267.png)

**Comment by Deesen** [comment]
In user-settings you can set checkbox "Use global configuration" or set custom blockformats for each user.

**Comment by bossloper** [comment]
... and if you are using the custom theme you need to make sure blockselect is one of the buttons.

**Comment by dmi3yy** [comment]
I found ) 

http://take.ms/S2tat

need add by default )

**Comment by bossloper** [comment]
you need blockselect for the custom 'Block Formats'

**Comment by dmi3yy** [comment]
now default settings ready for 90% managers )

**Comment by pmfx** [comment]
Agree, "formatselect" should be there by default. It is used most of the time.

**Comment by bossloper** [comment]
and blockselect?
