### ISSUE TITLE
Error in document.parser.class.inc.php, no output

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#1276]
after update to last develop (2710f2d22d8226cf20f0ba2f6ad65b76daf83317) 

that:
```
[*isfolder:is=`1`:then=`
<div class="portfolio[*id:is=`14`:then=`_cat`*] items">
 [!Ditto?  
// skiped
 !]
{{paginator}}
 </div> <!-- /items -->
 <div class="endcol"></div>
`*]
```
output nothing!

It has been established by experience that the problem in document.parser.class.inc.php
after revert it to 26f32bfc90b68ea91e9b14d1a53a02c4d5d87524 it work normaly

PHX used, internal filters disabled

**Comment by MrSwed** [comment]
also
```
[*pub_date:ne=`0`:then=`[*pub_date*]`:else=`[*publishedon*]`*]
```
now not working

**Comment by dmi3yy** [comment]
now we are tell about remove phx from core ) 
better use IF snippet ) 
or install phx plugin )

**Comment by MrSwed** [comment]
that is bad propouse.
with phx slightly more complicated query, like
```
[+phx:input=`[*isfolder*]`:ne=`1`:and:if=`[[getInheritField? &id=`[*id*]` &field=`showDateInContent`]]`:is=`1`:then=`<div class="date">[*phx:input=`[*pub_date:ne=`0`:then=`[*pub_date*]`:else=`[*publishedon*]`*]`:dateformat=`%d.%m.%Y`*]</div>`+]
```
give 01.01.1970
i.e. 
``` [*phx:input=`[*pub_date:ne=`0`:then=`[*pub_date*]`:else=`[*publishedon*]`*]`*] ```
gets empty..

I think need revert document.parser.class.inc.php or more carefully check the changes...

**Comment by MrSwed** [comment]
founded. 
These changes cause a problem 12c67aad38636705234439fbb3cda7512f4fb475

**Comment by yama** [comment]
```
[*isfolder:is=`1`:then=`
<div class="portfolio[*id:is=`14`:then=`_cat`*] items">
 [!Ditto?  
// skiped
 !]
{{paginator}}
 </div> <!-- /items -->
 <div class="endcol"></div>
`*]
```
```
[*phx:input=`[*pub_date:ne=`0`:then=`[*pub_date*]`:else=`[*publishedon*]`*]`*]
```
Maybe, these are nested quotes problem. I think PHx does not matter.
I'll fix these issue next month.

**Comment by MrSwed** [comment]
@yama No. 
This has been working for several years and I could not upgrade to version 1.2.2 until I rolled back the changes cdd7d8b
