### ISSUE TITLE
Maybe 2 Bugs Found Version 1.2 and 1.2.1

### ISSUE THREAD

**Issue by oclanis** [modxcms/evolution#1277]
Hi Folks, i'm running Apache 2.2.21 with PHP 5.3.8 and MySQL 5.0.8

Modx version 1.2.1
installed latest modx works fine so far, until i try to change the template within a resource / document, it says that the current document is edited by the user i'm currently logged in with. Also getting the an message which says that there are multiple Sessions active for a user.

Modx version 1.2
I reverted to Version 1.2 to get rid of the Document Lock issue in 1.2.1 and found out that when you edit a Template and assign template variables by clicking on "assigned variables" it will lose the sorting order of the template variables. This only happens when you assign tv's over the Template edit-section.

For that i checked the Database Tables, and when you assign tv's over the template-editor it will update the sorting in column "rank" in "site_tmplvars_template". All values in "rank" are null except tv's assigned over the Template-Editor?

Thanks so far, and for your good Work and Time

**Comment by Deesen** [comment]
Reg 1.2.1, are you sure all files were uploaded successfully? And have you run setup-routine successfully (/install/)? "Multiple Users" means you were logged in using 2 different browsers (and 2 different sessions). Maybe clicking "remove locks" would have helped? And you can also click directly on the lock-icon to release a single lock.

**Comment by oclanis** [comment]
Yes installation ran fine thru installroutine and upload, also. Version 1.2 is working fine for me, but not 1.2.1

http://abnahme.maineo.de is the latest Project i tried with Modx 1.2.1, since 1.2.1 isn't usable for me, i reverted to 1.2 which works perfectly.

No, this happens with just one instance of Firefox, also Internet Explorer, or Opera has the same userlock problem. When i change the Template in a Document it gives me the "User is editing Resource" message.

When you change the Template in a Document the Frameset reloads that page, after that i get the Message, like it loses the Session after that Reload, maybe the Session_id gets lost or something.

Tried everything, also checked for PHP issues, or special settings regarding Sessions in Version 5.3.8 but there are none, everything is on standard.

**Comment by dmi3yy** [comment]
plz test on 1.3.0 if still present write here:
https://github.com/evolution-cms/evolution/issues

**Comment by oclanis** [comment]
Oh fine, will download and test this weekend.
