### ISSUE TITLE
So many Error request to my website

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#1281]
Hi,

I found so many error log in my system events like this : 
http://domain.com/?q[]=a

**Comment by mgzawlinoo** [comment]
Source: Parser -         $q = trim($q,'/');
 / PHP Parse Error - The details of the error could be seen in the MODX system events log.

**Comment by Deesen** [comment]
Probably related to https://github.com/modxcms/evolution/pull/700

**Comment by Nicola1971** [comment]
same errors from two websites last night (from the same user  i.p.)

**Comment by bossloper** [comment]
Yes I had multiple sites with the same 'probing' last night. I guess it would be nice to not get the error but I don't think it is a security issue?
