### ISSUE TITLE
Global change basic snippets in core

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1284]
In my custom i clear many snippets:
https://github.com/dmi3yy/modx.evo.custom

I think need change some: 
AjaxSearch (use from extras)
Ditto -> DocLister
eForm -> FormLister
breadcrumbs -> DLcrumbs
Jot -> (use from extras)
membercheck - > (If can the same)
personalize -> (If can the same)
reflect - (use from extras)
wayfinder -> DLBuildMenu
WebLogin -> FormLister

**Comment by modxuser** [comment]
I am personally **against** removing:

- WayFinder
- Ditto
- eForm

These are fundemental snippets that have been in Evo pretty much since the start and are used in all of my websites and are not easily changeable, simply because I have multiple custom snippets that work directly with these core elements.

Meaning, if they were to be removed I would have to spend thousands of Euros to have all of my custom code re-coded to work with the other snippets.

**Comment by dmi3yy** [comment]
I suggested an alternative. 
And we dont stop support WF, Ditto, eForm  only move to extras ) 
But for new sites i not use this use new snippets they are better, but need write Manual on English 
http://docs.evolution-cms.com/Extras/Snippets/FormLister
http://docs.evolution-cms.com/Extras/Snippets/DocLister

for sample if on site 10 000 + with new snippets you can do site speed 2х or more faster 
and query 2x and more times less


Again, I propose options for development and specifically made for discussion :)

I use my fork(https://github.com/dmi3yy/modx.evo.custom) and there I can do everything I think is necessary but here in the official branch there is not only me :)

**Comment by fourroses666** [comment]
Why not move all to Extras. If you need something just go to extras and click install of update. I don't see the problems with it. When I need a navigation then just install wayfinder of dlbuildmenu.

**Comment by dmi3yy** [comment]
Dont want all to extras like REVO 
on 99% sites have:
menu, breadcrumbs, items, forms, images
than better when have default snippets for this ) 

i only want. update dafault snippets for more actual ) i know it hard and need for many people read new docs and test this but...

**Comment by modxuser** [comment]
Please don't get me wrong, I have nothing against NEW, but what I have a problem with is that the new snippets don't have English documentation ([Doclister does](http://www.evolution-docs.com/extras/doclister/)) and If I am right, they do not cover everything the others do.

- Can Doclister do Tagging, like Ditto (this is a major must have) ?
- Does Doclister have a split pagination e.g First Prev 1 2 3 ... 10 11 12 ... 80 81 82 Next Last
- Can Google recapthcha be added to FormLister easily ?

**Comment by dmi3yy** [comment]
Tagging not doing yet, when do write docs.
Doclister  split pagination work by default 
recapcha http://modx.im/blog/addons/4880.html 

you can do on eForm (login user, register user, edit document from frontend)? :)  
what about Ditto and Wayfinder on 20 000 documents? :) 

read about prepare it easy way to do site faster :)

I understand that there is no documentation and examples, but is this really an excuse not to develop? And use old solutions when there are new ones?
It is difficult to learn new things but it gives more opportunities.
If all against I leave unchanged a set of snippets, but you yourself do the same worse without striving for development. And in terms of documentation for a long time there is a question that the community would help her write. But unfortunately no one needs it. I unfortunately do not have time to code and write the documentation, but I'm always ready to help you tell if someone will take this responsibility

**Comment by modxuser** [comment]
@dmi3yy you are turning my words.

I have **NOTHING** against "NEW", so long as the new does what the old can

English documentation is a must, I am not a developer like you - I wish I had your talent, but I don't and as such, I am restricted in what I can do - I am not the only one in this situation, but I am one of few who actually open their mouths and say things that are sometimes uncomfortable

I am not Russian and as such can't translate Russian documentation

I am still working on the new English documentation website, when I have spare time - so if someone can translate then I see no problem in adding that content into the new site - as has already happened with DocLister.

**Comment by dmi3yy** [comment]
Sorry if I twisted the words. In general, I'm for what would be the development and that's right the question was asked: Can Doclister do Tagging

Actually, for this I created a topic that I could understand whether we can painlessly update the main snippets or there are still questions.

**Comment by Pathologic** [comment]
Default captchas in FormLister (you can create your own captcha class and use it):
![modxcaptcha](https://cloud.githubusercontent.com/assets/3012304/24195312/50bc920e-0f0a-11e7-96e7-83b45e318f69.png)
![recaptcha](https://cloud.githubusercontent.com/assets/3012304/24195313/50bce1d2-0f0a-11e7-8a57-f67a927049f9.png)

@dmi3yy are you trolling? DocLister [got tagging](http://modx.im/blog/addons/374.html) 4 years ago.

**Comment by dmi3yy** [comment]
OOO )) i not used Tagging 4 years))

**Comment by Pathologic** [comment]
reflect can be replaced with DLReflect, but I never used them.

**Comment by nick0** [comment]
Why not improve / refactor ditto and wayfinder and eform? They work brilliantly and most Evo users know how to use them. 

Why replace these snippets with new, undocumented and unproven elements that we need to find the time to learn, and then replace, and then troubleshoot, in our Evo sites? 

Its a big job to do that and to me it sounds like the situation with PHx / IF vs Modifiers all over again where the new addition can't do everything that the old can do and site owners waste time trying to get the new things working. Less is more.

I vote leaving ditto and wayfinder and eform as default Evo snippets and continuing to develop these. If someone wants to use the new things, they can install them from the Extras module and manually delete ditto and wayfinder and eform themselves.

**Comment by dmi3yy** [comment]
Refactor ditto sound good but imposible ) and Agel_Nesh will write new ) few year ago ) 
work all fine. Ok we are leave Ditto but i think no sense to refactor when we have DocLister ) 


about  PHx / IF vs Modifiers - yes its bad  i want delete all this and return to stable parser. 
I uderstand its no good for some site where use new phx/@/modifiers but no see another way. 

new parser know only Yama ( and no he havent time to fix (

**Comment by pmfx** [comment]
Ditto, eForm and other popular and proven snippets that users know, must stay on board. There is too much confusion with built-in filters/modifiers already. I think that rolling back to a stable parser is a good idea.

**Comment by Deesen** [comment]
I think its all about keeping the evolution.zip small, with no snippets / plugins installed by default which is not the worst idea, like Revo. Maybe it is possible to create a separate category in Extras first place, where all these "removed extensions" are listed. So after MODX install, just browse Extras/New Category and install Ditto, Eform, Wayfinder etc from there.

Maybe in future Extras can be improved so you can mark extensions and combine them to a list, to be able to install this list quickly on a new server/installation. So every developer with user-account can have his own mix / list of default extensions.

**Comment by modxuser** [comment]
@Deesen 

In reality it isn't possible to remove certain snippets as they are required for the default demo content, unless that is also removed, which in my opinion isn't something that should be done.

**Comment by dmi3yy** [comment]
For demo no problem its fast to change)

**Comment by modxuser** [comment]
I think you misunderstand what I meant @dmi3yy 

**What I meant is:**

No matter what snippets are used, new or old, they will still have to be distributed with the core if demo content is to be kept in.

**Comment by fourroses666** [comment]
For democontent (selecting Sample Site) you can add a description to download Snippet x and y.

**Comment by dmi3yy** [comment]
best way  change in snippets in work for 30 min )) if we are decide use new i do this )

**Comment by digitalime** [comment]
I agree that fewer snippets should be distributed in the default zip, as it is currently getting a bit big, and there is not need for a lot of the stuff in there.

By all means, move the following to Extras:

- AjaxSearch
- Breadcrumbs
- Jot
- Membercheck
- Personalize
- Reflect
- WebLogin
- WebSignUp

But I would argue for keeping the following:

- Ditto
- eForm
- Wayfinder

DocLister looks promising, but as mentioned above, there will be very limited adoption until there is some substantial documentation in English available.

<offtopic>What the hell happened to wiki.modxcms.com!?</offtopic>

Evolution is falling behind somewhat in the documentation department. The work done on http://docs.evolution-cms.com/ looks fantastic, but it's not so useful for non-Russian speakers. What is the progress of getting this translated to English? I would be happy to get involved in such an effort. A single location for the complete Evolution Documentation with examples and tutorials is sorely needed. This is a major task which I feel this needs to be prioritised rather than developing new snippets which simply improve functionality which already exists.

**Comment by modxuser** [comment]
@digitalime 

Take a [look here](http://www.evolution-docs.com/) for English docs including updates and information from the Github WIKI and the LLC WIKI

Ref Wiki - its been offline for weeks

**Comment by dmi3yy** [comment]
Russian docs all there 
https://github.com/evolution-cms/docs/


Отправлено с iPhone

**Comment by digitalime** [comment]
@modxuser 

Thanks a lot. That looks great! (especially the updated API docs).

However, documentation and examples for new snippets like DLcrumbs and FormLister still seems to be missing. This was the crux of my initial argument about keeping the "old" snippets around for a while longer.

I know the Wiki has been offline for a while - I was just unaware that the content now had a new home.

@dmi3yy Thanks a lot for that.

**Comment by modxuser** [comment]
@digitalime

> However, documentation and examples for new snippets like DLcrumbs and FormLister still seems to be missing.

As [noted here](https://github.com/modxcms/evolution/issues/1284#issuecomment-288366751)

**Comment by dmi3yy** [comment]
FormLister all there: http://docs.evolution-cms.com/Extras/Snippets/FormLister 
DLcrumbs  and DLBuildMenu 
https://github.com/Aharito/DocLister/blob/master/assets/snippets/DocLister/snippet.DLBuildMenu.php
https://github.com/Aharito/DocLister/blob/master/assets/snippets/DocLister/snippet.DLcrumbs.php

will be soon on docs.  ()

**Comment by digitalime** [comment]
@dmi3yy @modxuser Thanks a lot gents.

Apologies for hijacking this thread. The original discussion about which default snippets to include and which to remove, I think is an important one.

One thing that I think most will agree on is that there are some snippets in there which should be moved to Extras right now:

- AjaxSearch
- Breadcrumbs
- Jot
- Membercheck
- Personalize
- Reflect
- WebLogin
- WebSignUp
