### ISSUE TITLE
Update to php 7.0.13 

### ISSUE THREAD

**Issue by Metzelder21** [modxcms/evolution#1285]
php: 7.0.13
MODX v1.2.1

After the update I get the errors:

Fatal error: Uncaught Error: Call to undefined function mysql_query() in J:\usr\www\users\wuertp\manager\includes\document.parser.class.inc.php(1318) : eval()'d code:600 Stack trace: #0 J:\usr\www\users\wuertp\manager\includes\document.parser.class.inc.php(1318): eval() #1 J:\usr\www\users\wuertp\manager\includes\document.parser.class.inc.php(4482): DocumentParser->evalPlugin('//<?php\n\nif(!cl...', Array) #2 J:\usr\www\users\wuertp\manager\includes\document.parser.class.inc.php(737): DocumentParser->invokeEvent('OnWebPagePreren...', Array) #3 J:\usr\www\users\wuertp\manager\includes\document.parser.class.inc.php(2234): DocumentParser->outputContent() #4 J:\usr\www\users\wuertp\manager\includes\document.parser.class.inc.php(2141): DocumentParser->prepareResponse() #5 J:\usr\www\users\wuertp\index.php(128): DocumentParser->executeParser() #6 {main} thrown in J:\usr\www\users\wuertp\manager\includes\document.parser.class.inc.php(1318) : eval()'d code on line 600

any ideas?

**Comment by dmi3yy** [comment]
In manager/includes/config.inc.php set 
Type to mysql 

Or fix all mysql_ to mysqli

Отправлено с iPhone
