### ISSUE TITLE
Old stable parser

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1286]
I return old parser but need tests
github.com/dmi3yy/modx.evo.custom/tree/parser

you can only change this file 
https://github.com/dmi3yy/modx.evo.custom/blob/parser/manager/includes/document.parser.class.inc.php
 
http://modx.im/blog/5082.html

**Comment by modxuser** [comment]
I am not sure if this matters but according to [this page](https://github.com/modxcms/evolution/wiki/@IF-@ELSEIF-@ELSE-@ENDIF), there are distributed files using the @ modifiers, which I presume is the reason to return the parser back to its former state ?

[Here](https://github.com/modxcms/evolution/blob/develop/manager/media/style/MODxRE2/welcome.tpl) and [here](https://github.com/modxcms/evolution/blob/develop/assets/plugins/elementsintree/assets/on_manager_tree_render.tpl)

**Comment by dmi3yy** [comment]
Test old and new parser. Need fix only  Cross References  on Ditto and all good 


then i thin no sense rol back need fix  some issues and will be all good)
