### ISSUE TITLE
[not an issue] Multiple login sessions

### ISSUE THREAD

**Issue by sashabeep** [modxcms/evolution#1289]
Sometimes i forget to exit before moving test site to domain and see the message about 
```
Information: Multiple active user sessions (total 2) found for user %username%
```
Maybe, need to clear duplicate sessions after resetting filemanager and assets path after moving?

**Comment by Fr3ddy7** [comment]
https://github.com/modxcms/evolution/issues/1256

**Comment by dmi3yy** [comment]
i think its info need hide )
