### ISSUE TITLE
Duplicating document containing ' in pagetitle generates SQL error

### ISSUE THREAD

**Issue by BBloke** [modxcms/evolution#1291]
If you try to duplicate a resource containing and apostrophe in the page title.  Modx shows the following SQL error:

SELECT pagetitle FROM `valbruna`.`modx_site_content` WHERE pagetitle LIKE 'Duplicate Site 'offline Duplicate%'

Workaround is to remove the apostrpohe.

BBloke

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/issues/38
