### ISSUE TITLE
TiniMCE 4 Image insert

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#1300]
The new version greatly reduces the possibility of inserting pictures, for example there is no field to specify the *title*, but only *alt*.

The are a comparison TiniMCE4 Image insert and TinyMCE3
![image](https://cloud.githubusercontent.com/assets/5120610/24867257/560dabde-1e15-11e7-8f12-f5acc5f1a1e3.png)

PS. I think it is to many reason to teave tinyMCE3 as plugin for possibility to use it

**Comment by pmfx** [comment]
AFAIK there is no "title" attribute for an img tag in HTML specification. "title" is for link. "alt" is for image. 
https://www.w3schools.com/tags/tag_img.asp
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by Deesen** [comment]
Doesn´t "title"-attributes generally provide a tooltip for mouse-over?

**Comment by fourroses666** [comment]
Tooltips should be on a href indeed but it prolly would work on img too when using title.

**Comment by MrSwed** [comment]
[directresize](https://github.com/extras-evolution/directResize/blob/master/assets/plugins/directresize/configs/fancybox.config.php#L7) use *alt*, *title*, and other, that specified for image

**Comment by MrSwed** [comment]
Besides the title there is still not enough opportunity
And also lacks a "preview"
![image](https://cloud.githubusercontent.com/assets/5120610/24893990/cda64b40-1e8f-11e7-8322-06a0942b6d21.png)

**Comment by dmi3yy** [comment]
For this use class;) 

Yes without preview

Отправлено с iPhone

**Comment by Deesen** [comment]
Reg. the "title" in Tiny4 I found this parameter: https://www.tinymce.com/docs/plugins/image/#image_title

So adding the following to theme.tinymce4.base.inc.php should activate it:

    $this->set('image_title', true, 'bool' );
