### ISSUE TITLE
Глюк при работе плагинов - Plugin parse error, Temporarily disabled..

### ISSUE THREAD

**Issue by webber12** [modxcms/evolution#1301]
Постоянный глюк вот с этим куском - https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L1344-L1351 - плагин CResource не хочет работать по неизвестным причинам (в отчете "Plugin parse error, Temporarily disabled..."), плагины с названием TagSaver-|| вообще выдает ошибку вроде "некорректное имя файла" и т.п. Возможно, какие-то специфические требования к плагинам или к их названиям, чтобы эта штука работала, но на данный момент ее везде пришлось закомментировать.

**Comment by dmi3yy** [comment]
С плагинами вообще сложно они выдают ошибку без логов никто не прописывал логику отслеживания ошибок для плагинов никогда :(

**Comment by Pathologic** [comment]
Я тоже столкнулся, когда в плагине была ошибка, которую я исправил, но плагин так и не заработал; минут 10 я тупил :)  Может и неплохая идея, раз уж кривой плагин на OnManagerPageInit может вырубить админку. Но что если плагин сделает $modx->sendRedirect, lock-файл не удалится и все поломается?

**Comment by urbanklpn** [comment]
тоже столкнулся с этой бедой https://monosnap.com/file/FzAPGCYbo6cdgf2cHtA6Z6XOrostcU.png не часто, но стабильно падает эта ошибка

**Comment by dmi3yy** [comment]
Исправили ж глюк с лок файлом уже так же просьба писать тут: 
начиная с версии 1.3 основной репозиторий переехал: 
https://github.com/evolution-cms/evolution/issues
