### ISSUE TITLE
bug with ElementsTree

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#1302]
http://images.vfl.ru/ii/1492167235/2312f733/16855213.jpg

**Comment by modxuser** [comment]
I mentioned that the @ modifiers are also featured in files that are used by exactly this plugin, [noted here](https://github.com/modxcms/evolution/issues/1286#issuecomment-288676417)

Maybe thats the problem

**Comment by dmi3yy** [comment]
not solved. 

incorect work parsing parametrs from install
