### ISSUE TITLE
mm_multiplefields richtext field editing

### ISSUE THREAD

**Issue by sashabeep** [modxcms/evolution#1311]
Using current installation package it's impossible to edit richtext field created in managerManager multiplefields
![rt](https://cloud.githubusercontent.com/assets/5689796/25268996/83be00ee-2683-11e7-8633-39a8d259267a.png)

Edit link opens the blank window and control buttons in the footer of this window has no effect, seems like OK and Cancel do nothing, previously filled text didn't displayed in editor box
![2017-04-21 11 06 50](https://cloud.githubusercontent.com/assets/5689796/25269247/7ae8a3ec-2684-11e7-8cfb-cf39115ee495.jpg)

If i turn off old TinyMCE 3.x (4.x also installed with 1.2.1 as well) popup window shows only blank textarea and same two buttons

$ is not defined in popup window

**Comment by sashabeep** [comment]
Pull request to fix issue
https://github.com/modxcms/evolution/pull/1312

**Comment by MrSwed** [comment]
#1304 correct using richeditor from modx config..
