### ISSUE TITLE
Remove whitespace in PHP codes in the site cache - dont remove 90% of needed

### ISSUE THREAD

**Issue by webber12** [modxcms/evolution#1323]
This function don`t remove tabs and even spaces in html-code (chanks,templates etc) and in json-params for elements. But over 90% of spaces - in this elements. 
So its practically unuseful without that functionality.

in russian

Попробовал данную настройку и оказалось, что она не удаляет не только табы, но и обычные пробелы ни в чанках, ни в шаблонах, ни даже в параметрах json для плагинов и т.п. А т.к. 90% пробелов сосредоточены именно там, то функцию "вытягивания" кода в одну строку и, соответственно, урезания размера массива, она совершенно не выполняет.

**Comment by dmi3yy** [comment]
ну так оно вытягивает системные шутки то что в чанках и не должно трогать :)
