### ISSUE TITLE
Ошибка 404 для дочерних ресурсов

### ISSUE THREAD

**Issue by myindexlike** [modxcms/evolution#1326]
если у родителя убрать галочку участвует в url, то все дочерние начинают отдавать 404 страницу

**Comment by myindexlike** [comment]
чтобы ошибка воспроизвелась надо:
1) у родительской категории снять галочку "Участвует в URL"
2) в настройках сайта выставить Использовать AliasListing только для Папок - Да.

**Comment by janniconl** [comment]
Please use English language here -_-

**Comment by sunhaim** [comment]
Request engine improvement - include in documentListing all children of parent, hidden from url

**Comment by dmi3yy** [comment]
If use aliasListingFolder 
Then last folder need show in url



Отправлено с iPhone

**Comment by sunhaim** [comment]
Yes, but with this improvement it won't be necessary

**Comment by sunhaim** [comment]
This will provide stable engine work with no additional hidden conditions
