### ISSUE TITLE
TinyMCE ignores "Use global settings"

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#1339]
In 1.2.2-beta3 TinyMCE ignores "Use global settings" (for editor buttons) in user profile settings.

**Comment by nick0** [comment]
Good pickup @pmfx. I think is related to #1205.
Also seems to be another bug in TinyMCE with #1324.
Would be great to have these resolved for the next version.

**Comment by Deesen** [comment]
Cannot recreate this issue. I guess you wanted to edit the toolbar-buttons. Have you set the TinyMCE4 theme to "custom"? Otherwise settings like "Custom Buttons" and "Custom Plugins" have no effect.
