### ISSUE TITLE
MODxRE2_DropdownMenu not working

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#1340]
MODxRE2_DropdownMenu is amazing but Manager main frame is not working when user role don't have "Run module" permission.

**Comment by risingisland** [comment]
This is working for me, any other settings that might be different between roles?

**Comment by pmfx** [comment]
Try to disable all Elements and "Use the file manager (full root access) " permissions too.

Role screenshot:

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/26509963/77ee81be-425b-11e7-8bbd-2a78dd200690.png)

Bug:

![screenshot_2](https://cloud.githubusercontent.com/assets/10888055/26509994/8b69bce0-425b-11e7-9d40-88c2f5423d9e.png)

**Comment by risingisland** [comment]
OK, I was able to replicate the problem, but I think the problem is with "Edit Plugins".
Leave everything like you have it, but enable the "Edit Plugins" to see if the same thing happens.

**Comment by pmfx** [comment]
Yup. With "edit plugin" permission it works. This is odd behavior.

**Comment by risingisland** [comment]
In my instance, I am using a plugin (EvoDashboard) that personalizes the welcome page.
If I disable this, all works as intended.
Are you using any similar plugins as well?

**Comment by pmfx** [comment]
No. It is a clean Evo install with sample site.

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/26514632/55dda916-4273-11e7-9f38-6ad3dbd3ad22.png)

**Comment by risingisland** [comment]
Tomorrow, if I get the chance, I will create a fresh install and see if it is still does this.
Either way its strange and shouldn't be happening, as I dont let other users edit plugins.

**Comment by risingisland** [comment]
I just created a clean install, and now it is functioning correctly.
Maybe you could do the same to see what happens?
Im going to keep messing with it to see what is triggering this error.

**Comment by risingisland** [comment]
@pmfx @dmi3yy 
Experimenting with the settings, I have found that enabling any of the four Edit functions makes it work again, but I cant find what is causing it to brake.

![modx cms manager](https://cloud.githubusercontent.com/assets/6113504/26520834/420b87d2-42d2-11e7-8fc9-31741c1ec958.png)

**Comment by Deesen** [comment]
It seems to me this is related to "elementsInTree"-plugin. If user has no permissions to any type of elements, it leaves a `<div>` open which causes the HTML-code to break and the dashboard to be not displayed.

**Comment by Deesen** [comment]
I guess this should be the fix.

**Comment by risingisland** [comment]
Thanks @Deesen 
Yes this seems to fix it.

**Comment by pmfx** [comment]
Thanks Deesen. Thats working now but there is new JS error -  unable to open images/file browser.

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/26542629/01b19caa-445b-11e7-8463-d5b4f98bb2cc.png)

Console error:

![screenshot_2](https://cloud.githubusercontent.com/assets/10888055/26542631/0442504a-445b-11e7-91b8-0b6ad7ba1984.png)

**Comment by pmfx** [comment]
It occurs when user role have no elements/modules permissions even if ElementsInTree plugin is disabled.

**Comment by Deesen** [comment]
Yes this is related to https://github.com/modxcms/evolution/pull/1342#issuecomment-304591843
