### ISSUE TITLE
MODxRE2_DropdownMenu ElementsInTree filtering issue

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#1343]
When using MODxRE2_DropdownMenu theme, ElementsInTree filtering is not working after you open chunk or other element to edit.

**Comment by pmfx** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/10888055/26553672/0306f67c-448d-11e7-8ce0-e7b3e270e1b7.png)

**Comment by risingisland** [comment]
It seems to work when you first enter Manager, or hit [F5] to refresh, but once you browse to a different section (elements, modules, etc.), it quits working.

**Comment by pmfx** [comment]
Yes, exactly.

**Comment by pmfx** [comment]
In 1.2.2-beta2 it was working fine.

**Comment by Nicola1971** [comment]
same for me
