### ISSUE TITLE
1.2.2-beta3 - font size TinyMCE content

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1345]
The font-size isn't correct anymore.
It was the same as all other text but now its uge again.

![x](https://cloud.githubusercontent.com/assets/523389/26576470/47d5f374-4529-11e7-9421-97c5a95deeaf.jpg)

**Comment by Deesen** [comment]
Why not generally add your own `tinymce.css` to all installations so you have full control? There you can add

    body {
      font-family: What-ever, sans-serif;
      font-size: 11px;
    }

**Comment by fourroses666** [comment]
I know but shouldn't we use the same size for the whole manager on default.
