### ISSUE TITLE
1.2.2-beta3 User can't create resource in root

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#1346]
I have this option enabled in configuration:

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/26585566/c72a594e-454c-11e7-87e6-c5d9d1650eae.png)

But user can't create resource in root.

**Comment by Deesen** [comment]
Maybe you want to test, but should work.

**Comment by pmfx** [comment]
Fixed
