### ISSUE TITLE
MODx 1.2.1 Unable to Set TinyMCE4 as default editor 

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#1347]
How can this be done?  This [thread](https://forums.modx.com/thread/?thread=100387&page=2) talks about hardcoding which I tried without success.

**Comment by Tourist4Life** [comment]
Now sadly TinyMCE4 won't load at all.  I change the Editor to use value to TinyMCE4 as seen here:

https://cl.ly/2h2N2i1u471R

but nothing happens

**Comment by Deesen** [comment]
Any errors in browser console? Have you tried to clear MODX-cache (this will unlock locked plugins, in case TinyMCE4 was locked cause of any error)?

**Comment by Tourist4Life** [comment]
I have cleared the cache in the manager.  Do I need to delete cache files on the server?  If so which one?  Thanks Deesen!

**Comment by Deesen** [comment]
If plugins-lock was the issue, clearing cache in manager should help. Too less details/hints for me to guess what is going wrong on your side.

**Comment by Tourist4Life** [comment]
No errors in the console when viewing the manager.  Is there other information that I can give you?  

I believe that this may be a bug with 1.2.1 as [others](https://forums.modx.com/thread/?thread=100387&page=2) here are unable to get TinyMCE set as the default browsers?

**Comment by Deesen** [comment]
Can you give server-access to save time?

**Comment by Tourist4Life** [comment]
Done.

**Comment by risingisland** [comment]
Deeson has probably fixed it by now, but I remember one time during an upgrade I had a minor hickup with this. After changing the config to use tinymce, I also needed to set each user to also us it. 
Dont know if thats what was needed in your case?

**Comment by Deesen** [comment]
I have logged into manager now, and I noticed the following

- in MODX-configuration the default-editor was set to "None"
- when editing resource I could not change the editor from "None" to "TinyMCE4"
- but when setting TinyMCE4 as default in MODX-configuration, it is available when editing a resource

So maybe there is a bug that prevents temporarily switching of the editor, when it is set to "None".

**Comment by Tourist4Life** [comment]
Where did you change the default configuration?

In the config file or the manager?

**Comment by Deesen** [comment]
Within manager -> Tools -> Configuration -> Tab "Interface & Features" -> Editor to use
