### ISSUE TITLE
Bug in TinyMCE

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1348]
When placing an image in the Content field. -> Select the image, click on the link icon, link to a file, then you can't click on OKE.

Nothing happens.

When you do the same with selecting text it does work.

I think I found a bug! (1.2.1 and FF on mac)

![uhhh](https://cloud.githubusercontent.com/assets/523389/26729804/17be3c7c-47af-11e7-9cc3-af59dcc0d2f5.jpg)

**Comment by nick0** [comment]
Glad it isn't just me :). 
This is related to a couple of things in #1324.
I can't add a class or a link to images.
Would be great to have it fixed.

**Comment by dmi3yy** [comment]
plz test i update   tinymce to 4.6.3

**Comment by nick0** [comment]
Thanks @dmi3yy! Great work. That solves all three things in #1324. Now I can:
- ad a wrapper div to images
- add a link to an image
- add a class to an image

The 4.6.3 version does not solve the custom toolbar issue from #1205. For some reason I still cannot get rid of the second row of buttons in TinyMCE. This may be related to this below?

Not sure if another bug has surfaced? But the placeholder [+defaultCheckbox+]  is shown in the "tools > configuration > interface & features >  TinyMCE4 Settings" section. See image below...

![untitled-1](https://cloud.githubusercontent.com/assets/1768308/26770529/dc1c43d6-49f6-11e7-9363-29edadbe6487.png)

**Comment by Deesen** [comment]
I just checked the "[+defaultCheckbox+]" issue and with latest version of today everything works as expected. Can you maybe re-check with latest version?

**Comment by Jako** [comment]
You should make those extras installable separate from the core: The package on http://extras.evolution-cms.com/packages/adminka/tinymce4.html and in the store is 4.3.7.

Not everyone has the time to update the core, when he wants to fix a bug in an extra. And (somehow worse) not everyone wants to install a prerelease core version from GitHub, when he wants to fix a bug in an extra.

**Comment by dmi3yy** [comment]
Yes i will update soon in extras

**Comment by nick0** [comment]
> I just checked the "[+defaultCheckbox+]" issue and with latest version of today everything works as expected. Can you maybe re-check with latest version?

Hmmmm. I just tried the updated 4.6.3 in my Evo 1.2.1 install. 

The TinyMCE Plugin>Configuration page looks a little wierd with lots of text below the settings boxes (which were previously much wider) - see below:
![untitled-1](https://user-images.githubusercontent.com/1768308/27059049-b0b0456c-5013-11e7-8f75-03205decafb8.png)

And the TinyMCE section doesn't load at all in the Tools>Configuration>Interface&Features section (TinyMCE 4.6.3 is definitely installed)

Any ideas?

**Comment by Deesen** [comment]
Seems your configuration-string has been corrupted for any reason. You could try to tick the checkbox "Parse DocBlock" and then save the Plugin again to reset its configuration to default.

**Comment by nick0** [comment]
Thanks @Deesen.
I tried saving "Parse DocBlock" checkbox and that fixed the display on the Plugin > Configuration page. However, the TinyMCE section still doesn't load at all in the Tools>Configuration>Interface&Features section and now the Security, File Manager and File Browser Tools tabs do not load - it seems more broken now :)
Any ideas?

**Comment by Deesen** [comment]
Yes you can look into the main-frames source-code at the end to look for any PHP error-message. Maybe some files were not uploaded correctly, causing now an error.

**Comment by nick0** [comment]
Thanks for your help @Deesen.

 

Now I seem to be stuck in an endless loop of not being able to get 4.6.3 working in Evo 1.2.1. Even after manually deleting the cache file in assets/cache.

Either I activate 4.6.3 and I can’t access the rest of Interface & Features, nor the last 3 tabs – or I deactivate 4.6.3 and I can.

When I revert to 4.7.3 that came with 1.2.1 all data/tabs in Tools > Configuration displays as expected.

 

This is the error in system events when trying 4.6.3:

Plugin parse error, Temporarily disabled 'TinyMCE4'.

 

So it seem I am back to square 1 with that image wrapper / link / class issue. Bummer!

**Comment by Deesen** [comment]
Hmm maybe test 1.2.2-beta?

**Comment by nick0** [comment]
I can’t in this site unfortunately. Must have been some major changes from 1.2.1?? Thanks anyway @Deesen.

**Comment by fourroses666** [comment]
Will reopen if it doesn't work in the newst version
