### ISSUE TITLE
Modx System Error with .Core dump

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1349]
I have been receiving some system errors followed by .core dumps on a few sites.
I originally thought that it was related to phpThumb, but now I am starting to think it may be Ditto.

It happened again today, while building a new site, and I hadn't implemented phpThumb yet, but it seemed to be triggered by very basic call on a section using Ditto. I noticed the system seemed to hang for a bit. No errors, but then I found a big .core file via FTP.

A different time I received a sys. email:

> "Modx System Error on Web Site
> Source: SQL Query / Execution of a query to the database failed - MySQL server has gone away - The details of the error could be seen in the Modx system events log."

But nothing was in the events log.

Has anybody experienced this before or have any ideas what is causing this or how to diagnose?

**Comment by fourroses666** [comment]
Sounds more like server issues but I'm not an expert.
