### ISSUE TITLE
Template Variables have duplicate form label IDs 

### ISSUE THREAD

**Issue by ricardo-lewis** [modxcms/evolution#1350]
I have two sets of TVs, one is a group of 4 checkboxes, the other is a group of 4 radio buttons.

The MODX Manager is rendering the second set of form inputs as having the exact same IDs as the first.

This results in the first inputs being triggered by clicking on the labels of the second.

You can see below how the label of the radio will trigger the input of the checkbox.

From the first set:
````html
<label class="checkbox"><input type="checkbox" value="dont-show-in-doc" id="tv_0" name="tv3[]"  onchange="documentDirty=true;" />Don't Show In Document</label>
````
From the second set:
````html
<input type="radio" value="news" id="tv_0" name="tv32" checked="checked" onchange="documentDirty=true;" /><label for="tv_0" class="radio">News</label>
````

In my case it's pure coincidence that I had 2 groups of exactly 4 controls and the second set will trigger the first.

**Comment by Deesen** [comment]
Yes this has been fixed with https://github.com/modxcms/evolution/commit/94938d29a5d5a8b0844052c1046623dbd416710d . Which version are you using?

**Comment by ricardo-lewis** [comment]
I was under the impression that I was using the very latest 1.2.1 release

**Comment by ricardo-lewis** [comment]
I can see the fix was not included in the release

https://github.com/modxcms/evolution/blob/41267f98a8ee64e06678818e30e422875a1f8158/manager/includes/tmplvars.inc.php#L101
