### ISSUE TITLE
Лишняя папка в TinyMCE

### ISSUE THREAD

**Issue by AndreyMyagkov** [modxcms/evolution#1354]
В папке с плагином TinyMCE 4.6.3 лежит папка с предыдущей версией TinyMCE 4.6.1
assets\plugins\tinymce4\tinymce\js\
Эту папку можно удалить.

**Comment by risingisland** [comment]
The above message is correct (via Google translate), that the folder "assets/plugins/tinymce4/tinymce/js" should be removed, as it contains a full previous version (4.6.1) of TinyMCE that is not needed and only bloating the package.
@dmi3yy @Deesen
