### ISSUE TITLE
Error when configuring general settings of the site.

### ISSUE THREAD

**Issue by MyckolaPetrychko** [modxcms/evolution#1356]
I have that error: 
Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2

And the sql is like: 
SELECT DISTINCT sc.* FROM `modx`.`modx_site_content` AS sc LEFT JOIN `modx`.`modx_document_groups` AS dg ON dg.document = sc.id WHERE sc.parent='1' AND (1='1' OR sc.privatemgr=0) ORDER BY createdon LIMIT 0,

It has redundant comma in the end. Where I can fix it?

Modx version: 1.2.2.
php: 7

**Comment by Deesen** [comment]
- https://github.com/modxcms/evolution/blob/develop/manager/actions/document_data.static.php#L74
- https://github.com/modxcms/evolution/blob/develop/manager/includes/extenders/maketable.class.php#L489

Maybe `MAX_DISPLAY_RECORDS_NUM` is not defined for any reason?
