### ISSUE TITLE
Errors in MODxRE2_DropdownMenu

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1358]
@dmi3yy 
Many problems with 404s.
**Main Menu**
-   Elements
-     Templates, Template Variables, Chunks, Snippets, Plugins
-   Security
-     Manage Users, Web Users

**Tree**
-   Font size?

![my modx site modx cms manager](https://user-images.githubusercontent.com/6113504/27010611-56369786-4ea0-11e7-9b13-4bda1795b0f4.png)

**Comment by dmi3yy** [comment]
Thanks lost one file 
Add today 

Отправлено с iPhone

**Comment by risingisland** [comment]
Thanks.
Also, menu icons not showing...
![untitled-1](https://user-images.githubusercontent.com/6113504/27011070-e1f05694-4eab-11e7-9f17-cc4e69eb904b.jpg)

**Comment by pmfx** [comment]
What happened to previous version of navbar with dropdowns? It was much more better looking. Bigger, with icons etc.

**Comment by risingisland** [comment]
I too liked the bigger navbar. I had just finished updating the color scheme  :confused:

![cms](https://user-images.githubusercontent.com/6113504/27011418-30587594-4eb3-11e7-9b70-bf8ac3b5be4d.png)

**Comment by pmfx** [comment]
Yeah, thats the one. It was very good. No idea why it was changed to this small, dark one. Please bring it back @dmi3yy !

**Comment by risingisland** [comment]
@dmi3yy 
Can we bring back Menu Icons?

**Comment by dmi3yy** [comment]
http://take.ms/bwYHR
http://take.ms/daB92


now we are do theme like desctop app like   github Desctop )

and clear html code  after finish then return to design



От 11 июня 2017 г. в 22:04:27, risingisland (notifications@github.com)
написал:

@dmi3yy <https://github.com/dmi3yy>
Can we bring back Menu Icons?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/modxcms/evolution/issues/1358#issuecomment-307649546>,
or mute the thread

**Comment by risingisland** [comment]
@dmi3yy 
Unable to see Save Options correctly...

![manager](https://user-images.githubusercontent.com/6113504/27024475-9c4eba38-4f4e-11e7-907a-586e28656c16.png)

If theme is copied to create new theme (ex.: MODxRE2_DropdownMenu-New), dropdown does not work at all.

**Comment by risingisland** [comment]
Also Tree collapse / expand is not working correctly.

**Comment by dmi3yy** [comment]
What your browser?  cant reproduce bug with tree

**Comment by risingisland** [comment]
Firefox has problem. 
Chrome works fine.

**Comment by pmfx** [comment]
Same for me on Firefox.
Tree collapse issue + cutted off action dropdown.

**Comment by risingisland** [comment]
@pmfx After a few of these bugs are fixed, I can send you my theme version, which is similar to the blue that I posted up above, if interested.

**Comment by risingisland** [comment]
Snapshot button spacing...
![snapshot](https://user-images.githubusercontent.com/6113504/27042212-35090852-4f8e-11e7-878c-e15e1760283f.png)

**Comment by risingisland** [comment]
Tree now works.
Button alignment good.

Still a problem (in firefox) with Save drop-down:
![my modx site modx cms manager](https://user-images.githubusercontent.com/6113504/27251661-4f982e06-5343-11e7-9259-59309d8f2882.png)

**Comment by dmi3yy** [comment]
Fixed all this
