### ISSUE TITLE
Edit Resource on iPad - Missing Action Buttons

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#1363]
When editing a resource on an iPad the right side action buttons (Save, Duplicate, Delete etc) sometime are not displayed. It seems to be if the edit is done using the edit button.
To reproduce:

1) edit a resource in the manager using iPad
2) cancel the edit using cancel action button
3) use the edit button to edit the resource again

Result is the right side action buttons are missing. They remain missing even if another resource is edited.
This is the same for either manager theme (MODxRE2 or MODxRE2 Dropdown Menu).

![img_0093](https://user-images.githubusercontent.com/1744687/27031029-84099f5c-4f66-11e7-86a2-ac27aa297020.PNG)

**Comment by dmi3yy** [comment]
update to 1.3 all work fine )
