### ISSUE TITLE
Error on update to dev version

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1369]
Got an error when update from last week development version and the latest one.:

![yay](https://user-images.githubusercontent.com/523389/27231224-35f2c150-52b2-11e7-98da-585e87982507.jpg)

**Comment by risingisland** [comment]
I have this same error on a clean install. 
Previous did not have this.

**Comment by risingisland** [comment]
This seems to be resolved in the latest update.

**Comment by fourroses666** [comment]
Oke, yes mine was on a new install too.
