### ISSUE TITLE
TV (Checkbox) last state in backend after update to 1.2.1

### ISSUE THREAD

**Issue by signalfeuer** [modxcms/evolution#1374]
I updated a modx project from 1.1 to 1.2.1.

The problem is that a TV (checkbox) lost his state in this backend. There are three checkboxes which should be checked. The third of them is now unchecked on all pages (300+). Frontend is still fine and outputs the right content as if all three checkboxes were still checked.

If i save one of the pages again – without re-checking the third checkbox - i also lose the state in the frontend.

Any idea how to solve the problem without editing all the 300+ pages in backend again?

<img width="526" alt="bildschirmfoto 2017-06-20 um 10 52 42" src="https://user-images.githubusercontent.com/10433748/27324816-ac203190-55a6-11e7-8eb5-6ebdd0c99350.png">

**Comment by Deesen** [comment]
I just tested this issue with latest 1.2.2-beta3 and no issues. Every checkbox will be saved and reloaded correctly inside manager.

Maybe replacing this file with latest version helps? https://github.com/modxcms/evolution/blob/develop/manager/includes/tmplvars.inc.php

**Comment by signalfeuer** [comment]
Thanks for your help, but replacing that file doesn't change anything! :-(

**Comment by Deesen** [comment]
Sry for delay.. maybe as a workaround add a fourth blank/blind option which makes no difference if it gets lost or not? On the other hand, are there any errors in browser-console?

**Comment by signalfeuer** [comment]
That was a good idea but sadly doesn't solved the problem! :-(
There a no errors in browser-console. Tested with Chrome & Safari (Mac).

**Comment by mgzawlinoo** [comment]
Hi,
Sorry signalfeuer. 
Not related with this issue.
I have TV with checkbox type.
Add Widget Delimited tag value to " , " (comman and space)
But the output value only show (,) comma. didn't  include space value.

Eg ,I want to output value - 200, 201 (200 comma space 201)
but output value - 200,201.
I would like to know how to add extra space value in widget delimited tag value.
