### ISSUE TITLE
Googlebot 302 redirect

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1375]
I know that the sitemap snippet is not a core feature, but figured that there is probably a fare amount of people using it.

The issue I am having is when it is submitted to Google, it received this error:
> Redirect error: Redirect error
> HTTP Error: 302

And will not index it.
The sitemap.xml reads fine without error if I browse to it, and if I copy the content to a .txt file, Google reads it fine.

Anyone have any ideas or experienced this problem?
Any help would be greatly appreciated.

**Comment by risingisland** [comment]
This problem isn't related to sitemap. It is an overall problem. Opening new thread.

**Comment by fourroses666** [comment]
Maybe but just guessing. Is it a .htaccess issue?

**Comment by risingisland** [comment]
I've gone through and tried disabling friendly urls as well as remove .htaccess
If I copy the source, and upload it as a flat file. It is fine.

**Comment by risingisland** [comment]
I noticed that Google was completely dropping on of my sites.
When I tried to submit the sitemap.xml, I noticed the 302
Later after testing more pages on the site, I found that they were all giving 302s
Browsers work fine.

I started testing with:
http://www.redirect-checker.org/index.php

and receiving via the googlebot option:

```
302 Moved Temporarily
Status:	302 Moved Temporarily
Code:	302
Date:	Fri, 23 Jun 2017 14:29:12 GMT
Server:	Apache
X-Powered-By:	PHP/5.6.30
Location:	/
Content-Length:	0
Connection:	close
Content-Type:	text/html; charset=utf-8
```

**Comment by Deesen** [comment]
What happens if you try to view `yourdomain.com/sitemap.xml` inside your browser? Does it give you also a 302-redirect? If so, try setting resource-alias to "sitemap.xml" and Content-Type to "text/xml".

**Comment by risingisland** [comment]
Thanks for the feedback @fourroses666 @Deesen . I am kind of freaking out over this. :/
Via browser, sitemap and all pages view fine. no problems.
I had already had the settings as you mentioned.
Within the sitemap, there is no mention of redirects.

**Comment by bossloper** [comment]
Could it be server level setup issue? There are various threads about virtual directory setups returning 302 which Google webmaster does not like.

**Comment by risingisland** [comment]
How would I deduce this? and is there any info for a solution?
I have been googleing, but not finding any info like what you are mentioning.

**Comment by Deesen** [comment]
Maybe this helps? I guess the only solutions seems to upgrade your hosting-package then:

https://productforums.google.com/forum/#!topicsearchin/webmasters/authorid$3AAPn2wQcKph8N0rCzC6Y6woBSgsvRPxsV94us4Xf4bc3hNnxJzY11lS2fNbtojmTxmsNaBKhu8W22%7Csort:date%7Cspell:false

**Comment by risingisland** [comment]
I am not using godaddy hosting, as mentioned in your link.
But the strange thing is that I have several sites hosted on the same server and it seems to only be effecting the most recent installs/updates. Older sites seem to be fine.
I dont know why it would be effecting some and not others?

**Comment by risingisland** [comment]
Also, why would this be only happening to the PHP files, and not HTML files?

**Comment by Deesen** [comment]
This issue is surely not only related to GoDaddy. Probably your hoster does work the same like stated in one of the posts:

"This is not the first time I've run into this kind of situation. A few years ago I worked with a woman who owned a server farm. We had a similar problem on another domain. After much research, it turned out to be the use of virtual directories causing 302's. By putting domains in sub folders of central domains, (to save money) an instantaneous redirect occurred by necessity. A redirect that Google's crawlers can recognize, and don't like."

Maybe you can try providing instead of "sitemap.xml" the none-SEF variant like "index.php?id=123" (123 is your sitemap´s resource-ID). If TXT-files are read fine, maybe this variant causes no 302 too.

**Comment by risingisland** [comment]
Thanks for all the input Deeson.
I had also tried "index.php?id=123", but the result was the same.
Yes, using flat-files (html, xml) seem to work as excepted.

Here is one more question, I dont know if you can answer.
I placed the sitemap in a renamed .txt file, added its link to the Robot file, the new sitemap.xml is read fine by googlebot, but individual pages are not. So my question is, will having a sitemap be sufficient, or are all pages needed to be 302 free?

**Comment by Deesen** [comment]
Reg. SEO, I think all pages must be free of redirects. Especially free of 302 and 307 (both temporary redirects, while 301 is permanent redirect), as temporary redirects will not be indexed by Google AFAIK.

**Comment by Deesen** [comment]
Maybe it helps if you mention which hoster and rate you are using, so we can investigate on these details too.

**Comment by risingisland** [comment]
I am using a reseller package with InmotionHosting.com
Also, I would be happy to give you access to a test domain I set up.

**Comment by risingisland** [comment]
Thank you everybody for your assistance. This has been fully resolved.

This was due to the latest version of [Blackhole for Bad Bots](https://perishablepress.com/blackhole-bad-bots/) that I had added to Modx.
After performing many site file compares, I found that it was due to this update causing the problems.
