### ISSUE TITLE
Bug in method getDocumentChildrenTVars

### ISSUE THREAD

**Issue by AndreyMyagkov** [modxcms/evolution#1377]
$modx->getDocumentChildrenTVars($tourParent, array('myTv'), '1','', '', 'value' ) - return empty result 
https://monosnap.com/file/B19RxloaTKyXo55EdYxjVVk4gujYzZ

$modx->getDocumentChildrenTVars($tourParent, array('myTv'), '1','', '', 'id,value' )  - return empty result 
https://monosnap.com/file/B19RxloaTKyXo55EdYxjVVk4gujYzZ

$modx->getDocumentChildrenTVars($tourParent, array('myTv'), '1','', '', 'id' )  - return id and value  http://take.ms/izXudJ

**Comment by yama** [comment]
I found problem. I will fix it later

**Comment by yama** [comment]
Maybe fixed. Would you please test this fix?

**Comment by dmi3yy** [comment]
if still broken write plz here:
https://github.com/evolution-cms/evolution/issues
