### ISSUE TITLE
Dark theme selectable on config or user page?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#1378]
I'd like to be able to choose the dark theme as default for the admin and users. I like it.
Maybe we can add a dropdown select on the users page or on the configuration page in the manager?

![dark](https://user-images.githubusercontent.com/523389/27913144-71b635de-625f-11e7-9725-aeb7f66f12a9.jpg)

**Comment by risingisland** [comment]
Isnt this the purpose of being able to choose different themes?
Or maybe this should be added in Security/User Manager, like TinyMCE is?
Or possibly I am misunderstanding.

**Comment by dmi3yy** [comment]
In plans to do in the settings the ability to customize the design by analogy with october cms
