### ISSUE TITLE
Who now "owns" Evo ?

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1386]
I am aware that Evo has now moved and as such, who actually owns the rights to it now ?

I see Dmi3yy has added his name to the login logo "Evolution By Dmi3yy". Which in my personal opinion is a bit to much, as Evo is an open source project with multiple contributors.

So for clarity - who is responsible / the owner of Evo "as it is" at this present moment ?

**Comment by dmi3yy** [comment]
Sorry i not removed in new thene this logo  been in my custom 
https://github.com/dmi3yy/modx.evo.custom

in  EVO havent my nikname on logo:)  
http://take.ms/A5sIP

Now i Owner for EVO but EVO still opensource and will be all time opensource
