### ISSUE TITLE
Package Manager

### ISSUE THREAD

**Issue by risingisland** [modxcms/evolution#1387]
"Package Manager" module no longer works in v1.2.2 where it had been in the previous betas.
Is there anybody who is technically capable and that has time to look at this?
@dmi3yy @Deesen @Nicola1971

**Comment by dmi3yy** [comment]
I tested all ok 
http://take.ms/qysk0

can you send screenshot with error

**Comment by risingisland** [comment]
No error, everything shows blank. 
Cant veiw/load any local packages.
![package_manager](https://user-images.githubusercontent.com/6113504/28085092-829e2b2e-6672-11e7-8e59-8bfb07f48b27.png)
Before I could view existing or load new...
![package_manager-norm](https://user-images.githubusercontent.com/6113504/28085190-d93a7bb8-6672-11e7-8e2d-62546622060f.png)
I am using the latest as far as I know? v1.0-RC4

**Comment by dmi3yy** [comment]
Yes i tested in 1.2.2 and 1.0-RC4

**Comment by risingisland** [comment]
OK, I just switched from theme from "ModxRE2_Dropdown" to "ModxRE2" and it works.
It appears that there is a problem with the Dropdown theme.

**Comment by dmi3yy** [comment]
I tested on dropdown theme;) 

Maybe troube with browser cache

**Comment by risingisland** [comment]
OK, installed a new clean copy. Tried on both FF and Chrome. Same problem, only with Dropdown theme.
Viewed source, found that "manager\media\style\MODxRE2_DropdownMenu\style.css", line 100 is causing the problem.
`.tab-pane > .tab-page { display: none }` 

 By removing "display none" it seems to work fine. I dont see any problems anywhere else at the moment.

![untitled-1](https://user-images.githubusercontent.com/6113504/28087047-05d34032-6679-11e7-9b01-941cbc7d01df.png)

**Comment by dmi3yy** [comment]
ok will fix this

**Comment by risingisland** [comment]
Thanks Dmi3yy.

When you have a moment, maybe look at this bug to see if it can be fixed:
https://github.com/modxcms/evolution/issues/391

**Comment by dmi3yy** [comment]
Fixed in 1.3.0b
