### ISSUE TITLE
Future Updates for MODX Evo

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#1390]
I presume that any updates will now be via the new [Evolution CMS GitHub page](https://github.com/evolution-cms/evolution) and MODX Evolution 1.2.2 was the last release from this branch

If this is correct - can the community be informed somehow via the update channel ?

@Deesen , @yama , @dmi3yy

**Comment by dmi3yy** [comment]
Wait plz some days i prepare releases and public news:)


Отправлено с iPhone

**Comment by modxuser** [comment]
Cool
