### ISSUE TITLE
Renaming Folder "assets" for better Security

### ISSUE THREAD

**Issue by q2apro** [modxcms/evolution#1398]
I would like to suggest an enhancement to make Evolution CMS more secure. 

We already have the option to rename the `manager` folder. The other standard folder that comes with the installation is `assets`. When we could add an option to rename this folder as well, no bot could easily infiltrate, in my opinion. 

There were recent incidents that bots captured several evo/modx websites in Lithuania. The bot just searched for the assets path and a vulnerable module. If the path would be different, the bot had never found it. 

Thanks for your consideration. And great work, I love the new Evolution CMS!

**Comment by Deesen** [comment]
Please post it here https://github.com/evolution-cms/evolution/issues

**Comment by q2apro** [comment]
Sorry, my fault. Post sent over there.
