### ISSUE TITLE
How to install/update a Rich text editor in Modx evolution?

### ISSUE THREAD

**Issue by nidhiguptanawab** [modxcms/evolution#1399]
My client has a site built on Modx and there tinyMCE editor is not working at all but for the life of me I can't figure out how to fix it.

I can see the editor is selected but its not showing editor bar and everything is showing up in html, I am trying to install a new editor but can't figure out how to do it properly, can someone please help, its urgent.

Thanks so much,

**Comment by dmi3yy** [comment]
All work fine tinyMCE 3 or tinyMCE 4 
What version in Evo you use? 
And send plz screenshot of plugin list

Отправлено с iPhone

**Comment by nidhiguptanawab** [comment]
Hi Thanks for your reply, there are two tinymce editors in the list but without any version number.I downloaded tinymce4 from modx website but I can't figure out how to install it and make it to work.
![image](https://user-images.githubusercontent.com/16870633/30530547-d8f53d66-9c8a-11e7-9449-db72c49b266a.png)

**Comment by nidhiguptanawab** [comment]
and this is how it looks on the page edit screen
![image](https://user-images.githubusercontent.com/16870633/30530607-75d7077c-9c8b-11e7-961d-f5ea16ee6744.png)

**Comment by Deesen** [comment]
You need to figure out which TinyMCE-plugin is v4 and then rename the plugin´s name. So the names are like:

- "TinyMCE"
- "TinyMCE4"

Then you can choose "TinyMCE4". The plugins MUST have different names to work.

**Comment by nidhiguptanawab** [comment]
But can you please tell me how to install a new plugin? because in the assets > plugins folder there is only one tinyMCE folder so I am not even sure how two instances of tinymce are in the dropdown.

Thanks

**Comment by Deesen** [comment]
In "elements-management -> plugins" there must be 2 TinyMCE-plugins existing which become listed. If they are a duplicate, you can disable (and later delete) one of them.

Which Evo-Version do you use?

**Comment by nidhiguptanawab** [comment]
Modx version is 1.0.3
and this is the plugin version
![image](https://user-images.githubusercontent.com/16870633/30531741-90b2590e-9c93-11e7-8e0d-3a0985bb0be7.png)

**Comment by Deesen** [comment]
Wow this is OLD.. TinyMCE4 will probably not be compatible. Maybe disable one of these plugins (first 7, then 11) to test if it works then.

**Comment by nidhiguptanawab** [comment]
ha ha yes I tried disabling one of them, will try the other one and let you know. Thanks

**Comment by Deesen** [comment]
If not you can also check browser-console for Javascript-Errors.

**Comment by nidhiguptanawab** [comment]
ok so other than that no other option to fix the issue?

**Comment by Deesen** [comment]
It is hard to guess what the exact problem is in your case without further infos like from browser-console.

**Comment by dmi3yy** [comment]
Disable one 
Thay can not work together

Отправлено с iPhone

**Comment by dmi3yy** [comment]
Tiny4 cant work on 1.0.3

Отправлено с iPhone

**Comment by nidhiguptanawab** [comment]
ok so its working now :D

**Comment by Deesen** [comment]
Nice, then please close the issue.
