### ISSUE TITLE
MODx Evolution 1.2.1 Shopping Cart Solutions

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#1412]
Can anyone recommend a third party solution to drop into my MODx Evo 1.2.1 builds?  I've used Foxycart and Paypal years ago and I'm not sure if these are still an option.

Thanks.

**Comment by Tourist4Life** [comment]
Where is the download link to MODx 1.4.3?

**Comment by dmi3yy** [comment]
https://github.com/evolution-cms/evolution/releases

**Comment by dmi3yy** [comment]
http://evoshop.pro - now we work on evoShop but not finished yet 
https://tsvshop.xyz
https://github.com/extras-evolution/shopkeeper

**Comment by Tourist4Life** [comment]
Ok thank you.  I will have difficulty with the documentation as it is not in English.  Any other resources that have examples in practices?
