### ISSUE TITLE
При вставке логотипа [(login_logo)] картинка подставляется в [(login_bg)]

### ISSUE THREAD

**Issue by EGO7000** [modxcms/evolution#1413]
Может конечно только у меня такой глюк..
Возможно проблема в дублирующейся функции SetUrl(), и в итоге выполняется нижняя:
```
function SetUrl(url, width, height, alt) {
              document.settings.login_bg.value = url;
              document.images['login_bg'].src = "/" + url;
}
```
Браузер Chrome под Mac OS X.

**Comment by dmi3yy** [comment]
В дев версии помойму уже исправили 
Ага проблема в том м что функция переопределялась
