### ISSUE TITLE
evo 1.2.1 tinymce 4 - how to link to type "images", not only "files"

### ISSUE THREAD

**Issue by wishbone-design** [modxcms/evolution#1416]
before upgrading to tinymce 4, there was a setting somewhere (I don't remember where) and I was able to link to different resource types, i.e. to see in fckeditor options for files, images, media.
Now, with tinymce 4, I can't find such any more.
How can I insert a link and kcfinder displays the different folders for different types, i.e. "images", "files" etc. E.g. link an image to it's larger version.
Should be possible, huh?
thnx

**Comment by Deesen** [comment]
Yes, "files" can be linked just by clicking on the normal link-button and then

![image](https://user-images.githubusercontent.com/8569221/42125247-5cb4b94c-7c73-11e8-9339-99aded2fe5c7.png)

**Comment by Deesen** [comment]
BTW. the repository has moved to 

https://github.com/evolution-cms/evolution/
https://github.com/evolution-cms/evolution/issues

**Comment by wishbone-design** [comment]
thx, Deesen!
sure, that's the default: link to the "files"-folder.
I want to link to the "images"-folder to be able to have a large pop-up to an image.
Solution from 9 years ago ;-) doesn't work.
[https://forums.modx.com/thread/?thread=13450&i=1&page=2](url)

**Comment by wishbone-design** [comment]
before the upgrade to Tinymce 4, I added *somewhere* "images" to the file type and had these options:
![modx-templ-04](https://user-images.githubusercontent.com/3841564/42127276-961e24d0-7c95-11e8-9f34-34f155559d9e.jpg)

**Comment by wishbone-design** [comment]
before the upgrade to Tinymce 4, I added *somewhere* "images" to file types, and had these options:
![modx-templ-04-o](https://user-images.githubusercontent.com/3841564/42127289-f0603b18-7c95-11e8-969d-a572227b573c.jpg)
