### ISSUE TITLE
Не корректная работа при обновлении страницы

### ISSUE THREAD

**Issue by Sesqiwake** [modxcms/evolution#1419]
При обновлении страницы, появляется на секунду меню(на весь экран), которое по дефолту свернуто, я понимаю, что ошибка где-то по коду. Посоветуйте куда смотреть. чанк/ссылку на проект/фрагмент бага могу показать

**Comment by dmi3yy** [comment]
В первую очередь смотреть сюда: 
https://github.com/modxcms/evolution/issues/1391 

А дальше писать в нужное место хотя бы со скринами или видео это облегчит понимание где у вас ошибка и как ее решить. Ибо подобной проблемы не наблюдаю
