### ISSUE TITLE
FirstChildRedirect as checkbox in page setttings

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#180]
My idea is to add a function like [[FirstChildRedirect]] so the client can let a page redirect to the first child instead of adding an ID every time?

Checkbox on tab Page settings?

**Comment by fourroses666** [comment]
:fire: :construction_worker: :fire: 

any plans to do this for 1.0.16?

**Comment by fourroses666** [comment]
:fire_engine:

**Comment by fourroses666** [comment]
I'm having troubels with caching. The wayfinder navigation keeps linking to the wrong / old Id.
Maybe there is a possibility to add redirect 301 to .htaccess? 

I have a add on to clear cache and its ok again then but my clients don't. Maybe the way FirstChildRedirect uses can be improved/changed?

**Comment by bossloper** [comment]
Quite a while back FirstChildRedirect was updated. The default was changed from a 302 (temporary) redirect to a 301 (permanent) redirect. You will need to add a parameter &responseCode=`302` to your FirstChildRedirect calls to prevent the browser caching the redirect. Personally, for a CMS it is quite common to have changing content and site structure and so would make more sense to revert FirstChildRedirect to having a default of a 302 redirect.

**Comment by pmfx** [comment]
I agree with bossloper. Default 301 response can lead to unnecessary headache in most scenerios.

**Comment by fourroses666** [comment]
Not sure SEO wise the 302 is good but it could be a solution to add the parameter. I would like to see this option(s) to the settings Tab. I like the idea of Segr.

**Comment by bossloper** [comment]
RE:302 - The parameter already exists as part of the snippet.
True it is not ideal for SEO, but that is a call you have to make based on how a particular site is managed. If you have a site where you are not the only manager and there are other managers occasionally renaming pages you have to decide between 'better SEO' and 'page not found'. From a usability perspective I cannot have site visitors clicking page links and ending up at a page not found. But if page rename is a rare occurrence for your site you might be ok with that risk.

**Comment by fourroses666** [comment]
Magento does great with automaticly add a rewrite to the new URL.

**Comment by dmi3yy** [comment]
FirstChildRedirect has setting for set Order and ansver(301,302) i think  do this by chekbox in doc not right way.  For sample you can use weblink ) or any another way )
