### ISSUE TITLE
Errors in default template

### ISSUE THREAD

**Issue by Segr** [modxcms/evolution#197]
Not valid HTML & CSS
Unnecessary chank - for example "foorer"
Unnecessary code in CSS

**Comment by fourroses666** [comment]
What do we do? Remove it, update it? 
I can do a new responsive "Simple" theme but someone needs to change the "Demo site" then.

**Comment by dmi3yy** [comment]
Will be great new light simle demo site 
Need ready site and i intergate it

Отправлено с iPhone

**Comment by fourroses666** [comment]
Oké, 

I will my own responsive styles, just very basic..
Might need to change the Wayfinder tpl chunks too.

**Comment by fourroses666** [comment]
next week I'm on vacation so I'm afraid this will be done at the begin of februari

**Comment by Deesen** [comment]
Just for info, we already started building a new Bootstrap theme to replace the old one.

**Comment by fourroses666** [comment]
can be closed

**Comment by bossloper** [comment]
+1 close this...
