### ISSUE TITLE
Change word "Widget" -> "Processor"

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#240]
https://en.wikipedia.org/wiki/Widget
http://wiki.modxcms.com/index.php/Widgets

I don't use several widgets.
They are Floater, Marquee, RichText, Ticker and View Port.
They have some problem, use old Mootools.

Remain widgets are Image, HTML Entities, Date Formatter, Unixtime, Delimited List, HTML Generic Tag, Hyperlink, String Formatter and Data Grid.
I think, they are not "Widget". Widget is like blog parts.
"Processor" or "Converter" or "Formatter" are better.
Otherwise, "Output Filter".

**Comment by bossloper** [comment]
Is this still applicable (2 1/2 years), or can be closed?
