### ISSUE TITLE
Duplicating pages with slash

### ISSUE THREAD

**Issue by coffee-aroma** [modxcms/evolution#244]
Hi,

Modx creates duplicates pages, example:
for http://site/oo1/oo2/oo3/
Modx creates countless pages
- http://site///oo1/oo2/oo3/
- http://site/oo1///oo2////oo3///
- http://site/oo1//oo2/oo3///
- ...

Can I fix it?
Or configure a 404 error pages that contain more than one slash streak?

Thx

**Comment by bossloper** [comment]
can be closed?

**Comment by modxuser** [comment]
@coffee-aroma can you close this issue please if it has been resolved
