### ISSUE TITLE
Template Variable Type 'date' doesn't allow manual time

### ISSUE THREAD

**Issue by atmmarketing** [modxcms/evolution#261]
The 'clicking on days in the calendar' bit works, but you can't seem to type in a custom time. 

As soon as you do that, you lose the selected day (it reverts to today's date).

So you either have a custom date with the time set to now, or you have a custom time with the date set to today.

I'm referring to the little field for time that sites beneath the calendar.

**Comment by Deesen** [comment]
Still present? Cannot exactly recreate.

**Comment by bossloper** [comment]
It can work but is not very user friendly.

If you want both the date and time set you need to first select the month and year of the date wanted.
Then set the time and finally pick the date.

**Comment by Deesen** [comment]
Ah ok some situations were not ideal. I tried to improve..
