### ISSUE TITLE
should modx check for valid session cookies?

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#277]
I have seen in server logs invalid session ids which are an indication of bots checking for system information via failures. e.g.

PHP Warning: session_start() [<a href='function.session-start'>function.session-start</a>]: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in ...

Should a session check be added to the startCMSSession function in config.inc.php to check for valid sessions? Something along the lines of adding this, or similar, just before session_start() ?:

		if (isset($_COOKIE[$site_sessionname])) $checksessid = $_COOKIE[$site_sessionname];
		else if (isset($_GET[$site_sessionname])) $checksessid = $_GET[$site_sessionname];
		if (isset($checksessid) and !preg_match('/^[a-zA-Z0-9,\-]{22,40}$/', $checksessid)) {
			header('Status: 406 Not Acceptable');
			die();
		}

**Comment by dmi3yy** [comment]
fixed
