### ISSUE TITLE
Add Snippet Documentation

### ISSUE THREAD

**Issue by iAmKrug** [modxcms/evolution#280]
It would be great to see documentation for all snippets, plugins, and modules that ship with MODX Evolution. The most difficult thing about working with MODX is the lack of documentation. Most documentation is either barebones, outdate, or refers to a dead link

**Comment by dmi3yy** [comment]
better way do like this: 
http://docs.evolution-cms.com
https://github.com/evolution-cms/docs - but this only Russian
