### ISSUE TITLE
"Loading Files" Indefinitely

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#281]
https://github.com/yama/kcfinder-for-modx/issues/1
Moved from this issue.

After updating to Modx Evolution 1.0.14, when I attempt to open KCFinder all I get is a "Loading Files" message:

![screen shot 2014-06-18 at 9 55 57 pm](https://cloud.githubusercontent.com/assets/386558/3323831/06de3982-f76e-11e3-9e8b-bbef82a1d766.png)

**Comment by maximal** [comment]
The same issue :-(
