### ISSUE TITLE
Is MODx compatible with HHVM?

### ISSUE THREAD

**Issue by martinseener** [modxcms/evolution#307]
I know its working fabulously with libapache2-mod-php and php-fpm but does it also run with Facebooks HHVM?

**Comment by xaionaro** [comment]
According to information from our users: 

Version 2.2.10 works (except admin panel). The current latest version doesn't work.

**Comment by martinseener** [comment]
So there is no fully compatible version there, yet? Or how do you run modx when the admin panel does not work?

**Comment by xaionaro** [comment]
> So there is no fully compatible version there, yet? Or how do you run modx when the admin panel does not work?

nginx backends to hhvm for everything except admin panel and to apache2's mod_php5 for the admin panel.

**Comment by martinseener** [comment]
Ah okay. But thats too much, so we will wait for a fully compatible version then. Thanks for informtion!
