### ISSUE TITLE
Remember position after saving

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#318]
I really like the way revo remembers the position of the resource/page after saving.
I have to scroll down every time I save the chunk / template or editing a file when using the File Manager etc. When having a very long css file this can be very frustrating :( 
(It would safe allot of developing time!)

Is it possible this feature can be implemented?
I have no idea if it is a large task to do and if there are any disadvantages.
It works great in rev's manager.

When searching on google I found this: 
http://blog.crondesign.com/2009/09/scrollfix-remember-scroll-position-when.html

**Comment by dmi3yy** [comment]
Done
