### ISSUE TITLE
Add Font Awesome package in assets/js or assets/css

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#326]
I think that adding Font Awesome package ( in assets/js or assets/css)  would be of great help to the development of Modules interfaces, Snippets  and Plugins.
we would not need to add new images icons for each module or extra

the Font Awesome package will be called inside modules and plugins with the classic method (link href) or using **OnManagerMainFrameHeaderHTMLBlock** event

**Comment by dmi3yy** [comment]
i think better way use   assets/lib/ - for external libs  (like vendor folder) - its start to use composer )
like https://github.com/AgelxNash/DocLister/tree/master/assets/lib

**Comment by fourroses666** [comment]
:)

**Comment by Nicola1971** [comment]
@fourroses666  :D

i think i can close
