### ISSUE TITLE
Add a checkbox to hide/deactivate Templates

### ISSUE THREAD

**Issue by ricardo-lewis** [modxcms/evolution#328]
It would be nice to have a checkbox e.g. Active that would let you choose what templates appear in the selector. At the moment, we have to delete database records to remove unused Templates from the list. This is sub-optimal since a lot of my template code is based on templates having a fixed ID.

**Comment by pmfx** [comment]
Sure, MM can do that, but that is not exactly user friendly in this case. Would be nice to have this. I would want to see it on template edit page and as a bulk action when editing site configuration maybe.

**Comment by pmfx** [comment]
I would go even further and allow user to check/uncheck default MODX TVs and all other TVs while editing template. The same way as it is done with "TVs on Template" plugin (wich is great BTW). Unfortunately this plugin doesn't include default MODX TVs. Maybe it would be easier to enhace this plugin and make it a part of core build?

**Comment by dmi3yy** [comment]
Yes it will be good 

Îòïðàâëåííî ñ òåëåôîíà
www.dmi3yy.com

**Comment by fourroses666** [comment]
can be closed!

**Comment by ricardo-lewis** [comment]
I forgot I requested this. Really nice to see it made it into the core! Thanks so much!
