### ISSUE TITLE
Wayfinder hideSubMenus still applies parentClass to empty menus

### ISSUE THREAD

**Issue by ricardo-lewis** [modxcms/evolution#345]
When &hideSubMenus=`1`, the parentClass CSS class is still applied to non-active menus that have children, but are empty.

It would be nice if the snippet could refrain from adding the parentClass to a menu item if all its children are currently hidden.

**Comment by MrSwed** [comment]
maybe I misunderstand the problem .. but when the & hideSubMenus = 1 html of not active submenu is not displayed 
for example
`[[Wayfinder?  &hideSubMenus=1 &startId=`0`]]
`

- item 1
- item 2
  - subitem 2.1
  - subitem 2.2
- item 3
  - subitem 3.1
  - subitem 3.2

open item 2 or some of it child, html will be only
```
<ul>
<li>item 1</li>
<li class="active">item 2
 <ul>
  <li>subitem 2.1</li>
  <li>subitem 2.2</li>
 </ul>
<li>item 3</li>
<ul>
```
no html for subitem 3.1 and 3.2

does not it ?

**Comment by ricardo-lewis** [comment]
The HTML for item 3 adds the CSS class for a regular "parent" item, even though it should not be considered a parent because it is empty (its children are hidden).

**Comment by dmi3yy** [comment]
All correct need class parent 

Отправлено с iPhone

**Comment by ricardo-lewis** [comment]
The problem occurs when you try and style the menu as a dropdown. The empty parent takes on the appearance of a normal dropdown. It's confusing for end users.

**Comment by MrSwed** [comment]
may be better to use strict inheritance in CSS
.menu > ul > li > ul
maybe that's why it still do not fixed, 
imho, it not necessary for the set of the parent class if use strict css

**Comment by ricardo-lewis** [comment]
You can't style an LI tag that does not have children. There is no such thing as a parent selector in CSS, apparently it's too computationally intensive. Therefore you cannot isolate an element that has children as opposed to one that does not. 

It would be far easier if Wayfinder kept track of which LI elements actually had children.

**Comment by fourroses666** [comment]
Correct me if I'm wrong but is this the same issue here?

I'm busy with a dropdown navigation atm. and noticed it adds the dropdown class while these pages are not selected as "visible in menu".

```
	[!Wayfinder? 
	&startId=`0` 
	&level=`2` 
	&removeNewLines=`1`
	&outerTpl=`@CODE:<ul class="nav navbar-nav">[+wf.wrapper+]</ul>`
	&rowTpl=`@CODE:<li[+wf.classes+]><a href="[+wf.link+]" [+wf.attributes+]>[+wf.linktext+]</a>[+wf.wrapper+]</li>`
	&innerTpl=`@CODE:<ul class="dropdown-menu">[+wf.wrapper+]</ul>`
	&innerRowTpl=`@CODE:<li[+wf.classes+]><a href="[+wf.link+]">[+wf.linktext+]</a></li>`
	&parentRowTpl=`@CODE:<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" title="[+wf.title+]">[+wf.linktext+] <b class="caret"></b></a>[+wf.wrapper+]</li>`
	&activeParentRowTpl=`@CODE:<li class="dropdown active"><a class="dropdown-toggle" data-toggle="dropdown" href="#" title="[+wf.title+]">[+wf.linktext+] <b class="caret"></b></a>[+wf.wrapper+]</li>`
	!]
```
Blog doesn't have any visible pages and when active wayfinder shows _activeParentRowTpl_.
![blog-not-visible-in-menu](https://cloud.githubusercontent.com/assets/523389/13396786/d23878f6-def6-11e5-9d42-ccede134a80b.jpg)

**Comment by ricardo-lewis** [comment]
@fourroses666 this is the exact issue I'm talking about.

**Comment by MrSwed** [comment]
check this
8b6dc88

**Comment by ricardo-lewis** [comment]
Looks like you're on the right path, @MrSwed

**Comment by fourroses666** [comment]
:+1:  works

**Comment by fourroses666** [comment]
@ricardo-lewis Can be closed right?

**Comment by ricardo-lewis** [comment]
@fourroses666 If the fix has been officially applied, yes. I didn't get the notice about the commit, sorry. I wonder how long before it gets officially released? I tend not run any core customisations.

**Comment by fourroses666** [comment]
No problem, just like a clean issue list :v: 
It looks like its merged into development and will be there on next version/upgrade.
