### ISSUE TITLE
OnInterfaceSettingsRender in user form

### ISSUE THREAD

**Issue by kulmjens** [modxcms/evolution#357]
Why is there an invocation of the `OnInterfaceSettingRender` event in the file `mutate_user.dynamic.php` on line 715?

Seems to me as if this event is only for the interface tab on the settings page. So if I want to insert some extra fields into the user form and use this event, these extra fields are also displayed on the interface tab on the settings page as long as I am not looking at the manager action 

But I think it would be nicer if there was an event so that one can add an extra tab to the user form, like `OnExtraUserFormRender` after line 797 in `mutate_user.dynamic.php`. Right after user access permissions part or maybe before that.

Or did I misunderstood something?

**Comment by Deesen** [comment]
I think this event was meant especially to add TinyMCE-settings. So to solve this issue I would propose
  - add new plugin-event `OnUserFormSettingsRender`
  - in `mutate_user.dynamic.php`
    - invoke `OnUserFormSettingsRender` after `OnInterfaceSettingsRender`
    - **OR** invoke `OnUserFormSettingsRender` instead of `OnInterfaceSettingsRender` (requires adding `OnUserFormSettingsRender` to TinyMCE and all plugins now using `OnInterfaceSettingsRender` for user-settings)
