### ISSUE TITLE
Can't get full URL in contentfield (with TinyMCE) because of KCFinder?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#370]
I have just updated an old website. The website was set with absolute path in TinyMCE because I send newsletters and need the absolute path. When I added an image in the contentfield the URL to the image was: http://www.domain.com/assets/images/img.jpg

But after update it is back to: assets/images/img.jpg
I really need the full URL because I'm sending newsletters.

I tried every TinyMCE option but none gave absolute path, nothing is changed.
Probably because of the new KCFinder?

I know there is an option to fix this: 
Configuration > File Browser > File Browser URL
and change the URL to http://www.domain.com/assets/

But this is not what I want because custom TV's have the full URL aswell.
I need only TinyMCE / the content field to use absolute path.

![this](https://cloud.githubusercontent.com/assets/523389/5008644/c750bace-6a5e-11e4-8c61-2c4873ad5f81.jpg)

Is there a setting I'm missing?
Its very important for me.

**Comment by fourroses666** [comment]
phpthumb also doesn't work with full url: 
``<img src="[[phpthumb? &input=`[*image01*]` &options=`w=80,h=80,zc=1`]]" width="80" height="80" />``

**Comment by Jako** [comment]
```
<img src="[(site_url)][[phpthumb? &input=`[*image01*]` &options=`w=80,h=80,zc=1`]]" width="80" height="80" />
```

**Comment by fourroses666** [comment]
My problem is that I need to use Full-URL in the content (because of the TEMailing Module). It then adds Full-URL also in my custom TV.
Older versions of Evo I was able to add only Full-URL into the content and custom TV's where fine. That doens't work anymore :(

**Comment by Jako** [comment]
[(site_url)] as prefix should generate a full url to your installation. The image TV should not have the full url inside, since phpthumb snippet can't work with that.

**Comment by fourroses666** [comment]
Hmm, I did a new test and now it does work.. very weird. I think I was confused about not seeing full url into the popup when selecting an image.

So basicly when someone needs full url into the contentfield (I did because of sending e-mailings)
you needs to set Tinymce config to path URL:
![hmm](https://cloud.githubusercontent.com/assets/523389/5999155/5dcb9afe-aacf-11e4-81a3-294dad8fc39b.png)

When adding an image the path isn't full url:
![popup](https://cloud.githubusercontent.com/assets/523389/5999349/5b0a9980-aad1-11e4-927c-f75a50d197c7.png)

But when looking at the html source of the contentfield it did add the full URL!
![html](https://cloud.githubusercontent.com/assets/523389/5999370/84a1ed98-aad1-11e4-9d17-7b7ad78bbffb.png)

**Comment by Jako** [comment]
That behaviour should depend on the TinyMCE plugin setting.

**Comment by fourroses666** [comment]
Yes but could it be the config setting "Rewrite browser paths" needs to be on Yes?

**Comment by Jako** [comment]
Could you create a new issue with that: something like 'TinyMCE does not respect Rewrite browser paths system settings‘

Hope this is the real bug that happens here.

**Comment by fourroses666** [comment]
Well, after checking it doesn't matter if selecting "Rewrite browser paths" yes or no for the full url in the contentfield.

I just need to make sure when having upgraded a site the Tinymce configuration Path options: absolute path needs to be URL.
