### ISSUE TITLE
Unable to upload images via mcpuk browser

### ISSUE THREAD

**Issue by neoneddy** [modxcms/evolution#371]
I can upload via the file manager so  I know it's not a permissions issue.  This is present in 1.0.14 and 1.0.15 .

I'm on Rackspace Cloud Sites, PHP Version 5.4.10.

![image](https://cloud.githubusercontent.com/assets/819083/5017571/89d14ac2-6a74-11e4-93e3-958c89feeadc.png)

```
Refused to set unsafe header "Content-Length" joiner.php:82reader.onload joiner.php:82
POST http://hardystephens.com/manager/media/browser/mcpuk/browse.php?type=images&lng=en&act=upload net::ERR_EMPTY_RESPONSE joiner.php:433XMLHttpRequest.sendAsBinary joiner.php:433reader.onload joiner.php:95
```

People familiar with the situation say the JS should not be specifying a content length, the browser should do that.  I'm just the messenger here.

**Comment by fourroses666** [comment]
I have the same problem. 
I don't mind to hack core files for now if that fixes the problem but don't know how.
I can't find ``misc.js`` 

Would be nice to change this for 1.0.16 ?

**Comment by sparkyhd** [comment]
/manager/media/browser/mcpuk/js/browser/

**Comment by fourroses666** [comment]
there is no misc.js there and adding the protected lines between <?php doesn't work. getting error.

**Comment by jorjik** [comment]
попробовал патчить - не помогло...
а в "бета-версии" Димы - это убрали ?

**Comment by vmoreira** [comment]
Hello any solution. I try to implement this "bit strange" hack and dont do.
Anyone can provide the file to upload to this hack please.

![captura de ecra 2015-06-17 as 23 16 27](https://cloud.githubusercontent.com/assets/1786615/8220054/f5f8c04a-1546-11e5-9885-e41a0e363330.png)

**Comment by Pathologic** [comment]
Sorry, but my hack is not enough. I can implement another uploader to KCFinder, but will it be the solution? If someone came across this issue, please provide information from your hoster, what modsecurity (or naxsi) rules KCFinder violates.

**Comment by vmoreira** [comment]
@Pathologic Thanks your information....
Someone use 1.0.15 ok? I can't implement this version... I have tried sometimes and can t do it :( I stil use 1.0.14...

**Comment by vmoreira** [comment]
I have asked my online service server... and the error is:
 [Thu Jun 18 16:32:26 2015] [error] [client 188.37.74.127] ModSecurity: Multipart: Skipping invalid part 7df0d98 (part name missing): (offset 0, length 0) [hostname "www.testing.pt"] [uri "/15/manager/media/browser/mcpuk/browse.php"] [unique_id "VYMq2UIH0J0AADRHMA0AAAAB"]
[Thu Jun 18 16:32:26 2015] [error] [client 188.37.74.127] ModSecurity: Access denied with code 400 (phase 2). Match of "eq 0" against "MULTIPART_STRICT_ERROR" required. [file "/usr/local/apache/conf/modsec2.conf"] [line "39"] [id "200002"] [msg "Multipart request body failed strict validation: PE 0, BQ 0, BW 0, DB 0, DA 0, HF 0, LF 0, SM 0, IQ 0, IP 1, IH 0, FL 0"] [hostname "www.testing.pt"] [uri "/15/manager/media/browser/mcpuk/browse.php"] [unique_id "VYMq2UIH0J0AADRHMA0AAAAB"]

The actual solution:
It looks like this upload script was supplying some incorrect request body data causing a ModSecurity error. We've disabled ModSecurity for the /manager/media/browser/mcpuk/browse.php...

After that all is OK but is necessary to ask to change ModSecurity every site I have to install ou upgrade... Not functional but it's the solution.

**Comment by Pathologic** [comment]
@vmoreira so, probably it would be easier to change uploader, as I understand nothing from your error log :smile_cat:

**Comment by Francisb** [comment]
@Pathologic 
I have the same probleme but with A2 Hosting, evo 1.0.15. 
I get this error and your hack does not work for me, it gives me the seme error but replace upload by upld : 

Error message I'm getting. 
&act=upload 401 (Unauthorized)

thanks for the hepl.

**Comment by rocaoliveira** [comment]
Hi, have version Evo 1.5 in Rackspace Cloud but CKfinder same problem any solution?
