### ISSUE TITLE
Several issue (and workaround) when your MySQL config sql-mode=ANSI_QUOTES

### ISSUE THREAD

**Issue by ghimawan** [modxcms/evolution#378]
1.
Error: Failed to upload image using TinyMCE
File: manager/media/browser/mcpuk/core/uploader.php
Line: 315
Content:
        $setting = $modx->db->select('count(_)', $modx->getFullTableName('system_settings'), 'setting_name="clean_uploaded_filename" AND setting_value=1');
Solution:
        $setting = $modx->db->select('count(_)', $modx->getFullTableName('system_settings'), 'setting_name=\'clean_uploaded_filename\' AND setting_value=1');

2.
Error: Failed to upload image using TinyMCE
File: manager/media/browser/mcpuk/core/uploader.php
Line: 318
Content:
            $res = $modx->db->select('properties', $modx->getFullTableName('site_plugins'), 'name="TransAlias" AND disabled=0');
Solution:
            $res = $modx->db->select('properties', $modx->getFullTableName('site_plugins'), 'name=\'TransAlias\' AND disabled=0');

3.
Error: Failed to install sample data
File: install/setup.sql
Line: 1091
Content:
UPDATE `{PREFIX}system_settings` set setting_value = if(setting_value REGEXP 'application/json',setting_value,concat_ws(",",setting_value,"application/json")) WHERE setting_name='custom_contenttype';
Solution:
UPDATE `{PREFIX}system_settings` set setting_value = if(setting_value REGEXP 'application/json',setting_value,concat_ws(',',setting_value,'application/json')) WHERE setting_name='custom_contenttype';

4.
Error: Failed to create/edit document
File: manager/includes/document.parser.class.inc.php
Line: 2051
Content:
        $access = ($this->isFrontend() ? 'sc.privateweb=0' : '1="'.$_SESSION['mgrRole'].'" OR sc.privatemgr=0').(!$docgrp ? '' : ' OR dg.document_group IN ('.$docgrp.')');
Solution:
        $access = ($this->isFrontend() ? 'sc.privateweb=0' : '1=\''.$_SESSION['mgrRole'].'\' OR sc.privatemgr=0').(!$docgrp ? '' : ' OR dg.document_group IN ('.$docgrp.')');

5.
Error: Failed ajax search
File: assets/snippets/ajaxSearch/classes/ajaxSearchRequest.class.inc.php
Line: 295
Content:
            $f.= ' SEPARATOR "," ) AS ' . $jpref . '_' . $joined['id'];
Solution:
            $f.= ' SEPARATOR \',\' ) AS ' . $jpref . '_' . $joined['id'];

6.
Error: Failed ajax search
File: assets/snippets/ajaxSearch/classes/ajaxSearchRequest.class.inc.php
Line: 304
Content:
                $f.= ' SEPARATOR "' . $joined['concat_separator'] . '" ) AS ' . $jpref . '_' . $joined['displayed'][$d];
Solution:
                $f.= ' SEPARATOR \'' . $joined['concat_separator'] . '\' ) AS ' . $jpref . '_' . $joined['displayed'][$d];

7.
Error: Failed ajax search
File: assets/snippets/ajaxSearch/classes/ajaxSearchRequest.class.inc.php
Line: 322
Content:
            $f.= ' SEPARATOR "," ), "||", ",") AS tags';
Solution:
            $f.= ' SEPARATOR \',\' ), \'||\', \',\') AS tags';

Please update it in the next ModX Evolution release.
Thank you.

**Comment by bossloper** [comment]
very old.. can be closed?

**Comment by dmi3yy** [comment]
Yes

Отправлено с iPhone

**Comment by modxuser** [comment]
@ghimawan can you close this issue please if it has been resolved
