### ISSUE TITLE
htmlspecialchars + windows-1251

### ISSUE THREAD

**Issue by Zevseg** [modxcms/evolution#385]
After updating to 1.0.15 was so:
![2014-12-09 18-16-53](https://cloud.githubusercontent.com/assets/2156427/5358720/b053c3a2-7fd0-11e4-8af3-5d3d40f34f8b.png)
Empty, but must be code in template\chunks

Problem is: htmlspecialchars + modx_charset=windows-1251.
Solution: replace all htmlspecialchars on $modx->htmlspecialchars
Files where just htmlspecialchars :
* access_permissions.dynamic.php
* mutate_htmlsnippet.dynamic.php
* document_data.static.php
* mutate_module.dynamic.php
* mutate_plugin.dynamic.php
* mutate_settings.dynamic.php
* mutate_snippet.dynamic.php
* mutate_templates.dynamic.php
* mutate_tmplvars.dynamic.php
* mutate_user.dynamic.php
* mutate_web_user.dynamic.php
* web_access_permissions.dynamic.php
* tmplvars.format.inc.php
* tmplvars.inc.php

PHP Version 5.4.35

**Comment by Jako** [comment]
Could you prepare a pull request with that?
