### ISSUE TITLE
Richtext mini with just basic icons

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#388]
Would be nice to have a custom TV and choose Richtext with basic icons (bold / link?).

Sometimes I need a textarea mini but need to add enters or links.
Don't want to explain client how to use < br> or < strong>
That can only be done with Richtext. But that one is pritty large.

So I was thinking of Richtext mini

With these options (or less): ``bold,italic,underline,separator,bullist,separator,hr,charmap,separator,link,unlink,anchor,separator,code``

**Comment by Deesen** [comment]
I have tried to add this feature into core just for fun, but maybe a custom-TV makes more sense for this purpose?

**Comment by Deesen** [comment]
https://github.com/Deesen/evolution/tree/richtextmini

To use/configure the new TV, a new plugin is nessecary: `/assets/plugins/tinymce/plugin.tinymce_mini.php`.

@dmi3yy What you think? Should I send pull-request?

**Comment by dmi3yy** [comment]
Yes but no only tinymce 
Tinymce4
Kceditor

Отправлено с iPhone

**Comment by Deesen** [comment]
Ok works with TinyMCE4: https://github.com/Deesen/tinymce4-for-modx-evo/tree/richtextmini

**Comment by Deesen** [comment]
@dmi3yy Which version? "CKEditor for Evo 3.5.2-alpha" from repository?

**Comment by fourroses666** [comment]
So how can I test/see this in Evo 1.1 RC2.
I have updated tinymce4 but there is no option for richtxt mini.
![richtxtmini](https://cloud.githubusercontent.com/assets/523389/12977119/1f5e1622-d0c9-11e5-81b4-f7f52aed7589.png)

**Comment by fourroses666** [comment]
Ah nvm, 
https://github.com/modxcms/evolution/pull/492

**Comment by fourroses666** [comment]
Hmm, I don't get it. How do we use it? I have updated to latest Evo development version.
Is it a Custom input? 
Nicer to have it below the RichText?  RichText (Mini)?

**Comment by Deesen** [comment]
You need to install an additional plugin which is not yet in the default install: `/assets/plugins/tinymce/plugin.tinymce_mini.php.` (for TinyMCE3 of the default-install). You can find the events and plugin-configuration for setup in this file. Properties like width, height and toolbar-buttons are set up then in the plugin-config then.

**Comment by fourroses666** [comment]
Ah, I'm using v4 on my testsite. I'll wait.

Thanks for the work on it, great feature :)

**Comment by Deesen** [comment]
No need to wait, its also updated ;-) : https://github.com/yama/tinymce4-for-modx-evo/commits/master

**Comment by fourroses666** [comment]
I did update that package and Evo 1.1 RC2 development. I must do something wrong?

Has it to do with this; updates 20 hours ago while commit 4 hours ago. 
It isn't pushed yet?

![hmm](https://cloud.githubusercontent.com/assets/523389/12980950/f3ac9f9c-d0de-11e5-945c-7a18f2c9326d.jpg)

**Comment by Deesen** [comment]
No I pushed 20 hours ago, Yama merged 4 hrs ago.. what is the error..? Just normal textareas instead of Richtextmini?

**Comment by fourroses666** [comment]
There is no option "RichText (Mini)" visible in the dropdown input type.

(I haven't installed the plugin)

**Comment by Deesen** [comment]
It is not merged yet: https://github.com/modxcms/evolution/pull/492 .. here you find the full ZIP: https://github.com/Deesen/evolution/archive/richtextmini.zip

**Comment by fourroses666** [comment]
I can it now in the dropdown, but there is a "bug".

It looks like a Textarea and the mm_rule (move to tab) I used doesn't work.

**Comment by Deesen** [comment]
Do you have the Mini-Plugin for TinyMCE4 installed? https://github.com/yama/tinymce4-for-modx-evo/blob/master/assets/plugins/tinymce4/plugin.tinymce_mini.php

I need to check MM later, I do not use it often.

**Comment by Deesen** [comment]
@fourroses666 If you like to play, it is ready. KCFinder works for me, when creating a link you can choose from Modx ressource-tree, and "documentDirty" works: https://github.com/Deesen/ckeditor4-modx-evo

@yama What do you think about CKEditor4´s plugin-structure for TinyMCE4? I also want to make the settings-routine dynamically so we can port the class to every Editor out there in future easily.

**Comment by yama** [comment]
> I also want to make the settings-routine dynamically so we can port the class to every Editor out there in future easily.

Nice idea.

**Comment by fourroses666** [comment]
@Deesen,
With or without MM rule its the same, not working for me:
```
mm_createTab('SEO', 'seo', '', '3', '', '100%');
mm_moveFieldsToTab('seo-titel', 'seo');
mm_moveFieldsToTab('seo-omschrijving', 'seo');
```

The file: plugin.tinymce_mini.php is in the tinymce4 folder.
I need to update some plugin settings prolly?
Not much free time to explore this actually, so I think I'll wait.

**Comment by Deesen** [comment]
Yes MM needs a small update. It only recognizes "richtext" but not "richtextmini". I will do it after weekend.
