### ISSUE TITLE
Update TinyMCE to 4.x

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#390]
Hope someone can do this sometime.
(I don't know the size of this job is an uge one.)

TinyMCE really could use an update.
The version 4.x is much better, there are quite a few fixes/improvements.
(paste from words/removing/headings etc)

http://www.tinymce.com/

**Comment by janniconl** [comment]
Would be nice indeed. +1

**Comment by fourroses666** [comment]
Evo needs more programmers/coders :sob:   
I had a look at Processwire but when looking at other CMS-es I really like to stick with Evo/Modx.
Its way easier to build sites with this awesome CMS.

**Comment by dmi3yy** [comment]
https://github.com/yama/tinymce4-for-modx-evo

**Comment by fourroses666** [comment]
yeah I have seen that :) 

can't wait to try it out! 
together with zome packagemanager these are the best updates Evo could get.

I have seen this: https://github.com/dmi3yy/modx-install-manager
is it a packagemanager?

**Comment by dmi3yy** [comment]
https://github.com/dmi3yy/modx-install-manager  its  first alpha version  now is not actual

test     extras module in my custom evo   -  its real repository with all what need

**Comment by fourroses666** [comment]
oke, will follow progress :+1:

**Comment by dmi3yy** [comment]
https://github.com/dmi3yy/tinymce4-for-modx-evo
all work but setting not in MODX Settings. 

http://modx.im/blog/addons/4153.html
