### ISSUE TITLE
Password Bug : If special chars in password => can't login

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#391]
After spending extensive time upgrading one of my complicated sites to the latest Evo version, I decided to change all passwords etc. to ensure a fully clean slate.

I did the usual back-up beforehand and went ahead and changed all passwords. After the manager showed the new password, I logged out as usual, closed all browser windows, cleared all cache and continued to log back into the system.

Then it happend - the password wasn't accepted "Incorrect username or password entered!" - huh huh above my head.

So - put the backup in place and started again - same happend again.

Then I started stripping the new password down in steps, this took ages sad

Eventually I found the culprit - it was an "&", adding an ampersand in the password breaks the system.

To ensure this didn't have anything to do with the upgrade I installed a fresh copy and the exact problem arose again.

Give it a try - use this as a password: 123&123 (but don't forget to do a DB backup first)

**Comment by Jako** [comment]
New passwords have to be checked for & (and maybe some other chars) before saving by MODX.

**Comment by yama** [comment]
OK, I intend to repair this problem.

**Comment by Jako** [comment]
Think there is some htmlspecialchars that is running during setting the password and not during compairing it or vice versa.

**Comment by modxuser** [comment]
This still seems to be an issue as can be read on the forum [here](https://forums.modx.com/thread/101626/unable-to-log-in-to-manager-after-upgrade)

**Comment by risingisland** [comment]
It looks like @Deesen changes were added, but either did not fix, or something else has broken this.
I just tested with `&password` and was not able to login, had to restore db.

**Comment by Deesen** [comment]
I tested it with all kinds of weird characters so something else broke it again.

**Comment by modxuser** [comment]
@Deesen oh well LOL

Are you around at the moment Dennis ?

Can I send you a mail ?

**Comment by nick0** [comment]
Just confirming I also had this problem when updating from 1.0.15 to 1.2.1.
I updated and then couldn't login. I tried it 3 times and the same problem.
I use a password generator to create passwords for me - turns out the 3 passwords did have an & symbol, the new one doesn't and works fine.

**Comment by risingisland** [comment]
Is anyone working on a solution to this? 
Im kinda stuck at the moment.

**Comment by risingisland** [comment]
I too am having a problem with users trying to use auto-generated passwords and not being able to enter again. 

I'm afraid to update any more sites now.
Is anyone working on this?

**Comment by Deesen** [comment]
Are your issues solved by replacing `$_REQUEST['password']` by `$givenPassword` at https://github.com/modxcms/evolution/blob/develop/manager/processors/login.processor.php#L183 ?

**Comment by risingisland** [comment]
YES, @Deesen that seems to work just fine.
Thank you for the fix.

**Comment by Deesen** [comment]
@yama What was the reason of using $_REQUEST instead of $givenPassword? Maybe for compatibility-reasons I do not know, we should check for both? Like

    $matchPassword = login($username,$_REQUEST['password'],$dbasePassword) || login($username,$givenPassword,$dbasePassword)

**Comment by risingisland** [comment]
@Deesen This appears to also works: [#1191](https://github.com/modxcms/evolution/pull/1191/files/56f53b8003fa3a7cc39a8fa4ed28e703798a5f5b..e8db6214065357b97be8452d862cc4557f569b2c)
Which of the two would you recommend?

**Comment by Deesen** [comment]
This [commit](https://github.com/modxcms/evolution/pull/1191/files/56f53b8003fa3a7cc39a8fa4ed28e703798a5f5b..e8db6214065357b97be8452d862cc4557f569b2c) is only code clean-up, or does it fix that issue too without https://github.com/modxcms/evolution/issues/391#issuecomment-274808976 ?

**Comment by risingisland** [comment]
OK, my mistake, needed a bit more testing. The cleanup did nothing to fix it.
Changing `$givenPassword` did correct the problem.

After a bit more testing, I found that the problem only arises when you change the password via the "Change Password" button in the upper right.
But, if you update the password via the "Manager Users", it seems to work ok?

**Comment by Deesen** [comment]
Yes I found that out too but I did not understand yet, where exactly is the difference. With https://github.com/modxcms/evolution/issues/391#issuecomment-274808976 the password gets accepted no matter if set by "Change Password" or via "Edit Manager User".

**Comment by bossloper** [comment]
Agree with @risingisland . If changing password from 'change password' button (top right) then it will not log in if special characters are used.

Looks like this line is a problem? https://github.com/modxcms/evolution/blob/develop/manager/processors/save_password.processor.php#L19

If I comment it out then it seems to work.

**Comment by Deesen** [comment]
Like seen in my past commits to solve this issue I added htmlspecialchars() everywhere to assure there are no issues using all kinds of weird signs for username and password.

I just tried again with username/password `!'"§$%&/ \()=?öäüß` which does not work anymore like before.

**Comment by bossloper** [comment]
Here when saving user: https://github.com/modxcms/evolution/blob/develop/manager/processors/save_user.processor.php#L111
password does not use htmlspecialchars() ?

Is htmlspecialchars() acutally needed, as long as it is either everywhere or not at all?

**Comment by risingisland** [comment]
Just created a clean install with the latest dev, and am having continuing problems with this.

In line 183 of "manager/processors/login.processor.php" I initially thought that it was solved by replacing `$_REQUEST['password']` by `$givenPassword `, but with a clean install, found this giving the opposite results,  if pass set via User Manger, it will not work.

I then created yet another fresh install by replacing `$_REQUEST['password']` with @Deesen above suggestion/question, 
`$matchPassword = login($username,$_REQUEST['password'],$dbasePassword) || login($username,$givenPassword,$dbasePassword)`, 
and as far as I can tell, this is working in all areas.

**Comment by risingisland** [comment]
New update, new problem:

At install, if admin password contains special characters, upon first login, not excepted.

Reset pass via phpadmin to one that contains no special characters, login to manager, change password to on that does contain special characters, and with the above fix, all is fine.

What is different about how the install pass is saved verses admin?

**Comment by risingisland** [comment]
Is this something that will eventually be resolved?
I think it has been forgotten about.

**Comment by dmi3yy** [comment]
move to new repo
