### ISSUE TITLE
Full url and phpthumb don't work

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#393]
phpthumb doesn't work with full url, I have a custom TV where I add the full url like: http://www.domain.com/assets/images/image1.jpg

``<img src="[[phpthumb? &input=`[*image01*]` &options=`w=80,h=80,zc=1`]]" width="80" height="80" />``

the output is the "no-image" thumb.

**Comment by Jako** [comment]
phpthumb can't work with full urls.
