### ISSUE TITLE
enhancement: Bootstrap Manager

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#411]
anyone is interested to rebuild the manager with a responsive bootstrap grid?
http://youtu.be/4LqHw8pGBfQ

https://github.com/Nicola1971/evoBSframes

http://forums.modx.com/thread/96473/evo-boostrap-manager---step-1-done/#dis-post-522160

**Comment by pmfx** [comment]
Two thumbs up!

**Comment by janniconl** [comment]
Nice idea! Make sure you use the latest bootstrap.
Will make it much easier to make custom manager themes.

**Comment by dmi3yy** [comment]
If  use my custom  
all this  can do   without change core files ) 
https://github.com/dmi3yy/modx.evo.custom/tree/develop/manager/media/style/D3X

i do this  in Evolution  for 1.1

**Comment by Nicola1971** [comment]
Thanks, but i need some help from a js/php coder, because i'm just a designer. 
Everything I've done it's only html/css work.
@ janniconl 
yes it's the latest Bootstrap v3.3.2

@dmi3yy 
We must talk :+1:

**Comment by Nicola1971** [comment]
@dmi3yy 
mixed with my modxflat theme for your custom-evo:
https://github.com/Nicola1971/BSxFLAT

**Comment by mrhaw** [comment]
Cool! :+1:

**Comment by fourroses666** [comment]
Nice :hammer:

**Comment by bossloper** [comment]
Like it!

**Comment by Nicola1971** [comment]
@dmi3yy  
The first beta was using the ***old Evolution menu***, because to customize the ***Evo-custom menu***, you need to change classes hacking ***menu.class.inc.php*** (inside the "includes" folder) 

***Yesterday I've found a really simple solution*** :)
Just duplicate the menu.class.inc.php inside the Theme folder!!

The new Beta 1.2 is based on the new evo-custom menu 
https://github.com/Nicola1971/BSxFLAT

**Comment by Nicola1971** [comment]
Note: we can add support to Bootstrap to the whole manager just adding some classes

ie:

* .btn .btn-default/alert/warning/info... to all .actionbuttons
* .content to .sectionBody divs
* .form-control to all input forms

..etc...

**Comment by fourroses666** [comment]
https://github.com/modxcms/evolution/issues/502

![442b43](https://cloud.githubusercontent.com/assets/523389/13847752/f219f108-ec4e-11e5-962b-aafc9c539600.png)
