### ISSUE TITLE
Update to php 5.5.9

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#413]
I have a hosting which is going to upgrade their servers soon.
PHP is getting 5.5.9 and I would like to know if this works with Evo.

**Comment by fourroses666** [comment]
Or do I have to use this "hack"

http://forums.modx.com/thread/87015/evo-doesn-039-t-work-with-php-5-5-x#dis-post-480279

**Comment by Haprog** [comment]
This is no longer a problem. MODX 1.0.15 (Evo) works with PHP 5.5 and even 5.6 without any hacks. This was only a problem with some older versions of Evo. I just tested running MODX 1.0.15 frontend and backend on PHP 5.5.22 and 5.6.6 and I didn't get any errors or warnings.

**Comment by dmi3yy** [comment]
In config.inc.php 
Need change. Mysql to mysqli 
For beat work

Отправленно с телефона
www.dmi3yy.com

**Comment by fourroses666** [comment]
thanks!

**Comment by Haprog** [comment]
No, you don't even need to change database_type in config.inc.php to "mysqli". It will still work with "mysql". I did not change it and worked perfectly. Although the mysql extension/module in PHP is "deprecated" it is still working even in PHP 5.6 and using mysqli instead would be the suggested thing to do.

**Comment by Haprog** [comment]
I don't know how well the mysqli support of MODX has been tested yet, but if it works without problems then by all means use mysqli for a more modern MySQL API.

**Comment by dmi3yy** [comment]
I tested mysqli all work fine 
Exept  extras without dbapi  and with mysql_ in code 



Отправленно с телефона
www.dmi3yy.com

**Comment by dutchman1** [comment]
After the update I get the errors:
File: /manager/includes/document.parser.class.inc.php(957): eval () 'd code
Line: 412

Backtrace

1 DocumentParser-> executeParser ()
index.php on line 144
2 DocumentParser-> prepareResponse ()
manager / includes / document.parser.class.inc.php on line 1551
3 DocumentParser-> parseDocumentSource ()
manager / includes / document.parser.class.inc.php on line 1626
4 DocumentParser-> evalSnippets ()
manager / includes / document.parser.class.inc.php on line 1443
5 DocumentParser -> _ get_snip_result ()
manager / includes / document.parser.class.inc.php on line 1005
6 DocumentParser-> evalSnippet ()
manager / includes / document.parser.class.inc.php on line 1028

Any help is appreciated.

**Comment by yama** [comment]
Would you tell  me the snippet name?

**Comment by dutchman1** [comment]
Oh, sorry, it Breadcrumbs

**Comment by dutchman1** [comment]
I updated Breadcrumbs once again and now everything works, but ?phpMyAdmin=xxxxxx  still appears at the end of each link.

**Comment by pragneshkaria** [comment]
How to know , which version of EVO is running on my server.

**Comment by Zevseg** [comment]
/www/manager/includes/version.inc.php

**Comment by Haprog** [comment]
If you can log in to the manager, you can also see the MODX Evo version in the top right corner of the manager interface right next to the Logout link. And you can also see it along with some more information about your system on the "Reports / System Info" page.
