### ISSUE TITLE
Security Enhancement

### ISSUE THREAD

**Issue by amdbuilder** [modxcms/evolution#414]
It might be worth adding the following code in a .htaccess file located within the assets directory.  It should help improve security.

`<FilesMatch ".*\.(php|tpl)$">
   Order allow,deny
   Deny from all
</filesmatch>`

**Comment by Jako** [comment]
This should cause some issues with TinyMCE and other extras that call php files in assets folder but it is more secure to allow them with a separate config and deny all other.

**Comment by janniconl** [comment]
Yep, implemented this a few times but like Jako said, it broke some of the extras like MultiTV.

**Comment by Jako** [comment]
You could try to allow multitv.connector.php and multitv.module.php with an own .htaccess in assets/tvs/multitv/

```
# Allow to call multiTV connector and module
<FilesMatch "multitv\.(connector|module)\.php$">
Order allow,deny
Allow from all
</filesmatch>
```

Hope that works.

**Comment by janniconl** [comment]
Ok thx! I remember some other extras not working either though. cant remember which :P

**Comment by bossloper** [comment]
can be closed?

**Comment by modxuser** [comment]
@amdbuilder can you close this issue please if it has been resolved
