### ISSUE TITLE
makeUrl fails with site start and query string 

### ISSUE THREAD

**Issue by TimGS** [modxcms/evolution#415]
e.g. on http://localhost/dev/ calling makeUrl($site_start, '', 'a=1') returns http://localhost/dev/&a=1.

This is with friendly urls off.

Clipper's makeURL (virtually unchanged i.e. fundamentally the same as 1.0.6 and not 'refactored') works OK, implying it's a bug introduced since 1.0.6.

**Comment by modxuser** [comment]
@TimGS can you close this issue please if it has been resolved
