### ISSUE TITLE
Clear Cache Script for deployed updates

### ISSUE THREAD

**Issue by CharlesSellers** [modxcms/evolution#416]
Hello, 

I'm struggling to find a solution to this. 

We're running modx evo for a client of ours who is running their site on AWS. Every time we push an update we have to log into the admin and manually clear the cache. As the site auto scales this can cause issues.

We can write hooks with amazon via .ebextensions however, i have no idea which file we should execute, if we can execute any. 

Is it possible to clear the cache without having an active session and if not is there a script that can authenticate a user?

Kind regards
Charles

**Comment by Jako** [comment]
This post could be a good start: http://forums.modx.com/thread/38309/support-comments-for-modxapi-library?page=3#dis-post-217158

Don't know if this extra is still working in 1.0.15: http://modx.com/extras/package/modxapilibrary

**Comment by pmfx** [comment]
Hi Charles.
I have used this code as "clearCache" snippet some time ago and it worked fine. Code can be hooked to an event via plugin or used the way you think will be best for it. Haven't tested it on 1.0.15 though.

<?php
include_once $modx->config['base_path']."manager/processors/cache_sync.class.processor.php";
$sync = new synccache();
$sync->setCachepath("assets/cache/");
$sync->setReport(false);
$sync->emptyCache();
?>

**Comment by Eoler** [comment]
Calling `$modx->clearCache('full');` should be enough if document parser is loaded:
https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L2309

**Comment by CharlesSellers** [comment]
Brilliant, thanks everyone, its working now.
