### ISSUE TITLE
export.class.inc.php

### ISSUE THREAD

**Issue by quanglam4591** [modxcms/evolution#417]
1/ In function [makeFile], the return is 'no_retrieve' but the catched case in function [run] is 'failed_no_retrieve'

2/ In function [run], the switch($status) needs break; lines for cases.

3/ Function [curl_get_contents] does not support https and authentication.

**Comment by bossloper** [comment]
can be closed?

**Comment by dmi3yy** [comment]
Yes

Отправлено с iPhone

**Comment by modxuser** [comment]
@quanglam4591 can you close this issue please if it has been resolved
