### ISSUE TITLE
Upload files problem max size on 1.0.15

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#418]
On evo 1.0.14 no problems, on 1.0.15 when uploading a 1.79MB file I get: File is to big (max 1048576 Bytes)

When uploading evo 1.0.14 manager/media/browser/mcpuk/ it starts to work again.

There must be a bug or restriction set in 1.0.15..

**Comment by bossloper** [comment]
The 'File Manager' -> 'Maximum upload size' System option is now honoured in 1.0.15. You need to increase that parameter if you need to upload larger files.

**Comment by fourroses666** [comment]
Sounds good, where is that located?

**Comment by fourroses666** [comment]
Oké thanks it works, just added a 0 behind it.

The default needs to be increased. 1MB is a bit small for files!
Can this be set in Evo 1.0.16 / 1.1 ?

**Comment by bossloper** [comment]
Added request to update default upload size
https://github.com/modxcms/evolution/pull/419

**Comment by fourroses666** [comment]
thanks boss
