### ISSUE TITLE
Updating Weblink

### ISSUE THREAD

**Issue by digitalime** [modxcms/evolution#420]
Saving a weblink resource does not seem to update the actual value of the 'weblink' field in the database. It remains the same as the one given when the resource was originally created.

**Comment by Deesen** [comment]
Cannot recreate that issue.

**Comment by digitalime** [comment]
To recreate issue:

1. Create Resource
2. Save Resource
3. Change Resource Type to Weblink
4. Set Weblink value to http://foo.bar
5. Save Weblink and preview
6. Page redirects to http://foo.bar as expected
7. Go back and edit weblink
8. Change Weblink value to http://something.else
9. Save weblink and preview
Expected Behaviour: redirects to http://something.else
Actual Behaviour: redirects to http://foo.bar

Tested on Chrome 50, FF 38, Safari 9.1.1. All with and without browser cache activated.
Modx 1.1RC2

**Comment by Deesen** [comment]
Thanks for explaining. I tested it again and I´m 100% sure this is a browser cache-issue. FF for example is caching the destinations of 301/302-redirections, for some browser its harder to clean this cache. For FF I am using the addon "Empty cache button".

Before clearing cache I get redirected to http://foo.bar . Immediately after clearing cache I get redirected to http://something.else like "expected".

**Comment by bossloper** [comment]
can be closed?

**Comment by digitalime** [comment]
Yes. Thanks. 

Typed with big fingers on a tiny keyboard

**Comment by bossloper** [comment]
@digitalime  ... that's for you to do. 'close issue' or 'close and comment'
