### ISSUE TITLE
Delete git tags 

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#425]
Please remove the tags are not related to the main repositary
Some of them are my fault ..
7d66530c6c4c3ec1078da68525cf7986c30ad5a3        refs/tags/ddGetMultipleField_v.3.1
cf591917c035a8d25b3b4e23578f5030f263b207        refs/tags/ddTools_v.0.13
ed0d697069478f3db2ac7586902dda8b39431db8        refs/tags/Forwhat
65853a9f92247f3f21dde93f307208c3b62c909a        refs/tags/ManagerManager_v.0.6.2
1fce546fc38366607084bd05936e1be706f4d044        refs/tags/PHP_modifiers_v.14.11.28
ed2fc045228e88b8a085dad52d1e534534fdcd22        refs/tags/PHP_modifiers_v.14.11.28^{}
1bcc38ea15a64bfffbd6b96e9a72e6874d5032e6        refs/tags/Useless
Other - from other forks
see 
https://github.com/modxcms/evolution/tags

**Comment by Jako** [comment]
Done
