### ISSUE TITLE
Remove the dropdown and add a New tab

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#427]
I like this, remove the dropdown and add a New tab.
should be default
https://github.com/manse/tbfix.modx

**Comment by Haprog** [comment]
I haven't tried this, but this seems to remove the ability to do "Save and close" which is the current default.

I think it's a good idea to replace the current dropdown with something better, but I think it would be better to do as a "split button dropdown" like http://getbootstrap.com/components/#btn-dropdowns-split and have the default action be configurable via a site setting. And still be able to select and execute any of the other actions via the down arrow (it would still be one click less to run an alternate action compared to current separate dropdown).

Also just the text "Another" on the button is not good enough because it's not immediately obvious to a new user what it does.

**Comment by dmi3yy** [comment]
I do not like drop-down list
even in REVO made easy.
It may want to just change the path to the select to checkboxes(styled)

**Comment by pmfx** [comment]
I like Haprog's idea. 
Save (default action Save and continue) with dropdown (Save and close; Save and add another). 
Then Preview button, Cancel button, More button with Duplicate and Delete in dropdown.

**Comment by dmi3yy** [comment]
i think need button without text )  and with title  it will be small place

**Comment by fourroses666** [comment]
I personally don't need "Save and close" so only adding a "New page" button will do it for me.
The "bootstrap" dropdown looks good.

**Comment by dmi3yy** [comment]
I use "Save and close"  then need choice what need do )

**Comment by Haprog** [comment]
"Save and close" is important at least for sites with many active manager users since the document is "locked" to the user that has it open. So it makes sense to still be able to have save and close as default, but it is good to have an option in site settings to change the default.

**Comment by MrSwed** [comment]
Haprog idea looks good and to cater Dmitry :) , make a little changes and add some configuration options.
for example, to make the ability to customize the display of all other variants for  elements (or the whole menu) when you hover at it.  Ability to specify what items are always visible, depending on the preferences.

**Comment by dmi3yy** [comment]
I think better do like this: 
http://take.ms/B94MH

**Comment by pmfx** [comment]
I dont think that "only icons" is a good way. Hard to read an icon. Icons should always be used with text labels or not used at all. Haprog and MrSwed are right in my opinion and described how it should work. I vote for that :)

**Comment by fourroses666** [comment]
For info; 
I have removed all the icons on my custom styled evo manager. 
Don't like them over there, text-only is clear.
![custom-style](https://cloud.githubusercontent.com/assets/523389/8183916/86b37ce0-143b-11e5-8df1-f9de4322144c.png)

**Comment by pmfx** [comment]
@fourroses666 exactly! Icons there are just taking space.

**Comment by dmi3yy** [comment]
Group SAVE button like   (Save  [N] [A] [C])  then will be small and in green style.

**Comment by fourroses666** [comment]
do you mean something like this dmi3yy ?
![dim3y](https://cloud.githubusercontent.com/assets/523389/8184444/c22d7e4e-143e-11e5-920b-7ee2db246231.png)

**Comment by dmi3yy** [comment]
Yes :)

**Comment by fourroses666** [comment]
or this:
![example](https://cloud.githubusercontent.com/assets/523389/8185235/5dd53eb4-1443-11e5-8fd5-e670d6ae99e1.png)

**Comment by dmi3yy** [comment]
+1  click   is no good  better 1

**Comment by fourroses666** [comment]
![option2](https://cloud.githubusercontent.com/assets/523389/8185467/e9f11778-1444-11e5-86c8-e1b6982b42e0.png)

**Comment by fourroses666** [comment]
![hmmz](https://cloud.githubusercontent.com/assets/523389/8185537/4e46ab2a-1445-11e5-99fb-49b764f837c1.png)

**Comment by fourroses666** [comment]
last version :-0
![last1](https://cloud.githubusercontent.com/assets/523389/8185647/dc70bf76-1445-11e5-8322-62ea5d521bd7.png)

**Comment by pmfx** [comment]
I preffer this:
![e9f11778-1444-11e5-86c8-e1b6982b42e0](https://cloud.githubusercontent.com/assets/10888055/8187141/987e460e-144e-11e5-9acd-f48a4c6c32e3.png)

**Comment by dmi3yy** [comment]
Its good if save action in session for next action 

I

Отправлено с iPhone

**Comment by fourroses666** [comment]
yea like that one. remember last action

**Comment by Haprog** [comment]
+1 for last picture by pmfx

**Comment by MrSwed** [comment]
+1 for remember last action (set it to default action)

**Comment by bossloper** [comment]
also +1 for remember last action

**Comment by Deesen** [comment]
For those who missed it, with my plugin´s option "Extend Save-Button" it is divided into 3 single buttons: https://github.com/Deesen/modxEvo_scrollFix/

**Comment by dmi3yy** [comment]
want test one more time 

with evoBabel  dont start ) 
test on another project

**Comment by pmfx** [comment]
@Deesen Your plugin works great! Thank you. I think those features should be included in MODX by default. Love it. Thanks again.

**Comment by dmi3yy** [comment]
Will be great fix for default theme)

**Comment by Deesen** [comment]
@pmfx Glad you like it! Any issues pls let me know!
@dmi3yy I tried to install/setup evoBabel but failed, is there any english documentation?
