### ISSUE TITLE
Problem with a plus-sign in email address with forgot manager password

### ISSUE THREAD

**Issue by kulmjens** [modxcms/evolution#428]
Hi there,
the email address I have in my system conf has a plus-sign like `example+example@example.com`. When I entered this address into the forgot manager password email field, MODX responded with "Email not found" and no password mail was sent, because the plus-sign wasn't escaped in URL.

By adding `encodeURIComponent()` and changing line 26 of `assets/plugins/forgotmanagerlogin/plugin.forgotmanagerlogin.php` from

```
<button id="FMP-email_button" type="button" onclick="window.location = 'index.php?action=send_email&email='+document.getElementById('FMP-email').value;">{$_lang['send']}</button>
```

to

```
<button id="FMP-email_button" type="button" onclick="window.location = 'index.php?action=send_email&email='+encodeURIComponent(document.getElementById('FMP-email').value);">{$_lang['send']}</button>
```

seemed to solve the problem.

**Comment by bossloper** [comment]
This is fixed - can be closed.

**Comment by modxuser** [comment]
@kulmjens can you close this issue please if it has been resolved
