### ISSUE TITLE
Error image in images folder

### ISSUE THREAD

**Issue by barsproger** [modxcms/evolution#429]
When i have error image ( attached as file ) in images folder,  browser image manager don`t work.

See line 70

 if ($type == IMAGETYPE_PNG)
                imagealphablending($image, false);

Path: /manager/media/browser/mcpuk/lib/class_gd.php

My raw log.

URL: /manager/media/browser/mcpuk/browse.php?type=images&lng=ru&act=init

string(72) "/var/www/u0075918/public_html/spa-orenburg.ru/assets/images/banner23.png"
<br />
<b>Warning</b>:  imagealphablending() expects parameter 1 to be resource, boolean given in <b>/var/www/u0075918/public_html/spa-orenburg.ru/manager/media/browser/mcpuk/lib/class_gd.php</b> on line <b>73</b><br />
{"tree":{"
![banner23](https://cloud.githubusercontent.com/assets/7596679/8405729/dae9404a-1e6f-11e5-81cb-dc6f21c6c448.png)

**Comment by modxuser** [comment]
@barsproger can you close this issue please if it has been resolved
