### ISSUE TITLE
Add opportunity of edit template from file

### ISSUE THREAD

**Issue by keslo** [modxcms/evolution#431]
Hello!
Is it possible to add the ability to edit the template file? At the moment, I use this opportunity:

```
# code in template in MODX
[!includeFile? &file=`assets/templates/nameTemplate/index.html`!]

# Snippet to include files from filesystem
<?php
# [[includeFile? &file=`assets/templates/mytemplate/file.html`]]

if ( !isset($file) || $file== "" ) return "No file specified."; //check if there's a file given.

//Start the buffer
ob_start();

//include
include $file;

//get contents from the buffer
$ob_contents = ob_get_contents();

//and kill/delete the buffer
ob_end_clean();

//return it to MODx
return $ob_contents;
?>
```

In this embodiment, caching does not work and there are other bad moments. Can anyone have a better solution?
Edit site template as a file is very useful when developing "on the fly".

**Comment by MrSwed** [comment]
try [loadelement](https://gist.github.com/AgelxNash/9239062)

**Comment by keslo** [comment]
Thanks for the link. But primarily interested in downloading the file templates.

**Comment by pmfx** [comment]
What "other bad moments" there are?
Why did you disabled caching for this? Should work just fine with [[]]. The only need for this is to see changes immediately after updating template file on FTP, right?

**Comment by Deesen** [comment]
And to solve such bad moments you could develop a plugin, that scans all files/sub-directories of "/assets/templates/" for the newest file and let it clear the cache, in case a new file was found.

I started to use "loadelement" and "includeFile" too, so such automatic ClearCache would be comfortable.

**Comment by MrSwed** [comment]
@keslo Да )

**Comment by MrSwed** [comment]
also see https://github.com/mapledesign/modx-component-sync

**Comment by dmi3yy** [comment]
Now we do new plugin for edit from file 

Отправлено с iPhone
