### ISSUE TITLE
Deprecated core functions - Needed for Ditto

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#432]
References:
http://tracker.modx.com/issues/9720
https://github.com/modxcms/evolution/commit/ab52e6335b3538cff4afc00a7689975d2cdef3f1

Ditto TagList extender requires the makelist function that has been added to the deprecated functions.

See forum post: http://forums.modx.com/thread/97367/ditto---deprecated-php-code-makelist#dis-post-526702

Attached to the forum post is a zip file with the modifications required for Ditto

**Comment by yama** [comment]
Nice approach. Thanks
