### ISSUE TITLE
bad SEO when using phpthumb

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#434]
When I'm using phpthumb for my website the image is saved into folder /assets/cache/
In robots.txt there is a rule: Disallow: /assets/cache/

So the images are not found by Google :-1: 

I also hate the fact when replacing an image with the same name its not being updated.
The name isn't great also for SEO. When I call an image  nike-shoes-green its renamed like 400x300-nike-shoes-green.4af.jpg
is it possible to remove the size on front?

**Comment by fourroses666** [comment]
maybe we can change the folder and add an option to remove the size on front of the image?

**Comment by Nicola1971** [comment]
Ho do you manage multi size images (ie: one for ditto list and one for the article page) without the size suffiz?
Furthermore, image size information are essential for multi size Responsive (picturefill) scripts

**Comment by Nicola1971** [comment]
About Disallow: /assets/cache/  in 1.015 robot.txt

Can we fix in 1.0.16 with evo custom robot.txt?
https://github.com/dmi3yy/modx.evo.custom/blob/master/robots.txt

**Comment by dmi3yy** [comment]
yes

**Comment by pmfx** [comment]
When is 1.0.16 going to be released BTW?

**Comment by fourroses666** [comment]
Can at least this be added in robots.txt?

Allow: /assets/cache/images/

**Comment by Nicola1971** [comment]
@dmi3yy can we add these robot.txt lines from evo.custom in Evo 1.1? 
so we can close this issue ;)

**Comment by fourroses666** [comment]
yes please :) images in that folder needs to be found on internet

**Comment by dmi3yy** [comment]
done
