### ISSUE TITLE
evo 1.0.15: manager can't edit / create document (manager/index.php?a=27&id=17 500 (Internal Server Error))

### ISSUE THREAD

**Issue by modxcustomize** [modxcms/evolution#436]
Hi

just have updated evo 1.0.8 (which actually was very good working) to 1.0.15.

Seems all functions work but admin can't edit or/and create document

console logs examples:
GET http://www.site123.com/dev/manager/index.php?a=27&id=17 500 (Internal Server Error) index.php?a=1&f=tree:293 
GET http://www.site123.com/dev/manager/index.php?a=4 500 (Internal Server Error) onclick @ index.php?a=1&f=tree:381 

It's been tested with friendly urls OFF and disabled modRewrite in manager/ and root.. Tests with Friendly URLs ON also the same (bad)

The same issues is when MODX EVO is in the root of the domain and when it's in the subfolder like /dev

Please help

**Comment by pmfx** [comment]
What PHP and MySQL version there is?

**Comment by modxcustomize** [comment]
hi

it's PHP:  native (5.3)  and MySQL Server version: 5.5.42-cll - MySQL Community Server (GPL) Protocol version: 10

**Comment by pmfx** [comment]
Try replacing line 93 in `/manager/includes/extenders/dbapi.mysql.class.inc.php` with this:

```php
else            $this->conn = @mysql_connect($host, $uid, $pwd, true);
```

I remember that it helped me in some server configuration when 500 happened.

**Comment by modxcustomize** [comment]
Hi Piotr,
thanks for your suggestion but it proved to be already the same code on that line - perhaps my download version of 15th release already had this fix - I have downloaded somewhere by june '15

**Comment by pmfx** [comment]
Ah, OK. So maybe check server error log? Maybe there will be more details about it.

**Comment by janniconl** [comment]
Did you try removing the .htaccess or using the original .htaccess?

**Comment by modxcustomize** [comment]
Hi Piotr,
yes, I just can't find the error log on this hosting. Let me check if the error log file is described in the phpinfo ;-)


Hi Jan,
yes, I tried all .htaccess options: with the file and without it + with SEO FURL on and OFF - no progress...

**Comment by modxcustomize** [comment]
Hi all,
I could not find the error log saved in the modx dir and server's error_log on this shared host even investigating the phpinfo()..

But, when I try to stop each line in the index.php I can't do it after line:288 
so the code on line 289 with: include_once "actions/mutate_content.dynamic.php";
seems errors; and when I debug that included file: actions/mutate_content.dynamic.php 
I can't stop the code after line: 496 so the following code dies:
// invoke OnDocFormPrerender event
$evtOut = $modx->invokeEvent('OnDocFormPrerender', array(
    'id' => $id,
	'template' => $content['template']
));

Do you know why?

**Comment by pmfx** [comment]
Strange. Did you try reuploading all core MODX files like /manager/?

**Comment by modxcustomize** [comment]
yes, so that's not an issue at all. I am looking into OnDocFormPrerender events thinking of a tv params parsing per document..

**Comment by modxcustomize** [comment]
so this issue happened because all plugins and snippets used modxca_BASE_PATH instead of MODXBASE_PATH.

this could happen because in the config file for the dev server I changed the db prefix from  modx to modxca : thus I believe this variable value "modxca" got used everywhere when I was changing the database dump from modx to modxca without restricting the capitals match MODX

Sorry
