### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by luigif** [modxcms/evolution#438]
The parser in Evo 1.0.15 uses deprecated form of preg_replace for PHP Version 5.5.

When enabling log of DEPRECATD PHP errors:

PHP error debug
Error : preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead
ErrorType[num] : 	DEPRECATED[8192]
File : 	manager/includes/document.parser.class.inc.php
Line : 	1267
Source : 	$documentSource= preg_replace($in, $out, $documentSource);

**Comment by bossloper** [comment]
I see yama has a fix here?
https://github.com/yama/evolution-jp/blob/revision/manager/includes/document.parser.class.inc.php

I also found this, no idea who wrote it, or if it works correctly?
http://pastebin.com/2fAGjfkW

**Comment by dmi3yy** [comment]
fixed
