### ISSUE TITLE
DB dumps do not disable foreign key checks

### ISSUE THREAD

**Issue by TimGS** [modxcms/evolution#440]
The DB dumps created by the backup tool do not disable foreign key checks. 

As such, the SQL files created will often fail on import if foreign keys exist in the relevant (custom) tables.

-- Tim.

**Comment by Deesen** [comment]
Is it just about adding a "SET FOREIGN_KEY_CHECKS=0;" before the DROP-Statements and "SET FOREIGN_KEY_CHECKS=1;" after them? Or is the solution more complicated?

http://stackoverflow.com/questions/3476765/mysql-drop-all-tables-ignoring-foreign-keys

**Comment by TimGS** [comment]
I _think_ that should be fine.

If you look at an SQL dump produced by mysqldump you will see it saves the original FOREIGN_KEY_CHECKS setting instead of assuming it was 1.

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0

and at the end...

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS

-- Tim.

**Comment by Deesen** [comment]
It is added now.
