### ISSUE TITLE
eForm error report TPL

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#441]
I would like to make my own error report like:
```[!eForm? &errorTpl=`chunk` ```

chunk could look something like:
```<div class="">There are some errors in these fields.. [+errorfields+]</div>```

**Comment by kp52** [comment]
I think you can achieve what you want using the existing parameters and placeholders. 

The validation message format can be changed in the language file: `$_lang["ef_validation_message"]`

The validation itself can be modified using `&eFormOnValidate` to read the error messages and merge them into a chunk with `$modx->parseChunk()`.

**Comment by fourroses666** [comment]
hmm, in the lang file ```$_lang["ef_validation_message"] = "";``` 
It has default strong and break: ```<strong> --here message-- </strong> <br>``` which you can't correct/remove.
also it shows this for every form. would have liked it was possible by custom errorTpl=`` and validationTpl= `` but I can live with it. don't want to be doing any snippets for the validate.

**Comment by janniconl** [comment]
Isnt there already a parameter for this? `&errorTpl=chunk` Not well documented though. See: https://github.com/modxcms/evolution/blob/develop/assets/snippets/eform/snippet.eform.php#L90

**Comment by fourroses666** [comment]
Yea that works lol. Good find Jannico !

**Comment by fourroses666** [comment]
Ah, [+ef_required_list+]
