### ISSUE TITLE
My webiste is being hacked - modx version is 1.0.7

### ISSUE THREAD

**Issue by anahitdev** [modxcms/evolution#443]
My webiste is with modx version 1.0.7 and it is being hacked rapidly.How I can solve this?Also what is the best way of updating modx version.

Swift response is highly appreciated  so I can advice my client.

Thanks!

**Comment by dmi3yy** [comment]
update to 1.0.15  
upload files and run install 

p.s. do backup before

**Comment by anahitdev** [comment]
Where to upload files?on the same place where there were core files?Also update will mean rechange all stuff of the code?

**Comment by dmi3yy** [comment]
yes

**Comment by anahitdev** [comment]
It will overwrite the existing files of the old hacked version?

**Comment by dmi3yy** [comment]
yes

**Comment by anahitdev** [comment]
So I dont have any other way than updating the verison cause update will mean built the webiste again right?

**Comment by dmi3yy** [comment]
no you only update system files  all content will be saved

**Comment by Haprog** [comment]
Just updating to a newer version of MODX probably does not remove the backdoors (malicious code) that might have been installed by a hack. The hack(er) has probably uploaded at least some file or multiple PHP files mith malicious code which can be used to remotely run commands and hack the site again unless they are cleaned up. It is also possible that the database contains malicious code in MODX snippets or plugins after a hack.

Unfortunately there is no easy or sure way to recover from a hack without completely wiping the site files and database and installing from scratch or backups (though it might be hard to know for sure if some backups already contained malicious code injected by a hack, and the hacker might have just recently started to make use of it).

You could also try to find all the malicious code or files on the site yourself and remove/fix it but that might be really hard unless you have some experience doing it. And if you do so, you can never be quite completely sure that you found all of the malicious code even if you found some of it.

If you run any sites with MODX Evolution you should follow security announcements here http://forums.modx.com/board?board=295

MODX 1.0.15 is already almost a year old and it fixes security bugs that affected all previous versions. http://forums.modx.com/thread/94952/multiple-vulnerabilities-xss-remote-command-injection#dis-post-514187

**Comment by dmi3yy** [comment]
after update use https://revisium.com/ai/ for check backdoors (malicious code) and all be ok

**Comment by Haprog** [comment]
And just so you know MODX 1.0.7 was released almost 3 years ago (in 2012) and there have been multiple important security updates since then. You should keep your software up to date.

**Comment by anahitdev** [comment]
Yes thank you very much for the info!
