### ISSUE TITLE
Is 1.0.16 comming soon?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#448]
Wonder when there will come an update.

**Comment by dmi3yy** [comment]
I think will be 1.1

Next week  public 1.1 RC 

Отправлено с iPhone

**Comment by fourroses666** [comment]
oke thanks! :+1:

**Comment by fourroses666** [comment]
just let me know when we can start testing!

**Comment by dmi3yy** [comment]
ok )  

--  
Lukianenko Dmytro
Web developer  
http://dmi3yy.com


четверг, 12 ноября 2015 г. в 18:10, Marc написал:

**Comment by yama** [comment]
ok, thanks

**Comment by pmfx** [comment]
Wow, thats a great news! Is there changelog of upcoming update somewhere?

**Comment by janniconl** [comment]
Great news! Also looking forward to the change log.

**Comment by fourroses666** [comment]
Is there a default installed Package Manager in the new version of Evo?

**Comment by dmi3yy** [comment]
In my custom i Use Extras by default but in off version i thin we can add package Manageer

**Comment by fourroses666** [comment]
Any updates? :santa:

**Comment by pmfx** [comment]
Looks like everybody went on holiday or something :christmas_tree:

**Comment by dmi3yy** [comment]
Soon ;) 

Want test on php 7 , but need found some time for this 

Отправлено с iPhone

**Comment by fourroses666** [comment]
:+1:

**Comment by fourroses666** [comment]
Can you please add a line to:
/assets/plugins/managermanager/mm.inc.php

Add the line (20): 
global $mm_version;

(Right above: $mm_version = '0.6.2';)

For YAMS to not break the tabs.

**Comment by mgzawlinoo** [comment]
Hi, Is there a pagination for ddmultiplefields , at next update?

**Comment by dmi3yy** [comment]
I prefer to use multiTV
http://jako.github.io/multiTV/

**Comment by MrSwed** [comment]
@mgzawlinoo 
https://github.com/DivanDesign/MODXEvo.snippet.ddGetMultipleField
https://github.com/DivanDesign/MODXEvo.plugin.ManagerManager

**Comment by dmi3yy** [comment]
https://github.com/modxcms/evolution/releases/tag/v.1.1RC

**Comment by dmi3yy** [comment]
Wait for testing )

**Comment by fourroses666** [comment]
First (upgrade) test was oké! Just on a simple site.
Had a weird re-login when deleting a plugin one time but could be some cache issue.
Didn't happen after retry.
No default PackageManager? Would love to see a clean install without any plugins and being able to install them with Shop or PackageManager.

Still need to test on some other larger sites and play some with it.

Thanks allot!

**Comment by mgzawlinoo** [comment]
test with over 12000 documents web site and run smoothly. 
siteCache.idx.php reduced to 1.2MB to 115KB.
Thank you .
