### ISSUE TITLE
The cache folder is 14.6 GB, 1 826 576 files

### ISSUE THREAD

**Issue by Zevseg** [modxcms/evolution#450]
why not deleted the old?
Modx 1.0.15, PHP Version 5.2.17
Document caching type =  Cache is based on Resource ID and $_GET parameters
![2015-11-18 16-05-17](https://cloud.githubusercontent.com/assets/2156427/11240751/9f3f9a6c-8e0e-11e5-8ed8-9ab55d40f21c.png)

**Comment by dmi3yy** [comment]
php cant delete all files at once. and error. Need clear manual and then all ок   

update php   

--  
Lukianenko Dmytro
Web developer  
http://dmi3yy.com


среда, 18 ноября 2015 г. в 14:09, Zevseg написал:

**Comment by Zevseg** [comment]
Dmitry, these files do not appear all at once, there are files in the month of June. It may provide an option of cleaning the cache, if a long time through the admin panel it does not clean, produce as many files as it is bad

**Comment by dmi3yy** [comment]
you need to disable the code for pages that generate very many files or disable the cache based on het.
Alternatively write a plugin that will clean the cache files if more than 10 000


--  
Lukianenko Dmytro
Web developer  
http://dmi3yy.com


среда, 18 ноября 2015 г. в 14:43, Zevseg написал:

**Comment by Zevseg** [comment]
Ок, всё понятно. "Костыль" это тоже не круто.

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/5e2da11e57cd604ce92d22888fa846c77cb39505/manager/includes/document.parser.class.inc.php#L529
This is hash problem.
