### ISSUE TITLE
Create new password, logout, login page in frameset

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#452]
Minor issue,
When I change my password or username I have to relogin.
The login screen loads into the frameset not fresh page.

![xxx](https://cloud.githubusercontent.com/assets/523389/11867519/ed36fa8a-a4b1-11e5-894c-fe747cf71d6b.jpg)

**Comment by Deesen** [comment]
Seems to be solved with 1.1RC, cannot reproduce.

**Comment by fourroses666** [comment]
Will open issue if it happens again.
