### ISSUE TITLE
Evo 1.1RC - "Ditto" & "Use AliasListing only for Folders"

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#458]
The combination of "Ditto" & "Use AliasListing only for Folders" in certain cases does not work as expected - causing PHP errors and a broken site.

See my forum post <a href="http://forums.modx.com/thread/99188/modx-evolution-1-1rc#dis-post-536640">starting here</a>

**Comment by dmi3yy** [comment]
correct link http://forums.modx.com/thread/99188/modx-evolution-1-1rc#dis-post-536640

about Ditto and aliasListing, its bug 
about IF  - incorrect work if use  3 or more depth in snippets - it not right way

**Comment by modxuser** [comment]
> about IF - incorrect work if use 3 or more depth in snippets - it not right way

Sorry, but I don't understand - if this is the wrong way, why does it work when the "Use AliasListing only for Folders" is not active ?

**Comment by dmi3yy** [comment]
I am of the opinion that such nested snippets is not good. 

I will test where is bug. thanks for testing. And one more thing for test: https://github.com/dmi3yy/tinymce4-for-modx-evo

if you use https://github.com/dmi3yy/modx.evo.custom, can install from Extrass.

**Comment by modxuser** [comment]
> I am of the opinion that such nested snippets is not good. 

Ah, OK

But, if I don't do this I have to create multiple instances of one and the same chunk - this code is used on multiple pages using different templates - so there is no other feasible solution, just to change 2 numbers depending on which part of the site you are on

I am not the only one doing this - you can find a multitude of answers in the forum that have similar code where snippets are called in other snippets

**Comment by dmi3yy** [comment]
I test why not work this: 
[[if? &is=`[[UltimateParent]]:in:74` &then=`74` &else=`3`]]

but now fast solution do simple snippet with same logic inside

**Comment by modxuser** [comment]
Yes - I know the problem is because of the "if" call - I have since tried replacing the "if" call with an ID and it worked - but that doesn't solve the problem

I don't have a different solution, as written in my previous post

**Comment by dmi3yy** [comment]
I understand) then you have to look from the error and correct it :)

**Comment by modxuser** [comment]
In my eyes there is no error, at least not until I activate "Use AliasListing only for Folders"

So the error accurs when using "Ditto", "if" and "Use AliasListing only for Folders"

**Comment by modxuser** [comment]
> about Ditto and aliasListing, its bug 

Do I need to report this somewhere ?

**Comment by dmi3yy** [comment]
no need. 
this issues best place for report )

**Comment by modxuser** [comment]
OK, thanks for the feedback

Will you be looking further into the problem with "Ditto", "if" and "Use AliasListing only for Folders", when used together ?

**Comment by dmi3yy** [comment]
yes i will test and fix it

**Comment by modxuser** [comment]
that's great - thanks for your help

let me know where I can help - I am no a programmer, but can carry out testing

**Comment by modxuser** [comment]
Hi dmi3y
I have downloaded the latest version of 1.1RC and installed it on three different sites.
The only problem I have is with "Ditto" & "Use AliasListing only for Folders"

**Comment by dmi3yy** [comment]
Its great ) 
Next week I will try to find time to deal with this error

**Comment by modxuser** [comment]
OK, great stuff
I wont update the sites until the modified code is ready - that way I can go through and test everything without having to change the code every time in every site

**Comment by Deesen** [comment]
I think I found the reason. File document.parser.class.inc.php, Line 1158. The matches[0]-Array looks as follows:

    matches[0] = array(  
      0=>"[[UltimateParent]]",  
      1=>"[[if?&is=´[[if?&is=´[[UltimateParent]]:in:2´ &then=´2´ &else=´15´]]",  
      2=>"[[Ditto?&parents=´[[if?&is=´[[UltimateParent]]:in:2´ &then=´2´ &else=´15´]]´]]"  
    )

When the Ditto-String is processed by function evalSnippets(), matches[0] gets looped from the beginning so it replaces `[[UltimateParent]]` first:

Before `[[Ditto?&parents=´[[if?&is=´[[UltimateParent]]:in:2´ &then=´2´ &else=´15´]]´]]`
After `[[Ditto?&parents=´[[if?&is=´2:in:2´ &then=´2´ &else=´15´]]´]]`

As `matches[0][1]` could not be found in aboves "After"-String, it can not be replaced. Then Ditto receives the parameter like being called `[[Ditto?&parents=´[[if?&is=´]]`

The solution is running the foreach(matches[0]) in reverse to replace `matches[0][1]` before `matches[0][0]`:

https://github.com/modxcms/evolution/pull/467/files

**Comment by modxuser** [comment]
I just added the modified code and removed the old code as in the pull request - the modified code hasn't made a difference

Just to elaborate on this - I posted in the MODX forum that even when the call is modified to have a fixed number instead of using "Ultimateparent" and "if" that the pagination doesn't work and the counting (CountDocs) also doesn't work.

So the problem seems to be with the general compatibility between Ditto and the new AliasListing configuration setting

**Comment by Deesen** [comment]
Ok I could not recreate that bug on my local machine yet. But I hope I found the solution to dmi3yy´s comment: "about IF - incorrect work if use 3 or more depth in snippets - it not right way".

**Comment by modxuser** [comment]
@Deesen

Step 1:
document.parser.class.inc.php updated with new code

Step 2:
Test using original Ditto call -
```
[[Ditto? &extenders=`countDocs` &display=`1` &parents=`[[if? &is=`[[UltimateParent]]:in:74` &then=`74` &else=`3`]]` &depth=`2` &tpl=`countresult` &hideFolders=`1` &showInMenuOnly=`0` &showPublishedOnly=`1`]]
```
Result - the same as before

Step 3:
Changed Ditto call to
```
[[Ditto? &extenders=`countDocs` &display=`1` &parents=`[[if? &is=`74:in:74` &then=`74` &else=`3`]]` &depth=`2` &tpl=`countresult` &hideFolders=`1` &showInMenuOnly=`0` &showPublishedOnly=`1`]]
```
Result - works to a point

On pages that are in 74 the count is there - with a correct count
On pages that are in 3 the count is there - incorrect count but there
On pages that are not in 74 or 3 the count is taken from 74, not 3 as it is supposed to

**Comment by Deesen** [comment]
Are your ressources managed simply, without nested Containers? Just like:

- Ressource[74]
  - Ressource[10]
  - Ressource[11]
  - ... 50 Ressources
- Ressource[3]
  - Ressource[30]
  - Ressource[31]
  - ... 30 Ressources

So I can build up the same structure here. I noted already "AliasListing" does not recognize ressources without alias. Duplicated ressources (initially without alias) do not show up.

@dmi3yy 
Maybe duplicating a ressource should create an automatic alias instantly, like when just saving it manually again?

**Comment by modxuser** [comment]
@Deesen

My setup is similar to the following:

Homepage
About
Contact
Catalogue
-- Level 2
---- Level 3
---- Level 3
---- Level 3
-- Level 2
---- Level 3
---- Level 3
---- Level 3
RSS Feed
Sitemap


Catalogue - Redirects to first child (function will change in time)
Level 2 - an overview of all its level 3 elements
Level 3 - single element

Its similar to a catalogue of products, but it isn't a shop :)

I've been on your website and seen a tel. number - I can give you a quick call in the morning if that is better, that way I can explain better and maybe show you the site in question - I am in Hannover

**Comment by Deesen** [comment]
Stupid question: Does it change anything if you add &topLevel=´2´ ? Otherwise [[UltimateParent]] returns the ID of "Catalogue", not of Level 2: `[[UltimateParent?&topLevel=´2´]]`

When I set up containers like yours, [+count+] always shows the right value. Everything works like expected. I still cannot reproduce the bug.

You wrote it shows 185 pages - it should output 193. Did you figure out which 8 pages are missing, and if maybe something is configured different there? The only thing really helping me would be direct access to your server to dig deeper into the problem, check files and page-setup like with those 8 pages.

**Comment by modxuser** [comment]
@Deesen

I have re-created a part of the website in a complete new install of Evo 1.1RC2 and added your modification to the document.parser.class.inc.php.

I have added about 210 pages and it all works

I haven't got a clue now why it doesn't work in the oirignal install (live site)

I will go through the code bit for bit and post my result here

**Comment by Deesen** [comment]
Great you took that effort! I would check the "Level3"-aliases now: For example umlaute, spaces, double aliases, whatnot. It would be great to know which exact 8 pages are missing, to compare aliases etc 1:1 against pages that are displayed. You could just call Ditto to output CSV-format like `[+id+];"[+alias+]";` in the minimal-template. And then save the output of AliasListing Active / Disabled into 2 separate CSV-files to compare them via Excel / LibreOffice Calc. Or compare 2 text-files with Notepad++ to see what is changing.

**Comment by modxuser** [comment]
I am back on the original development site

Upgraded to RC2 and added your modification to the document.parser.class.inc.php

I have compared the output when "Use AliasListing only for Folders" is active and when not - as you suggested.

When AliasListing is active it removes duplicate pages - that's why I only have 185 pages instead of 193

**BUT**

I have tested with duplicate pages in a completelty fresh install and it all works

**Almost forgot (been a long day)**

Although I have made the modification to the document.parser.class.inc.php I am getting the error again

**Comment by dmi3yy** [comment]
Small test for AliasListingFolder 
https://monosnap.com/file/ysAzaOUi8yWksbGUXgRSl2iGaVSavm
Size siteCache.idx.php 500Kb 
Speed for 28k and 105k Docs the same :) 

if I do not get tired of it I will bring the number of documents to 1 mln items.
The problem is that in the document tree can only duplicate a section of 20 000 documents at a time, if more than the server timeout falls

**Comment by Deesen** [comment]
Thanks for all efforts dmi3yy, sounds really good.

@modxuser 
The modification to document.parser only affects nested snippet-calls, to avoid the SQL-Error with Ditto `.. WHERE parent IN ([[if?&is=) ..`.

Its strange that 2 installations act so different. If your site holds no sensitive data you can prepare a SQL-dump with all nessecary documents and chunks for me, so I can test this issue on my local-server.

**Comment by dmi3yy** [comment]
still works:  http://take.ms/Jqt2Oh   + 2mb memory for each 100 000 items ))

**Comment by modxuser** [comment]
**UPDATE:**

I have returned back to the fresh install and low and behold - got it to no-longer work properly, which tells me it is not just a local problem

**To reproduce the problem:**

Simply duplicate a level 2 folder - this in turn will duplicate its children and keep their set-up identical to the original folder duplicated.

The level 2 folder needs renaming and a new alias - all child documents simplt need publishing

Go to front-end, refresh and the count stays the same a beforehand - switch aliaslisting off and your count will rise

I duplicated 4 times, went from 135 children to 195

when "Use AliasListing only for Folders" is active count shows 135
when "Use AliasListing only for Folders" is inactive count shows 195

**Comment by modxuser** [comment]
well done dmi3yy, hope It works with Ditto soon

**Comment by Deesen** [comment]
Ok I could recreate that bug and I assume it is no real bug. I think you just have ressources with empty or double aliases in a container.
  
I have duplicated Level 2, and all of its ressources initially have NO alias. If I use Ditto immediately, it shows only 1 ressource, but i have 7 ressources. All of them have no alias (that is why you advise "rename Level2-Alias" for access). If I rename the empty Alias of 1 ressource, and run Ditto again it shows 2.
  
It seems AliasListing builds up an Associative-Array with Alias as keys, so it can keep only unique keys/aliases per depth/level. PHP-Arrays can also hold an empty key per level.

@dmi3yy 
Maybe to avoid this issue we could use "auto assign alias" from save_content_processor also in duplicate_processor? Or does it have too bad performance when duplicating 10000s of ressources? Maybe deactivating it when duplicating more than 500 ressources?

**Comment by dmi3yy** [comment]
Still good http://take.ms/d5n5X, but Ditto i think not good for this ) DocLister need )

**Comment by dmi3yy** [comment]
after copying rename the document, and then create an alias.
When bulk copying the logic necessary to check for all documents if the child is checked to resolve aliases that duplicate copy as they will then be all ok

also need to write a description of the function in that there are problems with empty nicknames that are possible in the case of copying several documents

I think it will give understanding and to avoid such a situation,

**Comment by modxuser** [comment]
Just to ensure clarity - all of my alias fields are filled, either with bespoke or duplicated names, none of them are empty

**Comment by modxuser** [comment]
If DocLister can do everything that Ditto can, I have no problem in changing over, if that will benefit the performance of the site

**Comment by modxuser** [comment]
@Deesen 

I've tried calling a couple of times using the number on your website, but I keep getting "not available" - zurzeit nicht erreichbar usw.

**Comment by dmi3yy** [comment]
DocLister can all what can Ditto and more, but some thing like filter set diferent ) 

but for example on the basis of Doclister already have good filters
https://github.com/webber12/eFilter

**Comment by modxuser** [comment]
Thanks dmi3yy

Off the top of my head what I personally need is: Tagging, Doc counts with totals, pagination, itteration, RSS and probably some other stuff that I have forgot in time :)

Does DocLister have a splitpagination ? As Ditto doesn't, but there is SplitPagination (http://modx.com/extras/package/splitpagination) that can be used in combination with Ditto

**Comment by Deesen** [comment]
@modxuser Yes I have bad mobile connection from where I work ;-). Your issue is just "duplicate aliases" then.

@dmi3yy Why no "Automatic Alias" for duplicating documents (save_content_processor Line 76)? It could avoid lot of confusion.

**Comment by modxuser** [comment]
Yes and No

In my first test I created per hand new files in level 2 and named them the same as in a different level 2 and that worked.

By duplicating a level 2 folder and its content - the problem arised

**Comment by dmi3yy** [comment]
@dmi3yy Why no "Automatic Alias" for duplicating documents (save_content_processor Line 76)? It could avoid lot of confusion. - can do like   alias1 
if turn on aliasListing )

**Comment by Deesen** [comment]
@modxuser Maybe you need to understand MultiDim-Associative-Arrays then.  
The keys are ['key']. $alias[] is Level 1, $alias[][] Level 2.. Looks like:

	$aliasArray['alias-ressource-74']['alias-1']
	$aliasArray['alias-ressource-74']['alias-2']
		...
	$aliasArray['alias-ressource-74']['alias-150']
	
	$aliasArray['alias-ressource-3']['alias-1']
	$aliasArray['alias-ressource-3']['alias-2']
		...
	$aliasArray['alias-ressource-3']['alias-150']

If you have duplicate alias the array cannot hold the same key multiple times. What you probably expect to count:

	$aliasArray['alias-ressource-3']['duplicate']
	$aliasArray['alias-ressource-3']['duplicate']
	$aliasArray['alias-ressource-3']['duplicate']

What the array technically can hold:

	$aliasArray['alias-ressource-3']['duplicate']

BTW same principle when alias is empy ['']:

	$aliasArray['alias-ressource-3']['']

**Comment by modxuser** [comment]
@Deesen 

LMAO - your barking up the wrong tree there :)

I am not a programmer :) wish I was, but I never will be

To emphasise: these problems **only arise** when "Use AliasListing only for Folders" is activated

**Comment by Deesen** [comment]
@modxuser That is why I tried to explain. I cannot do more ;-).
@dmi3yy But when duplicating the same container 2x, we have a "Duplicate Alias" again? What if SEO "Friendly URL alias path" is disabled?

**Comment by modxuser** [comment]
@Deesen 

Bitte nicht falsch verstehen - das war nicht boese gemeint :)

**Comment by Deesen** [comment]
Don´t worry! ;-)

**Comment by Deesen** [comment]
To create a unique alias on duplicate for each ressource: File `duplicate_content.processor.php`, Line 66 insert:

	// friendly url alias checks
	global $friendly_urls, $automatic_alias, $allow_duplicate_alias;
	$tbl_site_content = $modx->getFullTableName('site_content');
	if ($friendly_urls && $automatic_alias) {
		// auto assign alias
		$alias = strtolower($modx->stripAlias(trim( !empty($content['alias']) ? $content['alias'] : $content['pagetitle'] )));
		if(!$allow_duplicate_alias) {
			if ($modx->db->getValue($modx->db->select('COUNT(id)', $tbl_site_content, "id<>'$docid' AND alias='$alias'")) != 0) {
				$cnt = 1;
				$tempAlias = $alias;
				while ($modx->db->getValue($modx->db->select('COUNT(id)', $tbl_site_content, "id<>'$docid' AND alias='$tempAlias'")) != 0) {
					$tempAlias = $alias;
					$tempAlias .= $cnt;
					$cnt++;
				}
				$alias = $tempAlias;
			}
		}else{
			if ($modx->db->getValue($modx->db->select('COUNT(id)', $tbl_site_content, "id<>'$docid' AND parent=$parent AND alias='$alias'")) != 0) {
				$cnt = 1;
				$tempAlias = $alias;
				while ($modx->db->getValue($modx->db->select('COUNT(id)', $tbl_site_content, "id<>'$docid' AND parent=$parent AND alias='$tempAlias'")) != 0) {
					$tempAlias = $alias;
					$tempAlias .= $cnt;
					$cnt++;
				}
				$alias = $tempAlias;
			}
		}
		$content['alias'] = $alias;
	}

Taken from `save_content.processor.php` Line 74.

**Comment by modxuser** [comment]
@Deesen 

I have added the above code, but there are no changes - the duplicates are still not shown

**Comment by Deesen** [comment]
When you duplicate a ressource like Level 2, this code will give the new Level2 and all child-ressources a unique alias now. Without the code all new alias will be empty.

**Comment by modxuser** [comment]
what do you mean ? will it override the alias that is already used ?

I have for example over 100 aliases that are the same and need to be the same - they can not be changed

**Comment by Deesen** [comment]
It will create new alias when you duplicate a container. It will not change any already existing ressource / alias.

If you have double-aliases that cannot be changed, I think you simply cannot use AliasListing with Ditto right now. How many ressources do you have in total that you insist on using AliasListing?

**Comment by modxuser** [comment]
The code throws a PHP error when trying to duplicate:

```
« MODX Parse Error »

Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND alias='duplicate-of-parent-13'' at line 1

SQL > SELECT COUNT(id) FROM `evo-rc2`.`cms_site_content` WHERE id<>'278' AND parent= AND alias='duplicate-of-parent-13' 
```
BACKTRACE

    include_once(string $var1)
    manager/index.php on line 865
    
    duplicateDocument(278)
    manager/processors/duplicate_content.processor.php on line 27
    
    DBAPI->select('COUNT(id)', string $var2, string $var3)
    manager/processors/duplicate_content.processor.php on line 91
    
    DBAPI->query(string $var1)
    manager/includes/extenders/dbapi.mysqli.class.inc.php on line 146

**Comment by modxuser** [comment]
@Deesen 
I have sent you my number via your contact form on your website - it would be easier and quicker to have a quick chat - what do you think ?

**Comment by Deesen** [comment]
Does it finally fix the issue? https://github.com/Deesen/evolution/commit/1f93d953d0e34e49f5c71786e9521822aa2c6318?diff=unified

**Comment by modxuser** [comment]
@Deesen

Yes it seems to have fixed the issue with Ditto counting - great work, thanks for your time and effort
