### ISSUE TITLE
modx system Error not work Digital Ocean

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#460]
Hi, I move one of my web site to Digital Ocean and
modx system Error not work .
It is work at previous host  .
But in Digital ocean , it only send php error alert email . (such as snippet error) .
work well with eform .

Not sent when I modify index.php.
Is that depend on file permission? (index.php - permission set to 644)

I need to know if one of my user modify index.php , and modx system email to me . 
Note : It is work at previous host
Modx version : 1.0.15

**Comment by dmi3yy** [comment]
What version php on server?

**Comment by mgzawlinoo** [comment]
Php Ver : 5.5.9
@php ini 
display_errors	On

**Comment by dmi3yy** [comment]
Update to 1.1rc  i think it help

Отправлено с iPhone

**Comment by mgzawlinoo** [comment]
Thank you dmi3yy, I will try it .

**Comment by mgzawlinoo** [comment]
Now, Solved . 
I remove sendmail and install Exim 4. The problem solved.
