### ISSUE TITLE
"actionButtons" - CSS-IDs missing

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#461]
I am developing a plugin to optimize workflow within Manager and I noticed some IDs are missing. Normally it looks like:

`<ul class="actionButtons">  
    		  <li id="Button1">...Button Save...</li>  
    		  <li id="Button2">...</li>  
</ul>`

If you search for  `<li><a href="#" onclick="documentDirty=false;` the following files show up:

\manager\actions\messages.static.php
\manager\actions\move_document.dynamic.php
\manager\actions\mutate_role.dynamic.php
\manager\actions\mutate_web_user.dynamic.php

So if you want to address a specific Button via jQuery, there is no ID given.

If interested, my plugin: https://github.com/Deesen/modxEvo_scrollFix/
("Extend Save-Button" doesn´t work for "Edit Webuser-Page" due to above reason)

**Comment by dmi3yy** [comment]
You can fix and send PullRequest ind this will be added in 1.1 

"ScrollFix": Remembers last scroll-position after pressing Save-button now its work from CORE 

test plugin but have error $j

**Comment by janniconl** [comment]
Plugin worked for me. Great plugin btw! You could add in your README that people need the FLAT-theme for Modx Evo for this plugin to work (otherwise you would not have icons on the buttons)
