### ISSUE TITLE
Evo RC2 Extra module custom style

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#463]
Great to see Package Manager possible to add from the installer!

Is there a way to add a custom stylesheet URL? or can this be added?
(I have a custom manager style and like to change the style from Extra a littlebit without touching the core.)

**Comment by dmi3yy** [comment]
better way fixed in core and send Pull Request )

**Comment by fourroses666** [comment]
Oké, like this?

FILE: /assets/modules/store/template/main.html
`<link rel="stylesheet" type="text/css" href="[+site_url+]/assets/modules/store/css/style.css" />`

change into:
option 1: (new file)
`<link rel="stylesheet" type="text/css" href="media/style/[+manager_theme+]/store.css" />`

option 2: (paste in default style.css)
`<link rel="stylesheet" type="text/css" href="media/style/[+manager_theme+]/style.css" />`
