### ISSUE TITLE
Evo RC2 and TinyMCE custom style and options

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#464]
Thanks for adding TinyMCE4!

When choosing TinyMCE4 I would like to have interface options like TinyMCE3 has.

Like: `undo,redo,selectall,separator,bold,italic,underline,pasteword,separator,hr,charmap,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,image,link,unlink,anchor,media,separator,cleanup,removeformat,separator,print,code`

(I would also like to add a skin for my custom manager style.)

**Comment by dmi3yy** [comment]
Yes its all need move to settings from file, only after this add in core tinyMCE4

**Comment by fourroses666** [comment]
:+1:
