### ISSUE TITLE
kcFinder 2.5.4 creates no Thumbs of Images uploaded via FTP ?

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#468]
I tested it with a customer´s 1&1-server, and on my local-server (PHP5.6). kcFinder creates only Thumbs when uploaded via kcFinder´s moveUploadFile(). If uploaded via FTP, no thumbs are created. I found the root in core/lib/class_fastImage.php - Line 215. By removing `mb_convert_encoding()`, my thumbs are created as usual. moveUploadFile() does not use class fastImage, therefore thumbs get created. getFiles() uses it in Line 721

**Comment by dmi3yy** [comment]
Fix 
http://modx.im/blog/addons/4153.html#comment31882
