### ISSUE TITLE
Translation de.php in Dutch?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#470]
I logged in Transifex, I see some de.php file.
Is that correct? shouldn't that be nl.php for the Netherlands/Dutch?

![transifex](https://cloud.githubusercontent.com/assets/523389/12475096/ae554ae4-c020-11e5-9f18-cc4897d65cd8.jpg)

**Comment by Deesen** [comment]
There is a green Button "Join Team": https://www.transifex.com/modx/modx-evolution/

**Comment by fourroses666** [comment]
its gone now, I'm already on the "dutch" team.
probably it was a mistake
