### ISSUE TITLE
Possible SQL Injection?

### ISSUE THREAD

**Issue by terrybarth** [modxcms/evolution#471]
I have a site running Evo 1.0.15. I subscribe to SiteLock to monitor the site for malware. They sent me an alert about a possible SQL Injection.

(I changed the page names below)

Using the GET HTTP method, SiteLock found that :
- The following resources may be vulnerable to blind SQL injection :
- The 'username' parameter of the /manager/processors/login.processor.php CGI :

/manager/processors/login.processor.php?password=&rememberme=1&username=
)+or+(1=1

-------- output --------
HTTP/1.1 200 OK
-------- vs --------
## HTTP/1.1 406 Not Acceptable
- The 'start' parameter of the /page-name.html CGI :

/page-name.html?start=10)+or+(1=1

-------- output --------
HTTP/1.1 200 OK
-------- vs --------
## HTTP/1.1 406 Not Acceptable

Clicking directly on these URLs should exhibit the issue :
(you will probably need to read the HTML source)

**Comment by Deesen** [comment]
MODX just returns `echo"<script>window.setTimeout(\"alert('".addslashes($modx->db->escape($msg))."')\",10);history.go(-1)</script>"` = like clicking the browser´s back-button. So its no vulnerability I guess.  
Does it make sense to put `header('HTTP/1.1 406 Not Acceptable');` before echo ""?

**Comment by terrybarth** [comment]
I'm sorry, but i don't know what any of this means. SiteLock is telling me I have to address this. So I should tell them it's not really a threat?

**Comment by Deesen** [comment]
I asked the "crowd" as I have no experience with this issue as well ;-)

**Comment by modxuser** [comment]
This has been further discussed in the forum here:
http://forums.modx.com/thread/90793/community-concerns?page=21

**Comment by bossloper** [comment]
can be closed?

**Comment by terrybarth** [comment]
Yes.

**Comment by bossloper** [comment]
@terrybarth  ... that's for you to do. 'close issue' or 'close and comment' on github

**Comment by terrybarth** [comment]
Done.

Thanks


[image: logo]
*Terry Barth Design* *, Website Development*
612 859 2453 | 730 Stinson Blvd NE #103 | terrybarth@terrybarth.com |
www.terrybarthdesign.com
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=525502627009493>
