### ISSUE TITLE
not work <[!!]> in getTagsFromContent

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#474]
if(strpos($content,'<[!')!==false)  $content = str_replace('<[!', "<[{$spacer}!",$content);
 if(strpos($content,']]>')!==false)  $content = str_replace(']]>', "]{$spacer}]>",$content);
 if(strpos($content,'!]>')!==false)  $content = str_replace('!]>', "!{$spacer}]>",$content);
 if(strpos($content,';}}')!==false)  $content = str_replace(';}}', ";}{$spacer}}",$content);
 if(strpos($content,'{{}}')!==false) $content = str_replace('{{}}',"{{$spacer}{}{$spacer}}",$content);
 
in https://github.com/dmi3yy/modx.evo.custom i rollBack this function

**Comment by yama** [comment]
https://github.com/modxcms/evolution/commit/4fd93d88955c41e645473956ef5c3f98625fe222
https://github.com/modxcms/evolution/commit/81282c4e4f5a4e08194fb4fb3f79bd8c32d0a71a

**Comment by yama** [comment]
test code 1 : <img src="xxx" [[more-attrib]]>
test code 2 : <img src="xxx" [!more-attrib!]>

**Comment by dmi3yy** [comment]
Fixed
