### ISSUE TITLE
Snippet IF

### ISSUE THREAD

**Issue by Fess7** [modxcms/evolution#480]
![1](https://cloud.githubusercontent.com/assets/7957471/12744548/f64cb2c2-c9a5-11e5-999f-fba75a0c953c.png)
The snippet shows `1 1` instead of emptiness.

**Comment by Deesen** [comment]
How is it nested? In multiple chunks? Whatever I try I cannot recreate this bug.

**Comment by Fess7** [comment]
No, it is written in template, it is not nested.

**Comment by Fess7** [comment]
For example, there are snippets in template:
Site - http://modx-test.1gb.ru/
Manager - test 123456

**Comment by redtoadmedia** [comment]
As far as I know the if snippet for evo was a switch to show a chunk only.

**Comment by redtoadmedia** [comment]
You're either trying to use a revo snippet on an evolution site or you're using a very old snippet called if. And it doesn't have those parameters

**Comment by dmi3yy** [comment]
You can see params of snippet in comment inside snippet

Can work not only chunks 


Отправлено с iPhone

**Comment by Deesen** [comment]
@Fess7, you´re right. If [*content*] is empty, the snippet returns 1. If [*content*] is not empty, the snippet works normal. I inserted "test" as content, then it works: http://modx-test.1gb.ru/

Will try to find and fix this issue.

**Comment by MrSwed** [comment]
Same problem was where no return at end of the snippet which called by FileSource, loadelement plugin
> Да, идея абсолютно та же самая
>`$modx->snippetCache[$snippetName] = "return require '".$item->getRealPath()."';";`
see [disqus](https://github.com/DivanDesign/MODXEvo.snippet.ddGetMultipleField/pull/1) 

but, I see here 100% return at end )
but.. a few minutes..

**Comment by Fess7** [comment]
@Deesen, I thank you!
