### ISSUE TITLE
php 7 compatibility

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#481]
Presume this is relevant:
https://github.com/ClipperCMS/ClipperCMS/pull/463

Sigh, I wish Clipper and modx would 'make up' or whatever the politics are and combine to one.

**Comment by redtoadmedia** [comment]
>.>

**Comment by kp52** [comment]
Reminds me of a joke: [http://forum.ship-of-fools.com/cgi-bin/ultimatebb.cgi?ubb=get_topic;f=61;t=000011](http://forum.ship-of-fools.com/cgi-bin/ultimatebb.cgi?ubb=get_topic;f=61;t=000011)

**Comment by redtoadmedia** [comment]
well, I'm using both and will work with both. ignorant of any conflicts and will remain that way.
