### ISSUE TITLE
JSON-Variant of Plugin-Configuration

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#494]
I would like to see a JSON-Variant of the actual text-string based plugin-configuration. So

`&height=Height;text;100% &width=Width;text;400px &configKey=ConfigKey;text;default`

changes to

    {
    "width":[{"type":"text", "value":"100%", "default":"100%", "label":"Editor-Width", "desc":"Can be set in px or %."}],
    "height":[{"type":"text", "value":"200px", "default":"200px", "label":"Editor-Height", "desc":"Can be set in px or %."}],
    "pluginConfig":[{"events":"OnRichTextEditorRegister,OnRichTextEditorInit,OnInterfaceSettingsRender"}]
    }

which would enable additional fields like HTML-Description and no more restriction of signs. Also this way we could implement an "automatically mark plugin-events" function.

**Comment by dmi3yy** [comment]
Yes its good, but it is necessary to leave the compatibility with the older version since all additions to rewrite much laborious

**Comment by Deesen** [comment]
@yama Thanks! Just saw your work today. I tried to follow up https://github.com/modxcms/evolution/pull/543

**Comment by janniconl** [comment]
Could it be that you have broken EvoGallery?
See https://github.com/extras-evolution/EvoGallery/issues/11

Also when I try to install EvoGall module manually, I get Mysql errors, to reproduce:
- Add a new module
- paste text from: https://github.com/extras-evolution/EvoGallery/blob/master/install/assets/modules/gallery.tpl
- save

**Comment by Deesen** [comment]
Hmm interesting. You need to replace ' by " then it works.

**Comment by janniconl** [comment]
I thought so, maybe someone can add that to the extras repo? (I dont know how to do pull requests / not very familiar with git)

Also, could it be that this change to JSON also is the source for my problem as described here?
https://github.com/extras-evolution/EvoGallery/issues/11

Anyways, thanks for the help so far!

**Comment by Deesen** [comment]
Yes its very likely that this change is responsible for your issue. I will download EvoGallery soon and fix this issue.

**Comment by janniconl** [comment]
Thanks mate, hope you can fix it soon. Really holds me back from upgrading about 20 evo installs at the moment :( You efford is highly appreciated!

**Comment by Deesen** [comment]
Should be fixed, sry for the trouble ;-).

**Comment by janniconl** [comment]
Hi mate, no problem, Thanks for the quick work.

I've copied your changes and installed a new module with the install tpl from https://github.com/extras-evolution/EvoGallery/blob/master/install/assets/modules/gallery.tpl Worked like a charm!
