### ISSUE TITLE
RC3 or 1.1PR

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#495]
Am just wondering if there will be another release candidate or will 1.1 be released shortly ?

Cheers + please keep up the great work

**Comment by modxuser** [comment]
@dmi3yy 
I see you have updated the version.inc.php to RC3 but I don't see a release package

Are you going to create one ?

I ask as I am attempting to entice Evo users to test the release candidates as I post the information on the forum and require a download package for the download section of the main MODX website (pre-releases)

**Comment by dmi3yy** [comment]
On next week i test some thing and Realized

Отправлено с iPhone

**Comment by modxuser** [comment]
@dmi3yy 

Thanks - once you have made the release please let me know and I will update the forum post and ask Jay to update the pre-release page

**Comment by dmi3yy** [comment]
All done for 1.1 
need update  changelog.txt and can Realize)

**Comment by Nicola1971** [comment]
Great news. Thanks dmi3yy

**Comment by modxuser** [comment]
@dmi3yy

That sounds great

Once the changelog has been completed will the release be the official 1.1 version ?

**Comment by dmi3yy** [comment]
yes 
and tonight add #504

**Comment by modxuser** [comment]
Thats great work - thanks again

**Comment by dmi3yy** [comment]
Wiil be great write some thing like this:
 https://gist.github.com/dmi3yy/9324103

Done changelog: 
https://github.com/modxcms/evolution/blob/master/install/changelog.txt

Bugfixes: 44
Refactor: 35 
Additional Improvements & Updates: 35
Commits: 322
Files changed: 293
Participants: 18
-----
On MODX Evolution 1.1 worked:
- Dmytro Lukianenko (Dmi3yy)
- Sergey Davydov (MrSwed)
- Kari Söderholm (Haprog)
- YAMA (yama)
- Thomas Jakobi (Jako)
- and: Zevseg, Segr, TimGS, jasonabird, bossloper, Eoler, fourroses666, rpre, pmfx, kulmjens, MaXL-ru, janniconl, Fess7,esszett
---
I think best date for realise 29.02.2016 :) cool day 1 of 4 years

**Comment by modxuser** [comment]
@dmi3yy 
I have started a release message.

Someone else will have to write the tech part of the release, as I am not a developer and dont want to write something thats not correct.

[Uploading modx-1.1.txt…]()

**Comment by Eoler** [comment]
Great work! Can we sneak in a couple of commits before release? Is the develop branch base for a release?

P.S: I thought Deesen was also particularly active on 1.1RC

**Comment by modxuser** [comment]
@Eoler
I have already added Deesen to the release notes as one of the contributors

**Comment by dmi3yy** [comment]
Yes ;) 

Write at 3am:) add Deesen

Отправлено с iPhone

**Comment by dmi3yy** [comment]
Thanks

Отправлено с iPhone

**Comment by dmi3yy** [comment]
better with Deesen will be here: 

Dmytro Lukianenko (Dmi3yy) https://github.com/dmi3yy
Deesen (Deesen) https://github.com/deesen
Sergey Davydov (MrSwed) https://github.com/MrSwed
Kari Söderholm (Haprog) https://github.com/Haprog
YAMA (yama) https://github.com/yama
Thomas Jakobi (Jako) https://github.com/Jako
and: Zevseg, Segr, TimGS, jasonabird, bossloper, Eoler, fourroses666, rpre, pmfx, kulmjens, MaXL-ru, janniconl, Fess7,esszett

**Comment by Deesen** [comment]
Thanks all!

**Comment by modxuser** [comment]
@dmi3yy

Updated with your version -  see attached

Any tech infos need to be applied to the file - once you say its OK, I can then publish it on the Forum 29.02.2016 and also let the LLC know as they will have to update the MODX site

[modx-1.1.txt](https://github.com/modxcms/evolution/files/148046/modx-1.1.txt)

**Comment by dmi3yy** [comment]
All OK : )

**Comment by fourroses666** [comment]
Nice :) Great work.

Seen some nice stuff on the Russian blog!
http://modx.im/blog/addons/4244.html

![442b43](https://cloud.githubusercontent.com/assets/523389/13350971/c9a34c90-dc83-11e5-98cb-8c138925b880.png)

**Comment by dmi3yy** [comment]
[modx-1.1.txt](https://github.com/modxcms/evolution/files/148116/modx-1.1.txt)

update Add Agel_Nash 
His do:
* [GitHub:#cbce5e7] fix sendmail        
* [GitHub:#bdb542d] refactor BackTrace  
* [GitHub:#e612f72] refactor getLoginUserName   
* [GitHub:#03c5e28] refactor getLoginUserID     
* [GitHub:#816af9c] refactor getChunk   
* [GitHub:#93fa0fc] refactor runSnippet 
* [GitHub:#26f86d0] refactor makeUrl for AliasListingFolder       
* [GitHub:#3c94596] refactor checkPublishStatus()       
* [GitHub:#de360bd] autoload_register to spl_autoload_register 
* [GitHub:#07bac53] add function getCacheFolder 
* [GitHub:#9372391] add function setConditional 

but push in my Custom ) because it is not in the contributor

**Comment by modxuser** [comment]
I now have the official forum release post ready - if anyone wishes to update, add, or change it please download the copy attached here and re-upload when finished.

I will check on Monday (29.02.2016) for any changes - once @dmi3yy releases 1.1 I will post on the forum.

**IMPORTANT:** the post is Forum ready - meaning, it now uses the MODX forum syntax e.g. [b][/b]

[modx-1.1-final.txt](https://github.com/modxcms/evolution/files/148178/modx-1.1-final.txt)

**Comment by modxuser** [comment]
Jay Gilmore has made the announcement about the 1.1 release on the [MODX forum](https://forums.modx.com/thread/99649/modx-evolution-1-1-dozens-of-improvements-and-over-300-commits) with a modified version of my post - so I will now close this issue.
