### ISSUE TITLE
 Add a space in front of [+wf.classnames+] in wayfinder

### ISSUE THREAD

**Issue by Fess7** [modxcms/evolution#496]
I think, it would be nice.

**Comment by janniconl** [comment]
Whats wrong with adding it yourself in your template? (e.g. `class="myown-class [+wf.classnames+]"`

**Comment by Fess7** [comment]
If [+wf.classnames+] is empty, then there is a space. (e.g. `class="myown-class "`)
I would like to insert so `class="myown-class[+wf.classnames+]"`.

**Comment by modxuser** [comment]
Why don't you simply use the [Class parameters](https://rtfm.modx.com/extras/evo/wayfinder#Wayfinder-CSSClassNameParameters) in your call ?

**Comment by Fess7** [comment]
@modxuser, You are right. But as to me, it is not convenient.

**Comment by Deesen** [comment]
Maybe a simple new true/false option `[[Wayfinder? &classnamesspace=1 ]]` ?

**Comment by Fess7** [comment]
@Deesen, good idea! I am all for.

**Comment by janniconl** [comment]
That's what I would call over-optimalisation, since it really isn't a bug or a problem. Besides no one will probably will ever fall over this when the HTML source has a redundant space. I'm all for clean code ofcourse, but there are sufficient options in the current set-up in my opinion.

Eventhough, if anyone is willing to add a parameter to Wayfinder go head. But in my opinion there are better goals/more important issues for Evo to spend time on.

**Comment by modxuser** [comment]
I agree with janniconl - there is much more important things than this, especially when it can already be accomplished by using the class parameters

If someone does do the work, fine, but who is then going to do the documentation / update the RTFM ?

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/14984333d1a02f5e8f78e4b6eb74f3d12aa0fc0e/assets/snippets/wayfinder/wayfinder.inc.php#L283

`$output = preg_replace('@class="([^ "]*) "@','class="$1"',$output);`
Insert ths code.

**Comment by yama** [comment]
`if(strpos($output,'class=""')!==false) $output = str_replace('class=""','',$output);`
And this

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/14984333d1a02f5e8f78e4b6eb74f3d12aa0fc0e/manager/includes/document.parser.class.inc.php#L660
Or, core native imprement point.

```
if($modx->config['source_cleanup']==1) {
    $this->documentOutput = preg_replace('@class="([^ "]*) "@','class="$1"',$this->documentOutput);
    if(strpos($this->documentOutput,'class=""')!==false)
        $this->documentOutput= str_replace('class=""','',$this->documentOutput);
}
```

**Comment by Deesen** [comment]
I like `$modx->config['html_cleanup']==1` most because we can enhance it in case some further cleaning is nessecary in future. Also we could add a Plugin-Event "OnHtmlCleanup".

**Comment by Fess7** [comment]
@yama, thank you! It works.
