### ISSUE TITLE
New concept / class modxRTEbridge

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#498]
I have worked on a new [class ](https://github.com/Deesen/ckeditor4-modx-evo/blob/master/assets/plugins/ckeditor4/class.modxRTEbridge.inc.php)for easy implementing of (multiple) Richtext-Editors into Modx in future. A running version (also tested with Modx 1.0) for implementing **CKEditor4** can be found at https://github.com/Deesen/ckeditor4-modx-evo

Features:

  - allows dynamic / new settings via Modx- / user-configuration, also for multiple RTEs
  - allows dynamically translation of Modx- to specific editor-params via `gsettings/bridge.ckeditor4.inc.php`
    - Ex.: convert setting "entermode", string 'p' to constant CKEDITOR.ENTER_P
    - Ex.: convert setting "element_format", string 'html' to appending `<script>
                                                CKEDITOR.on( 'instanceReady', function( ev )
                                                {
                                                    ev.editor.dataProcessor.writer.selfClosingEnd = '>';
                                                })
                                            </script>` to $modx->documentOutput
  - themes are handled like skins (choose/create theme-file instead of limited theme-list) 
  - setting editorParams via Modx-, user-, plugin-configuration or in plugin-code via $rte->set()
  - runs also with richtextmini
  - etc.

So after installation of CKEditor4 you will find new configuration-options in Modx- and user-configuration based on old TinyMCE-config, but with new custom setting "maxHeight" at the end as example for dynamic settings. This way we can have "general Modx" settings mixed with editor-specific settings.

Theme "mini" acts as theme for Richtextmini and can also be choosen as general theme for testing. The mini-plugin `plugin.ckeditor4_mini.php` only works with https://github.com/modxcms/evolution/pull/492 / https://github.com/Deesen/evolution/tree/richtextmini . Here the new class shows its real capabilities I think.

@yama If it makes sense I can prepare a bridge-example for TinyMCE4.

**Comment by Deesen** [comment]
[CKEditor4 integration](https://github.com/Deesen/ckeditor4-modx-evo) is almost finished so the possibilities of the class can be demonstrated. The essential parts of modxRTEbridge are

  - Every theme- or bridge-file can access plugin-parameters and Modx-configuration parameters.
  - [bridge.ckeditor4](https://github.com/Deesen/ckeditor4-modx-evo/blob/master/assets/plugins/ckeditor4/gsettings/bridge.ckeditor4.inc.php) to translate settings from Modx-Parameters into Editor- / JS-language
    - Holds also customSettings and its defaultValues to create custom Modx-configuration settings
    - [gsettings.rows](https://github.com/Deesen/ckeditor4-modx-evo/blob/master/assets/plugins/ckeditor4/gsettings/gsettings.rows.inc.php) holds the old TinyMCE3-configuration providing minimum settings that are also generally available when porting new editors. Each "general setting" can be nulled by customSettings
  - [theme.base](https://github.com/Deesen/ckeditor4-modx-evo/blob/master/assets/plugins/ckeditor4/theme/theme.ckeditor4.base.inc.php) sets general settings, can be overwritten by custom theme
  - [theme.simple](https://github.com/Deesen/ckeditor4-modx-evo/blob/master/assets/plugins/ckeditor4/theme/theme.ckeditor4.simple.inc.php) > This custom theme to be selected in Modx-settings will tweak the user-interface
  - this prepares the editor-settings to be injected into the Modx manager sourcecode divided into 3 parts
    - [tpl.init_once](https://github.com/Deesen/ckeditor4-modx-evo/blob/master/assets/plugins/ckeditor4/tpl/tpl.ckeditor4.init_once.html) will be injected only once per editor at the beginning to inject loading the editors library. modxRTEbridge still can handle different editors on the same page. Mixing TinyMCE with CKEditor would cause injected tpl.init_once 2x, once for TinyMCE and once for CKEditor. Example  
`<script src="/assets/plugins/ckeditor4/ckeditor/ckeditor.js"></script>`  
`<script src="/assets/plugins/tinymce4/tinymce/tinymce.js"></script>`  
    - [tpl.config](https://github.com/Deesen/ckeditor4-modx-evo/blob/master/assets/plugins/ckeditor4/tpl/tpl.ckeditor4.config.html) will be injected once per theme to create a settings-object. So if CKEditor is used for a richtext-TV and richtextmini, tpl.config will create 2 different setting-objects, one for choosen theme and one for the mini-theme. This allows a global config-object for multiple editor-instances. Example  
`<script>var config_mini = {skin:'moono', width:'200px', height:'200px'};</script>`  
This also allows for example TinyMCE´s **elements: 'tv6,tv7'** (leaving tpl.init empty)  
`<script>tinyMCE.init({ theme: 'advanced', elements: 'tv6,tv7'});</script>`  
    - [tpl.init](https://github.com/Deesen/ckeditor4-modx-evo/blob/master/assets/plugins/ckeditor4/tpl/tpl.ckeditor4.init.html) will be injected for every editor instance to finally initialize each of them separately. The settings can be injected using the config-object (allowing cleaner html-output) or a prepared JSON-string with all settings for every instantiation. Example config-object:  
`<script>CKEDITOR.replace('tv6', config_mini);</script>`  
Example JSON-string:  
`<script>CKEDITOR.replace('tv6', {skin:'moono', width:'200px', height:'200px'});</script>`

**Comment by janniconl** [comment]
Sounds good Deesen! Thanks for your efford. Looking forward to see this implemented.

**Comment by Deesen** [comment]
I also plan a port of http://www.alohaeditor.org/ to see whats possible.

@dmi3yy Maybe we can add class modxRTEbridge to the core to develop it centrally?

**Comment by yama** [comment]
This source code is easy to understand.

**Comment by Deesen** [comment]
Ehm which source code? I have added multilanguage-support to modxRTEbridge for separated gsettings and custom-settings. So CK4 is already translated like Tiny3.

**Comment by yama** [comment]
OK, Thanks. I expect it.

**Comment by fourroses666** [comment]
Wow, this would be so nice as front editor. kinda like live typing. This way you directly can see what the changes are.
http://www.alohaeditor.org/demo/aloha-ui/

**Comment by dmi3yy** [comment]
yes %)

**Comment by Deesen** [comment]
I have prepared Aloha-Editor v2 now using again the modxRTEbridge: https://github.com/Deesen/alohaeditor2-for-modx-evo

Porting Aloha is real pain. The documentation is awful and incomplete, they are maintaing multiple dev-branches so its hard to keep overview. I already started to port v1 but its full of deprecated jQuery-code etc, and uploaded to the server it has 8 megabytes full of source-code -> http://oerpub.github.io/Aloha-Editor/src/demo/imageribbon/ . So I stopped trying to manage such a monster for now.

**Comment by dmi3yy** [comment]
I not tested: modxRTEbridge 
but if all ready we can merge this in 1.1 
or wait and add in next realize when  will be ready tinyMCE 4 and other

**Comment by Deesen** [comment]
I think its better to merge after 1.1 release but before Tiny4 release, so you can have a look before first. Who is maintaining Tiny4 now? If I can support, let me know.

**Comment by dmi3yy** [comment]
Ok. 
Yes you can support tiny4
Now its me)

Отправлено с iPhone

**Comment by Deesen** [comment]
Almost ready? https://github.com/Deesen/tinymce4-for-modx-evo

**Comment by Deesen** [comment]
Migrated v3 themes to v4 today. Custom-theme and webuser-theme are also working already. I removed/replaced deprecated plugins / buttons. https://github.com/Deesen/tinymce4-for-modx-evo

**Comment by Deesen** [comment]
Everything should work now https://github.com/Deesen/tinymce4-for-modx-evo
  - Modx-, user- and plugin-configuration as per Tiny3
  - Themes migrated from v3 to v4 (incl. custom- and webuser-theme), removed/replaced deprecated plugins/buttons)
  - Template-button loading content from chunks/ressources via `connector.tinymce4.templates.php`
  - Link-button allows now also "choosing from Modx-tree" like CKEditor4
  - STRG-S & Save-Button works (switches to "always stay" before saving to avoid leaving window)
  - documentDirty works
  - upgraded to latest Tiny 4.3.4 (also languages)
  - "Mini"-plugin also works (will be listed as separate editor "TinyMCE4 Mini" if installed)
