### ISSUE TITLE
new theme MODxPress

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#502]
new concept theme http://modx.im/blog/addons/4244.html
when be ready  start refactor default theme )

**Comment by dmi3yy** [comment]
https://github.com/WorkForFood/MODxPress

**Comment by Deesen** [comment]
Nice!! :+1:

**Comment by janniconl** [comment]
Can u add some screenshots in English interface language somewhere? Thx :)

**Comment by janniconl** [comment]
P.s. I would make the buttons flat-design style aswell. Since every other element is 'flat' aswell. So removing the light inner border / shadows and the gradient. Otherwise great job!

**Comment by dmi3yy** [comment]
http://take.ms/l34VG
http://take.ms/kCXm4
http://take.ms/pss1k
http://take.ms/kULqL

**Comment by janniconl** [comment]
That was quick :+1:  Cool thx! @dmi3yy

**Comment by dmi3yy** [comment]
https://screencloud.net/v/o1X6
https://screencloud.net/v/lWQ0

**Comment by fourroses666** [comment]
Wow looks very nice!

**Comment by WorkForFood** [comment]
Few new screenshots)) Sorry but with Russian language)
https://sc-cdn.scaleengine.net/i/771fb9b1440c11498a54a876af63ba1e.png
https://sc-cdn.scaleengine.net/i/3cc4808c3bda907fb73fc9a94f4bb4ed.png

**Comment by Deesen** [comment]
@dmi3yy Is a Manager-Template-API planned to complement new ModxAPI? I think it would be great to separate sql-statements etc from layouts. If it is planned I would like to support but alone I don ´t know where to start best.

**Comment by fourroses666** [comment]
@WorkForFood how the process going. :o

**Comment by WorkForFood** [comment]
@fourroses666 not so fast as it can be. :( Now i'm working with manager actions. I'm sort the code and rewrite markup in many manager actions. A lot of it is done (supports responsive markup and new js form framework) but i have a lot of main job and have not so much time to develop this project. :(

**Comment by fourroses666** [comment]
Yeah understand it eats allot of time. 
Just wondered how the process was going. 
Keep up the good work. 
Love what you already did!
