### ISSUE TITLE
Case sensitivity of snippet calls

### ISSUE THREAD

**Issue by Jako** [modxcms/evolution#503]
The new Evo version is case sensitive with snippet calls. A snippet called **WhatEver** could not called with `[[whatever]]` or `[[Whatever]]`. That was allowed in previous versions.

Maybe that should not be changed back, but it should be documented.

**Comment by dmi3yy** [comment]
All version will be case sensitive
Newer use cese insansetive))

Отправлено с iPhone

**Comment by Jako** [comment]
That should be documented somewhere, since it is a trap. I had to fix an installation today, because a  custom snippet was not running for that reason.

**Comment by Deesen** [comment]
Should I add this info here?
  - https://rtfm.modx.com/evolution/1.0/content-editing/modx-tags
  - https://rtfm.modx.com/evolution/1.0/designing/adding-snippets

**Comment by Jako** [comment]
I suggest to add that change in the changelog:
- Snippet calls are case sensitive. Are properties case sensitive too?

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/b6144830bcf1931f2e8d0273961ddf1db5fd4d6c/manager/includes/document.parser.class.inc.php#L1330
I just noticed.
MySQL does not distinguish case.
Therefore Cache is set.
However, PHP becomes invalid to distinguish a small and capital letter.
(Is this small bug?)

**Comment by Deesen** [comment]
Wouldn´t it make sense to handle snippet-names case-insensitive with strtolower()? https://github.com/Deesen/evolution/commit/be87c4643ff0fe92129ee1fcf56556b3258fe3dc

**Comment by dmi3yy** [comment]
And which version works independently checked the register pair legacy everywhere wayfinder no output
only Wayfinder works fine 
the same for params 

its work  from 0.9.3 version ) when I start use MODX

**Comment by Deesen** [comment]
You mean there was no change? Snippetcalls and params are case sensitive since 0.9.3?

**Comment by Jako** [comment]
There was a change. In that updated installation a snippet was named lowercase and the snippet call was done camelCase. There were no issues before the update to 1.1RC with that call. I don't know which version it was running before (something after 1.0.13, if I remember right).

**Comment by Deesen** [comment]
Hmm just wanted to help/solve the issue but don´t know how. So I better leave it.

**Comment by yama** [comment]
$modx->confit['case_sensitive_snipname']
How is add new config?
