### ISSUE TITLE
Listindexer uses mysql_

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#504]
As [reported here](https://forums.modx.com/thread/99264/evo-1-1rc---testers-required?page=2#dis-post-538769)

Affected code line [here](https://github.com/modxcms/evolution/blob/develop/assets/snippets/listindexer/snippet.listindexer.php#L436)

**Comment by dmi3yy** [comment]
need add  $modx->db->data_seek   

do this tonight  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 26 февраля 2016 г. в 00:09, modxuser написал:

**Comment by modxuser** [comment]
Cool :)
