### ISSUE TITLE
Feature TV input-type internal link-list

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#535]
I have many sites (with banners as example) and want to add some TV for internal links.
You don't want clients to type [~45~].

So I thought maybe its possible to add Internal Link list to the TV input type?

![input-type-linklist](https://cloud.githubusercontent.com/assets/523389/13533807/6ce456b6-e232-11e5-8df6-526311458487.png)
![select-out-list](https://cloud.githubusercontent.com/assets/523389/13533808/6ce733a4-e232-11e5-84bc-e3caf7d2914f.png)

**Comment by dmi3yy** [comment]
You can do this with custom tv
Or with @select  

For this all ready)

Отправлено с iPhone

**Comment by Deesen** [comment]
Why not setting up just a "number"-TV called [*link_id_1*].

In your banner-template you use [~[*link_id_1*]~] ?

**Comment by Deesen** [comment]
But a dedicated TV with nested tree-layout, and ajax-search could be great.

**Comment by bossloper** [comment]
set TV 'Input Option Values' to @EVAL return $modx->runSnippet('LinkListTV');
Then create a snippet and paste in the tinymce.linklist.php code from TinyMCE. A couple of small modifications to return the output instead of file_put_contents and you are there.... (though minus the ajax-search)

**Comment by Deesen** [comment]
Nice hint, thanks!

**Comment by pmfx** [comment]
Or instead of tinymce.linklist.php, make a Ditto call. There are plenty of options to achieve this without adding a new tv type. But I must admit that it would be useful to have it out of the box with some configuration options like parents/excluded docs/other stuff.

**Comment by bossloper** [comment]
Agreed, 'out of the box' would be nice, though there are options with the current setup.

**Comment by bossloper** [comment]
It leads to maybe creating a MODX api to return the list (with options), for use by TinyMCE, TVs etc

**Comment by Deesen** [comment]
Wanted to implement such a function into modxRTEbridge as "link-lists", "insert ressource/chunk-content" etc always needs a connector to Modx. So having such a function natively in Modx would be great.

**Comment by dmi3yy** [comment]
i think this great solution: 
http://modx.im/blog/addons/3461.html

**Comment by fourroses666** [comment]
That last solution looks pritty nice, but I'm happy with one of the other solutions aswell.
Cool to see Evo being pritty active.

@dmi3yy do you use an App for github on mobile?

**Comment by janniconl** [comment]
Tried to make Selector (https://github.com/Pathologic/Selector) work, but didnt get it. Too bad there is no documentation and all is in Russian :(

**Comment by fourroses666** [comment]
Would like to have a default solution for this. 
The @EVAL return $modx->runSnippet('LinkListTV'); doesn't seem to work.

Any idea's?

**Comment by fourroses666** [comment]
Shall I close this?

**Comment by dmi3yy** [comment]
yes

**Comment by fourroses666** [comment]
Thanks, would be doable I think but rather have a build in solution.
