### ISSUE TITLE
Idea: Save selected Chunks into assets/export/chunks.json

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#549]
I have an idea to save/restore standard-chunks, for example to easily install a standard-set of chunks after a fresh Modx-installation, or a keep a backup of the most important ones (optional date-time suffix to filename like backupmanager does -> chunks_2016-03-14_9-27.json ?).

Something like

- add new checkbox "Incooperate into chunks.json" to chunk-edit
- on chunk-save, all checked chunks will be translated into a JSON-string and stored in assets/export/chunks.json (or /assets/export/chunks/ or /import .. ?)
- add new tab/button to chunk-list/overview "Import chunks from JSON" with file-upload option and list of all existing .json files like backupmanager
- add to modx-config: "Save checked chunks", "Chunks-JSON filename", "Add date-time suffix"

So components can be installed easily via "Extras" and chunks easily via JSON-import/export. Of course we could add templates, TVs, snippets etc to this concept too... could replace/ be nice addition to fileSource-plugin. But as I said, just an idea ;-). At least for chunks I find it powerful having your standard-set of chunks available everywhere.

**Comment by fourroses666** [comment]
Yea, I like the idea to import standard-sets chunks/TVs/snippets.

Indeed possible to make a backup/export a chunk which can be imported/overwritten again.
Also for TV's it will be damn handy, I think DOC manager can do allot but I like it more by building some json txt file and import that.

It would have allot of power. 
So as example, you can build an eForm, export these (select) chunks and import them in an other site and your done.

**Comment by Deesen** [comment]
Hmm or maybe build a new (core?)-module for this issue.

**Comment by fourroses666** [comment]
Yea no problem with me. :smile:

**Comment by dzhuryn** [comment]
view my plugin https://github.com/dzhuryn/StaticElements-for-MODX-Evo/

**Comment by Deesen** [comment]
WOW, great start!! Will open some issues.
