### ISSUE TITLE
dbedit in Evo 1.1.

### ISSUE THREAD

**Issue by hgw7m** [modxcms/evolution#555]
Hello,

I just installed the dbedit module (from [https://github.com/ncrossland/ModX-Evo-dbEdit](https://github.com/ncrossland/ModX-Evo-dbEdit)) into a MODX Evo site, now version Evo 1.1, PHP 5.6

The module reports:
`mysql_query(): No such file or directory in (home path here)/assets/modules/dbedit/module.list.tables.inc.php on line 108`
`Warning: mysql_query(): A link to the server could not be established in (home path here)/assets/modules/dbedit/module.list.tables.inc.php on line 108`

In line 108 we have
`include_once $base_path."manager/includes/controls/datagrid.class.php";`

I can't add and connect to a table, after choosing the table the "Loading Configuration"-icon keeps turning ... no configuration ist loaded.

Any ideas? Thanks for any hints!
Guenter

**Comment by dmi3yy** [comment]
you need fix module all mysql_ to $modx->db

or change in config.inc.php   mysqli  to mysql

**Comment by hgw7m** [comment]
Hello, thanks for the quick reply. Changing config.inc.php seems to work. Thx!!

Does this potentialy conflict with other (standard) evo extras?

**Comment by dmi3yy** [comment]
yes all where not use $modx->db to connect in DataBase  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 15 марта 2016 г. в 12:18, hgw7m написал:

**Comment by hgw7m** [comment]
One more question: Is there a setting where to change the size of input fields? Type string produces size= 20, type varchar(125) the same. Didn't find this in search or docs. Need to hack if necessary?
Thx!!

**Comment by hgw7m** [comment]
Edited record.edit.inc.php - supposed to be the right place
