### ISSUE TITLE
Ajaxsearch: TypeError: Window.onDomReady is not a function

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#556]
I have ajaxsearch on a site and see an error (FF): TypeError: Window.onDomReady is not a function
Don't know why I get this error:
![as](https://cloud.githubusercontent.com/assets/523389/13777068/05f65d76-eaae-11e5-9485-eaf9fca172e5.png)

https://github.com/modxcms/evolution/blob/develop/assets/snippets/ajaxSearch/js/ajaxSearch1/ajaxSearch.js
last line: Window.onDomReady(activateSearch);

```
[!AjaxSearch? 
&ajaxSearch=`1`
&language=`nederlands` 
&showResults=`0` 
&landingPage=`12` 
&showMoreResults=`1` 
&moreResultsPage=`104`
&jScript=`jquery`
&addJscript=`0`
&tplInput=`zoek-input-nl`
!]
```

**Comment by Deesen** [comment]
Means Mootools is not included.

**Comment by fourroses666** [comment]
&addJscript=`1` does help but then Mootools is included :( 

AjaxSearch does work without it.
but to remove the error message I need to include it.

**Comment by fourroses666** [comment]
Using &ajaxSearch=`0` will remove the <head> stuff and the AjaxSearch still works.
No more issue/error in my console.
I don't understand why its needed, probably when using ajax with AjaxSearch but I'm not.
