### ISSUE TITLE
Question: How to purge old/orphan TV content

### ISSUE THREAD

**Issue by nick0** [modxcms/evolution#557]
Hello,
I am really excited by the recent Evo development - it sounds really exciting.
I have a question...
Is there a user friendly way (eg not too technical, maybe with a module, plugin or snippet) to purge old/orphan TV content (eg content that still exists in a website’s database for previously deleted / detached TVs)?
We were having issues with auto logout on an Evo 1.0.15 site and think orphan TV content may have been to blame for some of the logouts.

**Comment by Deesen** [comment]
It should be possible through a simple SQL-statement. I´m not 100% sure but I tested it with one TV. I edited one ressource, filled the new TV with text, removed template-assignment of the TV and it showed up using this query:

    SELECT cv.id,cv.contentid,cv.value FROM modx_site_tmplvar_contentvalues cv 
    WHERE cv.tmplvarid NOT IN (
	    SELECT t.tmplvarid FROM modx_site_tmplvar_templates t
    )

@dmi3yy : Does "Show orphan TV-content"-button like "Purge obsolute plugins" make sense?

**Comment by nick0** [comment]
Sorry for the slow response on this Deesen, I missed that there was a reply :)

Ah ok. Thanks for providing that code. I will give it a go in PHPMyAdmin.

It would be amazing to be able to do it through the manager to really clean up a website's database - working straight in MySQL is a little scary for a non coder and its nice being able to stay in Evo and do the edits there. Does anyone know how to turn the above code into a Module or Plugin?

**Comment by nick0** [comment]
Just wondering if the programmers have had any thoughts on this?

**Comment by Deesen** [comment]
Maybe a "maintenance"-module would make sense but which features should it offer beside TV-content? Just brainstorming:

- Purge orphan TV-content
- Purge none-assigned TVs
- Purge none-used Templates
- Optional SQL-backup before any purge?
- ..

**Comment by nick0** [comment]
+101

**Comment by nick0** [comment]
Maybe the features could be turned on / off?
For example with Purge none-assigned TVs and Purge none-used Templates, I often keep a number of unused (unassigned) TVs and Templates in projects that I will likely use later - I wouldn't want to actually delete those unused TVs or templates that I would like to keep for later use, But I would like to delete their orphan content to cleanup the DB.
Cheers Deesen

**Comment by bossloper** [comment]
@Deesen 
RE: Brainstorming additions for a 'maintenance module'. How about:
- trim options for the 'manager actions log', either by size, number of entries or date.
- maybe some sort of cleaning of phpthumbs in cache/images ... not sure about that one.

**Comment by Deesen** [comment]
Cleaning thumbs-cache by filedate would be simple&practical. With options like "older than" 1 month, 3 months, 6 months, 1 year, all thumbs..

**Comment by nick0** [comment]
That's an excellent idea re also clearing thumbs cache with specified time frame.
