### ISSUE TITLE
TinyMCE4 inline (front-editing) ID removal and use mce:edit

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#560]
@Deesen 
Reminder;

Try to: don't use ID's so the source gets messy.
- Add mce-edit (to the new default demo template) for inline front-editing with TinyMCE4.

This works:
```<h1 class="editable" id="modx_longtitle">Welcome to MODX</h1>```

Somehow get it to work with:
```<h1 mce:editable="modx_longtitle" >Welcome to MODX</h1>```

_(And let TinyMCE rip it out the inline code from the source?!)_

**Comment by Deesen** [comment]
Re-thought about this issue and there must be selectors existing in the template so TinyMCE and the save-function knows where to hook on. So to speak TinyMCE cannot remove IDs that have been there before TinyMCE.. so the only option would be to use plugin.tinymce4.php and OnParseDocument-event to replace all id="modx_bla" by empty string, so to remove IDs from source-code before sending to browser.

For class="editable" we could replace string "editable" by empty string (leaving empty class="" in source-code) or replacing class="editable" by empty string, but you must not use further classes on the element like class="editable border-bottom" or so then.

**Comment by fourroses666** [comment]
Hmm, brain cracker this is hehe.

I was thinking about wrapping with <span class="editable"> and remove the whole span onParseDoc then but I don't think the closing span can be removed.

Also thinking about just adding double ones and remove the whole thing like:
<h1 class="head" class="editable"></h1> or <h1 id="head" id="editable"></h1>

Don't know if that will give any issues.

**Comment by Deesen** [comment]
It will give issues, no double attributes allowed ;-). And removing closing spans is a problem too. So I don´t know how to solve this issue.

**Comment by fourroses666** [comment]
Me neither :'(

**Comment by fourroses666** [comment]
Can it be possible it knows when there is a TV in the template and add the inline editor?
I'm not a developer so do know whats possible. Or does it need the API.

**Comment by Deesen** [comment]
Hmm maybe yes :-)... maybe we could replace all placeholders set for inline like `[*content*]` by `<div id="modx_content">[*content*]</div>` only when logged in manager. This could indeed be the solution to leave no trace of inline-editing in frontend source-code. But not 100% sure yet.

**Comment by dmi3yy** [comment]
See quick manager;)

[#*content*]


Отправлено с iPhone

**Comment by Deesen** [comment]
Now I understand why there is `[*#content*]` in the demo-template, thanks :-)

**Comment by Deesen** [comment]
Finally added it, testers welcome ;-)

**Comment by fourroses666** [comment]
Coool, so that would mean when adding the class "mceEditable" its editable on front-end right?

**Comment by Deesen** [comment]
Not exactly. Its working like QuickManager, so to make a TV like `[*content*]` editable you only need to add a # to it `[*#content*]`. The plugin does the rest (like what you call mceEditable). Of course you need to enable InlineEdit-Mode in TinyMCE plugin-configuration.

**Comment by fourroses666** [comment]
Oke, thats even better :))) Thanks allot.
Sorry but not able to test very soon.

So if I would like to test I need to install the extra.
