### ISSUE TITLE
Plugin tv_categorized_tabs not working on 1.1

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#568]
After upgrading to 1.1 [tv_categorized_tabs plugin](http://modx.com/extras/package/tvcategorizedtabs) stopped working. TV's are no longer grouped in tabs only stacked. No JS error in console logs. Looks like plugin cant see MODX categories anymore?

**Comment by fourroses666** [comment]
Never knew that existed, nice plugin.

**Comment by pmfx** [comment]
Yeah, this one is great and kind of essential element of every MODX setup I have. Makes life a lot easier and more organized. I'm hoping that it will work again! I've noticed that plugin configuration is ignored too. Like no params are getting passed to the plugin. Any idea how to fix this?

**Comment by Deesen** [comment]
I see in plugin.php deprecated SQL-functions `mysql_query()`

**Comment by fourroses666** [comment]
Really beed to check out allot more plugins. There is allot of cool stuff peoples don't know about

**Comment by Deesen** [comment]
Maybe a hint: tv_categorized_tabs/ondocformrender.phtml line 166 says `table.getFirst()` which selects table tag of new preloader-div found in manager/includes/header.inc.php:

    <div id="preLoader"><table width="100%" border="0" cellpadding="0"><tr><td align="center"><div class="preLoaderText"><?php echo $_style['ajax_loader']; ?></div></td></tr></table></div> 

I did not configure this plugin yet but by removing above code, I see category-tabs appear below so maybe it will work then.

**Comment by Deesen** [comment]
Who wants to remove PHP-errors should replace

    mysql_query(         by   $modx->db->query(
    mysql_num_rows(      by   $modx->db->getRecordCount(
    mysql_fetch_assoc(   by   $modx->db->getRow(

**Comment by Deesen** [comment]
@pmfx Do you know if this plugin is compatible to YAMS mm-rules? Is it possible to use tv_categorized_tabs inside a YAMS language-tab?

**Comment by dmi3yy** [comment]
Use in mm_rules 
Movecategorytotab))

Отправлено с iPhone

**Comment by Deesen** [comment]
Sry for stupid questions :-)..

**Comment by pmfx** [comment]
@Deesen you are the man. Replacing old mysql queries with new one in plugin.php did the job perfectly. Thank you! Sorry but I've never used YAMS so can't answer that. BTW along with this plugin I recommend using [Categories Manager module](https://modx.com/extras/package/modxcategoriesmanager) by the same author ([stefan](https://modx.com/extras/author/stefan)). Both are gems in my opinion and completes eachother. There is [TVs on Template plugin](https://modx.com/extras/package/tvsontemplate) - great too.

**Comment by Deesen** [comment]
Nice :-). There is really too much good stuff out there, need to check those plugins soon.
