### ISSUE TITLE
Custom Modules out of /manager/ - How to use Manager´s session?

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#570]
I wanted to port myTinyTodo.net into a [custom module](https://github.com/Deesen/myTinyTodo-for-modx-evo), but I had hard times using Modx own session (to integrate mgrValidated into mytinytodo´s login-process etc).

I know about "include config.inc.php / startCMSSession()" but calling it from /assets/modules/mytinytodo/ will create its own session, separated from /manager/ session.

So how is it technically possible to use Manager-session in external scripts / paths? Is it nessecary that mytinytodo always uses `/manager/index.php?a=112&id=4` (manager´s link/button to module) instead of `assets/modules/mytinytodo/lib/index.php` to keep the right session?

**Comment by yama** [comment]
```
<?php
include_once('manager/includes/config.inc.php');
session_name($site_sessionname);
session_cache_limiter('');
session_start();
print_r($_SESSION);
```

**Comment by yama** [comment]
```
<?php
// include_once('manager/includes/config.inc.php');
$site_sessionname = 'originkey';
session_name($site_sessionname);
session_cache_limiter();
session_start();
$_SESSION['usertype']       = 'manager';
$_SESSION['mgrShortname']   = 'myName';
$_SESSION['mgrValidated']   = 1;
$_SESSION['mgrInternalKey'] = 2;
$_SESSION['mgrRole']        = 1;
header('Content-type: text/plain; charset=UTF-8');
print_r($_SESSION);
```

**Comment by Deesen** [comment]
Thanks! I interprete your answer that its not possible to get **same** session out of dir /manager/ ? myTinyTodo already has its own session-management (I would like it to check mgrValidated): https://github.com/Deesen/myTinyTodo-for-modx-evo/blob/master/assets/modules/mytinytodo/lib/init.php#L69

But the Ajax-features always call `mytinytodo/lib/index.php` so the session is different from `/manager/`.

**Comment by Deesen** [comment]
It seems it was my fault, I got it working now just by using startCMSSession() ..
