### ISSUE TITLE
Wayfinder weblink showing menutitle of linked page

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#572]
I'm having an issue with using weblinks; (Evo 1.1 with YAMS)
It shows the Menutitle of the page its linked to and not the current page, thats new for me.

It uses my navRowTpl:

```
<nav id="nav" class="nav">
	[[Wayfinder? 
	&startId=`0` 
	&firstClass=`first` 
	&level=`2` 
	&sortOrder=`ASC` 
	&sortBy=`menuindex`
	&rowTpl=`navRowTpl`
	&parentRowTpl=`navParentRowTpl`
	]]  
</nav>
```

**navRowTpl:**
`<li[+wf.id+][+wf.classes+]><a href="(yams_docr:[+wf.docid+])" [+wf.attributes+]>[[YAMS? &get="data" &docid="[+wf.docid+]" &from="menutitle"]]</a>[+wf.wrapper+]</li>`

![example](https://cloud.githubusercontent.com/assets/523389/13986313/122895be-f102-11e5-9b2c-fd8961d9baaa.jpg)

_Front-end: Terminal Amsterdam (GTA) should be: Bunker Terminals_

It looks like wayfinder is a bit mixed up or I need to add another rowTpl.

Same when using:
	&rowTpl=`@FILE:assets/modules/yams/tpl/wayfinder/doc/row.tpl`
	&parentRowTpl=`@FILE:assets/modules/yams/tpl/wayfinder/doc/parentrow.tpl`

**Comment by MrSwed** [comment]
try to set 
```
&useReferenced=`0`
```

**Comment by Deesen** [comment]
I am checking his site right now. `&useReferenced=0` results in "infinite redirections".. how can this be?

**Comment by fourroses666** [comment]
Does Wayfinder needs to be updated to development version?

**Comment by Deesen** [comment]
I think its because YAMS requests the translation by docid which points to target-id 31.

    [[YAMS? &get="data" &docid="[+wf.docid+]" &from="menutitle"]]

So a new placeholder like [+wf.sourceid+] is required for such a case ?

**Comment by fourroses666** [comment]
Thanx D, it works !
