### ISSUE TITLE
When using phpthumb and overwrite images with the same name, no update

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#575]
I'm experiencing the fact when I use phpthumb and upload an image -> don't like the image and remove it, then upload an image again with the same name, then the cached image is not being replaced.

Need to pick an other name to show the new image.

Any idea this can be fixed easy?
When we choose to cache images evey time with a new filename the webspace get pritty full.
But when choose an option to empty the whole cache images folder there will be issues aswell.
Maybe a regenerate button? Or is it something I'm experiecing as only person?

**Comment by Deesen** [comment]
A new "Image-Manager" module would be great.. just a little bit brainstorming:

- a database with all images, creation date, compression infos, size etc
- image categories
- set attributes like alt/title etc per image (how to solve for multilanguage like YAMS etc?)
- set optional URI for images, handle them via htaccess like SEF-links so they can be linked outside assets/images
- optional perceptional hashes?
- image statistics / infos

**Comment by fourroses666** [comment]
I actually don't know how other CMSses and whats already available which could be intergrated but it sounds very flexible.
For YAMS (looking a bit from SEO background) you can use different TVs so a duplicate image button and rename would be good enouf?

Something which looks like this? 
![better-cms_8](https://cloud.githubusercontent.com/assets/523389/14077930/79bfc704-f4f1-11e5-88c1-1235a8dab5f8.png)

Perhaps some image crop function like image plus has?
https://modx.com/extras/package/imageplustvinput

**Comment by fourroses666** [comment]
I can close this issue? It now overwrites the old image with the same name?

_You don't want to know howmany times I have to explain it here at the office that they need to use an other filename._

**Comment by Deesen** [comment]
Maybe you want to replace the affected file `manager/media/browser/mcpuk/core/browser.php
` to check if it solves your issue first?

**Comment by Deesen** [comment]
[browser.php](https://github.com/Deesen/evolution/blob/develop/manager/media/browser/mcpuk/core/browser.php)

**Comment by fourroses666** [comment]
It not working :(

**Comment by Deesen** [comment]
Maybe browser caching old image?

**Comment by dmi3yy** [comment]
no,  phpthumb not  test  date of image 

need add in md5    image time

**Comment by Deesen** [comment]
Stupid me, I fixed KCFinder, not phpthumbs ...will check after lunch.

**Comment by fourroses666** [comment]
This works :) Thanks.

_The only remark is that the thumb/image on the resource page is only being refreshed after saving the page and refreshing the iframe. The ones in the KCFinder popup and on the website frontpage are being refreshed_
