### ISSUE TITLE
mm_ddMultipleFields - a link problem with richtext or textarea

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#576]
I upgrade to 1.1 and I found a error ... 
at mm_ddMultipleFields - "a tag" link problem with richtext or textarea .

eg . I add a data like this : 
" Link 1 : <a href="http://www.google.com">google</a> "
and it occur " a" onchange="documentDirty=true;" />  " error .

1.0.15 it's ok with link attr in datafield such as richtext or textarea.
![error](https://cloud.githubusercontent.com/assets/9032715/14092071/2e0e1b20-f56a-11e5-8bb2-6b0bd2581ef7.png)

**Comment by mgzawlinoo** [comment]
Hi, there another error at 1.0.15
when I add link tag in textarea . the a tags are markup with " " 
like this :
`Link 1 -&nbsp;<a href=&#34;http:/www.example.com&#34;>http://www.example.com</a>`

so a link with " " double quote and it's not go specific link

**Comment by MrSwed** [comment]
what in mm_rules ? how call mm_ddMultipleFields ?
what in raw data ?

**Comment by mgzawlinoo** [comment]
mm_rules : 
mm_ddMultipleFields('link1', '', '4', 'richtext', 'Links');

I fill data - eg - `<p><a href="http:/www.example.com/link1.html">http://www.example.com/link1.html</a></p>`

and save , it change to `<p><a href=&#34;http:/www.example.com/link1.html&#34;>http://www.example.com/link1.html</a></p>`

call mm_ddmutiplefieds is simple call like this : 
[+col0+]

**Comment by MrSwed** [comment]
can not reproduce
![image](https://cloud.githubusercontent.com/assets/5120610/14100153/fcab93c6-f593-11e5-86af-94d2ddcc2973.png)
![image](https://cloud.githubusercontent.com/assets/5120610/14100206/6d3e680c-f594-11e5-9f26-cbfc69726179.png)

for toggle raw button:
```
mm_ddMultipleFields('link1', '', '', 'richtext', 'Links','auto','||','::','auto','auto',0,0,'','{"btnToggleRaw":true}');
```

check delimiters: if you use '||' or '::' somewhere, you need set other delimiters

**Comment by MrSwed** [comment]
Can be closed ?
