### ISSUE TITLE
eform phone validation focused only the Russian

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#577]
It focused on the Russian mobile + city code of 3 digits (eg, Moscow).

[eform.inc.php#L256](https://github.com/modxcms/evolution/blob/master/assets/snippets/eform/eform.inc.php#L258)
commit : https://github.com/modxcms/evolution/commit/2e56507354608c00a7ac75baff49819a403678b4

so [this usage](https://habrahabr.ru/post/110731/) not fit for other countries. and cannot to be committed to common repository, isnt it ?

**Comment by Deesen** [comment]
I think too. International phone-validation would be nice but seems a bigger lib like https://github.com/giggsey/libphonenumber-for-php is needed to achieve.
