### ISSUE TITLE
Language of  management system

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#581]
It seems that the management system is determined by the language settings of  browser, instead of the settings in the configuration
![image](https://cloud.githubusercontent.com/assets/5120610/14184167/8f2857ea-f77c-11e5-945a-b7fcbb7cb6de.png)

**Comment by fourroses666** [comment]
When I choose Russian-UTF8 as "User language" I get this error when checking "Manage Elements"

![untitled-1](https://cloud.githubusercontent.com/assets/523389/14201285/2f1847c8-f7f1-11e5-825f-f61e13a4cbfe.jpg)

**Comment by MrSwed** [comment]
may be it no browser language.. no changes in browser help to set other then russian

**Comment by MrSwed** [comment]
no changes in managemet helps..
i can reset setting only do sql
delete FROM `modx_user_settings` where user = 4

that is an error, while set user settings

**Comment by Deesen** [comment]
I tried to check this issue. For me the active language is the one set in user-settings and if not set, the global setting is used, like expected.

@fourroses666 Not 100% sure if it´s no bug, but I guess if you want to use i.e. russian language, you must set database to UTF8 collation. Where does latin_swedish come from?

**Comment by fourroses666** [comment]
On this server it seems the collation is latin_swedish.
I think on install I did choose: general utf8 ci 
Other lang no issues, russian utf8 can't check Elements etc.

![yo](https://cloud.githubusercontent.com/assets/523389/14232274/120853d4-f9a5-11e5-8508-fb4c3f800da2.jpg)

**Comment by Deesen** [comment]
Just for my interest, what happens if you use "russian" instead of "russian-utf8"?

**Comment by MrSwed** [comment]
russian - it is windows-1251, so if first waas russian-utf8, after swicthing to russian get some like this:
![image](https://cloud.githubusercontent.com/assets/5120610/14240236/e80f15b6-fa4b-11e5-9dab-6cc0d0b66e4c.png)

**Comment by Deesen** [comment]
Thanks! Expected this in combination with latin_swedish so the DB-collation is the reason. I wonder how this can happen, should such a situation not be avoided by install-procedure?

**Comment by MrSwed** [comment]
code page latin yes - that not the bug - "features of the database with a different encoding"
but no changeble user language settings - that is bug and it need to check..

**Comment by Deesen** [comment]
Checked already yesterday, could not recreate that issue. See my comment https://github.com/modxcms/evolution/issues/581#issuecomment-204946390

**Comment by Deesen** [comment]
Do you have the same problem on different installations / servers?

**Comment by MrSwed** [comment]
for the first time encountered. I usually install for Russian-speaking users, and usually language settings are not changed after installation

**Comment by Deesen** [comment]
Ok I tried the same then on my localhost:
  - created new database
  - uploaded Modx 1.1-package (not dev-version)
  - install-language: Russian, database-setup: SET CHARACTER SET utf8_general_ci, admin-language: Russian-UTF8

After install:

![lang1](https://cloud.githubusercontent.com/assets/8569221/14254223/1582b820-fa8f-11e5-979a-0d8a27a1ae9d.png)

Then I changed to "nederlands utf8" and saved. After automatic manager refresh it immediately looks like:

![lang2](https://cloud.githubusercontent.com/assets/8569221/14254263/40668ef4-fa8f-11e5-8628-59f44ad3f154.png)

Switched back to "russian" and then opened user-management to change language for admin-user:. After saving and reopening user-management the language is "nederlands":

![lang3](https://cloud.githubusercontent.com/assets/8569221/14254744/5dd085c4-fa91-11e5-9060-c61bf1768b45.png)

Then I reloaded/refreshed manager / all frames and the whole manager is "nederlands":

![lang4](https://cloud.githubusercontent.com/assets/8569221/14254782/9126d22a-fa91-11e5-938b-0b0fea71ce70.png)

Then I created 3 new users to have a situation / user with ID4 (user "test3) and set this user to "nederlands utf8"

![lang5](https://cloud.githubusercontent.com/assets/8569221/14255099/dc36b63a-fa92-11e5-8dc1-0e5e1ac6a274.png)

After login with user "test3" language is immediately nederlands:

![lang6](https://cloud.githubusercontent.com/assets/8569221/14255104/df0aeb6a-fa92-11e5-8b53-977d9043e284.png)

Database "modx_user_settings" looks like:

![lang7](https://cloud.githubusercontent.com/assets/8569221/14255107/e1f68b9a-fa92-11e5-8da4-97dedc99c353.png)

I can switch languages back and forth, works like expected, no problem. Maybe a SQL-Server issue? Do you have access to mysql.err - file to check sql-error-log after you saved a user?

**Comment by fourroses666** [comment]
I don't have access to that. (only apache errors log)

**Comment by MrSwed** [comment]
I think it can be closed
problem in the default database encoding

**Comment by fourroses666** [comment]
yea close it

**Comment by modxuser** [comment]
@MrSwed can you close this issue please if it has been resolved
