### ISSUE TITLE
Remove wayfinder doc.html or change link

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#582]
Can this file be removed?
https://github.com/modxcms/evolution/blob/develop/assets/snippets/wayfinder/wayfinder.documentation.html

If not then link to:
https://forums.modx.com/thread/40293/new-wayfinder-e-book?page=13#dis-post-502627

I personally like it minimal.

**Comment by MrSwed** [comment]
I think, it needed  to write new documentation in one place, like 
https://github.com/evolution-cms/docs

**Comment by fourroses666** [comment]
Thats oke with me.
To bad its not English thow :(

**Comment by janniconl** [comment]
Thats too bad indeed :(

**Comment by Deesen** [comment]
As [parseDocBlock()](https://github.com/modxcms/evolution/pull/583#issuecomment-207731844) is now added to Modx-core we could add a parameter @documentation to provide a link to official documentations. So when editing a snippet/plugin accordingly links to docs will be shown.

**Comment by Deesen** [comment]
Added it #592
