### ISSUE TITLE
class.modxRTEbridge.php  need php 5.4 

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#584]
use Closure Object on 294 row. its no good.  
MODX EVO work on 5.3

**Comment by Deesen** [comment]
Tried but cannot get PHP5.3 running on my localhost (DLLs missing etc). How to solve problem in line 294?

https://github.com/modxcms/evolution/blob/develop/assets/lib/class.modxRTEbridge.php#L294

**Comment by dmi3yy** [comment]
https://github.com/dmi3yy/modx.evo.custom/blob/master/assets/lib/class.modxRTEbridge.php#L294

https://github.com/dmi3yy/modx.evo.custom/issues/332

**Comment by Deesen** [comment]
Now I understand. On modx.com is stated ManagerManager also needs 5.4: https://develop.modx.com/develop/evolution/requirements/ . Minimum recommended is 5.2.

But install/action.summary.php only checks for PHP 5.0.0. Should I change it to 5.4.0 or do we need to make bridge compatible with 5.2?

**Comment by dmi3yy** [comment]
Minimum need 5.3 

Отправлено с iPhone

**Comment by Deesen** [comment]
Tried but could not solve this issue nicely.. the whole bridging-concept is based on that closure object. Seems to be bigger effort. Any idea?

**Comment by Deesen** [comment]
Was not that much effort.. but I cannot test myself on PHP5.2. Hope it works?

**Comment by dmi3yy** [comment]
php 5.2 no need )
