### ISSUE TITLE
tinymce - Update from 1.0.15 to 1.1 didn't work

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#586]
After updating a 1.0.15 site to 1.1 all went well, until testing started

As I don't use the editor myself I wasn't aware that there were problems, until I was told by my client

After the update, the editor wouldn't show the content, but the editor was there, along with the custom toolbar

I carried out numerous tests including re-naming the manager folder back to manager, re-installing the 1.1 version a couple of times using different set-ups, but no change.

I decided to remove the 1.1 version of tinymce and uploaded the version from 1.0.15 onto the server. I logged out, cleared cache from everywhere then logged back in - the editor now works as it did in 1.0.15

Any ideas why ?

To note is - both versions are marked up using the same version number "3.5.11"

**Just for clarity:**
The 1.1 files were uploaded via FTP in the original zip and unpacked on the server
This problem was / is apparent on both local and live servers

**Comment by Deesen** [comment]
This is indeed strange. Did you look into browsers console to see any error-messages? It sounds like a JS-error if toolbar is there but content not.

**Comment by modxuser** [comment]
sorry - didn't take that into account as it was an urgent fix, so that the client could carry on working

So, no - I don't have any info ref console errors

**Comment by Deesen** [comment]
Maybe you can rename actual working tinymce-dir so you can rename it back afterwards, then upload tinymce from 1.1 again to check console?

**Comment by modxuser** [comment]
@Deesen 

I've put the 1.1 version back in place on the local server (live is not available due to work in progress)

I get the following:

> JavaScript Error: TypeError:F[2] is undefined

Also noticed that I can type within the content area but none of the toolbar elements work. for example, clicking "HTML" doesn't work, or trying to use the "bold" element, doesn't work either

If I type in the editable area(s) and save, the page refreshes and the area is empty again - the new text is not saved at all.

I wasn't sure whether or not to provide this info as I was under the impression the latest "4.x" version was being added, due to the lack of HTML5 support in "3.x"

**Comment by Deesen** [comment]
I compared both versions and the only thing that has changed small is the youtube-plugin. Maybe you can check just replacing it (in tiny_mce/plugins/youtubeIframe). I also installed 1.0.15 first on my localhost, and then updated to 1.1. Tinymce is running fine for me in Chrome and Firefox.

**Comment by modxuser** [comment]
Swapped the folders - no difference

There must be some other changes in the 1.1 tinymice folder, as the 1.0.15 version works without any problems

**Comment by Deesen** [comment]
You mentioned you "cleared cache from everywhere" but IMO this could be still a browser-cache issue of mixing old JS-files with new ones. TinyMCE loads a separate JS-file per plugin. So if any of these old plugin-files are mixed/loaded from cache with new ones from server, it may cause a conflict?

STRG-F5 is often not enough to clear cache so in Firefox I regularly have to use "Configuration -> privacy -> clear history -> set checkbox on cache" (freely translated) to clear cache 100%. I have no more ideas without direct access to your installation.

**Comment by modxuser** [comment]
@Deesen 

Cache is not an issue - I have all my browsers set to not cache at all, and I am experienced enough with MODX to know that cache problems (whether MODX cache or browser cache) can be major problems when it comes to testing

Access to the install won't happen

IMO there have been changes made to the 1.1 tinymice that affect in some way - also, although changes have been made to the version in 1.1, the version number hasn't been changed / updated - which is misleading

**Comment by Deesen** [comment]
Sry cannot help then.

**Comment by bossloper** [comment]
The youtube-plugin update did not quite make it into 1.1. It is still in Dev branch, so it is nothing to do with that.
I found the issue. There was a minor change to xconfig.js . It has an extra | in the code.
I will file an update.

For TinyMCE version numbers in MODX. Historically the version number in MODX has reflected the offical TinyMCE version number. The files getting changed are not part of the TinyMCE install so no change to the version number... definitely confusing!

**Comment by bossloper** [comment]
https://github.com/modxcms/evolution/pull/589

**Comment by modxuser** [comment]
@bossloper

That did the trick - have tested the version from DEVELOP (since your change was merged) and it now works without any problems - local and on the live server

Thanks for your time
