### ISSUE TITLE
Easy2Gallery and 1.1

### ISSUE THREAD

**Issue by imandic** [modxcms/evolution#587]
I have a problem installing Easy2Gallery module into 1.1
Installation procedure fails with response:

544 : $dbase = xxxxx_db1
545 : $dbase = SHOW TABLES FROM xxxxx_db1
546 : $params = Access denied for user 'user_YY'@'localhost' (using password: NO)

Problem is that database user_YY does not exist, active user is user_YY_db1 (with _db1) at the end with full privileges. I have tried to create "user_YY" with all privileges but getting same errors.

Any suggestion?

error_log:
[Wed Apr 06 23:56:52 2016] [warn] [client xxx.yyy.zzz.kkk] mod_fcgid: stderr: PHP Warning:  mysql_query(): Access denied for user 'user_YY'@'localhost' (using password: NO) in /var/www/vhosts/domain.tld/httpdocs/assets/modules/easy2/install/index.php on line 115, referer: http://domain.tld/manager/index.php?a=106
[Wed Apr 06 23:56:52 2016] [warn] [client xxx.yyy.zzz.kkk] mod_fcgid: stderr: PHP Warning:  mysql_query(): A link to the server could not be established in /var/www/vhosts/domain.tld/httpdocs/assets/modules/easy2/install/index.php on line 115, referer: http://domain.tld/manager/index.php?a=106
[Wed Apr 06 23:56:54 2016] [warn] [client xxx.yyy.zzz.kkk] mod_fcgid: stderr: PHP Warning:  mysql_real_escape_string(): Access denied for user 'user_YY'@'localhost' (using password: NO) in /var/www/vhosts/domain.tld/httpdocs/assets/modules/easy2/includes/models/e2g.public.class.php on line 225, referer: http://domain.tld/manager/index.php?a=112&id=4
[Wed Apr 06 23:56:54 2016] [warn] [client xxx.yyy.zzz.kkk] mod_fcgid: stderr: PHP Warning:  mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/domain.tld/httpdocs/assets/modules/easy2/includes/models/e2g.public.class.php on line 225, referer: http://domain.tld/manager/index.php?a=112&id=4
[Wed Apr 06 23:56:54 2016] [warn] [client xxx.yyy.zzz.kkk] mod_fcgid: stderr: PHP Warning:  mysql_real_escape_string(): Access denied for user 'user_YY'@'localhost' (using password: NO) in /var/www/vhosts/domain.tld/httpdocs/assets/modules/easy2/includes/models/e2g.public.class.php on line 225, referer: http://domain.tld/manager/index.php?a=112&id=4
[Wed Apr 06 23:56:54 2016] [warn] [client xxx.yyy.zzz.kkk] mod_fcgid: stderr: PHP Warning:  mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/domain.tld/httpdocs/assets/modules/easy2/includes/models/e2g.public.class.php on line 225, referer: http://domain.tld/manager/index.php?a=112&id=4
[Wed Apr 06 23:56:54 2016] [warn] [client xxx.yyy.zzz.kkk] mod_fcgid: stderr: PHP Warning:  mysql_query(): Access denied for user 'user_YY'@'localhost' (using password: NO) in /var/www/vhosts/domain.tld/httpdocs/assets/modules/easy2/includes/models/e2g.public.class.php on line 774, referer: http://domain.tld/manager/index.php?a=112&id=4
[Wed Apr 06 23:56:54 2016] [warn] [client xxx.yyy.zzz.kkk] mod_fcgid: stderr: PHP Warning:  mysql_query(): A link to the server could not be established in /var/www/vhosts/domain.tld/httpdocs/assets/modules/easy2/includes/models/e2g.public.class.php on line 774, referer: http://domain.tld/manager/index.php?a=112&id=4
[Wed Apr 06 23:56:54 2016] [warn] [client xxx.yyy.zzz.kkk] mod_fcgid: stderr: PHP Warning:  mysql_query(): Access denied for user 'user_YY'@'localhost' (using password: NO) in /var/www/vhosts/domain.tld/httpdocs/assets/modules/easy2/install/install.class.php on line 542, referer: http://domain.tld/manager/index.php?a=112&id=4
[Wed Apr 06 23:56:54 2016] [warn] [client xxx.yyy.zzz.kkk] mod_fcgid: stderr: PHP Warning:  mysql_query(): A link to the server could not be established in /var/www/vhosts/domain.tld/httpdocs/assets/modules/easy2/install/install.class.php on line 542, referer: http://domain.tld/manager/index.php?a=112&id=4

**Comment by dmi3yy** [comment]
change in manager/includes/config.inc.php 

type = mysqli => type = mysql  and all be ok 

E2G not use DBAPI

**Comment by esszett** [comment]
So that means it uses the deprecated mysql extension… if you change config back to mysqli after installation of E2G, is it working than or should a todo assigned to make E2G working with mysqli?

**Comment by imandic** [comment]
Thanks dmi3yy.
Esszett: Changing back to mysqli breaks module.

**Comment by fourroses666** [comment]
Hmm, I get the following error on a site I have updated to 1.1 with Easy2Gallery

**Error : mysql_query(): Access denied for user 'root'@'localhost' (using password: NO)**

**Comment by dmi3yy** [comment]
need update in E2G  all code from mysql_  to modx->db->

or in manager/includes/config.inc.php set mysqli -> mysql  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 30 августа 2016 г. в 17:04, Marc написал:

**Comment by fourroses666** [comment]
Ah YES, I thought I did but it didn't overwrite it 

CHMOD was 404 !

Works now

**Comment by mediengaarage** [comment]
I have the same problem.
 I changed in all e2g code mysql_ to modx->db-> 
in manager/includes/config.inc.php type is mysql.
PHP 5.6
easy2gallery 1.4.14

i get a parse error:
syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /.../assets/modules/easy2/includes/models/e2g.module.class.php on line 823

**Comment by Deesen** [comment]
Please post your line 823

**Comment by mediengaarage** [comment]
the line 823 is:
 $queryInsertFile = modx->db->query($insertFile);

**Comment by bagi091** [comment]
Typo
symbol **$** before modx->db

`$queryInsertFile = $modx->db->query($insertFile);`

**Comment by mediengaarage** [comment]
Thanks, i changed it, and a few other also.
now i get a error

Call to a member function real_escape_string() on a non-object in /.../assets/modules/easy2/includes/models/e2g.public.class.php on line 225

Line 225:
$string = $modx->db->real_escape_string($string);

**Comment by bagi091** [comment]
`$string = $this->modx->db->escape($string);`

**Comment by mediengaarage** [comment]
Next error

Call to a member function fetch_assoc() on a non-object in /.../assets/modules/easy2/includes/models/e2g.module.class.php on line 4669

Line 4669:
while ($row = $modx->db->fetch_assoc($configsQuery)) {

**Comment by bagi091** [comment]
`while ($row = $this->modx->db->getRow($configsQuery)) {`

**Comment by mediengaarage** [comment]
Error line:
$queryDir = $modx->db->query($selectDir);

**Comment by bagi091** [comment]
line? file?

**Comment by mediengaarage** [comment]
Sorry!
Call to a member function query() on a non-object in /.../assets/modules/easy2/includes/models/e2g.public.class.php on line 774

**Comment by bagi091** [comment]
`$queryDir = $this->modx->db->query($selectDir);`

**Comment by mediengaarage** [comment]
Call to a member function fetch_assoc() on a non-object in /.../assets/modules/easy2/includes/models/e2g.public.class.php on line 782

Line 782:
while ($l = $modx->db->fetch_assoc($queryDir)) {

**Comment by bagi091** [comment]
`while ($l = $this->modx->db->getRow($queryDir)) {`

**Comment by mediengaarage** [comment]
Call to a member function free_result() on a non-object in /.../assets/modules/easy2/includes/models/e2g.public.class.php on line 788

Line 788:
 $modx->db->free_result($queryDir);

**Comment by bagi091** [comment]
`$this->modx->db->freeResult($queryDir);`

**Comment by mediengaarage** [comment]
I get an error in the module:
« MODX Parse Error »
Execution of a query to the database failed - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SETS' at line 1
SQL > SHOW CHARACTER SETS

require_once(string $var1)
assets/modules/easy2/index.php on line 53

Line 53:
return require_once $installFolder . DIRECTORY_SEPARATOR . 'index.php';


DBAPI->query('SHOW CHARACTER SETS')
assets/modules/easy2/install/index.php on line 113

Line 113:
$getChr = $modx->db->query("SHOW CHARACTER SETS");

**Comment by bagi091** [comment]
`$getChr = $modx->db->conn->get_charset();`
or try delete this line.

**Comment by Deesen** [comment]
@bagi091 Thanks!

**Comment by mediengaarage** [comment]
If i delete or rename it i get an other error:

Call to undefined method DBAPI::num_rows() in /.../assets/modules/easy2/install/index.php on line 123

Line 123:
if ($modx->db->num_rows($getCol) > 0) {

**Comment by bagi091** [comment]
it is new error

**Comment by mediengaarage** [comment]
yes its new

**Comment by bagi091** [comment]
moment

**Comment by bagi091** [comment]
new line 122
`if ($modx->db->getRecordCount($getCol) > 0) {`
new line 124
`while ($row = $modx->db->getRow($getCol)) {`

**Comment by mediengaarage** [comment]
is it right that line 122 to 124 now are:

if ($modx->db->getRecordCount($getCol) > 0) {
 if ($modx->db->num_rows($getCol) > 0) {
while ($row = $modx->db->getRow($getCol)) {

where close brackets?

**Comment by mediengaarage** [comment]
so i get this error:
syntax error, unexpected end of file in /.../assets/modules/easy2/install/index.php on line 214

**Comment by bagi091** [comment]
sorry
line 123 and 125 in your code (not 122 and 124)

**Comment by risingisland** [comment]
Would you guys mind starting a new branch for Easy2?
It would be great to have an updated version that the rest of could use too.

**Comment by bagi091** [comment]
I use [SimpleGallery](https://github.com/Pathologic/SimpleGallery)

**Comment by mediengaarage** [comment]
o.k. install without error. when i click install then i get an error:

Call to a member function query() on a non-object in /.../assets/modules/easy2/install/install.class.php on line 542

Line 542:
$res = $modx->db->query('SHOW TABLES FROM `' . $dbase . '`');

**Comment by risingisland** [comment]
@mediengaarage 
Would you mind sharing your final product once you get it working?

**Comment by mediengaarage** [comment]
@risingisland
of course i will sharing it

**Comment by bagi091** [comment]
`$res = $this->modx->db->query('SHOW TABLES');`

and line 550
`while ($row = mysql_fetch_row($res)) {`
replace to `while ($row = $this->modx->db->getRow($res,"num")) {`

and line 556
`if (!mysql_query('RENAME TABLE easy2_dirs TO ' . $this->modx->db->config['table_prefix'] . 'easy2_dirs')) {`
replace to `if (!$this->modx->db->query('RENAME TABLE easy2_dirs TO ' . $this->modx->getFullTableName('easy2_dirs') )) {`

and line 590
`$queryCreateDirTable = mysql_query($createDirTable);`
replace to `$queryCreateDirTable = $this->modx->db->query($createDirTable);`

and line 473 
`if (!mysql_query('ALTER TABLE ' . $this->modx->db->config['table_prefix'] . $table . ' ADD `' . $fieldName . '` ' . $fieldInfo . ' ' . $position))`
replace to `if (!$this->modx->db->query('ALTER TABLE ' . $this->modx->getFullTableName($table) . ' ADD \``' . $fieldName . '\`` ' . $fieldInfo . ' ' . $position))`
in this line need replace ` \`` ` to `

**Comment by mediengaarage** [comment]
Great, but a new error:
Call to a member function query() on a non-object in /.../assets/modules/easy2/install/install.class.php on line 674

Line 674:
$modx->db->query('ALTER TABLE ' . $this->modx->db->config['table_prefix'] . 'easy2_dirs CHANGE `cat_visible` `cat_visible` TINYINT(4) DEFAULT \'1\' NOT NULL AFTER `last_modified`');

**Comment by mediengaarage** [comment]
`$modx->db->query('ALTER TABLE ' . $this->modx->db->config['table_prefix'] . 'easy2_dirs CHANGE `cat_visible` `cat_visible` TINYINT(4) DEFAULT \'1\' NOT NULL AFTER `last_modified`');`

**Comment by bagi091** [comment]
replace `mysql_query `to `$this->modx->db->query`

**Comment by mediengaarage** [comment]
Call to a member function query() on a non-object in /.../assets/modules/easy2/install/install.class.php on line 700

Line 700:
$res = $modx->db->query('SELECT cat_right FROM ' . $this->modx->db->config['table_prefix'] . 'easy2_dirs WHERE cat_id=1');

perhaps Line 701 also:
if ($modx->db->num_rows($res) == 0) {

**Comment by bagi091** [comment]
700 
`$modx->db->query` replace to `$this->modx->db->query`
701
`mysql_num_rows` to `$this->modx->db->getRecordCount`
705
`mysql_query` to  `$this->modx->db->query`

**Comment by mediengaarage** [comment]
The line getting higher ...

Call to a member function query() on a non-object in /.../assets/modules/easy2/install/install.class.php on line 1355

Line 1355:
$result = $modx->db->query($select);

Line 1357:
 while ($l = $modx->db->fetch_assoc($result)) {

**Comment by bagi091** [comment]
1355
`mysql_query` to `$this->modx->db->query`
1357
`mysql_fetch_assoc` to `$this->modx->db->getRow`

**Comment by bagi091** [comment]
1391
1409
1412
`mysql_real_escape_string` to `$this->modx->db->escape`

**Comment by mediengaarage** [comment]
i also change it on lines:
1277, 1194, 1197, 1206

now error:
Call to a member function result() on a non-object in .../assets/modules/easy2/install/install.class.php on line 1207

Line 1207:
$result = $modx->db->result($select, 0, 0);

**Comment by bagi091** [comment]
`mysql_result($select, 0, 0)` to `$this->modx->db->getValue($select)`

**Comment by mediengaarage** [comment]
i change lines:
70
75
89
94
1250
1251

Installed successfully :-)!
I deleted Insall folder:

Call to undefined method DBAPI::fetch_assoc() in /.../assets/modules/easy2/includes/models/e2g.public.class.php on line 531

Line 531:
 while ($row = $modx->db->fetch_assoc($queryIndexFile)) {

same change than obove?

**Comment by bagi091** [comment]
yes
`mysql_fetch_assoc` to `$this->modx->db->getRow`

**Comment by mediengaarage** [comment]
I changed a lot of others ...
Backend seems to work now. all my folders and items are gone. 
When i want to synchronize it, theres a message that the browser does not support HTTP request.

Frontend i get a error:

Call to a member function fetch_assoc() on a non-object in /.../assets/modules/easy2/snippet.easy2gallery.php on line 25
Line 25:
while ($row = $this->modx->db->fetch_assoc($query_configs)) {

When i change it to:

while ($row = $this->modx->db->getRow($query_configs)) {

there is still an error:

Call to a member function getRow() on a non-object in /.../assets/modules/easy2/snippet.easy2gallery.php on line 25
Line 25:
while ($row = $this->modx->db->getRow($query_configs)) {

**Comment by bagi091** [comment]
`while ($row = $modx->db->getRow($query_configs)) {`

**Comment by mediengaarage** [comment]
i have changed a lot of other code.
Now the folder and the items where shown in frontend.
But i can't zoom the items.
Here is the frontend: [http://www.bairer-musi.de/bildergalerie-musifest.html](url)

In Backend there are no folder and items. I can not synchronize or load from server.
Also i can not make folder. There is no error, only a message, that it don't work.

Do you have any idea?

**Comment by mediengaarage** [comment]
I think there are so many wrong code, that it is very difficult to get all of this.
What can we do?

**Comment by bagi091** [comment]
In frontend not work, but url on item wrong. See template.

in backend. I need see the code.

**Comment by mediengaarage** [comment]
What is wrong with the url?
I have e2g at an other customer and here it works. But its modx 1.0.15: 
[http://www.baiern.eu/bildergalerie.html?sid=1&gid=10#1_10](url)
the url is the same.

Should i send you all the code?

**Comment by risingisland** [comment]
I believe that something is broken in "assets/modules/easy2/show.easy2gallery.php", because when linking directly to a target image: 
[http://www.baiern.eu/assets/modules/easy2/show.easy2gallery.php?fid=390](url) works as intended, 
but [http://www.bairer-musi.de/assets/modules/easy2/show.easy2gallery.php?fid=944](url) does not.

**Comment by bagi091** [comment]
yes. file assets/modules/easy2/show.easy2gallery.php use mysql_connect
but dont have $modx object.
it needs to be rewritten to use modx api

**Comment by mediengaarage** [comment]
Please tell me where?:

> <?php

// harden it
require_once('../../../manager/includes/protect.inc.php');

/**
 * EASY 2 GALLERY
 * @uses file to show the image for Easy 2 Gallery Module
 * @author Cx2 <inteldesign@mail.ru>
 * @author Temus <temus3@gmail.com>
 * @author goldsky <goldsky@fastmail.fm>
 */
error_reporting(0);

if (empty($_GET['fid']) || !is_numeric($_GET['fid'])) {
    $text = isset($_GET['text']) ? $_GET['text'] : 'Error';
    sh_err($text);
}

// MODx config
require_once '../../../manager/includes/config.inc.php';

$modx->db->connect($database_server, $database_user, $database_password) or
        sh_err('MySQL connect error');
$modx->db->select_db(str_replace('`', '', $dbase));
$modx->db->query("{$database_connection_method} {$database_connection_charset}");

// e2g's configs
$e2g_res = $modx->db->query('SELECT * FROM ' . $table_prefix . 'easy2_configs');
if (!$e2g_res)
    sh_err('MySQL query error for configs');
else {
    while ($row = $this->modx->db->getRow($e2g_res)) {
        $e2g[$row['cfg_key']] = $row['cfg_val'];
    }
}

// get the image file ID
$id = (int) $_GET['fid'];
$res = $modx->db->query('SELECT * FROM ' . $table_prefix . 'easy2_files WHERE id=' . $id);
if (!$res)
    sh_err('MySQL query error for files');

// get the filename
$row = $this->modx->db->getRow($res);
$filename = $row['filename'];

$res = $modx->db->query('SELECT A.cat_id, A.cat_name '
                . 'FROM ' . $table_prefix . 'easy2_dirs A, ' . $table_prefix . 'easy2_dirs B '
                . 'WHERE B.cat_id=' . $row['dir_id'] . ' '
                . 'AND B.cat_left BETWEEN A.cat_left AND A.cat_right AND A.cat_level > 0 '
                . 'ORDER BY A.cat_left'
);
if (!$res)
    sh_err('MySQL query error');

// get the file's path
$path = '';
while ($l = $modx->db->fetch_row($res)) {
    $path .= $l[1] . '/';
}

$fp = '../../../' . $e2g['dir'] . $path . $filename;
$fp = utf8_decode($fp);

/**
 *  WATERMARK
 */
if ($e2g['ewm'] != 0) {
    $inf = getimagesize($fp);

    if ($inf[2] == 1)
        $im = imagecreatefromgif($fp);
    elseif ($inf[2] == 2)
        $im = imagecreatefromjpeg($fp);
    elseif ($inf[2] == 3)
        $im = imagecreatefrompng($fp);
    else
        sh_err('Imagecreate error');

    if ($e2g['wmtype'] == 'text') {
        // X
        $len = strlen($e2g['wmt']);
        if ($e2g['wmpos1'] == 3)
            $x = $inf[0] - 10 - ($len * 6);
        elseif ($e2g['wmpos1'] == 2)
            $x = ($inf[0] - ($len * 6)) / 2;
        else
            $x = 10;

        // Y
        if ($e2g['wmpos2'] == 3)
            $y = $inf[1] - 20;
        elseif ($e2g['wmpos2'] == 2)
            $y = ($inf[1] / 2) - 5;
        else
            $y = 10;

        $textColor = imagecolorallocate($im, 0, 0, 0);
        imagestring($im, 2, $x - 1, $y, $e2g['wmt'], $textColor);
        imagestring($im, 2, $x + 1, $y, $e2g['wmt'], $textColor);
        imagestring($im, 2, $x, $y - 1, $e2g['wmt'], $textColor);
        imagestring($im, 2, $x, $y + 1, $e2g['wmt'], $textColor);
        imagestring($im, 2, $x + 1, $y + 1, $e2g['wmt'], $textColor);
        imagestring($im, 2, $x - 1, $y - 1, $e2g['wmt'], $textColor);

        $textColor = imagecolorallocate($im, 255, 255, 255);
        imagestring($im, 2, $x, $y, $e2g['wmt'], $textColor);
    } elseif ($e2g['wmtype'] == 'image') {

        $wmfp = '../../../' . str_replace('../', '', $e2g['wmt']);
        if (!file_exists(realpath($wmfp))) {
            sh_err('WM file not found');
        }

        $wminfo = getimagesize($wmfp);

        if ($wminfo[2] == 1)
            $wmi = imagecreatefromgif($wmfp);
        elseif ($wminfo[2] == 2)
            $wmi = imagecreatefromjpeg($wmfp);
        elseif ($wminfo[2] == 3)
            $wmi = imagecreatefrompng($wmfp);
        else
            sh_err('WM error');

        imageAlphaBlending($wmi, false);
        imageSaveAlpha($wmi, true);
        $wm_w = imageSX($wmi);
        $wm_h = imageSY($wmi);

        // X
        $len = strlen($e2g['wmt']);
        if ($e2g['wmpos1'] == 3)
            $x = $inf[0] - 10 - $wm_w;
        elseif ($e2g['wmpos1'] == 2)
            $x = ($inf[0] - $wm_w) / 2;
        else
            $x = 10;

        // Y
        if ($e2g['wmpos2'] == 3)
            $y = $inf[1] - 10 - $wm_h;
        elseif ($e2g['wmpos2'] == 2)
            $y = ($inf[1] / 2) - $wm_h;
        else
            $y = 10;


        imagecopy($im, $wmi, $x, $y, 0, 0, $wm_w, $wm_h);
        imagedestroy($wmi);
    }

    // SAVE
    //header("Content-type: image/jpeg");
    //imagejpeg($im);
    //imagedestroy($im);

    ob_start();
    header('Last-Modified: ' . date('r'));
    header('Accept-Ranges: bytes');
    header('Content-type: image/jpeg');
    header('Content-Disposition: inline; filename="' . $filename . '"');
    imagejpeg($im);
    imagedestroy($im);
    header('Content-Length: ' . ob_get_length());
    ob_end_flush();
} else {
    header('Content-type: image/jpeg');
    header('Location: ' . $fp);
    exit();
}

function sh_err($text) {
    $w = isset($_GET['w']) ? $_GET['w'] : 300;
    $h = isset($_GET['h']) ? $_GET['h'] : 200;
    $textHeight = isset($_GET['th']) ? $_GET['th'] : 5;

    header("Content-type: image/png");
    $im = @imagecreate($w, $h)
            or die("Cannot Initialize new GD image stream");
    $bgColor = imagecolorallocate($im, 255, 255, 255);
    $textColor = imagecolorallocate($im, 233, 14, 91);
    $text = trim($text) != '' ? $text : "Image error";
    $y = $h/2 - $textHeight * 4;
    $textWidth = imagefontwidth($textHeight) * strlen($text);
    $center = ceil($w / 2);
    $x = $center - (ceil($textWidth / 2));
    imagestring($im, $textHeight, $x, $y, $text, $textColor);
    imagepng($im);
    imagedestroy($im);
    exit();
}

**Comment by mediengaarage** [comment]
i still don't see folder or files.
I can't make folder.
when i want to upload a image i get an error:
Call to undefined method DBAPI::insert_id() in /.../assets/modules/easy2/includes/models/e2g.module.class.php on line 1856

Line 1856:
'fid' => $this->modx->db->insert_id()

**Comment by mediengaarage** [comment]
When i try to make a folder i get error:
Call to a member function query() on a non-object in /.../assets/modules/easy2/includes/models/TTree.class.php on line 52

Line 52: 
$result = $modx->db->query($query);

**Comment by mediengaarage** [comment]
Something new?
