### ISSUE TITLE
Feature: Sort tree like Revolution

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#588]
I have a wish that I could sort the tree by moving the pages like is possible in Revolution.
Pick up the pagetitle and move it. **Timesaver!**

Its just way easier to sort it and don't open any resources and change the menuindex.
Also hate the fact to start at menuindex 999 for newsitems and count down.

**Comment by Deesen** [comment]
Well not exactly what you asked for but almost possible with DocManager (didnt know myself before :-) ) : https://forums.modx.com/thread/97722/change-easily-the-menuindex

**Comment by bossloper** [comment]
I was suggesting the sort be pulled out of docmanager and referenced directly from the tree menu:
https://github.com/modxcms/evolution/issues/532

**Comment by fourroses666** [comment]
I will close this one!
