### ISSUE TITLE
Warning: Cannot modify header information - headers already sent by ..

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#596]
When duplicating a resource I get a back-end error message.
Just updated some site to 1.1 but its still there.
The page is duplicated but you can only see that after refreshing the tree.

`Warning: Cannot modify header information - headers already sent by (output started at /home/xxx/public_html/manager/includes/document.parser.class.inc.php:1101) in /home/xxx/public_html/manager/processors/duplicate_content.processor.php on line 35`

Any idea how to solve this?

**Comment by Deesen** [comment]
If you use v1.1, line 1101 echos the return of a plugin. I´m just guessing: It seems a plugin causes an error-message, or some other unnessecary output like whitespace. Do you have turned off error-reporting in Modx-config?

**Comment by fourroses666** [comment]
I think its PHx.

When setting on errors show all, on the front-end (website) I get a Parse Error:

**`Error : Undefined variable: key`**

```
ErrorType[num] 	NOTICE[8]
File 	/home/xxx/public_html/manager/includes/document.parser.class.inc.php
Line 	1242
Source 	else $key .= $char;
Current Snippet 	if
Current Plugin 	PHx(OnParseDocument)
```
https://github.com/modxcms/evolution/blob/master/manager/includes/document.parser.class.inc.php#L1242


PHx Plugin:

```
if (!class_exists('PHxParser')) {
    include MODX_BASE_PATH . "assets/plugins/phx/phx.parser.class.inc.php";
}
$e = &$modx->Event;
switch($e->name) {
    case 'OnParseDocument':
        $PHx = new PHxParser($phxdebug,$phxmaxpass);
        $PHx->OnParseDocument();
        break;
}
```
Any idea whats wrong?

_I can understand front-end errors but didn't know it could give back-end errors._

**Comment by fourroses666** [comment]
But when I remove this PHx plugin then still the same error message/issue on duplicating resources.

**Comment by Deesen** [comment]
If you set error-level to "error + warning + information" it will show these "NOTICE"-messages, so better set it to "error" or "error + warning" to skip these NOTICEs.

**Comment by fourroses666** [comment]
I have that set as; _ignore all_, but it still gives this warning in the manager when duplicating a resource.

**Comment by Deesen** [comment]
I guess so too, maybe you can change error-reporting level in your hosters backend? Or some htaccess changes it? Direct access to server is not possible I guess?

**Comment by Deesen** [comment]
You can try last commit to avoid the "notice".

**Comment by fourroses666** [comment]
Its still there :'-(

**Comment by Deesen** [comment]
Hard to figure out, don´t know where to start.

**Comment by fourroses666** [comment]
Yea I understand, I do have Cpanel access.

Nothing special in Error report.
ModSecurity is on.

I can try to change the PHP version thow.

**Comment by Deesen** [comment]
You can try each of them, why not? But I think I cannot help without being able to "play" with some files, or see which plugins you are using, how they are set up etc.. maybe one of your plugins is using a wrong event and gets fired within the manager, where its not supposed to be? Just guessing..

**Comment by fourroses666** [comment]
Updated to PHP 5.6 and error is gone :)))))) 

Thanks for your time
