### ISSUE TITLE
Add "longtitle" to tree option - Enhancement

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#598]
Tools / Configuration / Interface & Settings => Display Name in Resource Tree

Available options:

```
[*pagetitle*]
[*menutitle*]
[*alias*]
[*createdon*]
[*editedon*]
[*publishedon*]
```

As I am not a coder, Is it possible to add:

`[*longtitle*]`

**Comment by Deesen** [comment]
No problem.

**Comment by modxuser** [comment]
Great stuff, thanks

**Comment by modxuser** [comment]
I have downloaded the Develop branch and added your changes to the two files - installed over a 1.1RC2 version and wanted to change to longtitle - its not available

As seen in the image attached
![resource-tree-name](https://cloud.githubusercontent.com/assets/1859868/14453920/dc40a298-0097-11e6-8921-be4b9bccdbc7.png)

**Comment by Deesen** [comment]
You can choose it directly in the tree:

![tree](https://cloud.githubusercontent.com/assets/8569221/14454098/f4a8f168-0098-11e6-8a20-f2b1049158e8.png)

**Comment by modxuser** [comment]
Just found that out - see https://github.com/modxcms/evolution/issues/600

But it should be in the default configuration

**Comment by Deesen** [comment]
For this reason you can simply leave it as "default" :

![tree2](https://cloud.githubusercontent.com/assets/8569221/14454639/ccea3a94-009b-11e6-8dd0-1fb27ec2c3c2.png)

My opinion is, this way its highly flexible and users don´t need to have admin-rights to change the node-title. So they can order by / see published_on etc in the tree, find out in an overview if something is missing etc.

**Comment by modxuser** [comment]
As above - this is something I wouldn't do and as such, if it's to stay in Evo, I will have to find a way of removing it

**Comment by modxuser** [comment]
I have put your changes for the nodes.php back in place and have modified "mutate_settings.dynamic.php" as follows:

Line: 1243

`$option = array('pagetitle','longtitle','menutitle','alias','createdon','editedon','publishedon');`

Simply added "longtitle"

This works :)
