### ISSUE TITLE
MODxCarbon - Sort site tree

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#600]
When clicking on the "Sort Site Tree" button in the left panel, the drop down is messed up - as seen in the attached image

![sort-site-tree](https://cloud.githubusercontent.com/assets/1859868/14454114/07f7616e-0099-11e6-90e7-3c6788845a12.png)

**Comment by Deesen** [comment]
Maybe you want to style it "perfect" yourself? manager/media/style/MODxCarbon/style.css line 588 #floater has fixed height/width and maybe needs some additional styling.

**Comment by modxuser** [comment]
I would personaly remove it: https://github.com/modxcms/evolution/issues/598#issuecomment-208780719

**Comment by Deesen** [comment]
Please think about its possibilities, not about the confusion it may did to you at first. I already used it a lot, incl some of my customers...

**Comment by modxuser** [comment]
I just looked at a 1.1 install I did recently - this feature isn't in it - so I presume this has only just been added

If it is to stay in Evo, is it possible to set a config to not display it ?

**Comment by Deesen** [comment]
Yes it has been added after 1.1 release. And I try to use the dev-version on customer installs if possible, so I can test it out live and in detail. Thats is why it has been used already "a lot".

Reg config, if others think the same we should add it. So I would like to wait first for other opinions.

There are probably some more features in the dev-version you are not aware of. And I think we cannot add a config-key for every little new feature. Just my 2 cents..

**Comment by modxuser** [comment]
Is it not plausible to let the community know what features are being added or taken away before it happens ?

That way the DEV team would know what the end-users think and it would possibly save valuable time and effort

**Comment by fourroses666** [comment]
Is this such a big deal?

I personally never used it and I'm pritty sure my clients didn't either.
But it can't do any harm to add this function if you ask me.

And on new releases of Evo there is a list of Changes, prolly will be added there.
https://raw.githubusercontent.com/modxcms/evolution/1.1/install/changelog.txt

**Comment by modxuser** [comment]
Don't get me wrong, I have no problem with the function

I have a problem with the new / additional position - this setting is already in the default configuration and doesn't need to be where it is now - see here: https://github.com/modxcms/evolution/issues/598#issuecomment-208776496

My original enquiry: https://github.com/modxcms/evolution/issues/598#issue-147653524

**Comment by Deesen** [comment]
Maybe we can just remove the setting from configuration instead, which is not nessecary anymore?

**Comment by Deesen** [comment]
Any maybe leave a notice in configuration like "note-title can be set now in manager tree".

**Comment by modxuser** [comment]
@Deesen 

Call me old fashioned, but something that works perfectly OK, doesn't need to be removed just because something new comes along

**Comment by Deesen** [comment]
Ok but that doesn´t mean everybody is old fashioned ;-) so let us please wait for more opinions. With the "default"-option I tried to make best compromise between the new feature and old modx-setting.

**Comment by bossloper** [comment]
Surely both the default config option and the new setting work together and are both needed.
The 'default config' option is a site wide setting, whereas the new setting on the tree enables each user to overridde this default if they want?

Or am I misreading it?

**Comment by Deesen** [comment]
This is exactly the way it works.

**Comment by modxuser** [comment]
I am not saying everyone is old fashioned. It works perfectly OK where it is

I suggest publishing it in the Forum then, or at least letting others know who don't use GutHub some other way

**Comment by modxuser** [comment]
Ah, OK

I wasn't aware that it is supposed to be like that

Thats the problem in my opinion when the community are not informed about new features - a lack of information, if you don't know the facts or in this case how to use it, you can jump to wrong conclusions as I probably have

**Comment by modxuser** [comment]
So the combination of both is there to override defaults - OK, no problem

I have added longtitle to the default configuration, as can be seen here: https://github.com/modxcms/evolution/issues/598#issuecomment-208820201

**Comment by bossloper** [comment]
Maybe it just needs the wording updating on the config setting.
Something like:
"Select the default Resource field to show as the Resource name in the Resource Tree. This can be overridden from the site tree."

**Comment by nick0** [comment]
Just putting my 5c in...
I prefer the config only setting - and I will keep using menu title from there.
Using long title has the potential to get a bit long for labels in the tree I think. 
And the extra field control looks a bit messy given the lack of real estate.
Is it possible to hide this new field with ManagerManager or turn it off in the config?

**Comment by nick0** [comment]
> Thats the problem in my opinion when the community are not informed about new features - a lack of information, if you don't know the facts or in this case how to use it, you can jump to wrong conclusions as I probably have

I agree with modxuser. Each community release, this one included, it sounds like there are some great new features but with a lack of documentation / instructions on the new features its hard to know about them. The changelog is not enough to know what they are and how they work etc.

**Comment by modxuser** [comment]
@Deesen 

> manager/media/style/MODxCarbon/style.css line 588

Changed from
```
#floater {
	display: none;
	position: absolute;
	width: 200px;
	height: 50px;
	top: 25px;
	left: 4px;
	background: #fff;
	border-bottom: 1px solid #666;
	z-index: 500;
}
```
To:
```
#floater{
	display:none;
	position:absolute;
	top:25px;
	left:0;
	width:auto;
	height:auto;
	padding:5px 5px 5px 0;
	background-color:#fff;
	border-bottom: 1px solid #666;
	z-index:500;
}
#floater table{
	background:inherit;
}
#floater table select{
	display:block;
}
```

**Comment by fourroses666** [comment]
https://github.com/modxcms/evolution/pull/601

**Comment by Deesen** [comment]
Thanks!

**Comment by modxuser** [comment]
I have referenced this feature on the forum, here: https://forums.modx.com/thread/99924/evo---new-feature---sort-site-tree
