### ISSUE TITLE
New Feature - docBlock / Information-Tab

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#603]
As I´m working on a new feature right now, I want to ask for your opinions before "shooting to fast". In actual dev-version it is possible now to add additional infos like links to a components docBlock, so to render them nicely in a separate tab. Maybe this way we can raise the "documentation"-mentality a bit in future.

For example let´s take component "AjaxSearch".

The **docBlock** has additional parameters: `@documentation`, `@reportissues`, `@author`
Also `@link` is possible to add "further links" for whatever reason (not in this example).

![docblock-1](https://cloud.githubusercontent.com/assets/8569221/14461265/0146aa36-00c2-11e6-8caa-19bdb796b194.png)

This fills the **Information-tab** (user-friendly list with clickable links etc)

![docblock](https://cloud.githubusercontent.com/assets/8569221/14461004/f78be5de-00c0-11e6-83b9-ff818f03505f.png)

What is your opinion? Anything that could be improved? Maybe additional "info"-parameters?

**Comment by modxuser** [comment]
+1

The only thought I have is if linked pages are moved or deleted

**Comment by fourroses666** [comment]
:+1: I have no additions. Looks good.

**Comment by Deesen** [comment]
Reg documentation and links, of course they will be added, corrected or removed with every Modx-update. Everybody for example can open issues to propose or remove links.

**Comment by Nicola1971** [comment]
+1

**Comment by nick0** [comment]
Wow, this is wonderful. Great work!

**Comment by pmfx** [comment]
+1

**Comment by Deesen** [comment]
Seems everybody is happy with it, so I finished adding docBlocks to all default snippets and plugins, and also tried to check&iterate version-no when nessecary: https://github.com/modxcms/evolution/pull/597
