### ISSUE TITLE
Duplicate action in index.php

### ISSUE THREAD

**Issue by vvp33** [modxcms/evolution#605]
Duplicate action in /manager/index.php. Number duplicate is 54.

**Comment by Deesen** [comment]
My fault.. fixed it.

**Comment by vvp24** [comment]
Tanks

**Comment by bossloper** [comment]
can be closed?

**Comment by bossloper** [comment]
still needs closing...

**Comment by modxuser** [comment]
@vvp33 can you close this issue please if it has been resolved, thanks
