### ISSUE TITLE
Is there something like Contentblocks?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#608]
Is there something like Contentblocks? 

So you can be able to choose what TV(s) you want to add and be able to sort these blocks.
Would make it so much easier and fun to play with the manager. MultiTV comes close but as far as I know it shows the same block everytime.

As example it could be **_something_** like this:
![fc](https://cloud.githubusercontent.com/assets/523389/14810093/659d1158-0b91-11e6-8846-5a2d5a00d8c9.gif)

Each button would load a "chunk" and their TVs.

**Comment by Deesen** [comment]
I already bookmarked "Sir Trevor" (like your screenshot, but frontend-editing, maybe also in manager?) as I would love to have a relyable Evo-port of it but no time yet: http://madebymany.github.io/sir-trevor-js/example.html

In the meantime you can achieve something similar with MultiTV. You can create different tabs and MultiTV will save the last choosen tab as placeholder [+fieldTab+] (which can act as your "choosen row-template"). So refering to your screenshot in tab 1 you would place "address", in tab 2 "button" and so on. In Frontend you can render these rows with the MultiTV-snippet using a chunk like:

`[[if?&is=[+fieldTab+]:eq:address &then=@TPL:your adress-template / chunk]]`
`[[if?&is=[+fieldTab+]:eq:button &then=@TPL:your button-template / chunk]]`
...

**Comment by fourroses666** [comment]
**WOW that 'Sir Trevor' looks very awesome! ** 

Need to play with multiTV. Thanks for pointing that out. I now remember I have talked about that with Jako it could be possible indeed by using these tabs.

**Comment by Deesen** [comment]
Yes but downside when using tabs is, you always need to use unique input-ids. So if you want to create all 17 contentblocks like in your screenshot, and let´s say each of them has 5 input-fields like "title, content, image, css-class, option x" then you have to create 85 unique input-fields in MultiTV-config. From my experience if you want to make it really nice&flexible, you need a lot more inputs. So this solution is not 100% satisfying (for me). For this reason I wrote my some custom PHX-modifiers and snippet. So you can configure MultiTV so to get a form like this per row:

![m1](https://cloud.githubusercontent.com/assets/8569221/14814733/ddac67aa-0ba7-11e6-98b7-4217f6aa22c9.png)

And in manager it looks like:

![m2](https://cloud.githubusercontent.com/assets/8569221/14814737/e655c78e-0ba7-11e6-8267-cb09b8d6e66a.png)

**Comment by fourroses666** [comment]
Thats allot of settings! Looks like it does work.

**Comment by fourroses666** [comment]
New for Revolution: https://modx.com/extras/package/structures

**Comment by Deesen** [comment]
Here if you like to play.. I used it on several websites and it is working relyable. I tried to make a translatable version which can be easily installed. Hope it works -> https://github.com/Deesen/multiTvLayout

**Comment by fourroses666** [comment]
Nice, will have a look :) (after the weekend 😞 )

**Comment by fourroses666** [comment]
Have installed and a quick look, it works but not really how I'd like to have it.
I will close the issue. Maybe in the future some cool stuff like sir trevor can be implemented.
Can't think that straight now lol.

--

Something else, you did some front-editing stuff when adding a class or # before a TV it was possible to edit it? Whats up with that cool stuff?

**Comment by Deesen** [comment]
You can test it with TinyMCE4 by enabling inline-mode in plugin-config and using # inside placeholders like `[*#content*]`.

Reg. multiLayout, I guess its too complicated to set up, right? Too much PHP.. but I was able to create the content for several websites using it with an existing templates with each their own CSS-classes etc.. so basically you have everything in hand you need to create bootstrap-content with columns and rows and images etc.

contentBlocks is a monster. It will need serious effort to create the same for Evo and it will not be free of charge I guess. I had no success to extend Sir Trevor or http://code.viget.com/colonel-kurtz/ further than the demo.
