### ISSUE TITLE
шаблоны

### ISSUE THREAD

**Issue by urbanklpn** [modxcms/evolution#610]
нашел неудобность.. када шаблон создаешь на 1.1 оно сначала без галки по дефолту создаецца "Template selectable when creating or editing ressources." и не выбрать в списке
пастаянна забываю поставить
можт по дефолту ее включить?

**Comment by Deesen** [comment]
Its already in next update: When creating a "new template" the checkbox "template selectable" is checked by default: https://github.com/modxcms/evolution/commit/b4ced1fa5a0282f1dc7aca4fc6eac1e019537467

**Comment by urbanklpn** [comment]
thx

**Comment by bossloper** [comment]
can be closed?...
