### ISSUE TITLE
Ditto Pagination - Doesn't work after update

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#616]
The link code generated by Ditto in Evo 1.1 looks like this:
`index.php?id=229?start=10`

Note the double question mark.

For more information please read the [forum post here](https://forums.modx.com/thread/100080/ditto-2-1-1-pagination-not-working-with-evo-1-1)

**Comment by Deesen** [comment]
Hmm seems to be related also to this issue https://github.com/Jako/multiTV/issues/154

**Comment by modxuser** [comment]
@Deesen 

Looks like it

Looking at the link - if FURLs were active it would in theory work
