### ISSUE TITLE
500 error on upgrade

### ISSUE THREAD

**Issue by terrybarth** [modxcms/evolution#617]
I posted this in the Modx Evo forum and someone suggested that it would better to post it here.

I'm trying to update Modx Evo 1.0.14 to 1.1. After uploading the zip file and unzipping it, I got a server 500 error on both the front-end and the manager. I never got to running the install. Just unzipping the files resulted in the 500 error.

I checked the .htaccess file, didn't see anything out of the ordinary.

I restored all the files from my backup, created just prior to the unzip and the site came back.

I thought perhaps the unzip function failed somehow so I manually uploaded the unzipped files. I uploaded the assets folder, check the front-end, all good. Same after uploading the manager folder. However, after uploading the install folder, the 500 error returned.

Just for kicks, I checked to see if the installer would run and that page came up. I started the install, all the pre-checks were good, so I started it. It confirmed the status on all the extra updaets, then stopped. I tried the manager login, that page appears, but I can't login. It just returns to the login form with no errors.

Now I just noticed that the hostmonster server is running php 5.2.17. Might this cause all of this trouble? If not, anyone have any thoughts about what's going on?

**Comment by bossloper** [comment]
You might need/not have MySQLi installed on the server?

**Comment by terrybarth** [comment]
This is an upgrade, not a new install. The site has been running for years. How could it not have MySQL?

**Comment by Deesen** [comment]
MySQL**i**, not MySQL ;-) because its deprecated: http://stackoverflow.com/a/2190766/2354531

**Comment by terrybarth** [comment]
I checked the phpinfo and I do see MySQLi on the list. So I believe it is there. This is on Hostmonster shared hosting. 

However, I never even got to run the install (see sequence above). The error appeared just after unzipping the modx zip file.

**Comment by Deesen** [comment]
I just found a way to put my hoster-account back to PHP 5.2 and immediately MODX stops working. So MODX needs at least 5.3.

**Comment by Deesen** [comment]
The installer only checked for 5.0.0 but 5.3 is required.

**Comment by terrybarth** [comment]
Any thoughts on why I get a 500 server error after unzipping the modx zip file.

**Comment by Deesen** [comment]
As you noticed you use PHP 5.2.17 but MODX needs minimum 5.3.

**Comment by terrybarth** [comment]
I'm sorry to be a pain. . . 

I understand how that would cause the install process to fail, but I don't understand how that's relevant to simply unzipping the files to the server.

I just copied the modx zip file to the server, unzipped it and suddenly I have a 500 server error on refresh.

**Comment by bossloper** [comment]
Because unzipping the files overwrites the assets and manger folders with new code regardless of if you have run the install. I.e. a lot of snippets/plugins and modules reference files in the assets folder that at the moment you unzip will be updated. Running the install mainly updates the database information.

**Comment by terrybarth** [comment]
Ah, got it. I've updated php to 5.6, the latest offered on hostmonster. I'll give it another try.

Thanks for your patience.

**Comment by bossloper** [comment]
php 5.6 does require all snippets/plugins/modules to be using MySQLi and so all database calls should be via the modx DBAPI. You might just find if you have any older third party snippets/plugins that they do not work if not coded with the DBAPI. If it is easy to change php version you might want to start with  php 5.4 and work up from there!

**Comment by Eoler** [comment]
> php 5.6 does require all snippets/plugins/modules to be using MySQLi

Not really, deprecated MySQL library functions weren't removed before PHP 7.
Disabling deprecated/notice PHP error level messages is enough:
http://forums.modx.com/thread/96325/modx-and-php-5-5-x#dis-post-521224

**Comment by terrybarth** [comment]
With the newer version of php, 5.6, the install worked flawlessly.

Thank you all for your help.

**Comment by bossloper** [comment]
"Disabling deprecated/notice PHP error level messages is enough"
- Fine as a short-term work around, but it is there as a safety net. I'd be carful of running with these notices disabled indefinitely. You might get caught out after a couple of php upgrades if you are not aware of something (not necessarily just MySQL) that is to be removed completely from future php versions.

**Comment by bossloper** [comment]
I think this can be closed now...
