### ISSUE TITLE
The resource name in the tree

### ISSUE THREAD

**Issue by Fr3ddyCruger** [modxcms/evolution#618]
The resource name in the tree - dont work :)

always shows only - [*pagetitle*]

**Comment by Deesen** [comment]
Cannot recreate that issue. Which version?

**Comment by Fr3ddyCruger** [comment]
evo 1.1 (last from github)

**Comment by Fr3ddyCruger** [comment]
http://i11.pixs.ru/storage/4/8/2/345345png_9844122_21812482.png

**Comment by Deesen** [comment]
"Default" will display the setting from configuration. I guess your setting is on "Resource´s title" as per screenshot:

![tree](https://cloud.githubusercontent.com/assets/8569221/15038864/0d70dc12-12a8-11e6-83dc-3fcad808b227.png)

**Comment by Fr3ddyCruger** [comment]
Why this option in two places? 0.0

**Comment by Deesen** [comment]
It was already a topic ;-) :

  -  https://forums.modx.com/thread/99924/evo---new-feature---sort-site-tree
  -  https://github.com/modxcms/evolution/issues/598

But as the community is rather quiet and widespread, its hard for developers like me to ask or wait for opinions. So I always try to find a compromise between new features and not breaking old behaviours.

Added a note to configuration to avoid confusion:

![note](https://cloud.githubusercontent.com/assets/8569221/15039328/780e3a02-12ac-11e6-8c58-13ec8dbdee3d.png)

**Comment by Fr3ddyCruger** [comment]
thnx)))
