### ISSUE TITLE
plugin properties problem 

### ISSUE THREAD

**Issue by Fr3ddyCruger** [modxcms/evolution#619]
http://pixs.ru/delete/21814639/2251296/

1.1 final, does not show the field to display the plug-in parameters) broke

**Comment by Deesen** [comment]
Pls paste the exact config-string here.

**Comment by Fr3ddyCruger** [comment]
&eadbg=Debug Enabled?;list;true,false;false &word_wrap=Word Wrap Enabled?;list;true,false;true &font_size=Font Size;list;8,9,10,11,12;9 &defaultHeight=Initialize editor height;list;300px,400px,500px,600px,700px;500px &min_height=Minimum editor height;list;200,300,400;400 &start_highlight=Initialize with highlighting enabled?;list;true,false;true &allow_toggle=Allow editor toggling?;list;true,false;true &allow_resize=Allow editor resizing?;list;y,n;y &fullscreen=Initialize editor in fullscreen mode?;list;true,false;false &replace_tab_with_spaces=Replace tab with spaces?;list;// No,/* Yes */;/* Yes */ &tab_as_spaces=How many spaces per tab?;list;3,4,5;4 &plugins=Active Plugins;string;modx, syntax_selection &catchunload=Try/Catch on Unload?;list;yes,no;yes&compressor=PHP Compressor Enabled?;list;0,1;0

**Comment by Fr3ddyCruger** [comment]
as with all plugins, when you press the "update" does not show the parameter fields

**Comment by Deesen** [comment]
With "all plugins"? Can you check the browser-console for javascript-errors? For me your config-string works fine:

![plugin](https://cloud.githubusercontent.com/assets/8569221/15041876/a4a8eb62-12bf-11e6-9260-7239a985fdb7.png)

**Comment by Fr3ddyCruger** [comment]
8) someone put to use by default codemirror and therefore did not work. When using the same editarea, two shows at once the editor) that there is not normal

**Comment by Deesen** [comment]
Sry I don´t exactly understand "two editors at once". Is your problem solved, or a new problem?

**Comment by Fr3ddyCruger** [comment]
I had not set - when installed, the problem was solved, but there was another. Now two editors. - Sewn in probably, and plug-in parameters do not work without it (an error in the console)

http://i9.pixs.ru/storage/2/3/9/MODXjpg_5290308_21815239.jpg

**Comment by Fr3ddyCruger** [comment]
if codemirror is already integrated into the system, it is possible to give up editarea. But there is also a problem, namely the problem with finding and replacing text in the editor. field moves down

ctrl+f
http://i11.pixs.ru/storage/3/1/5/234234234j_2401291_21815315.jpg

**Comment by Fr3ddyCruger** [comment]
a vicious circle) no codemirror = do not work in the parameters of plug-ins, and with it immediately two editors (since codemirror use the system default)

- To codemirror does not work properly search and replace, the search field is not fully visible :)

**Comment by Deesen** [comment]
Does the circle gets broken by these changes? ;-)

**Comment by Fr3ddyCruger** [comment]
options in plugins and left without editor), if you turn off codemirror 8)

**Comment by Deesen** [comment]
Above changes are not merged yet, so you need to download my fork: https://github.com/Deesen/evolution

**Comment by Fr3ddyCruger** [comment]
thank you very much that support it)) it works
