### ISSUE TITLE
Subdomain issues?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#620]
I have upgraded from 1.0.14 -> 1.1 but somehow there are issues.

Codemirror isn't putting the numbers on the right place. 
My templates ordening are mixed up?!

Also with the default theme. My guesses are its because I'm on a subdomain (test.domain.com).
Already did a re-upgrade but no luck.

![codemirr](https://cloud.githubusercontent.com/assets/523389/15107555/ba0ff1c6-15d0-11e6-80d0-905e11a77e46.jpg)
![huh](https://cloud.githubusercontent.com/assets/523389/15107556/ba15187c-15d0-11e6-9e88-fc801ac4301f.png)

**Comment by fourroses666** [comment]
Codemirror issue is fixed. Did some changes on te config of the plugin.

**Comment by Deesen** [comment]
Which changes?

**Comment by fourroses666** [comment]
Just some settings, don't know which was the one. I thought I changed the lineWrapping one. But now I can't reproduce the bug!

**Comment by fourroses666** [comment]
This fixed my templates sorting; 
https://github.com/modxcms/evolution/commits/develop/manager/actions/resources.static.php
