### ISSUE TITLE
Show value $_GET, $_POST, $_COOKIE, $_SERVER and $_SESSION

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#621]
https://forums.modx.com/thread/99775/output-value-of-get-post-cookie-server-session
Show value $_GET, $_POST, $_COOKIE, $_SERVER and $_SESSION

`[!$_GET['username'] !]`
`[!$_GET['username']:ifempty=<form><input name="username"></form>!]`
`[!$_SERVER['REQUEST_TIME']:dateFormat='Y-m-d'!]`
`[!$_SERVER['HTTP_USER_AGENT']:find='Chrome':then='Chrome':else='Other'!]`

http://mng.demo.modx.jp/pack_list/Evolution/modx1015j.html
Sample

**Comment by yama** [comment]
https://github.com/modxcms/evolution/issues/622
https://github.com/modxcms/evolution/issues/623
Combination

**Comment by MrSwed** [comment]
is it safe ?

**Comment by MrSwed** [comment]
with phx get same error https://github.com/modxcms/evolution/issues/623#issuecomment-219452130
Parse error: syntax error, unexpected ')' in /manager/includes/document.parser.class.inc.php(1284) : eval()'d code on line 1
i try simple 
`[!$_SESSION["usertype"] !]`
but 
`[!$_SESSION !]`
is work - show all array

**Comment by yama** [comment]
Thanks for your information.
I will fix it later.

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/813160242249b27ff74fa3c0927555fcd303bc37/manager/includes/document.parser.class.inc.php#L1191-L1197
Security Considerations.
