### ISSUE TITLE
MODIFIERS class into core (PHx)

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#623]
https://github.com/modxcms-jp/evolution-jp/blob/develop/manager/includes/extenders/ex_modifiers.php
- Light weight than PHx plugin
- It can also be used for chunks and snippets
- Flexible
- Easy to read
- Delimter free ( ' " \` )
- Many modifiers
- Compatible with PHx plugin
- It can coexist with PHx plugin

```
[*longtitle:ifempty=[*pagetitle*]*]
```
```
[*longtitle:ifempty='[*pagetitle*]'*]
```
```
[*longtitle:ifempty="[*pagetitle*]"*]
```
```
[*longtitle:ifempty([*pagetitle*])*]
```
```
[*longtitle:ifempty('[*pagetitle*]')*]
```

**case-insensitive**

```
[*template:is(1):then(Top page):else(Sub page)*]
```
```
[*template:IS(1):THEN('Top page'):ELSE('Sub page')*]
```

**Multi line**

```
[*id
  :is(1)
  :then(Top)
  :else(Other)
*]
```

```
[*email:spam_protect*]
```
```
[*price:number_format*]
```
```
[*content:addBreak*]
```
```
[*pagetitle:strip_tags*]
```

```
[(site_name:escape)]
```
```
{{Chunk:escape}}
```
```
[+placeholder:escape+]
```

```
[[Snippet:escape?param=1&param2]]
```
```
[!$_SERVER['REQUEST_TIME']:dateFormat('Y-m-d H:i:s')!]
```

```
[*pict:is_image:tpl('<img src="[+value+]">')*]
```

```
[+image:isNotEmpty
  :then('<img src="[[phpthumb? &input=`[+image+]` &options=`w=300`]]" />')
  :else('[+wf.linktext:substr(0,1)+]')
+]
```

```
[*pub_date:ifEmpty('[*publishedon*]'):dateformat=`%d.%m.%Y`*]
```

```
<@IF: [*id:is('[(site_start)]')*] >
This is Top page
<@ENDIF>
```

```
<@IF:[!$_SERVER['REQUEST_TIME']:dateFormat('H'):<(12)!]>
Morning now
<@ENDIF>
```

http://php.net/manual/en/function.date.php
PHP Date format

http://mblo.info/matome/modifiers/

**Comment by MrSwed** [comment]
@yama 
- What about the two passes, as there is a lack in phx ?
- It is possible to use external custom modifiers from phx ([for example](https://github.com/Evolution-extras/PHx-Modifiers/tree/master/assets/plugins/phx/modifiers)) ? What need to do: rename files, or change vars also ?
- English documentation? (Google poor translator of technical documentation :)

**Comment by yama** [comment]
@MrSwed 
https://github.com/modxcms/evolution/blob/a01fad974f6efce523b22534f7c13f384158cf83/manager/includes/extenders/modifiers.class.inc.php#L837-L844
There are external custom modifiers location.

1. /assets/modifiers/mdf_{mod_name}.inc.php
2. /assets/plugins/phx/modifiers/{mod_name}.phx.php
3. /assets/plugins/phx/modifiers/{mod_name}.phx.php
4. /extenders/modifiers/mdf_{mod_name}.inc.php
5. /manager/includes/extenders/modifiers/mdf_{mod_name}.inc.php

Sorry, english document does not yet exist.

**Comment by MrSwed** [comment]
>It can coexist with PHx plugin

can not :(
[here ](https://github.com/modxcms/evolution/blob/a01fad974f6efce523b22534f7c13f384158cf83/manager/includes/extenders/modifiers.class.inc.php#L282)I get error on standart using phx
```
Parse error: syntax error, unexpected ')' in ../public_html/manager/includes/extenders/modifiers.class.inc.php(282) : eval()'d code on line 1

Parse error: syntax error, unexpected ')' in ../public_html/manager/includes/extenders/modifiers.class.inc.php(282) : eval()'d code on line 1

```
I use a lot of phx in my [templates](https://github.com/MrSwed/modx-1.x-swed/blob/master/assets/element/chunk/Template/CONTENT.tpl)

**Comment by yama** [comment]
OK, I will fix it later.

**Comment by yama** [comment]
![01](https://cloud.githubusercontent.com/assets/73999/16573997/2521723a-42b5-11e6-8f56-cb6dab1873cc.png)
Added new setting.

**Comment by janniconl** [comment]
What exactly is the main advantage of this addion, compared to PHx? I can almost do anything with PHx. Why should I use this?

Could you please DISABLE this new option by default (set it to "No")?

I am also using PHx a LOT and these latest additons gave me a lot of errors like this:
````
[Tue Jul 05 18:20:02 2016] [error] [client 82.73.176.114] PHP Fatal error:  Call to a member function phxFilter() on a non-object in /home/[mydomainname]/public_html/manager/includes/document.parser.class.inc.php on line 1077
```` 

Disabling Enable Filters helped, thankfully.

**Comment by yama** [comment]
> PHP Fatal error:  Call to a member function
It's basic bug. Could you teka me more information?
There are many problems with PHx plugin. I want to solve these.

**Comment by janniconl** [comment]
What kind of info do you need?
I am running the latest (dev) versions of modx and PHx 2.2.0, server specs:
PHP: 5.5.30
MySQL: 5.6.26

Disabling the "Enable filters" option prevented this error. When I enable it again I only see a white page and 1 rule in php errorlog (like above).

**Comment by MrSwed** [comment]
@yama 
I think it's worth to make a more detailed description of this option, in comparison with phx and provide a link to the documentation.
Then, #667

**Comment by yama** [comment]
@janniconl 

> PHP Fatal error:  Call to a member function phxFilter() on a non-object in /home/[mydomainname]/public_html/manager/includes/document.parser.class.inc.php on line 1077

Thanks for your information. 
https://github.com/modxcms/evolution/blob/a01fad974f6efce523b22534f7c13f384158cf83/manager/includes/extenders/modifiers.extenders.inc.php
Maybe, here is a point.

```
<?php
/**
 * MODIFIERS Extension config file
 * Date: 2016-05-10
 * Time: 10:00
 */

include_once MODX_MANAGER_PATH . 'includes/extenders/modifiers.class.inc.php';
$this->filter= new MODIFIERS;

if(!class_exists('MODIFIERS')) return false;
else                           return true;
```
Please renew it in this code.

**Comment by yama** [comment]
@MrSwed 
Thanks, It's good idea.

**Comment by yama** [comment]
@janniconl 
Or please insert a line in the top.
```
if (is_object($this->filter)) return true;
```
https://github.com/modxcms/evolution/blob/develop/manager/includes/extenders/phpcompat.extenders.inc.php
Same approach.

**Comment by yama** [comment]
"MODIFIERS" or "FILTERS".
As the name of the class, which is easy to understand ?
Easy to understand better of "FILTERS" in Japan.

**Comment by Deesen** [comment]
My 2 cents from my understanding: Modifiers change values, Filters only separate/sort out values from a set of values without changing them?

**Comment by yama** [comment]
Thanks. I will use that as reference.

**Comment by MrSwed** [comment]
#684 **//todo**: 
- more intuitive description, and then translate it to other languages
- documentation and link to it in description (now link to it issue)

ps. is there a todo list on github project?

**Comment by MrSwed** [comment]
**//todo (if possible):
- in configuration, if phx plugin installed and it enabled, show option "Enable filters" read only and "No" regardless that value in db. So add desription, like: "&lt;b&gt;Phx plugin enabled. Before use filters, it must be disabled&lt;/b&gt;"

**Comment by MrSwed** [comment]
@yama 
This calls
```
[+phx:input=`[*pub_date:ne=`0`:then=`[*pub_date*]`:else=`[*publishedon*]`*]`+] 
```
gets 2 **Parse error: syntax error, unexpected ')' in `manager\includes\extenders\modifiers.class.inc.php ([283](https://github.com/modxcms/evolution/blob/develop/manager/includes/extenders/modifiers.class.inc.php#L283) and [289](https://github.com/modxcms/evolution/blob/develop/manager/includes/extenders/modifiers.class.inc.php#L289)  : eval()'d code on line 1**

that is part of 
```
[+phx:input=`[*pub_date:ne=`0`:then=`[*pub_date*]`:else=`[*publishedon*]`*]`:dateformat=`%d.%m.%Y`+]
```
of course, in that examle it can be replaced to 
```
[*pub_date:ne=`0`:then=`[*pub_date*]`:else=`[*publishedon*]`:dateformat=`%d.%m.%Y`*]
```
but in other situation may be need exactly phx:input call

**Comment by MrSwed** [comment]
other example **phx:input** in **phx:input**  - in both cases it get expected result on page.
no error if phx plugin enabled and 
with error 500 (same line numbers - then and else) in modifiers (phx plugin is off) :
**PHP Parse error:  syntax error, unexpected T_LNUMBER in ../public_html/manager/includes/extenders/modifiers.class.inc.php(283) : eval()'d code on line 1
PHP Parse error:  syntax error, unexpected T_LNUMBER in ../public_html/manager/includes/extenders/modifiers.class.inc.php(289) : eval()'d code on line 1**

```
[[Wayfinder? &startId=`0` &level=`1` &useWeblinkUrl=1 &rowTpl=`menurow` ]]

<li[+wf.id+][+wf.classes+]><a href="[+wf.link+]" title="[+wf.title+]" [+wf.attributes+]>
	<span>[+phx:input=`[+image+]`:is=``:then=`[+phx:input=`[+wf.linktext+]`:substr=`0,1`+]`
:else=`<img src="[+image+]" alt="[+phx:input=`[+wf.linktext+]`:specialchar+]"/>`+]</span>
[+wf.linktext+]</a>[+wf.wrapper+]</li>
```
this is the case when nesessary use phx:input, becouse standart use, for example [+wf.linktext:substr='0,1'+] did'n work

**Comment by yama** [comment]
https://github.com/modxcms/evolution/commit/b4c9c6ce46dd537575593c25c763e749c5527ae5

`
[+phx:input='[+image+]':is='':then='[+phx:input="[+wf.linktext+]":substr="0,1"+]':else='<img src="[+image+]" />'+]
`
Before

`
[+image:isNot(''):then('<img src="[+image+]" />'):else('[+wf.linktext:substr(0,1)+]')+]
`
After
(I do not confirm the test results)

**Comment by MrSwed** [comment]
@yama 
work, but with same errors. 
There are now code:
```
		[+image:isNot(''):then('<img src="[[phpthumb? 
		&input=`[+image+]` 
		&options=`w=300,h=300`
		]]" alt="[+wf.linktext:specialchar+]"/>'):else('[+wf.linktext:substr(0,1)+]')+]
```
That is before (worked normal with phx)
```
[+phx:input=`[+image+]`:is=``:then=`[+phx:input=`[+wf.linktext+]`:trim:limit=`1`+]`:else=`<img src="[[phpthumb? 
 &input=`[+image+]` 
 &options=`w=300,h=300`]]" alt="[+phx:input=`[+wf.linktext+]`:specialchar+]"/>`+]
```

**Comment by yama** [comment]
@MrSwed 
Thanks for your information. I also tried to test . The procedure of the test that I have done .

(1) Create chunk. The chunk name is 'menurow' . 
```
[+image:isNot('')
:then('<img src="[[phpthumb? &input=`[+image+]` &options=`w=300`]]" />')
:else('[+wf.linktext:substr(0,1)+]')
+]
```
(2) Put snippet call into template.
```
[[Wayfinder? &startId=`0` &level=`1` &useWeblinkUrl=1 &rowTpl=`menurow` ]]
```
(3) Create the TV. TV name is 'image' .
(4) Set TV value into resource . I have set the file name as "logo.png" to the resource of the pagetitle "Design" .
(5) It could be obtained following output . It could be obtained intended as output . Error is not out .
```
<ul>
H B F G
<img src="assets/cache/images/300x-logo.883.png">
C
</ul>
```
(Home, Blog, Features, Getting help, Design, Contact)

I could not see the problem . Do you have any information likely to be another hint ?

**Comment by MrSwed** [comment]
@yama 
sorry - it work (latest changes) - Error gets [this](https://github.com/modxcms/evolution/issues/623#issuecomment-234555532)  (my old temlate)
I fix it and no error more
and this work with PHX enabled!

Thanks!

**Comment by em-piguet** [comment]
I just tried on a site without PHx installed and i feel very confusing the fact that in Ditto there is also a version of PHx..  https://github.com/modxcms/evolution/blob/develop/assets/snippets/ditto/classes/phx.parser.class.inc.php

for example i think this code in ditto chunk 
`		[+phone:isnot=``:then=`[+phone+]`+]
`
is parsed by the phx in ditto and not the new filters options.. because if i do : (notice the ' instead of `)

`		[+phone:isnot='':then='[+phone+]'+]
`
it doesnt'work.

**Comment by kivamp** [comment]
@yama 
Hi
If _GET with arrays (ex: **?filter[id]=1&filter[parent]=&filter[date]=**)
[!_GET['filter']!] return ']'
and
<@IF:[!$_GET['filter']:isEmpty!]> make error:: strpos() expects parameter 1 to be string, array given
File	/var/www/virtual/tmbadm.ru/htdocs/manager/includes/extenders/modifiers.class.inc.php
Line	997
Source	if(strpos($content,'[')===false && strpos($content,'{')===false) return $content;
Evo 1.2.1

**Comment by fourroses666** [comment]
```[[phpthumb? &input=`[*foot-img1*:id=1]` &options=`w=100,h=100,zc=1`]]```

Is this also possible? 
`[*foot-img1*:id=1]`

Grab TV from ID x and use phpthumb snippet to crop the image?

**Comment by Ronef** [comment]
Guys, what about performance?
