### ISSUE TITLE
1.1.1 Release Candidate ?

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#624]
There have been tons of changes since the release of 1.1 in February and I get the feeling they aren't being fully tested in a multitude of individual / bespoke installs

Wouldn't it be a good idea to think about releasing a release candidate "1.1.1 RC1" ?

**Comment by bossloper** [comment]
+1

**Comment by modxuser** [comment]
Any takers on this ??

**Comment by Nicola1971** [comment]
+1

**Comment by MrSwed** [comment]
.. not ready release candidate yet, now only beta. #634
need more tests (there are testers?)

**Comment by modxuser** [comment]
@MrSwed 

The problem with testing is that no-one is publishing on the Forum about it

The majority of people that use Evo still use the forum more than they do GitHub - if no notification is made, no testing will be done, at least not from a wide range of install types

The majority of work that has been completed in the last couple of months has in my opinion only been realy tested by the developer who has made the modification(s)

Which obviously means it will work perfectly OK in that developers set-up, but may not work in a different set-up, or it may cause conflicts etc.

That's why I asked ref. release candidate - that way it can be posted on the MODX site for download as well as here, and that way it can be tested.

We all know that a release candidate is not a finished product and as such is treated (IMO) as a testing tool

**Comment by MrSwed** [comment]
@modxuser 
Well .. waiting for response from the releasers..

**Comment by janniconl** [comment]
Been working with the latest dev 1.1 versions for a few weeks. It is certainly releasable as a RC now in my opinion, but might be too early still for a definitive version. A lot has changed so there still can be some bugs. Eventhough, a RC version might make people download and use the latest versions more, so bugs are found earlier.

**Comment by yama** [comment]
https://github.com/modxcms/evolution/issues/623#issuecomment-219452130
I intend to solve this issue before release.

**Comment by modxuser** [comment]
Any update on this ? I see further improvements, yet hardly anyone is testing - this should be released to the community as a beta or pre-release ASAP

**Comment by bossloper** [comment]
can be closed?
