### ISSUE TITLE
Can't save the edited page

### ISSUE THREAD

**Issue by alexxis** [modxcms/evolution#628]
Evo 1.1, MySQL: 5.7.12, PHP 5.6, Apache 2.4. It seems the similar issue: https://github.com/modxcms/revolution/issues/12826. `« MODX Parse Error »
Execution of a query to the database failed - Expression #1 of ORDER BY clause is not in SELECT list, references column 'modx.tvtpl.rank' which is not in SELECT list; this is incompatible with DISTINCT` `SQL > SELECT DISTINCT tv.*, IF(tvc.value!='',tvc.value,tv.default_text) as value FROM `modx`.`modx_site_tmplvars` AS tv INNER JOIN `modx`.`modx_site_tmplvar_templates` AS tvtpl ON tvtpl.tmplvarid = tv.id LEFT JOIN `modx`.`modx_site_tmplvar_contentvalues` AS tvc ON tvc.tmplvarid=tv.id AND tvc.contentid='1' LEFT JOIN `modx`.`modx_site_tmplvar_access` AS tva ON tva.tmplvarid=tv.id WHERE tvtpl.templateid='3' AND (1='1' OR ISNULL(tva.documentgroup)) ORDER BY tvtpl.rank,tv.rank, tv.id`

**Comment by Deesen** [comment]
Also related to https://github.com/modxcms/revolution/issues/12401

**Comment by alexxis** [comment]
The simplest way to solve this issue don't use MySQL 5.7, isn't it?

**Comment by Deesen** [comment]
I guess so too ;-)
