### ISSUE TITLE
MAC Safari: CKFinder can't remove image, no subnav

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#629]
I can't remove images when I use MAC and latest Safari.
Also no new folders etc.. The subnav doesn't show up. 

I does work on the demo;
https://cksource.com/ckfinder
![ckfinder](https://cloud.githubusercontent.com/assets/523389/15186428/46b885ca-179d-11e6-9545-90557b08dc21.png)

**Comment by bossloper** [comment]
I can't help with a solution, but note Evo does not use CKFinder it uses KCFinder http://kcfinder.sunhater.com/

Subtly different name, similar look but different code. KCFinder is used because it is GPL, whereas CKFinder is paid for.

**Comment by Deesen** [comment]
Refering to your screeshot, does this issue happen also for images or only for PDFs?

**Comment by fourroses666** [comment]
you are right Bossloper, my bad.

the whole subnav isn't visible, (right click windows) for images and files.
Does work on the demo for safari: http://kcfinder.sunhater.com

**Comment by Deesen** [comment]
Does the Safari Error-Console report any error?

**Comment by fourroses666** [comment]
Nope,

I see some fix here: Safari 3 right-click fix
https://github.com/sunhater/kcfinder/blob/b645d2a81e647d63780c238b130593e32b4d95a9/doc/Changelog.md#24-2010-07-20

But thats 2010.

My guesses are there is something wrong here ?! but could also be something else..
https://raw.githubusercontent.com/modxcms/evolution/develop/manager/media/browser/mcpuk/js/jquery.rightClick.js

**Comment by Deesen** [comment]
Sry I guess I cannot help without having a MAC at hand to try out.

**Comment by fourroses666** [comment]
Understand 👍 

I always used Windows and didn't know about this "bug".
Is everyone on Windows? Weird this isn't noticed before :o

Clients can't add folders or delete/rename images who are on Mac and Safari.

**Comment by Deesen** [comment]
It seems there are several options as their is no "native right-click" in OSX? I found this article http://osxdaily.com/2011/05/24/enable-right-click-mac/

**Comment by fourroses666** [comment]
(On Firefox it works with using "CTRL" and "click" to get the subnav.)

I just tested again and noticed to get the subnav on the resource tree using "CTRL" and "click" that works but also directly loads the page.

So the behaviour is different for Safari and Firefox.

**Comment by bossloper** [comment]
You can also get the subnav on the manager resource tree by left clicking the file/folder icons (not the title text).

**Comment by fourroses666** [comment]
That correct bossloper, but on the title its not really possible, it directly loads the resource.

I use Firefox so its not an issue for me but clients might have this "setup" (iMac and mouse without button).

**Comment by Deesen** [comment]
Stupid question but does a double-click instead of "right-click" make any difference?

**Comment by fourroses666** [comment]
Nope ❌

**Comment by fourroses666** [comment]
Maybe update will help, don't know if its a simple update thow. Don't know if there is allot of custom code etc.

![update](https://cloud.githubusercontent.com/assets/523389/15243005/6d7f1f36-18f9-11e6-9771-107789e227dc.png)

**Comment by Deesen** [comment]
I also found "elFinder" which is open-source, has a lot more features and gets regular updates. I started already to port it to Evo but not sure if I can finish it alone. Maybe you want to stress it out to check if it works for you on all systems?

http://studio-42.github.io/elFinder/

**Comment by dmi3yy** [comment]
need do selectable file manager )  its be great 

https://github.com/Temus/elFinder

**Comment by Deesen** [comment]
Thanks for the link! Would be great indeed. The only problems is that many plugins / tools use hardcoded path like calling directly /media/browser/mcpuk/browser.php. So we would need to update all those plugins too.

I propose same mechanismn like "Display name in resource tree":

  - global option in MODX-configuration to set a "default"-filemanager
  - option in user-config to set filemanager to system´s "default" or selecting a custom filemanager

**Comment by dmi3yy** [comment]
yes its will be great
