### ISSUE TITLE
How to get Recent Edit Resource with ditto

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#630]
Hi,
Sorry for my question and I don't want to ask this question at modx forum.
My problem is I want to show recent edit resource .
I found at admin cms panel - Recent Resources tab and it show recent edit resouce.
So, I would like to know how to call with Ditto

**Comment by modxuser** [comment]
**Cached call:**

`[[Ditto? &parents=YOUR-ID` &tpl=`YOUR-TEMPLATE` &display=`10` &orderBy=`editedon DESC` &showPublishedOnly=`1` &randomize=`0`]]`

**Uncached Call:**

`[!Ditto? &parents=`YOUR-ID` &tpl=`YOUR-TEMPLATE` &display=`10` &orderBy=`editedon DESC` &showPublishedOnly=`1` &randomize=`0`!]`

Example using ID 1 as the parent, "latest" chunk as the output template and it should randomise the results:

`[[Ditto? &parents=`1` &tpl=`latest` &display=`10` &orderBy=`editedon DESC` &showPublishedOnly=`1` &randomize=`1`]]`

If this isn't exactly what you want, others may well provide a better solution.

You should also take a closer look at the [Ditto documentation](https://rtfm.modx.com/extras/evo/ditto).

Please note: Github remove the "spacing grave accent" from the calls, so don't copy and paste the call. Use the attached file, it's basically a copy of this message.

[ditto-call.txt](https://github.com/modxcms/evolution/files/260250/ditto-call.txt)

**Comment by mgzawlinoo** [comment]
Thank you bro , it work well .
