### ISSUE TITLE
Wayfinder &showSubDocCount=`true`

### ISSUE THREAD

**Issue by jorjik** [modxcms/evolution#631]
работает только при вызове в текущей директории (BUG)
или!
работает, если писать &**hideSubMenus**=`0` (что не удобно, т.к. потом стилямя надо скрывать)

конечно, пишем адекватный параметр &**level**, а также выводим через [+wf.**subitemcount**+]

P.S. в файлах этого параметра я не нашёл; версия 2.0.4

**Comment by MrSwed** [comment]
check last version from develop branch and give more info about bug
