### ISSUE TITLE
New demo template

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#632]
Me and @Deesen have made a new basic demo/sample template build on Bootstrap.

See here:
http://tinyurl.com/z4pk53o

Let me know what you think and with the help of @dmi3yy it will be in the next version of Evo.

See any bugs? Let me know

**Comment by modxuser** [comment]
If you ask me I don't see the point of having a base template

I think it's simply more balast that has to be deleted each time an update or install is completed

Does anyone use it at all ?

**Comment by fourroses666** [comment]
Its the sample site you don't have to use

**Comment by bossloper** [comment]
Looks good to me. For those new to MODX and promoting the system, it is nice to have something relevant even if it is to be deleted.

**Comment by Nicola1971** [comment]
Nice

check this one too
http://www.evoboot.tattoocms.it/

https://github.com/Nicola1971/EvoBoot

**Comment by Deesen** [comment]
@modxuser It´s meant to replace the demo-site / demo-content from 2006 (I guess you know this one http://evo.modx.ru/ ) using an up to date framework like Bootstrap. To keep ballast at minimum we load files like the framework only from CDNs.

**Comment by Nicola1971** [comment]
I have always highly valued the demo content but, with the Store (Extras) module as default in Evo 1.1  manager, we could remove the Demo Content (and demo Template) and make it available to download as an extra

**Comment by nick0** [comment]
This is a great looking template, great job by you both :) This should definitely replace the current default.

I am with @modxuser in that I don't use the base template and always delete it. However its probably still important to have for new users, at least on their first install. WordPress does the same thing - it has a demo post and a demo page with a demo theme that can be easily deleted. It makes sense to include it to me.

Great work.

**Comment by fourroses666** [comment]
We could do that too. Remove the demo and add it to the Store. Not a bad idea @Nicola1971 .
What do you think about that @dmi3yy ? Keeping it clean.

**Comment by Nicola1971** [comment]
however, the template is very nice and clean. for me +1

my two cents about the demo content:

- marketing view: default template (and demo content)  should show most of the evo power, basic examples to understand how to create a full site with evo: doclister (done), jot (done) phpthumb(missing), if (or yama phx additions)(done?)... regards this king of features it seems a little bit updated  - It offers only the features of modxhost, with doclister instead ditto.

- to fix: http://demo.esensdev2.nl/features/ajax "Check out the Ajax-powered search in this example site": there is no ajax in this template [remove]

- http://demo.esensdev2.nl/features/extendable: Using jQuery-effects.. where? [remove]

- Blog post tags: all blog post have 0 tags - add tags to blog posts or, better, remove tags (old and bad for seo)

- Blog post images: please...

**Comment by Deesen** [comment]
I try to answer shortly

  - docLister: We did not use it in the demo yet (still no experience with it LOL)
  - phpThumb: Which images should we use without bloating the MODX-package? The MODX-Logo?
  - Ajax: If you enter a search-word, a Modal should pop up with the results instead of loading new page.
  - Blog Tags: Removing it makes sense then indeed
  - Blog images: Which to use? Like the original modxhost this demo-content uses no external / additional files

**Comment by fourroses666** [comment]
Never used docLister aswell.
To use images for the blog is a good idea. Not sure where to grab them from. I think placehold.it/400x300 can be used so no saved images.
Maybe a link to the documentation for phpthumb is better.

**Comment by Nicola1971** [comment]
i dont think images are really needed for a phpthumb example.
we can show a good mixed phpthumb/if example with something like this:

```[[if? &is=`[*Thumbnail*]:!empty` &then=`<div class="blog-img">
                        <img src="[[phpthumb? &input=`[*Thumbnail*]` &options=`w=1300,h=655,zc=TL`]]" alt="[*pagetitle*]" class="img-responsive"/>
                    </div>`]]```

when Thumbnail tv is empty does not show anything, else show a phpthumb image.

anyway, phpthumb has a noimage.png placeholder when you have no image, check sidebar news and photos stream in this template:
http://www.evoboot.tattoocms.it/

**Comment by fourroses666** [comment]
Ah looks good Nicola, will use that.

Just noticed, can't find any YAMS "extender" for DocLister. 
Like Ditto has: 	
`&extenders='@FILE assets/modules/yams/yams.extender.inc.php'`

But will change it for the demo to DocFinder.

**Comment by Nicola1971** [comment]
@fourroses666 I used a couple of times just yams with ditto. For doclister must ask to AgelxNash

@Deesen I did not see the ajax search results, sorry . very cool ;)

NOTE:

There is an old annoying issue with the ajaxsearch form : when you load the demo with a mobile device (or resizing the page to a small view) , page scrolls automatically to the form:

![demo-mobile](https://cloud.githubusercontent.com/assets/7342798/15447779/ae8a1cf6-1f4d-11e6-905f-7a58356bf2f7.png)

**Comment by fourroses666** [comment]
Beside some small changes I'd like to add/replace this.
I don't know how to do this, found the file to be changed in the install folder. 
Like; https://github.com/modxcms/evolution/blob/develop/install/assets/templates/modx_host.tpl
Probably not that difficult but rather let is add by a developer. 
Some chunks needs minore changes too.

Don't know if @dmi3yy can add it? 
I can give access to the demo site.
http://tinyurl.com/z4pk53o

**Comment by Deesen** [comment]
@fourroses666 I will take care of it of course. It would be great to know when release of 1.1.1 is planned so we can finish it before.

**Comment by fourroses666** [comment]
Ah cool, it really needs some update lol. That demo is so 2006

**Comment by Nicola1971** [comment]
any news about it?

@fourroses666 can i help you?

**Comment by fourroses666** [comment]
Well, I'm not sure how Deesen thinks about that. I'm oké with it.
Can give you admin access to the manager. 
Beside some minor fixes its ready to replace the old template in the install file. 
Probably the bootstrap and fontawesome paths can be changed to the internal ones.

**Comment by Deesen** [comment]
No problem, I did not really start yet so @Nicola1971 you´re welcome ;-).

**Comment by Nicola1971** [comment]
happy to help you guys ;)

At first check, It seems almost ready.

 a couple of things noticed at first sight:

1) missing bootstrap Register form : don't worry we can take from one of my templates - http://www.evoboot.tattoocms.it/request-an-account.html

2) Logo path requires [(site_url)] prefix or will not work on local servers (wamp)

3) Path to google fonts, rquires https prefix..  or will not work on local servers (wamp)

Regards Bootstrap Local vs CDN:

I dont suggest to use recently added Bootstrap folder inside manager: don't like manager path in my front end template code, for security reasons ;)

Sometimes i use to work with my laptop where there is no internet connection (or is not stable, like on train), in this case, CDN will not work. 
Anyway, is not a big issue when you can temporarily adjust the path to the manager folder.

@fourroses666 
once we resolved the remaining issues, to accelerate the export of all chunks, i suggest to delete every chunk you do not need and export tpl using one of these modules (by KP52).

https://github.com/Nicola1971/Packager

https://github.com/Nicola1971/makeinstall-module

**Comment by fourroses666** [comment]
Then we could keep the "maxcdn" bootstrap/fontawesome path and a ```/* comment */``` to copy it to a folder once going live. Using manager path isn't that great idea indeed.

You can do these points if you want, I noticed you are in the template so can't correct it right now.

Not sure what you want to do with the Packager.
Do you want to make it a package instead of replacement of the old modxhost one?

**Comment by Nicola1971** [comment]
1) Fixed logo and google fonts path on your site.
2) updated to Bootstrap FormSignup chunk from EvoBoot template
http://demo.esensdev2.nl/request-an-account

Packager or MakeInstall modules just help you to export all new updated chunks and template to .tpl files for Evo Installer

**Comment by fourroses666** [comment]
Thanks, 

_there is a col-md-12 which can be removed, see the space on the request an account page :0_

Still don't understand what you mean with the packager stuff. 
Oke so you can make backups in .tpl files, thats cool, never tried it but do you want to make this demo an installer?

**Comment by Nicola1971** [comment]
> there is a col-md-12 which can be removed, see the space on the request an account page :0

done ;)

>  but do you want to make this demo an installer?

To add your template to Evo Setup, i think you need to create new .tpls files for your template and your chunks (ie: your new chunks for Ajax Search Modal)

**Comment by fourroses666** [comment]
I never did that before and no time to dig into it atm. 
So to finish this you need some .tpl files for the installer?
Does the old demo, modxhost works like that too?

**Comment by Nicola1971** [comment]
@fourroses666 
Say goodbye to MODXHost
Mostly done! :)
Not sure i've included all your new chunks, but seems work for me. 

Download a latest dev and overwrite with this:
https://github.com/Nicola1971/MODX-startup-Evo-Install

**Comment by Nicola1971** [comment]
missing map in contact page: need to update all the content table

**Comment by fourroses666** [comment]
👋 

Cool, going to check it out tonight.

**Comment by fourroses666** [comment]
I have installed the latest development version, with the demo, then installed packager and installed the new bootstrap demo. Changed the default template and got success!

It does have old text, (credits etc are updated) / login, contactform and blog styles are not bootstrap.

So we need chunks:
- ContactForm
- Comments_tplForm
- ditto_blog
- FormSignup

Not 100% sure if we need more chunks

**Comment by Nicola1971** [comment]
Ok
I need to know any chunk you added or modified.
Because we need to 
1) replace modified chunks in setup.data.sql, 
2) add new chunks with  .tpl files in to the install folder,
3) remove all modx host chunks from setup.data.sql

**Comment by Nicola1971** [comment]
For me it's the perfect demo template: no files in assets, very minimal and light weight..and easy to delete (I hate delete all annoying modx host chunks in demo content)

Good work guys!

**Comment by Nicola1971** [comment]
@fourroses666  please test clean install too, because we must remove all modx host chunks.

**Comment by fourroses666** [comment]
Oke I will, hope to have the time tonight to test.

**Comment by fourroses666** [comment]
Yes it works great on a clean install too. If you don't need the blog or whatever.
Going to check all chunks needed now.

**Comment by fourroses666** [comment]
Just installed a clean Evo with modxHost and checked the differences with the new demo:

**Modified chunks:**
- Comments
- ContactForm
- ditto_blog
- FormSignup 
- WebLoginSideBar

**New chunks:**
- AjaxSearch_tplAjaxGrpResult
- AjaxSearch_tplAjaxResult
- AjaxSearch_tplAjaxResults
- AjaxSearch_tplInput
- Comments_tplComments
- Comments_tplForm

**Chunks which could be removed**
- ContactStyles  (&cssStyle=`ContactStyles` could be removed out of the call in contactpage)
- footer
- meta
- mh.InnerRowTpl
- mh.InnerTpl 
- mh.OuterTpl 
- mh.RowTpl

**Comment by Nicola1971** [comment]
Checking a fresh install with https://github.com/Nicola1971/MODX-startup-Evo-Install:

### Modified chunks:

Comments OK
ContactForm OK
ditto_blog OK
FormSignup OK
WebLoginSideBar OK

### New chunks:

AjaxSearch_tplAjaxGrpResult OK
AjaxSearch_tplAjaxResult OK
AjaxSearch_tplAjaxResults OK
AjaxSearch_tplInput OK
Comments_tplComments OK
Comments_tplForm [Missing - just added] > OK

### Chunks which could be removed

ContactStyles (&cssStyle=ContactStyles could be removed out of the call in contactpage) TO DO in table site_content
footer OK
meta OK
mh.InnerRowTpl OK
mh.InnerTpl OK
mh.OuterTpl OK
mh.RowTpl OK

So, we just need to update the content table

**Comment by Nicola1971** [comment]
Update:

1)  Updated content in:
* Home
* Design
* Contact US
* Features » Extendability

Did not found other updated content in your demo site

2) Added missing chunks

3) renamed th new login form chunk from WebLoginSidebar to WebLogin_tplForm - fit better your chunk name structure - and never liked the name (it's not only used in to the sidebar)

4) Merged in my repo with latest Dev and removed MODxHost folder from assets/templates

Everything works for me :)

https://github.com/Nicola1971/evolution

**Comment by fourroses666** [comment]
Cool thx for the work @nicola1971 !

**Comment by Deesen** [comment]
Definetly thanks for your efforts!

**Comment by Nicola1971** [comment]
I have an issue with WebLogin_tplForm

If you check demo content does not install

Tried to remove @internal    @installset base, sample
https://github.com/modxcms/evolution/blob/develop/install/assets/chunks/WebLogin_tplForm.tpl#L11

still same issue with demo content

**Comment by fourroses666** [comment]
WebLogin_tplForm is installed on my testsite thow.

When logged in I can't comment on the blog. 
Seems "Comments_tplForm"  is missing.

**Comment by Nicola1971** [comment]
@fourroses666  seems the same issue with weblogin chunk, not understand the problem - all chunks are in the install folder
https://github.com/modxcms/evolution/tree/develop/install/assets/chunks

**Comment by fourroses666** [comment]
I don't know whats wrong, not that great at finding this problem. 
Its here too indeed; https://github.com/Nicola1971/evolution/tree/develop/install/assets/chunks
Would it be an issue with setup.sql ?


_Just updated an hour ago;_
https://github.com/modxcms/evolution/blob/develop/install/setup.sql

**Comment by dmi3yy** [comment]
better ad in data.setup.sql   for  clean install no need show all this chunks  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 01:26, Marc написал:

**Comment by Nicola1971** [comment]
> better ad in data.setup.sql   for  clean install no need show all this chunks

i can add to data.setup.sql, but i think that tpl format for demo content are more simply to update  (i think the demo theme will be updated a bit)

still cant understand the issue

**Comment by fourroses666** [comment]
Any idea how to solve it?

**Comment by Nicola1971** [comment]
@fourroses666  as @dmi3yy said : fast solution . move chunks code in data.setup.sql

**Comment by Nicola1971** [comment]
@fourroses666  https://github.com/modxcms/evolution/issues/824

**Comment by fourroses666** [comment]
Have one little issue with the contactpage. The textarea should need `<textarea row="6".`
![textarea](https://cloud.githubusercontent.com/assets/523389/19416536/70a84cae-9393-11e6-8f7d-372e736f0b66.jpg)

When logged in the manager and going to the blog there are old image icons.
No time to change this now. Might need a new jot tpl for this one?!
![blog](https://cloud.githubusercontent.com/assets/523389/19416571/2e3e2edc-9394-11e6-9c68-a5d0a621ffe7.jpg)

**Comment by Nicola1971** [comment]
you can replace in  Comments_tplComments with font awesome, but requires some css update
![wdwvyras2nwzwaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19417231/9feaea62-93a7-11e6-8c53-2b87c310008b.png)


```
<a name="jc[+jot.link.id+][+comment.id+]"></a>
	<div class="panel panel-[+chunk.rowclass:ne=``:then=`primary`:else=`info`+] [+comment.published:is=`0`:then=`jot-row-up`+]">
		<div class="panel-heading"><span class="jot-subject">[+comment.title:limit:esc+]</span></div>
		<div class="panel-body">
	 <div class="jot-comment">
 		 
		 <div class="jot-user">
		 [+comment.createdby:isnt=`0`:then=`<b>`+][+comment.createdby:userinfo=`username`:ifempty=`[+comment.custom.name:ifempty=`[+jot.guestname+]`:esc+]`+]
[+comment.createdby:isnt=`0`:then=`</b>`+]
		 <br />Posts: [+comment.userpostcount+]
		 </div> 
		
		 <div class="jot-content">
			 
			 <div class="jot-posticon">
					[+phx:userinfo=`lastlogin`:ifempty=`9999999999`:lt=`[+comment.createdon+]`:then=`
				 <i class="fa fa-comment-o" aria-hidden="true"></i>
				 `:else=`
				 <i class="fa fa-commenting-o" aria-hidden="true"></i>
				 `:strip+]
			 </div>		 
			 
			 <div class="jot-mod">
			 [+jot.moderation.enabled:is=`1`:then=`
				<a href="[+jot.link.delete:esc+][+jot.querykey.id+]=[+comment.id+]#jotmod[+jot.link.id+]" onclick="return confirm('Are you sure you wish to delete this comment?')" title="Delete Comment"><i class="fa fa-trash" aria-hidden="true"></i></a>
				[+comment.published:is=`0`:then=`
				<a href="[+jot.link.publish:esc+][+jot.querykey.id+]=[+comment.id+]#jotmod[+jot.link.id+]" onclick="return confirm('Are you sure you wish to publish this comment?')" title="Publish Comment"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
				`+]
				[+comment.published:is=`1`:then=`
				<a href="[+jot.link.unpublish:esc+][+jot.querykey.id+]=[+comment.id+]#jotmod[+jot.link.id+]" onclick="return confirm('Are you sure you wish to unpublish this comment?')" title="Unpublish Comment"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
				`+]
			 `:strip+]
			 [+jot.user.canedit:is=`1`:and:if=`[+comment.createdby+]`:is=`[+jot.user.id+]`:or:if=`[+jot.moderation.enabled+]`:is=`1`:then=`
				 <a href="[+jot.link.edit:esc+][+jot.querykey.id+]=[+comment.id+]#jf[+jot.link.id+]" onclick="return confirm('Are you sure you wish to edit this comment?')" title="Edit Comment"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
   		 `:strip+]
			 </div>	
			  
			 <span class="jot-poster"><b>Reply #[+comment.postnumber+] on :</b> [+comment.createdon:date=`%a %B %d, %Y, %H:%M:%S`+]</span>
			 <hr />
			 <div class="jot-message">[+comment.content:wordwrap:esc:nl2br+]</div>
			 <div class="jot-extra">
			 [+comment.editedon:isnt=`0`:then=`
			  <span class="jot-editby">Last Edit: [+comment.editedon:date=`%B %d, %Y, %H:%M:%S`+] by [+comment.editedby:userinfo=`username`:ifempty=` * `+]</span>
			  &nbsp;`+] [+jot.moderation.enabled:is=`1`:then=`<a target="_blank" href="http://www.ripe.net/perl/whois?searchtext=[+comment.secip+]">[+comment.secip+]</a>`+]</div>
		 </div>
		 
	 </div>
	</div>
	</div>

```

**Comment by Nicola1971** [comment]
solved with bootstrap classes, no need update css

![l0eraberaberaberabexbz4p8dtsparrgme0maaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19418687/2f024792-93c9-11e6-8717-70aa4975dc0a.png)

ok for you?

**Comment by fourroses666** [comment]
Looks great! Also nice text icon on right top.
