### ISSUE TITLE
name it tree ^^

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#636]
https://github.com/modxcms/evolution/issues/598

after the introduction of the sort function in the tree - flies the set value. After exiting the admin panel becomes - [*pagetitle*]
When established - [*menuindex*]

1.1 from git

**Comment by Deesen** [comment]
These sorting-options are only saved per session. If you log out, session will be deleted. Is this your issue?

**Comment by Fr3ddyCruger** [comment]
yes, not very convenient if there are long [*pagetitle*]

**Comment by Deesen** [comment]
What does the community think? Should we add those 3 sorting-options to DB-table "user_settings" so to load them at user-login into session?

**Comment by Fr3ddyCruger** [comment]
a great idea), or remove it from the tree at all, in the settings enough points ... but as for me)

**Comment by Deesen** [comment]
You don´t need sorting option in tree? Or do you want to open again your issue https://github.com/modxcms/evolution/issues/618 ? ;-)

**Comment by Fr3ddyCruger** [comment]
so let it be, the main thing that this function does not interfere with normal operation)) and it does not get off setting, after the closing session

**Comment by Fr3ddyCruger** [comment]
community sleep ^^

**Comment by fourroses666** [comment]
I never touch these settings. Add them to DB-table "user_settings" sounds good but it doesn't really matter for me 👍

**Comment by Nicola1971** [comment]
It makes sense to me. 
+1 for me

**Comment by MrSwed** [comment]
I think it is a good practice to store user settings on the server. However, may need to provide the behavior of constantly switching, that is, on the server to store only what the user has set on the settings page, but what "temporarily" changed in the interface, leave the in session.

**Comment by janniconl** [comment]
I agree with @MrSwed. My 2 cents:

- Save the sorting options in the DB. If I change the order I will probably do this because I **always** want it this way. So I want it on my next session aswell. 
- I think the current solution is fine and intuitive for me, but adding it to Configuration **as well** would be a nice extra and could be more intuitive/logical for others.

**Comment by Fr3ddy7** [comment]
+1 8)))

**Comment by bossloper** [comment]
Suppose saving to DB is the ultimate, but is it worth the effort.

Personally I just leave it as sorted by menu index - ascending, changing the name might be useful but no big deal either way. Having the tree sort order different from an actual website menu structure sort order must be rare? Though I presume some do sort it other ways for various reasons?

I know for a 'non-techie' site manager it is confusing. They just want to sort the website menu. If they come across 'sort the site tree' they sometimes assume it is sorting the menu on the site. If the manager tree then does not reflect that sort order they don't follow the subtlety of 'site tree' vs 'menu index'.

**Comment by Fr3ddy7** [comment]
problem described above, when made in the sorting tree, it was only maintained for the session, and when the function has been configured - to work regardless of the sorting tree.

+ For everything in the name of the tree was also run off, and it's not very useful if the site is optimized for search engines and a long pagetitle

**Comment by Deesen** [comment]
I hope this solves the issue?

**Comment by janniconl** [comment]
Works for me (saving the order in db)

**Comment by Fr3ddy7** [comment]
yes! thnx 8)
