### ISSUE TITLE
phpthumb cache management

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#637]
Does anyone have a plugin or other automated solution for managing the phpthumb cache?
both the assets/.thumbs/ folder and assets/cache/
Over time this could get out of hand on an 'actively' managed site.
I see Revo has a plugin for this, but Evo does not?

Thanks in advance.

**Comment by Deesen** [comment]
I personally know none, but what is the Revo-version´s name and how does it work? Maybe we can port it?

**Comment by bossloper** [comment]
This is the plugin for revo:
https://github.com/modxcms/pThumb/tree/pThumb-dev/core/components/phpthumbof/elements/plugins

**Comment by Deesen** [comment]
Ah ok, pThumb does not simply delete all cached images OnSiteRefresh-event but offers a mode with options like maxage, maxfiles, maxsize too. The older phpThumbOf-plugin seems to just delete all cached images.

Wouldn´t it be a great idea to implement an optional images-table to MODX-DB ? So all thumbnails created by MODX, uploaded through manager etc will be listed in it for future maintaining-procedures like ClearCache or whatever. Also this would open the door to an image-manager where you can add/change ALT-Attributes of images centrally, using perceptional hashes etc.

**Comment by bossloper** [comment]
I think clearing all thumbnails too often could be too server resource intensive. So some sort of maxage, maxfiles or maxsize would be useful. 
Or maybe run the cleanup on OnCacheUpdate but also include some sort of random number generator (a bit like Linux session cookies are managed) so it only actually runs the clean every now and again (e.g. give it only a 1% chance of executing the clean).

Yes images-table might be a good long term goal.

**Comment by bossloper** [comment]
If anyone is interested in a starting point for anything more sophisticated(!) :-) I have a basic cache cleaner plugin. It will traverse the cache folder and clear out files over a certain age. It is triggered by OnCacheUpdate event.

https://github.com/bossloper/CacheClean
