### ISSUE TITLE
Транслитерация при загрузке файлов

### ISSUE THREAD

**Issue by sashabeep** [modxcms/evolution#640]
Плагин transalias установлен, но транслитерация при загрузке не происходит
1.1 свежая

**Comment by dmi3yy** [comment]
Так в плагине в настройках установите параметр в rusianlovercase 

Это в сборке моей по умолчанию стоит сразу а в официальной надо править 

Отправлено с iPhone

**Comment by sashabeep** [comment]
Дмитрий, вы не представляете, какой я дурак, стоит russian но legal characters вместо lowercase alphanumeric
