### ISSUE TITLE
New feature: Welcome Screen showing "Important version notices"

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#645]
I think we need a new feature like showing a changelog or a shorter updated version of it on the welcome screen. The MODX-Feed seems not enough for me. This way we developers could add such important infos with every pull-request if nessecary, and without depending on the MODX-feed like

MODX 1.1.1 - Important notice
  - feature X has been moved to ...
  - setting X can now be found in ...
  - security-role X has been added to allow ...
  - new API / extender X added, more infos at URL ...

Refering to confusion like #639, #618 etc.

**Comment by Deesen** [comment]
Also it would complete the new "information-tab" - philosophy of having documentation at hand within MODX. To finalize it I would like to modify the help-button and add a table with documentation-links to it like theme MODxPress has deluded us.

**Comment by fourroses666** [comment]
+1 on this!

**Comment by Fr3ddyCruger** [comment]
+1 )

**Comment by pmfx** [comment]
+1

**Comment by nick0** [comment]
+10 This is an awesome idea.

**Comment by esszett** [comment]
+1 yes please

**Comment by janniconl** [comment]
+1 Nice idea

**Comment by Deesen** [comment]
The help-action / button was already prepared in a nice way so I improved it instead of altering the welcome-screen. Screenshots -> #668
