### ISSUE TITLE
Uncaught TypeError: Cannot read property 'submit' of undefined

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#646]
I try to check #639
so I do 
- get last develop version
- Open Doc Manager module
- Go to 4th tab (Other Properties)
- Select Publish/Unpublish
- Add a range of resource id's, e.g. **2****
- Click submit

it is work, but in console :
VM6341 docmanager.js:106
Uncaught TypeError: Cannot read property 'submit' of undefined
  postForm @ docmanager.js:106
  onclick @ VM6371 index.php?a=112&id=1:240

![image](https://cloud.githubusercontent.com/assets/5120610/15466353/d92b9bde-20e1-11e6-8105-6605864ff039.png)

**Comment by Deesen** [comment]
I tested with an old 1.0.14 installation and the error is the same (also "switch template"-tab), but anyway it works.

**Comment by MrSwed** [comment]
ok, leaves it here, may reach the hands to fix it :)

**Comment by Deesen** [comment]
Can be closed?

**Comment by bossloper** [comment]
I just tested this and it looks fixed to me.
