### ISSUE TITLE
site_tmplvar_contentvalues 65535 Bytes Limit breaks MultiTV 

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#648]
Due to its column-type TEXT the limit to store TV-values is 65535 Bytes. It happened several times that a customer (by accident) copied from Word and pasted directly into TinyMCE3 which causes lots of unnessecary data / Word-tags. It easily blows up the 65535 Bytes-limit. So in most cases the JSON-string gets useless = all content of this TV is lost unless you have a backup.

The only quick work-around now is to change TEXT to MEDIUMTEXT. I checked Revo and they also use MEDIUMTEXT. So would it make sense to make `site_tmplvar_contentvalues.values` a MEDIUMTEXT by default like Revo? Or does it affect performance too much for bigger sites using lots of small TVs?

**Comment by janniconl** [comment]
I had the same once, cost me a lot of time recovering from Google cache. +1 for a default fix.

**Comment by janniconl** [comment]
P.s. I _have_ changed this it to MEDIUMTEXT on a site with a lot of small TV's (and multi tv's). No problems there so far.

**Comment by Jako** [comment]
MultiTV is not meant to contain a lot of data. To use MEDIUMTEXT is quite ok, but please don't put a lot of data into a datatable/horizontal/vertical MultiTV. It is a very ineffective approach to store JSON data in the `values` field. Better use a dbtable MultiTV for this.
