### ISSUE TITLE
Error with latest DocFinder on extras-revolution

### ISSUE THREAD

**Issue by janniconl** [modxcms/evolution#650]
I use it a lot, since it is a lot better than the default search (e.g. because it has search + replace options). The latest version does not work for me anymore. Anyone else having problems with DocFinder?

I tried to go back to 1.6. This version does not give an error, but the search always returns _all_ resources (modx 1.1. dev) so is basically broken as well.

For more details on the bug: https://github.com/extras-evolution/DocFinder/issues/4
(posting this here since it has been 22 days and no reactions at all)

**Comment by pmfx** [comment]
Same issue here. Using DocFinder 1.7 and now it returns ALL resources, no matter what I search. DocFinder is one of best modules for Evolution in my opinion.

**Comment by Deesen** [comment]
Strange. I installed 1.7 as well and the search works like expected, see screenshots. "home" can be found, "home2" not:

home:

![docfinder1](https://cloud.githubusercontent.com/assets/8569221/15529278/712cb8e4-224c-11e6-95dd-66aeca65528c.png)


home2: 
![docfinder2](https://cloud.githubusercontent.com/assets/8569221/15529280/7330603c-224c-11e6-9665-a8e6e8722260.png)

**Comment by janniconl** [comment]
For me the issue is fixed now: https://github.com/extras-evolution/DocFinder/issues/4

@pmfx Are you sure u have the latest 1.7 files/installation from https://github.com/extras-evolution/DocFinder/ ? Because I only had the all-results-problem with 1.6.

**Comment by janniconl** [comment]
@Deesen I have another error in DocFinder

When entering a search query, e.g. for "home", go to the 3rd tab (Combined view).
If you then click on the name of the resource fond _or_ on the checkbox, I get an error.

**Comment by Deesen** [comment]
The action-id was missing, should be fixed now.

**Comment by pmfx** [comment]
@janniconl Looks like I had strange 1.7 version Downloaded latest from https://github.com/extras-evolution/DocFinder/ and kno it search fine. Problem with action id missing is still there in combined view though.

**Comment by Deesen** [comment]
The action-id fix has not been merged yet ;-) : https://github.com/Deesen/DocFinder
