### ISSUE TITLE
CodeMirror and TinyMCE issue with 1.1.1-beta 

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#652]
With a fresh install of evo 1.1.1-beta CodeMirror and TinyMCE  do not appear when you try to edit/create a document or element.

Both plugins are enabled but, to make them work, you need to open the plugin configuration tab, click on update parameter display" and.. "save"

**Comment by fourroses666** [comment]
I have updated aswell. My .htaccess file isn't empty but it does look like it.

![htaccess](https://cloud.githubusercontent.com/assets/523389/15690538/42d24972-2784-11e6-8807-571183898ca4.gif)

**Comment by fourroses666** [comment]
console says:  getPreventDefault()   -->   defaultPrevented

**Comment by Deesen** [comment]
Cannot recreate that issue. I installed a fresh new 1.1.1-beta on a new webserver and Tiny3 and CodeMirror work right out of the box. Also file-manager upload is working without console-notice.

**Comment by fourroses666** [comment]
I have no issues with TinyMCE as Nicola has/had but Codemirror does.

I did an upgrade from 1.0.15 to 1.1.1 beta and the issue appeared. 
Now downgraded to 1.1 stable but the issue is still there. Can't use codemirror.

Want to see for yourself?

**Comment by Deesen** [comment]
Yes please :+1:

**Comment by fourroses666** [comment]
You've got mail

**Comment by fourroses666** [comment]
Seems Codemirror and FF on MAC has issues, Safari doesn't. 
The weird thing is after the downgrade the issue is still there while on other 1.1 installs I don't have it. So might be specific this install?! 

Need to see on an other install if the same happens

**Comment by fourroses666** [comment]
Hmm, ok just did an upgrade (1.1 RC2 to 1.1.1 beta) and no issues ... 
There is something weird going on with that install..

I don't have the issue Nicola has, mabe its a settings thing @Nicola1971 ?

**Comment by Nicola1971** [comment]
@fourroses666 have you tried 
> plugin configuration tab > click on "update parameter display" > "save"?

worked for me

**Comment by fourroses666** [comment]
yes I did, doesn't work for the codemirror. Going to re-upgrade it again and see what happens lol

**Comment by Deesen** [comment]
@Nicola1971 Can you see any error-message in console or so? And which browser do you use?

**Comment by Nicola1971** [comment]
@fourroses666 I've updated to beta 1.1.1 about 6-7 modx sites, on my local server and online. Issue happened about 50% of them.
Sometime only on Codemirror, sometime both, sometime no issue..
initially I thought it was my problem

**Comment by Nicola1971** [comment]
@Deesen 
![tinyerror](https://cloud.githubusercontent.com/assets/7342798/15703943/67700350-27e8-11e6-8958-1f64790ca682.jpg)

**Comment by fourroses666** [comment]
After deleting codemirror and reupgrade codemirror works again.
Only issue now is that I'm missing some colors;
![wheres-my-colors](https://cloud.githubusercontent.com/assets/523389/15704152/95e2122c-27e9-11e6-8f23-20c70bfc3758.png)

**Comment by Deesen** [comment]
@fourroses666 CSS-highlighting should be fixed with my commit

@Nicola1971 Console says error in line 868. I´m not sure if line 868 on my side is the same so can you post the content of your line?

**Comment by Nicola1971** [comment]
@Deesen 
I investigated: in this case, the error cames from a module. Removed the module, console error disappeared, but remained the issue with tinymce

**Comment by fourroses666** [comment]
Thanks, that works @Deesen !!

**Comment by Nicola1971** [comment]
Fixed again saving plugin parameter display
In the last hour, i've updated to beta 3 websites (two online and one on local wamp server)
strangely, cannot recreate the issue.

**Comment by Deesen** [comment]
@fourroses666 With above commit also .htaccess etc should be displayed right.

**Comment by fourroses666** [comment]
Just checked, but no it didn't!! Nothing visible for .htaccess

_btw, the color theme is on default but different, its less good visible :(_
missing orange color :o 
![theme](https://cloud.githubusercontent.com/assets/523389/15708546/5a209086-27ff-11e6-8fda-067eead76c41.png)
I need to check the css

**Comment by fourroses666** [comment]
Ooops, sorry, didn't see you had a second file changed! 

The .htaccess works, only the color theme is different on FF.

**Comment by Deesen** [comment]
I´m not sure why this difference. But I had to add "mode/css-compressed.js" for highlighting CSS-code so I guess this latest version handles CSS-code different and generates tags different as well. As you said, what was .cm-string-2 before is now .cm-atom, so it must be JS-related. It seems by changing the default.css you cannot achieve same visual appearance as before. Is it a big problem?

**Comment by fourroses666** [comment]
Yes seems to be different colors and I hate it lol. Yeah I'm picky about this stuff :(
Well I'm very used to build sites with CSS in a chunk.

I think I will make a new theme :P 
Or use the old 5.6 CodeMirror (if possible to downgrade it)
_The Ambiance theme looks pritty chill for your eyes._

**Comment by Deesen** [comment]
Is it solved now?

**Comment by fourroses666** [comment]
think so

**Comment by Nicola1971** [comment]
i close this issue, because is not related only to timymce and codemirror.
