### ISSUE TITLE
EvoGallery PHP7 and MODX 1.1

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#657]
There might be an issue with PHP7 and EvoGallery.
I don't think EvoGallery isn't being maintained anymore so thats why I post it here.

I have copied and paste this from sjmclean's here below:

_When I try to upload, Evo Gallery echos 'HTTP Error'. From the Net it also shows that action.php did not load with a 500 Internal Server Error._

_When I comment the following two lines from action.php (lines 29/30):
```if ($pvTmp[1]=='list' && $pvTmp[3]!="") $parameters[$pTmp[0]] = $pvTmp[3]; //list default
        else if($pvTmp[1]!='list' && $pvTmp[2]!="") $parameters[$pTmp[0]] = $pvTmp[2];```The script runs, insert the entry in the table but does not upload the image. I've checked that there are the permissions set on the folders as well._

_as soon as I switch to PHP7 (with the Multiple Instances PHP through CPanel) that the problem arises_

Does anyone else has this issue on PHP7 ?

**Comment by pmfx** [comment]
For me this issue occurs even on PHP 5.4 I think it has something to do with new modules JSON configuration. When I downgraded to 1.0.15 all works fine :(

**Comment by Deesen** [comment]
Hmm, did both of you use latest version of https://github.com/extras-evolution/EvoGallery from 28.04. ?

**Comment by fourroses666** [comment]
I personally have no issues I know of. sjmclean seemed to have issues. Will contact him.

**Comment by pmfx** [comment]
Upgrade to MODX 1.1.1-beta and Evogallery to the latest (from 28.04) worked for me. Thanks Deesen!

**Comment by fourroses666** [comment]
Will close this issue, 

Last I've heared it still didn't work for sjmclean and mode some custom code.

**Comment by fourroses666** [comment]
Ah yea just noticed uploading didn't work, no eroor message nothing. 
Update with Extras did fix that.
