### ISSUE TITLE
Tab error

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#660]
Hi,
I have two page , Home and Content
Home include - three tab (General, Content , Address)
Content Include - two tab (General, Content)

I have an error when I edit Home page's addess and then I continue to edit content page .
The error occur like this : 
"managermanager : an error has occured : Type error - cannot read property 'tab' of undefined."

my mm_rules : 
mm_hideTabs('settings,access'); // Hide the settings and access tabs for all users

If I don't use this rule , the problem solve . But I want to hide setting and access tab.

**Comment by fourroses666** [comment]
Hmm, I wonder, what tab is the access tab? 
I have no error when adding that rule on 1.1.
The rule also looks to be correct: http://code.divandesign.biz/modx/mm_hidetabs
Would it be a conflict with an other rule?

**Comment by mgzawlinoo** [comment]
now , solve . I disable remember tab in site setting.
