### ISSUE TITLE
Can not "preview" unpublished pages (blank page) when logged in 

### ISSUE THREAD

**Issue by janniconl** [modxcms/evolution#662]
- I am using the latest modx 1.1.1 Dev from github
- I am sure I am logged into the manager (same domain)

I can not view resources which are unpublished anymore, when I am logged in. Everytime I preview an unpublished page (resource) I get a blank page. When I **publish** the page (resource) I see the normal contents. When I unpublsh it again it shows a white page again. 

- PHP Logs show no errors
- MODx logs show no errors
- I have this with multiple 1.1.x installations, on different hosting environments

**Anyone else having this aswell?** Or is it a plugin I'm using or something else...

**Comment by Deesen** [comment]
I am having exact the same issue but I´m not sure I found the reason.

@yama Maybe you can help? document.parser.class.inc.php line 2043 has an `exit;`. When commenting it out, I can see unpublished pages again when logged in.

**Comment by janniconl** [comment]
I believe line 2043 was added on may 10th: https://github.com/modxcms/evolution/commit/14c360116ff2cb12d1e76f3bb907d5bb47679f0c

**Comment by janniconl** [comment]
@yama Any help?

**Comment by Deesen** [comment]
I think removing the `exit;` should solve it.

**Comment by bossloper** [comment]
agreed

**Comment by yama** [comment]
thanks.

**Comment by janniconl** [comment]
Excellent, thanks Deesen
I already removed `exit;` earlier and had no problems so far.
Closing this issue
