### ISSUE TITLE
For developers. Indentation: spaces or tabs.

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#666]
Please read this: https://habrahabr.ru/post/118208/. 

IMHO, regardless of your preferences (tabs or spaces), a good habit is to use that format, which is used in the file before your making changes in (that same for end of line: crlf / lf)
https://habrahabr.ru/post/83528/#comment_2488104

as for me, before read this article I was an ardent supporter of the spaces -  I always used the 1 space for indent. Code with more than two spaces in indents irritated me - as a whole, in this respect, nothing has changed - big indents still annoying.:) 
But, after reading the article, I reviewed my preference, realizing that I can configure size of tabs in my IDE and viewers  - now it is equal to a 1 space and now foreign code became much more  easier to view and edit! .. well, except those, that with a lots of spaces in indents :)
![image](https://cloud.githubusercontent.com/assets/5120610/16594800/ba74e5da-42f4-11e6-9ba6-c275436806b0.png)

**Comment by Deesen** [comment]
I think too in this respect spaces make a lot more sense.

**Comment by yama** [comment]
If anything, I like space, but entrust you. Let's make it even with either.

**Comment by pmfx** [comment]
2 spaces indent is my choice :) Why? Very readable and don't take much space on screen.

**Comment by MrSwed** [comment]
the main message of this issue - do not mix everything into a landfill - use the same format that was up to you

**Comment by yama** [comment]
http://gizmodo.com/google-coder-analyzes-a-billion-files-to-find-a-winner-1786016648
I think, either is OK

**Comment by Deesen** [comment]
Just noticed: This issue has number of the devil 666 .. so by default consensus is not possible :-) .. just joking.

**Comment by Ronef** [comment]
Tabs is more usefull.
