### ISSUE TITLE
link to documentation in descriptions

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#667]
I think it worth pointing out a link to the extended documentation in description of config options, that may cause the users questions. That can  helps understand usage, purpose and behavior in different modes. 

But where must be an actual documentation?.. in the wiki of the repository or a separate repository, such as https://github.com/evolution-cms/docs, or in https://rtfm.modx.com/evolution/1.0 ?

for example
what is AliasListing, why it is generally added ?
how to use filters and what is it #623 
(add other options that are not clear)

**Comment by Deesen** [comment]
Also related to #645

**Comment by Deesen** [comment]
I tried to prepare something, see #668, but of course its up to each developer to fill in the information.
