### ISSUE TITLE
Change the layout a little for wide screens

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#672]
I have to scroll allot. Would this be an good solution? Don't know about any cons but looks pro to me. 

Situation now:
![hmm](https://cloud.githubusercontent.com/assets/523389/16766975/6645f730-483d-11e6-8848-ca6f4dceb845.jpg)

New situation:
![sidebar](https://cloud.githubusercontent.com/assets/523389/16766979/684e237c-483d-11e6-8cd5-3e71fb8768b7.jpg)

**Comment by fourroses666** [comment]
ideally have a (H1) header above the content. I always use [*description*] as H1 and change the name with mm_rules :(

**Comment by Fr3ddy7** [comment]
see Editor settings, it is a problem with it.
he is a fixed width

**Comment by pmfx** [comment]
To achieve more flexible and future-proof forms layout we would have to rewrite most of Manager interface with CSS framework like Bootstrap. I think about all the stuff that shows up in main Manager frame. A lot of work but it would great to make that step. ATM there is a a HTML and CSS mess.

**Comment by pmfx** [comment]
Was experimenting with rewriting Manager with Bootstrap over the weekend. A lot of work but doable. 

Login: http://prntscr.com/bvlmxx
Dashboard: http://prntscr.com/bvlnm7 and http://prntscr.com/bvlnun
Navbar: https://snag.gy/AZJPs4.jpg
Context menu: http://prntscr.com/bvlo5d
Edit resource:
http://prntscr.com/bvlojo
http://prntscr.com/bvlqw8
https://snag.gy/4Yvrhz.jpg
https://snag.gy/SmRsHL.jpg
http://prntscr.com/bvlpwu

To have it all in Bootstrap, huge amount of code will have to be rewritten. I mean HTML in 95%. Mostly files in /manager/actions/ So many changes will make it not possible to merge with current develop branch - am I right? If so, how to do this?

ManagerManager rules like "mm_hideFields" "mm_renameField" may not work as html will change. We will have to update MM. In new version .form-group divs will have unique ID so it will be very easy to target them with MM.

**Comment by fourroses666** [comment]
Just to say, Nice work! 👍 
Has great potential. 
Wonder what others think about it.

**Comment by bossloper** [comment]
I think Nicola has looked at this last year:
https://github.com/Nicola1971/BSxFLAT/issues/2
The big issue is getting away from frames, there is so much code and call backs linked in to the frame set-up. @pmfx as you say "huge amount of code will have to be rewritten". If the community can get together and work on a 'single push' away from frames then there may be a chance!

**Comment by pmfx** [comment]
For now I have moved (merged) menu.php directly to 1.php to have fully working navbar with dropdowns. I think tree iframe and main iframe can stay as as they are. Everything is working fine (updated JS to avoid menu iframe) - example: saving resource updates tree as expected. Maybe Tree can be moved but I dont know if its only updated by AJAX or by reloading too.

**Comment by Nicola1971** [comment]
@pmfx very nice work!! 
About frames: i've done the same (merged menu with 1.php) with my bsxflat theme but i've a lot of issue with refresh tree and other js issue.

If you want, we can work together to complete a bootstrap manager :)

@fourroses666 

I've added some very basic responsive features like this in my Flat manager beta3.0. 
Just for a better experience with tablets and wide screens desktops

They are based on the latest evo development code, so can be easily integrated for all the default themes:

**Editing documents in Small Screen**
![document-layout-small](https://cloud.githubusercontent.com/assets/7342798/17021413/2e55c456-4f48-11e6-9c1e-62123aa8bf53.png)

**Editing documents in Wide screen** (Revo like):
![document-layout-wide](https://cloud.githubusercontent.com/assets/7342798/17021426/3ed019e4-4f48-11e6-88d7-a25526f294e5.png)


**responsive buttons** (with awesome fonts instead icons):

wide screen
![buttons-layout-wide](https://cloud.githubusercontent.com/assets/7342798/17021436/4c344e34-4f48-11e6-9511-8887236abe4e.png)


Small screen
![buttons-layout-small](https://cloud.githubusercontent.com/assets/7342798/17021435/4a691ca6-4f48-11e6-8413-37086c6abd24.png)



**form switch**:
![form-switch-details](https://cloud.githubusercontent.com/assets/7342798/17021461/70dad1a4-4f48-11e6-9845-ba6dadbc2afa.png)


![formswitch-inmenu](https://cloud.githubusercontent.com/assets/7342798/17021588/3acc1c0c-4f49-11e6-9c30-e4a5a5d9f922.png)

**Comment by pmfx** [comment]
@Nicola1971 thanks, as for JS I had a lot of error log investigating but yes - tree refreshing works fine, and no bigger errors noticed. It would be great to have you working on this too.

If any of you guys want to check it out, here is **live version**:
http://pm-fx.com/sandbox/evobootstrap/manager/
user: githubviewer
password: gview345

**Comment by Nicola1971** [comment]
checked your manager.
I think we can merge a lot from both projects ;)

**Comment by fourroses666** [comment]
@Nicola1971 
Hey thats nice, I didn't knew it was revo-like next to eachother.
Never took the time to try it out.

**Comment by Nicola1971** [comment]
however, if the development team is interested in adding these two features, i've created a fork with latest evo 

Layout for wide screen + switch (mutate_content.dynamic.php modification)
https://github.com/Nicola1971/evolution/commit/9ab6cf31fcfb59cce329288d764a87f2936390b2

addition in MODxRE and Carbon of very minimal responsive.css 
https://github.com/Nicola1971/evolution/commit/74fd6d1130f7ba1129bcd9425e0c12e9c634b7ac

link rel to responsive.css in header.inc.php
https://github.com/Nicola1971/evolution/commit/3482fe0c327355a256d4ae45b341a40f86d7c3a8

Result:
![general](https://cloud.githubusercontent.com/assets/7342798/17026513/948125b4-4f60-11e6-982b-7caee2f285db.png)

![settings](https://cloud.githubusercontent.com/assets/7342798/17026527/9f5c41e4-4f60-11e6-9c0c-28262d27fa61.png)

works with all classic themes

**Comment by fourroses666** [comment]
I remove the Introtext field (9 out 10 times) with mm_rules (and the longtitle) and it would look a bit weird then :(

So its not possible to place content left and other fields right? 
I'm a bit neutral on this then, I'm oké with or without that rev styled fields on wide screens.

**Comment by Nicola1971** [comment]
removing introtex? yes should be a little weird  :D

**Comment by nick0** [comment]
Wonderful work @pmfx - those screen caps look really awesome. Very modern and functional. It looks really exciting. 
I must say though I prefer the original / current format with the "menu settings" (menu title and menu index etc) in the one group of fields as title, description etc. It flows nicely currently and is easy to use.

@fourroses666 and @Nicola1971. Please don't move the General fields (title, description, summary etc to the RHS. It make no sense. It is no problem scrolling down to the resource content RTE. On narrower screens, if they stack below when Evo becomes responsive, that's even worse. The current "field flow / layout" works really well. If you are going to roll something like this out, please give the option to revert back to vertical stacking.

**Comment by bossloper** [comment]
It does look nice, but the same as @fourroses666 I also remove introtext and longtitle using managermanager + move 'used template' to the settings tab (90% of the time template never needs changing for daily manager). Sometimes I also move a couple of key TVs to the menu tab so they are at the top. Also worth remembering this would effect QM+ too.

So I would be concerned the 2 column approach could mess up a few peoples managermanager setup.

Could the whole 2 column setup be handled by a managermanager plugin instead. Not the nicest solution from a coding perspective but would at least be optional and maybe the plugin could specify the fields for the second column?

**Comment by pmfx** [comment]
@bossloper thanks. Here are examples without introtext and longtitle field. I agree it breaks layout flow a little. Maybe stacked fields is the best way after all.

Two columns & hidden fields: https://snag.gy/ylPQrf.jpg
Stacked & all fields visible: https://snag.gy/nzoSAu.jpg
Stacked & some fields hidden: https://snag.gy/tTo3uH.jpg
Two columns alternative & all fields: https://snag.gy/zWGVSb.jpg
Two columns alternative & hidden: https://snag.gy/JtTIx2.jpg

What do you think about last two examples? I think it's a nice compromise between two options.

**Comment by fourroses666** [comment]
The last one does look the best to me. I don't know how the source/code of the page looks like but is it possible to wrap or change it like the image below? Full width and 3 columns.
To me this looks allot better (on wide screens). Don't know the options.

If its possible with a plugin (like @bossloper says) to get a sidebar I would definately like that.
_I like to see the content as far up as possible._

![example](https://cloud.githubusercontent.com/assets/523389/17052051/1487fe72-4ffc-11e6-85ec-ab9b9c21e9d0.jpg)

**Comment by bossloper** [comment]
Agree last one looks best, but I still think whatever you do it will restrict the flexibility of managermanager where all fields can be moved anywhere, into tabs etc so someone out there will end up with a layout that is compromised.... unless we go the next level #688

**Comment by Nicola1971** [comment]
@bossloper: in my tests, replace tables with divs in mutate_content.dynamic.php brokes managemanager functions :(

**Comment by Nicola1971** [comment]
It would be better a manager able to manage all this layout option with manager manager instead broke it

**Comment by pmfx** [comment]
@fourroses666 I don't think a fluid width (100%) conatainer is a best option. There will be problems with that. Thats why I suggested fixed width container (its max-width: xxx actually) because it is a lot easier to mantain and dont break layout. This will keep thing nicely together and more or less in the center of the screen. Thats the idea.

@bossloper I agree, but what do you suggest - merge "general", "menu settings" and "other" fieldsets into one and all stacked? It would work but page will expand vertically a lot. I suggest using 2 cols like it is now, eventually rethink what fields should be in which fieldset and if proposed by me fieldsets general", "menu settings" and "other" are logical and works fine.

@Nicola1971 Of course replacing tables with divs will break MM rules. But there is no other way. ManagerManager will have to be updated as well. But it would be much easier and cleaner to target fields by MM dev as every .form-group (label,input,optional help text) will have it unique ID.
> Can you send me a copy of the manager or create a git to fork?

Sure but I think it is too early. Have to update some things there first.

**Latest screenshots:**
http://prnt.sc/bw2j1v
http://prnt.sc/bw2jgg

**Demo is still there:**
http://pm-fx.com/sandbox/evobootstrap/manager/
user: githubviewer
password: gview345

**Comment by pmfx** [comment]
I have moved to new issue #690

**Comment by bossloper** [comment]
@pmfx - I meant as managermanager can create tabs (which is a great feature) any of the existing fields can be moved from general into a custom tab potentially leaving maybe only one field in general.

For my site managers I try to keep the number of fields to a minimum on the General tab...
I move the' menu title' and 'show in menu'. Then move the more admin orientated ones to an 'admin' tab that only certain managers can see. So I normally have 'title', 'description', 'menu title', 'show in menu' and 'published' on the general tab followed by resource content, which keeps the content quite high up the page.

So my general point is it will be very hard to make a 2 col design work for everyone if they make a lot of use of the managermanager, unless this 2 col setup can be made optional.

![edit](https://cloud.githubusercontent.com/assets/1744687/17055826/4d73a42e-5007-11e6-890d-4be84addf718.png)

**Comment by pmfx** [comment]
@bossloper OK I see your point and I agree. Maybe new ManagerManager rule for 2 cols would be best then.

**Comment by nick0** [comment]
The new screen caps look beautiful @pmfx. I am all for fields and a manager that look as nice as that.
But I agree with @bossloper that the extra columns should be handled by managermanager / a managermanager plugin so as not to interfere with current MM settings / preferences. 
I also think the sub category headings should be done by MM also. The sub headings take up a lot of additional vertical screen space. 
So does having the labels above the form field. They look really so nice above but having the labels to the left of the form field does save vertical real estate.
Maybe "placeholder" text could be used instead, doing away with labels altogether eg placeholder="Longtitle" etc?
I use MM lots to hide various unneeded fields on many different templates - here are some examples:
*longtitle,link_attributes,menutitle
*longtitle,description,introtext,menutitle,content
*longtitle,description,link_attributes,introtext,menutitle
*longtitle,description,link_attributes,introtext,content
*longtitle,alias,link_attributes,introtext,menutitle,content
*description,alias,link_attributes,introtext,menutitle,content
*longtitle,description,alias,link_attributes,introtext,menutitle,content
Having sub headings will end up a lot less neater and actually take up more screen real estate in this instance. 
One template will have 2 fields above, 1 field to the right, 1 field below. 
Another will have 1 field above, 2 to the right, 1 below etc. 
All in sections with sub headings that take up more space than the individual fields themselves. 
I feel with this kind of usage it will actually seem less organised, more bitsy and it will end up looking like WordPress which is all over the shop. 
I vote the default setting remains as one groups of fields as per currently with no sub headings.

**Comment by fourroses666** [comment]
I will close this. This will be possible with the new template engine.

https://github.com/modxcms/evolution/issues/764#issuecomment-250380369
