### ISSUE TITLE
$modx->makeURL() change in 1.1 breaks link

### ISSUE THREAD

**Issue by Breezer** [modxcms/evolution#674]
I have a call to makeURL which works through 1.0.15, then is broken in 1.1. It appears to be when furls are disabled.
The line is this:
`$xforum['ajax_processor_url']  = str_replace( '&amp;', '&', $modx->makeUrl( (int)$xforum['ajax_processor_id'], $alias= '', $args= 'action=', $scheme= 'full' ));`

output in 1.0.15:
http://localhost/evolution1015/index.php?id=17&action= 
 http://localhost/evolution1015/utility/ajax_processor?action=

output in 1.1:
http://localhost/evolution1_1/index.php?id=17?action= 
 http://localhost/evolution1_1/utility/ajax_processor?action=

**Comment by Deesen** [comment]
I guess its related to #616 . Should already be corrected for 1.1.1 with commit https://github.com/modxcms/evolution/commit/16dee097a9ae0d6ecc0ee2a7af0b7a8571caac0c

**Comment by Breezer** [comment]
Quick testing with the 16dee09 commit seems to work, thanks and this issue can be closed I think.
