### ISSUE TITLE
$modx->changeWebUserPassword

### ISSUE THREAD

**Issue by urbanklpn** [modxcms/evolution#676]
updates db with unhashed password
fix please 
$this->db->update(
                            array(
                                'password' => $this->db->escape($newPwd),
                            ), $tbl, "id='".$this->getLoginUserID()."'");
to
$this->db->update(
                            array(
                                'password' => $this->db->escape(md5($newPwd)),
                            ), $tbl, "id='".$this->getLoginUserID()."'");

**Comment by Deesen** [comment]
Related to #304
