### ISSUE TITLE
query re errors on login "Important System Files have been modified"

### ISSUE THREAD

**Issue by nick0** [modxcms/evolution#677]
Hello,

Whenever I login to any one of my Evo 1.0.15 sites (its been happening from memory since 1.0.13), I get sent an error email saying "Source: Important System Files have been modified. - The details of the error could be seen in the MODX system events log.".

When I go to Reports > System Events I see the corresponding error titled "Important System Files have been modified."

A configuration error shows on the "home tabs" saying "One or more configuration details didn't check out OK:..."

These 4 items are listed in Tools > Configuration > User:
* index.php
* .htaccess
* my-custom-manager-folder-name/index.php
* my-custom-manager-folder-name/includes/config.inc.php

All I am doing is logging in and an error is reported.

Does anyone else get this error? Any idea whats causing it and how to stop it?

Thanks for any help.

**Comment by Deesen** [comment]
When you save configuration a hash (MD5 of your 4 files) gets calculated. If you edit one of those 4 files (like modifiying .htaccess) afterwards, you´ll get the message ""Important System Files have been modified." as the hash has changed. So you need to save again your MODX-config to update it.

**Comment by nick0** [comment]
Ah I see. Thanks for explaining that Deesen, I never knew that. 
On re saving the configuration settings, the error is no longer visible on the "home tabs".
Thanks a lot.

**Comment by yama** [comment]
This feature I have made in a long time ago , I do not think there is less need now.
It can often lead to confusion , I think that may be abolished.

**Comment by Deesen** [comment]
Maybe a more detailed "warning-message", and a "remove notification"-button to rebuild the hash with a mouse-click?

**Comment by bossloper** [comment]
+1
I would like to see the feature stay in some form if possible.

**Comment by Deesen** [comment]
@nick0 Maybe you want to reopen this issue so its on the list.

**Comment by nick0** [comment]
Done. Thanks Deesen and Yama

**Comment by Deesen** [comment]
LOL, now maybe it can be closed? ;-)

**Comment by nick0** [comment]
Haha, ok closed. Thank you again
