### ISSUE TITLE
New 'Manage Image/File/Element button

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#681]
On latest beta (as of 18th July).
Should the display of the 'Manage Image/File/Element' buttons be supressed if the manager has no permission?

At the moment if a manager is not an element editor the buttons are displayed and clicking them nothing happens, not even a 'no permission' message.

**Comment by Deesen** [comment]
I think it should be suppressed. Most professional way to avoid confusion.

**Comment by pmfx** [comment]
There is a conditional for "elements button" already. As for images/files I think we should create two new permissions for images and files. Feels like it would be useful. 1st permission to manage images (assets/images/) and 2nd permission to manage files (assets/files/).

**Comment by bossloper** [comment]
@pmfx - yes but the conditional is just on if the javascript should be written or not. This means if the manager does not have permission they still see the buttons, but clicking them nothing happens (not even a message), which might be confusing.

New permissions would be good, but how or would they also be applied to TinyMCE toolbar when adding images or file links?

**Comment by pmfx** [comment]
@bossloper there is no check right now for images/files management. If you or someone else can fix it, please do. As for "elements management tree button" it is wrapped in php:

`<?php if ($modx->hasPermission('edit_template') || $modx->hasPermission('edit_snippet') || $modx->hasPermission('edit_chunk') || $modx->hasPermission('edit_plugin')) { ?>
    <td><a href="#" id="Button12" class="treeButton" title="<?php echo $_lang["element_management"]."\n".$_lang['em_button_shift'] ?>"><?php echo $_style['element_management'] ; ?></a></td>
<?php } ?>
`

So I think it is OK, right?
Good question about TinyMCE Toolbar. Would be great if it respects those new permissions.

**Comment by bossloper** [comment]
I suppose the new roles for images and files would be used in TinyMCE to decide if the 'Browse' button is displayed next to 'Image URL' and 'Link URL'. For better security the new roles would also check at the browser level so a manager cannot just paste in the browser edit url.

**Comment by Deesen** [comment]
Reg. TinyMCE: We can add at beginning of mcpuk/browse.php 

    if ($modx->hasPermission('file_manager')) {
      echo 'no permission';
      exit;
    }

so at least a message is given in pop-up. With TinyMCe4 and modxRTEbridge we can add the same IF-clause so the button only gets added to a theme when having permission.

**Comment by bossloper** [comment]
@Deesen - you beat me too it! It would make sense to hide the browse button (if no permission) in the TinyMCE popup too though?

**Comment by bossloper** [comment]
@pmfx - re elements management tree button - yes looks good to me.

**Comment by bossloper** [comment]
@Deesen  - though it would not be 'file_manager' - as I understand it that is a separate role for access to the whole file system not just the mcpuk files in assets/files.

**Comment by Deesen** [comment]
@bossloper : Ah you now I know what you mean. There are 2 pop-ups. One by TinyMCE for the image, the next one by MODX for image/file-manager. In TinyMCE3 you can remove the file-manager button by removing param "file_browser_callback" from tinymce/js/mce_init.js.inc line 60.  So we could use hasPermission() to control this param.

For TinyMCE4 I need to check later but I guess its similar.

Reg. permission 'file_manager' you are right, was just meant as example.

**Comment by Deesen** [comment]
So we need 2 additional permissions to grant separate access to assets/files or assets/manager. How to call them? Maybe

    hasPermission('assets_images')
    hasPermission('assets_files')

**Comment by bossloper** [comment]
@Deesen - yes that is what I was referring to. I don't think there are any other places in the default setup where the file manager is called? 
Adding the check to browser.php would catch any calls that may come from a custom manager setup. The check it would need to distinguish between a request for images and files to then cross-check against the applicable new role. Your suggestion 'assets_images' and 'assets_files' seems good to me and is distinct enough from the existing 'file_manager' role.

**Comment by Fr3ddy7** [comment]
I noticed that the buttons do not disappear with the manager, they have but when you click nothing happens :) it's ok? It may make sense not to show

**Comment by Deesen** [comment]
Hmm buttons must be hidden when having no permission ( https://github.com/Deesen/evolution/commit/96bcfe5eee84882745971d702dc305eb79735869 ).

**Comment by Fr3ddy7** [comment]
checked on another site, similar) button is, when you ckick - nothing

**Comment by Deesen** [comment]
Can you check browser-console for any message? Maybe a JS-error?

**Comment by Fr3ddy7** [comment]
clean, no error's, no warnings

**Comment by pmfx** [comment]
Guys I think it is tree.php:436 We need to have 3 if there not 1.

![2016-07-30-09-41-02](https://cloud.githubusercontent.com/assets/10888055/17268913/c422dab2-5639-11e6-8718-59a1fd32c7ea.png)

**Comment by Deesen** [comment]
Thanks, will correct it after the weekend if nobody else takes care of it.

**Comment by pmfx** [comment]
Added a commit for this. I hope it work fine ;)

**Comment by Nicola1971** [comment]
@bossloper:  we can close this issue

**Comment by bossloper** [comment]
Ok

**Comment by bossloper** [comment]
Ok
