### ISSUE TITLE
Translation of Manager

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#693]
I'd like to do some Manager translations.
Noticed it needs a bit of attention.

But where do I need to do this?
Do I need to copy English files and translate them in my own language or can we use some software:

I liked Transifex; 
https://www.transifex.com/modx/modx-evolution/

**Comment by Deesen** [comment]
I can also take care of english and german translations but I have no clue who is in charge of Transifex to grant permissions.

**Comment by fourroses666** [comment]
Yama and dmi3yy. Jako isn't active for Evo anymore.

**Comment by fourroses666** [comment]
@yama / @dmi3yy 
Can we update Transifex? Looks to me last update was: Oct 10th 2014.
So probably the lang files needs to be uploaded to Transifex again?

**Comment by yama** [comment]
https://www.transifex.com/modx/modx-evolution/dashboard/
Thanks for your information. Updated.

**Comment by Deesen** [comment]
Great! I already updated german.

**Comment by fourroses666** [comment]
Updated Dutch!

**Comment by fourroses666** [comment]
I'm closing this issue. Would be great if it can be added before the newest version comes out. 👍 

```
German (de) 99% - 1 string to translate
Italian (it) 97% - 51 strings to translate
Polish (pl) 97% - 54 strings to translate
Spanish (es) 97% - 51 strings to translate
Swedish (sv) 97% - 51 strings to translate
Finnish (fi) 96% - 71 strings to translate
Russian (ru) 96% - 59 strings to translate
```

**Comment by fourroses666** [comment]
Did some update again. 👍 

```
Dutch (nl) 100% - ready for use
German (de) 99% - 1 string to translate
Italian (it) 96% - 58 strings to translate
Polish (pl) 96% - 61 strings to translate
Russian (ru) 96% - 66 strings to translate
Spanish (es) 96% - 58 strings to translate
Swedish (sv) 96% - 58 strings to translate
Finnish (fi) 95% - 78 strings to translate
```

**Comment by fourroses666** [comment]
Two new strings to update;

```
Dutch (nl) 100% - ready for use
German (de) 99% - 3 strings to translate
Finnish (fi) 96% - 75 strings to translate
Italian (it) 96% - 59 strings to translate
Polish (pl) 96% - 59 strings to translate
Russian (ru) 96% - 67 strings to translate
Spanish (es) 96% - 59 strings to translate
Swedish (sv) 96% - 59 strings to translate
```

**Comment by Deesen** [comment]
Also a lot of keys are missing (only existing in english.inc.php but not on Transifex) so cannot be translated. I made a small script to find out which :

`author_infos, confirm_delete_group, confirm_reset_sort_order, documentation, files_management, files_management_no_permission, further_info, images_management, last_update, license, parse_docblock, parse_docblock_msg, purge_plugin, references, report_issues, reset_sort_order, role_assets_images, role_assets_files, role_file_management, search_criteria_top, search_criteria_top_msg, search_criteria_url_msg, set_automatic, set_default, set_default_all, sort_alphabetically, sort_menuindex, sort_updating, sort_updated, sort_nochildren, sort_elements_msg, template_notassigned_tv, template_selectable, tmplvars_rank_edit_message, use_breadcrumbs, use_breadcrumbs_message, version, enable_filter_title, enable_filter_message, setting_resource_tree_node_name_desc_add, aliaslistingfolder_title, aliaslistingfolder_message, version_notices, em_button_shift, reset_sysfiles_checksum_button, reset_sysfiles_checksum_alert, file_browser_disabled_msg, which_browser_default_title, which_browser_default_msg, which_browser_title, which_browser_msg, option_default`

**Comment by fourroses666** [comment]
Good you found these. So the langfile needs to be uploaded to Transifex?

Don't know if its hard to do and wise, but on an Opencart site I had there was a plugin where the  strings could be translated. Would be ideally to translate these within the manager. But I'm not a coder.

**Comment by Deesen** [comment]
Yes needs upload but we do not have nessecary admin-rights.

Does Opencart use Transifex? I guess translation works only locally like in Joomla, right?

**Comment by fourroses666** [comment]
Isn't Yama/Dimmy able to do?
Else, maybe we need to drop Transifex then?

If these langfiles could be edited within the manager it might be possible to export/pull request the langfile and don't need Transifex.

Never used Joomla.

There is an Extention for OC to use multilang.
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=16468

Maybe its better to translate directly into the langfiles.
Its not that hard to pull these files, but the missing strings should be added first.

**Comment by Deesen** [comment]
Surely they have the rights to upload, I guess we just need to wait..

**Comment by fourroses666** [comment]
Dutch is 💯 %

**Comment by pmfx** [comment]
Polish :100:%

**Comment by yama** [comment]
thanks

**Comment by fourroses666** [comment]
https://www.transifex.com/modx/modx-evolution/dashboard/

German / Russian: 39 strings to translate

**Comment by Deesen** [comment]
Thanks for reminding!

**Comment by fourroses666** [comment]
@pmfx - 13 strings to translate :octocat:

**Comment by pmfx** [comment]
@fourroses666 thanks for notice and done :)

**Comment by fourroses666** [comment]
2 new ones appeared!
PL NL = 💯 %

**Comment by fourroses666** [comment]
I have no permission (anymore) to translate already translated strings in Transifex :( @yama @dmi3yy

**Comment by dmi3yy** [comment]
Can you sent your email  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


суббота, 17 декабря 2016 г. в 13:15, Marc написал:

**Comment by fourroses666** [comment]
marc [a] graffx.nl

**Comment by dmi3yy** [comment]
I think @yama have more permision ) need add for Mark Role Corrector  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


суббота, 17 декабря 2016 г. в 13:17, Lukianenko Dmytro написал:

**Comment by dmi3yy** [comment]
try now  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


суббота, 17 декабря 2016 г. в 13:20, Marc написал:

**Comment by fourroses666** [comment]
Yea works now, thx.

**Comment by fourroses666** [comment]
Still have no access dmi3yy but I noticed I have 2 accounts!
So I logged into the other one and its oke now!
