### ISSUE TITLE
new icons in tree 8)

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#694]
I suggest to change the standard icons in the tree. As an option is taken from the pre-made themes, new icons for documents, folders, and so on.

like:
http://s018.radikal.ru/i508/1607/1b/62e02a5521e6.png
or
http://s020.radikal.ru/i706/1607/47/a3a43aa0b799.jpg

the standard has long become boring and a lot of edits in the standard template, we have to abandon the other, in the direction of new buns and goodies :)

**Comment by Fr3ddy7** [comment]
what think of community?

**Comment by fourroses666** [comment]
I like the first one. But should be implemented in the Bootstrap version.
https://github.com/modxcms/evolution/issues/690

**Comment by Fr3ddy7** [comment]
It seems to have written that the default theme will also be available) so it makes sense to finally change the old icons in the tree

**Comment by nick0** [comment]
I like the first one too (62e02a5521e6.png), with a suitable pdf and word doc icon too.
Then folders, pages, xml, pdf and docs are covered.
Nice work
