### ISSUE TITLE
multitv + tv problem after update (last from git)

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#696]
https://s32.postimg.org/rc0jl8ddh/1111.png

table and other tv on a separate tab, after the upgrade - all mixed up, and so on two different sites.
in source code - all td+tr (multitv+tv) merged into one large and "beautiful" table :(

**Comment by Fr3ddy7** [comment]
noticed if you put multitv the latest in a list on the new tab - everything is fine

mm_rules:

`if(in_array($content['id'], array(4,17,18,19,55,22,23,24,28))){
    mm_createTab('Настройка курсов', 'course', '', '', '', '');
    mm_moveFieldsToTab('after,cost,date,duration,time,picture,slider,table', 'course', '', '');
}`

multitv config - datatable
Thanks for help :)

**Comment by Deesen** [comment]
You wrote "if.... everything is fine". Is your problem solved? I´m using MultiTV and mm_moveFieldToTab a lot and have no issues.

**Comment by Fr3ddy7** [comment]
you use datatable config ? or another ?

this problem just with datatable (:

**Comment by Deesen** [comment]
Yepp, most of the times I use "datatable"-mode.

**Comment by Deesen** [comment]
Maybe you can provide manager-access to a demo-installation so we can check "live" what is going on?

**Comment by Fr3ddy7** [comment]
http://design-school.kiev.ua/manager/
login - git
pass - FhqvaMNY

test document in tree, test tab in document

**Comment by Deesen** [comment]
Thanks, now I understand. It is strange indeed. I tried some things and by putting "table" from beginning to the end like `mm_moveFieldsToTab('lp-reviews,lp-teachers,table', 'test', '', '');` it seems to work.

**Comment by Fr3ddy7** [comment]
i'm talking about this and wrote that if you put table  to the end - everything is going fine.

**Comment by Fr3ddy7** [comment]
maybe it's a problem of multitv ?

**Comment by Deesen** [comment]
Sorry I thought "the latest" was refering to MultiTV version ;-).

I´m not sure if problem is related to MultiTV or ManagerManager. But if I change line 129 in /assets/plugins/managermanager/js/jquery.ddMM.js

`var $movedTV = $toMove.appendTo($target.find('> table:first'));`

to 

`var $movedTV = $toMove.appendTo($target);`

it works for me with "table" at first place. But I´m not sure if it is safe to remove "> table:first".

**Comment by Deesen** [comment]
I reported the issue to DivanDesign, let´s see..

**Comment by Fr3ddy7** [comment]
thnx 8)
