### ISSUE TITLE
Error "Parser - if ($q[strlen($q) - 1] == '/')"

### ISSUE THREAD

**Issue by Fess7** [modxcms/evolution#698]
Error information: 
ErrorType[num]  WARNING[2]
File    ...\manager\includes\document.parser.class.inc.php
Line    472
Source  if ($q[strlen($q) - 1] == '/') 
REQUEST_URI     http://modx/?q[]=1

Backtrace:
DocumentParser->executeParser()
index.php on line 146
DocumentParser->cleanDocumentIdentifier(array $var1)
manager/includes/document.parser.class.inc.php on line 1941

MODX does not filter array.

**Comment by yama** [comment]
> REQUEST_URI http://modx/?q[]=1

There may be a problem here .

**Comment by yama** [comment]
https://github.com/modxcms/evolution/commit/67727686c359d18166ff3f9b3c53c1a233792ecb
I solved the problem of the q parameter.
https://forums.modx.com/thread/77732/index-php-q---problem
https://forums.modx.com/thread/28689/request-q-vs-server-request-uri

**Comment by Fess7** [comment]
@yama, why did you remove `?q=$1` in ht.access?
At present, sites do not work without `q`.

**Comment by yama** [comment]
With or without a "q", it should work . Does not it work?
So , line 11 of the document.parser.class.inc.php, please try to insert the "exit($q);" to the previous line of "return $q;"(line 2011 ) .
And , please look at your site . What will be displayed ?

**Comment by Fess7** [comment]
In the document.parser.class.inc.php has `$_GET['q']`, therefore I think have to be so:
 `$_REQUEST['q'] = $_GET['q'] = $this->setRequestQ($_SERVER['REQUEST_URI']);` -> [code](https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L1888)
\+ There are `$_GET['q'], $_POST['q']` there -> [code](https://github.com/modxcms/evolution/blob/develop/index-ajax.php#L37)

**Comment by yama** [comment]
Thanks!

**Comment by Fess7** [comment]
@yama, thank you for your help!

**Comment by dmi3yy** [comment]
Its incorrect with this no correct work some plugins. 
$_REQUEST['q'] = $_GET['q'] = $this->setRequestQ($_SERVER['REQUEST_URI']);

With this line: 
http://take.ms/KqeIf

Without 
http://take.ms/OOypQ

and  $_GET['q'] cant be array its incorrect. 
and need only $_GET['q']

no use  $_REQUEST. 

if use $_REQUEST    $_POST['q'] - work to its incorrect
