### ISSUE TITLE
nested tv or nested binding

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#699]
Hi,
Is there a nested tv dropdown list between two tvs ? or
Nested binding (@select) between two parents documents that connect with two tvs. ?

Eg. Country chain select with Town .

**Comment by Deesen** [comment]
Firstly I think you would need a database for Country / Town relations. Secondly its not possible to refer to another TV´s value as I know. I guess it would need something like

"tv_country": @SELECT country_name, country_value FROM countries
"tv_city": @SELECT city_name, city_value FROM cities WHERE country_value = [+tv_country+]

But [+tv_country+] will not be replaced right now. Or do you need something different?

**Comment by Deesen** [comment]
Maybe you wanna try it?

**Comment by mgzawlinoo** [comment]
Thandk you Deesen , I will try it .

**Comment by Nicola1971** [comment]
Wow waiting nesting tv drop down from a lot of years. Great @Deesen . I will try soon

**Comment by dmi3yy** [comment]
Its easy do with custom TV ;) 


Отправлено с iPhone
