### ISSUE TITLE
Wayfinder, very strange. After add '[+wf.menuindex+]', TVs do not handled normaly.

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#701]
so.. using
```
[[Wayfinder? &startId=`0` &level=`2` &useWeblinkUrl=1 &rowTpl=`menurow` ]]
```
where menurow with test TV Vars :
```
<li[+wf.id+][+wf.classes+]><a href="[+wf.link+]" title="[+wf.title+]" [+wf.attributes+] 
data-test="[+hideChildsMenu+] [+DisplayListStyle+]
">[+wf.linktext+]</a>[+wf.wrapper+]</li>
```

where hideChildsMenu can be 0,1 or empty, DisplayListStyle can be empty or an string
all versions after 95e2020d1e1355e9b822fb292412ae0ac78923cf 
get in the is unpredictable result in data-test - only numbers, and regardless of the set value of needed TVvars hideChildsMenu - always 0, DisplayListStyle  sometime - 1

But, after delete '[+wf.menuindex+]' at line [L42](https://github.com/modxcms/evolution/blob/develop/assets/snippets/wayfinder/wayfinder.inc.php#L42) i get normal result !! (data-test="1 gallery")

So, Can someone explain to me why this is happening?!

real menurow wil be:
```
<li[+wf.id+][+wf.classes+]><a href="[+wf.link+]" title="[+wf.title+]" [+wf.attributes+]>[+wf.linktext+]</a>[+phx:input=`[+hideChildsMenu+]`:ne=`1`:then=`[+wf.wrapper+]</li>
```

**Comment by MrSwed** [comment]
it looks like a restriction on the number of elements in the array
$this->placeHolders['rowLevel']...

**Comment by Deesen** [comment]
In wayfinder.inc.php @ line 251 / 253 the menuindex was missing in $phArray. I added it.

**Comment by MrSwed** [comment]
Thats it! Thanks!
