### ISSUE TITLE
API: getSnippetName or currentSnippet

### ISSUE THREAD

**Issue by MrSwed** [modxcms/evolution#703]
subj do not work. 
Don`t in standart snippet, no included.
for example, if I want to write self recursive snippet, I need it.

**Comment by Deesen** [comment]
Inside "if"-snippet I added `echo 'snippet='.$modx->getSnippetName();` and it displays "snippet=if". Not sure how to recreate your issue.

**Comment by MrSwed** [comment]
yeah.. I see, 
It  do not work after some $modx->runSnippet(), but this is solved. 
thanks!
