### ISSUE TITLE
elFinder 2.1.x for MODX Evo

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#705]
As addon / optional replacement for KCFinder. For testing just rename original "mcpuk"-directory (/manager/media/browser/mcpuk) to something else and upload elFinder.

https://github.com/Deesen/elFinder-for-modx-evo

Should already work with TinyMCE3 & 4 and uses MODX-configuration. Related to #629.

**Comment by pmfx** [comment]
Cool but I'm not familiar with it. 
Can you tell me is it better than KCFinder?
Is KCFinder outdated? Whats the main reason to switch?

**Comment by Deesen** [comment]
I want to make File Browsers optional, so in MODX/user-settings you can choose which Browser you prefer (KCFinder or elFinder). KCFinder is not maintained anymore as I know while elFinder is maintained, and provides lot more features. Maybe it works also better on mobiles or Mac Safari. Demo: http://studio-42.github.io/elFinder/

**Comment by fourroses666** [comment]
Looks like the extended version of kcfinder, oke with me.
Only downside is allot of extra small files to the package.
I'm even oke with complete replacement but I'm sure some just would like to keep the old kcfinder one.

**Comment by Deesen** [comment]
Me too so I made it optional like dmi3yy proposed it. If you have issues for example with Mac Safari now, you have option to try alternatives like elFinder. And I guess it will not be added to MODX-core (why 2 file-browsers?), so no increasing of files.

**Comment by fourroses666** [comment]
👍

**Comment by pmfx** [comment]
OK, that can be very useful indeed. Thanks @Deesen !

**Comment by Fr3ddy7** [comment]
elFinder
used in it do not work preview, when you insert a picture in the TV or multitv
