### ISSUE TITLE
Templte Image

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#708]
Hi,

Is it possible to add template image?
Eg. When I'm make new resource and choose template dropdown, 
the template style images will show next side. 

Template image will be manually add at template section.

**Comment by Fr3ddy7** [comment]
a useless idea, before you create such a - consider whether it is somebody else, or just for you. There are introducing new features, remove the old bugs, but do not solve the problem of each individual. 

There is a community (http://forums.modx.com/), for a nominal fee, good people can do like (but it will be for you personally, and to update the system - more of a problem.)
