### ISSUE TITLE
MODxRE treeNodeHover colors (1.1.1 beta 2)

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#713]
latest 1.1.1 beta 2

![tree-item-hover](https://cloud.githubusercontent.com/assets/7342798/17782894/dccb300a-6575-11e6-8008-0c71a71ca50f.jpg)

**Comment by Fr3ddy7** [comment]
installed the latest version, I do not observe this problem

**Comment by Deesen** [comment]
Me too. @Nicola1971 : What does browser-inspector say? Any hint?

**Comment by Nicola1971** [comment]
uploaded again Beta 2 files, issue vanished. Probably a corrupted css?
