### ISSUE TITLE
Sort By TV Value or Filter TV Value

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#714]
Hi,
At Resource Overview, 
There was a Sort by -> Creation date, Pub date, Title, Menu index and Order by Asc , Desc.

I would like to know is there a function to add sorty by tv value or filter by tv value.
Eg. I have a product type tv and at resource overview, I can filter to see product type one resource.
![standard modx cms manager](https://cloud.githubusercontent.com/assets/9032715/17885365/114a1ce4-6943-11e6-8c5d-81e8ec3c0e17.png)

**Comment by Nicola1971** [comment]
try this module:
http://www.tattoocms.it/extras/modx-modules/article-manager-module.html

**Comment by mgzawlinoo** [comment]
Thank you Nicola , awesome website , awesome extras .
