### ISSUE TITLE
multitv + date picker (1.1.1 beta2)

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#720]
Hello)
the calendar (date picker) changed, now there is a problem in multitv. (datatable config)

I put a screen on previous versions of the kind, and he was a bit of another type) 
return normal date picker:)

https://postimg.org/image/hjf3tmcv3/
https://postimg.org/image/yio28vo2n/

probably because they have added a strange air-datepicker

**Comment by Deesen** [comment]
This should make MultTV compatible with new datepicker.

**Comment by yama** [comment]
https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/includes/multitv.class.php#L394-L396
Maybe these lines.

```
if (isset($currentClass[1])) {
    $_ = $currentClass[1];
    if(!isset($this->modx->config['mgr_date_picker_path']))
        $_ = str_replace('DatePicker', 'mtvDatePicker', $_);
    $fieldClass[] = $_;
}
```

**Comment by Fr3ddy7** [comment]
better) now at least seen datapiker

find more:
1. triggered immediately, push the box - nothing. Gone cursor, press again - showing ok.
2. it would be great that he was tuned, because this is not seen the last of the field.
3. in the old could ubrezat time (if not necessary, and only necessary data)
then sought, not found

why have removed the old one? he even design was better than this))

**Comment by Fr3ddy7** [comment]
https://postimg.org/image/vnxrv1zmd/

**Comment by Fr3ddy7** [comment]
4. new datapicker makes vertical scrolling, as its position relative to the field = down. you need to maximize the window, in order to work properly) in the old was better aligned to it = up, relative to the field

**Comment by yama** [comment]
@Fr3ddy7 
Thanks for your information. I'll try later considered them.

**Comment by Fr3ddy7** [comment]
#724
