### ISSUE TITLE
To bind the DatePicker in manager theme

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#722]
https://github.com/modxcms/evolution/issues/720
related to

https://github.com/modxcms/evolution/blob/abd43f80b1b5c38c4b9f043c80f1ee264f9ae256/manager/media/style/MODxCarbon/style.php#L16
$modx->config['mgr_date_picker_path']='media/style/MODxCarbon/moo-datepicker/datepicker.inc.php';

**Comment by Fr3ddy7** [comment]
why MODxCarbon ?) because the default is always ModxRE

**Comment by Fr3ddy7** [comment]
propose to remove the old theme and leave a ModxRE, as it most edits already

**Comment by Deesen** [comment]
As I know there are several people still using Theme "Modxcarbon", like @modxuser. So when removing it I´m sure not everybody will be happy with it. Maybe we should wait and see what comes out of the new manager-template engine first https://github.com/modxcms/evolution/issues/690#issuecomment-237077383

**Comment by modxuser** [comment]
@Fr3ddy7

"MODxCarbon" took over from "MODxLight" & "MODxGreen" in version 1.0.0

"MODxRE" first appeared in Evolution 1.0.12, so in reality "MODxCarbon" is the long standing default theme.

I don't know who changed the code to use MODxRE as default, but every install I do, whether for myself or others I have to change it every time - its a pain, but something that can be lived with.

**Comment by pmfx** [comment]
@modxuser MODxRE is just better and easier to read. Carbon wont be developed AFAIK and it will be left behind so you should stick with MODxRE on your sites until completely new Bootstrap theme comes next year.

**Comment by modxuser** [comment]
@pmfx
Have you actually put out a questionnaire asking if people want to use MODxRE or stay with MODxCarbon ?

I don't think so - why don't you ask others before taking such major decisions ?

**Comment by pmfx** [comment]
@modxuser I am not in position of taking any decisions that is why I said "AFAIK". Just passing what I know is coming for Evo and what I observed during last months/years. But seriously, what holding you with MODxCarbon?

**Comment by Fr3ddy7** [comment]
nothing has been decided, it was an idea, a proposal. Since this topic is already done a lot of edits that are not in the old topic. (And it looks much better, the basis has been taken RevoStyle v1)
