### ISSUE TITLE
1.1.1 beta3 and YAMS

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#728]
I have a site just updated to 1.1.1 beta3 but YAMS isn't working on it.
Not sure its an issue with YAMS or 1.1.1 or just this YAMS site and others do work..
I get Page not found for the not default lang. 
After seeing that error I updated YAMS to the latest version (deesen).
No [*content*] visible and page not found for other languages.

Have to revert the site again (1.0.15).

---

Making a duplicate of the original old version on a subdomain right now, updated YAMS and that all works.

Going to update now to stable 1.1. and going to look whats happens.

**Comment by fourroses666** [comment]
Oke, it seems the YAMS site update works when updating from 1.0.15 to 1.1.

So I think 1.1.1 beta3 has some issues with YAMS sites.

**Comment by fourroses666** [comment]
- Confirmed the update to the beta3 version doesn't work with YAMS. The not default language pages are blank. Also see this image:
![schermafbeelding-2016-09-03-om-13 11 12](https://cloud.githubusercontent.com/assets/523389/18224513/42a8687a-71d8-11e6-9539-62ca163f4587.jpg)



- Also noticed the install folder is not deleted while it worked on other versions.

**Comment by Deesen** [comment]
Sent you an email, seems file-upload of MODX and/or YAMS were incomplete. On my test-installation everything works fine with latest MODX and latest YAMS.

**Comment by fourroses666** [comment]
I probably didn't update YAMS or Evo correct because after reuploading it now works indeed.. Sorry for that.

The missing icons have to do with my own styled Theme.
Will be a fix for later or hopefully the bootstrap version will come soon after the update.
