### ISSUE TITLE
1.1.1 beta3

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#730]
- It didn't delete my install folder while that always works on this host. (think it did on a other site I've updated so not sure why it didn't delete it)
- when using Manage Files in the manager and check my CSS then no colors with the new codemirror, also when hit save I get a popup.

![uhh](https://cloud.githubusercontent.com/assets/523389/18233498/87d67da8-72e9-11e6-85e2-315d104510b7.jpg)

**Comment by Deesen** [comment]
Are you sure CSS-highlighting always worked? Or is a `<style>`-tag nessecary to trigger highlighting? When I add this tag, highlighting works.

Reg. deleting "install"-folder AFAIK nothing has changed in code.

**Comment by Deesen** [comment]
Codemirror in Filemanager should now respect file-extensions, so modes like "css" will be triggered by file-extensions like "styles.css".

**Comment by fourroses666** [comment]
If I have this install folder issue again on an other site I will reopen this issue.
Thanks for the Codemirror fix. Need to check. (It worked on chunks and templates but not on in filemanager.)
