### ISSUE TITLE
evogallery

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#732]
1.1.1beta3 + last evogallery 

in system events, + 5-6 items every reload page

```
$modx->fetchRow() is deprecated function
Snippet - EvoGallery
/home/port/public_html/site1/assets/snippets/evogallery/classes/gallery.class.inc.php(line:230) 
```
![modx4](https://cloud.githubusercontent.com/assets/8958344/18238018/15b80eaa-7341-11e6-9a0c-e7def7e74a06.jpg)
![modx](https://cloud.githubusercontent.com/assets/8958344/18238019/15d08a34-7341-11e6-89fd-b871373afbe3.jpg)

**Comment by Deesen** [comment]
Maybe you want to check? https://github.com/Deesen/EvoGallery

**Comment by Fr3ddy7** [comment]
very very very thank you :)
