### ISSUE TITLE
hide TopMenu

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#738]
hide top menu, anyone any ideas? button is in the template D3X
- need to cut down shift when clicking pictures, well, hide icons change (tree menu)

![screenshot_1](https://cloud.githubusercontent.com/assets/8958344/18316516/9976b7d0-7523-11e6-9b7d-2e0dfa7d192a.png)

**Comment by Nicola1971** [comment]
check 1.php and menu.php frames

https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/media/style/D3X/frames/menu.php#L101

https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/media/style/D3X/frames/1.php#L49

https://github.com/dmi3yy/modx.evo.custom/blob/master/manager/media/style/D3X/images/icons/application_get.png

**Comment by Nicola1971** [comment]
try this one (just done with photoshop)
![application_top_expand](https://cloud.githubusercontent.com/assets/7342798/18318685/f1d977d8-7522-11e6-9c3a-98a0969fb274.png)

**Comment by Nicola1971** [comment]
or without arrow
![application_normal](https://cloud.githubusercontent.com/assets/7342798/18318787/517f7228-7523-11e6-8f40-c665ff3fe496.png)

**Comment by Fr3ddy7** [comment]
second best, we must now think about how to change the icons on activity better
