### ISSUE TITLE
Fo developers: Remove .gitignore from repository

### ISSUE THREAD

**Issue by Ronef** [modxcms/evolution#741]
I think it's more usefull when everyone can have their own settings.

_Please react with +1 or -1 below ↓._

**Comment by fourroses666** [comment]
+1
I always remove the file.

**Comment by Deesen** [comment]
For developers it is good to have it.. so if removing, I propose to only remove it in final releases, not in dev.

**Comment by Fr3ddy7** [comment]
@Ronef  https://github.com/DivanDesign/MODXEvo.plugin.ManagerManager.mm_moveFieldsToTab/issues/1

**Comment by Tornek** [comment]
+1

**Comment by Ronef** [comment]
@Fr3ddy7 :D Thank you for notification, but if you want resolve the issue faster, you can create a pull request ;-)

**Comment by nick0** [comment]
+1, I always remove manually

**Comment by fourroses666** [comment]
On second thoughts, I don't have any issues with it being there, don't care much.
Even thinking about using Github private reporsitorys.
