### ISSUE TITLE
FirstChildRedirect for resources

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#756]
I would like to have the possibility (also for clients) to choose a resource to redirect to the First child of the folder.

Postion to do it could be where we choose to make a 'Weblink' and add 'Redirect to first child'.

_Somewhere between the Evo issues this question was posted but can't find it._

**Comment by Deesen** [comment]
Which purpose does it have? In which situations would you like to use it?

**Comment by fourroses666** [comment]
I use it allot, for example, when I have a newspage and don't need the overview page, I need to add [[FirstChildRedirect]] to automaticly foreward to the first child.
To change this ID in the Weblink every time there is a new news item is being forgotten allot.

Don't you use it allot?

**Comment by nick0** [comment]
I dont know if this is really needed as a core modification. Best to keep things streamlined.
I use the FirstChildRedirect snippet alot too.
But it is easy to create a "category" template with [[FirstChildRedirect]] in the content for these instances and it works flawlessly. If the client chooses the right template, it will always redirect. 
Or add a TV to the template that handles the [[FirstChildRedirect]] so the client can manually choose.
Just my 5 cents

**Comment by fourroses666** [comment]
I just think it would be easier to just select the "First Child Redirect" and not have to use a new template or custom TV for it.
