### ISSUE TITLE
Move field "publicate" to first tab?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#757]
I have a default mm_rule where I move the publish checkbox to the first tab.

Most of the time you (and clients) don't need the second tab. 
The only reason would be to publish the resource.
Maybe we can vote to move it to the frst tab by default?

`mm_moveFieldsToTab('published','general');`

**Comment by Nicola1971** [comment]
+1 for me

**Comment by bossloper** [comment]
+1 I always have that in my mm_rules too.

**Comment by pmfx** [comment]
OK with me.

**Comment by pmfx** [comment]
Can go under "Show in menu".

**Comment by nick0** [comment]
I disagree. -1 for me.

I create a publishing tab in mm rules and move the Publish Checkbox, the Publish Date and the Un-publish date to its own tab. I think these 3 are too related to be separated and would clutter the General tab.

**Comment by janniconl** [comment]
-1 for me, I agree with nick0

**Comment by fourroses666** [comment]
I really think the publish checkbox belongs on the first tab. I use publish checkbox almost every time while publishdate fields I only used it on 1 site of all my 200+ evo sites.

**Comment by pmfx** [comment]
Still +1 from me. In most cases "Published" fits better in first tab as it is a basic option commonly used and will save us that one or two unnecessary clicks. Publish & Unpublish dates are extended settings, therefore should stay in "Settings" tab. It can be always moved from General tab by MM rule.

**Comment by nick0** [comment]
The problem is that sometimes you have to clear the date in the Publish Date field and also unclick the Public checkbox, so then you have to go to 2 different tabs with multiple clicks for your proposal anyway.

Cant you move that with mm anyway, rather than more mods to the core?

**Comment by bossloper** [comment]
@nick0  - I see your point. Irrespective of if the checkbox is left where it is or not it raises the question; Should the publish checkbox auto clear the publish date when unchecked, and clear the unpublished date when checked?

**Comment by pmfx** [comment]
I think it should work the same way as it do right now. I would only add an alert to inform user about it when dates are set.

**Comment by bossloper** [comment]
Or could it auto clear the date if the date is in the past?

**Comment by nick0** [comment]
Good questions @bossloper.
I think it should probably work the same way as it does now. The future-publishing / un-publishing works really great right now.

**Comment by Deesen** [comment]
With new template-engine you could move the publish-checkbox to first tab/section. It would only need some call like

    $tpe->moveElement(
      'mutate.documentPane.tabSettings.section1.publishedcheck', // Element to move
      'mutate.documentPane.tabGeneral.section1' // Target-Element
    );

**Comment by fourroses666** [comment]
Closing this issue, can be fixed by the new template engine. Hope to have it default.
