### ISSUE TITLE
TinyMCE 3.5.11 doesn't load on MODx 1.1 for specific templates - PHx Conflict?

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#758]
After upgrading I'm unable to use TinyMCE with most of my templates.  Additionally, I cannot save resources that use these templates.  Could this be conflict with PHx or another snippet or perhaps template variables that are assigned to the template?

I've ripped out all of the code in the template but kept my TVs and as soon as I change the template to the new empty one TinyMCE goes away.

**Comment by Deesen** [comment]
Sounds like a javascript-issue caused by some plugin or TV. Does browser-console show any error-message?

**Comment by Tourist4Life** [comment]
I'm seeing the following errors from Firebug:  https://cl.ly/1H0p3A2S401Q and Chrome:  https://cl.ly/1X360F342S02.  
![screen shot 2016-09-21 at 11 48 14 am](https://cloud.githubusercontent.com/assets/22347489/18718423/70dc4a64-7ff1-11e6-8b96-87b06f7cd909.png)
![screen shot 2016-09-21 at 11 48 47 am](https://cloud.githubusercontent.com/assets/22347489/18718422/70dc3c0e-7ff1-11e6-8627-ad98dabcc210.png)

**Comment by Deesen** [comment]
It seems for me you need to turn on displaying PHP-errors, so you can see "edit resource"-page some error-message.

The seconds tab is missing, I see only tab "General", which is a sign that some errors happened while rendering a TV. So the TV missing at the end of the list could be the one responsible for the errors.

**Comment by Tourist4Life** [comment]
Thx Deesen.  I've found the conflict!  It appears that the "Quill" snippet was missing.  I'm not what happened during the upgrade process to 1.1 but it appears that assets/snippets/quill was deleted?  

I chose MERGE on my FTP upgrade to MODx 1.1 and I believe that there are other custom snippets that were preserved.

....at any rate I found what I just uploaded is the most recent version of Quill for Evolution which is Quill 1.0.7-pl as seen [here](http://modx.com/extras/package/quill) and it appears to have fixed the issue?!

**Comment by Deesen** [comment]
This is strange and should not happen indeed but I guess deletion of assets/snippets/quill happened by your FTP-program. If you have access to apache logs maybe you can search for "quill" to see when and how it got altered/deleted. So your problem is already solved?

**Comment by Tourist4Life** [comment]
Yes the issue with saving resources and TinyMCE is now solved!  I downloaded logs for the domain but don't see any reference to "quill".  Now I'm off to fight this error post MODx 1.1 upgrade:

http://banffrealestate.com/news/news-search?query=test

... I will take that to another thread.

**Comment by Deesen** [comment]
Ok, then please also post the full error-message to be seen when logged-in as admin.
