### ISSUE TITLE
MODx Parse Errors after Evo 1.1 Upgrade

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#759]
I'm getting the following error when logged in via Manager and viewing this [page](http://banffrealestate.com/news/news-category?cat=real_estate):

Error : mysql_real_escape_string(): Access denied for user 'prajwalm'@'localhost' (using password: NO)

As seen below when logged in via Manager post 1.1 upgrade.

![screen shot 2016-09-21 at 3 21 31 pm](https://cloud.githubusercontent.com/assets/22347489/18725702/544162ea-800f-11e6-9930-3500d83695d4.png)

...full BackTrace info here:

![screen shot 2016-09-21 at 2 03 55 pm](https://cloud.githubusercontent.com/assets/22347489/18722865/4ac4be98-8004-11e6-8a90-f6e09ca59688.png)

This error is from a Blog page which uses the snippet blog_get_search_ditto and Ditto as seen below
`<?php
$blog_query = mysql_real_escape_string($_GET['query']);	
$modx->setPlaceholder('blog_query',$blog_query);

$id = $modx->documentIdentifier;

// Ditto parameters
$params['parents'] = '91';
$params['extenders'] = 'summary,search';
$params['tpl'] = 'blog_listing_tpl';
$params['orderBy'] = 'pub_date DESC';
$params['dateSource'] = 'pub_date';
$params['display'] = '5';
$params['truncText'] = 'Read More...';
$params['dateFormat'] = '%m/%d/%y';

$params['searchFields'] = 'content,pagetitle';
$params['searchString'] = $blog_query;
$params['searchOptions'] = '';

$params['paginate'] = '1';
$params['tplPaginatePage'] = '@CODE: <li><a href="[+url+]">[+page+]</a></li>';
$params['tplPaginateCurrentPage'] = '@CODE: <li class="current_menu_item"><a>[+page+]</a></li>';

	
$output = $modx->runSnippet('Ditto', $params);
return "$output";
?>`

**Comment by Deesen** [comment]
You could try replacing

`$blog_query = mysql_real_escape_string($_GET['query']); `

by

`$blog_query = mysqli_real_escape_string($modx->db->conn, $_GET['query']); `

**Comment by Deesen** [comment]
BTW you made your server-path public in your screenshot. I would remove the path and reupload image (everything before /manager/).

**Comment by Tourist4Life** [comment]
WOW!  Deesen that is pure magic!  Success!

A thousands times "thank you".  Issue resolved.

**Comment by Tourist4Life** [comment]
Just realized there are two other snippets that are part of the Blog functioning properly that are also not working.  The first is blog_get_cat_ditto as seen here:

`<?php
$cats_str = $modx->db->getValue($modx->db->select("elements", $modx->getFullTableName('site_tmplvars'), "id=23"));
     
$cats_arr = explode('||', $cats_str);

$cats_dict = array();

foreach($cats_arr as $e){
	$ee = explode('==', $e);
	$cats_dict[$ee[1]] = $ee[0];
}

$blog_cat = mysql_real_escape_string($_GET['cat']);	
$modx->setPlaceholder('blog_cat',$cats_dict[$blog_cat]);


$id = $modx->documentIdentifier;

// Ditto parameters
$params['parents'] = '91';
$params['extenders'] = 'summary';
$params['tpl'] = 'blog_listing_tpl';
$params['orderBy'] = 'pub_date ASC';
$params['dateSource'] = 'pub_date';
$params['display'] = '5';
$params['truncText'] = 'Read More...';
$params['truncLen'] = '100';
$params['dateFormat'] = '%m/%d/%y';

$params['filter'] = 'blog_category,'.$blog_cat.',1';

$params['paginate'] = '1';
$params['tplPaginatePage'] = '@CODE: <li><a href="[+url+]">[+page+]</a></li>';
$params['tplPaginateCurrentPage'] = '@CODE: <li class="current_menu_item"><a>[+page+]</a></li>';


$output = $modx->runSnippet('Ditto', $params);
return "$output";
?>`

and blog_get_cat_list as seen here:

`<?php
$cats_str = $modx->db->getValue($modx->db->select("elements", $modx->getFullTableName('site_tmplvars'), "id=23"));
     
$cats_arr = explode('||', $cats_str);

$cats_dict = array();

foreach($cats_arr as $e){
	$ee = explode('==', $e);
	$cats_dict[$ee[1]] = $ee[0];
}

$cat_page_url = $modx->makeUrl(93);

$chld = $modx->getAllChildren(91);

$chld_vars = $modx->getDocumentChildrenTVars(91, array('blog_category'));

$used_cats = array();

foreach($chld_vars as $c){
	//var_dump($c);
	$used_cats[$c[0]['value']] = 1; 
}

foreach($used_cats as $e => $dummy){
	echo '<li><a href="'.$cat_page_url.'?cat='.$e.'">'.strtoupper($cats_dict[$e]).'</a></li>';
}
?>`

....is there a simple fix for these as well?

**Comment by Tourist4Life** [comment]
and the final is and blog_get_cat_list as seen here:

`<?php
$cats_str = $modx->db->getValue($modx->db->select("elements", $modx->getFullTableName('site_tmplvars'), "id=23"));
     
$cats_arr = explode('||', $cats_str);

$cats_dict = array();

foreach($cats_arr as $e){
	$ee = explode('==', $e);
	$cats_dict[$ee[1]] = $ee[0];
}

$cat_page_url = $modx->makeUrl(93);

$chld = $modx->getAllChildren(91);

$chld_vars = $modx->getDocumentChildrenTVars(91, array('blog_category'));

$used_cats = array();

foreach($chld_vars as $c){
	//var_dump($c);
	$used_cats[$c[0]['value']] = 1; 
}

foreach($used_cats as $e => $dummy){
	echo '<li><a href="'.$cat_page_url.'?cat='.$e.'">'.strtoupper($cats_dict[$e]).'</a></li>';
}
?>`

**Comment by Deesen** [comment]
In first snippet maybe replace

`$blog_cat = mysql_real_escape_string($_GET['cat']); `

by

`$blog_cat = mysqli_real_escape_string($modx->db->conn, $_GET['cat']);`

**Comment by Tourist4Life** [comment]
BOOM! That did it. Thank you Deesen!
