### ISSUE TITLE
question: was an outer wrapper ever developed for Ditto?

### ISSUE THREAD

**Issue by nick0** [modxcms/evolution#762]
Hello,

Just a question...

Was an outer wrapper ever developed for Ditto? And was this ever built into the Ditto of this Evo currently being developed?

I think the outer wrapper is the one thing missing from Ditto, so that empty results return empty output without relying on phx that sometimes works and that sometimes doesnt work in that instance.

**Comment by Deesen** [comment]
Maybe `noResults` with a blank space will help you?

    [[Ditto?&noResults=` `]]

**Comment by fourroses666** [comment]
Yup thats what I alwas use too

**Comment by nick0** [comment]
Howdy,

Not really @Deesen because any html used outside of the ditto call (eg what would normally go in an outer wrapper like in WayFinder or MultiTV, both of which handle empty results really well) like an opening and closing div and /or ul etc is still output with empty results.

Eg consider this example where you want the ditto items in a list...
```
<div>
 <ul>
  ditto call including noresults=``
 </ul>
</div>
```
you are still going to get that outer content included, just that the ditto content in between is empty...
```
<div>
 <ul>

 </ul>
</div>
```
That is what happens for me anyway. That is not ideal.

That's why I think outer wrapper capability is missing in Ditto,

**Comment by Deesen** [comment]
Looking at the snippets-code I see at the end a parameter called "outerTpl". So in your above case it would look like

    <div>
      <ul>
        [+wrapper+]
      </ul>
    </div>

**Comment by nick0** [comment]
Wowwwwwww, that is awesome to know. Thanks so much for finding that out for me @Deesen, I had no idea about it.

And thank you to @dmi3yy and @Jako for building this into the snippet.

It works perfectly for me in Evo 1.0.15 with Ditto 2.1.1. Just awesome

This is my ditto call if anyone is interested:
`[[Ditto? &id=`test[*id*]` &startID=`[*id*]` &depth=`0` &outerTpl=`menu-wrapper` &tpl=`menu-row` &noResults=` ` &orderBy=`menuindex ASC`]]`

The &noResults=` ` seems to be needed when using the outer wrapper to produce empty output when no items exist.

Love it.

Thanks again.

**Comment by pmfx** [comment]
Didn't know about it either. Cool. Thanks @Deesen !

**Comment by nick0** [comment]
Give it a go @pmfx , it works great!

I think there are a number of really great improvements / mods that we might not know about. So much work has been done here by such clever developers, the progress is awesome.
