### ISSUE TITLE
MODx Parse Error after Evo 1.1 Upgrade

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#768]
I've got another custom snippet that seems to be breaking after my 1.1 upgrade.  Here is the error message

![image](https://cloud.githubusercontent.com/assets/22347489/18924510/77978a70-857e-11e6-8198-676ed762405c.png)
![image](https://cloud.githubusercontent.com/assets/22347489/18924545/8e6af142-857e-11e6-84f9-365954f0aac2.png)

and the custom PHP code in the snippet

`<?php
$features = $modx->getTemplateVar('GetProperties','',1);
$features = $features['value'];

$features_arr = explode("||",$features);

//$ids = rtrim(join(',',$features_arr),",");
$ids = rtrim(join(',',preg_replace('/\D/', '',$features_arr)),",");

$query = "SELECT * FROM mls_listings where MLSNumber IN($ids) ORDER BY ListPrice DESC";
//$query = "SELECT * FROM `mls_listings` WHERE REPLACE(MLSNumber, 'OM', '') IN ($ids) ORDER BY `ListPrice` DESC";
$result = mysql_query($query);

if (!$result){
 if ($onHome)
 echo '';
 return;

}

$numb = 0;
while ($row = mysql_fetch_assoc($result)){
     $numb ++; 
      if ($onHome && $numb>3) break;
      $price = (int)$row['ListPrice'];
      $price_str =  '';
      $i=0;
      while ((int)$price){
         if ((int) $price && $i % 3 == 0 && $i) $price_str = ','.  $price_str;
         $i++;
         $price_str = ($price % 10) .  $price_str;
         $price /=10;
       }     
       
       $query2 = "SELECT * FROM mls_listings_images where UniqueIdent = '{$row["UniqueIdent"]}' ORDER BY ImageNo LIMIT 1";
       $result2 = mysql_query($query2);
       $row2 = mysql_fetch_assoc($result2);

       $src = $row2['LocalLocation'];
	$src = str_replace ('/****/****/public_html/soriahkanji.com/' , '' , $src);
     

      $params['HouseNo']=$row['HouseNo'];
      $params['StreetName']=$row['StreetName'];
      $params['StreetType']=$row['StreetType'];
      $params['ListPrice']= $price_str;
      $params['TotalBedroom']=$row['TotalBedroom'];
      $params['TotalBaths']=$row['TotalBaths'];
      $params['PostalCode']=$row['PostalCode'];
      $params['City']=$row['City'];
      $params['ListingID']=$row['ListingID'];
 	$params['MLSNumber']=$row['MLSNumber'];
      $params['PublicRemarks']=$row['C_Remarks'];
      $params['image_src']=$src;
//      $params['']=$row[''];
//     $params['']=$row[''];
//      $params['']=$row[''];
     $output.=$modx->parseChunk('FeaturedPropertiesTpl', $params, '[+', '+]');
}
echo $output;
?>`

**Comment by Deesen** [comment]
Maybe try replacing

`mysql_query(` with `$modx->db->query(`

`mysql_fetch_assoc(` with `$modx->db->getRow(`

**Comment by Tourist4Life** [comment]
Thanks Deesen!  That helped!  The snippet runs now but I can't get the image path out of the DB.  So this line
`$params['image_src']=$src;`
returns nothing.

**Comment by Tourist4Life** [comment]
Fixed it!  

My error was in this line:

`  $query2 = "SELECT * FROM mls_listings_images where UniqueIdent = '{$row["UniqueIdent"]}'`

changing it to 

` $query2 = "SELECT * FROM mls_listings_images where UniqIdent = '{$row["SysID"]}' ORDER BY ImageNo LIMIT 1";`

did the trick.

Thanks again Deesen!  You are the Man!
