### ISSUE TITLE
Auto clear publish or unpublish date if in the past and publish checkbox updated

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#771]
Just pulling this separate to #757 

Should the publish date be cleared automatically if it is in the past and the publish date checkbox is changed? The scenario being for example:
- publish date is set on a resource
- time passes and the resource is then automatically published
- manager wants to unpublish the resource again so edits resource and unchecks the publish box.
- because the publish date is still populated the resource will republish when saved UNLESS the publish date is also cleared.

My point being if the manager edits a resource where the auto publish date has passed then if they specifically uncheck the publish box the publish date should be automatically cleared so the unpublish is honoured. 
Applicable also for unpublish date being in the past and checking the publish checkbox.

**Comment by nick0** [comment]
I think this is a really good idea @bossloper.

There is definitely some double handling at times with the publish checkbox and clearing the auto published date, so this could mitigate that,

(the auto publish date is obviously needed to get around that silly January 1, 1970 date that still shows in ditto and presumably other snippet results from time to time. I don't know why the 1970 date appears, MODx wasn't around quite then :) - at least something in the 2000's would be good as a default :) its wierd that the published date (even if the checkbox was manually checked) sometimes shows the 1970 date and not the actual first publish / save date by default)

**Comment by Deesen** [comment]
1970 appears because of [unix-time](https://en.wikipedia.org/wiki/Unix_time). Simply if a date-field has value 0, in "unix-time" this is 1.1.1970.

How about a simple javascript-confirmation window when ticking/unticking the checkbox with a text for example like "This action will clear the publish-date (24-10-2016 14:35:00) because it is in the past. Do you want to continue?"

**Comment by nick0** [comment]
Ah I see. Thanks for clarifying.

That sounds a good idea.

Could we also have something that appears on saving when no date is present in the date field... something that replaces the 0 Unix date with the date at last save so we don't get the 1970 date ever. Would that be feasible?

**Comment by bossloper** [comment]
RE: How about a simple javascript-confirmation
Logically, does it even need a confirmation?
