### ISSUE TITLE
Bundle Categorized TV tabs and Categories Manager extras with MODX setup

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#775]
I think it would be good to have an old plugin made by stefan in 2010 bundled with MODX setup. Here is a link to the plugin **"tv_categorized_tabs"** on MODX extras http://modx.com/extras/package/tvcategorizedtabs The thing is, that it is a pretty old plugin and I had to modify it to work with multiTV but in my opinion it is a must have in almost every project. 

How it works. For example I have TVs categorized nicely like this on Elements list:

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/18997289/fc73ea16-8733-11e6-95f9-d039ecf43029.png)

and while editing page witm template with TVs it puts TVs into tabs named after categories they are in. 

![screenshot_2](https://cloud.githubusercontent.com/assets/10888055/18997294/0122b678-8734-11e6-9bce-f6b987eb3d8f.png)

Since I found this plugin I **don't have to use ManagerManager mm_createTab() + mm_moveFieldsToTab()**. It works just better and is similar to behavior Revolution.

Stefan made another great extra called **"MODx_Categories_Manager"** to update categories easily and even to give categories a rank so we could order Tabs on Resource Edit page anyway we want. It is here module https://modx.com/extras/package/modxcategoriesmanager 

![screenshot_3](https://cloud.githubusercontent.com/assets/10888055/18997379/648dc2a2-8734-11e6-9223-070d37bf9691.png)

I have both Plugin and Module working perfectly with the latest beta 1.1.1-beta3 (although I had to fix it to work with multitv) and if you ask me this Plugin and Module should be bundled with MODX by default or should be reproduced into core (written from scratch) as these are extremely useful yet not many people knows about it.

Fastest and easiest way is to bundle it with MODX setup and make it better on git while it is still work with current Evo. I can provide Plugin code working fine with multiTV.

**Comment by dmi3yy** [comment]
not good like revo, better global tab  
--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 30 сентября 2016 г. в 18:38, Piotr Matysiak написал:

**Comment by Nicola1971** [comment]
Never user categorized tv tabs, I'm an addicted to manager manager, but I will test soon.
For sure,  Evo missing a tool to manage categories : +1 for me

**Comment by pmfx** [comment]
@Nicola1971 If you want to test it here is my version that works fine with MultiTV https://app.box.com/s/hj05g6tqpe1tfybi98r0uxds418m68jg

@dmi3yy Thats a matter of personal preferences. I think it should be available for users as a bundled plugin (link above) or new code & system settings. If plugin not much work. This way we give users a choice and functionality of it is great IMHO.

**Comment by nick0** [comment]
sounds interesting.
I too like @Nicola1971 also love using ManagerManager but think this is a little different. Could be nice for organising the TVs.
As long as it works with MultiTV.
Great work @pmfx

**Comment by fourroses666** [comment]
I'm +1 on this one. Can be very very usefull. Nice way to compact all these TV's in an tab.

**Comment by pmfx** [comment]
I am closing this issue for now. If anyone want to use this plugin I have created public repo here https://github.com/pmfx/CategorizedTabs It is now compatible with MODX install script. 

Later, I will try to do same thing for "Categories Manager" module.

If all will work fine, I will bring this subject (include it or not in install as optional plugin/module) back .

**Comment by pmfx** [comment]
Gentlemen! I have successfully converted "**Categories Manager**" to work with MODX install script and created a repository to keep this amazing module alive. Tested and working. 

Please check it out and let me know if you want me to **add it to MODX install**.

https://github.com/pmfx/CategoriesManager

**Comment by bossloper** [comment]
... and ladies ;-)

**Comment by pmfx** [comment]
Pardon me - and Ladies ;-)

**Comment by fourroses666** [comment]
Hmm, will look pritty weird on all sites I will update. (I use MM allot.)

But as checkbox option on install and upgrade this is great.  _(On default not checked)_

Will need to get used of it but its a nice feature. 👍

**Comment by Deesen** [comment]
What about adding the "Categories Manager" to MainMenu -> Elements like "Manage Elements, Manage Files, Manage Categories" ?

**Comment by pmfx** [comment]
@fourroses666 [CategorizedTabs](https://github.com/pmfx/CategorizedTabs) is a plugin (obviously haha) so it can be turned on and off at any moment after installation - no conflicts if existing setup. And I think it would be good for new users (and power too) to have nicely organized TVs by default. But should it be there by default - thats still need to be discussed. I use this plugin almost in all my MODX projects.

But right now, I think we should have this [Categories Manager](https://github.com/pmfx/CategoriesManager) module included in MODX install., as we need a tool to easy manage categories by default.

@Deesen Having it under Manage Elements menu tab makes sense, but it would require new permission added to the system. And maybe merging with "manager" folder?

**Comment by Nicola1971** [comment]
+ 1 for CategoryManager inside elements menu and evo install. Always missed this feature in evo.

-1 for CategorizedTabs inside install, sorry.
 It's a nice plugin and simpler than managermanager, but with Mm you can do much more things and using both plugins seems too much for me: If you are accustomed to using  ManagerManager and you have a a lot of tabs in resource edit, "tabs inside tabs" does look very weird.

**Comment by fourroses666** [comment]
Lets do it under Elements !

**Comment by pmfx** [comment]
OK but how? Where do we start? Module is ready to go and it only needs to be added to install base. If we want it to be under Elements then how much additional work there is? And will it delay 1.2 release?

**Comment by Deesen** [comment]
I think a new permission like `hasPermission('category_manager')` will do. Not sure how complicated implementing it will become, need to start and see.

**Comment by fourroses666** [comment]
Rethinking of it, when its under Elements we can't choose to set it on/off can we? Don't know about any 'timestamps' for evo 1.2.

**Comment by Deesen** [comment]
With a new permission (by default only "on" for Administrators) you can turn it on/off.

**Comment by pmfx** [comment]
Maybe I will add it to install base as a optional module, and we can remove it when we have it ready and working under "Elements" tab. What do you think?

**Comment by Deesen** [comment]
Its finished :-) ..

**Comment by pmfx** [comment]
You're crazy! :D Great work Deesen.

**Comment by fourroses666** [comment]
:-))

**Comment by dmi3yy** [comment]
about timestams

now we can publish   1.2-RC1   

need for this:
- changelog  
- fix https://github.com/modxcms/evolution/issues/824


then  1-2 week for testing and publish 1.2)  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 21 октября 2016 г. в 11:23, Deesen написал:

**Comment by pmfx** [comment]
#824 is closed (4 days ago) and supposedly fixed (right?).

**Comment by pmfx** [comment]
@dmi3yy and we have some nice pull request waiting to be merged :) Like updated install theme and categories manager built into the core.

**Comment by pmfx** [comment]
@dmi3yy maybe you can use this as a part of changelog/main improvements list? I'm sure I have missed a lot of changes done inside MODX core itself so feel free to modify/update it:

- New clean default Manager theme.
- New theme for installation process.
- New and dynamic welcome dashboard with drag and drop widgets.
- New demo site buit with Bootstrap 3.
- Manager is now using FontAwesome for most icons.
- Improved workflow inside manager with ElementsInTree plugin.
- Search form is now always accessible in top frame.
- Quick and easy Elements searching with live filtering.
- Powerful categories management with built in Categories Manager.
- Easy access to sort menuindex option in tree context menu.
- Updated TinyMCE to version 4.

Note: some fixes + categories management + new installation process theme are waiting in pull requests.
