### ISSUE TITLE
doube bootstrap file its no good

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#778]
http://take.ms/5hlTO

**Comment by pmfx** [comment]
First one is Javascript inside "media/script" folder.
Second is CSS inside "media/style" folder.
So it make sense to me. No double/cloned files there.

**Comment by Deesen** [comment]
Maybe move all BS-related files to assets/lib/bootstrap3 ?

**Comment by pmfx** [comment]
@Deesen Yeah, agree.

**Comment by Fr3ddy7** [comment]
and use in demo template 8)

**Comment by Nicola1971** [comment]
It' s not a good idea for security reasons, use bootstrap from a manager path in demo template

**Comment by Deesen** [comment]
But "assets/lib/bootstrap3" is no manager-path?

**Comment by Nicola1971** [comment]
> But "assets/lib/bootstrap3" is no manager-path?
ops, sorry.
Ok for me

**Comment by fourroses666** [comment]
assets/lib/bootstrap3    👍
