### ISSUE TITLE
where all setting for widgets on Dashboard? 

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#779]
http://take.ms/ped7E
it no good 

i want fast assets for fix it  or hide for userS%)

**Comment by Nicola1971** [comment]
Sorry @dmi3yy don't understand the issue

**Comment by Nicola1971** [comment]
tryng to uderstand, do you mean setting to change panel position by default ? (not drag and drop / localstorage)

**Comment by dmi3yy** [comment]
yes )

**Comment by Nicola1971** [comment]
we need four parameters for widget, like my widgets plugins config
![yyajocufjh9aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19393863/e1b60822-9236-11e6-81aa-949005bdd133.png)

a better solution: in addition to the localstorage feature, add an option to save json to db
![1ltnqsiecaaaecbgzmqficsqfudgkqiecaaaecgqfhmaollgabagqiecawywlvyfenpzkrwzfwqw4aaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19394117/014ecfec-9238-11e6-990c-390a6ef2b190.png)

**Comment by Deesen** [comment]
Save JSON to DB is no problem using manager-API `getLastUserSetting($key)` and `saveLastUserSetting($settings, $val='')`: https://github.com/modxcms/evolution/blob/develop/manager/includes/extenders/manager.api.class.inc.php#L215-L249

**Comment by Nicola1971** [comment]
Thanks @Deesen, i will try for next versions.

@dmi3yy 
Actually, to solve this issue and allow more Dashboard customizations, I decided to keep alive my EvoDashboard Plugin as a Dashboard Manager and started a new version for Evo 1.2

Features:
* Show/Hide Dashboard Header: restore the deprecated modx logo with sitename header
* Allow custom header logo 
* Set the default Show/Hide for Widgets 
* Set the default Position and Size for Widgets
* Show/Hide User Info in Welcome widgets

![weqjw2u9pam1aaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19628925/a6c29dd6-9969-11e6-9e6e-bac52d3faf24.png)

**Comment by Nicola1971** [comment]
For me should works nice for evo 1.2

- No plugin or deactivated : just dashboard , support for external widgets, default evo widget layout and local storage for user settings

- with plugin: all the default features  + custom default layout settings (show hide widgets and custom position)... and more:

We can add more "optional" features with plugin: 
- delete widget button, 
- full screen (frame) button (tested, but actually bugged), 
- button to save more local storage layout settings (layout 1, layout. 2, layout3...)

**Comment by pmfx** [comment]
I don't see a need to have settings for Dashboard either. No need to have complicated setting for it in site configuration. Keep it simple.

**Comment by Nicola1971** [comment]
for me, we just need options to:

1) Hide unwated widgets (i always hide news and security widget to my customers)
2) Change and fix default widget position and size: localstorage works nice for a single user, but not good if you want the same layout for all users and not sure will really need add data inside user settings table just for dashboard.

All these features are now in my Plugin.

As ManagerManager or tvtabs, its just something to customize the Manager experiece, most of users will be happy just with default themes dashboard features, no need to add in System Settings for me.

The latest version works nice with evo 1.2.

 I just want to add a couple of minor settings:
- option choose plugin dashboard.css or theme dashboard.css 
- option to enable/disable plugin color.css (a set of styles to create better icons with font awesome)

![evodash31-re2](https://cloud.githubusercontent.com/assets/7342798/19762774/963f5952-9c3b-11e6-910e-662985f36de2.png)

**Comment by dmi3yy** [comment]
yes i too for this:  

1) Hide unwated widgets (i always hide news and security widget to my customers)
2) Change and fix default widget position and size: localstorage works nice for a single user, but not good if you want the same layout for all users and not sure will really need add data inside user settings table just for dashboard.
its need by default.  




--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 13:05, Nicola написал:

**Comment by Nicola1971** [comment]
> its need by default.
you mean in evo install?

Updated a bit the plugin:

* New option **ManagerOnly** in widget display selection: **Show widget Only to manager** (role 1)
* choose plugin dashboard.css or theme dashboard.css
* to enable/disable plugin color.css 

![eelbefuxqj1wsuwjqyubeiabeiabepgpabwoetcphwh4hnvapldzcfyyas5v9rrfzmpnuq3h217tgqvffteyeiabeiabeicbcccg1jh p5cmm8f0ec0haaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19779932/70f2559e-9c83-11e6-9745-f67f6617001e.png)

**Comment by Nicola1971** [comment]
maybe better call adminOnly instead managerOnly
