### ISSUE TITLE
Install now? missing head and base href

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#780]
`<p>Do you want to <a href="install/index.php">install now?</a></p>`

Missing < html/head/body > and < base > or/and add slash / here -> demo.site.com/demo/install/install/index.php 

issue with subdomains. demo/install/install/index.php

**Comment by pmfx** [comment]
@fourroses666 Tested it lately on subdomain/subdir and worked fine. Do you still have problem with it?

**Comment by fourroses666** [comment]
Need to test again. Extremely busy upcomming week :(

_Just thinking about it, don't know if it makes a difference when using .htaccess or ht.access._

**Comment by fourroses666** [comment]
I don't have any issues anymore with the installer. Don't know what was wrong but works now.

I do think the source is missing html / body;
![source](https://cloud.githubusercontent.com/assets/523389/19416181/02e3505a-938a-11e6-9530-f6cf962897d3.jpg)

I always have to choose "set names". I don't know about others but maybe this should be selected as default.
![names](https://cloud.githubusercontent.com/assets/523389/19416199/ad95a430-938a-11e6-8b78-7a6853e9b7ab.jpg)

Got missing tables message when installing with demo content.
![jot](https://cloud.githubusercontent.com/assets/523389/19416206/059c6d94-938b-11e6-8651-32c87ff1f62d.jpg)

Install folder isn't deleted while normally it does. No resources are in the tree.
![no-resources](https://cloud.githubusercontent.com/assets/523389/19416226/8821965e-938b-11e6-843b-7582554cae34.jpg)


But maybe I'm testing too soon.

**Comment by Deesen** [comment]
- I also have to always choose "set names"
- I had same "jot_content doesnt exist"-error and fixed it already
- install-dir is being removed for me, no issue here

**Comment by fourroses666** [comment]
Install folder not being deleted must be because of the jot table issue. I had no chunks and plugins installed too. 

Maybe turn these "set names" and "set characters" arround. So first names.

**Comment by Deesen** [comment]
Nobody interested in switching "set names" with "set characters" ?

**Comment by fourroses666** [comment]
I can't find a reason to not switch them. Actually don't know what is does but for newly users this can be a issue if they don't know it needs to be set to names.

**Comment by fourroses666** [comment]
Closing this
