### ISSUE TITLE
New default theme proposition - MODxRE2

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#781]
I think it would be nice to have a new default look and feel in next Evolution release. To make it look more, I don't know... serious? MODxRE theme was similiar to old Revolution and I've added some styles to MODxRE theme to make it look like new Revolution theme (it is really nice and clean) and called it MODxRE2. 

You can try it just by overwriting 2 MODxRE files:

style.css: https://gist.github.com/pmfx/63b9e3da4ccc85dcaa837e213e07ebb8
login.tpl: https://gist.github.com/pmfx/4b5406190f71e752a844f482b09ad6a2

It is fully compatible with current develop version. Just some styles overwrites starting from line 2640.

What do you think?

Screenshots:

![screenshot_0](https://cloud.githubusercontent.com/assets/10888055/19023544/ed9694ee-88f0-11e6-95de-c36e8cdd7c75.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19023561/7bd5529a-88f1-11e6-91cc-f7ba0b7fd0f8.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/10888055/19023545/ed98a284-88f0-11e6-9270-a6e78ac03d0d.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/10888055/19023547/ed9ab650-88f0-11e6-9537-3a7ec401dc9e.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/10888055/19023546/ed99ca92-88f0-11e6-9b7b-a762c9efba71.png)

**Comment by fourroses666** [comment]
I don't care allot about a new MODxRE personally, but it does looks allot better pmfx.
I'm more excited about the Bootstrap3 version! 

_I use my own custom style for all sites.
https://github.com/fourroses666/evo-custom-manager-login
https://github.com/fourroses666/evo-custom-manager-style

Another one I have build but don't use:
https://github.com/fourroses666/evo-revo-login
https://github.com/fourroses666/evo-revo-theme_

**Comment by Fr3ddy7** [comment]
looks good, but without the tabs was not very comfortable) all used to them)
can be done in the same color (as the background on the right), the color tabs to fill?

**Comment by Nicola1971** [comment]
Actually all themes uses the same classes and css selectors, so adding a new event into the top frame, we can overwrite theme styles to fit our preference, just with a plugin

https://www.youtube.com/watch?v=EJ0vXnLuPeY

https://github.com/modxcms/evolution/pull/782

**Comment by Nicola1971** [comment]
example: just editing few parameters with my plugin and custom event
![nkeezb1qahcaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19048048/ee365ef2-89a4-11e6-9446-5d62aa1714e0.png)

**Comment by pmfx** [comment]
@fourroses666 Thanks.
@Fr3ddy7 I am used to green too but I think it is good moment for some default visual upgrade.
@Nicola1971 Really like the idea of new event and modifying theme via plugin.

My point is: proposed theme is really easy to integrate (just copy MODxRE as MODxRE2 and overwrite login.tpl and style.css) and in next release users would get some fresh (more balanced) air or could change theme back to MODxRE if they want.

**Comment by Nicola1971** [comment]
> @Nicola1971 Really like the idea of new event and modifying theme via plugin

@pmfx my idea is 2 yers old, but i think that will work much better with your bootstrap manager .

i'm updating a bit this old plugin (adding some dashboard styles) i will share very soon to test.

**Comment by Fr3ddy7** [comment]
@pmfx  Your version of the background above - better. I'm not saying leave the old tabs, you can leave the color, that was accustomed to) and they simply modify the style of the new admin panel

**Comment by nick0** [comment]
its really exciting to see some work on the visual / branding of Evo

**Comment by pmfx** [comment]
Thanks @nick0 appreciate it. I've created pull request #785 to include new theme.

**Comment by Nicola1971** [comment]
tested this morning, i like it - much flatter and lighter than MODxRE.
+1 for me

**Comment by Nicola1971** [comment]
just a request

can we change the input text and text area to a larger width? (like in my MODxFlat)

from this
![swgcgk31usaaaecbagqiecaaaecbagqiecaaaecyxcyewd8c8hedeao5nxjaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19068917/c7c5eea6-8a24-11e6-9331-5437765b75bc.png)


to this
![zae7stpoiecbagaabagqiecbagaabagqiecbayowcyw afwgvnq3m8tqq1waaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19068921/ce1db8d8-8a24-11e6-85db-2c4dae8cca98.png)

https://gist.github.com/Nicola1971/b9fb39429bf67602e9d413d974d343b3#file-modxre2-style-css-L2064-L2067

**Comment by dmi3yy** [comment]
+1  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 12:25, Nicola написал:

**Comment by Nicola1971** [comment]
mixing with some MODxFlat things..

tree menu looks much better with my MODxFlat icons

![jq3imudxsgqaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19069201/25d577cc-8a26-11e6-881b-6949e369ca3b.png)

![krqaabbbbaaaeeeeaaaqqqqaabbbcitofocyz pzxgnox3wezzaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19069211/2e06bac8-8a26-11e6-92b1-a7e97024c7a2.png)

**Comment by dmi3yy** [comment]
nice  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 12:32, Nicola написал:

**Comment by pmfx** [comment]
@Nicola1971 text input width updated in PR #785 

Really like new your icons in Tree. But I dont know if outlined or solid icons are better. We have solid in tree buttons. And solid will play nice with another icon on it (white). Example: to indicate secured document or other type - white Lock icon on solid folder/file icon. 
Potential issue with stacked icons is that they are meant to be big. We need small icons and from my short tests it is hard to read small stacked FA icons...

Maybe we dont need many icons in tree. Maybe only folder and file icon with some color variations to show what resource type it is.

**Comment by Nicola1971** [comment]
note: these are not font icons , but still pngs

**Comment by pmfx** [comment]
@Nicola1971 Oh, right, cool! 😆  Hehe thought it was FA for a moment. No problem then!

Back to icons. They look good. I think you can replace old icons with your new ones in MODxRE2 once MODxRE2 will be pulled to develop.

**Comment by Nicola1971** [comment]
anyone interested to replace checkbox with toggle switches? for me looks more modern and  userfriendly 
![uncheck](https://cloud.githubusercontent.com/assets/7342798/19072245/79fd5c08-8a34-11e6-8ea7-7b9607da851a.png)

![toggle](https://cloud.githubusercontent.com/assets/7342798/19072248/7f946742-8a34-11e6-80d8-438bc8e51cd6.png)

![toggles](https://cloud.githubusercontent.com/assets/7342798/19072250/83f5ca56-8a34-11e6-8acc-fcbd2258cb1b.png)

**Comment by pmfx** [comment]
Hm, not really. I'm fine with default system checkboxes with simple markup and visuals.

**Comment by Nicola1971** [comment]
ok

i will try to do with a plugin

**Comment by Fr3ddy7** [comment]
@Nicola1971 +1 nice for me

**Comment by Fr3ddy7** [comment]
left to change the folding icons :)
and remove from a bunch of threads is no longer relevant icons

**Comment by fourroses666** [comment]
the new theme looks good guys 👍

**Comment by nick0** [comment]
The toggle switches look nice @Nicola1971. I agree it looks very modern. For some reason I think I personally prefer the simplicity of the checkboxes.

I like the tree menu icons that @Nicola1971 put up. They are very clear and look nice.

The input boxes changed to full / 100% width in General fields section look great. I think visually the select boxes (eg Uses Template) should also be at the matching width. Otherwse there is one narrow one among lots of long ones.

Great job everyone.

**Comment by Fr3ddy7** [comment]
drain all in a heap, so you can find bugs and test) icons in the tree, checkboxes, and a new admin panel

**Comment by Nicola1971** [comment]
https://github.com/modxcms/evolution/pull/792

Updated tree icons

![bvqsjgbzyagaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19149225/0fcbe80c-8bc1-11e6-9ae3-bf1ebdd5953d.png)

Updated Manage Files icons (because originally based on tree icons)
![kdaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19149237/242364c4-8bc1-11e6-8b5d-30026c460804.png)

Updated user icon, because just looks better :)
![saaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19149249/32b15a28-8bc1-11e6-8ab0-a107d7a86766.png)

![3dgrd0aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19149255/36e116f6-8bc1-11e6-9c3d-113e610516a2.png)

**Comment by pmfx** [comment]
Great work @Nicola1971 !

**Comment by fourroses666** [comment]
Becomming a nice theme. Maybe these "Manager Files" Options icons you see in the screeny above can be changed too?

**Comment by Nicola1971** [comment]
Note: in files.dynamic.php there are a lot  hardcoded icons in the code, very ugly.

Done:

before:

![gaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19150538/a6b5d48e-8bc7-11e6-82fa-9996421ad035.png)

after:
![mqatyajmgakwgzggwoirjoabjwactiajmaemwasmcwewx9nlplmftiajmaemwasyqewq b8hejv3823 kqaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19150545/b4150c4e-8bc7-11e6-9195-bcb8ba7cb797.png)

**Comment by Nicola1971** [comment]
collapse icons

![bgoaefanhhghglddugeyl38ee4cay6abrhghgjbme1i6v9kfbv5t ue0waaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19151073/f13f2192-8bca-11e6-844c-eb6762ce4009.png)

![x efhdgssufcaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19151075/f68fa2e8-8bca-11e6-8a28-bf76e19755eb.png)

**Comment by Fr3ddy7** [comment]
@Nicola1971  cool :+1:

**Comment by Nicola1971** [comment]
as said in the elementsintree issue: https://github.com/modxcms/evolution/issues/783


we should use unique icons:

fa-th-large: chunks
fa-cogs: modules
fa-plug: plugins
fa-code: snippets
fa-list-alt: tvs
fa-newspaper-o: templates

![wmaz3qv5fecfgaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19153198/c566e888-8bd5-11e6-83d6-f3920bf97557.png)

**Comment by Fr3ddy7** [comment]
need fix icon media/style/MODxRE2/images/icons/question-sign.png

its help popup icons near input fields

**Comment by Nicola1971** [comment]
@Fr3ddy7 
https://github.com/modxcms/evolution/pull/795

![fbv2qaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19153648/b1c5b9b0-8bd7-11e6-911c-18a81e97e5e1.png)

**Comment by pmfx** [comment]
@Nicola1971 good spotting. I have updated ElementsInTree. Great job with all other icons.

**Comment by Deesen** [comment]
BTW I´m loving that new theme! Great work @all!

**Comment by Nicola1971** [comment]
most icons are replaced 

![wb3zqaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19156164/4308cdc8-8be1-11e6-9e85-d742c85bf0af.png)

![wc8s9rfsguzrqaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19156167/459e8e42-8be1-11e6-86dc-0bd34aecc292.png)

**Comment by Nicola1971** [comment]
I'm categorizing all icons, so will be easier to understand style.php and replace them with font awesome in a next future 

https://github.com/Nicola1971/evolution/blob/develop/manager/media/style/MODxRE2/style.php

**Comment by pmfx** [comment]
@Nicola1971 secured resource icon is hard to read - maybe you can make yellow locker black?

now:
![1](https://cloud.githubusercontent.com/assets/10888055/19158715/0ff33b2c-8bea-11e6-8e70-4bc853d864c4.png)

black (easier to read):
![2](https://cloud.githubusercontent.com/assets/10888055/19158727/199cac30-8bea-11e6-8679-863748a0f639.png)

**Comment by Nicola1971** [comment]
because MODxFlat has a dark background tree

updated to work with dark and light bg

![qiqabjihne bflrxrtj5yuzsaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19161536/7f6f34f6-8bf4-11e6-874a-a0be3302ed18.png)

**Comment by pmfx** [comment]
@Nicola1971 Much better now

**Comment by Fr3ddy7** [comment]
@Nicola1971 need lock icon for folder ;)

**Comment by Fr3ddy7** [comment]
very very cool template :) thnx

I think now it is precisely possible to remove carbon )

**Comment by nick0** [comment]
Hey @Nicola1971, in the Manage Files section...
Currently the icons to the LHS of the file names in the Manage Files section looks kind of like the old ones from the LHS of the resource name in the Tree? 
Is it worthwhile changing the LHS Manage Files icons to match the new icons used in the Tree? 

> because MODxFlat has a dark background tree. updated to work with dark and light bg
That looks way better, clear to read now.
The more I look at it though, the more I think the solid black lock that @pmfx put up is a stronger visual (more contrast).

Looking great!

**Comment by Nicola1971** [comment]
> right! thanks
![ayc eaaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19184303/c3180fba-8c7c-11e6-811f-90232b72e3d7.png)

**Comment by Nicola1971** [comment]
> Is it worthwhile changing the LHS Manage Files icons to match the new icons used in the Tree?

@nick0 you mean outlined like in the tree?

**Comment by pmfx** [comment]
@Nicola1971 I'm wondering if full color folder and file icon would be better looking than outlined or not. Could you show us a preview of solid icons please?

**Comment by pmfx** [comment]
@Fr3ddy7 I too think MODx Carbon Theme can be removed. It worked well for many years and now it can retire ;)

**Comment by zaigham** [comment]
Just a suggestion, maybe we can add gravatar to the username in admin area?

![](https://cloud.githubusercontent.com/assets/7342798/19151075/f68fa2e8-8bca-11e6-8a28-bf76e19755eb.png)

**Comment by Nicola1971** [comment]
@pmfx 

>Could you show us a preview of solid icons please?

![p14hnfgomia aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19187679/284c82f2-8c8d-11e6-9f99-75f6016ee0c5.png)

**Comment by Nicola1971** [comment]
Removed all hardcoded icons from files.dynamic.php, and updated all four themes

![download](https://cloud.githubusercontent.com/assets/7342798/19187864/40d54678-8c8e-11e6-9def-f7f3b19f387b.png)

**Comment by pmfx** [comment]
@Nicola1971 thanks for preview, lets stay with outlined, looks better.

**Comment by pmfx** [comment]
@Nicola1971 I have updated style.php and removed moo-datepicker folder from theme folder as datepicker was not working. Issue #800 Fix #799

**Comment by pmfx** [comment]
I wonder if we should use more visible color (maybe #4078c0) for items with "Show in menu" checked. So items visible in menu and hidden from menu would be easier to distinguish. 

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19203322/e711c118-8cd6-11e6-93da-e08294d2bf55.png)

**Comment by Deesen** [comment]
Absolutely :+1:

**Comment by pmfx** [comment]
Cool, new color added to #799

**Comment by nick0** [comment]
> @nick0 you mean outlined like in the tree?

Sorry for delay. Yes, exactly like you did it in your comment with "Removed all hardcoded icons from files.dynamic.php, and updated all four themes". That looks awesome @Nicola1971! Great job

Great idea with more colour contrast for add-to-menu @pmfx. Looks great.
Out of interest, what do unpublished and deleted resources look like?

**Comment by Deesen** [comment]
Personally I would also prefer to give the "Show in menu" a noticeable font-weight.

**Comment by fourroses666** [comment]
Agree to deesen, **bold** ones. Color can stay.

**Comment by Deesen** [comment]
Also in "Manage Elements" personally I don´t like the "line-through". This looks much sleeker to me:

![tv](https://cloud.githubusercontent.com/assets/8569221/19211728/f28ff52e-8d43-11e6-8892-d93db8bca8d8.png)

    .disabledPlugin a {
      color: #aaa;
      font-style: italic;
    }

**Comment by pmfx** [comment]
@nick0 unpublished and deleted have not changed. See screenshot below.
@Deesen agree - bold font for published and in menu. Gray and normal weight if hidden. 
@Deesen as for disabled elements maybe better have it similar as unpublished resource (pale red, italic)?

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19212230/815c05b4-8d4d-11e6-970f-3541027dfaa3.png)

**Comment by Deesen** [comment]
Nice, I like it even more! But main point for me was removing "line-through".

**Comment by pmfx** [comment]
You mean remove line through from Site Tree too?

**Comment by Deesen** [comment]
No, for deleted elements like in site-tree "line-through" makes sense.

**Comment by pmfx** [comment]
Cool, removed only from disabled elements.

**Comment by nick0** [comment]
> @nick0 unpublished and deleted have not changed. See screenshot below.

Thanks for showing that @pmfx . Great to see all resource scenarios in the tree. Very nice.

I didn't notice this before... 
Are the blue show-in-menu links all bold?
If there are lots of show-in-menu resources and not much else the tree might look a bit heavy because of all the bold text.
I vote normal weight for those blue show-in-menu links.
What do others think?

**Comment by nick0** [comment]
> Also in "Manage Elements" personally I don´t like the "line-through". This looks much sleeker to me

Agreed, that looks nice!

**Comment by pmfx** [comment]
@nick0 you may be right. Preview without bold font:

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19216380/3ef1eb0a-8db9-11e6-9df7-a0645dbe534e.png)

**Comment by Fr3ddy7** [comment]
need style for multitv buttons (add, edit, delete)

**Comment by Fr3ddy7** [comment]
404 error file-alt-secure.png

![234234](https://cloud.githubusercontent.com/assets/8958344/19219217/fdd5990c-8e15-11e6-907d-85a3a62eb465.jpg)

**Comment by pmfx** [comment]
@Fr3ddy7 yeah, missing icon fixed in PR #799

**Comment by Nicola1971** [comment]
> 404 error file-alt-secure.png

Sorry, misprint after testing solid icons :)

Regards solid icons.
I'm sure, there are a lot of unused images inside the theme folder.
So, after a clean up of these icons, we could include the solid version of icons for user preference.

**Comment by nick0** [comment]
That looks awesome unbolded @pmfx, it looks sooooooo good. Nice one!

**Comment by pmfx** [comment]
@nick0 thanks, I like it too :) 
BTW I wonder how far we are from releasing 1.1.1 to the public. Was using it for a while and didn't noticed any bugs.

**Comment by dmi3yy** [comment]
I have some list with bug 
-  shared params, not correct work 
Some issues from my custom https://github.com/dmi3yy/modx.evo.custom/issues

And some bug from: 
http://modx.im/blog/dmi3yy/4721.html

My custom EVO in core the same. 
Then all bugs the same


Отправлено с iPhone

**Comment by Nicola1971** [comment]
@pmfx 
love the "primary color" for inmenu items, always used this style in modxFlat and color Skin

**Comment by dmi3yy** [comment]
http://modx.im/blog/dmi3yy/4739.html

**Comment by dmi3yy** [comment]
http://take.ms/QOtbg  - and by Default hide)

**Comment by dmi3yy** [comment]
Move search to top and remove  welcome text )
now more space 
http://take.ms/qURmd

**Comment by pmfx** [comment]
@dmi3yy cool, I will update search input styling a little later.

**Comment by dmi3yy** [comment]
need  set 100% by default like in main tab 
http://take.ms/8eyCJ

and  fix plx bug   when open close http://take.ms/PnFRi
sub menu need fixed for normal work on mobile)

**Comment by dmi3yy** [comment]
Old Icons 
http://take.ms/EgE9p

**Comment by dmi3yy** [comment]
http://take.ms/GVL6E

**Comment by dmi3yy** [comment]
http://take.ms/S99Ey

**Comment by dmi3yy** [comment]
http://take.ms/91seE

**Comment by dmi3yy** [comment]
http://take.ms/Z1nwR

**Comment by Nicola1971** [comment]
> Old Icons 
http://take.ms/EgE9p

@dmi3yy https://github.com/modxcms/evolution/pull/825

**Comment by pmfx** [comment]
@dmi3yy I have fixed this:

https://monosnap.com/file/060Ei2xxRNuxPcl2kcZnThofxaHMbt
https://monosnap.com/file/kaWIA61ANkyL8qlM9VWI59niLiqxy0
https://monosnap.com/file/W0oeY0Sx9pSyg8XWade7eRSoSDoJ3c
https://monosnap.com/file/LsDMevfAArhKhUCljTZKKCxxo3Epvw

In PR #820

**Comment by Nicola1971** [comment]
just for curiosity: whats the problem with 4 screenshot? dont understand cyrillic :)

**Comment by dmi3yy** [comment]
Move button to the one. Column with selects

Отправлено с iPhone

**Comment by dmi3yy** [comment]
http://take.ms/zTgF3
Have install folder but not see Error on dashboard(

**Comment by dmi3yy** [comment]
http://take.ms/YmRDf

**Comment by dmi3yy** [comment]
I think this will be nice
http://take.ms/R87Wg

**Comment by pmfx** [comment]
@dmi3yy scrollbar removed in #830

**Comment by fourroses666** [comment]
maybe replace this with some font awesome list style.
![liststyle](https://cloud.githubusercontent.com/assets/523389/19416625/82680f40-9395-11e6-99ac-ec4433c5ab80.jpg)

`list-style: outside url("images/misc/li.gif") disc;`

`.dynamic-tab-pane-control li`

**Comment by Nicola1971** [comment]
these style images are there from Etomite era, always hated 
![flat2 5-snippets](https://cloud.githubusercontent.com/assets/7342798/19416718/3ec1da7a-9398-11e6-87af-c1c606d0cf07.jpg)

**Comment by pmfx** [comment]
This bullet icon was not changed since Etomite? Haha what a survivor! :)
@Nicola1971 Maybe we could use the same list style/icons as we have in ElementsInTree plugin?

**Comment by fourroses666** [comment]
yea I like this icon in the tree.    >

**Comment by dmi3yy** [comment]
Tree Icons are not beautiful on retina display ((

**Comment by pmfx** [comment]
We will need 2x bigger images. Not sure if @Nicola1971 have it. Anyway I think it should be improved not now but in next release (1.2.1?).

**Comment by fourroses666** [comment]
Ideally it would be a font awesome icon in future and not an image!.

**Comment by Nicola1971** [comment]
>
@pmfx  We will need 2x bigger images. Not sure if @Nicola1971 have it. Anyway I think it should be improved not now but in next release (1.2.1?). 

I have a 512px black version of most of theme, but "composed icons" like icons with lock or "Media Type" icons should be recreated.

I can do for nex minor release

There a re two big issue with font awesome:

1) missing most of "composed" and "Media Type" icons
2) get the tree working :)

Issue 1) 
a) we can try to use font awesome stacked icons, but not sure we can cover all the tree icons set 
b) maybe create a custom icon set from png/svg?

issue 2) 

i've done some experiments with some code taken from ModxPress theme, but have a lot of issue

**Comment by pmfx** [comment]
If we want to cover all resource type, therefore use stacked font awesome, then it won't work. Stacked font awesome icons are meant to be big and will not be readable when squeezed into 16x16px area. 

I see two solutions:

1. Use FA without stacking but it will not cover all resource types.
2. Using @Nicola1971 512px version icons and recreate missing ones. 512px size is a little to big. 64x64px or 128x128px should be ok for retina as we are have them in 16x16px area.

For next release after this one, I would go with solution 2, but after that, work on solution 1.

**Comment by dmi3yy** [comment]
for retina  normax siteX2   
if icons 16x16 need 32x32 )


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 18 октября 2016 г. в 14:11, Piotr Matysiak написал:

**Comment by Nicola1971** [comment]
@pmfx we can use some color class to help identify icons:

``` fa-file-excel-o green```

from my never completed bootstrap theme:

![fa-tree](https://cloud.githubusercontent.com/assets/7342798/19476566/2e50917e-953a-11e6-9da8-bc489bb28671.jpg)

**Comment by dmi3yy** [comment]
On welcome page want font files ( 
http://take.ms/owVZp

**Comment by Nicola1971** [comment]
>On welcome page want font files ( 
http://take.ms/owVZp

@dmi3yy 
fixed https://github.com/Nicola1971/evolution/commit/42bfafaaea2feedd463101735d97a09b3eb619b8

**Comment by Nicola1971** [comment]
@pmfx 
> Maybe we could use the same list style/icons as we have in ElementsInTree plugin?

Do you like it?
![download](https://cloud.githubusercontent.com/assets/7342798/19596126/62342c58-978d-11e6-9df9-9ec9a2ae02d3.png)

**Comment by pmfx** [comment]
@Nicola1971 I like it very much! :)
