### ISSUE TITLE
Enhancement: Add ElementsInTree plugin to default MODX setup

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#783]
dmi3yy shared on gist a **great plugin** to enhance Tree functionality called **ElementsInTree**. Great work there dmi3yy - thanks! 

It adds tabs with elements in Tree so you can edit elements very quick. Even in new window. It is faster and more convenient than default way. And even works better than Revolution IMHO.

I tihnk it is so good it should be in every MODX install **and I strongly suggest to add it to default MODX setup**. 

**I have updated it a little to use hasPermission** so if user role is just edit resources then he see only one tab "Site Tree". If user can edit chunks, a tab "CH" shows up. Same thing for snippets, plugin, templates and tvs. Some styling updates too.

Try it: https://gist.github.com/pmfx/884210dfdd8f49319f9aa6fb9ef3d7ba

Screenshots:

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19054059/e7408474-89bd-11e6-9b81-01fc43a599e9.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/10888055/19054060/e7420646-89bd-11e6-9d47-5322291f9a9b.png)

**Comment by dmi3yy** [comment]
i think by default not good but i can all in extrass for fast install)

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 00:13, Piotr Matysiak написал:

**Comment by pmfx** [comment]
Common, why not? We have stuff like "Jot" or "ListIndexer" or "Search Highlight" that are bundled and are rarely used by most users. Your plugin is a **really time saver and improvement** of working in Manager. It is a "must have", dmi3yy.

**Comment by dmi3yy** [comment]
Yes for Admin its great by for manager  who work only with content no need )  
better for manager minimal info like http://take.ms/442zx  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 00:21, Piotr Matysiak написал:

**Comment by Nicola1971** [comment]
i agree with @dmi3yy, not by default.. at least until we can get "file" tab too (for me most usefull)

anyway, i love this plugin but i dont like very much "short names" like PL, SN, CH, not very clear for customers.

so, i forked this nice plugin and created a version with accordian to show full names
![weeeyw14riulgaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19054611/7ebe523e-89c0-11e6-91a9-b0706b61ec92.png)
 
https://gist.github.com/Nicola1971/f4a4febe3b7392e1ed7f9415d3da07e1

**Comment by pmfx** [comment]
@dmi3yy This is why I added "hasPermission" to it. Regular user only see one tab "Site Tree". It is no difference for user. It even make it looks better if you ask me.

![screenshot_4](https://cloud.githubusercontent.com/assets/10888055/19054736/022da430-89c1-11e6-979c-c6edfbcb2acb.png)

**Comment by dmi3yy** [comment]
i think tab no need add accordion bottom on document tree ))

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 00:28, Nicola написал:

**Comment by pmfx** [comment]
Tabs under Tree would be bad user experience. Especially in big trees/big sites - a lot of scrolling up and down. Tabs works better.

**Comment by dmi3yy** [comment]
I love EVO and I do not want to, he looked like a completely REVO

I think you need to develop a separate and make its own flavor to it, although the functionality has to be on the level.

At the moment, in terms of functionality Page greeting was very nice but the style and layout is a little behind  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 00:30, Lukianenko Dmytro написал:

**Comment by Nicola1971** [comment]
> i think tab no need add accordion bottom on document tree 

absolutely, i have sites with thousand of documents, it would be unusable

i suggest accordian only for elements - with 3 tabs: site, elements, files.
anyway, for me the only usefull tab is the file manager

for elements we have the new tree button that works much better for me.

> I love EVO and I do not want to, he looked like a completely REVO

100% agree - otherwise I would use revo

**Comment by pmfx** [comment]
> I love EVO and I do not want to, he looked like a completely REVO

> 100% agree - otherwise I would use revo

Guys, if I was about to choose between Evo or Revo basing on how the system looks I would choose Revo. 

Yet I prefer Evo. 

But I want it to look more modern and making it look like a Revo sibling is not wrong in my opinion. MODxRE theme refered to old Revo theme. Thats why I think MODxRE2 theme can refer/look close to new Revo theme. Nothing wrong with that.

**Comment by dmi3yy** [comment]
see theme  D3X   i add  few day ago  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 00:54, Piotr Matysiak написал:

**Comment by Nicola1971** [comment]
@pmfx from what I see at this days (lie manager theme api, boostrap manager, new dashboard...), it think will not be long before see a better manager ui in evo than revo :)

**Comment by dmi3yy** [comment]
beautiful UI is something that is sorely missed.

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 01:02, Nicola написал:

**Comment by Nicola1971** [comment]
probably the biggest issue in evo that looks too much older compared to other cms.

**Comment by fourroses666** [comment]
The document tree really needs an update.
Very hard to style that.

This UI looks pritty modern;
https://github.com/modxcms/evolution/issues/690

**Comment by dmi3yy** [comment]
+1 #690  its  fresh   and  lite)   but header background need change )  need simplest )

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 01:10, Marc написал:

**Comment by fourroses666** [comment]
css;
`{background-image: linear-gradient(to right, #3f4850 0px, #365462 46%, #3e5554 60%, #42554d 68%, #573d4e 100%);}`

**Comment by pmfx** [comment]
> see theme  D3X   i add  few day ago

@dmi3yy D3X doesn't look good and it should never go into develop branch. Sorry to be harsh, but I work with designs and frontend every day and I see that it is too "heavy", colors and patterns doesn't fit, paddings/margins need fixing, fonts are too small and shadows are too strong. It is far from being alternative to MODxRE. We should include MODxRE2 #781 But maybe its just my taste...

D3X:

![screenshot_5](https://cloud.githubusercontent.com/assets/10888055/19056398/4365bd90-89c9-11e6-9d13-f4e0e9b496af.png)

MODxRE2:

![screenshot_6](https://cloud.githubusercontent.com/assets/10888055/19056637/c9c584d2-89ca-11e6-8191-44f2471c931e.png)

**Comment by dmi3yy** [comment]
thank for scrin lose icons in tree menu )  

I think need 1 or 2 fresh   theme  

MODxRE2  see like fresh MODxCarbon )  and  I like it )  

my theme better for me if choice  with   D3X  MODxRE and MODxCarbon  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 01:39, Piotr Matysiak написал:

**Comment by pmfx** [comment]
> my theme better for me if choice with D3X MODxRE and MODxCarbon

Sure it can be better choice for you but I was a little surprised that you added it to develop branch. We should discuss new themes, like we discuss other things on Github.

We should have one legacy theme and one new default. Max 3. No more than 3 themes bundled or it will be hard to update.

**Comment by dmi3yy** [comment]
II added for convenience because I have to edit and EBO and MODX.EVO.Custom so at the moment it’s easier and more convenient to synchronize unfortunately I once made a mistake and added separately and did not change the fork of the now late. Before the release will remove the theme, it is not a problem)

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 01:52, Piotr Matysiak написал:

**Comment by Nicola1971** [comment]
for me, we need just a theme in evo package.
I only use my MODxFlat theme since many years (with a custom modxflat colours skin for any customer site), @fourroses666 uses a custom theme, @dmi3yy uses D3X...

we just need a single theme with a clear documentation of updates, so anyone can update the custom theme. 
Like for the frontend theme, for me, the default theme is just a basic "template" for custom themes.

one of the most wonderful things of evo is the manager customization:  is not possible satisfy all of us.

ie: I like use my flat theme to offer to my customers a manager with their "brand colours and logo" (so i started evodashboard). they really love this feature and i dont want to lose it :)

**Comment by dmi3yy** [comment]
+1 its right way!!  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 02:12, Nicola написал:

**Comment by nick0** [comment]
That MODxRE2 screencap looks awesome @pmfx , great job.

I agree, less themes also equals less weight...
One great default theme (probably for visual consistency / branding might be the nicest option) - or - one great default theme and one great alternative theme (gives more choice).
At the moment 2 themes are shipped by default in 1.0.15 and I think that is a good number, any more and it might dilute the visual.

At the moment in 1.0.15 I use MODxRE. Would happily use MODxRE2 if that replaced MODxRE.

On the elements in the tree. I like tabs best. Great idea. I like the sound of the option to hide from non admins. Not fussed if not included by default (why not if it adds more efficient editing for admins as long as doesn't slow the manager down) but I would definitely like to use it.

**Comment by pmfx** [comment]
Thanks @nick0 appreciate it. I've created pull request #785 to include new theme.

**Comment by pmfx** [comment]
Updated ElementsInTree plugin to use FontAwesome icons.
https://gist.github.com/pmfx/884210dfdd8f49319f9aa6fb9ef3d7ba

![2016-10-05](https://cloud.githubusercontent.com/assets/10888055/19113492/2370c434-8b0a-11e6-8246-363662fef6b3.png)

**Comment by Nicola1971** [comment]
very nice. now looks good!

**Comment by nick0** [comment]
> Updated ElementsInTree plugin to use FontAwesome icons.

Wow, they look awesome @pmfx . I think the icons are much nicer than the abbreviated words. Wonderful job.

**Comment by pmfx** [comment]
Thanks guys!

**Comment by Nicola1971** [comment]
there is a small issue with tab icons:

the **cogs** icon was always used for modx modules.
![tkaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19152600/0fc87110-8bd3-11e6-957a-37feec6429b4.png)

replace with plug icon?
http://fontawesome.io/icon/plug/

![89l2zmdmczxaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19152604/1762998c-8bd3-11e6-9611-3eaf47989700.png)

**Comment by Nicola1971** [comment]
@pmfx 

we should use unique icons:

fa-th-large: chunks
fa-cogs: modules
fa-plug: plugins
fa-code: snippets
fa-list-alt: tvs
fa-newspaper-o: templates

we need to change the welcome module icon too
![dzohpjs11qbcaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19152795/fb099a50-8bd3-11e6-81a7-c60de0459de6.png)

**Comment by Nicola1971** [comment]
![wmaz3qv5fecfgaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19153045/256c0dea-8bd5-11e6-93a7-7605ef7f1494.png)

**Comment by pmfx** [comment]
@Nicola1971 "plug" icon fits perfect :) 
Code updated https://gist.github.com/pmfx/884210dfdd8f49319f9aa6fb9ef3d7ba

**Comment by pmfx** [comment]
I've added configuration option to use icons or not. If not text tpl/tv/ch/sn/pl will be displayed.

**Comment by nick0** [comment]
great idea @pmfx, then you you've got everyone covered

**Comment by Nicola1971** [comment]
@pmfx I had not noticed the "**nw**" (new window) feature, cool, but it's very small and at the first time i have read "**new**"  :D 
Can we replace with an icon?

I always use **fa-external-link** in my dashboard widgets for the "open in a popup" feature:
http://fontawesome.io/icon/external-link/

![x f4hmh4alyiwaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19189609/33a1d434-8c99-11e6-9d97-a79dcfba4d27.png)



https://gist.github.com/Nicola1971/f4a4febe3b7392e1ed7f9415d3da07e1#file-gistfile1-php-L95

**Comment by pmfx** [comment]
Yeah, but I cant get it to work with plugin setting (use icons or not). I created "if" inside "createResourceList" but it ignores "$useIcons" plugin setting value. Will leave text version until I sort it out.
