### ISSUE TITLE
Widgets examples for the new Dashboard

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#786]
I'm testing and updating my EvoDashboard widgets plugins for the new native dashboard.

I opened this issue just to show some ideas (I'm sure you can do better)
I will write soon a tutorial about creating widgets for the dashboard.
# Welcome Stats

it's a basic modx system information widgets: show number of documents,  webuser, users and managers .

you can choose between three layouts

Box
![w9pbnva76vrdgaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19070673/b930a176-8a2c-11e6-9ae4-535d68364b49.png)

Round
![wxofjku5lq3ff3ib3jaoyeaw9ijqc42mn755knhqnwsyf9rcwl6yvgwmtiro64j rtjc4txu2nzixy3xfq ylffnlv8prw8xtsv2msqaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19070726/0415e7f0-8a2d-11e6-88e6-e28820489d8b.png)

Lite
![i9yxw3e9kyshzn9t27d5w3clsbklafqkavqajvoar8faq8fv364udybekqhe9k1gkztpfl3759 1puu5woalwgclsbklafqkavqajr4m2bn5fkaz8b5ieufwoa5ve8x88guwaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19070806/5989b66c-8a2d-11e6-8a04-14c74c552918.png)

**Comment by Nicola1971** [comment]
#Rss Reader

An RSS reader based on native rss features of Evo Manager (used to load Modx News widget)
![weg9npbudmzfwaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19070960/07819208-8a2e-11e6-9140-9ddef4b0b6e7.png)

**Comment by dmi3yy** [comment]
need  symetric  for mest visual effect http://take.ms/ysD2N

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 13:26, Nicola написал:

**Comment by Nicola1971** [comment]
#Html widget

Just display a chunk in the widget with what you want
![fpfdxwh6s0gaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19071010/46db8f76-8a2e-11e6-954e-1164ab8a2b38.png)

**Comment by Nicola1971** [comment]
# Latest Disqus

Show latest disqus comments on your site
![bo7vof2yqzqaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19071058/7881796e-8a2e-11e6-8f37-ce109b9a5f01.png)

**Comment by dmi3yy** [comment]
Nice nice i want  it ))  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 4 октября 2016 г. в 13:30, Nicola написал:

**Comment by Nicola1971** [comment]
# List Resource widget

Looks like the latest resource widget but works like my **Article Manager** Module
http://www.tattoocms.it/extras/modx-modules/article-manager-module.html

Is not based on a db query, but use Ditto to call documents.
You can choose parent folder, depht, display, etc

Most important feature: you can choose what you want see in the Overview accordian.
![5n9tpuqde8caaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19071362/fc95cf56-8a2f-11e6-894d-8de65c7f3fd9.png)

You can duplicate and create panels for any kind of project, ie: for Shopkeeper products (showing products fields like price, color ecc)

**Comment by Nicola1971** [comment]
# Last Registered users

Show latest registered webusers 
![nv gaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19071693/a49008d8-8a31-11e6-8cde-c6065b9f96c5.png)

option with photo

![3xufq238adwm1pfbzhaoaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19071740/e9941b22-8a31-11e6-81ed-8bc521c1b4e1.png)

option with editing in a popup

![kln8b9z8cszmnjq0aaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19071700/b117c3de-8a31-11e6-938b-d4159f8be535.png)


I want to allow custom fields like List Resource

**Comment by Nicola1971** [comment]
@dmi3yy 
> need  symetric  for mest visual effect http://take.ms/ysD2N

Welcome Stats need some css updates with latest gridster dashboard 

> Nice nice i want  it ))

http://www.tattoocms.it/extras/plugins/welcome-latest-disqus-comments-dashboard-widget.html

**Comment by nick0** [comment]
Wow, looks really nice!
