### ISSUE TITLE
TinyMCE4 insert image not working

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#787]
When trying to insert image/file by clicking on browse button

![screenshot_0](https://cloud.githubusercontent.com/assets/10888055/19073078/4a1e037a-8a39-11e6-875e-006346736fed.png)

I get this

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19073084/4f8f41d4-8a39-11e6-83d4-59383c9c88e3.png)

**Comment by Deesen** [comment]
I guess its coming from manager/media/browser/mcpuk/core/autoload.php . You could add a test-string to that error-message for testing.

**Comment by pmfx** [comment]
@Deesen I've changes text in line 30 of manager/media/browser/mcpuk/core/autoload.php but nothing happened. Still the same error message.

**Comment by Deesen** [comment]
So the error-msg is not coming from autoload.php? Not sure where to look else.

**Comment by Deesen** [comment]
Can you provide direct access to MODX-manager and also FTP? So I can view & test some files myself?

**Comment by pmfx** [comment]
@Deesen sure, I will mail it to you.

**Comment by Deesen** [comment]
I guess I found the reason. I log into /sandbox/evo110/manager/ so the session-cookie is linked to that path. When I am logged in, this should be the path to the browser used by TinyMCE (path works when logged in):

    /sandbox/evo110/manager/media/browser/mcpuk/browse.php?opener=tinymce4

But TinyMCE opens the URL with slash /manager so it seems you have another manager-directory in root, which causes the error-message. `/sandbox/evo110` is missing in path.

    /manager/media/browser/mcpuk/browse.php?opener=tinymce4&field=mceu_64-inp&type=images

So TinyMCE needs to get fixed..

**Comment by Deesen** [comment]
That should fix it, if not let me know.

**Comment by pmfx** [comment]
@Deesen it works now! Good job. Is there a way to make KCFinder window bigger in TinyMCE4? Maybe 850x750px? Not many files are visible right now in grid view.

**Comment by pmfx** [comment]
Kinda sad that we can't maximize window like it w could before, don't you think? ;)

**Comment by Deesen** [comment]
But you should have a maximize-button within KCFinder toolbar! ;-)

**Comment by pmfx** [comment]
Haha! You got me!
