### ISSUE TITLE
MODx Parse Errors & custom PHP code errors after Evo 1.1 Upgrade

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#788]
I have several websites in which a Listbox (Multi-Select) TV uses a snippet to populate the field with MLS numbers that are being pulled from a non-MODx table in the DB (exp. https://cl.ly/3o1U3p202w0s ).

After the upgrade I modified my custom PHP code in the snippet as follows:

> i replaced

> mysql_query( with $modx->db->query(

> with 

> mysql_fetch_assoc( with $modx->db->getRow(

per @Deesen suggestion....which works fabulous when I select just one MLS #.  

However, when I select more than one nothing displays

Here is the snippet code:

`<?php
$features = $modx->getTemplateVar('GetTopPicks','',1);
$features = $features['value'];
$features_arr = explode("||",$features);

$ids = rtrim(join(',',$features_arr),",");
//$ids = rtrim(join(',',preg_replace('/\D/', '',$features_arr)),",");

$query = "SELECT * FROM mls_listings where MLSNumber = '$ids' ORDER BY ListPrice DESC";
//$query = "SELECT * FROM `mls_listings` WHERE REPLACE(MLSNumber, 'OM', '') IN ($ids) ORDER BY `ListPrice` DESC";
$result = $modx->db->query($query);

$numb = 0;
while ($row =  $modx->db->getRow($result)){
     $numb ++; 
      if ($onHome && $numb>3) break;
      $price = (int)$row['ListPrice'];
      $price_str =  '';
      $i=0;
      while ((int)$price){
         if ((int) $price && $i % 3 == 0 && $i) $price_str = ','.  $price_str;
         $i++;
         $price_str = ($price % 10) .  $price_str;
         $price /=10;
       }     
	
	  $query2 = "SELECT * FROM mls_listings_images where UniqIdent = '{$row["SysID"]}' ORDER BY ImageNo LIMIT 1";
      $result2 = $modx->db->query($query2);
      $row2 = $modx->db->getRow($result2);

      $src = $row2['LocalLocation'];
	  $src = str_replace ('*******/soriahkanji.com/' , '' , $src);
	  
	  $params['DwellingType']=$row['DwellingType'];
	  $params['FloorArea']=$row['FloorArea'];
	  $params['image_src']=$src;
	  $params['HouseNo']=$row['HouseNo'];
      $params['StreetName']=$row['StreetName'];
      $params['StreetType']=$row['StreetType'];
      $params['ListPrice']= $price_str;
      $params['TotalBedroom']=$row['TotalBedroom'];
      $params['TotalBaths']=$row['TotalBaths'];
      $params['PostalCode']=$row['PostalCode'];
	  $params['Community']=$row['Community'];
      $params['City']=$row['City'];
      $params['ListingID']=$row['ListingID'];
	  $params['MLSNumber']=$row['MLSNumber'];
      $params['PublicRemarks']=substr($row['PublicRemarks'], 0, 400);
	  $params['Features']=$row['Features'];
	  $params['View']=$row['View'];
	  $params['Amenities']=$row['Amenities'];
      
//    $params['']=$row[''];
//    $params['']=$row[''];
//    $params['']=$row[''];
     $output.=$modx->parseChunk('TopPicksTpl', $params, '[+', '+]');
}
echo $output;
?>`

and here is the TopPicksTpl chunk code:  https://cl.ly/1M3a3V0E162y

**Comment by Deesen** [comment]
It has nothing to do with upgrade but with line

    $query = "SELECT * FROM mls_listings where MLSNumber = '$ids' ORDER BY ListPrice DESC";

which I guess should be

    $query = "SELECT * FROM mls_listings where MLSNumber IN ($ids) ORDER BY ListPrice DESC";

**Comment by Tourist4Life** [comment]
I get this error now:

https://cl.ly/452U0D1C3D1g

**Comment by Deesen** [comment]
If so, also before the upgrade it could not work with none-numerical IDs... try

    $ids = rtrim(join(',',$features_arr),",");

to

    $ids = "'". join("','", $features_arr) ."'";

**Comment by Tourist4Life** [comment]
Thanks Deesen.  That did it!

**Comment by Tourist4Life** [comment]
@Deesen do you see something in this line that is preventing my pre MODx 1.1 code from getting the image path?


$sid = $row['SysID'];
$query = "SELECT LocalLocation FROM mls_listings_images WHERE UniqIdent = '{$sid}'  ORDER by ABS(ImageNo) ASC";
$result = $modx->db->query($query);

$images = '';
while ($row = $modx->db->getRow($result)){
    $img = str_replace(MODX_BASE_PATH, '',$row[0]);
    $images .= '
	 <div class="slide-bg swiper-lazy" data-background="'.$img.'" data-sub-html="<strong>first line</strong><br/>Second line of the caption"></div>';
}	
$images .= '';
	
$p['images'] = $images;

**Comment by Deesen** [comment]
Is `$img` really empty if you echo it?

    $img = str_replace(MODX_BASE_PATH, '',$row[0]);
    echo $img;

**Comment by Tourist4Life** [comment]
I have added the echo and still no output.  Here is the URL:  http://fairview-condo.com/soriahkanji.com/listing.html?id=2229.

Here is the full snippet

```
<?php
$x = $_GET['id'];
$x = str_replace("'","&#39;",$x);
$x = str_replace("<","",$x);
$x = str_replace(">","",$x);
$x = htmlentities($x, ENT_QUOTES);

$query = "SELECT * from mls_listings where ListingID = '{$x}' ";
$result = $modx->db->query($query);

if ($row = $modx->db->getRow($result)){

$p = array();

$pp = intval($row['ListPrice']);
$price = '';
      
       $i = 0;
        while ($pp > 0){
          $ost = $pp % 10;
          $pp = intval($pp / 10);
		   if ($i > 0 && $i %3  == 0){
			  $price  = ',' . $price;
			}
		   $price = $ost . $price;
          $i++;
	   }

$p['al_listingid'] = $row['ListingID'];
$p['longtitle'] = $row['Address'];
$p['al_addressawp'] = $row['AddressAWP'];
$p['al_postal'] = $row['PostalCode'];
$p['al_virtualtour'] = $row['VirtualTour'];
$p['al_neighbourhood'] = $row['Community'];
$p['al_micromarket'] = str_replace(' ', '', strtolower($row['Community']));
$p['al_bedrooms'] = $row['TotalBedroom'];
$p['al_bathrooms'] = $row['TotalBaths'];
$p['al_fullbaths'] = $row['FullBaths'];
$p['al_halfbaths'] = $row['HalfBaths'];
$p['al_squarefeet'] = $row['FloorArea'];
$p['al_garage'] = 0;
$p['al_unitnumber'] = $row['UnitNumber'];
$p['al_age'] = $row['Age'];
$p['al_price'] = $price;
$p['al_mls'] = $row['MLSNumber'];
$p['al_lotsize'] = $row['LotSizeSqMeters'];
$p['al_dwellingtype'] = $row['DwellingType'];
$p['al_taxes'] = $row['Taxes'];
$p['al_taxyear'] = $row['ForTaxYear'];
$p['al_styleofhome'] = $row['StyleOfHome'];
$p['al_yearbuilt'] = $row['YearBuilt'];
$p['al_view'] = $row['View'];
$p['al_specific'] = $row['ViewSpecific'];
$p['al_stratafee'] = $row['StrataFee'];
$p['al_lotsize'] = $row['LotSizeSqMeters'];
$p['al_listfirm'] = $row['ListFirm'];
$p['al_lastupdate'] = $row['LastUpdate'];
$p['status'] = $status;
$p['introtext'] = $row['PublicRemarks'];
$p['content'] = $row['PublicRemarks2'];
$p['al_bestfeatures'] = $row['Features'];
$p['al_amenities'] = $row['Amenities'];
$p['al_siteinfluences'] = $row['SiteInfluences'];

$sid = $row['SysID'];
$query = "SELECT LocalLocation FROM mls_listings_images WHERE UniqIdent = '{$sid}'  ORDER by ABS(ImageNo) ASC";
$result = $modx->db->query($query);

$images = '';
while ($row = $modx->db->getRow($result)){
    $img = str_replace(MODX_BASE_PATH, '',$row[0]);
	echo $img;
    $images .= '<div class="swiper-slide"><img class="slide-thumb" src="'.$img.'" alt="'. $p['longtitle'].' - '.$p['al_neighbourhood'].'"  /></div>';
}	
$images .= '';
	
$p['images'] = $images;

echo $modx->parseChunk('MLS_listing_Photos',$p,'[+','+]');

}
?>

```
