### ISSUE TITLE
Missing "Search by template ID"

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#789]
Looks like this option was removed. Can we bring it back? It is very useful.

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19130102/28d5185e-8b4a-11e6-9ebc-ac06fc981af0.png)

**Comment by Deesen** [comment]
I also improved the form, it now remembers values after sending. And I merged alias/ID into the same field. 

![search](https://cloud.githubusercontent.com/assets/8569221/19154839/5975c50c-8bdc-11e6-9cc3-e7d538e33383.png)

**Comment by pmfx** [comment]
Perfect! Thanks Deesen.
