### ISSUE TITLE
AjaxSearch code placed below in the source.

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#790]
Is there a way to place this automatic code placed right before the < /body > 
instead of in the < head >?

We probably talkin about mili seconds here but Google just likes js on the bottom.

**Benefits of Moving JavaScripts to the Bottom**

_JavaScript is a client side programming language. It is executed and run by a user’s web browser and not by your web server. When you put JavaScript at the top, browsers may execute or process the JavaScript before loading the rest of your page. When JavaScripts are moved to the bottom, your web server would quickly render the page and then the user’s browser would execute JavaScripts. Since all the server side rendering is already done, the JavaScript will load in the background making the overall load faster._

_This will improve your speed score when testing with Google page speed or Yslow. Google and other search engines are now considering page speed as one of the performance matrices when displaying search results. This means that websites that load faster will appear more prominently in search results._ 

```
<!-- start AjaxSearch header -->
<script type="text/javascript">
//<![CDATA[
asvar=new Array();asvar[0]='{"vsn":"1.10.1","adv":"oneword","sub":"","bxt":"Search here...","cfg":"&language=`english` &landingPage=`19` &showResults=`0` &moreResultsPage=`19` &addJscript=`0` "}';
//]]>
</script>
<!-- end AjaxSearch header -->
```

**Comment by Deesen** [comment]
You could test file ajaxSearchOutput.class.inc.php line 895-929 and replace `regClientStartupScript` by `regClientScript` to achieve it.

**Comment by fourroses666** [comment]
Yea that works, nice find. 
I noticed that script isn't being placed in the source when using: `&ajaxSearch="**0**"`
_(Had some sites with and without the script)_

I better use that in the future to keep the source cleaner.
