### ISSUE TITLE
Performance: Minify manager styles [smart or not?]

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#791]
On all my sites I use minify, wonder if we like to add it to the manager?
Big plus will be performance.
Some downs might be for manager developers it will be harder to find the right lines with firebug and maybe some cache issues?

It works pritty damn good on my frontend sites thow. 
Just adding src="**/min/?f=**/assets/my-path/style.css**,**/assets/another-one.css" and also for my .js files.

Add a plugin "minifyRegistered".
https://github.com/Jako/MinifyRegistered

**Comment by Deesen** [comment]
If you have big manager with 1000 of files like Revo, then it could make sense. But for Evo I guess nobody would notice any difference in performance. Also it can harden bugfixing like you mentioned, so not worth the effort in my opinion.

**Comment by Nicola1971** [comment]
I agree with Deesen, actually I don't think we need to minify

**Comment by fourroses666** [comment]
Oke no problem.
