### ISSUE TITLE
ManagerManager: An error has occurred: TypeError - $j(...).mm_widget_showimagetvs is not a function

### ISSUE THREAD

**Issue by Tourist4Life** [modxcms/evolution#797]
This error appears only with certain templates which leads me to believe that there is a jquery conflict?  

https://cl.ly/0R4533340h3s

**Comment by Nicola1971** [comment]
I had this issue from years:

Most common causes:

- front end template: try to change quick manager jquery setting (able/disable jquery in fronted and manager)

- manager theme: try to change manager theme

- errors in your mm rules chunk

**Comment by Nicola1971** [comment]
solved?

**Comment by Tourist4Life** [comment]
Yes disabling jquery in the front end seems to have fixed this!

Thanks @Nicola1971 !
