### ISSUE TITLE
DatePicker not working on latest build

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#800]
I got error in console log when editing resource and DatePicker is not showing up.

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19188171/40e199ee-8c90-11e6-8f8b-d26e77a9d035.png)

**Comment by Deesen** [comment]
For me the same. At the source-code´s end datePicker is loaded from theme MODxCarbon?

**Comment by pmfx** [comment]
I've updated style.php and now it is working.

Was:
`$modx->config['mgr_date_picker_path'] = sprintf('media/style/%s/moo-datepicker/datepicker.inc.php',$modx->config['manager_theme']);`

Is:
`$modx->config['mgr_date_picker_path'] = 'media/style/common/moo-datepicker/datepicker.inc.php';`

**Comment by Deesen** [comment]
Me I found MODxRE2/moo-datepicker/datepicker.tpl which had "modxcarbon" in it.

**Comment by pmfx** [comment]
Fixed #799

**Comment by pmfx** [comment]
But moo-datepicker folder should be in common folder. It is not present in other themes. #799
