### ISSUE TITLE
Enhancement: Elements Category Collapse (accordion)

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#806]
Many of my sites are based on large amounts of snippets, chunks, plugins divided into different categories.

Sometimes in very hard for my eyes search them in the static.resource  page.

I always hope to see this feature (maybe in the new elementsintree plugin too)

https://www.youtube.com/watch?v=mF6Xr3s1er8

what do you think about it?

**Comment by kp52** [comment]
That looks a handy idea. You'd probably want to have an item count by the category title in place of, or at least as well as the numerical ID. I doubt if ID is much use, except for referring to templates - other resources are referred to by name in the API.

**Comment by Deesen** [comment]
And it would need some kind of "remember tab"-functionality. Makes no sense to me without.

**Comment by pmfx** [comment]
I would prefer to have something like "instant search" form on top of the list more. Build with javascript only.

**Comment by Nicola1971** [comment]
@pmfx  I agree
month ago,  i've tried something like this but with no luck

http://jsfiddle.net/x8rpY/1/

**Comment by Nicola1971** [comment]
@Deesen 
> And it would need some kind of "remember tab"-functionality. Makes no sense to me without.

agree, but don't know how remember tab works in Evo

**Comment by pmfx** [comment]
@Nicola1971 Yes, something similar this. Maybe I will look into this "instant search" this week.

**Comment by Deesen** [comment]
Yes should be not complicated using Localstorage + Javascript. For example in my scrollfix-plugin I added a new option some months ago to mark "last edited ID". So when I opened plugin scrollFix and close it, in static.resource it is marked green and bold.. very useful if you open and close i.e. several chunks in a row:

![last-edited](https://cloud.githubusercontent.com/assets/8569221/19237347/b36495a2-8efc-11e6-8527-83466791849f.png)

**Comment by Nicola1971** [comment]
testing collapse categories with elementsintree (like in revo)

Looks cool to me

![azxjbpss1gxjaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19238979/441aada0-8f04-11e6-9923-683b38e18144.png)

**Comment by pmfx** [comment]
OK, so I've experimented with "live" search of elements and I think I have it working. Used small jQuery plugin. Will prepare a preview soon :)

@Nicola1971 collapsing in ElementsInTree look interesting. Maybe I will open github project for this plugin so we can work on it more efficient.

**Comment by pmfx** [comment]
Elements live search/filtering demo:
http://pm-fx.com/sandbox/evo110/manager/
preview/preview

Let me know what you think.
I can make pull request if everybody are happy :)

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19248106/6c9a3e4c-8f2e-11e6-866a-7e48dcf052c2.png)

**Comment by pmfx** [comment]
Ah, this is jQuery plugin I used https://github.com/riklomas/quicksearch

**Comment by dmi3yy** [comment]
yes its nice   pull  this %)  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 10 октября 2016 г. в 22:15, Piotr Matysiak написал:

**Comment by a-sharapov** [comment]
Looks great!

**Comment by pmfx** [comment]
Done #808 :)

**Comment by Nicola1971** [comment]
really nice!

**Comment by fourroses666** [comment]
Works great!

**Comment by pmfx** [comment]
@Nicola1971 I have added it to ElementsInTree plugin. Works fine.
https://gist.github.com/pmfx/884210dfdd8f49319f9aa6fb9ef3d7ba

![screenshot_2](https://cloud.githubusercontent.com/assets/10888055/19249727/3b3aa554-8f37-11e6-8126-32cd9806010e.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/10888055/19249728/3b3e0f28-8f37-11e6-954f-342d34c0e20f.png)

**Comment by Nicola1971** [comment]
@pmfx really love this feature in resource.static, finally I don't need chrome/Firefox search to fast find resources. No more need accordion here.

Looks nice with tree plugin too, but If you have a lot of resource, the list is still too long for the tree frame.

**Comment by nick0** [comment]
Great work @pmfx! I love this search functionality in elements and the tree, that is a great addition.

Do you think the search box ties is with the buttons (new, sort)? I am not sure the more I look at it.
Not sure if this is possible but what if the search looked more like one of those buttons like in the mockup below?
It could probably just say Filter List

![untitled-1](https://cloud.githubusercontent.com/assets/1768308/19256034/d94e0bb4-8faa-11e6-806e-f9bde1448a5e.jpg)

Could the search have a minus button inside the field on the RHS that appears when something is typed so that searched text can be easily cleared?

**Comment by nick0** [comment]
The theme in your test site looks awesome @pmfx!

**Comment by nick0** [comment]
The accordion idea is really nice @Nicola1971.
If this was rolled out it would be nice to show a + (to expand) and a - (to minimise) so the functionality is clearer.

**Comment by Nicola1971** [comment]
refined Elementsintree collapse styles
![4 yhjl4osjwaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19269594/bd361258-8fbb-11e6-8817-f769c33ac966.png)

![qm9axqah7ddwq63hgmwarkscaq9ulnn3zpb621imvpln3ntjgbtk3a1hkb06lxqcly45kae1acary9xxuzo8wemiazbfj0nkhh9zibjqa4aix6iusydpgjmafncldoouop72uctebxbfj0fndl7datyaloelakev8fg72kssq1nmuaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19269598/c23e5648-8fbb-11e6-9d61-f0c47e124b1a.png)


video
https://www.youtube.com/watch?v=23bzgYrIF8o

**Comment by Nicola1971** [comment]
@pmfx 
Tried to merge the search with accordion in Elementsintree.

there is a "obvious" issue: 
**when the collapsible content is hidden, you can't see the search filter working**
 :D  :D 

Default view with all visible content makes no sense to me, so i've found a cool solution:

expand categories when you focus on search form!

video demo:
https://www.youtube.com/watch?v=4RpJPa_CWAU

gist
https://gist.github.com/Nicola1971/f4a4febe3b7392e1ed7f9415d3da07e1

**Comment by pmfx** [comment]
Hah, I've just done the same! But I prefer to see all categories expanded by default. Icons on lists are nice.
https://gist.github.com/pmfx/884210dfdd8f49319f9aa6fb9ef3d7ba

**Comment by Nicola1971** [comment]
for me, all categories expanded, does not looks very good and, if you want, you just need to click on search to expand all.

should be better enable/disable the "in" class as a plugin configuration parameter, so people can choose default layout (tried but does not work, like  your useicons variable issue).

**Comment by pmfx** [comment]
@nick0 good idea, added in #811 

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19277989/f8c2a1d6-8fdb-11e6-9e39-6ed5fa296daf.png)

**Comment by pmfx** [comment]
@Nicola1971 Honestly I don't know. Initially idea of ElementsInTree was to show all and to have quick access to elements. It was extended then with live search feature to speed things up even more. Collapsed elements on start maybe looks better but delays access to what user is looking for. I think of collapse as a nice addon but not default state. But thats me. I wonder what others think. 

I would want it to remember what was collapsed and what wasn't on reload though :)

**Comment by Nicola1971** [comment]
It depends on the amount of elements you have. For a small site expanded categories works nice, for big site with a lot of resource, looks like the resource tree with all folder expanded: an infinite scroll.
Note: the default view of resource tree is with closed folder.
Better solution: find a way to add a configuration option.

Anyway is not important for me: I'm very satisfied for all these updates and the new manager theme. There are a lot of features I've added or "tried" / "dreamed" to add :) Into my themes and plugins.
Really love all your additions to the manager.

**Comment by nick0** [comment]
> @nick0 good idea, added in #811 

That looks awesome @pmfx! Great job and thank you.

> refined Elementsintree collapse styles

That looks super @Nicola1971. Well done.

How good does this theme look!!

Thanks to all.

**Comment by pmfx** [comment]
@Nicola1971 Agree - best solution to this is to add a configuration option. 

I have created a repository for this great plugin so we can work on it better:
 https://github.com/pmfx/ElementsInTree

Also added it to MODX install in PR #820 :)

**Comment by Nicola1971** [comment]
for all evo users who suffer for the limitations of items in the module menu...

the module tab!
![wdu6dbomt5z8gaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19416773/7cc714b0-9399-11e6-94aa-093a9195907b.png)

**Comment by fourroses666** [comment]
The ? next to the TV fields on a resource have a gap on wide screens and too small on small ones.
Maybe this is better to use? 

```
form#mutate .inputBox {
    width: 93%;
}
form#mutate .inputBox {
    width: -moz-calc(100% - 30px);
    width: -webkit-calc(100% - 30px);
    width: -o-calc(100% - 30px);
    width: calc(100% - 30px);
}
```
![gap](https://cloud.githubusercontent.com/assets/523389/19419731/13be1780-93de-11e6-9cac-9128f2b14c42.jpg)

-----

The preloader could have a smaller font-size?
Doesn't need to be so big if you ask me. 

```
.preLoaderText p {
    font-size: 14px;
}
```

Really like this new theme.

**Comment by pmfx** [comment]
@Nicola1971 I think we can close this "issue" :)

**Comment by Nicola1971** [comment]
yes, we can close

just check how much is sexy this plugin with dark colours  :) (MODxFlat Theme)
![download](https://cloud.githubusercontent.com/assets/7342798/19471982/b1e5d036-9525-11e6-8136-8b0e579277f7.png)

**Comment by pmfx** [comment]
Damn, Plugin, you look sexy tonight! Haha. 
Very nice!
