### ISSUE TITLE
Access to Manager message page

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#815]
With latest top nav and welcome updates we have completely removed any access to the Message system.

I never used it, but we need to restore for people who use it.

for now, i just added a link to action 10 in the welcome message row
https://github.com/modxcms/evolution/pull/814/commits/dc24d7628c4456b49649611ad1fcf63d60c32998

![download 1](https://cloud.githubusercontent.com/assets/7342798/19307137/1ffaad5a-9079-11e6-925e-c9347f759625.png)

other options:
- add a Message icon next to the Help icon
- add a menu item (inside Tools Menu?)
- restore a button in the top nav

![oim7bscjqh6p554u6 22buaaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19307365/58025922-907a-11e6-85c6-e1cf13490fe4.png)

**Comment by pmfx** [comment]
You are right. I think linked message (first screenshots) is OK. Simple and easy to maintain.  
Other options sounds good too **except button next to logout**. 
It is not THAT important feature to be visible all the time if you ask me.

**Comment by fourroses666** [comment]
> Other options sounds good too except button next to logout.
> It is not THAT important feature to be visible all the time if you ask me.

Maybe its possible to show when message > 0 

I don't use that system and rather don't have this button too.

**Comment by Nicola1971** [comment]
> Don't know if its much work but would be nice to have a config setting to set on/off the messages system. Then its (inbox) not visible too on the dashboard.

agree. would be nice an option in settings > interface and features to hide it, like old "Show META Keywords tab" (that we could completely remove, anyone still use that tab?)

**Comment by pmfx** [comment]
@Nicola1971 very good idea to have it in settings > interface as an option. 
I've never used "Show META Keywords tab". I think it should be removed completely.

**Comment by fourroses666** [comment]
Never used it, use my own custom tv and tab

**Comment by nick0** [comment]
I never use the meta keywords tabs either (I use intro text for keywords)

+1 for option to remove the message system via the configuration settings.

**Comment by Nicola1971** [comment]
solved for now
