### ISSUE TITLE
Enhancement: Remove Login Credentials for Default Registration Email 

### ISSUE THREAD

**Issue by freelancewebdev** [modxcms/evolution#818]
The default email that is sent to a user when they register contains their login credentials.  Email is inherently insecure so including the credentials in this way is a poor default choice in this day and age.

**Comment by Deesen** [comment]
How would the ideal procedure for creating MODX-users work for you then?

**Comment by freelancewebdev** [comment]
Hey,

The same as it does now.  Just the the default email sent out to a user
when they register wouldn't have their login credentials in it.

I'm referring to the text sent out in the Web Signup Email field in the
system configuration.



Kind regards,

Joe Molloy

F R E E L A N C E  W E B  D E V E L O P E R

-----------------------------------------------------------------------------------
C O N T A C T  D E T A I L S
-----------------------------------------------------------------------------------
Mobile:                  +353 86 6087493
Landline:                +353 1 8348780
Web:                      hyper-typer.com

C o n n e c t i o n s
-----------------------------------------------------------------------------------
Twitter:                   twitter.com/FreelanceWebDev
Facebook:               fb.me/FreelanceWebDeveloperIreland
Google Plus:           gplus.to/FreelanceWebDev
Skype:                    FreelanceWebDev
RSS:                      hyper-typer.com/latestnews.rss
-----------------------------------------------------------------------------------

**Comment by freelancewebdev** [comment]
The string for the default email is coming the language file in
'manager/includes/lang.  Line 100 in english.inc.php

$_lang["system_email_websignup"] = 'Hello [+uid+]
Here are your login details for [+sname+]:
Username: [+uid+]
Password: [+pwd+]
Once you log into [+sname+] ([+surl+]), you can change your password.
Regards,
Site Administrator';

should be changed to:

$_lang["system_email_websignup"] = 'Hello [+uid+]
Welcome to [+sname+] ([+surl+])
Regards,
Site Administrator';

Many users won't know the significance of the need to change their
credentials after the has been transmitted by email.  To avoid this, they
should just not be sent in the first place.


Kind regards,

Joe Molloy

F R E E L A N C E  W E B  D E V E L O P E R

-----------------------------------------------------------------------------------
C O N T A C T  D E T A I L S
-----------------------------------------------------------------------------------
Mobile:                  +353 86 6087493
Landline:                +353 1 8348780
Web:                      hyper-typer.com

C o n n e c t i o n s
-----------------------------------------------------------------------------------
Twitter:                   twitter.com/FreelanceWebDev
Facebook:               fb.me/FreelanceWebDeveloperIreland
Google Plus:           gplus.to/FreelanceWebDev
Skype:                    FreelanceWebDev
RSS:                      hyper-typer.com/latestnews.rss
-----------------------------------------------------------------------------------

**Comment by Deesen** [comment]
Yes but webusers, when creating an account, have to set name/password themselves so they know it and there is no need to send again via insecure email. 

If a manager adds a user or changes user-credentials, how to notify this user in a secure way? Maybe a new option that forces users to change password at first login?

**Comment by freelancewebdev** [comment]
The change password on first login still requires a password to be sent via email.  

My preference would be to never have it be necessary for an administrator to know a user's password - that's another security issue and it also introduces an extra and unnecessary work load for the admin.  

In cases where I have had to implement a password reset before, I've sent the user to a link with a form which takes the user's email address.  It checks for this address in the database and if found, sends a temporary link to that address.  It should be noted that after the user submits their email, they are not given any indication that their email has been found or not - we don't want an enumeration attack.  They are only told that if the email address is found, they will receive a password reset email shortly.   The link I sent contained a guid which I store for the user.  When the user follows the link back to the site, they are asked to enter their username (I can pull the guid from the query string) and if the username maps to the email address initially provided AND the guid also maps to the same username, a password change is accepted.  A final confirmation email is sent to the user just to confirm that this action has been taken, obviously without the new credentials.

**Comment by bossloper** [comment]
@freelancewebdev  so that is a little like the current manager frontend 'forgot password' mechanism?

I.e. in summary -  an expiring token is assigned to the account. A link (with token) is emailed to the user that when clicked logs them in via checking against the token and then as an addition would force a password reset?

**Comment by freelancewebdev** [comment]
No, the link in the email doesn't automatically log them in - it leads them back to a form when they are required to submit their username and we can grab the token too.  If we just automatically log in anyone who comes back through the link, that's no different to sending the full credentials.  My version requires both validation of the email, username AND the token.

**Comment by bossloper** [comment]
So they need to know their username. I know from experience some users even forget that. :-)

**Comment by pmfx** [comment]
Current way of sending password in open text is really BAD. I agree with @freelancewebdev beside one thing - not sure if user needs to remember **username** to reset password. Maybe providing email should be enough. And confirmation with username but WITHOUT new password will be sent.

**Comment by freelancewebdev** [comment]
Well as always these things are a trade-off between security and convenience.  I feel it's important to have the second piece of data to confirm with the token, not just the email. Perhaps to cover the case of someone forgetting their username too, a partially masked version could be sent to remind them.

**Comment by bossloper** [comment]
@pmfx - I agree. And if the token expires (system configurable) then that should be secure enough?

**Comment by Deesen** [comment]
Maybe a "forgot username" - option makes sense? User can enter email-adress and it will also send a link with token by mail. If clicked on and valid, MODX will reveal just the username corresponding to this emailadress. I am no security-expert so not sure about it..

**Comment by freelancewebdev** [comment]
That's why I was suggesting the masked username.  If I was sent something like f*****n**w****v, that would probably be enough to remind me.  If that doesn't suffice for a user, it's really a situation an admin should be paying some attention to anyway IMHO.

**Comment by Deesen** [comment]
Yes I deleted my "Forgot username"-proposal posting, makes no sense in this regard.

**Comment by freelancewebdev** [comment]
I don't think there's going to be a one size fits all solution here.  For some a token would suffice, others, like me, would prefer a third piece of data to lock down the association of a user with their account.  I am sure something modular can be built.  

Really my main goal here was to get the language file changed so I don't have to remember to do it each time I inherit an Evo site - ideally our defaults would promote good practice.

**Comment by freelancewebdev** [comment]
The other possibility is to have an admin nominated field as the secondary data - so rather than being stuck with username, an admin could use phone number or some other field from their users' profile.

**Comment by Deesen** [comment]
BTW you lead me to another idea. How about an optional "lang"-override? Like having a new directory inside `/manager/includes/lang/` like `/manager/includes/lang/override/`. This directory holds custom overrides that will not be altered at any Evo-update. Would it be a useful addition to MODX?

**Comment by freelancewebdev** [comment]
I've no idea how the language files work in Evo to be honest but I did notice when I was looking for the text of the email that there's a British English version of the english language file but it only has a few entries so perhaps there is a mechanism already to extend the default files?

**Comment by Deesen** [comment]
1. the english-language will be loaded here 
https://github.com/modxcms/evolution/blob/develop/manager/index.php#L156-L162
2. the user-language will be loaded and overrides existing english keys here 
https://github.com/modxcms/evolution/blob/develop/manager/index.php#L164-L166

So I guess there is no similar mechanismn. After line 166 we just need to check if language-file exists inside directory `/override/` and load it as step 3.
