### ISSUE TITLE
Idea to make Duplicating TVs faster

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#822]
It takes allot of time to build TVs when you use them allot.
I was thinking about a way to make this work a little faster.

Especially the instant duplicate and renaming in the list would help allot.
Not having to load a whole new page and go back again to the list.

_Or to take that a little further all items which are on the TV detail page already visible in an accordion. So we can stay on the same page._

![tv-idea](https://cloud.githubusercontent.com/assets/523389/19391606/a849674a-922d-11e6-93a0-b76ad0a01f63.jpg)

**Comment by pmfx** [comment]
@fourroses666 Good idea! I think it should be available for templates, chunk, snippets, plugins too.

**Comment by fourroses666** [comment]
Could look a bit like Nicola did on the dashboard. For TVs it would really help me allot.
Some sites have 50+ TVs and this could really be a timesaver. 

Delete might need a popup, "are you sure?"

**Comment by dmi3yy** [comment]
I thin no need more new  ideas  

need fix all bug  and public  new version and then add new)  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 14 октября 2016 г. в 18:12, Marc написал:

**Comment by dmi3yy** [comment]
like https://github.com/modxcms/evolution/issues/824
or this https://github.com/modxcms/evolution/issues/823


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 14 октября 2016 г. в 18:15, Lukianenko Dmytro написал:

**Comment by fourroses666** [comment]
Oke, could be labelled for the next version.

**Comment by pmfx** [comment]
I agree with dmi3yy. Lets work on this and other ideas (like #770) after this release is completed.

**Comment by Nicola1971** [comment]
I agree with you @dmi3yy: we need to fix and public a new version... **for now!**.

But there are too much steps for most of everyday routines in evo manager and this is a great idea to improve the manager in next version (1.1.x)

**Comment by dmi3yy** [comment]
For now think:  

fix for ne theme MODxRE2  

and fix bug and all   

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 14 октября 2016 г. в 18:21, Nicola написал:

**Comment by Nicola1971** [comment]
forgot this issue.
@fourroses666 check here:
https://github.com/modxcms/evolution/issues/894

**Comment by fourroses666** [comment]
Think this can be closed
