### ISSUE TITLE
Error in ShareParams

### ISSUE THREAD

**Issue by Dmi3yy** [modxcms/evolution#823]
fix it https://github.com/modxcms/evolution/commit/fce980ec162b462c0c620e858dfaf351bd816605
but i think no good

where we have shared params in  function  we have :

but this incorrect json http://take.ms/k0yxt

**Comment by Deesen** [comment]
Not tested.. is this the solution??

**Comment by dmi3yy** [comment]
Its work 


Отправлено с iPhone

**Comment by SebastianoFereiro** [comment]
Добрый день, обновил сегодня версию 1.2-d8.1.4, но вот завести работу
evobabel-0.2 -  плагина evoBabelPlaceholder и [+switchLang+] не могу
подробнее здесь описывал
https://github.com/dmi3yy/modx.evo.custom/issues/354
возможно, я что-то не учел (полная переустановка плагина, а так же попытка потанцевать с последовательностью настройки не помогла)
примечание: создание языковых версий работает штатно.

**Comment by WebAdmFcm** [comment]
Дмитрий, доброго времени суток!
Пытаюсь сделать мультиязычность, установил и настроил плагин EvoBabel.
Делал все по инструкции, не могу понять или я что-то не то делаю или плагин не работает.
Можете написать, работает ли он вообще, если да, то на какой версии, пробовал на 1.4.2, 1.2-d8.1.5

**Comment by Dmi3yy** [comment]
Использовать надо последнюю версию на текущий момент это 1.4.10 а. не 1.4.2

**Comment by WebAdmFcm** [comment]
Поставил версию 1.4.10, все-равно не работает, TV relation так и не появилось у ресурсов, пробовал добавлять TV - не помогло.
Добавилась К кнопкам редактирования ресурса кнопка RU, при нажатии на нее куча надписей Undefined.
Настраивал так:
Создал документ Title - RU, longtitle - Русский, Desc - 1 (Главная), Алиас ru.
В него перекинул все ресурсы.
Создал TV relation, Шаблон Язык
Установил Из репозитория Модуль
В модуле evoBabelLexicon: id шаблона языка - поставил ID созданного шаблона под названием
Язык; id TV языковых связей - ID созданного TV relation.
В плагине evoBabel прописал: ids TV для синхронизации - ID созданного нового TV titlepage
ids шаблонов для синхронизации - Указал ID Имеющихся Шаблонов.
Не понимаю, что еще нужно, напишите, пожалуйста
