### ISSUE TITLE
Demo site is broken 

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#824]
https://monosnap.com/file/x8owzTwtg5KJZbcslySHFR66MvRT6z

**Comment by Deesen** [comment]
Does it fix the issue?

**Comment by Deesen** [comment]
I also noticed database is not resetted when installing demo-site. Old chunks, ressources etc are not removed. Maybe we should add `TRUNCATE TABLE` to setup.data.sql ?

**Comment by modxuser** [comment]
The demo site has been broken since the 1.1 version was released.

This was discussed in the MODX forums shortly after 1.1 was released, but I sadly can't find the post.

**Comment by dmi3yy** [comment]
need  template 'Sample template in Bootstrap' move to sql.

**Comment by Deesen** [comment]
But like now it is also possible to install template without demo-site.

**Comment by dmi3yy** [comment]
ok )

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


суббота, 15 октября 2016 г. в 14:30, Deesen написал:

**Comment by Deesen** [comment]
Plus it is easier to maintain a file-based template. And we can also provide more theme-variants in future. Maybe a radio-option which variant to install demo-content with. Just thinking loud..

**Comment by Deesen** [comment]
But maybe its not good to clear too many tables when installing demo-content? For example, should plugins and snippets be removed or not?

https://github.com/modxcms/evolution/blob/develop/install/setup.data.reset.sql

**Comment by Nicola1971** [comment]
Always dreamed 3 option in install

1) install demo: just install demo content
2) install demo and reset : install demo content and truncate all tables
3) reset all: truncate all tables and reset the system to base installation (no demo content)

**Comment by dmi3yy** [comment]
fixed this ?

**Comment by Deesen** [comment]
I hope so. I had same error like your screenshot but now no more.

**Comment by dmi3yy** [comment]
ok then close
