### ISSUE TITLE
Extras Module not working

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#839]
I get jQuery error (depracated getPreventDefault() ) when clicking on "Install" and nothing happens. Just "loading" animation.

![screenshot_2](https://cloud.githubusercontent.com/assets/10888055/19468668/0178654a-9518-11e6-9c96-4ec6730a0647.png)

Does it work for you?

**Comment by Nicola1971** [comment]
I wanted to open the same issue, but I was not sure if the problem was just for me. 
only it happens with some sites: just loading... sometimes say "installed" too, but nothing happens

**Comment by Nicola1971** [comment]
another small issue with Extras module: 404 error: search a store.css inside theme folder 

![storecss](https://cloud.githubusercontent.com/assets/7342798/19472507/efcabbc6-9527-11e6-96ab-15911ed503fa.jpg)

**Comment by fourroses666** [comment]
Have issues too with installing sometimes.

Because Store/Extras is default it should be in the theme CSS.

**Comment by dmi3yy** [comment]
need add store.css but not working if:

not instaled zip extention php
not work openssl
not have premision for folders with elements

**Comment by pmfx** [comment]
OK maybe it is hosting problem. Closing this issue for now.
