### ISSUE TITLE
not work search from  topmenu

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#841]
http://take.ms/cmxDG

**Comment by dmi3yy** [comment]
its bug :)  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


вторник, 18 октября 2016 г. в 18:10, Deesen написал:

**Comment by Deesen** [comment]
Ah right, because of the space..

**Comment by dmi3yy** [comment]
done )

**Comment by Deesen** [comment]
But stupid me, was NOT because of spaces LOL ..
