### ISSUE TITLE
Enhancement: Remove widget button

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#848]
![h9b9x9z4ivciaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19557439/fe6d2804-96c5-11e6-8149-565029cdd274.png)

I think is a missing feature for the Dashboard
so I've updated  dashboard.js and welcome tpl, works very nice

demo:
https://www.youtube.com/watch?v=jIqhGi0HyjY

what do you think about it? pull?

**Comment by dmi3yy** [comment]
need add button bottom   Add Widget from widget list  

if delete only restore all work  this no good   

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 20 октября 2016 г. в 14:07, Nicola написал:

**Comment by Nicola1971** [comment]
> need add button bottom   Add Widget from widget list
if delete only restore all work  this no good

@dmi3yy working on it, need to find a way to hide not deleted widget from the list

![wnguyr5iugwmaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19592729/4a1df294-977d-11e6-999d-e13880eb6f01.png)

check video
https://youtu.be/m7YyDeH2guY

**Comment by dmi3yy** [comment]
and move button to bottom with button default )  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 21 октября 2016 г. в 11:59, Nicola написал:

**Comment by Nicola1971** [comment]
Placed before the grid just for testing. I will move next to reset button.

Anyway, after latest Evodashboard updates, I don't think it's very useful.

You can hide widget with my plugin and additional widget are just plugins, so you can disable.

**Comment by Nicola1971** [comment]
I think I close. Evodashboard solve this for now.
