### ISSUE TITLE
Multiple upload for Manage Files. [label feature]

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#854]
Would be nice to have a multiple file upload at the Manage Files section. 
Really have no idea if its an easy task but if so it would be nice to have.

**Comment by pmfx** [comment]
Agree, maybe we could use something like http://filer.grandesign.md

**Comment by fourroses666** [comment]
Looks sexy :)

**Comment by fourroses666** [comment]
Closing this, will be cool to have but not that important. Don't think anyone is up for the task. No problems.

**Comment by Deesen** [comment]
I already tried to prepare "elFinder" but its not 100% integrated into MODX yet (thumbnails for example). But with a modern file-manager multifile-uploads will generally be no issue I guess. https://github.com/Deesen/elFinder-for-modx-evo

**Comment by fourroses666** [comment]
Thats KCFinder on steriods :P
I rather have http://modx.im/blog/addons/4693.html responsive filemanager for tinymce4 as filemanager thow.

(This issue I'm talking about the File Management.)
![x](https://cloud.githubusercontent.com/assets/523389/21741460/91a630b8-d4d6-11e6-9579-fa9f9bb6eeb7.jpg)

**Comment by Deesen** [comment]
Ah ok, it should be easy to add it via HTML5 then: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_multiple

Maybe you reopen the issue so it stays on the list.

**Comment by fourroses666** [comment]
Cool

**Comment by Deesen** [comment]
Should work now :-)

**Comment by fourroses666** [comment]
Nice, thanks allot. Have not tested yet but if it doesn't I will reopen!
