### ISSUE TITLE
New "Manage Elements" popup width

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#857]
With new addition of search and help button in elements , the "Manage Elements" popup (tree button) should be wider 

![popup](https://cloud.githubusercontent.com/assets/7342798/19621448/78e75bcc-9892-11e6-8bc5-577e765e5827.jpg)

**Comment by Deesen** [comment]
The width is set here https://github.com/modxcms/evolution/blob/develop/manager/frames/tree.php#L456 . Is replacing 800 by 960 enough?

**Comment by pmfx** [comment]
Fixed in https://github.com/modxcms/evolution/pull/853/commits/6432a59fcecca29d3f6345c4f2e9306adbf39210 https://github.com/modxcms/evolution/pull/853 changed to 960x720

**Comment by Nicola1971** [comment]
ok closed
