### ISSUE TITLE
Sections or Tabs in Plugins and Modules configuration

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#858]
I do not know if we can already do something similiar with the latest json configurations

Would be useful to have "sections" for  long plugin and modules configurations (like QuickManager plugin)

something like this
![plugin-conf2](https://cloud.githubusercontent.com/assets/7342798/19627968/d28b3600-9953-11e6-9687-eb10ebd898ab.jpg)

or with tabs ;) (like categorized tvs)

**Comment by Deesen** [comment]
Yes indeed it would be nice to have more functionality for creating those configuration-forms. Right now "sections" are not possible.

**Comment by Nicola1971** [comment]
has been some improvement with https://github.com/modxcms/evolution/issues/867

i can close this for now
