### ISSUE TITLE
User Date Birth datepicker starts from 2006

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#859]
Just for young people? :D

I feel so old
![birth](https://cloud.githubusercontent.com/assets/7342798/19656638/1a330fdc-9a21-11e6-8800-c36d25a88f7d.jpg)

**Comment by Deesen** [comment]
System Config -> Interface -> Datepicker-Offset ;-)

**Comment by Nicola1971** [comment]
..and so senile :) 
closed
