### ISSUE TITLE
evo 1.1 - double "?" issue when creating urls with furls off

### ISSUE THREAD

**Issue by Breezer** [modxcms/evolution#860]
I use the following code to create urls:
`$xforum['url_sep'] = ( $modx->isFrontend() ? ( $modx->config['friendly_urls'] =='0' ? '&' : '?' ) : '&' );`

In evo 1.1, this only works if furls are enabled. Disabling furls ends up with urls like this:
index.php?id=4?xid=1

In all previous versions the above code works fine with or without furls.

**Comment by Deesen** [comment]
Without seeing code its hard. I guess you know/tried it all yourself but: Is `$modx->config['friendly_urls']` defined? Or does it hold '0' but you still get '?' / false as result?

Just out of interest.. same issue when you switch 0 with 1?

    $modx->config['friendly_urls'] =='1' ? '?' : '&'

**Comment by Breezer** [comment]
I tracked it down to makeURL(), passing aruments does not work in the following situation with furls off:
`$title_link ='<a href="'.$modx->makeUrl( $last['uparent'],'',$xforum['url_sep'].$last_link ).'">'.$last['title'].'</a>';`

Removing the arguments works:
`$title_link ='<a href="'.$modx->makeUrl( $last['uparent'] ) . $xforum['url_sep'].$last_link.'">'.$last['title'].'</a>';`

The following also works:
`$title_link ='<a href="[~'.$last['uparent'].'~]'. $xforum['url_sep'].$last_link.'">'.$last['title'].'</a>';`

**Comment by Deesen** [comment]
My testcase with latest DEV (not 1.1..) :

	$last_link = '&lastlink=99';
	$last['title'] = 'lastTitle';
	$xforum['url_sep'] = ( $modx->isFrontend() ? ( $modx->config['friendly_urls'] =='0' ? '&' : '?' ) : '&' );

	$title_link ='<a href="'.$modx->makeUrl( 33, '', $xforum['url_sep'].$last_link ).'">'.$last['title'].'</a>';

	$output  = 'fURL = '.$modx->config['friendly_urls'];
	$output .= "\n";
	$output .= 'sep = '.$xforum['url_sep'];
	$output .= "\n";
	$output .= $title_link;

	return $output;

outputs for me 

fURL = 0
sep = &
<a href="/index.php?id=33&lastlink=99">lastTitle</a>

**Comment by Deesen** [comment]
BTW there is no need to add a "url_sep" as it is managed by makeURL() https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L2796-L2806

**Comment by Deesen** [comment]
Issue solved or are you having still trouble? Or is it required to use MODX 1.1 to help you out?

**Comment by Breezer** [comment]
I decided that in my case I didn't require makeURL(), I used the third solution I posted above. Thanks for the help though :)
