### ISSUE TITLE
Idea: Show "locked"-symbol with user-info in tree

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#862]
Its already working except "auto-update" and only some lines of code..

![tree-lock](https://cloud.githubusercontent.com/assets/8569221/19717697/252bb942-9b62-11e6-8f8a-211989826394.png)

**Comment by pmfx** [comment]
Interesting. Locker icon could be placed before title cause with long titles it would be invisible.

**Comment by Deesen** [comment]
For visual impression:

![tree-lock2](https://cloud.githubusercontent.com/assets/8569221/19718173/7b7f56da-9b64-11e6-83ec-01be16f51792.png)

**Comment by fourroses666** [comment]
Very nice idea, I like it. 

Don't know a good place for it and how, but I would like to have the "Remove unlocks" button somewhere directly accessable. So I don't have to tell my clients they need to go to tab Tools > Remove Unlocks to unlock. Don't you guys?

**Comment by Deesen** [comment]
Or make the lock-icon clickable if "remove locks" permission is given, so you can remove just this resource´s lock, not all.

**Comment by bossloper** [comment]
Are we a small step from allowing individual resource unlock vs needing to unlock all?

Plus I cannot remember, is there a specific remove locks permission for manager?

**Comment by pmfx** [comment]
@bossloper yes there is permission for this:

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/19721607/4a6c33a6-9b73-11e6-9fc5-eeebdb0bd976.png)

**Comment by Deesen** [comment]
@bossloper With latest commit, when you click on lock-icon and resource could be successfully unlocked, the icon fades out. Otherwise javascript-alert with error-message appears.

**Comment by bossloper** [comment]
Sounds good! I'm just not in a position to test the latest and greatest this week.

**Comment by bossloper** [comment]
When there is a lock message popup the message is repeated in the background. Also might be good to trigger a tree refresh after a lock message like this as it would be likely they clicked on a locked resource because their site free needs a refresh to show current locks.

![untitled](https://cloud.githubusercontent.com/assets/1744687/20479300/99416516-afd5-11e6-9a69-3e3c681a6514.jpg)

**Comment by Fr3ddy7** [comment]
not show for manager rule, just for admin (last from git)

and manager have error before dashboard "Parse error: syntax error, unexpected ';' in /home/xxxxxxx/public_html/manager/includes/document.parser.class.inc.php(1185) : eval()'d code on line 1"

**Comment by Fr3ddy7** [comment]
ohh ) "show locks", now its work, but error before dashboard "Parse error: syntax error, unexpected ';' in /home/xxxxxxx/public_html/manager/includes/document.parser.class.inc.php(1185) : eval()'d code on line 1"
