### ISSUE TITLE
Parse Error "date(): It is not safe to rely on the system's timezone settings..."

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#863]
Sometimes on some servers I have this error in system-log even when setting timezone in [htaccess](https://github.com/modxcms/evolution/blob/develop/ht.access#L8). And sometimes I had to manually add `date_default_timezone_set('Europe/Berlin')` to both index.php to get MODX working.

In `class.phpmailer.php` I found the following piece of code:

```
date_default_timezone_set(@date_default_timezone_get());
```

Does it make sense to add it to documentParser `__construct();` before loading DBAPI to generally avoid this issue?

Full error-msg: date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead

**Comment by Deesen** [comment]
Nobody else facing this issue? Maybe a new configuration-setting for enable/disable `date_default_timezone_set()` makes sense?

**Comment by bossloper** [comment]
I did a few years ago and think adding default to .htaccess fixed it. My current server has it set somewhere in the default php setup 'WHM' and 'PHP Configuration Editor'.

**Comment by pmfx** [comment]
I always have to add **php_value date.timezone 'Europe/Dublin'** to .htaccess for Irish MODX sites to work. Error otherwise.

**Comment by Deesen** [comment]
Ok thanks.. it seems some (cheap?) servers do not allow setting timezone via htaccess. But looking into core-code I´m not sure where is best place to add `date_default_timezone_set()` and how to make it configurable. I guess it has to be added to install-processor so it can be added to config.inc.php before the first `$modx->db->connect()` which triggers the error in my cases.

If nobody else has serious issues with it I guess its ok to wait. In case it becomes a problem, it seems adding `date_default_timezone_set(@date_default_timezone_get());` to document.parser as fallback will avoid it. While the timezone **can still be set via htaccess**!
