### ISSUE TITLE
Evobabel и 1.2-d8.1.4 передача параметров модуля Evobabel

### ISSUE THREAD

**Issue by SebastianoFereiro** [modxcms/evolution#865]
Добрый день, обновил сегодня версию 1.2-d8.1.4, но вот завести работу
evobabel-0.2 - плагина evoBabelPlaceholder и [+switchLang+] не могу
подробнее здесь описывал
dmi3yy/modx.evo.custom#354
возможно, я что-то не учел (полная переустановка плагина, а так же попытка потанцевать с последовательностью настройки не помогла)
примечание: создание языковых версий работает штатно.

**Comment by dmi3yy** [comment]
На днях проверю  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 11:55, SebastianoFereiro написал:

**Comment by dmi3yy** [comment]
Просьба проверить надеюсь будет работать теперь 
https://github.com/modxcms/evolution/commit/3c1e4c9bec5e02171cfd0abad3e22a3df234d55e

**Comment by SebastianoFereiro** [comment]
Проверил, без изменений (тестировал с полной переустановкой плагина)

**Comment by dmi3yy** [comment]
Исправил наконецто :) 
работает 
http://take.ms/xkm5K
ща будет релиз

**Comment by Deesen** [comment]
@dmi3yy @yama Just for your info: I found this commit of 15.10.2016 which has removed the check I added yesterday again: https://github.com/modxcms/evolution/commit/61884d5cef84e8178b3144384b17d955d42b8dfc

**Comment by dmi3yy** [comment]
there were two mistakes: it is a problem with empty values, and when they received the general parameters we get in the variable json 2 instead of 1, and it was not parse to array

Отправлено с iPhone

**Comment by SebastianoFereiro** [comment]
Извините еще раз, после обновления document.parser.class.inc.php получаю
 (если cобытие OnWebPageInit убрать, ошибки нет, но и плагин соответственно не пашет)
Error : Invalid argument supplied for foreach()
Error information	
ErrorType[num]	WARNING[2]
File	/manager/includes/document.parser.class.inc.php(1196) : eval()'d code
Line	101
Current Plugin	evoBabel(OnWebPageInit)

Basic info	
REQUEST_URI	*
Resource	[1] *
Referer	
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
IP	*
Current time	2016-10-28 12:41:38

Benchmarks	
MySQL	0.0160 s (9 Requests)
PHP	0.0280 s
Total	0.0440 s
Memory	1.7656326293945 mb

Backtrace
DocumentParser->executeParser()
index.php on line 154
DocumentParser->invokeEvent('OnWebPageInit')
manager/includes/document.parser.class.inc.php on line 1992
DocumentParser->evalPlugin(string $var1, array $var2)
manager/includes/document.parser.class.inc.php on line 4029
eval()
manager/includes/document.parser.class.inc.php on line 1196

**Comment by Deesen** [comment]
Perfect timing, right today I need evoBabel for a new website. Let´s see...

**Comment by dmi3yy** [comment]
test site   8.1.5 + evobabel )  
http://site7.div.net.ua/manager/
admin
123456


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 28 октября 2016 г. в 12:48, SebastianoFereiro написал:

**Comment by Deesen** [comment]
It´s working right? Thanks :-)
