### ISSUE TITLE
i think need switch place for paramets and paramets setting 

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#867]
http://take.ms/DzcWv

**Comment by Deesen** [comment]
Or maybe move to a new tab, or a button for hide() / show() codemirror?

**Comment by dmi3yy** [comment]
any plugin snippet  modules  

i think  new tab with auto heght will be best solution  

and we stil have bug with  json in parametrs (      

not work  multiPhotos .  but no js error    error in paramets  if    set all params like  
tv, roles, template    - then  all work  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 19:00, Deesen написал:

**Comment by Deesen** [comment]
I need multiPhotos-package for testing. Is this one right? http://extras.evolution-cms.com/ru/packages/gallery/multiphotos.html

**Comment by dmi3yy** [comment]
yes  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 19:07, Deesen написал:

**Comment by dmi3yy** [comment]
problems here:
http://modx.im/blog/fast-solution/4762.html#comment37830


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 19:09, Lukianenko Dmytro написал:

**Comment by dmi3yy** [comment]
need unset   if  parametr not set  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 19:10, Lukianenko Dmytro написал:

**Comment by Deesen** [comment]
Then this issue must have existed before 1.1, there was never unset() but always empty strings like `$templ=""`. In MultiPhotos-plugin line 23-24

    $templ = isset($templ) ? explode(',',$templ) : false;
    $role  = isset($role)  ? explode(',',$role)  : false;

should be

    $templ = isset($templ) && !empty($templ) ? explode(',',$templ) : false;
    $role  = isset($role)  && !empty($role)  ? explode(',',$role) :  false;

**Comment by dmi3yy** [comment]
In all manual and all asset we use

 $templ = isset($templ) ? explode(‘,',$templ) : false;

You can see this in eForm Ditto and others.  

on 1.0.15 all work great.

this bug after do json params.  

We need to make backward compatibility  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 19:53, Deesen написал:

**Comment by Deesen** [comment]
But I guess Ditto doesn´t use simple check like

    if (($templ && !in_array($cur_templ,$templ)) || ($role && !in_array($cur_role,$role))) return;

**Comment by Deesen** [comment]
How to set explicit empty strings then? All empty string-vars then are no more existing. Maybe this could lead to more problems?

**Comment by Deesen** [comment]
I have no clue. I will install 1.0.15 then and see with xdebug what is the exact difference!

**Comment by dmi3yy** [comment]
https://github.com/modxcms/evolution/blob/develop/assets/snippets/breadcrumbs/snippet.breadcrumbs.php#L23-L47
https://github.com/modxcms/evolution/blob/develop/assets/snippets/DocLister/snippet.DocLister.php#L27
https://github.com/modxcms/evolution/blob/develop/assets/snippets/eform/snippet.eform.php#L37-L42

https://github.com/modxcms/evolution/blob/develop/assets/plugins/codemirror/codemirror.plugin.php#L26-L36
https://github.com/modxcms/evolution/blob/develop/assets/plugins/transalias/plugin.transalias.php#L22-L29

in each  snippet plugin we are use this  check

and now we are broken.

need fix in core.   i fix  i know where add some line of code)   

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 20:00, Deesen написал:

**Comment by dmi3yy** [comment]
Pathlogic do this )  
http://take.ms/lkY7W


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 20:05, Deesen написал:

**Comment by Deesen** [comment]
Sorry for the trouble then. I will also look into this if you do not earlier. I am using 1.1 and 1.2 beta for a lot of websites to test and I never had issues like this.

**Comment by Deesen** [comment]
Ok thanks..

**Comment by dmi3yy** [comment]
In my sites i too no have trouble.  
but we use not all assets. Many people use old snippets and  if we are off team then need  backward compatibility.  

for sample now not work  evoBabel.  I thing  its the same bug.  
https://github.com/modxcms/evolution/issues/865


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


четверг, 27 октября 2016 г. в 20:13, Deesen написал:

**Comment by Deesen** [comment]
I guess this is the solution then ;-)

**Comment by Deesen** [comment]
Regarding "Switch place settings".. for 1.2.1 or should we do already for 1.2 ?

**Comment by Nicola1971** [comment]
I've done for plugins and module, if we want for 1.2, i can pull request

Used **$_lang['set_default_all']** for second tab, so no need additional language string

![d e6zd6xon8paaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19815144/cdbd1a84-9d41-11e6-85b7-c4457b9f138a.png)

![yuovvyw00aaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19815139/c8c023c8-9d41-11e6-82b4-49bf8d590cf0.png)

**Comment by dmi3yy** [comment]
Yes this better now 
Need add translate string and add to 1.2 

Отправлено с iPhone

**Comment by Nicola1971** [comment]
a new string instead $_lang['set_default_all']  ?

**Comment by Deesen** [comment]
I also think 

- maybe calling new tab something like "Config String" ?
- "Parse Docblock" makes more sense in tab "general", maybe at bottom as it will only be needed for new elements and "in sight" because of no code existing.. and with code it will be "out of sight" at bottom so cannot be clicked so easily by mistake?
- "Shared Parameters" in tab "configuration" at top
- "Set defaults"-Button into tab "configuration"
- when clicking "update parameter display" it should automatically switch to tab "configuration" first, then update parameters

**Comment by pmfx** [comment]
Yeah, calling tab "Set defaults" dont feel right. Agree with Deesen suggestions.

**Comment by pmfx** [comment]
Maybe call it "Configuration Variables" or "Configuration Source".

**Comment by Nicola1971** [comment]
or just Properties (like in the original code) https://github.com/modxcms/evolution/blob/develop/manager/actions/mutate_plugin.dynamic.php#L500-L501

![m1 jp69dlnplqzdkfosi8un uqn1vvq90fn7rrtxlgltlixhlbqw6v8dgumoqpofhn8aaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19819282/3317181e-9d54-11e6-917c-352ab84b6362.png)

![auwmsjtgor kaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19819287/381d7f10-9d54-11e6-9d85-8f4c2fc886b5.png)

![prop](https://cloud.githubusercontent.com/assets/7342798/19819291/3d24c87e-9d54-11e6-927b-dad1623fdfd6.png)


>when clicking "update parameter display" it should automatically switch to tab "configuration" first, then update parameters

@Deesen  dont know how do it :)

**Comment by dmi3yy** [comment]
nice !  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


пятница, 28 октября 2016 г. в 22:20, Nicola написал:

**Comment by Deesen** [comment]
@Nicola1971 This call selects second tab: `tpSnippet.pages[1].select();` before `showParameters(this)` in line `<input type="button" onclick='showParameters(this)' value="<?php echo $_lang['update_params']; ?>" />`

**Comment by pmfx** [comment]
@Nicola1971 "Properties" or "Parameters" both sounds simple and good to me :)

**Comment by Nicola1971** [comment]
I thought about parameters as first definition. For me it's better than properties.

**Comment by Deesen** [comment]
Considering that this string is called "properties" within the whole MODX-core, maybe this makes most sense. For example in install.tpl-files we find `@internal @properties`. In document.parser functions are called `parseProperties()` and so on. So if the tab and input-field is called the same, its reasonable I guess.

**Comment by Nicola1971** [comment]
ok, properties.

**Comment by Nicola1971** [comment]
Updated modules tabs
Note: modules have already a Properties tabs (is the 4th tab), so i merged and moved some thing to replicate the Plugin tabs layout

**Tab General**:
Moved from tab properties all fields like name, category, disbled, ...
Much better in the first tab like plugin, snippets and chunks
![dyfbjbqqlky3aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19836660/9971166a-9ea7-11e6-958a-07a1b1527aa6.png)

**Configuration Tab**
![paaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19836666/ca6e61b4-9ea7-11e6-9996-3e385f65caa4.png)

New **Properties Tab**
![wmznojpfiqipqaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19836672/ed361e08-9ea7-11e6-8afd-bf8f3389e28a.png)

**Comment by Nicola1971** [comment]
@Deesen i've tried to add your code: jump to the config tab , but does not update parameters.
If you want to add, here the pull https://github.com/modxcms/evolution/pull/876

Sorry, I've had a rude awakening today with the **earthquake** in my town (Rome/Italy).. I am not very shiny today :(

**Comment by Nicola1971** [comment]
restyled set default as a primary button

![iiaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19838136/0ddaaf36-9ec9-11e6-842b-50a8797427cc.png)

**Comment by Nicola1971** [comment]
move Module usergroup access to new Access Permission tab

![whmj3qezug6iqaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19838219/ec137e9e-9eca-11e6-8050-d1b46f6b65fe.png)

**Comment by pmfx** [comment]
Good work Nicola. There was a mess in modules tabs and now it looks a lot better.

**Comment by Deesen** [comment]
@Nicola1971 I will check tab-switch later myself now that it is merged. And I hope bad news are limited to your awakening only!

**Comment by Deesen** [comment]
@Nicola1971 For your info, I added the `tpSnippet.pages[1].select();` now.

**Comment by Nicola1971** [comment]
great, i will test very soon

>  And I hope bad news are limited to your awakening only!

mainly fear for friends and family, but we are all fine. Thanks ;)

**Comment by Nicola1971** [comment]
@Deesen have you changed set defaults buttons style? now are smaller in plugins config than module config

**Comment by Deesen** [comment]
Thanks there is still some dirt to clean indeed..

**Comment by Deesen** [comment]
And I changed to small buttons because with many parameters the screen is almost full of buttons.

**Comment by Nicola1971** [comment]
I understand, but we don't have this kind of buttons in the rest of manager and looks a bit weird.
We can try with a default white (outlined) button, should look lighter

Or replace with a white button with a reset icon.

In my option, although we have not yet a responsive manager, we should use more touchable elements, at least for tablets.
Any manager UI update should be a step forward for the next responsive manager. for not doing the same things over again in a few months

**Comment by Deesen** [comment]
Then please feel free to optimize! I just did not like having almost green background because of so many big green buttons, which nobody needs most of the time.

**Comment by Deesen** [comment]
Maybe you guys have a good idea how to redesign this configuration-table so we can have Label, most kinds of inputs with 100% width (not 80% inputs & textarea like now) and the "Set default"-button sitting at the right place. Maybe just an icon after label is enough?

**Comment by Nicola1971** [comment]
@Deesen 

![0xkkgfikaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19890685/a17cecc6-a03c-11e6-9513-c5439fc6c913.png)

**Comment by fourroses666** [comment]
Much better!

**Comment by Deesen** [comment]
I knew it :-)

**Comment by Nicola1971** [comment]
done modules too.
restyled a bit table borders to make it more similiar to System Settings 

![4jhqkongaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19893637/246c91ec-a04a-11e6-8274-dab5ac544689.png)

https://github.com/modxcms/evolution/pull/891

**Comment by Deesen** [comment]
Nice, thank you!

**Comment by fourroses666** [comment]
Do you guys think that info text should be hidden and click on the title it should collapse?
Would "compress"  the page allot.

**Comment by Nicola1971** [comment]
@fourroses666 , nice suggestion but we need to clean up the code before any addiction to this page - it's an HTML code nightmare from ten years ago :)
Just an example of the code: the config parameters table is inside another table with only one TD with col span....
10 year ago table styles: previous grey tables borders ..was not borders, but col-space and greys is background of container table TD.

Working on this file is a jump back in HTML table days :)

**Comment by pmfx** [comment]
Yeah, it's pretty bad hehe.

**Comment by fourroses666** [comment]
Hard to style that yea. 👎
