### ISSUE TITLE
multitv sorter in datatable mode 

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#869]
need
http://take.ms/XCiBE

have
http://take.ms/t1hVT

**Comment by Nicola1971** [comment]
Multitv need restyling to fit latest evo look.

I use multitv with 100% of my projects, but forms looks a bit ugly.

**Comment by Deesen** [comment]
@dmi3yy Are you missing the sort-button? In `dbtabledemo.config.json` must be set at bottom

    "configuration": {
        "radioTabs": 0,
        "sortindex": "id"
    }

as per http://jako.github.io/multiTV/template_variable/#other-options . And I am not sure why but it seems a check for `'dbtable'`is missing in [multitv.class.php line 533](https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/includes/multitv.class.php#L533) . It should be

    if (!$this->configuration['sorting'] && $this->display == 'datatable' || $this->display == 'dbtable') {

Maybe it helps?
