### ISSUE TITLE
Chunk with parameters drops placeholders defined before chunk

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#874]
Have issue with #625 

**Placeholders defined before chunk are missing inside this chunk when it have a parameter.**

![2016-10-29-21-21-23](https://cloud.githubusercontent.com/assets/10888055/19832213/adb23134-9e1d-11e6-9407-7a3a301c3da8.png)

When I call chunk **{{chunktest}}**, [+before_chunk_placeholder+] **inside** chunk is OK and value is visible.

When I call chunk **{{chunktest?&chunk_placeholder='Im chunk placeholder'}}**, [+before_chunk_placeholder+] **inside** chunk is empty.

**Comment by Deesen** [comment]
Ok I can recreate that issue and will look into it.

**Comment by Deesen** [comment]
If I change `'hasModifier'` to `false` both placeholders are working -> https://github.com/modxcms/evolution/blob/develop/manager/includes/document.parser.class.inc.php#L1044

@yama Is this a fix or does it break other functionality?

**Comment by Deesen** [comment]
@pmfx As stated in Slack I checked myself again and also with yama. It seems this issue is solved, I cannot recreate it using the same test-case as 1 month ago.

**Comment by yama** [comment]
> inside chunk is OK and value is visible.

I can not understand this part well. "value is visible"?

**Comment by Deesen** [comment]
@pmfx Please correct me if I am wrong. My test-case for this issue:

Chunk "chunkph":
----------------

<p>
	in chunk: [+chunk_placeholder+]<br/>
	before chunk: [+before_chunk_placeholder+]
</p>



Snippet "setPlaceholder":
-------------------------

$modx->setPlaceholder($placeholder, $content);



Content of my test-resource:
-------------------------

[[setPlaceholder?&placeholder=\`before_chunk_placeholder\` &content=\`this is content for ph before_chunk_placeholder\`]]


**chunk_placeholder is parsed, before_chunk_placeholder is NOT**  
{{chunkph?&chunk_placeholder=\`chunk_placeholder\`}}


**chunkph - before_chunk_placeholder is parsed**  
{{chunkph}}

**Comment by yama** [comment]
It is not linked with setPlaceholder. I will improve it later.

**Comment by pmfx** [comment]
Just tested it and works great now. Thanks! Closing.
