### ISSUE TITLE
multitv error in console

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#883]
last evo from git

in chrome 
![11111](https://cloud.githubusercontent.com/assets/8958344/19859220/2e7c6ecc-9f8d-11e6-928d-8a06b90946fa.jpg)

dont work save in datatable config

**Comment by Fr3ddy7** [comment]
in firefox all ok

**Comment by Deesen** [comment]
Somehow www. and none www. URLs are mixed up as you can see in screenshot. Forcing to www. or without www. via normal .htaccess should help already.

**Comment by Deesen** [comment]
https://github.com/modxcms/evolution/blob/develop/ht.access#L18-L22

**Comment by Fr3ddy7** [comment]
yeah thnx)

automatic redirection does not work for a folder /manager, how to be if everywhere in the www ?manager can write with hands without www & have some errors

**Comment by Deesen** [comment]
Not sure I understand. You can put a redirection into /manager/.htaccess to force www. or none-www.

**Comment by Fr3ddy7** [comment]
ok)

i make 

# Rewrite domain.com -> www.domain.com -- used with SEO Strict URLs plugin
RewriteCond %{HTTP_HOST} !^$
RewriteCond %{HTTP_HOST} !^www\. [NC]
RewriteCond %{HTTP_HOST} (.+)$
RewriteRule ^(.*)$ http://www.%1/$1 [R=permanent,L] . 

but redirect work to main page, not to manager folder with www

**Comment by Deesen** [comment]
I always work with subdomains (like dev.subdomain.de) if possible so I sometimes have the problem getting redirected like www.dev.subdomain.de. To avoid this I remove all www in manager/.htaccess:

    RewriteEngine On
    RewriteBase /

    # without www all domains
    RewriteCond %{HTTP_HOST} .
    RewriteCond %{HTTP_HOST} ^www.(.*)$ [NC]
    RewriteRule ^(.*)$ http://%1/$1 [R=301,L]

If that does not work for you, someone with more experience has to help you out.
