### ISSUE TITLE
TinyMCE4 Custom Style Formats 

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#886]
For TinyMCE4 plugin I am looking at the 'Custom Style Formats' parameter. These custom styles only seem to apply to a block level element? 

I.e. I'm trying to reproduce the 'CSS selectors' option from TinyMCE3 plugin where the styles will place a span around selected text. However if I select a word within a paragraph and apply one of the custom styles (for example) then it applies the style (cssClass) to the paragraph and not the selected text. Is there a way to add inline custom styles to the TinyMCE4 plugin?

**Comment by Deesen** [comment]
Do you mean this option? https://www.tinymce.com/docs/demo/format-custom/

**Comment by Deesen** [comment]
TinyMCE4 supports these options:

- https://www.tinymce.com/docs/configure/content-formatting/#block_formats
- https://www.tinymce.com/docs/configure/content-formatting/#style_formats

**Comment by bossloper** [comment]
Yes, the 'Custom Style Formats' for TinyMCE4 seems to give a block format?

I'm looking to emulate the inline format from TinyMCE3 'CSS selector' in 'Interface & Features'.

Which is your second link: https://www.tinymce.com/docs/configure/content-formatting/#style_formats ... 
But how to set that up via the MODX TinyMCE4 plugin parameters or 'Interface & Features'?

**Comment by Deesen** [comment]
I already tried to prepare documentation for Tiny4.. this is a part of it. Would be great to know if it already helps in your case or if I need to clarify some details.

### Custom themes

All themes are located in directory `assets/plugins/tinymce4/theme`. The base-theme `theme.tinymce4.base.inc.php` will always be loaded to set all nessecary base options. All other themes are meant to customize the base-theme. Select your theme within Modx-configuration.

To create your own custom theme, duplicate one of the other themes/files and customize it per your needs. Within a theme editor-options are set like

    $this->set('parameter', 'value', 'type');

#### Example "custom toolbar"

Refering to the TinyMCE4-docs https://www.tinymce.com/docs/configure/editor-appearance/#toolbarn , the parameters are "toolbar1" and "toolbar2". Their type is "string". So inside your theme this example can be achieved with  
 
    $this->set('toolbar1', 'undo redo | styleselect | bold italic | link image', 'string');
    $this->set('toolbar2', 'alignleft aligncenter alignright',                   'string');

To remove a setting completely, set it to NULL:

    $this->set('toolbar1', NULL, 'string');

**Comment by Deesen** [comment]
No it doesn´t help enough. I need to check in detail and let you know.

**Comment by bossloper** [comment]
Thanks for answering your own question :-)
Bottom line just trying to have a custom style format that is applied as a span, as per TinyMCE3 plugin. Current ''Custom Style Formats' in the plugin configuration is applied to the block. I was assuming it could be set via the MODX interface but maybe it needs some theme file magic to achieve.

**Comment by Deesen** [comment]
I think what you need is what I posted first (and deleted..): https://www.tinymce.com/docs/demo/format-custom/

I will try to change Tiny4 so it accepts parameter like in above demo:

![custom_styles](https://cloud.githubusercontent.com/assets/8569221/19867675/07094f78-9fa5-11e6-91d5-0ea3486058d1.png)

**Comment by Deesen** [comment]
Updated the screenshot..

**Comment by bossloper** [comment]
Yes I think that is what I'm after. 
It is about backwards compatibility and not dropping existing functionality as we go forward. I think that goes for all Evo improvements. That way we can keep the user base we have and build on it for the future.

**Comment by Deesen** [comment]
Yes I will take that into account. It should provide format `Title,cssClass|Title2,cssClass` as well as the full format like in screenshot. For your info, the bridge handles this parameter here https://github.com/modxcms/evolution/blob/develop/assets/plugins/tinymce4/bridge.tinymce4.inc.php#L100-L120

**Comment by Deesen** [comment]
Please enjoy :-)

**Comment by bossloper** [comment]
Thanks, works great!
For it to work you need to ensure the 'fully manual' custom style code is wrapped in [ ].
Would it be best to add these automatically?

Also a couple of things relating to the formatting. 

If you use the 'simple' format method e.g. 'Title,cssClass|Title2,cssClass' it automatically infers you want Paragraph, Header 1 - Header 6, Div, Pre adding to the format dropdown list. Are these really needed? There is a 'formatselect' plugin that displays the Paragraph dropdown for selecting these 'block formats' via the MODX Block Formats parameter. 
I also think this 'formatselect' plug should be a default on more of the themes so as to make use of the 'Block Formats parameter'.

I still wonder how many people would use the 'Title,cssClass|Title2,cssClass' method when it does not allow inline styling, it seems very limited. Should the 'simple' 'Title,cssClass|Title2,cssClass' format set up inline formats by default rather than the block level formatting it provides now?

**Comment by Deesen** [comment]
Reg. wrap in [] I thought its even more flexible without forcing [] so you could even add a variable or function now.

And to be honest I do not remember exactly why the "simple format" is that simple. Thinking about it now IMO it is completely useless. If the formatselect-plugin makes that much sense, let´s add it. Have no experience with it.

**Comment by bossloper** [comment]
re: [] Good point.

formatselect is the same plugin used on TinyMCE3, nothing new, and as there is already a MODX parameter for it in the TinyMCE4 'Interface & Features' system config, it seems strange it is not in the plugin list for the themes.

Maybe the 'simple format' can be changed to setup inline formats then? 
That ways it would all reflect more how the existing TinyMCE3 works.

**Comment by Deesen** [comment]
Reg. "formatselect" I missed this button when I ported old Tiny3-themes. I added this button now as per old themes.

Reg. "simple format for inline formats", do you mean changing the list of selectors the css-class is applied to? Actual these are `a,strong,em,p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,tr,span,img`

**Comment by bossloper** [comment]
RE: formatselect - Great!

RE: "simple format for inline formats"
From what I can see the 'simple formats' in the MODX TinyMCE4 plugin are always applied to the parent selector? So effectively only give a block level format. i.e. you cannot select a word within a paragraph and apply one of the 'simple formats'. I was more considering changing them to add a <span> around the selected text to make them more useful.

So from: https://www.tinymce.com/docs/configure/content-formatting/#style_formats
it would mean setting each 'simple format' up using the inline: 'span' option:
{title: 'Example 1', inline: 'span', classes: 'example1'},

**Comment by Deesen** [comment]
Thanks for figuring out!

**Comment by bossloper** [comment]
Are you also taking out the Paragraph Header 1 - 6 etc from the 'simple format' list i.e. lines 105 to 113 of bridge.tinymce4.inc.php ? They are now not needed because of the "formatselect" plugin being added.
