### ISSUE TITLE
Some minor issues with 1.2-RC1

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#888]
1.2-RC1

just updated a site and missing last 2 tabs

![missing-tab](https://cloud.githubusercontent.com/assets/523389/19871738/873f85b6-9fb6-11e6-84ef-2ec456055cb3.jpg)

**Comment by fourroses666** [comment]
oops

**Comment by dmi3yy** [comment]
turn off tinyMCE plugin  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 31 октября 2016 г. в 23:09, Marc написал:

**Comment by fourroses666** [comment]
Yea correct.

**Comment by fourroses666** [comment]
- Can't reach File Manager.
- Images not visible, like; /assets/cache/images/banner/640x-banner2.42d.png

Images are there but not visible, or is it some server issue?

**Comment by dmi3yy** [comment]
check    assets/cache/images/.htaccess

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 31 октября 2016 г. в 23:36, Marc написал:

**Comment by fourroses666** [comment]
correct!

and file manager location not correct its saying

**Comment by fourroses666** [comment]
Ah, had to re refresh manager path. My bad

**Comment by fourroses666** [comment]
Don't know this is a bug:

No output:
```
[*id:is=`5`:then=`[[Ditto? 
&parents=`5`
&total=`all` 
&showPublishedOnly=`1`
&showInMenuOnly=`0`
&orderBy=`menuindex ASC` 
&noResults=` ` 
&tpl=`tpl-blog-overzicht`
]] `:else=``*]
```

After a space before [[Ditto.. it does work:
[*id:is=`5`:then=`  [[Ditto? 

---

Very small detail; File Manager folders has a larger line-height?: Don't know why.
![detail](https://cloud.githubusercontent.com/assets/523389/19875144/91cda0da-9fca-11e6-9ea3-3c79e652f9a2.jpg)

**Comment by Deesen** [comment]
Reg file-manager its strange indeed. I also could not find out where line-height comes from. But for example the table-tag has no cellspacing- or cellpadding-attribute.

Reg. `[*id...*]` I think its a bug. I added another `[*id:is*]` with only "yes" or "no" as result but no output. There is only output if I remove the `[*id:then='[[Ditto...`

My testcase using demo-site is:

    [*id*]<br/>
    [*id:is=`49`:then=`yes`:else=`no`*] <br/>
    [*id:is=`49`:then=`[[Ditto?
    &parents=`2`
    &total=`all` 
    &showPublishedOnly=`1`
    &showInMenuOnly=`0`
    &orderBy=`menuindex ASC` 
    &noResults=`no results` 
    &tpl=`ditto_blog`
    ]]`:else=`else`*]

**Comment by Deesen** [comment]
If I add `table tr td { height:21px; }` to file-manager all row have height 27px. Setting it below 21px there is always some difference like .5px.

**Comment by Deesen** [comment]
I found the reason. Using a snippet call is ok as the snippet-result / return will be rendered first. Means

    [*id:is=`49`:then=`[[Ditto?&tpl='ditto_tpl']]`:else=``*]

will be send to the "is/then/else"-mechanismn like

    [*id:is=`49`:then=`<div class="blogentry">... [!jot?&param=`xy`!] ...</div>`:else=``*]

The first sign after `then=` is the delimiter like " or ' or ´. In this case it is ´. If `{{ditto_tpl}}` now outputs this delimiter-sign like within above snippet-call `[[jot]]`, the filter/modifier-mechanismn gets broken as it will be handled as

    then=`<div class="blogentry">... [!jot?&param=`

It will search for the next `:` to determine the `else` and so on...

**Comment by fourroses666** [comment]
Probably it works when using a chunk instead of the direct snippet call and maybe if? works too.
But I don't understand how can it be possible when I add a simple blank space it does work.

**Comment by fourroses666** [comment]
Reg. the space, I think the image isn't a block/inline-block and adds a 5px at the bottom.

**Comment by Deesen** [comment]
Maybe you can post what the Ditto-snippet itself returns so I can see its exact output.

**Comment by fourroses666** [comment]
Oke, will do. Can't at the moment.

Have another small "issue"  I just noticed. eForm is outputting inputfields before checkboxes/radiobuttons. Maybe this sortorder can be fixed?

![order-eform](https://cloud.githubusercontent.com/assets/523389/19889123/755f239c-a033-11e6-94e6-54611308c902.jpg)

**Comment by fourroses666** [comment]
Need the space to show the ditto.
```
			[*id:is=`5`:then=` [[Ditto? 
				&parents=`5`
				&total=`all` 
				&showPublishedOnly=`1`
				&showInMenuOnly=`0`
				&orderBy=`menuindex ASC` 
				&noResults=` ` 
				&tpl=`tpl-blog-overzicht`
			]]`:else=``*]
```
Chunk:

```
<div class="item" style="float:left; width:20%; padding:15px;">
	<a href="[~[+id+]~]">
		<img src="[[phpthumb? &input=`[+blog-afb1+]` &options=`w=300,h=380,zc=1`]]" />
		<div><h3>[+description+]</h3></div>
	</a>
</div>
```

**Comment by fourroses666** [comment]
Can css be changed please?

For MAC and firefox we need this style:
```
*{
-moz-osx-font-smoothing: grayscale;
}
```

Change password and logout right top are too "bright".
```
#supplementalNav a {
    color: rgba(255, 255, 255, 0.75) !important;
}
```

Codemirror fontsize is a bit big/uge.
```
.CodeMirror {
    font-size: 1.1em;
much nicer ---> font-size: 1em;
}
```

**Comment by pmfx** [comment]
@fourroses666 #895

**Comment by fourroses666** [comment]
Thanks, see some small issue with dutch lang but don't think there is an easy solution.
Probably need to translate that button. Or make it a inline-block but no clear:both after the refreshbutton so still looks weird. 
```
.actionButtons a, .actionButtons li.primary a, .actionButtons a.primary, .actionButtons a.default{
    display:inline-block;
}

```
![dutch-lang](https://cloud.githubusercontent.com/assets/523389/19910273/4795dd94-a08c-11e6-9eee-76c4237c1e41.jpg)

**Comment by Deesen** [comment]
Reg. "space to show ditto" I used your chunk but no change. Even with space I have no output.

**Comment by fourroses666** [comment]
Hmm, thats weird. It really does work with space (or character) with me.
Maybe its not meant to use snippets into the "parameters?". (Or my PHx plugin is different?)
Probably will work without any space when using a chunk for the Ditto call. Haven't tried changing it to  DocLister actually. Maybe it does with that.

**Comment by Deesen** [comment]
Your PHx-plugin? I tried it using the new built-in filters, not PHx.

**Comment by fourroses666** [comment]
Ah yea, thought [*id:is=``... uses PHx.
Not sure it did overwrite my PHx settings plugin on Evo update which could be different on my basic installs. Anyway just trying to find the differences why it does work on my install and yours not, its weird. 

Hope to do some more testing this weekend on the latest build to see if there are any issues/bugs.

**Comment by fourroses666** [comment]
Don't know if its already fixed but with the "elements tree" my TV's and (if I'm correct) Plugins are not visible. You can also see it here on this screendump:

![dutch-lang](https://cloud.githubusercontent.com/assets/523389/19910273/4795dd94-a08c-11e6-9eee-76c4237c1e41.jpg)

There are no TV's :o

**Comment by fourroses666** [comment]
I really like the new RC2 theme, no doubt.
I do see there can be done many small design improvements. 

The dashboard uses font-size:13px; 
The manager resources uses font-size:75%;
TinyMCE (4) uses font-size:15px;

I have the best readability when using 10pt. 
All these should be font-size:13px or 10pt.

I would have added some pull requests if I had some time to do it.

When I have some spare time ( and internet at home, broken router 👎 ) I would like to make a new style for TinyMCE4 and also the KCFinder to look like it belongs to the manager theme.

**Comment by Deesen** [comment]
Are your TVs back like mentioned in https://github.com/pmfx/ElementsInTree/issues/19?

The theme is indeed great :-). Reg. font-sizes, I leave that up to you guys. But an exclusive Tiny4-theme / KCFinder-theme sounds nice!
