### ISSUE TITLE
[enhancement] Actions in Manage Elements

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#894]
Just done in my fork - what do you think?
works with permissions in templates, tvs, chunks, snippets and plugins.

+a bit of restyling and a little hover on elements

https://youtu.be/J-wVlhu4tmM

![gkmlyshg0kaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/19900565/477c56c6-a064-11e6-95bc-92264b1e4747.png)

**Comment by pmfx** [comment]
Yes! I like it and want it! Good work man. Duplicating and Deleting (critical) would need to have a confirmation popup.

**Comment by Nicola1971** [comment]
Yes, delete need a confirmation, but not sure for duplicate (2 clicks with confirm: the same of open resource and duplicate).
The duplicate button is usefull because is faster 

Anyway, not for 1.2

**Comment by pmfx** [comment]
There is confirmation popup on duplicate (when editing) so it should be on the list too. To have consistency and dont surprise user. Even with popup there will be less clicking.

**Comment by Nicola1971** [comment]
Should be nice, for the next release, add "fast action buttons" in whole manager: manage elements, manage users, manage web users...
Waiting @Deesen manager API, for a more cool manage documents and users.

**Comment by fourroses666** [comment]
Nice Nicola

**Comment by Nicola1971** [comment]
@pmfx you're right, but we need something to improve speed in manager actions:
- duplicate elements is very slow - to much step and a lot of issue (i.e.: tvs does not update name, just description - so error message: still exist resource with this name...bla bla..
- I always dreamed bulk actions with checkbox to delete mass resource or users.
I.e.: when I change template to an old site, I need to delete a lot of elements from old template.

about elements > combined view

 "delete" (category) in combined view tab should be moved somewhere...
Somewhere you can choose to delete children elements too.:)
maybe in next manage category module @Deesen ?

**Comment by Deesen** [comment]
Yes we can add a feature like that. But as you mentioned a sensitive topic like "changing templates on old sites", IMO this is one of the bottlenecks of MODX as it can become quite complicated having old and new elements listed when the list is long. And IMO deleting whole category with its elements requires 3x "Are you sure?"-confirmation or an auto-backup function :-D ..

I think this deserves some brainstorming about how to reach simplifying this procedure as good as possible. Maybe for example it makes sense to be able to enable/disable chunks first, before deleting them? Maybe also for snippets for easier debugging or whatever?

**Comment by pmfx** [comment]
@Nicola1971 I agree. Bulk actions (checkboxes on left, actions on top) would be the perfect solution. This should be tagged as a priority. Sometimes there is a lot of stuff to delete and I have a "clickathon".

@Deesen I like idea of disabling elements (possibly along with bulk actions). Roght now the only way to semi-do-it is to change element name. A little awkward if you ask me :)

**Comment by Deesen** [comment]
I mean the category manager will already help A LOT to categorize old and new elements so I´m not sure which is best approach.

Maybe a new system-setting would also be practical to enable logging when "disabled chunks" have been called, and from where. Just brainstorming..

**Comment by Nicola1971** [comment]
> And IMO deleting whole category with its elements requires 3x "Are you sure?"-confirmation or an auto-backup function :-D

* Are you sure? 
* Are you really sure? 
* Seriously, you really want to delete all these elements? :-D

"bulk actions" could be a separate page/module, for security reason and because is not an everyday routine :)
idea: "bulk actions" in DocManager? it makes sense to me

**Comment by pmfx** [comment]
>"bulk actions" could be a separate page/module, for security reason and because is not an everyday routine :)

Not really. I think that adding new role permission like "elements_bulk_actions" would do the job. If role has permission, user will see checkboxes and actions.

**Comment by Nicola1971** [comment]
yes, nive idea @pmfx 
I had thought about something like this for Actions in Manage Elements, we could add a new seto of permission, to restict the use.
ie:
- allow elements toolbar: edit, duplicate, delete buttons, next elements list
- allow elements bulk actions: mass delete/disable

**Comment by Nicola1971** [comment]
Finished and works nice:
https://youtu.be/Kg_5-ut10a0

* new add/duplicate/delete button with roles control in Manager Elements tabs
* confirm window for duplicate and delele buttons
* some css restyle to elements list
* added button style to detete category button 
* added missing confirm window to detete category button 
* new language string confirm_delete_category

**Comment by pmfx** [comment]
Great work Nicola!

**Comment by Nicola1971** [comment]
@Deesen @pmfx @fourroses666 @dmi3yy @yama @Fr3ddy7 .... all :)
More elements view options:

default view
![list](https://cloud.githubusercontent.com/assets/7342798/22383743/5900c46c-e4cb-11e6-9acf-abf0c50675fa.png)

no buttons
![no-buttons](https://cloud.githubusercontent.com/assets/7342798/22383748/6012b256-e4cb-11e6-958b-8453a7ddccc5.png)


no description
![no-descr](https://cloud.githubusercontent.com/assets/7342798/22383751/637e57ec-e4cb-11e6-85cb-657815209f32.png)


inline
![inline](https://cloud.githubusercontent.com/assets/7342798/22383759/66e5032c-e4cb-11e6-8511-b8c601a5b6d6.png)

**Comment by Nicola1971** [comment]
I'm not sure if is **usefull** of "**too much**" :)

So, please test

Actually i have found only a couple of styling issues:

* a bit of overflow in "inline" view, when there are a lot of elements
* checkbox/radio next to the filter and buttons, could cause some layout issue on small monitors (perhaps it is best under?)

To do 
* better styling
* language strings for checkbox/readio labels

It's in a dedicated branch:
https://github.com/Nicola1971/evolution/tree/Manage_Elements

**Comment by Deesen** [comment]
Already checked it and I like the usability. Of course it needs a "remember setting" function via localStorage (I can take care). And I would love to have multi-column / flexbox display additionally to "inline". Would be great mix of list & inline.
