### ISSUE TITLE
output current plugin id

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#896]
Should be nice add to some Manager plugins and modules, a small link (maybe a font awesome icon) to the config tab in plugin settings page.

Anyway, i never found a way to output the current plugin id (for the path).
there is an old topic on modx forum
https://forums.modx.com/thread/96413/output-current-plugin-id

is possible?

**Comment by Deesen** [comment]
No it is not, the SQL-ID of plugin is not saved anywhere in the actual core. What do you mean by "path"? Why do you need it?

**Comment by Nicola1971** [comment]
> What do you mean by "path"? Why do you need it?
@Deesen to get a link to the plugin config page, i try to explain with a picture:

![widget-set](https://cloud.githubusercontent.com/assets/7342798/19928992/6cdb0b40-a101-11e6-9a59-4388ab4bc09b.jpg)

**Comment by Deesen** [comment]
Got it! Needs some update in core.

**Comment by Nicola1971** [comment]
should be nice, now that we have an Information tab and a more clean and understandable Config tab :)

**Comment by Deesen** [comment]
Until then you can add this code to a plugin to get its id:

    $result = $modx->db->select('id', $this->getFullTableName("site_plugins"), "name='{$modx->event->activePlugin}' AND disabled=0");
    $pluginid = $modx->db->getValue($result);

**Comment by Deesen** [comment]
In future it should be possible to simply use `$modx->event->pluginId` which is a cleaner solution than an extra sql-query.

**Comment by Nicola1971** [comment]
thanks @Deesen i will test soon

**Comment by Nicola1971** [comment]
`index.php?id='.$pluginid.'&a=102`

works :) Thanks @Deesen !
need to find a way to open the right tab 

something like:

`index.php?id='.$pluginid.'&a=102#tabConfig`

but it's ok for now
