### ISSUE TITLE
Only UTF8 Collations on fresh install

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#897]
I thought it was a problem with mine localhost wamp, but I also tried with two remote servers.
Cant set Latin or other collation, I can choose only UTF8 collations

![utfonly](https://cloud.githubusercontent.com/assets/7342798/19926329/415d638a-a0f4-11e6-9035-9fb2cf523f0d.jpg)

**Comment by Nicola1971** [comment]
it's a recent issue, because everything worked when i updated and tested install with the new Bootstrap template (done a lot of clean install test)

i dont understand much about it, but could be something related to this commit? https://github.com/modxcms/evolution/commit/30ba7dde29abac0a71d608949e9181b4800e75bb @yama ?

**Comment by Nicola1971** [comment]
confirm: tested with a previous version of connection.collation.php, works with all a collations

**Comment by yama** [comment]
OK, I will repair this issue at  later.

**Comment by Nicola1971** [comment]
all collactions are back. Thanks @yama
