### ISSUE TITLE
not work OnFriendlyURLSettingsRender

### ISSUE THREAD

**Issue by saniock** [modxcms/evolution#901]
`global $modx;
$e = $modx->Event;

if ($e->name == 'OnFriendlyURLSettingsRender' && $modx->getPlaceholder('canonical') == ''){
	$tv_id_save = 65; // ID ТВ для сохранения значений
	
	// если данная страница есть в настройках
	$sql = "SELECT value FROM ".$modx->getFullTableName("site_tmplvar_contentvalues")." WHERE contentid = '1' AND tmplvarid = '".$tv_id_save."'";
	$res = $modx->db->query($sql);
	
	// если есть
	if ($line = $modx->db->getRow($res)){
		$uri = urldecode($_SERVER['REQUEST_URI']);
		$modx->setPlaceholder('current_uri', $uri);
		if(preg_match('#^([^\?]*)(\?.*)?$#', $uri, $matches)) {
			$path = explode('/', $matches[1]);
			foreach($path as $i => $step) {
				if(in_array($step, array('', 'index'))) {
					unset($path[$i]);
				}
			}
			$gets = explode('&', substr($matches[2], 1));
			foreach($gets as $i => $get) {
				if(in_array($get, array('f[8][]=0', 'f[1][]=0', 'f[6][]=0', 'f[24][]=0', /*'fii=43',*/ 'page=1', ''))) {
					unset($gets[$i]);
				}
				elseif(preg_match('#^f\[\d+\]\[m(in|ax)\]=$#', $get)) {
					unset($gets[$i]);
				}
				else {
					$gets[$i] = str_replace(' ', '+', $get);
				}
			}
			$filters = array();
			$filtered_path = $path;
			$params = array();
		}
		$tmp = unserialize($line['value']);
		// прохожу по значениям
		foreach ($tmp AS $key => $value) {
			// если не доп. параметр
			if (!strstr($key, '__') AND $value AND $key != 'id' AND $key != 'save') {
				// проверяю есть ли это в строке запроса
				$str = mb_stripos($_REQUEST['q'], $value, 0, 'UTF-8');
				
				// и это не мин и макс
				if ($str !== false) {
					$find = array_search($value, $filtered_path);
					if($find !== false) {
						if(preg_match('#^f\[(\d+)\]\[\]=(.*)$#', $tmp[$key.'__to'], $m)) {
							$filters[$m[1]][] = str_replace('+', ' ', $m[2]);
							$params[$m[1]][] = $find;
						}
						else {
							$m = explode('=', $tmp[$key.'__to']);
							$_REQUEST[$m[0]] = $_GET[$m[0]] = $m[1];
							if($m[0] == 'fii') {
								$category = 'fii';
							}
						}
						unset($filtered_path[$find]);
					}
				}
			}
			elseif(!empty($gets) && preg_match('#__to$#', $key)) {
				$find = array_search($value, $gets);
				if($find !== false) {
					$path[] = $tmp[substr($key, 0, -4)];
					unset($gets[$find]);
				}
			}
		}
		if(!isset($category) && empty($filtered_path)) {
			$_REQUEST['fii'] = $_GET['fii'] = 43;
		}
		if(isset($_GET['min'])) {
			$filters[$_GET[$category]]['min'] = $_GET['min'];
		}
		if(isset($_GET['max'])) {
			$filters[$_GET[$category]]['max'] = $_GET['max'];
		}
		if(empty($filtered_path) || $filtered_path === array(1 => 'stomatologii') || $filtered_path === array(1 => 'specialisty')) {
			$allowed_filters = array(1, 6, 24);
			if($filtered_path[1] === 'stomatologii') {
				$allowed_filters = array(1, 6, 8, 24, 30, 53);
			}
			elseif($filtered_path[1] === 'specialisty') {
				$allowed_filters = array(1, 6, 13, 24, 30);
			}
			foreach($params as $i => $steps) {
				if(!in_array($i, $allowed_filters)) {
					foreach($steps as $step) {
						unset($path[$step]);
					}
				}
			}
			$all_filters = $checked_filters = $categories = array();
			foreach ($tmp AS $key => $value) {
				if (!strstr($key, '__') AND $value AND $key != 'id' AND $key != 'save') {
					if(preg_match('#^f\[(\d+)\]\[\]=(.*)$#', $tmp[$key.'__to'], $m)) {
						$name = str_replace('+', ' ', $m[2]);
						$id = intval($m[1]);
						$all_filters[$id][] = array($value, $name);
						if(in_array($value, $path)) {
							end($all_filters[$id]);
							$checked_filters[$id][key($all_filters[$id])] = $name;
						}
					}
					else {
						$m = explode('=', $tmp[$key.'__to']);
						if($m[0] == 'fii') {
							$categories[intval($m[1])] = array($value);
						}
					}
				}
			}
			$result = $modx->db->query("SELECT id, caption FROM ".$modx->getFullTableName('site_tmplvars')." WHERE category=15");
			while($row = $modx->db->getRow($result)) {
				$categories[intval($row['id'])][1] = $row['caption'];
			}
			$_REQUEST['all_filters'] = $_GET['all_filters'] = $all_filters;
			$_REQUEST['checked_filters'] = $_GET['checked_filters'] = $checked_filters;
			$_REQUEST['categories'] = $_GET['categories'] = $categories;
			$underground = array();
			$result = $modx->db->query("SELECT id, name FROM ".$modx->getFullTableName('city')." WHERE hide=0");
			while($row = $modx->db->getRow($result)) {  
				$underground[intval($row['id'])]['name'] = $row['name'];
			}
			$result = $modx->db->query("SELECT parent_id, id, name FROM ".$modx->getFullTableName('street')." WHERE hide=0");
			while($row = $modx->db->getRow($result)) {
				$parent = intval($row['parent_id']);
				if(isset($underground[$parent])) {
					$underground[$parent]['children'][intval($row['id'])] = $row['name'];
				}
			}
			$_REQUEST['underground'] = $_GET['underground'] = $underground;
			
			$_REQUEST['f'] = $_GET['f'] = $filters;
			$_REQUEST['q'] = $_GET['q'] = empty($filtered_path)?'':implode('/', $filtered_path).'/';
			$real_uri = $canonical = $paging = (empty($path)?'':'/'.(implode('/', $path))).'/';
			if(!empty($gets)) $real_uri .= '?'.implode('&', $gets);
			if($uri !== $real_uri) {
				$modx->sendRedirect($real_uri, 0, 'REDIRECT_HEADER', 'HTTP/1.1 301 Moved Permanently');
			}
			foreach($gets as $i => $get) {
				if(!preg_match('#^(max|min)=#', $get)) {
					unset($gets[$i]);
				}
			}
			if(!empty($gets)) $paging .= '?'.implode('&', $gets);
			$modx->setPlaceholder('canonical', $canonical);
			$modx->setPlaceholder('paging', $paging);
		}
	}
}`

**Comment by Deesen** [comment]
I guess wrong event? No array is returned for display -> https://github.com/modxcms/evolution/blob/develop/manager/actions/mutate_settings.dynamic.php#L886
