### ISSUE TITLE
Manager Screendump on Github project page

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#905]
I always like to see whats it about. When looking for a CMS it would be nice to see how the Manager looks like here on github. We should add a manager screendump or partial one in the README.md

**Comment by fourroses666** [comment]
Have a screendump here. Where to place the image? Should we store this image extern?

![manager-example](https://cloud.githubusercontent.com/assets/523389/20462458/9d7160bc-af1e-11e6-8604-44929559bf1b.jpg)

**Comment by pmfx** [comment]
Added three screenshots in #956 

![screenshot_1](http://image.prntscr.com/image/ec33b07b02054186a5713df3447967bf.png)

![screenshot_2](http://image.prntscr.com/image/ad611b2bc2e342f581682777611f9128.png)

![screenshot_3](http://image.prntscr.com/image/bad9c3f1221847348193d6dd30ba1253.png)
