### ISSUE TITLE
Quick Manager+ Styling

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#907]
1) Buttons should follow the backend manager style? 
i.e. for MODxRE2 the Quick Manager+ buttons should be Bootstrap buttons.

2) When autohide is off (which is needed to work with a touch device), instead of overlaying the site with a opacity it might be better to force the Quick Manager bar above the site? Otherwise on a small screen a site 'burger bar' style website menu can end up under the Quick Manager menu bar making it unusable.

**Comment by Nicola1971** [comment]
regards question 1)

actually, i don't think is possible ('ve tested a bit)

to fit backend manager buttons, you need to load the entire theme css on the frontend:

in addition to overweight,  just imagine how many conflicts and issues with your frontend Template styles (first: button styles) :(

**Comment by bossloper** [comment]
1) Very true, forget that one. It would need to be a frame!?! Which is no good.
2) This still stands though.

**Comment by Deesen** [comment]
1. I think some parts of QM need refactoring, then its possible. Without a frame of course. And why not use a tiny responsive framework like http://purecss.io/ to make it responsive. We should be able to avoid all conflicts by prepending css-id like #qm_34ikb6 to every QM css-rule. Also I think it is possible and would be good to make the Quickmanager styleable for each site. So one can easily adapt bar/button-color or whatever.
2. To solve this I think we can already refactor and then also solve point 1.

**Comment by Nicola1971** [comment]
Restyled QM buttons with MODxRE2 style

![qm1](https://cloud.githubusercontent.com/assets/7342798/22082201/13560aea-ddc7-11e6-9ba3-889e70c88a77.jpg)

![qm2](https://cloud.githubusercontent.com/assets/7342798/22082205/19eb4398-ddc7-11e6-8ff5-7d59bb73a418.jpg)

**Comment by Nicola1971** [comment]
@bossloper just added an option for "bottom" toolbar

![bottom-toolbar](https://cloud.githubusercontent.com/assets/7342798/22174166/b8eff1f2-dfd7-11e6-99e9-d42e19d490a3.jpg)

**Comment by bossloper** [comment]
great idea, that will certainly help.

**Comment by Nicola1971** [comment]
...and Left Toolbar
![left-toolbar](https://cloud.githubusercontent.com/assets/7342798/22175524/9c83d6e0-dff6-11e6-87a3-5492abc64761.jpg)

...and Right Toolbar
![right-toolbar](https://cloud.githubusercontent.com/assets/7342798/22175527/af77f768-dff6-11e6-9cbd-73d8392fff98.jpg)

**Comment by pmfx** [comment]
Great improvement! I really like it as sidebar.

**Comment by Nicola1971** [comment]
and just added a **before** (top position-relative) options, so we will have:

* top 
* left
* bottom
* right
* before (position relative, before the site)

![before-toolbar](https://cloud.githubusercontent.com/assets/7342798/22175702/99c0e796-dffa-11e6-8705-d93ff6b66311.jpg)

Need to test custom buttons (feature that i never used) with sidebat layout

**Comment by bossloper** [comment]
Side toolbar looks very useful, but how will it work for custom buttons? a popup?

**Comment by Nicola1971** [comment]
if you want to test QuickManager 1.5.7

https://github.com/Nicola1971/QuickManager

**Comment by Nicola1971** [comment]
ok never used custom buttons, 

Added support for sidebar icons:  

example from QM documentation

```'Site statistics','link','http://www.google.com/analytics/','',''```

result:
![custom-butt-top](https://cloud.githubusercontent.com/assets/7342798/22176294/3e792314-e007-11e6-91dc-d354f8971330.jpg)

New way (with icon for siodebar layout)
```'Site statistics','link','http://www.google.com/analytics/','','','area-chart'```

result in sidebar
![custom-butt-right](https://cloud.githubusercontent.com/assets/7342798/22176304/8080454e-e007-11e6-925f-045e2ad0f26e.jpg)

**Comment by Nicola1971** [comment]
Fixed a bit styles - now works very fine for me - please test it.
i cant stop playing with the toolbar in sidebar :-D

**Comment by Nicola1971** [comment]
last small addition: Responsive - Media Query for horizontal toolbars : switch from text buttons to icons on small devices

![qm-mobile](https://cloud.githubusercontent.com/assets/7342798/22183112/8424d3d6-e0b6-11e6-8cc1-fd53efebcaa1.jpg)

**Comment by bossloper** [comment]
You had just one more play then :-) I will give it a try next week.
Nice addition, looks like you might have been looking at the WP frontend toolbar? I think that is a good baseline to refer to.

**Comment by Nicola1971** [comment]
I must admit, I don't know wp toolbar, got the ideas for better QM positions talking with @pfmx

**Comment by bossloper** [comment]
For research/inspiration it is worth a look.

**Comment by a-sharapov** [comment]
Hello there, did u accept any design corrections? Like this: http://prntscr.com/dywtqf

**Comment by Nicola1971** [comment]
@a-sharapov  yes I accept any improvement, but

* MODX icon - sadly we need to remove all modx logos and name in the next future. Anyway, the actual icon is a bit ugly :) need something better.
* Background gradient - how does it look on sidebar?

I'm planning to add an option for backgroud: sidebar toolbar looks good without background too (just buttons without autohide)

**Comment by fourroses666** [comment]
Looks nice Nicola, maybe smaller buttons so you have a little smore space (and also smaller icons (font) I do like the background gradients as it suits the manager theme top. Well done

**Comment by pmfx** [comment]
> background gradient - how does it look on sidebar?

You would need to just switch background direction to vertical (top -> bottom).

I posted my style on Slack but I will add it here too:

![pasted image at 2017_01_20 23_33](https://cloud.githubusercontent.com/assets/10888055/22185516/a3b82ad2-e0e7-11e6-9a22-6a66114ef24a.png)
For buttons I've used Manager top nav buttons style 1:1. Feels more natural to me :)

**Comment by a-sharapov** [comment]
@pmfx, nice one. dat coolest more of my variant

**Comment by bossloper** [comment]
Another suggestion. With the Quick Manager+ bar having a 'Manager' button that takes you back to the manager interface, it would be nice to have a reciprocal at the top of the manager interface that takes you back to the frontend - but not like preview which opens a new tab and also available at the level 1 manager menu. Then it would be quick to switch from front to back from one window.
e.g.

![untitled](https://cloud.githubusercontent.com/assets/1744687/22196758/a4f1c94e-e146-11e6-8a21-454cc267d4d9.png)

**Comment by Nicola1971** [comment]
Thanks to all for suggestions, tried to add all.

Updates:
* Updated Colorbox to 1.6.4
* Replaced logo/icon with a fontawesome 
* Now the icon changes when toolbar is closed
* Added gradient background and some updated styles @a-sharapov
![qm-top-grad](https://cloud.githubusercontent.com/assets/7342798/22209087/7f612dac-e185-11e6-80c5-f72075d2eb08.jpg)
![qm-top-grad-close](https://cloud.githubusercontent.com/assets/7342798/22209090/835af0e6-e185-11e6-979e-bce9688f376a.jpg)


* Vertical gradient in sidebar top -> bottom @pfmx
* a bit Smaller icon buttons, but still touchables @fourroses666 
![qm-right-grad](https://cloud.githubusercontent.com/assets/7342798/22209096/8b9b2906-e185-11e6-8645-dfb75dc64697.jpg)


* Now you can choose from plugin config: 2 buttons styles :  actionButtons or navButtons ( like @pfmx) 
![qm-top-nav](https://cloud.githubusercontent.com/assets/7342798/22209108/94b1b30c-e185-11e6-9970-22b0fc8228c4.jpg)
![qm-right-nav](https://cloud.githubusercontent.com/assets/7342798/22209113/99734900-e185-11e6-9b86-0c116eee2bb7.jpg)

* Now you can remove the background from plugin config (nice in sidebar view)
![qm-right-nobg](https://cloud.githubusercontent.com/assets/7342798/22209122/a0986b20-e185-11e6-986a-31dca1e41aff.jpg)

**Comment by fourroses666** [comment]
Nice Nicola.

Some final thought. Maybe you can made all the mobile icons square? Width and height 44px; or 50px; The cross also font-awesome.
Does the buttons change in mobile icons for the horizontale version?

**Comment by Nicola1971** [comment]
@fourroses666 
> Maybe you can made all the mobile icons square? Width and height 44px; or 50px; 

To save space? or just for design?
yes, but i'm trying to mantain the same style of the manager (buttons are not squared in manager)

> The cross also font-awesome.

Just done:
![qm-close-fa](https://cloud.githubusercontent.com/assets/7342798/22212963/d67387a4-e192-11e6-8b25-d9d3f5047b20.jpg)


> Does the buttons change in mobile icons for the horizontale version?

Yes, all horizontal version switch to icon/mobile at low res
![mobile-butt](https://cloud.githubusercontent.com/assets/7342798/22213066/236b5618-e193-11e6-9def-1fd5f5ca378b.jpg)

> And option for fixed or static/relative perhaps?

**Before** is like **top** but with relative position
don't think sidebars or bottom are useful in relative position

**Comment by fourroses666** [comment]
yea its oke like that :) looking great. 1 thing is that its not aligned in the center. the cross and id:2 text. job well done
