### ISSUE TITLE
New Resource - Unknown Error occured while sending lock-request

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#908]
Latest dev clean install. 
When adding a new resource after 10 seconds an 'Unknown error' message pops up:

![locked](https://cloud.githubusercontent.com/assets/1744687/20054466/05c10acc-a4d5-11e6-8c34-e8dc4f43f26d.png)

**Comment by Deesen** [comment]
I mentioned in PR it needs some testing first. I guess you installed into a subdirectory like the issue with Tiny4-search?

**Comment by bossloper** [comment]
yes it is same subdirectory install. 
Though I only get that error for a new resource, not when editing and existing one.

**Comment by Deesen** [comment]
Yes I just noticed the ID 0 which means "new resource", thanks for the info. Embarrassing bug...

**Comment by bossloper** [comment]
yes that works now.
