### ISSUE TITLE
TinyMCE4 - Custom Parameters - Need adding last to options list

### ISSUE THREAD

**Issue by bossloper** [modxcms/evolution#912]
Any Custom Parameters are applied first when defining TinyMCE, which means they may not be applied if there are subsequent 'built in' options:

```
<script>var modxRTEbridge_tinymce4 = {"default":"config_tinymce4_full"};</script><script>
    var config_tinymce4_full = {
**custom parameters currently here**
        relative_urls:true,
        remove_script_host:true,
        convert_urls:true, ...
```

I would suggest adding the 'Custom Parameters' to the end of the configuration so it will override any 'built in' options in the TinyMCE setup?

**Comment by Deesen** [comment]
Makes much sense!
