### ISSUE TITLE
MODX_startup_Bootstrap.tpl

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#915]
I have just seen a modification that @Yama has made to the "[MODX_startup_Bootstrap.tpl](https://github.com/modxcms/evolution/commit/0594d655ace4de2518eb005d043d412cf257f900)"

This:
`<link href="[[if? &is=`[*id*]:is:1` &then=`[(site_url)]` &else=`[(site_url)][~[*id*]~]`]]" rel="canonical">`

Has been changed to this:
`<link href="[(site_url)]<@IF:[*id:isnt(1)*]>[~[*id*]~]<@ENDIF>" rel="canonical">`

I get the jist of things but has anyone taken into account all of the error pages, 404, 403 etc. They shouldn't be given back in the canonical link, in that situation, only the homepage should be given back.

Is the new syntax cached, or is it called every time ?

**Just a side note:**

XHMTL + HTML are being mixed up, the use of "/" isn't require in self closing tags e.g base href, charset - for my liking it should be one or the other and not a mix, just clean code.

Should the lang="en" be set per hand, can't it be set via the manager language ?

**Comment by yama** [comment]
OK, I will fix it soon.

**Comment by yama** [comment]
> Is the new syntax cached, or is it called every time ?

Yes, cached

> Should the lang="en" be set per hand, can't it be set via the manager language ?

Shall I make a variable "[(lang_code)]" ?

**Comment by modxuser** [comment]
The manager language is already there, so can't that be used ?

`[(manager_language)]`

As seen in the [documentation](https://docs.modx.com/evolution/1.0/content-editing/modx-tags)

**Comment by Deesen** [comment]
@modxuser To understand you right, do you mean changing demo-template MODX_startup_Bootstrap like `<html lang="[(lang_code)]">` ? 

https://github.com/modxcms/evolution/blob/develop/install/assets/templates/MODX_startup_Bootstrap.tpl#L15

https://github.com/modxcms/evolution/blob/develop/manager/includes/lang/english.inc.php#L16

**Comment by modxuser** [comment]
@Deesen 

`<html lang="[(manager_language)]">`

Or something new, like what you and @yama have proposed

`<html lang="[(lang_code)]">`

**Comment by modxuser** [comment]
The point behind this is simple:

If anyone outside of an English speaking country uses the template, the tag is wrong as it should default to the language that is selected in the manager

This is in some cases not corrrect, especially when a user creates a site in English but has the manager in their mother / native language.

Another situation is where a multi-language site is built, in this case the tag (unless possible), should be removed

**Comment by Deesen** [comment]
`[(manager_language)]` will output full names like "english" (for name of language-file). So we need a new placeholder for outputting lang-code set in manager language-files like https://github.com/modxcms/evolution/blob/develop/manager/includes/lang/english.inc.php#L16

This means in frontend the core always needs to load manager language-files to provide this lang-code, which makes no sense to me.

Maybe a simple chunk `<html lang="{{lang-code}}">` will do? This will hopefully also lead to better understanding how to use chunks / MODX.

**Comment by modxuser** [comment]
Or simply remove it ?

**Comment by Deesen** [comment]
"Google" says better not remove it, but set it right (also needed for CSS etc). I guess there is no perfect solution for all situations here without adding some kind of multilanguage-feature to the core, or like Revo´s Context Settings.

**Comment by Deesen** [comment]
:-)

**Comment by modxuser** [comment]
@Yama

Cool - looking at the code it picks up the language file and reads the "$modx_lang_attribute", if it doesn't have an attribute set, it uses "en"

**Comment by Deesen** [comment]
Yes when saving system-settings an additional key is set. This way the manager language-file will not get loaded in front-end so my comments were nonsense.

I think a complete 1.2-documentation is generally a big topic. But maybe a notice in settings is enough?

![langcode](https://cloud.githubusercontent.com/assets/8569221/20168236/2b0c870e-a721-11e6-8046-1b7666eb20a3.png)

**Comment by bossloper** [comment]
There are a few system config settings where it might be useful to add the placeholder code to the description? i.e. Site name, Site start, error page etc.

**Comment by Deesen** [comment]
Can only help! :+1:

**Comment by pmfx** [comment]
I don't think binding Manager Language with frontend is a good idea. Doesn't make sense to me. Isn't it supposed to be Manager-only setting? I agree with @modxuser that frontend language attribute should be set manually or via a custom snippet.

Regarding documentation - placeholder codes (or tags) next to system setting name would be a nice addition.

**Comment by modxuser** [comment]
@pmfx I think you have misunderstood, **I suggested using the Manager** setting to do this.

This is a compromise and if you read [what I wrote for the documentation](https://github.com/modxcms/evolution/issues/915#issuecomment-259417707), you will see why.

**Comment by pmfx** [comment]
I don't use [(modx_charset)] either. Why it doesn't make sense? Well for me it is too fragile setting. Imagine that situation when there is a new site administrator. Old one was english and new one is german and he wants to have manager in german language, but the site frontend is english. This can lead to problems. I know there are user default settings, but still it can be misleading for some. For me most manager settings are for backend. I configure frontend with plugins/snippets.

**Comment by modxuser** [comment]
As mentioned above:

> Please note that the tag is a compromise. If you build multi-language websites or your website content language is different to your chosen manager language, the tag should not be used.

**Comment by yama** [comment]
This is quick fix. It becomes easy to make free public templates by [(lang_code)] .
I think that backend lang and frontend lang should separate him each, at the next opportunity...
