### ISSUE TITLE
My Concerns

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#916]
Although I think the advances that have been made (in leaps and bounds) to Evo are great and more than welcome, the time has come to release what is already completed.

It was [proposed 19 days ago](https://github.com/modxcms/evolution/pull/850), any ideas when it will be released ?

> need write changelog and write pre-release and publish on modx.com

Where is the changelog, where is the list of changes - the pre-release write-up can be the same as [the one I wrote for the last version](https://github.com/modxcms/evolution/releases/tag/1.1), it just needs modifying to cater for the changes

**Comment by dmi3yy** [comment]
Now i go to holiday and do this on this week

Отправлено с iPhone

**Comment by modxuser** [comment]
That sounds great @dmi3yy

**Comment by bossloper** [comment]
can be closed?
