### ISSUE TITLE
new modx evo forum

### ISSUE THREAD

**Issue by mgzawlinoo** [modxcms/evolution#917]
Hi, 
After upgrading Modx 1.1 ,
I have many problem with some snippet such as filterig the ditto result from form with $_get method.
(I know my snippet are out of date and I don't know how to fix it with new modx version.
Now Modx evo official forum is not useful and I don't wanna ask my problem at there.
So is there a other modx evo forum or website that can ask beginner question.
Sorry for my question at github issue and you can delete this issue.

**Comment by fourroses666** [comment]
Hi mgzawlinoo,

I think the best place to ask is the forums.
