### ISSUE TITLE
EvoCheck: PHP-Script to assist finding compromised code

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#937]
### When trying this script on a live-site, change password in Line 16 first!

Ref. to #919 I thought maybe a dedicated script as "first-help" tool makes sense like `manager/evohacked.php`.  It uses `includes/config.inc.php` to connect to database. See screenshots for more details.

Moved to https://github.com/extras-evolution/evocheck

In Dashboard it displays Plugins assigned to the following "critical events" so far: 

    OnBeforeCacheUpdate
    OnCacheUpdate
    OnManagerAuthentication
    OnManagerPageInit
    OnWebPageInit
    OnWebPagePrerender

**Comment by Deesen** [comment]
preg_match('/(base64_|eval|system|shell_|exec|php_)/i'

**Comment by Deesen** [comment]
Improved

![modx-hass](https://cloud.githubusercontent.com/assets/8569221/20456277/071677d8-ae74-11e6-8ecf-4e3b24ff94f7.png)

**Comment by Deesen** [comment]
![modx-hass-changedafter](https://cloud.githubusercontent.com/assets/8569221/20456336/37923fd6-ae75-11e6-9b6f-760740120866.png)

**Comment by dmi3yy** [comment]
graat idea )  


--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


суббота, 19 ноября 2016 г. в 17:28, Deesen написал:

**Comment by Deesen** [comment]
Does a dedicated repository for it make sense or better not make such tool too public? If repository makes sense,  should we add it to extras-evolution or I make my own?

**Comment by Nicola1971** [comment]
great tool @Deesen !

**Comment by pmfx** [comment]
Great idea indeed. You can create repository, I dont see issues with making it public.

**Comment by Deesen** [comment]
#### Same "Check core files on login" as per MODX-Config. Elements and Files are now clickable and open in a popup with highlighted code. Shift-Click opens multiple windows.

![hass1](https://cloud.githubusercontent.com/assets/8569221/20463794/88d53ea4-af3b-11e6-8485-493d8a5e47e6.png)

#### Summary Length can be set to zero to only disable Element- / Filenames without any preview of source-code.

![hass2](https://cloud.githubusercontent.com/assets/8569221/20463795/8b196992-af3b-11e6-9b28-f20365aa1307.png)

#### PHP stat() fileinfo

![hass3](https://cloud.githubusercontent.com/assets/8569221/20463796/8cf860d8-af3b-11e6-94a6-e06e110c48f8.png)

**Comment by Deesen** [comment]
What would be the perfect name for such a tool? "Hack-Assistant" looks and sounds strange to me ;-)

- MODX Evolution Hacked (best for SEO?)
- CCAss (Compromised Code/Core Assistant)
- EvoAnalyzer
- ..

**Comment by dmi3yy** [comment]
I and more people use:  
https://revisium.com/aibo/

I think better some like Antivirus / Malware Scanner for MODX EVO  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 21 ноября 2016 г. в 10:36, Deesen написал:

**Comment by bossloper** [comment]
MODX Malicious Code Scanner?

**Comment by fourroses666** [comment]
Secure site checker / assistant

**Comment by pmfx** [comment]
Evo Malware Check
Evo Malware Scanner

**Comment by Nicola1971** [comment]
For Marketing view: better something less "negative" than hacked or malware
something like Evo _Safety_ Assistant/Checker/Analyzer

**Comment by bossloper** [comment]
Evo Airbag ;-)

**Comment by dmi3yy** [comment]
Evo Doctor )  

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 21 ноября 2016 г. в 12:28, Mr B написал:

**Comment by yama** [comment]
Evo first aid kit

**Comment by nick0** [comment]
Great idea Deesen! Thank you.

Along the lines of @Nicola1971...
Evo Safety Check

Or maybe (obtusely)...
NoCompromises
A code safety check for Modx Evblution

**Comment by voklee** [comment]
@Deesen 
Very nice tool used it on all my sites.

Arent you able to write a fix against the hacks. Seems the patch is not fully working when i read at : [https://github.com/modxcms/evolution/issues/919](url)

There is an other easy methode to check if you are hacked that clients can check without the help of us as developers.

> Go to google.com
> type: `site:yoursite.com`
> Click on 'Search tools' > Change 'any time' to 'past month'
> Hit 'search' 

If you get Japanese or Chinese results you are infected......

**Comment by Deesen** [comment]
I think the fix is already working, its about correct removal of all traces of the hack.

Anyway in case of a future-hack we maybe can provide a set of RegEx-strings to search the server using "the tool" for a known hack.

Reg. the name, thanks @all. I guess I will stick with "EvoCheck". Its short and easy to remember, no bad marketing :D and describes best what the tool is about: Checking Evo!

And dmitryy proposed we can also create a module, beside the actual "standalone"-version.

**Comment by pmfx** [comment]
Good name. And maybe plugin showing warnings on dashboard (EvoCheck run on login).

**Comment by nick0** [comment]
Excellent ideas @Deesen and @pmfx

**Comment by Nicola1971** [comment]
+1 for EvoCheck module + dashboard plugin

**Comment by Deesen** [comment]
Reg. plugin and module I think we must consider that hackers will take EvoCheck also into account. Just to remind, in november-hack they created an extra plugin but could hide it from manager :-). So if EvoCheck is installed and hacked, and admins relys on that "green light", nobody is helped. Not sure how to make such mechanismn 99-100% relyable and secure without an "extra-layer" above PHP (like some Apache-App, just guessing). I am excited about any ideas coming up!

**Comment by Deesen** [comment]
Moved to https://github.com/extras-evolution/evocheck-standalone

**Comment by Deesen** [comment]
v0.2 as module-version can be tested here https://github.com/extras-evolution/evocheck/tree/v0.2-module

### Now with delete-buttons

![ec1](https://cloud.githubusercontent.com/assets/8569221/21023946/086ac2f6-bd83-11e6-8a2e-3d1aceb4a68b.png)

![ec2](https://cloud.githubusercontent.com/assets/8569221/21023962/1e190982-bd83-11e6-89ef-2b7e2727baf3.png)

### optional RegEx-strings to select from

![ec3](https://cloud.githubusercontent.com/assets/8569221/21024022/480bcf22-bd83-11e6-97b8-77d01e01273c.png)

**Comment by nick0** [comment]
Great work @Deesen. 

I think this sentence in the instructions:
It is just a simple try of explanation to none-experienced users, to enable them start investigating on their own and get more help at https://github.com/modxcms/evolution .

could possibly be changed to:
It is just a simple try of explanation to inexperienced users, to enable them to start investigating on their own and to get more help at https://github.com/modxcms/evolution.

or probably neater like this:
Inexperienced and new Evolution users are encouraged to read the following instructions to help with initial investigations and to get more help at https://github.com/modxcms/evolution.

Note there is a typo in this sentence.
The "Changed-after"-date is not relyable! 
change:
relyable
to:
reliable

Thanks @Deesen and keep up the super work.
