### ISSUE TITLE
comments should be removed from siteCache.idx.php

### ISSUE THREAD

**Issue by Cipa** [modxcms/evolution#938]
on a default site install this file is ~86kb

Stuff like this

* Jot
 * 
 * User comments with moderation and email subscription
 *
 * @category 	snippet
 * @version 	1.1.5
 * @license 	http://www.gnu.org/copyleft/gpl.html GNU Public License (GPL)
 * @internal	@properties
 * @internal	@modx_category Content
 * @internal    @installset base, sample
 * @documentation MODX Wiki http://wiki.modxcms.com/index.php/Jot
 * @reportissues https://github.com/modxcms/evolution
 * @link 		Latest Version http://modx.com/extras/package/jot
 * @link 		Jot Demo Site http://projects.zerobarrier.nl/modx/
 * @author      Armand "bS" Pondman apondman@zerobarrier.nl
 * @lastupdate  09/02/2016
 */

and 

/*
    Param: tplYear

    Purpose:
    Template for the year item

    Options:
    - Any valid chunk name
    - Code via @CODE:
    - File via @FILE:

    Default:
    See default.tempates.php
*/

should not be in that file. This will improve speed on initial cache genearttion and pages that are not cached. Also it will help on server with slow write speed

**Comment by Cipa** [comment]
maybe we can use 
php_strip_whitespace

**Comment by yama** [comment]
http://php.net/manual/en/function.php-strip-whitespace.php
How about this function?

**Comment by yama** [comment]
> maybe we can use
> php_strip_whitespace

Oh, I did not read it. I think that's fine, but how is it?

**Comment by yama** [comment]
https://github.com/pear/PHP_Compat/blob/master/PHP/Compat/Function/php_strip_whitespace.php

**Comment by yama** [comment]
[cache_sync.class.processor.zip](https://github.com/modxcms/evolution/files/601500/cache_sync.class.processor.zip)

**Comment by Cipa** [comment]
php_strip_whitespace works only on files I believe. We could use regex, see second link
