### ISSUE TITLE
New API - Safety eval

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#939]
ref : https://github.com/modxcms/evolution/issues/919

https://gist.github.com/yama/418d54809b4f6be9a2d9a4522ff16e9c

https://github.com/modxcms/evolution/blob/f61a450eb06c75b18b67282b0a70e3df5f5be678/assets/snippets/ditto/classes/filter.class.inc.php#L24-L26

```
$this->filterValue = eval(substr($currentFilter["value"],5));
```
For example, the above code ...
```
$this->filterValue = $modx->eval(substr($currentFilter["value"],5));
```
Rewrite like this

**Comment by yama** [comment]
https://gist.github.com/yama/418d54809b4f6be9a2d9a4522ff16e9c
Updated

**Comment by yama** [comment]
Although it can prevent the execution of dangerous PHP code, it can not prevent the output of dangerous HTML tags. Because there are many patterns. Perhaps it may be necessary to use htmlspecialchars() at $_POST.

**Comment by yama** [comment]
https://gist.github.com/yama/4e9d53b494c217faba63232b35c63319
Part2.
Simple and safety.

**Comment by Segr** [comment]
why not in PHPCOMPAT?

**Comment by Segr** [comment]
$modx->phpcompat->eval()

**Comment by yama** [comment]
Thanks for the suggestion. This safeEval is a very limited eval. So, I did it like this.

**Comment by yama** [comment]
There is another reason. The "eval" isn't function name, it's syntax. Therefore, there are cases where an error occurs.
