### ISSUE TITLE
Manage Files doesn't work?

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#941]
Just installed fresh 1.2-RC1. Getting the message when clicking on Manage Files;

Can not read this directory.

**Comment by Deesen** [comment]
I guess you need to check/reset "File Manager path" in Configuration -> File Manager.

**Comment by fourroses666** [comment]
Ah sorry did check but didn't notice it needs to be [(base_path)]assets/ instead of the / I had.
