### ISSUE TITLE
System Notification Emails Receiver

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#944]
Wouldn´t it  be great to have the option to send "Mail on MODX errors" to multiple manager-users? I think of a checkbox in manager user-settings.

In case of errors the notification email gets send to the adress set in configuration as "E-mail address", and to all manager-users with checkbox. Maybe for manager user with ID 1 it should be active by default.

In most cases I have to set "Email adress" to "info@customerdomain.de", so notifications get only send to customer and not me the administrator...

**Comment by bossloper** [comment]
That crossed my mind too. 

You would need to be careful it did not send too many emails i.e. you probably do not want 1 email for each error in the log!

Also, how would that work with the core file check as it is only triggered at a manager login I believe(?) so might not get to the MODX errors log for a long time depending on how often a site needs maintaining. Thus for core file check should there be a periodic check via a frontend trigger. Wouldn't want it to test too often or it would have a performance hit on the website.

**Comment by Deesen** [comment]
Maybe

- an intelligent system-message queue which will not send the same warning over and over again, but will notify again once in case the same error appeared more than 10x per minute or so ?
- some kind of php-controlled "CRON-job" I guess, so every 2 hours a job will be called, for example checking those system-files, or maintain something else

**Comment by fourroses666** [comment]
Hmm, I always have to set it off because it mails every time I login in the manager.
Don't know why it does it. So rather not have it default send to admins.

**Comment by bossloper** [comment]
How about as an alternative to email a 'Manager API' (accessed via a key authentication?) where basic system information could be queried. E.g. MODX version, error log count, manager activity count (from manager actions?), online/offline etc etc. 
Then for those admins that manage multiple MODX sites they could have a centralised dashboard listing their sites with the status for each.

**Comment by Deesen** [comment]
Now it is getting spooky, I was thinking of exact the same ;-). Maybe worth to add to modxapi.ajax #946 ? At least it is noted. Would be a dream to have such a "master control" !!

**Comment by Deesen** [comment]
@fourroses666 Which error-message is sent to you everytime?

**Comment by yama** [comment]
> some kind of php-controlled "CRON-job"

https://github.com/WordPress/WordPress/blob/master/wp-cron.php
Like the wp-cron

**Comment by fourroses666** [comment]
@Deesen 

`In dutch: Source: Belangrijke Systeem bestanden zijn aangepast! - The details of the error could be seen in the MODX system events log.`

Log says:
![log](https://cloud.githubusercontent.com/assets/523389/20481928/fff0fa42-afe9-11e6-85e6-95ae3fe529c5.png)
