### ISSUE TITLE
modxapi.ajax

### ISSUE THREAD

**Issue by Deesen** [modxcms/evolution#946]
All ideas regarding a new "modxapi.ajax":

- Issue 944: for those admins that manage multiple MODX sites they could have a centralised dashboard listing their sites with the status for each
- Ajaxify buttons in dashboard
- Ajaxify buttons in elements-management
- only reload tree-locks, not whole tree
- elementsInTree: only reload locks, not whole tree
- #1230 Collection in Tree, load resources-data as per pagination / search etc

**Comment by dmi3yy** [comment]
start work on this in modx.js and new theme
