### ISSUE TITLE
Important Questions

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#951]
I am being PM'd on a regular basis on the MODX forum ref. the latest hack. The general questions:

1. Has the code been updated since the first post was made
2. According to the Github post the download [found here](http://extras.evolution-cms.com/packages/core/security-fix.html) is outdated, where do I find the new code
3. Does the develop branch in Github have the updated code
4. Is it safe to download and install the code found in the Develop branch
5. When will Evo 1.2 be released
6. I am not a developer and don't know how GitHub works, can you guide me to download the updated code
7. It has been mentioned that the latest updated code is not sufficient to stop my website from being hacked, can you verify this please.

I can't answer these questions as I am not a DEV. Please could someone clarify where what is, where to download it and when the 1.2 release will be released

**My opinion:**

The 1.2 release is long overdue, there has been tons of coding completed and none of it has been extensively tested in a variety of situations - not only that, it seems that everyday something new is being added or updated - isn't it time to get the release out in the open ?

It is also now an anticipated release, due to the latest hack

**Comment by fourroses666** [comment]
There where no hacks since I have uploaded the latest version on github.
Can't confirm if the Extras module is updated so I manually updated my sites to be sure it has the latest fix.

Download it and upload;
https://github.com/extras-evolution/security-fix

I actually still need to see if the latest version works when updating a site with YAMS.
I have done some tests but there keep things being improved. _(Good but there doesn't seem to be an end)_
There needs to be a point where we heavily test the latest development version and then roll it out (I think).

The security leak did slowed it down.

**Comment by modxuser** [comment]
@fourroses666 

Looking at the protect.inc.php found in the download, the date is from 10 days ago, whereas the current Develop version is from 7 hours ago ????

I don't see the light at the end of the tunnel at the moment, too much confusion

**Comment by pmfx** [comment]
@dmi3yy & @yama time for 1.2-RC1? Or there is something important left to do holding it back?

**Comment by dmi3yy** [comment]
Need stop add new, refactor, e t s 
Test all and realise. 

Only fix bug. Plz for all




Отправлено с iPhone

**Comment by bossloper** [comment]
@modxuser the change for protect.inc.php in the last few hours was relatively minor compared to the security fix. 
Most of the recent commits are minor bug fixes or refactoring i.e. not critical. 
One of the main changes that probably needs checking before a new version are the new lock functions #945

**Comment by pmfx** [comment]
Maybe we should release 1.1.1 with security patch NOW and after that 1.2-RC1 in few days.

**Comment by yama** [comment]
https://github.com/modxcms/evolution/tree/1.1.1_security_fix
https://github.com/modxcms/evolution/archive/1.1.1_security_fix.zip
The security Fix package is already ready. Everyone should use this.
https://github.com/modxcms/evolution/commits/1.1.1_security_fix
Only eform and ajaxsearch have been updated.
In addition, we fixed the error when new installing sample data.

**Comment by modxuser** [comment]
Thanks @yama I will update the forum post accordingly
