### ISSUE TITLE
I: system events management

### ISSUE THREAD

**Issue by mcparana** [modxcms/evolution#962]
it would be useful to have some kind of event management on plugins tab of element management, maybe in ?a=100 action, with crud for user-defined events.

**Comment by Deesen** [comment]
And where would custom events become invoked?

**Comment by mcparana** [comment]
last time i needed it when added plugin to update document when web user posts comment via jot

**Comment by Deesen** [comment]
Ah ok, and I just remembered "ShopKeeper" creates its own events too. Could be indeed very helpful for future developments.

**Comment by dmi3yy** [comment]
move to new repo https://github.com/evolution-cms/evolution/issues/54
