### ISSUE TITLE
Fresh install, missing configuration tabs

### ISSUE THREAD

**Issue by pmfx** [modxcms/evolution#964]
![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/20570757/327dbb3c-b1a5-11e6-8ef6-e6955ba2b89c.png)

**Comment by Deesen** [comment]
Pls check source-code immediately (before error is gone) and tell me which error is at its end ;-).

**Comment by pmfx** [comment]
There is no errors at the end. Just end of html.

![screenshot_2](https://cloud.githubusercontent.com/assets/10888055/20571900/87bb621c-b1a9-11e6-84d8-af369a0ec178.png)

**Comment by Deesen** [comment]
Must be something stupid simple, I am waiting for your details via PM.

**Comment by pmfx** [comment]
Working now.
