### ISSUE TITLE
Duplicate entry '61-612' for key 'ix_tvid_contentid' 

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#973]
http://take.ms/d0zz3

**Comment by dmi3yy** [comment]
Duplicate entry '61-612' for key 'ix_tvid_contentid' во время выполнения SQL запроса ALTER TABLE `sns_site_tmplvar_contentvalues` ADD UNIQUE INDEX `ix_tvid_contentid` (`tmplvarid`,`contentid`).

**Comment by Deesen** [comment]
http://stackoverflow.com/a/33438274/2354531

**Comment by mcparana** [comment]
think this is not a bug of update. 
duplicate data in site_tmplvar_contentvalues is realy evil but each site admin has to decide what value to save himself.
auto remove of duplicates guarantees data loss in this case.

**Comment by Deesen** [comment]
Then question is, where and how exactly do such duplicates come from and how to avoid them?

**Comment by Deesen** [comment]
I think without primary key this would avoid duplicates: http://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html . I already used it for other none-MODX projects.

**Comment by mcparana** [comment]
creation of unique index (subject) will solve duplicate problem on new installations.

on upgrade we cannot modify neither TV id nor content id (parts of that key), it will cause data inconsistence.

so duplicates removal is only manual task.

**Comment by Deesen** [comment]
Was just answering my own question ;-). This will check for duplicate keys for example inside instprocessor.php. They could be moved to an extra table or dumped to file maybe to have no data-loss? Just brainstorming..

    // Check for duplicate keys - Issue #973
    $query = "SELECT tmplvarid,contentid, count(*)
      from $dbase.`" . $table_prefix . "site_tmplvar_contentvalues` tvc
      LEFT JOIN $dbase.`" . $table_prefix . "site_tmplvars` tv ON tv.id = tvc.tmplvarid
      group by tmplvarid,contentid
      having count(*) > 1";
    $rs = mysqli_query($conn, $query);
    while($row = mysqli_fetch_row($rs)) {
        echo 'TV-Id '.$row[0].' - Content-ID '.$row[1].'<br/>';
    };

**Comment by mcparana** [comment]
separate table sounds good :)

**Comment by dmi3yy** [comment]
http://take.ms/Q50Hnw

**Comment by dmi3yy** [comment]
all simple %) 
http://take.ms/19AAN
