### ISSUE TITLE
hacked and other issues

### ISSUE THREAD

**Issue by wishbone-design** [modxcms/evolution#978]
I'm running evo 1.04 - yes, I know, I should long have updated, but there have been changes from third party which make me not dare to touch.
I'm **being hacked permanently** - new php-files everywhere, new folders in root ("headers", "pages" "views", "articles"...). I clean every then and now until I have a solution.
Closed some security weaknesses in the php.ini - no effect.
I tried the .htaccess from [this comment](https://forums.modx.com/thread/98168/evo-1-0-15-getting-hacked#dis-post-530835) - no effect.
(And now, when editing in the manager, every " (quote) is being prepended a \ (backslash) (escape?), the quote thus being interpreted as a html entity and not a sign.
The latter is most urgent. The backslashes only came after I tried the above .htaccess (which of course I deleted immediately). They haven't been there after the infection(s). I think it's only a minor problem, some settings.

But I also **need help with the upgrade**! Commercial would be fine if not too expensive...
thx

**Comment by Deesen** [comment]
Maybe you want to close it meanwhile?

**Comment by wishbone-design** [comment]
yes - the issue is in the other thread now.
