### ISSUE TITLE
evo: manager prepending \ before each "

### ISSUE THREAD

**Issue by wishbone-design** [modxcms/evolution#980]
where are the settings?
thx

**Comment by Deesen** [comment]
Maybe a "magic quotes"-issue http://stackoverflow.com/questions/3006407/slash-before-every-quote-problem . Check your /.htaccess and /manager/.htaccess for `magic_quotes_gpc` . Ifany entry exists, you can change it to `php_flag magic_quotes_gpc Off`, or add this rule to /manager/.htaccess.

**Comment by modxuser** [comment]
You may also like to take a [look at Google](https://www.google.de/search?q=modx+evo+magic+quotes&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=jgU8WIitM9Co8wfG_LG4Cg) reference @Deesen reply ref. magic quotes

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/v1.1RC2/manager/index.php#L106-L111
I think that this part is not working
What is your PHP version?

**Comment by wishbone-design** [comment]
omg this is Christmas, so much help!
Yama, PHP is 5.53 stable
the code part you mentioned says "5.3" in mine instead of "5.4" in yours.

**Comment by wishbone-design** [comment]
@Deesen magic quotes are on in the php ini. I have access to the php.ini. sShould I switch them off there? Wouldn't that be a security problem?

**Comment by bossloper** [comment]
If you are on 5.3 then yes turn off magic quotes, it is a security risk. Ideally upgrade php to a later version.
See here: http://php.net/manual/en/security.magicquotes.php . It was removed from 5.4+

**Comment by wishbone-design** [comment]
Now put magic quotes off, the backslashes are gone!!!
Anyway, the `quotes_stripper.inc.php` part should have stripped the magic quotes 
ok the php version is 5.329. Is it just upgrading, or could I run into problems with my modX-install? which version do you recommend (there is 5.4, 5.5, 5.6 and 7)

**Comment by yama** [comment]
https://github.com/modxcms/evolution/blob/v1.1RC2/manager/index.php#L106
if (version_compare(phpversion(), "5.4") < 0) {
This line
if (get_magic_quotes_gpc()) {
Please rewrite like this

**Comment by fourroses666** [comment]
I'd go for PHP7. Way faster as older versions. You need at least version Evo 1.1

**Comment by yama** [comment]
If it does not fix it,
https://github.com/modxcms/evolution/blob/v1.1RC2/manager/includes/quotes_stripper.inc.php
The contents of this file,
https://github.com/modxcms-jp/evolution-jp/blob/develop/manager/includes/quotes_stripper.inc.php
Please rewrite like this

**Comment by bossloper** [comment]
RE: php version. The higher the version the more chance you have a third prty plugin/snippet/module that might have incompatibility issues due to obsolete functionality used. Maybe step up the versions and see how it goes. The higher you can use the better from a security standpoint.
