### ISSUE TITLE
Minor xss vulnerability issue

### ISSUE THREAD

**Issue by yama** [modxcms/evolution#981]
https://github.com/modxcms/evolution/blob/v1.1RC2/manager/index.php#L218-L229
Validating the value here, but,

https://github.com/modxcms/evolution/blob/v1.1RC2/manager/actions/mutate_user.dynamic.php#L207
Don't use that value.
This can be easily solved. Don't use the $_XXX variable as it is.

**Comment by Deesen** [comment]
SO just change `$_GET["a"]` to `$modx->manager->action`?

Those files too:

- mutate_role.dynamic.php
- mutate_plugin.dynamic.php
- mutate_module.dynamic.php
- mutate_snippet.dynamic.php
- mutate_tmplvars.dynamic.php
- mutate_web_user.dynamic.php

**Comment by dmi3yy** [comment]
not work in chunks

**Comment by dmi3yy** [comment]
http://take.ms/8a4EO
