### ISSUE TITLE
ElementsInTree styles and old (and custom) manager themes with Evo1.2

### ISSUE THREAD

**Issue by Nicola1971** [modxcms/evolution#984]
with all recents commits ElementsInTree plugin has become a very nice peace of code and an important part of Evo1.2 UI improvements.

Actually styling ElementsInTree for custom themes or updating old themes (i'm updating MODxRE and Carbon) is a bit hard because inline styles used by the plugin
As a part of new Evo 1.2, ElementsInTree styles should be moved to the manager theme css to allow custom styling without dozens of "!important" and make more simpler/faster update/fix old manager themes.

After that should be nice if we give some **guidelines to update old manager themes for evo 1.2**, because most of themes are broken with 1.2 (ie: new searchbars in top frame and manage elements, dashboard, ElementsInTree..).

some examples with ElementsInTree 

**ScienceStyle**
![8dh87vjqzjzzaaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/20668549/b50d64bc-b56f-11e6-9eb2-4140a353a98c.png)

**WMOD**
![giqf0daaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/20668574/d1d0325a-b56f-11e6-8547-e0ad155b47e2.png)

**MODxCarbon**

![naaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/20668533/a623c1d0-b56f-11e6-98ee-0c9ec651d65b.png)

**Comment by pmfx** [comment]
AFAIK it was decided to support only one theme with 1.2 and up and all sites upgraded to 1.2 should use official and default MODxRE2 theme. We've made it as requirement in readme file "This plugin requires MODX Evolution 1.2 or later.". All those custom themes floating around makes my head hurt :D

**Comment by Nicola1971** [comment]
Yes, MODxRE2 is the offcial theme, but there are a lot of themes for Evo, is not nice kill all these extras.
I know all modifications in latest Evo, so i'm updating my MODxFlat during the development, but for other authors of custom themes? is not kind

Anyway **Manager Customization** is an important feature of Evolution and all bundled extras like ElementsInTree should work with manager themes css not with an their own css.

**Comment by pmfx** [comment]
But if styles are about to be moved to Manager Theme CSS file then ElementsInTree should no longer be a plugin but built into the core. What I'm saying is that manager theme css file should not include plugins styles, right?

**Comment by Nicola1971** [comment]
plugins/extras should use styles from manager to fit the manager theme, when is possible, or an "anonymous" styling: 
ie: the new ElementsInTree elements context menu has MODxRE hardcoded styles (blue top border), not good

**Comment by fourroses666** [comment]
I guess when its a default plugin it should be in manager CSS.
Or the path needs to be able to modify in the plugin settings/config or should be moved to the theme folder as separate css file so it can be copied and adjusted.

**Comment by bossloper** [comment]
"plugins/extras should use styles from manager to fit the manager theme, when is possible" +1 on that.
Another example plugin where this is needed would be Quick Manager+ #907

**Comment by modxuser** [comment]
@Nicola1971 If this issue is resolved can you close it please, Cheers

**Comment by Nicola1971** [comment]
@modxuser , not really solved, but i can close for now
