### ISSUE TITLE
Possible feature? Select ID to show TV and not only on Templates

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#986]
I'm using allot of mm_rules to show or hide TVs.

It would really make things easier to be able to select IDs "(pagetitle (id)" where to show the TV.
Don't know whats possible but love to have some kind of way to deside if a "custom" TV is visible on a resource or not. (or a new admin tab where you can hide /show some TVs attached to resources)

This part of developing takes allot of time for me and I would love to have it simplified.

![select-pages](https://cloud.githubusercontent.com/assets/523389/20670747/ac0316ea-b57a-11e6-846a-f592562d8524.jpg)

**Comment by Deesen** [comment]
Not sure how to manage it when having 500 documents or more, simple checkbox will not do ;-). You can already reach your target with simple PHP in mm_rules:

    if(in_array($modx->documentObject['id'], array(1,2,3))) {
        // Resource-ID is 1,2 or 3
	    mm_hideFields(...);
    } else {
        // Resource-ID is not 1,2,3
    }

**Comment by fourroses666** [comment]
I sometimes want to do too complex behaviour so I was thinking of a way to simplify this in an overview. My PHP knowledge is close to zero and stuggle allot with it when I need too complex "else ifs". Having TVs visible in tabs while I rather not etc. But making such overview or other some way arround will probably also very complex.

**Comment by Deesen** [comment]
It would also be possible by extending MM-functions with additional ID-limit-parameter. As I know DivanDesign is updating it soon so maybe they can take your proposal into account? But still I think adding IDs manually like `1,2,3` makes more sense than choosing from resource-tree or checkbox one by one.
