### ISSUE TITLE
User language 2 versions and no sortorder

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#987]
Not important but just wonder why and if one language file can be removed;
![nl](https://cloud.githubusercontent.com/assets/523389/20671955/cfc7db7e-b57f-11e6-9c9d-fd9cf1c9cc22.png)

Is the non utf8 version needed?
It isn't sorted A-Z, Security -> User tab -> language

**Comment by Deesen** [comment]
I can only guess UTF8 is needed depending on how collation of database / PHP is set.

Reg. A-Z, no issue for me. Everything sorted like it should.

**Comment by bossloper** [comment]
RE: A-Z - I also see the random sort order (1.2RC2). Note this is for 'create/edit user' not the Tools -> Config page.
Looks like system config has a nice set of functions for lang dropdown setup. This is not used by mutate_user.dynamic.php

**Comment by fourroses666** [comment]
Is this the reason why its not sorted correct by A-Z for my manager language?
https://github.com/modxcms/evolution/blob/develop/manager/includes/lang/country/nederlands-utf8_country.inc.php
