### ISSUE TITLE
not parsed  TinyMCE params on Settings

### ISSUE THREAD

**Issue by dmi3yy** [modxcms/evolution#989]
they are all [+ +] 

http://take.ms/Nzja8

**Comment by Deesen** [comment]
yama informed me that recursive parsing has been removed in `$modx->parseText ()` so I need to adapt modxRTEbridge to fix those `[++]`.

**Comment by dmi3yy** [comment]
not all 
http://take.ms/HIjww

**Comment by Deesen** [comment]
Can you test deleting value and saving config? Maybe you have some [++] saved in DB?

**Comment by Deesen** [comment]
I can save spaces and empty values, both works for me:

![empty-values](https://cloud.githubusercontent.com/assets/8569221/20677666/135ae750-b594-11e6-96a1-19584cfcbfc6.png)

**Comment by dmi3yy** [comment]
its fresh install 

i think  incorect parse first time
