### ISSUE TITLE
user status in dashboard

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#991]
last evo gev (maybe 5-10 min ago)

when i`m log-in and online, the table shows that i log-off from the admin panel

![tyhfth](https://cloud.githubusercontent.com/assets/8958344/20673316/512ec9ae-b58d-11e6-86df-3fbf7c998d71.jpg)

**Comment by Deesen** [comment]
Have you run /install to update DB ?

**Comment by Fr3ddy7** [comment]
yes

**Comment by Deesen** [comment]
And still you ALWAYS see yourself as "idle user" (grey = longer than 20min no action) and with last action "logout"? Need to have server-access to see myself.

**Comment by Fr3ddy7** [comment]
yes, ALWAYS ))

**Comment by Deesen** [comment]
Cannot help without server access.

**Comment by Fr3ddy7** [comment]
http://tulej.kiev.ua/manager/

Deesen 
v6F8Haxz

**Comment by Deesen** [comment]
Thanks you can remove it, I found/fixed the issue.

**Comment by Fr3ddy7** [comment]
thank you :)

**Comment by Deesen** [comment]
Close? :-)
