### ISSUE TITLE
something wrong (lock documents)

### ISSUE THREAD

**Issue by Fr3ddy7** [modxcms/evolution#992]
last evo from git

in russian language i see - [+firsthit_df+]
in english - i see last editing date 

![3453534534](https://cloud.githubusercontent.com/assets/8958344/20673906/83d4f2be-b58f-11e6-945d-30a5a961b7ff.jpg)

**Comment by Deesen** [comment]
I updated english-lang, russian need to be updated too. `[+firsthit_df+]` has been renamed to `[+lasthit_df+]` ...

https://github.com/modxcms/evolution/commit/6437263123d9e0f57873ebb0de77c9fa55a0e279

**Comment by dmi3yy** [comment]
fixed

--  
Lukianenko Dmytro
Web developer  
Site:       http://dmi3yy.com
Skype:   dmi3yy
Phone:  +38 (091) 357-10-80


понедельник, 28 ноября 2016 г. в 17:29, Deesen написал:

**Comment by Fr3ddy7** [comment]
wow)
